### ISSUE TITLE
eureka registry support customize IP

### ISSUE THREAD

**Issue by liuqunqi** [seata/seata#1100]
when i deploy seata on cloud host，can not get real ip
-----------------------------------------------------------------------
2019-05-24 09:21:26.491 WARN [main]io.seata.common.util.NetUtil.getLocalAddress0:155 -Failed to retrieving ip address, ecs-bd21: ecs-bd21: Name or service not known
java.net.UnknownHostException: ecs-bd21: ecs-bd21: Name or service not known
at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
at io.seata.common.util.NetUtil.getLocalAddress0(NetUtil.java:150)
at io.seata.common.util.NetUtil.getLocalAddress(NetUtil.java:142)
at io.seata.common.util.NetUtil.getLocalIp(NetUtil.java:119)
at io.seata.server.Server.main(Server.java:87)
Caused by: java.net.UnknownHostException: ecs-bd21: Name or service not known
at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
... 4 common frames omitted

**Comment by liuqunqi** [comment]
when i deploy seata on cloud host，can not get real ip
-----------------------------
2019-05-24 09:21:26.491 WARN [main]io.seata.common.util.NetUtil.getLocalAddress0:155 -Failed to retrieving ip address, ecs-bd21: ecs-bd21: Name or service not known
java.net.UnknownHostException: ecs-bd21: ecs-bd21: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
	at io.seata.common.util.NetUtil.getLocalAddress0(NetUtil.java:150)
	at io.seata.common.util.NetUtil.getLocalAddress(NetUtil.java:142)
	at io.seata.common.util.NetUtil.getLocalIp(NetUtil.java:119)
	at io.seata.server.Server.main(Server.java:87)
Caused by: java.net.UnknownHostException: ecs-bd21: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
	... 4 common frames omitted

**Comment by xingfudeshi** [comment]
Thanks for reporting.I will check it.

**Comment by xingfudeshi** [comment]
@liuqunqi Hi.It doesn't seem to be seata's problem.Have you tried to modify the hosts file?add the following record on it:
`127.0.0.1 ecs-bd21`
it seems

**Comment by liuqunqi** [comment]
> @liuqunqi Hi.It doesn't seem to be seata's problem.Have you tried to modify the hosts file?add the following record on it:
> `127.0.0.1 ecs-bd21`

 i created  ECS  Instance named “ecs-bd21”，it can not get public ip，so，i hope seata support customize IP or better solution

**Comment by xingfudeshi** [comment]
> > @liuqunqi Hi.It doesn't seem to be seata's problem.Have you tried to modify the hosts file?add the following record on it:
> > `127.0.0.1 ecs-bd21`
> 
> i just created ECS Instance named “ecs-bd21”，then deploy seata，output that message， it can not get public ip，so，i hope seata support customize IP or better solution

custom IP for eureka?

**Comment by liuqunqi** [comment]
> > > @liuqunqi Hi.It doesn't seem to be seata's problem.Have you tried to modify the hosts file?add the following record on it:
> > > `127.0.0.1 ecs-bd21`
> > 
> > 
> > i just created ECS Instance named “ecs-bd21”，then deploy seata，output that message， it can not get public ip，so，i hope seata support customize IP or better solution
> 
> custom IP for eureka?

yes！expose custom IP to the registrar （eureka、zk、redis...）

**Comment by xingfudeshi** [comment]
![image](https://user-images.githubusercontent.com/24457941/58402002-ddb8cd80-8091-11e9-8435-b3d0eb204d30.png)

**Comment by liuqunqi** [comment]
this is eureka  service address not seata service address

**Comment by liuqunqi** [comment]
this is eureka service address not seata application address,i mean custom seata  IP @xingfudeshi

**Comment by xingfudeshi** [comment]
> this is eureka service address not seata application address,i mean custom seata IP @xingfudeshi

OK.i got it.you wanna specific the IP when start seata-server,right?

**Comment by liuqunqi** [comment]
> > this is eureka service address not seata application address,i mean custom seata IP @xingfudeshi
> 
> OK.i got it.you wanna specific the IP when start seata-server,right?

yes
