### ISSUE TITLE
java.lang.IllegalArgumentException: branchSession can be null for memory lockMode

### ISSUE THREAD

**Issue by xianwei** [seata/seata#1211]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
I have a 'for update' sql in the transaction, then I got the exception:
java.lang.IllegalArgumentException: branchSession can be null for memory lockMode

### Ⅱ. Describe what happened
```
lockKey:elc_order:66274
java.lang.IllegalArgumentException: branchSession can be null for memory lockMode.
	at io.seata.server.lock.LockerFactory.get(LockerFactory.java:102)
	at io.seata.server.lock.DefaultLockManager.getLocker(DefaultLockManager.java:100)
	at io.seata.server.lock.DefaultLockManager.getLocker(DefaultLockManager.java:90)
	at io.seata.server.lock.DefaultLockManager.isLockable(DefaultLockManager.java:72)
	at io.seata.server.coordinator.DefaultCore.lockQuery(DefaultCore.java:110)
	at io.seata.server.coordinator.DefaultCoordinator.doLockCheck(DefaultCoordinator.java:186)
	at io.seata.server.AbstractTCInboundHandler$6.execute(AbstractTCInboundHandler.java:196)
	at io.seata.server.AbstractTCInboundHandler$6.execute(AbstractTCInboundHandler.java:192)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:113)
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:192)
	at io.seata.core.protocol.transaction.GlobalLockQueryRequest.handle(GlobalLockQueryRequest.java:35)
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:418)
	at io.seata.core.rpc.DefaultServerMessageListenerImpl.onTrxMessage(DefaultServerMessageListenerImpl.java:85)
	at io.seata.core.rpc.netty.RpcServer.dispatch(RpcServer.java:253)
	at io.seata.core.rpc.netty.AbstractRpcRemoting$3.run(AbstractRpcRemoting.java:356)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

### Ⅲ. Describe what you expected to happen
I need a common way to handle it.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. add @GlobalTransaction
2. add 'for update" sql, like : select * from order where id = 1 for update

### Ⅵ. Environment:

- JDK version : java version "1.8.0_151" 
                        Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
- OS : CentOS Linux release 7.3.1611 (Core)
- Others: MySQL5.6.43-log

**Comment by xianwei** [comment]
![image](https://user-images.githubusercontent.com/3487614/59590086-dda26f80-911d-11e9-89e5-a44431691d56.png)
![image](https://user-images.githubusercontent.com/3487614/59590126-f1e66c80-911d-11e9-8533-65a05cd2813e.png)

**Comment by xianwei** [comment]
Does it mean 'select for update statement must be db mode'?

**Comment by xianwei** [comment]
I think it's same with the issue #1153.
