### ISSUE TITLE
spring boot can not start integrate with seata

### ISSUE THREAD

**Issue by lmzhizhe** [seata/seata#1240]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
spring boot can not start with seata,please read the error info.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.[0;39m 
[ ] [main] [34mINFO [0;39m [36mo.a.d.s.b.c.e.AwaitingNonWebApplicationListener[0;39m - [34m [Dubbo] Current Spring Boot Application is about to shutdown...[0;39m 
[ ] [main] [1;31mERROR[0;39m [36mo.s.b.SpringApplication[0;39m - [1;31mApplication run failed[0;39m 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'globalTransactionScanner' defined in class path resource [com/vivo/it/test1/config/SeataAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is io.seata.common.exception.NotSupportYetException: not support register type: null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:625)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:228)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:707)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.vivo.it.test1.TestDubboService1Application.main(TestDubboService1Application.java:37)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is io.seata.common.exception.NotSupportYetException: not support register type: null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:620)
	... 19 common frames omitted
Caused by: io.seata.common.exception.NotSupportYetException: not support register type: null
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:80)
	at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:65)
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:81)
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:124)
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:113)
	at com.vivo.it.test1.config.SeataAutoConfig.globalTransactionScanner(SeataAutoConfig.java:44)
	at com.vivo.it.test1.config.SeataAutoConfig$$EnhancerBySpringCGLIB$$6687f6de.CGLIB$globalTransactionScanner$0(<generated>)
	at com.vivo.it.test1.config.SeataAutoConfig$$EnhancerBySpringCGLIB$$6687f6de$$FastClassBySpringCGLIB$$e469024b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.vivo.it.test1.config.SeataAutoConfig$$EnhancerBySpringCGLIB$$6687f6de.globalTransactionScanner(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 20 common frames omitted
Caused by: java.lang.IllegalArgumentException: illegal type:null
	at io.seata.config.ConfigType.getType(ConfigType.java:62)
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:78)
	... 35 common frames omitted



```

### Ⅲ. Describe what you expected to happen

spring boot started success!

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

no

### Ⅴ. Anything else we need to know?

no
### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows 10
- Others: no

**Comment by xingfudeshi** [comment]
Do you have file. conf and registry. conf files in the resources directory? Please paste your file. conf and registry. conf contents.

**Comment by lmzhizhe** [comment]
please watch the attach pirture！

**Comment by lmzhizhe** [comment]
![21](https://user-images.githubusercontent.com/5087276/60088224-ed026800-9770-11e9-8ad9-7e0de209d7c2.gif)

**Comment by lmzhizhe** [comment]
`transport {
  # tcp udt unix-domain-socket
  type = "TCP"
  #NIO NATIVE
  server = "NIO"
  #enable heartbeat
  heartbeat = true
  #thread factory for netty
  thread-factory {
    boss-thread-prefix = "NettyBoss"
    worker-thread-prefix = "NettyServerNIOWorker"
    server-executor-thread-prefix = "NettyServerBizHandler"
    share-boss-worker = false
    client-selector-thread-prefix = "NettyClientSelector"
    client-selector-thread-size = 1
    client-worker-thread-prefix = "NettyClientWorkerThread"
    # netty boss thread size,will not be used for UDT
    boss-thread-size = 1
    #auto default pin or 8
    worker-thread-size = 8
  }
}

service {
  #vgroup->rgroup
  vgroup_mapping.my_test_tx_group = "default"
  #only support single node
  default.grouplist = "172.20.227.159:8091"
  #degrade current not support
  enableDegrade = false
  #disable
  disable = false
}

client {
  async.commit.buffer.limit = 10000
  lock {
    retry.internal = 10
    retry.times = 30
  }
}


## transaction log store
store {
  ## store mode: file、db
  mode = "file"

  ## file store
  file {
    dir = "file_store/dubbo"

    # branch session size , if exceeded first try compress lockkey, still exceeded throws exceptions
    max-branch-session-size = 16384
    # globe session size , if exceeded throws exceptions
    max-global-session-size = 512
    # file buffer size , if exceeded allocate new buffer
    file-write-buffer-cache-size = 16384
    # when recover batch read size
    session.reload.read_size = 100
  }
}

`

**Comment by lmzhizhe** [comment]
> Do you have file. conf and registry. conf files in the resources directory? Please paste your file. conf and registry. conf contents.

please read the attach file
[file.txt](https://github.com/seata/seata/files/3324643/file.txt)
[registry.txt](https://github.com/seata/seata/files/3324644/registry.txt)

**Comment by lmzhizhe** [comment]
> Do you have file. conf and registry. conf files in the resources directory? Please paste your file. conf and registry. conf contents.

My applicaiton used apollo config server,it is incompatible with seata?

**Comment by xingfudeshi** [comment]
From these exceptions,the problem may caused by here:
![image](https://user-images.githubusercontent.com/24457941/60143795-832aa280-97f2-11e9-963e-f20278990645.png)
the value of config->type is not correctly readed.Please check.

**Comment by lmzhizhe** [comment]
> From these exceptions,the problem may caused by here:
> ![image](https://user-images.githubusercontent.com/24457941/60143795-832aa280-97f2-11e9-963e-f20278990645.png)
> the value of config->type is not correctly readed.Please check.

registry.conf 和 file.conf 我是从 demo里面拷贝出来的，为什么没有读取正确？这两个文件 resource里面都有的啊

**Comment by lmzhizhe** [comment]
`
    public FileConfiguration(String name) {
        if (null == name) {
            CONFIG = ConfigFactory.load();
        } else {
            CONFIG = ConfigFactory.load(name);
        }
        configOperateExecutor = new ThreadPoolExecutor(CORE_CONFIG_OPERATE_THREAD, MAX_CONFIG_OPERATE_THREAD,
            Integer.MAX_VALUE, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>(),
            new NamedThreadFactory("configOperate", MAX_CONFIG_OPERATE_THREAD));
        configChangeExecutor = new ThreadPoolExecutor(CORE_CONFIG_CHANGE_THREAD, CORE_CONFIG_CHANGE_THREAD,
            Integer.MAX_VALUE, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>(),
            new NamedThreadFactory("configChange", CORE_CONFIG_CHANGE_THREAD));
        configChangeExecutor.submit(new ConfigChangeRunnable());
    }
`
我debug 发现这个地方 初始化 了两次，第一次 初始化是从registry.conf里面读取拿到了配置，第二次就没有了，这个是什么原因？

**Comment by xingfudeshi** [comment]
i will check.

**Comment by lmzhizhe** [comment]
> i will check.

我启动的时候，我没有配置seataConfigEnv，为什么默认 是找到 dev.cfg 文件,问题已经找到 增加dev 文件就可以了
