### ISSUE TITLE
error happened when integrate with nacos

### ISSUE THREAD

**Issue by lmzhizhe** [seata/seata#1255]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

error happened when integrate with nacos，can not started
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'globalTransactionScanner' defined in class path resource [com/vivo/it/boot/framework/config/DataSourceConfigure.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.config.ConfigurationProvider[Nacos] and classloader : sun.misc.Launcher$AppClassLoader@73d16e93
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:625)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:228)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:707)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.vivo.it.test1.TestDubboService1Application.main(TestDubboService1Application.java:39)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.config.ConfigurationProvider[Nacos] and classloader : sun.misc.Launcher$AppClassLoader@73d16e93
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:620)
	... 19 common frames omitted
Caused by: io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.config.ConfigurationProvider[Nacos] and classloader : sun.misc.Launcher$AppClassLoader@73d16e93


```

```
registry {
  # file 、nacos 、eureka、redis、zk
  type = "nacos"
  
  nacos {
    serverAddr = "172.20.226.105,172.20.226.106,172.20.226.107"
    namespace = "public"
    cluster = "default"
  }
  eureka {
    serviceUrl = "http://localhost:1001/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = "0"
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk
  type = "nacos"
  
  nacos {
    serverAddr = "172.20.226.105,172.20.226.106,172.20.226.107"
    namespace = "public"
    cluster = "default"
  }
  apollo {
    app.id = "fescar-server"
    apollo.meta = "http://192.168.1.204:8801"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  file {
    name = "file.conf"
  }
}
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. can not started when integrate with nacos
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : centos7
- Others:

**Comment by lmzhizhe** [comment]
resolved，need add nacos dependency。

**Comment by slievrly** [comment]
@lmzhizhe great.

**Comment by juaihua** [comment]
> resolved，need add nacos dependency。

hi, bro , i met the same problem , can you teel me what dependency exactly?  thanks .

**Comment by lmzhizhe** [comment]
> > resolved，need add nacos dependency。
> 
> hi, bro , i met the same problem , can you teel me what dependency exactly? thanks .

I forgot，maybe you can watch the variables ：seataEnv  and  group config
