### ISSUE TITLE
io.seata.core.exception.TransactionException: RPC Timeout

### ISSUE THREAD

**Issue by sun6hua** [seata/seata#1282]
System environment：Jdk 1.8 , centos7 ,springcloud ,seata-server 0.6.1
Is it seata-server select after adding for update ---select *** for update causes too many locked keys，then timeout ?
The following is the exception information：

2019-07-10 00:01:00.415 ERROR 20333 --- [nio-9026-exec-6] i.s.core.rpc.netty.AbstractRpcRemoting   : wait response error:cost 30001 ms,ip:172.31.176.17:8091,request:xid=172.31.176.17:8091:2013495478,branchType=AT,resourceId=jdbc:mysql://mysql.rds.aliyuncs.com:3306/lmt-pro?useUnicode=true&serverTimezone=Hongkong&useSSL=false,lockKey=qp_shop:48,90,117,119,120,122,128,134,135,147,152,159,160,169,172,173,174,175,176,177,179,180,183,188,204,206,209,210,220,225,230,237,238,240,246,249,250,251,252,256,263,266,267,268,277,284,285,297,299,301,303,305,306,307,309,312,313,314,315,317,318,319,320,321,322,324,325,326,327,328,329,330,331,332,334,335,336,337,338,340,341,343,345,346,347,348,349,351,354,355,356,358,359,360,362,363,365,366,368,369,371,372,373,375,376,378,380,381,382,383,384,385,387,388,389,390,391,392,394,396,398,399,400,402,403,405,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,428,430,432,439,441,443,445,446,447,450,451,452,453,454,455,456,458,459,460,461,462,463,464,465,466,472,474,475,476,477,478,479,480,481,490,493,496,497,499,500,501,502,503,505,508,510,513,515,519
2019-07-10 00:01:00.523  INFO 20333 --- [nio-9026-exec-6] i.seata.tm.api.DefaultGlobalTransaction  : [172.31.176.17:8091:2013495478] rollback status:Rollbacked
2019-07-10 00:01:00.536 ERROR 20333 --- [nio-9026-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: 
### Cause: java.sql.SQLException: io.seata.core.exception.TransactionException: RPC Timeout
; uncategorized SQLException; SQL state [null]; error code [0]; io.seata.core.exception.TransactionException: RPC Timeout; nested exception is java.sql.SQLException: io.seata.core.exception.TransactionException: RPC Timeout] with root cause

java.util.concurrent.TimeoutException: cost 30001 ms
	at io.seata.core.protocol.MessageFuture.get(MessageFuture.java:64) ~[seata-core-0.6.1.jar!/:na]
	at io.seata.core.rpc.netty.AbstractRpcRemoting.sendAsyncRequest(AbstractRpcRemoting.java:260) ~[seata-core-0.6.1.jar!/:na]
	at io.seata.core.rpc.netty.AbstractRpcRemoting.sendAsyncRequestWithResponse(AbstractRpcRemoting.java:190) ~[seata-core-0.6.1.jar!/:na]
	at io.seata.core.rpc.netty.RmRpcClient.sendMsgWithResponse(RmRpcClient.java:197) ~[seata-core-0.6.1.jar!/:na]
	at io.seata.core.rpc.netty.RmRpcClient.sendMsgWithResponse(RmRpcClient.java:207) ~[seata-core-0.6.1.jar!/:na]
	at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:66) ~[seata-rm-0.6.1.jar!/:na]
	at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96) ~[seata-rm-0.6.1.jar!/:na]
	at io.seata.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:198) ~[seata-rm-datasource-0.6.1.jar!/:na]
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:177) ~[seata-rm-datasource-0.6.1.jar!/:na]
	at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:156) ~[seata-rm-datasource-0.6.1.jar!/:na]
	at io.seata.rm.datasource.ConnectionProxy.setAutoCommit(ConnectionProxy.java:218) ~[seata-rm-datasource-0.6.1.jar!/:na]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:107) ~[seata-rm-datasource-0.6.1.jar!/:na]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:57) ~[seata-rm-datasource-0.6.1.jar!/:na]
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:86) ~[seata-rm-datasource-0.6.1.jar!/:na]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:101) ~[seata-rm-datasource-0.6.1.jar!/:na]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:47) ~[seata-rm-datasource-0.6.1.jar!/:na]
	at io.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:63) ~[seata-rm-datasource-0.6.1.jar!/:na]

**Comment by slievrly** [comment]
#1148 resolved

**Comment by sun6hua** [comment]
OK  ，Thank You
