### ISSUE TITLE
Latest relase 0.7.0 can not work

### ISSUE THREAD

**Issue by sunnycamel** [seata/seata#1295]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
just run seata server with default config, the server just not work

### Ⅱ. Describe what happened

2019-07-13 11:00:02.622 ERROR[NettyServerNIOWorker_2_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:424 -0318
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 2415945472 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430)
        at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:75)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)

### Ⅵ. Environment:

- JDK version : 1.8
- OS : mac osx
- Others:

**Comment by sunnycamel** [comment]
这个项目让我非常失望，媒体上报道得轰轰烈烈，实际上一个简单的demo都很长时间跑不过去。如果是我不会使用造成的问题，但是我也确实没有看到一个像样的文档，来说怎么使用。

**Comment by zjinlei** [comment]
还在快速迭代中，可以加官方钉钉群一起参与进来
0.7昨天刚发版，修改了协议，demo是基于0.6.1的，待更新

**Comment by slievrly** [comment]
@sunnycamel please use the 0.7.0 seata-all and seata-server.

**Comment by majiajue** [comment]
0.7.1 
默认配置 
seata-server 
同样有这个问题
@zjinlei 
```
2019-07-16 17:13:37.832 INFO [NettyServerNIOWorker_8_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:212 -will destroy channel:[id: 0x7f3e6c57, L:/10.255.1.11:8091 - R:/10.255.0.2:51514],address:10.255.0.2:51514


2019-07-16 17:13:37.832 INFO [NettyServerNIOWorker_8_8]io.seata.core.rpc.netty.AbstractRpcRemoting.close:445 -ChannelHandlerContext(RpcServer#0, [id: 0x7f3e6c57, L:/10.255.1.11:8091 - R:/10.255.0.2:51514]) will closed


2019-07-16 17:13:37.833 INFO [NettyServerNIOWorker_8_8]io.seata.core.rpc.netty.AbstractRpcRemoting.close:445 -ChannelHandlerContext(RpcServer#0, [id: 0x7f3e6c57, L:/10.255.1.11:8091 ! R:/10.255.0.2:51514]) will closed


2019-07-16 17:13:37.833 INFO [NettyServerNIOWorker_8_8]io.seata.core.rpc.netty.RpcServer.handleDisconnect:286 -10.255.0.2:51514 to server channel inactive.


2019-07-16 17:13:37.833 INFO [NettyServerNIOWorker_8_8]io.seata.core.rpc.netty.RpcServer.handleDisconnect:295 -remove unused channel:[id: 0x7f3e6c57, L:/10.255.1.11:8091 ! R:/10.255.0.2:51514]


2019-07-16 17:13:37.833 INFO [NettyServerNIOWorker_2_8]io.seata.core.rpc.netty.RpcServer.exceptionCaught:334 -channel exx:Adjusted frame length exceeds 8388608: 2415945472 - discarded,channel:[id: 0x50155067, L:/10.255.1.11:8091 - R:/10.255.0.2:54110]


2019-07-16 17:13:37.834 ERROR[NettyServerNIOWorker_2_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:424 -0318


io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 2415945472 - discarded


	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522)


	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500)


	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387)


	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430)


	at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:75)


	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)


	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)


	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)


	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)


	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)


	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)


	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)


	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)


	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)


	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)


	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)


	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)


	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)


	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)


	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)


	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)


	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)


	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)


	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)


	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)


	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)


	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)


	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zjinlei** [comment]
0.7.1已经修复这个问题，请确认下服务端和客户端是否都是0.7.1以及是否存在多版本导致打包版本不对导致。

**Comment by shadowedge** [comment]
> 
> 
> 0.7.1已经修复这个问题，请确认下服务端和客户端是否都是0.7.1以及是否存在多版本导致打包版本不对。

样例工程里的 springcloud-jpa-seata 目前用的seata是0.6.1版本，无法连接0.7.1 server。但给seata版本升级到0.7.1后，还是无法连接，仍然报错 io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 2415944960 - discarded

**Comment by yub1ng** [comment]
这是我遇到的情况以及解决方法：https://www.jianshu.com/p/b11ac0d1bde4

**Comment by liuqi111** [comment]
> 0.7.1已经修复这个问题，请确认下服务端和客户端是否都是0.7.1以及是否存在多版本导致打包版本不对。

springcloud-eureka-seata 在确认服务端与客户端到最新版本0.7.1后，也仍然报错，
2019-07-22 01:19:04.582 ERROR[NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:424 -0318
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 2415945472 - discarded

**Comment by bao17634** [comment]
有没有能跑的demo，官方的demo都跑不起来

**Comment by zjinlei** [comment]
@bao17634 demo is work well
please join dingding group 23171167 to describe your situation in detail

**Comment by jianghu-coding** [comment]
我之前也遇到过这个问题，发现是 seata-server 运行的版本和代码里面引入的 seata 不一致，改成一致后，就不会存在这个问题了

**Comment by Daiqiangdeveloper** [comment]
我都1.1.0   还有这个破错误  跑个demo都各种问题

**Comment by Nobodylesszb** [comment]
1.2版本也有这个问题，启动服务什么没干就出现这个错误

**Comment by guxq** [comment]
同问：1.2版本也有这个问题，启动服务什么没干就出现这个错误
