### ISSUE TITLE
0.7.1 start seata-server.sh file storeMode= db is invalid

### ISSUE THREAD

**Issue by lomo-dcm** [seata/seata#1310]
Start parameter forcing  -m db   otherwise  default memory mode

直接用默认参数覆盖配置文件中的参数了，参数生效优先级没处理好，seata-server会产生sessionStore文件
导致global_table  branch_table表都没有数据，但是也能正常回滚，这2张表数据应该直接走内存方式了

**Comment by lomo-dcm** [comment]
直接用默认参数覆盖配置文件中的参数了，参数生效优先级没处理好

**Comment by wudgaby** [comment]
0.6.1 我开启db模式的时候 为什么无法获取全局事务
报的异常是
`Begin new global transaction [null]

java.lang.IllegalStateException

at io.seata.tm.api.DefaultGlobalTransaction.rollback(DefaultGlobalTransaction.java:138)`


0.7.1有个坑在undo_log表 多加了一个字段context. 在UndoLogManager类中可以看到.

**Comment by slievrly** [comment]
@wudgaby Is the function of version 0.7.1 ok?

**Comment by wudgaby** [comment]
经过不断试错. 可以了. 
用的seata-samples/springcloud-jpa-seata 测试 
环境 
seata-all 0.7.1  
seata server 0.7.1  
spring-cloud-alibaba-seata 0.9.1.BUILD-SNAPSHOT


把transaction_service_group改长一点 就不会有以下异常.

Seata-server报异常
`io.seata.common.exception.StoreException: Data truncation: Data too long for column 'transaction_service_group' at row 1
        at io.seata.core.store.db.LogStoreDataBaseDAO.insertGlobalTransactionDO(LogStoreDataBaseDAO.java:255)
        at io.seata.server.store.db.DatabaseTransactionStoreManager.writeSession(DatabaseTransactionStoreManager.java:107)
        at io.seata.server.session.db.DataBaseSessionManager.addGlobalSession(DataBaseSessionManager.java:87)`

**Comment by vikenlove** [comment]
@wudgaby  i was commit a pr for undo_log.sql file .
