### ISSUE TITLE
java.nio.BufferOverflowException: null  java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189)

### ISSUE THREAD

**Issue by lomo-dcm** [seata/seata#1336]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

分支事务向tc注册的时候报出来的， 由于分支提交20条行记录，lockKey的值，转成byte 会出现如上问题。

### Ⅰ. Issue Description
java.nio.BufferOverflowException: null
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189)
	at java.nio.ByteBuffer.put(ByteBuffer.java:859)
	at io.seata.codec.seata.protocol.transaction.BranchRegisterRequestCodec.encode(BranchRegisterRequestCodec.java:82)
	at io.seata.codec.seata.protocol.MergedWarpMessageCodec.encode(MergedWarpMessageCodec.java:55)
	at io.seata.codec.seata.SeataCodec.encode(SeataCodec.java:46)
	at io.seata.core.rpc.netty.v1.ProtocolV1Encoder.encode(ProtocolV1Encoder.java:93)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1104)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1151)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1075)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by lomo-dcm** [comment]
lockKey的值过大的时候，转成byte  会出现如上问题。

**Comment by lomo-dcm** [comment]
分支事务向tc注册的时候报出来的

**Comment by cmonkey** [comment]
能使用develop 分支测试一下吗?
在对lockKey 的长度扩展到7000字节，执行BranchRegisterRequestCodecTest无法重新此问题

**Comment by sun6hua** [comment]
我的代码在运行过程中，lockKey 长度到 1770 字节时候就会出现
[lector_RMROLE_1] i.s.core.rpc.netty.v1.ProtocolV1Encoder  : Encode request error!
java.nio.BufferOverflowException: null，
然后事务全部回滚，出现异常信息：
[Request processing failed; nested exception is org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is java.sql.SQLException: io.seata.core.exception.TransactionException: RPC Timeout] with root cause
java.util.concurrent.TimeoutException: cost 30000 ms
@cmonkey

**Comment by lomo-dcm** [comment]
> 能使用develop 分支测试一下吗?
> 在对lockKey 的长度扩展到7000字节，执行BranchRegisterRequestCodecTest无法重新此问题

公司的项目集成的， 记录如果是20条， lockkey  少点 就成功了

**Comment by lomo-dcm** [comment]
> 我的代码在运行过程中，lockKey 长度到 1770 字节时候就会出现
> [lector_RMROLE_1] i.s.core.rpc.netty.v1.ProtocolV1Encoder : Encode request error!
> java.nio.BufferOverflowException: null，
> 然后事务全部回滚，出现异常信息：
> [Request processing failed; nested exception is org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is java.sql.SQLException: io.seata.core.exception.TransactionException: RPC Timeout] with root cause
> java.util.concurrent.TimeoutException: cost 30000 ms
> Environment：springcloud，seata-server0.7.1
> @cmonkey

你这个问题 应该跟我不一样，https://github.com/seata/seata/pull/1333/files 你这个修复过了 你看看

**Comment by sun6hua** [comment]
谢谢，你说的这个内存泄漏的问题，确实存在。不过我的问题感觉和你的一样，分支提交update 300多行记录，lockKey的值过大导致这个问题，试了一下update80多条数据，不会出现异常。但是这个问题需要解决，业务每次update多少条数据不确定

**Comment by slievrly** [comment]
@lomo-dcm I will fix this problem.

**Comment by lomo-dcm** [comment]
> @lomo-dcm I will fix this problem.

感谢大佬救命
