### ISSUE TITLE
TM should check XID in phase of beginning

### ISSUE THREAD

**Issue by VainEffort** [seata/seata#1349]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

In phase of beginning a global transaction, TM may get null XID and continues to execute which causes all branch transaction running without distributed transaction context.

### Ⅱ. Describe what happened

  I throw a new RuntimeException in TC's DefaultCore.begin(), the global transaction executes in an illegal status.

```

TC's log, I throw a RuntimeException:

2019-07-25 10:55:37.084 ERROR[ServerHandlerThread_3_500]io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate:123 -Catch RuntimeException while do RPC, request: timeout=600000,transactionName=createUser(com.ifc.basic.demo.api.dto.CreateUserRequest)

java.lang.RuntimeException: null

    at io.seata.server.coordinator.DefaultCore.begin(DefaultCore.java:134)

    at io.seata.server.coordinator.DefaultCoordinator.doGlobalBegin(DefaultCoordinator.java:146)

    at io.seata.server.AbstractTCInboundHandler$1.execute(AbstractTCInboundHandler.java:53)

    at io.seata.server.AbstractTCInboundHandler$1.execute(AbstractTCInboundHandler.java:1)

    at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:117)

    at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:50)

    at io.seata.core.protocol.transaction.GlobalBeginRequest.handle(GlobalBeginRequest.java:77)

    at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:430)

    at io.seata.core.rpc.DefaultServerMessageListenerImpl.onTrxMessage(DefaultServerMessageListenerImpl.java:87)

    at io.seata.core.rpc.netty.RpcServer.dispatch(RpcServer.java:252)

    at io.seata.core.rpc.netty.AbstractRpcRemoting$3.run(AbstractRpcRemoting.java:371)

    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

    at java.lang.Thread.run(Thread.java:748)







TM's log, which XID == null

[dd98182a13946294,dd98182a13946294,true] 2019-07-25T10:55:36,998 INFO io.seata.tm.TransactionManagerHolder : TransactionManager Singleton io.seata.tm.DefaultTransactionManager@54098572

[dd98182a13946294,dd98182a13946294,true] 2019-07-25T10:55:37,017 INFO io.seata.common.loader.EnhancedServiceLoader : load LoadBalance[null] extension by class[io.seata.discovery.loadbalance.RandomLoadBalance]

[dd98182a13946294,dd98182a13946294,true] 2019-07-25T10:55:37,095 ERROR io.seata.core.rpc.netty.AbstractRpcRemotingClient : begin response error,release channel:[id: 0x87b7fa04]

[dd98182a13946294,dd98182a13946294,true] 2019-07-25T10:55:37,095 INFO io.seata.core.rpc.netty.NettyClientChannelManager : return to pool, rm channel:[id: 0x87b7fa04,]

[dd98182a13946294,dd98182a13946294,true] 2019-07-25T10:55:37,095 INFO io.seata.tm.api.DefaultGlobalTransaction : Begin new global transaction [null]

[dd98182a13946294,dd98182a13946294,true] 2019-07-25T10:55:38,158 ERROR team.scf.frame.base.controller.advice.CommonExceptionAdvice : 

java.lang.IllegalStateException: null

    at io.seata.tm.api.DefaultGlobalTransaction.commit(DefaultGlobalTransaction.java:113) ~[classes[]]

    at io.seata.tm.api.TransactionalTemplate.commitTransaction(TransactionalTemplate.java:103) ~[classes[]]

    at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:74) ~[classes[]]

    at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:101) ~[classes[]]

    at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:76) ~[classes[]]

    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]

    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]

    at com.ifc.basic.demo.biz.foo.service.FooServiceImpl$$EnhancerBySpringCGLIB$$8c1fff81.createUser(<generated>) ~[classes[]]

    at com.ifc.basic.demo.biz.foo.controller.FooController.createUser(FooController.java:55) ~[classes[]]

    at com.ifc.basic.demo.biz.foo.controller.FooController$$FastClassBySpringCGLIB$$add10ca9.invoke(<generated>) ~

...

```

### Ⅲ. Describe what you expected to happen

All branch transaction ran without distributed transaction context for XID == null, and can't be commit or rollback for not registering to TC.

TM should check XID, and stop this kind of illegal status transaction to go on.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. uses serialization = "SEATA", PROTOBUF mode checks null XID to prevent response back to TM.

2. make seata server fail to process TM's begin request

### Ⅵ. Environment:

- JDK version : JDK1.8

- OS : windows

- Others: seata 0.7.1

**Comment by VainEffort** [comment]
why tm releases the channel when getting GlobalBeginResponse which resultCode=failed?

**Comment by slievrly** [comment]
@VainEffort thank you, i will fix it.
