### ISSUE TITLE
io.seata.core.exception.TransactionException: null.   DefaultCore.lambda$branchRegister$0(DefaultCore.java:79)

### ISSUE THREAD

**Issue by lomo-dcm** [seata/seata#1361]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata0.7.1版本，eureka注册中心， db模式
集群模式的seata-server进行压测就会出现如下错误：(单机模式没问题)
seta-server 端的报错：
io.seata.core.exception.TransactionException: null
at io.seata.server.coordinator.DefaultCore.lambda$branchRegister$0(DefaultCore.java:79)
at io.seata.server.session.GlobalSession.lockAndExcute(GlobalSession.java:594)
at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:66)
at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:174)
at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:148)
at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:144)
at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:117)
at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:144)
at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:430)
at io.seata.core.rpc.DefaultServerMessageListenerImpl.onTrxMessage(DefaultServerMessageListenerImpl.java:87)
at io.seata.core.rpc.netty.RpcServer.dispatch(RpcServer.java:252)
at io.seata.core.rpc.netty.AbstractRpcRemoting$3.run(AbstractRpcRemoting.java:371)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

seta-server 端的报错：
io.seata.core.exception.TransactionException: null
at io.seata.server.coordinator.DefaultCore.lambda$branchRegister$0(DefaultCore.java:79)
at io.seata.server.session.GlobalSession.lockAndExcute(GlobalSession.java:594)
at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:66)
at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:174)
at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:148)
at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:144)
at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:117)
at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:144)
at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:430)
at io.seata.core.rpc.DefaultServerMessageListenerImpl.onTrxMessage(DefaultServerMessageListenerImpl.java:87)
at io.seata.core.rpc.netty.RpcServer.dispatch(RpcServer.java:252)
at io.seata.core.rpc.netty.AbstractRpcRemoting$3.run(AbstractRpcRemoting.java:371)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by lomo-dcm** [comment]
跟这个问题差不多https://github.com/seata/seata/issues/1324
但是没有解决方案

**Comment by cmonkey** [comment]
有能复现的demo吗?
