### ISSUE TITLE
io.seata.core.exception.TransactionException: null

### ISSUE THREAD

**Issue by hunter7727** [seata/seata#1373]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
环境配置：
   seata-server     1台服务器 配置为db模式
   seata-server启动命令 ： sh seata-server.sh -p 8091 -m db
   file.conf配置文件中的store.mode=“file”
  demo用的是springcloud-eureka-seata
  postman请求连接：localhost:8084/purchase/commit

### Ⅱ. Describe what happened

调用第一次是正常的，以后每次调用都会报这个错误

2019-08-01 09:08:53.038 INFO [ServerHandlerThread_45_500]io.seata.core.lock.AbstractLocker.acquireLock:112 -Global lock on [storage_tbl:9] is holding by 2018349446
2019-08-01 09:08:53.043 ERROR[ServerHandlerThread_45_500]io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate:120 -Catch TransactionException while do RPC, request: xid=192.168.56.101:8091:2018349457,branchType=AT,resourceId=jdbc:mysql://129.28.184.196:3306/eureka,lockKey=storage_tbl:9
io.seata.core.exception.TransactionException: null
        at io.seata.server.coordinator.DefaultCore.lambda$branchRegister$0(DefaultCore.java:79)
        at io.seata.server.session.GlobalSession.lockAndExcute(GlobalSession.java:594)
        at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:66)
        at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:174)
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:148)
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:144)
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:117)
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:144)
        at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:430)
        at io.seata.core.rpc.DefaultServerMessageListenerImpl.onTrxMessage(DefaultServerMessageListenerImpl.java:87)
        at io.seata.core.rpc.netty.RpcServer.dispatch(RpcServer.java:252)
        at io.seata.core.rpc.netty.AbstractRpcRemoting$3.run(AbstractRpcRemoting.java:371)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
2019-08-01 09:08:53.658 INFO [batchLoggerPrint_1]io.seata.core.rpc.DefaultServerMessageListenerImpl.run:199 -SeataMergeMessage xid=192.168.56.101:8091:2018349457,extraData=null
,clientIp:192.168.56.1,vgroup:my_test_tx_group

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zjinlei** [comment]
please changed store.mode=“db”

**Comment by hunter7727** [comment]
yes,Yes, changed to ' store.mode=“db” ' is ok.
