### ISSUE TITLE
Start Seata Server error

### ISSUE THREAD

**Issue by lindengCm** [seata/seata#1399]
Ⅰ. Issue Description
启动Seata Server报错

Ⅱ. Describe what happened
直接运行io.seata.server.Server类下的main方法，抛出异常
2019-08-05 09:53:29.589 INFO [RetryRollbacking_1]io.seata.core.rpc.ChannelManager.getChannel:338 -No channel is available for resource[jdbc:mysql://localhost:3306/fescar]
2019-08-05 09:53:29.594 ERROR[RetryRollbacking_1]io.seata.server.coordinator.DefaultCore.doGlobalRollback:324 -Exception rollbacking branch BR:2018652798/2018652795
java.lang.RuntimeException: rm client is not connected. dbkey:jdbc:mysql://localhost:3306/fescar,clientId:dubbo-demo-order-service:127.0.0.1:56049
	at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:216)
	at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:235)
	at io.seata.server.coordinator.DefaultCoordinator.branchRollback(DefaultCoordinator.java:240)
	at io.seata.server.coordinator.DefaultCore.doGlobalRollback(DefaultCore.java:301)
	at io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking(DefaultCoordinator.java:318)
	at io.seata.server.coordinator.DefaultCoordinator.lambda$init$1(DefaultCoordinator.java:391)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
数据库配置是正确的

Ⅲ. Environment:

- JDK version : 1.8
- OS : win 10
- Others:

**Comment by zjinlei** [comment]
At startup, it reads the previously unfinished global transaction and continues to execute. This log is a rollback retry, You can see the reason for the rollback failure of the corresponding branch transaction.
Generally mirror error, you can debug DataCompareUtils.isRecordsEquals
