### ISSUE TITLE
seata release 0.8.0 illegal type:null

### ISSUE THREAD

**Issue by CengSin** [seata/seata#1528]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

当系统环境变量中没有`SEATA_CONFIG_ENV=default`的时候，会报以下错误。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'globalTransactionScanner' defined in class path resource [cn/notcallme/web/config/SeataAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is io.seata.common.exception.NotSupportYetException: not support register type: null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:228) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:721) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:534) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at cn.notcallme.web.WebApplication.main(WebApplication.java:12) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is io.seata.common.exception.NotSupportYetException: not support register type: null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	... 19 common frames omitted
Caused by: io.seata.common.exception.NotSupportYetException: not support register type: null
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:84) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:68) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:81) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:124) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:113) ~[seata-all-0.8.0.jar:0.8.0]
	at cn.notcallme.web.config.SeataAutoConfig.globalTransactionScanner(SeataAutoConfig.java:22) ~[classes/:na]
	at cn.notcallme.web.config.SeataAutoConfig$$EnhancerBySpringCGLIB$$1c6f1a68.CGLIB$globalTransactionScanner$0(<generated>) ~[classes/:na]
	at cn.notcallme.web.config.SeataAutoConfig$$EnhancerBySpringCGLIB$$1c6f1a68$$FastClassBySpringCGLIB$$36a86aca.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at cn.notcallme.web.config.SeataAutoConfig$$EnhancerBySpringCGLIB$$1c6f1a68.globalTransactionScanner(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_211]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	... 20 common frames omitted
Caused by: java.lang.IllegalArgumentException: illegal type:null
	at io.seata.config.ConfigType.getType(ConfigType.java:62) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:82) ~[seata-all-0.8.0.jar:0.8.0]
	... 35 common frames omitted
```

### Ⅲ. Describe what you expected to happen

不需要手动设置系统变量，或者在quick start中写清楚需要配置环境变量。不过在代码中我看到if中的判断逻辑有问题。按照seata的思路来说，应该是不需要配置系统环境变量的。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 删除系统变量中的SEATA_CONFIG_ENV
2. 稍等一两分钟
3. 重启使用0.8.0版本的seata的项目

### Ⅴ. Anything else we need to know?

`ConfigurationFactory.java`中这段代码好像有些问题

```java
    static {
        String env = System.getenv(ENV_SYSTEM_KEY);
        if (env != null && System.getProperty(ENV_PROPERTY_KEY) == null) {
            //Help users get
            System.setProperty(ENV_PROPERTY_KEY, env);
        }
        envValue = System.getProperty(ENV_PROPERTY_KEY);
    }
```

### Ⅵ. Environment:

- JDK version : 1.8
- OS : Windows10
- Others: Intellij iDEA

**Comment by cmonkey** [comment]
SEATA_CONFIG_ENV本身默认可以看做等于DEFAULT_ENV_VALUE, 所以是否参数给的不正确

**Comment by CengSin** [comment]
我在代码中报错的位置没有看到这条规则`SEATA_CONFIG_ENV本身默认可以看做等于DEFAULT_ENV_VALUE`。所以我也不是很确定你是否正确

**Comment by xingfudeshi** [comment]
By default,Seata does not require setting environment variables.And this problem seems caused by registry.conf,can you paste out the content of it?

**Comment by xingfudeshi** [comment]
It's better to give a screenshot which contains all the conf files.

**Comment by CengSin** [comment]
- register.conf

![image](https://user-images.githubusercontent.com/23357893/63757433-a0601800-c8ec-11e9-92ce-3b026373a2db.png)

- file.conf

```
transport {
  # tcp udt unix-domain-socket
  type = "TCP"
  #NIO NATIVE
  server = "NIO"
  #enable heartbeat
  heartbeat = true
  #thread factory for netty
  thread-factory {
    boss-thread-prefix = "NettyBoss"
    worker-thread-prefix = "NettyServerNIOWorker"
    server-executor-thread-prefix = "NettyServerBizHandler"
    share-boss-worker = false
    client-selector-thread-prefix = "NettyClientSelector"
    client-selector-thread-size = 1
    client-worker-thread-prefix = "NettyClientWorkerThread"
    # netty boss thread size,will not be used for UDT
    boss-thread-size = 1
    #auto default pin or 8
    worker-thread-size = 8
  }
}

service {
  #vgroup->rgroup
  vgroup_mapping.my_test_tx_group = "default"
  #only support single node
  default.grouplist = "127.0.0.1:8091"
  #degrade current not support
  enableDegrade = false
  #disable
  disable = false
}

client {
  async.commit.buffer.limit = 10000
  lock {
    retry.internal = 10
    retry.times = 30
  }
}
## transaction log store
store {
  ## store mode: file、db
  mode = "file"

  ## file store
  file {
    dir = "sessionStore"

    # branch session size , if exceeded first try compress lockkey, still exceeded throws exceptions
    max-branch-session-size = 16384
    # globe session size , if exceeded throws exceptions
    max-global-session-size = 512
    # file buffer size , if exceeded allocate new buffer
    file-write-buffer-cache-size = 16384
    # when recover batch read size
    session.reload.read_size = 100
  }

  ## database store
  db {
    driver_class = ""
    url = ""
    user = ""
    password = ""
  }
}
```

**Comment by cmonkey** [comment]
使用此配置不能重新你所报告的错误, 你需要确认一下SEATA_CONFIG_ENV的值是多少

**Comment by CengSin** [comment]
我系统环境变量中没有`SEATA_CONFIG_ENV`，他应该是`null`

**Comment by xingfudeshi** [comment]
Have you tried to restart the.system?what is the output of command "echo %SEATA_CONFIG_ENV%"？

**Comment by CengSin** [comment]
系统版本 ： `Windows10` 。

当我没有在环境变量中设置 `SEATA_CONFIG_ENV` 时，使用 `set SEATA_CONFIG_ENV` 返回为空。
当我设置了 `SEATA_CONFIG_ENV` 之后返回为 `SEATA_CONFIG_ENV=default` 。

可以通过新建一个Demo项目，启动来重现此bug

**Comment by CengSin** [comment]
重启系统并不能解决问题。

**Comment by xingfudeshi** [comment]
I will check.

**Comment by xingfudeshi** [comment]
> 重启系统并不能解决问题。

I can't reproduce your problem.Please wait for next release as the multiple-configuration logics has been improved.
