### ISSUE TITLE
consul1.4.1 has no class com.ecwid.consul.v1.health.HealthServicesRequest，but seata is used at ConsulRegistryServiceImpl.java

### ISSUE THREAD

**Issue by LiuHongYuanl** [seata/seata#1543]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.rm.datasource.DataSourceProxy]: Factory method 'dataSourceProxy' threw exception; nested exception is java.lang.NoClassDefFoundError: com/ecwid/consul/v1/health/HealthServicesRequest
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 146 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/ecwid/consul/v1/health/HealthServicesRequest
	at io.seata.discovery.registry.consul.ConsulRegistryServiceImpl.getHealthyServices(ConsulRegistryServiceImpl.java:241) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.discovery.registry.consul.ConsulRegistryServiceImpl.refreshCluster(ConsulRegistryServiceImpl.java:268) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.discovery.registry.consul.ConsulRegistryServiceImpl.lookup(ConsulRegistryServiceImpl.java:156) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:214) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:161) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.core.rpc.netty.RmRpcClient.registerResource(RmRpcClient.java:226) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.rm.AbstractResourceManager.registerResource(AbstractResourceManager.java:119) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.rm.datasource.DataSourceManager.registerResource(DataSourceManager.java:149) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.rm.DefaultResourceManager.registerResource(DefaultResourceManager.java:114) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.rm.datasource.DataSourceProxy.init(DataSourceProxy.java:87) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:76) ~[seata-all-0.8.0.jar:0.8.0]
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:65) ~[seata-all-0.8.0.jar:0.8.0]
	at com.turtle.shop.service.store.service.SeataAutoConfig.dataSourceProxy(SeataAutoConfig.java:78) ~[classes/:na]
	at com.turtle.shop.service.store.service.SeataAutoConfig$$EnhancerBySpringCGLIB$$a8f9cafa.CGLIB$dataSourceProxy$1(<generated>) ~[classes/:na]
	at com.turtle.shop.service.store.service.SeataAutoConfig$$EnhancerBySpringCGLIB$$a8f9cafa$$FastClassBySpringCGLIB$$a76afa21.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at com.turtle.shop.service.store.service.SeataAutoConfig$$EnhancerBySpringCGLIB$$a8f9cafa.dataSourceProxy(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 147 common frames omitted

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- OS :win10
- seata:0.8.0
- consul 1.4.1

**Comment by LiuHongYuanl** [comment]
Thank you
