### ISSUE TITLE
ERROR[NettyServerNIOWorker_8_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:424 -0318 java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by suhli** [seata/seata#1579]
### Ⅰ. Issue Description
seata OOM

### Ⅱ. Describe what happened

```
2019-09-03 10:58:39.474 ERROR[NettyServerNIOWorker_8_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:424 -0318
java.lang.OutOfMemoryError: Direct buffer memory
	at java.base/java.nio.Bits.reserveMemory(Unknown Source)
	at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

 second instance of the same app id online

### Ⅴ. Anything else we need to know?
running on docker,
Dockerfile:
```Dockerfile
FROM openjdk:11-jre

ENV TZ=Asia/Shanghai
ENV LC_ALL=zh_CN.UTF-8
ENV PROJECT=seata-server
COPY ./ /jar/
RUN chmod +x /jar/init.sh && \
    /jar/init.sh

ENTRYPOINT exec /jar/bin/seata-server.sh
```
init.sh:
```bash
#!/bin/sh
cd /jar/
tar -zxvf ./seata-server.tar.gz
cp -f file.conf ./conf/
cp -f registry.conf ./conf/
rm ./conf/nacos-config.txt ./conf/nacos-config.sh ./conf/nacos-config.py
chmod +x ./bin/seata-server.sh
```
registry.conf:
```
registry {
  type = "eureka"
  eureka {
    serviceUrl = "http://192.168.1.100:30761/eureka"
    application = "seata-server"
    weight = "1"
  }
}

config {
  type = "file"
  file {
    name = "file.conf"
  }
}
```
file.conf:
```
transport {
  # tcp udt unix-domain-socket
  type = "TCP"
  #NIO NATIVE
  server = "NIO"
  #enable heartbeat
  heartbeat = true
  #thread factory for netty
  thread-factory {
    boss-thread-prefix = "NettyBoss"
    worker-thread-prefix = "NettyServerNIOWorker"
    server-executor-thread-prefix = "NettyServerBizHandler"
    share-boss-worker = false
    client-selector-thread-prefix = "NettyClientSelector"
    client-selector-thread-size = 1
    client-worker-thread-prefix = "NettyClientWorkerThread"
    # netty boss thread size,will not be used for UDT
    boss-thread-size = 1
    #auto default pin or 8
    worker-thread-size = 8
  }
  shutdown {
    # when destroy server, wait seconds
    wait = 3
  }
  serialization = "seata"
  compressor = "none"
}
service {
  #vgroup->rgroup
  vgroup_mapping.my_test_tx_group = "seata-server"
  vgroup_mapping.seata-server="seata-server"
  #degrade current not support
  enableDegrade = false
  #disable
  disable = false
  #unit ms,s,m,h,d represents milliseconds, seconds, minutes, hours, days, default permanent
  max.commit.retry.timeout = "-1"
  max.rollback.retry.timeout = "-1"
}

client {
  async.commit.buffer.limit = 10000
  lock {
    retry.internal = 10
    retry.times = 30
  }
  report.retry.count = 5
}

## transaction log store
store {
  ## store mode: file、db
  mode = "db"
  ## database store
  db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "dbcp"
    ## mysql/oracle/h2/oceanbase etc.
    db-type = "mysql"
    url = "jdbc:mysql://192.168.1.100:30336/seata"
    user = "root"
    password = "root"
    min-conn = 1
    max-conn = 3
    global.table = "global_table"
    branch.table = "branch_table"
    lock-table = "lock_table"
    query-limit = 100
  }
}
lock {
  ## the lock store mode: local、remote
  mode = "remote"
  remote {
    ## store locks in the seata's server
  }
}
recovery {
  committing-retry-delay = 30
  asyn-committing-retry-delay = 30
  rollbacking-retry-delay = 30
  timeout-retry-delay = 30
}

transaction {
  undo.data.validation = true
  undo.log.serialization = "jackson"
}

## metrics settings
metrics {
  enabled = false
  registry-type = "compact"
  # multi exporters use comma divided
  exporter-list = "prometheus"
  exporter-prometheus-port = 9898
}
```

full log:[https://gist.github.com/suhli/291ebc036f91a6612f8d968ead680183](https://gist.github.com/suhli/291ebc036f91a6612f8d968ead680183)
### Ⅵ. Environment:

- JDK version :openjdk:11-jre
- seata server version :0.8.0
client base on incubator-shardingsphere,custom replace seata-tm version to 0.8.0

**Comment by slievrly** [comment]
@suhli There are other exceptions before OOM?

**Comment by suhli** [comment]
> @suhli There are other exceptions before OOM?

seems no
![image](https://user-images.githubusercontent.com/23626907/64153153-ccd1e200-ce60-11e9-8868-534daa5c70b5.png)

**Comment by cmonkey** [comment]
尝试将Too many connections的问题修复后，试试

**Comment by suhli** [comment]
> 尝试将Too many connections的问题修复后，试试

没重现,先close了..
