### ISSUE TITLE
Data too long for column 'transaction_name'

### ISSUE THREAD

**Issue by hengboy** [seata/seata#1635]
```java
2019-09-10 09:48:32.549 ERROR[ServerHandlerThread_8_500]io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate:123 -Catch RuntimeException while do RPC, request: timeout=60000,transactionName=deviceBindPersonGroup(java.lang.String, com.smn.microservice.iot.server.bff.business.request.device.DeviceBindPersonGroupRequest)
io.seata.common.exception.StoreException: Data truncation: Data too long for column 'transaction_name' at row 1
	at io.seata.core.store.db.LogStoreDataBaseDAO.insertGlobalTransactionDO(LogStoreDataBaseDAO.java:255)
	at io.seata.server.store.db.DatabaseTransactionStoreManager.writeSession(DatabaseTransactionStoreManager.java:107)
	at io.seata.server.session.db.DataBaseSessionManager.addGlobalSession(DataBaseSessionManager.java:87)
	at io.seata.server.session.AbstractSessionManager.onBegin(AbstractSessionManager.java:115)
	at io.seata.server.session.GlobalSession.begin(GlobalSession.java:128)
	at io.seata.server.coordinator.DefaultCore.begin(DefaultCore.java:129)
	at io.seata.server.coordinator.DefaultCoordinator.doGlobalBegin(DefaultCoordinator.java:146)
	at io.seata.server.AbstractTCInboundHandler$1.execute(AbstractTCInboundHandler.java:53)
	at io.seata.server.AbstractTCInboundHandler$1.execute(AbstractTCInboundHandler.java:50)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:117)
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:50)
	at io.seata.core.protocol.transaction.GlobalBeginRequest.handle(GlobalBeginRequest.java:77)
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:430)
	at io.seata.core.rpc.DefaultServerMessageListenerImpl.onTrxMessage(DefaultServerMessageListenerImpl.java:87)
	at io.seata.core.rpc.netty.RpcServer.dispatch(RpcServer.java:252)
	at io.seata.core.rpc.netty.AbstractRpcRemoting$3.run(AbstractRpcRemoting.java:371)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'transaction_name' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4230)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4164)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2838)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2334)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2262)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2246)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:256)
	at io.seata.core.store.db.LogStoreDataBaseDAO.insertGlobalTransactionDO(LogStoreDataBaseDAO.java:253)
	... 19 common frames omitted
```

**Comment by jsbxyyx** [comment]
I will fix it

**Comment by jsbxyyx** [comment]
@hengboy can you submit a pr fix it? it very simple, you only need to update transaction_name varchar(128) in db_store.sql
