### ISSUE TITLE
When I used the - DseataConfigEnv parameter, I was prompted that I could not find it.

### ISSUE THREAD

**Issue by hengboy** [seata/seata#1659]
when i execute `sh seata-server.sh -DseataConfigEnv=prod -p 8091 -h 172.17.55.220 -m db`
```
Option error Was passed main parameter '-DseataConfigEnv=prod' but no main parameter was defined in your arg class
Usage: sh seata-server.sh(for linux and mac) or cmd seata-server.bat(for 
      windows) [options]
  Options:
    --host, -h
      The host to bind.
      Default: 0.0.0.0
    --port, -p
      The port to listen.
      Default: 8091
    --storeMode, -m
      log store mode : file、db
      Default: file
    --help
```

**Comment by hengboy** [comment]
By modifying the command parameters of `seata-server.sh'file to start `seata-server', adding `DseataConfigEnv=prod', the console prints at startup:
```
Exception in thread "main" io.seata.common.exception.NotSupportYetException: not support register type: null
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:80)
	at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:65)
	at io.seata.server.metrics.MetricsManager.init(MetricsManager.java:49)
	at io.seata.server.Server.main(Server.java:56)
Caused by: java.lang.IllegalArgumentException: illegal type:null
	at io.seata.config.ConfigType.getType(ConfigType.java:62)
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:78)
	... 3 more
```

**Comment by jsbxyyx** [comment]
please paste you conf and seata version

**Comment by hengboy** [comment]
seata version：0.7.1
config:
```
config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "file"

  nacos {
    serverAddr = "localhost"
    namespace = "public"
    cluster = "default"
  }
  consul {
    serverAddr = "127.0.0.1:8500"
  }
  apollo {
    app.id = "seata-server"
    apollo.meta = "http://192.168.1.204:8801"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  etcd3 {
    serverAddr = "http://localhost:2379"
  }
  file {
    name = "file.conf"
  }
}
```

**Comment by hengboy** [comment]
registry:
```
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "eureka"

  nacos {
    serverAddr = "localhost"
    namespace = "public"
    cluster = "default"
  }
  eureka {
    serviceUrl = "http://service:nodev2@iot-node1:10000/eureka"
    application = "seata-server"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = "0"
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
  }
  etcd3 {
    cluster = "default"
    serverAddr = "http://localhost:2379"
  }
  sofa {
    serverAddr = "127.0.0.1:9603"
    application = "default"
    region = "DEFAULT_ZONE"
    datacenter = "DefaultDataCenter"
    cluster = "default"
    group = "SEATA_GROUP"
    addressWaitTime = "3000"
  }
  file {
    name = "file.conf"
  }
}

```

**Comment by jsbxyyx** [comment]
you have registry-prod.conf file?

**Comment by hengboy** [comment]
seata-server also needs to add registry-prod.conf? @jsbxyyx

**Comment by jsbxyyx** [comment]
because you add `-DseataConfigEnv=prod` parameter

**Comment by hengboy** [comment]
@jsbxyyx Do business services need to be added?

**Comment by jsbxyyx** [comment]
if you have different environment, you may be need multiple sets of configurations.

**Comment by xingfudeshi** [comment]
Please refer to here:https://github.com/seata/seata/wiki/Multi-configuration-Isolation

**Comment by xingfudeshi** [comment]
Both file-prod.conf and registry-prod-conf are needed in your situation.
