### ISSUE TITLE
Seata client error Global lock wait timout

### ISSUE THREAD

**Issue by lkxsoul** [seata/seata#1679]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

seata-all 0.8.1 版本AT db模式下主键长度过长（大于32位），导致 Global lock wait timout

### Ⅱ. Describe what happened

 db模式下 使用36位的UUID设置主键时，报错Global lock wait timout，

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 
- OS :
- Others:

**Comment by lkxsoul** [comment]
db模式下，当主键长度超过内存值时，需要修改lock_table中pk（主键）的长度，问题可解决

**Comment by jsbxyyx** [comment]
OK

**Comment by lkxsoul** [comment]
部分server以及client错误日志如下：

【seata-server】

io.seata.common.exception.StoreException: Data truncation: Data too long for column 'pk' at row 1
	at io.seata.core.store.db.LockStoreDataBaseDAO.doAcquireLock(LockStoreDataBaseDAO.java:292)
	at io.seata.core.store.db.LockStoreDataBaseDAO.acquireLock(LockStoreDataBaseDAO.java:164)
	at io.seata.server.lock.db.DataBaseLocker.acquireLock(DataBaseLocker.java:64)
	at io.seata.server.lock.DefaultLockManager.acquireLock(DefaultLockManager.java:64)
	at io.seata.server.session.BranchSession.lock(BranchSession.java:272)
	at io.seata.server.coordinator.DefaultCore.lambda$branchRegister$0(DefaultCore.java:80)
	at io.seata.server.session.GlobalSession.lockAndExcute(GlobalSession.java:597)
	at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:68)
	at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:192)
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:148)
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:144)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:117)
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:144)
	at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:483)
	at io.seata.core.rpc.DefaultServerMessageListenerImpl.onTrxMessage(DefaultServerMessageListenerImpl.java:87)
	at io.seata.core.rpc.netty.RpcServer.dispatch(RpcServer.java:266)
	at io.seata.core.rpc.netty.AbstractRpcRemoting$3.run(AbstractRpcRemoting.java:371)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

【server-client】


JDBC  Connection  [io.seata.rm.datasource.ConnectionProxy@125bcd73]  will  not  be  managed  by  Spring
==>    Preparing:  insert  into  seata_mq(sid,param,createTime)  values  (?,?,?)  
==>  Parameters:  9d3c84a2-14f8-494d-8d04-ad491fcd3569(String),  测试三是(String),  2019-09-19  12:43:37.282(Timestamp)
2019-09-19  12:43:40  [ERROR][io.seata.rm.datasource.exec.AbstractDMLBaseExecutor][executeAutoCommitTrue][97]->  execute  executeAutoCommitTrue  error:Global  lock  wait  timeout
io.seata.rm.datasource.exec.LockWaitTimeoutException:  Global  lock  wait  timeout
at  io.seata.rm.datasource.exec.LockRetryController.sleep(LockRetryController.java:50)
at  io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:293)
at  io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:133)
at  io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:90)
at  io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:58)
at  io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:96)
at  io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:101)
at  io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:47)
at  io.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:54)
at  sun.reflect.NativeMethodAccessorImpl.invoke0(Native  Method)
at  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at  java.lang.reflect.Method.invoke(Method.java:498)
at  org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
at  com.sun.proxy.$Proxy216.execute(Unknown  Source)
at  org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
at  org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
at  org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
at  org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
at  org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
at  sun.reflect.NativeMethodAccessorImpl.invoke0(Native  Method)
at  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at  java.lang.reflect.Method.invoke(Method.java:498)
at  org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
at  com.sun
