### ISSUE TITLE
RegisterRMRequest Error to get ResourceIds

### ISSUE THREAD

**Issue by wslongchen** [seata/seata#1692]
### Ⅰ. Issue Description
I used Seata in my Dubbo project. There were three projects, two of which used sharding-jdbc. I configured and tested that errors in these two projects could be rolled back, and data was generated in the undo_log table and the table data was deleted after the rollback was successful. But when I added a new project method to the previous method, the data could not be rolled back successfully, and no data was generated in the undo_log table.

I carefully compared the configuration files of the three projects and the logs of seata-server at startup. The only difference was that the third project first reminded RegisterRMRequest {resourceIds='null'at startup, but the second one successfully printed the link address of the database resources. I hope I can get some help. Thank you very much.

There is the log :

```
019-09-21 14:40:32.716 [configOperate_1_2] WARN  io.seata.config.FileConfiguration-Could not found property service.disableGlobalTransaction, try to use default value instead. 
2019-09-21 14:40:32.718 [main] INFO  i.seata.spring.annotation.GlobalTransactionScanner-Initializing Global Transaction Clients ...  
2019-09-21 14:40:33.498 [main] INFO  io.seata.core.rpc.netty.AbstractRpcRemotingClient-RpcClientBootstrap has started 
2019-09-21 14:40:33.503 [main] INFO  i.seata.spring.annotation.GlobalTransactionScanner-Transaction Manager Client is initialized. applicationId[my_test_tx_group] txServiceGroup[my_test_tx_group] 
2019-09-21 14:40:33.541 [main] INFO  io.seata.rm.datasource.AsyncWorker-Async Commit Buffer Limit: 10000 
2019-09-21 14:40:33.672 [main] INFO  io.seata.core.rpc.netty.AbstractRpcRemotingClient-RpcClientBootstrap has started 
2019-09-21 14:40:33.674 [main] INFO  i.seata.spring.annotation.GlobalTransactionScanner-Resource Manager is initialized. applicationId[my_test_tx_group] txServiceGroup[my_test_tx_group] 
2019-09-21 14:40:33.674 [main] INFO  i.seata.spring.annotation.GlobalTransactionScanner-Global Transaction Clients are initialized.  
2019-09-21 14:40:38.509 [timeoutChecker_1] INFO  io.seata.core.rpc.netty.NettyClientChannelManager-will connect to 10.33.250.239:8091 
2019-09-21 14:40:38.515 [timeoutChecker_1] INFO  io.seata.core.rpc.netty.NettyPoolableFactory-NettyPool create channel to transactionRole:TMROLE,address:10.33.250.239:8091,msg:< RegisterTMRequest{applicationId='my_test_tx_group', transactionServiceGroup='my_test_tx_group'} > 
2019-09-21 14:40:38.673 [timeoutChecker_1] INFO  io.seata.core.rpc.netty.NettyClientChannelManager-will connect to 10.33.250.239:8091 
2019-09-21 14:40:38.674 [timeoutChecker_1] INFO  io.seata.core.rpc.netty.RmRpcClient-RM will register :null 
2019-09-21 14:40:38.675 [timeoutChecker_1] INFO  io.seata.core.rpc.netty.NettyPoolableFactory-NettyPool create channel to transactionRole:RMROLE,address:10.33.250.239:8091,msg:< RegisterRMRequest{resourceIds='null', applicationId='my_test_tx_group', transactionServiceGroup='my_test_tx_group'} > 
2019-09-21 14:40:39.283 [configOperate_1_2] WARN  io.seata.config.FileConfiguration-Could not found property transport.serialization, try to use default value instead. 
2019-09-21 14:40:39.286 [configOperate_1_2] WARN  io.seata.config.FileConfiguration-Could not found property transport.compressor, try to use default value instead. 
2019-09-21 14:40:39.374 [NettyClientSelector_RMROLE_1] INFO  io.seata.common.loader.EnhancedServiceLoader-load Codec[SEATA] extension by class[io.seata.codec.seata.SeataCodec] 
2019-09-21 14:40:39.498 [timeoutChecker_1] INFO  io.seata.core.rpc.netty.NettyPoolableFactory-register success, cost 185 ms, version:0.8.0,role:TMROLE,channel:[id: 0x48fcb77f, L:/10.33.250.207:58936 - R:/10.33.250.239:8091] 
2019-09-21 14:40:39.498 [timeoutChecker_1] INFO  io.seata.core.rpc.netty.RmRpcClient-register RM success. server version:0.8.0,channel:[id: 0x642dea8f, L:/10.33.250.207:58937 - R:/10.33.250.239:8091] 
2019-09-21 14:40:39.501 [timeoutChecker_1] INFO  io.seata.core.rpc.netty.NettyPoolableFactory-register success, cost 222 ms, version:0.8.0,role:RMROLE,channel:[id: 0x642dea8f, L:/10.33.250.207:58937 - R:/10.33.250.239:8091] 
2019-09-21 14:40:41.134 [main] INFO  com.alibaba.druid.pool.DruidDataSource-{dataSource-1} inited 
2019-09-21 14:40:41.514 [main] INFO  io.seata.core.rpc.netty.RmRpcClient-register to RM resourceId:jdbc:mysql://10.33.250.20:3306/shby_db_agma 
2019-09-21 14:40:41.516 [main] INFO  io.seata.core.rpc.netty.RmRpcClient-register resource, resourceId:jdbc:mysql://10.33.250.20:3306/shby_db_agma 
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : CENTOS 7
- SEATA: 0.8.0

**Comment by wslongchen** [comment]
Well,When I submitted a timeout for the test transaction, the project prompted:

```
2019-09-21 15:08:33.528 [rpcDispatch_RMROLE_8_8] INFO  io.seata.rm.datasource.DataSourceManager-branchRollback failed reason [2020195761/10.33.250.239:8091:2020195755 Could not initialize class io.seata.rm.datasource.undo.UndoLogParserFactory$SingletonHolder] 
2019-09-21 15:08:33.528 [rpcDispatch_RMROLE_8_8] INFO  io.seata.rm.AbstractRMHandler-Branch Rollbacked result: PhaseTwo_RollbackFailed_Retryable 
```

**Comment by wslongchen** [comment]
I tried to upgrade to 0.8.1 and encountered the following exceptions when the test transaction rolled back。
```
2019-09-21 15:37:58.883 [DubboServerHandler-10.33.250.207:20988-thread-3] INFO  io.seata.common.loader.EnhancedServiceLoader-load LoadBalance[null] extension by class[io.seata.discovery.loadbalance.RandomLoadBalance] 
2019-09-21 15:37:59.000 [configOperate_1_2] WARN  io.seata.config.FileConfiguration-Could not found property transaction.undo.log.table, try to use default value instead. 
2019-09-21 15:37:59.011 [configOperate_1_2] WARN  io.seata.config.FileConfiguration-Could not found property transaction.undo.log.serialization, try to use default value instead. 
2019-09-21 15:37:59.016 [DubboServerHandler-10.33.250.207:20988-thread-3] WARN  io.seata.common.loader.EnhancedServiceLoader-load [io.seata.rm.datasource.undo.parser.JacksonUndoLogParser] class fail. com/fasterxml/jackson/databind/JsonSerializer 
2019-09-21 15:37:59.018 [DubboServerHandler-10.33.250.207:20988-thread-3] WARN  io.seata.common.loader.EnhancedServiceLoader-load [io.seata.rm.datasource.undo.parser.ProtostuffUndoLogParser] class fail. io/protostuff/runtime/Delegate 
2019-09-21 15:37:59.029 [DubboServerHandler-10.33.250.207:20988-thread-3] ERROR io.seata.rm.datasource.ConnectionProxy-process connectionProxy commit error: null 
java.lang.ExceptionInInitializerError: null
	at io.seata.rm.datasource.undo.UndoLogParserFactory.getInstance(UndoLogParserFactory.java:46)
	at io.seata.rm.datasource.undo.mysql.MySQLUndoLogManager.flushUndoLogs(MySQLUndoLogManager.java:100)
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:217)
	at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:189)
	at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:177)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:280)
	at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:176)
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.commit(AbstractLogicalConnectionImplementor.java:81)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:272)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:532)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:746)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:533)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:304)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.shby.agma.serviceImpl.AgmaAccountDetailServiceImpl$$EnhancerBySpringCGLIB$$6b45c17c.insertAccountDetail(<generated>)
	at org.apache.dubbo.common.bytecode.Wrapper3.invokeMethod(Wrapper3.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84)
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at com.shby.core.filter.DubboExceptionFilter.invoke(DubboExceptionFilter.java:24)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at io.seata.integration.dubbo.TransactionPropagationFilter.invoke(TransactionPropagationFilter.java:60)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:55)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:92)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:48)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:81)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:96)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:148)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:150)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:152)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.rm.datasource.undo.UndoLogParser[jackson] and classloader : sun.misc.Launcher$AppClassLoader@18b4aac2
```

**Comment by jsbxyyx** [comment]
could you add jackson-databind dependency

**Comment by warrior2005** [comment]
I meet this same error, and add jackson-databind dependency fixed it.
