### ISSUE TITLE
Use spring boot admin to report netty error

### ISSUE THREAD

**Issue by wangwengeek** [seata/seata#1700]
0.7.1 nacos 
2019-09-24 09:51:25.476 INFO [NettyServerNIOWorker_3_8]io.seata.core.rpc.netty.RpcServer.exceptionCaught:334 -channel exx:Adjusted frame length exceeds 8388608: 539976035 - discarded,channel:[id: 0xeebae00c, L:/*:8091 - R:/*:35838]
2019-09-24 09:51:25.476 ERROR[NettyServerNIOWorker_3_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:424 -0318
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 539976035 - discarded
  at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522)
  at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500)
  at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387)
  at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430)
  at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:75)
  at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
  at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
2019-09-24 09:51:25.477 INFO [NettyServerNIOWorker_3_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:212 -will destroy channel:[id: 0xeebae00c, L:/172.16.10.208:8091 - R:/172.16.10.208:35838],address:172.16.10.208:35838
2019-09-24 09:51:25.477 INFO [NettyServerNIOWorker_3_8]io.seata.core.rpc.netty.AbstractRpcRemoting.close:445 -ChannelHandlerContext(RpcServer#0, [id: 0xeebae00c, L:/172.16.10.208:8091 - R:/172.16.10.208:35838]) will closed

**Comment by cmonkey** [comment]
能给出具体的场景吗？

**Comment by wangwengeek** [comment]
是 这个报错 应该是 spring boot admin 验证应用状态请求的报错，都注册到nacos了

**Comment by cmonkey** [comment]
> 是 这个报错 应该是 spring boot admin 验证应用状态请求的报错，都注册到nacos了

能详细告诉你的部署架构吗

**Comment by wangwengeek** [comment]
就开一个 nacos 把seata 和spring boot admin都注册上去就会报错了

**Comment by cmonkey** [comment]
> 就开一个 nacos 把seata 和spring boot admin都注册上去就会报错了

好，我检查一下

**Comment by cmonkey** [comment]
此问题来自于spring-boot-admin 对seata 服务的health check , 而目前seata 不支持health check

**Comment by wangwengeek** [comment]
嗯
