### ISSUE TITLE
seata 0.8.1 did not solved the problem https://github.com/seata/seata/issues/1480

### ISSUE THREAD

**Issue by 13567436138** [seata/seata#1718]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

the same as https://github.com/seata/seata/issues/1480
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- OS :
- Others:

```
2019-09-27 17:20:59.869 ERROR 8928 --- [leMetaChecker_1] i.s.r.d.sql.struct.TableMetaCache        : get table meta error:Table 'stocklogdb.sku_lockinfos' doesn't exist

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'stocklogdb.sku_lockinfos' doesn't exist
	at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_162]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_162]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1365) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:291) ~[druid-1.1.10.jar:1.1.10]
	at io.seata.rm.datasource.StatementProxy$1.execute(StatementProxy.java:68) ~[seata-rm-datasource-0.8.0.jar:na]
	at io.seata.rm.datasource.StatementProxy$1.execute(StatementProxy.java:65) ~[seata-rm-datasource-0.8.0.jar:na]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:69) ~[seata-rm-datasource-0.8.0.jar:na]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:47) ~[seata-rm-datasource-0.8.0.jar:na]
	at io.seata.rm.datasource.StatementProxy.executeQuery(StatementProxy.java:65) ~[seata-rm-datasource-0.8.0.jar:na]
	at io.seata.rm.datasource.sql.struct.TableMetaCache.fetchSchemeInDefaultWay(TableMetaCache.java:131) ~[seata-rm-datasource-0.8.0.jar:na]
	at io.seata.rm.datasource.sql.struct.TableMetaCache.fetchSchema(TableMetaCache.java:119) ~[seata-rm-datasource-0.8.0.jar:na]
	at io.seata.rm.datasource.sql.struct.TableMetaCache.refresh(TableMetaCache.java:104) ~[seata-rm-datasource-0.8.0.jar:na]
	at io.seata.rm.datasource.DataSourceProxy$1.run(DataSourceProxy.java:91) [seata-rm-datasource-0.8.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_162]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [na:1.8.0_162]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [na:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.39.Final.jar:4.1.39.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
```

**Comment by l81893521** [comment]
you error trace show the version of seata is 0.8.0

**Comment by 13567436138** [comment]
oh,maybe my client is 0.8.0 server is 0.8.1

**Comment by l81893521** [comment]
yes, you can change the version and try again, if have any problem, welcome to report in any time, or provide a pr to solve it.

**Comment by xingfudeshi** [comment]
> oh,maybe my client is 0.8.0 server is 0.8.1

Solved?
