### ISSUE TITLE
registry seata-server in Consul error 424 and 430

### ISSUE THREAD

**Issue by ElanZh** [seata/seata#1752]
- JDK version : ```11```
- OS : ```windows```
- Others: ```seata-0.8.1```

I just download release zip file, and edit the ```registry.conf```

我把seata-server注册到consul上，会出现一个名为```default```的服务，控制台上出现错误信息
when I registry seata-server in Consul，I can find a service named ```default```，and the console has error info:

```java
2019-10-12 11:49:22.394 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.RpcServer.exceptionCaught:348 -channel exx:null,channel:[id: 0xe12f1d97, L:0.0.0.0/0.0.0.0:80
91]
2019-10-12 11:49:22.398 ERROR[NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:424 -0318
java.lang.NullPointerException: null
        at io.seata.common.util.NetUtil.toStringAddress(NetUtil.java:72)
        at io.seata.common.util.NetUtil.toStringAddress(NetUtil.java:51)
        at io.seata.core.rpc.netty.RpcServer.handleDisconnect(RpcServer.java:297)
        at io.seata.core.rpc.netty.RpcServer.channelInactive(RpcServer.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
2019-10-12 11:49:22.400 ERROR[NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:430 -failed to close channel [id: 0xe12f1d97, L:0.0.0.0/0
.0.0.0:8091]: null
java.lang.NullPointerException: null
        at io.seata.core.rpc.netty.AbstractRpcRemoting.getAddressFromChannel(AbstractRpcRemoting.java:524)
        at io.seata.core.rpc.netty.AbstractRpcRemoting.destroyChannel(AbstractRpcRemoting.java:495)
        at io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught(AbstractRpcRemoting.java:428)
        at io.seata.core.rpc.netty.RpcServer.exceptionCaught(RpcServer.java:351)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:247)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by xingfudeshi** [comment]
I'll check It.

**Comment by xingfudeshi** [comment]
@ElanZh Can you post a snapshot of consul that shows the details of service registeration.

**Comment by xingfudeshi** [comment]
Please try to use the following command to start seata-server:
```
./seata-server.sh --h xxx.xxx.xxx.xxx
```
The xxx.xxx.xxx.xxx stands for any IP except 127.0.0.1 and 0.0.0.0.

**Comment by ElanZh** [comment]
> 
> 
> Please try to use the following command to start seata-server:
> 
> ```
> ./seata-server.sh --h xxx.xxx.xxx.xxx
> ```
> 
> The xxx.xxx.xxx.xxx stands for any IP except 127.0.0.1 and 0.0.0.0.

sh seata-server.sh -h 192.168.1.30 -p 8091

试过了，仍然是那个报错。
I have tried , still 424 and 430 error.

**Comment by ElanZh** [comment]
> 
> 
> @ElanZh Can you post a snapshot of consul that shows the details of service registeration.

![图片](https://user-images.githubusercontent.com/24262577/66728108-7f8c5b80-ee75-11e9-96b5-c70ff437e8bc.png)

**Comment by ElanZh** [comment]
> 
> 
> @ElanZh Can you post a snapshot of consul that shows the details of service registeration.

![图片](https://user-images.githubusercontent.com/24262577/66728131-a9458280-ee75-11e9-960c-a81c6205efff.png)

**Comment by xingfudeshi** [comment]
@ElanZh I've checked the problem you described,but i did not find any exceptions.Can you provide a demo can reproduce this problem?a ZIP or github repo .

**Comment by ElanZh** [comment]
> 
> 
> @ElanZh I've checked the problem you described,but i did not find any exceptions.Can you provide a demo can reproduce this problem?a ZIP or github repo .

只需要seata-server 0.8.1 的包，
just seata-server 0.8.1 release ZIP，
然后，编辑```registry.conf```
then edit ```registry.conf``` , 
```
registry {
  type = "consul"
  consul {
    cluster = "default"
    serverAddr = "my_consul_IP:8500"
  }
}
etc...
```
 最后启动 seata-server
then start the seata-server

**Comment by cmonkey** [comment]
Consul 的版本是多少，我启动一个docker试一下

**Comment by ElanZh** [comment]
> 
> 
> Consul 的版本是多少，我启动一个docker试一下

consul 1.4.2
![图片](https://user-images.githubusercontent.com/24262577/66736829-e40ee100-ee9c-11e9-8619-204cecce0e58.png)

**Comment by cmonkey** [comment]
重现了，应该和jdk version 有关系，通过jdk 配合consul 1.4.2 1.6.1 都无法发现此问题
将jdk 切换为openjdk 11 就能重现此问题

**Comment by xingfudeshi** [comment]
@cmonkey Good job!

**Comment by ElanZh** [comment]
> 
> 
> 重现了，应该和jdk version 有关系，通过jdk 8 配合consul 1.4.2 1.6.1 都无法发现此问题
> 将jdk 切换为openjdk 11 就能重现此问题

那我现在seata-server出现这个错误是不是也跟 ```openjdk-11``` 有关？会不会影响功能？

```java
2019-10-14 09:29:27.846 ERROR[NettyServerNIOWorker_3_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:424 -0318
java.io.IOException: Connection reset by peer
        at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by cmonkey** [comment]
这是另一个问题了吧，我没有测到这个问题

你方便的话，需要告诉我如何重现

**Comment by ElanZh** [comment]
启动项目注册到seata-server就会经常出现这个

**Comment by ElanZh** [comment]
> 
> 
> 这是另一个问题了吧，我没有测到这个问题
> 
> 你方便的话，需要告诉我如何重现

启动项目把事务注册到seata-server，server端就会经常出现这个
