### ISSUE TITLE
seata 0.9.0  {store.db.driver-clas s-name} can't be empty

### ISSUE THREAD

**Issue by lidong1665** [seata/seata#1853]
Exception in thread "main" io.seata.common.loader.EnhancedServiceNotFoundExcepti
on: not found service provider for : io.seata.server.store.TransactionStoreManag
er caused by io.seata.common.exception.StoreException: the {store.db.driver-clas
s-name} can't be empty.
        at io.seata.core.store.db.AbstractDataSourceGenerator.getDriverClassName
(AbstractDataSourceGenerator.java:53)
        at io.seata.server.store.db.DruidDataSourceGenerator.generateDataSource(
DruidDataSourceGenerator.java:36)
        at io.seata.server.store.db.DatabaseTransactionStoreManager.init(Databas
eTransactionStoreManager.java:98)
        at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedSer
viceLoader.java:363)
        at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedService
Loader.java:234)
        at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedService
Loader.java:194)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoad
er.java:89)
        at io.seata.server.session.db.DataBaseSessionManager.init(DataBaseSessio
nManager.java:81)
        at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedSer
viceLoader.java:363)
        at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedService
Loader.java:234)
        at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedService
Loader.java:194)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoad
er.java:89)
        at io.seata.server.session.SessionHolder.init(SessionHolder.java:96)
        at io.seata.server.Server.main(Server.java:71)

**Comment by slievrly** [comment]
@lidong1665 what configuration center is used? Paste the configuration item value.

**Comment by lidong1665** [comment]
Version 0.9.0 nacos's namespaces have been updated and the problem has been found.
