### ISSUE TITLE
高并发测试，程序卡死，错误信息如下：

### ISSUE THREAD

**Issue by tiangk** [seata/seata#1859]
### Ⅵ. Environment:

- JDK version : 1.8.1
- OS : windows
- Others: oracle 11g

[t0Aggr HT200407008896B-8083] 2019-10-31 16:50:16.561+0800 [,,] [NettyClientSelector_TMROLE_1] ERROR i.s.c.rpc.netty.v1.ProtocolV1Decoder - Decode frame error!
java.lang.IllegalArgumentException: not support typeCode,-9510
	at io.seata.codec.seata.MessageCodecFactory.getMergeResponseInstanceByCode(MessageCodecFactory.java:345)
	at io.seata.codec.seata.MessageCodecFactory.getMessage(MessageCodecFactory.java:284)
	at io.seata.codec.seata.SeataCodec.decode(SeataCodec.java:79)
	at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decodeFrame(ProtocolV1Decoder.java:136)
	at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:83)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[t0Aggr HT200407008896B-8083] 2019-10-31 16:50:16.623+0800 [,,] [NettyClientSelector_TMROLE_1] ERROR i.s.c.r.n.AbstractRpcRemotingClient - 0318
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: not support typeCode,-9510
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: not support typeCode,-9510
	at io.seata.codec.seata.MessageCodecFactory.getMergeResponseInstanceByCode(MessageCodecFactory.java:345)
	at io.seata.codec.seata.MessageCodecFactory.getMessage(MessageCodecFactory.java:284)
	at io.seata.codec.seata.SeataCodec.decode(SeataCodec.java:79)
	at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decodeFrame(ProtocolV1Decoder.java:136)
	at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:83)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	... 20 common frames omitted
[t0Aggr HT200407008896B-8083] 2019-10-31 16:50:16.623+0800 [,,] [NettyClientSelector_TMROLE_1] INFO  i.s.c.r.n.NettyClientChannelManager - return to pool, rm channel:[id: 0xb37360bf, L:/192.168.145.15:18323 - R:/192.168.145.15:8091]
[t0Aggr HT200407008896B-8083] 2019-10-31 16:50:16.624+0800 [,,] [NettyClientSelector_TMROLE_1] INFO  i.s.c.r.n.AbstractRpcRemotingClient - remove exception rm channel:[id: 0xb37360bf, L:/192.168.145.15:18323 - R:/192.168.145.15:8091]
[t0Aggr HT200407008896B-8083] 2019-10-31 16:50:16.624+0800 [,,] [NettyClientSelector_TMROLE_1] ERROR i.s.c.rpc.netty.AbstractRpcRemoting - 0318

**Comment by xingfudeshi** [comment]
What's the version of seata?

**Comment by xingfudeshi** [comment]
try latest
