### ISSUE TITLE
seata-server-0.9.0 Startup failure

### ISSUE THREAD

**Issue by yuhuangbin** [seata/seata#1876]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata-server-0.9.0 Startup failure
- sh seata-server.sh -m file

### Ⅱ. Describe what happened
```java

Exception in thread "main" io.seata.common.exception.NotSupportYetException: not support register type: null
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:87)
	at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:71)
	at io.seata.server.metrics.MetricsManager.init(MetricsManager.java:49)
	at io.seata.server.Server.main(Server.java:62)
Caused by: java.lang.IllegalArgumentException: illegal type:null
	at io.seata.config.ConfigType.getType(ConfigType.java:70)
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:85)
	... 3 more
```

### Ⅵ. Environment:

- JDK version : 1.8
- OS : MacOs
- Others:

**Comment by cmonkey** [comment]
是不是有自定义环境变量呢?

**Comment by yuhuangbin** [comment]
seata-server-0.8.1.tar.gz also failed to start, but seata-server-0.8.0.tar.gz is ok

**Comment by slievrly** [comment]
has been solved by `sudo`, but the root cause needs further check.

**Comment by yuhuangbin** [comment]
The cause modified the system environment variable and executed the source command, but the seata-server cannot read the latest and needs to restart the computer

**Comment by yuhuangbin** [comment]
The cause modified the system environment variable and executed the `source` command, but the `seata-server` cannot read the latest and needs to restart the computer

**Comment by xingfudeshi** [comment]
> The cause modified the system environment variable `SEATA_ENV` and executed the `source` command, but the `seata-server` cannot read the latest and needs to restart the computer

You need to restart your process to make the environment variable effective.
