### ISSUE TITLE
io.seata.common.exception.FrameworkException: No available service

### ISSUE THREAD

**Issue by kangjunxiang** [seata/seata#1944]
# Test info
```java
@Test
	public void asyncTest(){
		for(int i=0 ;i<50;i++){
			try {
				log.info("num："+i);
				baseService.testAsync(i+"");
				//Thread.sleep(2000);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
```
baseService.testAsync
```java
@Override
	public String testAsync(String str) {
    	
		Long startTime = System.currentTimeMillis();
        dataExchangeLogService.insertSysLog("type1", "start:test", "",
                "time", startTime+"", str);
        
        log.info("AsyncStart："+str);
        systemService.testAsTime(str);
        
		Long endTime = System.currentTimeMillis();
        dataExchangeLogService.insertSysLog("type1", "end:test", (endTime-startTime)+"ms",
                "time", endTime+"", str);
        
		return "ok";
	}
```
    systemService.testAsTime
```java
@Async
    @GlobalTransactional(timeoutMills=200000)
	@Override
	public void testAsTime(String str) {
    	Long startTime = System.currentTimeMillis();
        dataExchangeLogService.insertSysLog("type1", "start:testAsTime", "",
                "time", startTime+"", str);
        try {
			Thread.sleep(10000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			// log.error("testAsTime error"+str, e);
		}
		Long endTime = System.currentTimeMillis();
        dataExchangeLogService.insertSysLog("type1", "end:testAsTime", (endTime-startTime)+"ms",
                "time", endTime+"", str);		
	}
```
# info logs
```
[DubboServerHandler-192.168.56.1:18082-thread-14:21814] [INFO] - com.xxx.BaseServiceImpl.testAsync(BaseServiceImpl.java:2403) - AsyncStart：6
[taskExecutor-7:21826] [INFO] - io.seata.tm.api.DefaultGlobalTransaction.begin(DefaultGlobalTransaction.java:106) - Begin new global transaction [111.111.111.146:8091:2028678011]
[main:21828] [INFO] - com.xxx.GlobalTransactionalTest.asyncTest(GlobalTransactionalTest.java:55) - num：7
[DubboServerHandler-192.168.56.1:18082-thread-16:21836] [INFO] - com.xxx.BaseServiceImpl.testAsync(BaseServiceImpl.java:2403) - AsyncStart：7
[main:21846] [INFO] - com.xxx.GlobalTransactionalTest.asyncTest(GlobalTransactionalTest.java:55) - num：8
[taskExecutor-8:21852] [INFO] - io.seata.tm.api.DefaultGlobalTransaction.begin(DefaultGlobalTransaction.java:106) - Begin new global transaction [111.111.111.146:8091:2028678014]
[DubboServerHandler-192.168.56.1:18082-thread-18:21856] [INFO] - com.xxx.BaseServiceImpl.testAsync(BaseServiceImpl.java:2403) - AsyncStart：8
[taskExecutor-9:21867] [INFO] - io.seata.tm.api.DefaultGlobalTransaction.begin(DefaultGlobalTransaction.java:106) - Begin new global transaction [111.111.111.146:8091:2028678018]
[main:21869] [INFO] - com.xxx.GlobalTransactionalTest.asyncTest(GlobalTransactionalTest.java:55) - num：9
[DubboServerHandler-192.168.56.1:18082-thread-20:21918] [INFO] - com.xxx.BaseServiceImpl.testAsync(BaseServiceImpl.java:2403) - AsyncStart：9
[main:21931] [INFO] - com.xxx.GlobalTransactionalTest.asyncTest(GlobalTransactionalTest.java:55) - num：10
[taskExecutor-10:21932] [INFO] - io.seata.tm.api.DefaultGlobalTransaction.begin(DefaultGlobalTransaction.java:106) - Begin new global transaction [111.111.111.146:8091:2028678024]
[DubboServerHandler-192.168.56.1:18082-thread-22:21942] [INFO] - com.xxx.BaseServiceImpl.testAsync(BaseServiceImpl.java:2403) - AsyncStart：10
[main:21955] [INFO] - com.xxx.GlobalTransactionalTest.asyncTest(GlobalTransactionalTest.java:55) - num：11
[DubboServerHandler-192.168.56.1:18082-thread-24:22005] [INFO] - com.xxx.BaseServiceImpl.testAsync(BaseServiceImpl.java:2403) - AsyncStart：11
[main:22017] [INFO] - com.xxx.GlobalTransactionalTest.asyncTest(GlobalTransactionalTest.java:55) - num：12
[DubboServerHandler-192.168.56.1:18082-thread-26:22027] [INFO] - com.xxx.BaseServiceImpl.testAsync(BaseServiceImpl.java:2403) - AsyncStart：12
[main:22037] [INFO] - com.xxx.GlobalTransactionalTest.asyncTest(GlobalTransactionalTest.java:55) - num：13
[DubboServerHandler-192.168.56.1:18082-thread-28:22048] [INFO] - com.xxx.BaseServiceImpl.testAsync(BaseServiceImpl.java:2403) - AsyncStart：13
[main:22066] [INFO] - com.xxx.GlobalTransactionalTest.asyncTest(GlobalTransactionalTest.java:55) - num：14
[DubboServerHandler-192.168.56.1:18082-thread-30:22077] [INFO] - com.xxx.BaseServiceImpl.testAsync(BaseServiceImpl.java:2403) - AsyncStart：14
```
# error logs
```
[taskExecutor-10:15149] [ERROR] - org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler.handleUncaughtException(SimpleAsyncUncaughtExceptionHandler.java:38) - Unexpected error occurred invoking async method: public void com.xxx.SystemServiceImpl.testAsTime(java.lang.String)
io.seata.core.exception.TransactionException: Failed to report global commit
	at io.seata.tm.api.DefaultGlobalTransaction.commit(DefaultGlobalTransaction.java:133) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.tm.api.TransactionalTemplate.commitTransaction(TransactionalTemplate.java:103) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:74) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:101) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:76) ~[seata-all-0.9.0.jar:0.9.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: io.seata.common.exception.FrameworkException: No available service
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.loadBalance(AbstractRpcRemotingClient.java:279) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.sendMsgWithResponse(AbstractRpcRemotingClient.java:225) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.sendMsgWithResponse(AbstractRpcRemotingClient.java:233) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.tm.DefaultTransactionManager.syncCall(DefaultTransactionManager.java:95) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.tm.DefaultTransactionManager.commit(DefaultTransactionManager.java:64) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.tm.api.DefaultGlobalTransaction.commit(DefaultGlobalTransaction.java:127) ~[seata-all-0.9.0.jar:0.9.0]
	... 10 more
[taskExecutor-8:15184] [ERROR] - io.seata.tm.api.DefaultGlobalTransaction.commit(DefaultGlobalTransaction.java:130) - Failed to report global commit [111.111.111.146:8091:2028669114],Retry Countdown: 1, reason: No available service
[taskExecutor-8:15185] [ERROR] - org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler.handleUncaughtException(SimpleAsyncUncaughtExceptionHandler.java:38) - Unexpected error occurred invoking async method: public void com.xxx.SystemServiceImpl.testAsTime(java.lang.String)
io.seata.core.exception.TransactionException: Failed to report global commit
	at io.seata.tm.api.DefaultGlobalTransaction.commit(DefaultGlobalTransaction.java:133) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.tm.api.TransactionalTemplate.commitTransaction(TransactionalTemplate.java:103) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:74) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:101) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:76) ~[seata-all-0.9.0.jar:0.9.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: io.seata.common.exception.FrameworkException: No available service
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.loadBalance(AbstractRpcRemotingClient.java:279) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.sendMsgWithResponse(AbstractRpcRemotingClient.java:225) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.sendMsgWithResponse(AbstractRpcRemotingClient.java:233) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.tm.DefaultTransactionManager.syncCall(DefaultTransactionManager.java:95) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.tm.DefaultTransactionManager.commit(DefaultTransactionManager.java:64) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.tm.api.DefaultGlobalTransaction.commit(DefaultGlobalTransaction.java:127) ~[seata-all-0.9.0.jar:0.9.0]
	... 10 more
```

# description
Not for polling is normal, what configuration needs to be adjusted?
**num：11** later ，Did not create global transaction？ **Begin new global transaction**

**Comment by kangjunxiang** [comment]
Asynchrony leads to the end of the spring life cycle.

```java
        @Test
	public void asyncTest(){
		for(int i=0 ;i<50;i++){
			try {
				log.info("num："+i);
				baseService.testAsync(i+"");
				//Thread.sleep(2000);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
                try {
			Thread.sleep(200000);
		  } catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
```
