### ISSUE TITLE
JPA保存关联对象时报错

### ISSUE THREAD

**Issue by wgb123** [seata/seata#1954]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
角色对象
![16560308445273](https://user-images.githubusercontent.com/26479828/69782609-7b7d8880-11ec-11ea-8437-c2e8bff3701f.png)
出错方法
![360截图17860601589980](https://user-images.githubusercontent.com/26479828/69782651-9b14b100-11ec-11ea-8faf-48a4e98977a0.png)

### Ⅱ. Describe what happened

 Caused by: javax.persistence.RollbackException: Error while committing the transaction
        at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:77) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:71) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:536) ~[spring-orm-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        ... 82 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_211]
        at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_211]
        at io.seata.rm.datasource.sql.struct.TableMeta.getPkName(TableMeta.java:153) ~[seata-all-0.9.0.jar!/:0.9.0]
        at io.seata.rm.datasource.AbstractConnectionProxy.prepareStatement(AbstractConnectionProxy.java:114) ~[seata-all-0.9.0.jar!/:0.9.0]
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$1.doPrepare(StatementPreparerImpl.java:86) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:171) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:77) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.buildBatchStatement(AbstractBatchImpl.java:136) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.getBatchStatement(AbstractBatchImpl.java:125) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.persister.collection.AbstractCollectionPersister.recreate(AbstractCollectionPersister.java:1306) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.action.internal.CollectionUpdateAction.execute(CollectionUpdateAction.java:80) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:600) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:474) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1437) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:494) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3245) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2451) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:473) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:156) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:231) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:68) ~[hibernate-core-5.2.17.Final.jar!/:5.2.17.Final]
        ... 83 common frames omitted

```
Just paste your stack trace here!
```

### Ⅵ. Environment:

- JDK version :1.8
- OS : 
- Others:

**Comment by wgb123** [comment]
两个index的IntexType 都是 Normal  返回的list是空，然后getPkName就报了数组越界。不是很理解这边，想问一下有什么改进方法

**Comment by zjinlei** [comment]
Seata requires tables to have primary key, latest 1.0.0-SNAPSHOT added reminder information.
![image](https://user-images.githubusercontent.com/20024955/69782887-3e65c600-11ed-11ea-8027-bbf58ab6aadb.png)

**Comment by wgb123** [comment]
![1](https://user-images.githubusercontent.com/26479828/69784315-7589a680-11f0-11ea-916b-2c1afa8f7a9b.png)
![2](https://user-images.githubusercontent.com/26479828/69784322-77ec0080-11f0-11ea-9fba-0f0495a88253.png)
两个表都是有主键的

**Comment by wgb123** [comment]
![360截图173211289612397](https://user-images.githubusercontent.com/26479828/69784795-9bfc1180-11f1-11ea-9cd0-8f15370b9f41.png)

**Comment by l81893521** [comment]
What kind of Database? Oracle?

**Comment by l81893521** [comment]
Can you give us the sql to create the same table?

**Comment by wgb123** [comment]
mysql

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for fl_role_info
-- ----------------------------

CREATE TABLE `fl_role_info`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `role_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `user_id` int(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1037 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE `fl_mean_info`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `alias` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `menu_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `menu_url` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `order_id` int(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 42 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE `fl_role_info_menus`  (
  `RoleInfo_id` int(11) NOT NULL,
  `menus_id` int(11) NOT NULL,
  INDEX `FKib2sp5gy5e7v12cbgccadv9u`(`menus_id`) USING BTREE,
  INDEX `FKdpm3kwqmvet5q525sloqq2sup`(`RoleInfo_id`) USING BTREE,
  CONSTRAINT `FKdpm3kwqmvet5q525sloqq2sup` FOREIGN KEY (`RoleInfo_id`) REFERENCES `fl_role_info` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FKib2sp5gy5e7v12cbgccadv9u` FOREIGN KEY (`menus_id`) REFERENCES `fl_mean_info` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB AUTO_INCREMENT = 13565 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

**Comment by wgb123** [comment]
Hibernate: delete from fl_role_info_menus where RoleInfo_id=?
Hibernate: insert into fl_role_info_menus (RoleInfo_id, menus_id) values (?, ?)
是不是因为操作的中间表没有主键？

**Comment by l81893521** [comment]
I think yes, you can create a primary key and try again.

**Comment by wgb123** [comment]
可行
