### ISSUE TITLE
resourceIds='null cause the failure of a rollback

### ISSUE THREAD

**Issue by YangXueJun** [seata/seata#1955]
### Ⅰ. Issue Description
Somtimes  , client register to seata server will  appears the following log info. 
When **resourceIds='null'**, will cause the failure of a rollback. And  **resourceIds='null'** not always appears.  (服务客户端端连接seata服务器时，如果出现resourceIds='null'，后续回滚就会失败。resourceIds='null'的情况还不是一定会出现的，有时候有不为null可以正常回滚的)

seata-server.log
`2019-11-28 16:27:58.588 INFO [ServerHandlerThread_97_500]io.seata.core.rpc.DefaultServerMessageListenerImpl.onRegRmMessage:116 -rm register success,message:RegisterRMRequest{resourceIds='null', applicationId='cdemo-service', transactionServiceGroup='consumer_tx_group'},channel:[id: 0xdbc1db06, L:/127.0.0.1:8091 - R:/127.0.0.1:52050]`

rollback failed log info

```
2019-11-28 13:50:10.417 INFO [RetryRollbacking_1]io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking:388 -Failed to retry rollbacking [10.70.12.171:8091:2028644734] Unknown java.lang.RuntimeException: rm client is not connected. dbkey:jdbc:mysql://127.0.01:3306/test,clientId:cdemo-service:127.0.0.1:61634
2019-11-28 13:50:10.418 INFO [RetryRollbacking_1]io.seata.core.rpc.ChannelManager.getChannel:426 -No channel is available for resource[jdbc:mysql://127.0.01:3306/test] as alternative of cdemo-service:127.0.0.1:62283
2019-11-28 13:50:10.418 ERROR[RetryRollbacking_1]io.seata.server.coordinator.DefaultCore.doGlobalRollback:420 -Exception rollbacking branch xid=10.70.12.171:8091:2028644739 branchId=2028644740
java.lang.RuntimeException: rm client is not connected. dbkey:jdbc:mysql://127.0.01:3306/test,clientId:cdemo-service:127.0.0.1:62283
at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:217)
at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:269)
at io.seata.server.coordinator.DefaultCoordinator.branchRollback(DefaultCoordinator.java:306)
at io.seata.server.coordinator.DefaultCore.doGlobalRollback(DefaultCore.java:398)
at io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking(DefaultCoordinator.java:386)
at io.seata.server.coordinator.DefaultCoordinator.lambda$init$1(DefaultCoordinator.java:486)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)

```

###  项目情况
项目整合了dubbo 、nacos、seata、springcloud（0.9.0）
参照下面的例子做的
https://github.com/seata/seata-samples/tree/master/spring-cloud-alibaba-samples
如果打断点，过一定时间，则不会出现resourceIds='null ，也能够正常回滚。

![image](https://user-images.githubusercontent.com/11888152/69793797-159cfb00-1204-11ea-977d-d01df543198d.png)

调用代码
![image](https://user-images.githubusercontent.com/11888152/69794274-ec309f00-1204-11ea-94c1-c80487e2aa55.png)

### Ⅵ. Environment:

- JDK version :1.8
- OS :mac
- Others:

**Comment by YangXueJun** [comment]
rollback failed  log info

> 2019-11-28 13:50:10.417 INFO [RetryRollbacking_1]io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking:388 -Failed to retry rollbacking [10.70.12.171:8091:2028644734] Unknown java.lang.RuntimeException: rm client is not connected. dbkey:jdbc:mysql://127.0.01:3306/test,clientId:cdemo-service:127.0.0.1:61634
> 2019-11-28 13:50:10.418 INFO [RetryRollbacking_1]io.seata.core.rpc.ChannelManager.getChannel:426 -No channel is available for resource[jdbc:mysql://127.0.01:3306/test] as alternative of cdemo-service:127.0.0.1:62283
> 2019-11-28 13:50:10.418 ERROR[RetryRollbacking_1]io.seata.server.coordinator.DefaultCore.doGlobalRollback:420 -Exception rollbacking branch xid=10.70.12.171:8091:2028644739 branchId=2028644740
> java.lang.RuntimeException: rm client is not connected. dbkey:jdbc:mysql://127.0.01:3306/test,clientId:cdemo-service:127.0.0.1:62283
>         at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:217)
>         at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:269)
>         at io.seata.server.coordinator.DefaultCoordinator.branchRollback(DefaultCoordinator.java:306)
>         at io.seata.server.coordinator.DefaultCore.doGlobalRollback(DefaultCore.java:398)
>         at io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking(DefaultCoordinator.java:386)
>         at io.seata.server.coordinator.DefaultCoordinator.lambda$init$1(DefaultCoordinator.java:486)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.lang.Thread.run(Thread.java:748)

**Comment by slievrly** [comment]
@YangXueJun this has nothing to do with `resourceIds='null'`, you can see client log, it will show the cause of rollback fail.

**Comment by YangXueJun** [comment]
> @YangXueJun this has nothing to do with `resourceIds='null'`, you can see client log, it will show the cause of rollback fail.

Thanks your reply，It's my pleasure.
I had solved this probem, spring-cloud-alibaba-dependencies（2.1.0.RELEASE）depends seata-all(0.7.1) that contains a bug.  This bug sometimes register with resourcesId=null, it lead to rollback failed. And this bug had fixed In subsequent versions .(我已经解决这个问题，spring-cloud-alibaba-dependencies（2.1.0.RELEASE)依赖的是seata-all:0.7.1，这个版本的seata有一个bug，这个bug会导致注册服务时 resourcesId=null，最终回滚失败。查看最新版的seata-all:0.9.0,这个bug已经解决。


seata-all:0.7.1  code
![image](https://user-images.githubusercontent.com/11888152/69847399-f6f53d80-12b1-11ea-87c7-e52dcb657c37.png)

seata-all :0.9.0 code
![image](https://user-images.githubusercontent.com/11888152/69846617-9107b680-12af-11ea-87c1-4b8fee2b6b7f.png)



### Solution

Eliminate old dependency ,and add new version dependency.
剔除老版本依赖，引入新版seata依赖。

```
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-all</artifactId>

                </exclusion>
            </exclusions>
        </dependency>
<dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-all</artifactId>
            <version>0.9.0</version>
        </dependency>

```

**Comment by slievrly** [comment]
@YangXueJun 1.0 will reset this code，it cause a bug on tcc mode.
