### ISSUE TITLE
Under concurrent pressure test, it is unable to roll back and dirty data appears

### ISSUE THREAD

**Issue by wanqiang2046** [seata/seata#1991]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Single access can be rolled back normally, but under the concurrent stress test, it cannot be rolled back and dirty data appears. Global submission can be submitted normally

### Ⅱ. Describe what happened
framework：springcloud+fegin+consul+mybatis
I used JMeter to perform a pressure test on the Seata transaction rollback, and found that the transaction was not rolled back, and dirty data appeared, which caused the record to fail to roll back all the time, which is no longer normal.

Service caller：

    @Override
    @GlobalTransactional(timeoutMills = 300000, rollbackFor = Exception.class)
    public Response atPurchaseRollback(String skuCode, Integer count) {
        //下订单
        orderFeignClient.create(skuCode, count);
        //减库存
        storageFeignClient.deduct(skuCode, count);

        throw new RuntimeException("库存不足");
    }

Inventory service：Only one update SQL operation

    @Override
    public Response deduct(String skuCode, Integer count) {

        storageMapper.deductUpdate(skuCode, count);

        return Response.ok();
    }

Order service：Only one insert SQL operation

    @Override
    public Response create(String skuCode, Integer count) {
        String orderId = UUID.randomUUID().toString();
        Order order = new Order();
        order.setCount(count);
        order.setOrderId(orderId);
        order.setSkuCode(skuCode);
        int result = orderMapper.insert(order);
        if(result == 0){
            return Response.errorMsg("创建订单失败");
        }
        return Response.ok().putData(orderId);
    }

Inventory  Exception:

{"@class":"io.seata.rm.datasource.undo.BranchUndoLog","xid":"10.104.6.96:8091:2029302874","branchId":2029306263,"sqlUndoLogs":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.undo.SQLUndoLog","sqlType":"UPDATE","tableName":"inventory_storage","beforeImage":{"@class":"io.seata.rm.datasource.sql.struct.TableRecords","tableName":"inventory_storage","rows":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.sql.struct.Row","fields":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"id","keyType":"PrimaryKey","type":4,"value":1},{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"count","keyType":"NULL","type":4,"value":-90000}]]}]]},"afterImage":{"@class":"io.seata.rm.datasource.sql.struct.TableRecords","tableName":"inventory_storage","rows":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.sql.struct.Row","fields":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"id","keyType":"PrimaryKey","type":4,"value":1},{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"count","keyType":"NULL","type":4,"value":-190000}]]}]]}},{"@class":"io.seata.rm.datasource.undo.SQLUndoLog","sqlType":"UPDATE","tableName":"inventory_storage","beforeImage":{"@class":"io.seata.rm.datasource.sql.struct.TableRecords","tableName":"inventory_storage","rows":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.sql.struct.Row","fields":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"id","keyType":"PrimaryKey","type":4,"value":1},{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"count","keyType":"NULL","type":4,"value":10000}]]}]]},"afterImage":{"@class":"io.seata.rm.datasource.sql.struct.TableRecords","tableName":"inventory_storage","rows":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.sql.struct.Row","fields":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"id","keyType":"PrimaryKey","type":4,"value":1},{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"count","keyType":"NULL","type":4,"value":-90000}]]}]]}}]]}

2019-12-05 09:44:29,905 [fb4-seata-storage] [rpcDispatch_RMROLE_4_8] INFO  io.seata.rm.datasource.DataSourceManager[branchRollback] - branchRollback failed reason [Branch session rollback failed and try again later xid = 10.104.6.96:8091:2029302874 branchId = 2029306263 Has dirty records when undo.]
2019-12-05 09:44:29,906 [fb4-seata-storage] [rpcDispatch_RMROLE_4_8] INFO  io.seata.rm.AbstractRMHandler[doBranchRollback] - Branch Rollbacked result: PhaseTwo_RollbackFailed_Retryable
2019-12-05 09:44:29,993 [fb4-seata-storage] [rpcDispatch_RMROLE_5_8] INFO  io.seata.core.rpc.netty.RmMessageListener[onMessage] - onMessage:xid=10.104.6.96:8091:2029302874,branchId=2029306263,branchType=AT,resourceId=jdbc:mysql://10.104.6.10:3319/fb4_seata_storage,applicationData=null
2019-12-05 09:44:29,994 [fb4-seata-storage] [rpcDispatch_RMROLE_5_8] INFO  io.seata.rm.AbstractRMHandler[doBranchRollback] - Branch Rollbacking: 10.104.6.96:8091:2029302874 2029306263 jdbc:mysql://10.104.6.10:3319/fb4_seata_storage
2019-12-05 09:44:30,014 [fb4-seata-storage] [rpcDispatch_RMROLE_5_8] INFO  io.seata.rm.datasource.undo.AbstractUndoExecutor[dataValidationAndGoOn] - Field not equals, name count, old value -190000, new value 10000
2019-12-05 09:44:30,017 [fb4-seata-storage] [rpcDispatch_RMROLE_5_8] INFO  io.seata.rm.datasource.DataSourceManager[branchRollback] - branchRollback failed reason [Branch session rollback failed and try again later xid = 10.104.6.96:8091:2029302874 branchId = 2029306263 Has dirty records when undo.]
2019-12-05 09:44:30,017 [fb4-seata-storage] [rpcDispatch_RMROLE_5_8] INFO  io.seata.rm.AbstractRMHandler[doBranchRollback] - Branch Rollbacked result: PhaseTwo_RollbackFailed_Retryable
2019-12-05 09:44:30,081 [fb4-seata-storage] [rpcDispatch_RMROLE_6_8] INFO  io.seata.core.rpc.netty.RmMessageListener[onMessage] - onMessage:xid=10.104.6.96:8091:2029302874,branchId=2029306263,branchType=AT,resourceId=jdbc:mysql://10.104.6.10:3319/fb4_seata_storage,applicationData=null
2019-12-05 09:44:30,082 [fb4-seata-storage] [rpcDispatch_RMROLE_6_8] INFO  io.seata.rm.AbstractRMHandler[doBranchRollback] - Branch Rollbacking: 10.104.6.96:8091:2029302874 2029306263 jdbc:mysql://10.104.6.10:3319/fb4_seata_storage
2019-12-05 09:44:30,150 [fb4-seata-storage] [rpcDispatch_RMROLE_6_8] INFO  io.seata.rm.datasource.undo.AbstractUndoExecutor[dataValidationAndGoOn] - Field not equals, name count, old value -190000, new value 10000
2019-12-05 09:44:30,152 [fb4-seata-storage] [rpcDispatch_RMROLE_6_8] INFO  io.seata.rm.datasource.DataSourceManager[branchRollback] - branchRollback failed reason [Branch session rollback failed and try again later xid = 10.104.6.96:8091:2029302874 branchId = 2029306263 Has dirty records when undo.]
2019-12-05 09:44:30,153 [fb4-seata-storage] [rpcDispatch_RMROLE_6_8] INFO  io.seata.rm.AbstractRMHandler[doBranchRollback] - Branch Rollbacked result: PhaseTwo_RollbackFailed_Retryable
.....................................
io.seata.rm.datasource.exec.LockWaitTimeoutException: Global lock wait timeout
	at io.seata.rm.datasource.exec.LockRetryController.sleep(LockRetryController.java:50)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:291)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:135)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:90)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:58)
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:94)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:101)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:47)
	at io.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

lock_table:
  rowkey
  jdbc:mysql://10.104.6.10:3319/fb4_seata_order^^^inventory_order^^^208236
 jdbc:mysql://10.104.6.10:3319/fb4_seata_storage^^^inventory_storage^^^1

global_table:
xid                                                transaction_id   status
10.104.6.96:8091:2029242591    2029242591       5

branch_table:

branch_id             xid                                                        resource_group_id         resource_id
2029242625      10.104.6.96:8091:2029242591                 (NULL)     jdbc:mysql://10.104.6.10:3319/fb4_seata_order            
2029242854      10.104.6.96:8091:2029242591                 (NULL)
jdbc:mysql://10.104.6.10:3319/fb4_seata_storage

### Ⅲ. Describe what you expected to happen
Data should be rolled back normally under pressure test

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

100% probability of occurrence under concurrent pressure measurement

### Ⅴ. Anything else we need to know?
My seata version: 0.9.0

### Ⅵ. Environment:

- JDK version :1.8
- OS :linux
- Others:

**Comment by zjinlei** [comment]
refer: https://github.com/seata/seata/issues/1965

**Comment by wanqiang2046** [comment]
@zjinlei  My demo has no dirty read transaction. Both branch transactions are write, no read, inventory service update, and order service write.

**Comment by wanqiang2046** [comment]
@zjinlei  According to the scenario, there should be no need to strengthen isolation. I tried to add @ GlobalLock annotation to the inventory service, but the same exception will still occur.

**Comment by zjinlei** [comment]
Please package the latest code of develop branch locally, version 1.0.0-SNAPSHOT.
Execute in seata root directory, mvn clean install -DskipTests = true -U -P release-seata.
The server will be automatically generated under the distribution target, delete the bin conf lib directory before generating.

**Comment by JIJL** [comment]
@zjinlei 
I have the same problem, and i build the version 1.0.0-SNAPSHOT package.
I used JMeter to test seata transaction performance, but also got dirty read problem even thought use `SELECT FOR UPDATE` statement.

##### Server Exception
```
2019-12-09 09:57:09.712 ERROR[ServerHandlerThread_1_72_500]io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate:120 -Catch TransactionException while do RPC, request: xid=127.0.0.1:8091:2029584491,branchType=AT,resourceId=jdbc:mysql://127.0.0.1:3
306/db_storage,lockKey=storage_tbl:1io.seata.core.exception.BranchTransactionException: Global lock acquire failed xid = 127.0.0.1:8091:2029584491 branchId = 2029584583
  at io.seata.server.coordinator.DefaultCore.lambda$branchRegister$0(DefaultCore.java:87)
  at io.seata.server.session.GlobalSession.lockAndExcute(GlobalSession.java:597)
  at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:70)
  at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:203)
  at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:172)
  at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:167)
  at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:117)
  at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:167)
  at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
  at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:540)
  at io.seata.core.rpc.DefaultServerMessageListenerImpl.onTrxMessage(DefaultServerMessageListenerImpl.java:92)
  at io.seata.core.rpc.netty.RpcServer.dispatch(RpcServer.java:296)
  at io.seata.core.rpc.netty.AbstractRpcRemoting$3.run(AbstractRpcRemoting.java:368)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
2019-12-09 09:57:09.714 INFO [batchLoggerPrint_1_1]io.seata.core.rpc.DefaultServerMessageListenerImpl.run:201 -SeataMergeMessage xid=127.0.0.1:8091:2029584492,extraData=null
```

**Comment by zjinlei** [comment]
@JIJL 
This exception stack is a branch registration failure, usually a lock conflict, not dirty data.
You can view the detailed description on the server side.

**Comment by JIJL** [comment]
@zjinlei 
It was really my fault.
I have another question. Does seata automate local transactions? Do I still need to handle local transactions manually?

**Comment by xingfudeshi** [comment]
> @zjinlei
> It was really my fault.
> I have another question. Does seata automate local transactions? Do I still need to handle local transactions manually?

You can treat branch transaction as local transaction,so it will be managed by seata.
