### ISSUE TITLE
SEATA-SERVER DB 使用阿里云RDS数据库，会有权限问题

### ISSUE THREAD

**Issue by 604152021** [seata/seata#1998]
SEATA-SERVER session_store 希望存储在阿里云RDS上

希望server支持RDS

**Comment by zjinlei** [comment]
session_store is file mode,db mode is not required.

**Comment by slievrly** [comment]
@604152021 using db mode also supports RDS.

**Comment by 604152021** [comment]
@zjinlei thanks ,but I want to use db mode

**Comment by 604152021** [comment]
@slievrly really? when I use  this samples of springcloud-eureka-feign-mybatis-seata ,some errors occured. Seata server version is 0.9 and seata server use RDS. 

Errors as follow:

java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not register branch into global session xid = 192.168.56.1:8091:2029781908 status = TimeoutRollbackin ]
	at io.seata.rm.datasource.ConnectionProxy.recognizeLockKeyConflictException(ConnectionProxy.java:148) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:210) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:187) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:175) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.ConnectionProxy$$Lambda$539/776965289.call(Unknown Source) ~[na:na]
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:278) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:174) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$0(AbstractDMLBaseExecutor.java:92) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$$Lambda$535/1932714595.call(Unknown Source) ~[na:na]
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:288) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:135) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:90) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:58) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:94) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:101) [seata-all-0.9.0.jar:0.9.0]

Would you help me ?  very thanks.

**Comment by a364176773** [comment]
> @slievrly really? when I use this samples of springcloud-eureka-feign-mybatis-seata ,some errors occured. Seata server version is 0.9 and seata server use RDS.
> 
> Errors as follow:
> 
> java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not register branch into global session xid = 192.168.56.1:8091:2029781908 status = TimeoutRollbackin ]
> at io.seata.rm.datasource.ConnectionProxy.recognizeLockKeyConflictException(ConnectionProxy.java:148) ~[seata-all-0.9.0.jar:0.9.0]
> at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:210) ~[seata-all-0.9.0.jar:0.9.0]
> at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:187) ~[seata-all-0.9.0.jar:0.9.0]
> at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:175) ~[seata-all-0.9.0.jar:0.9.0]
> at io.seata.rm.datasource.ConnectionProxy$$Lambda$539/776965289.call(Unknown Source) ~[na:na]
> at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:278) ~[seata-all-0.9.0.jar:0.9.0]
> at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:174) ~[seata-all-0.9.0.jar:0.9.0]
> at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$0(AbstractDMLBaseExecutor.java:92) [seata-all-0.9.0.jar:0.9.0]
> at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$$Lambda$535/1932714595.call(Unknown Source) ~[na:na]
> at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:288) ~[seata-all-0.9.0.jar:0.9.0]
> at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:135) ~[seata-all-0.9.0.jar:0.9.0]
> at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:90) [seata-all-0.9.0.jar:0.9.0]
> at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:58) [seata-all-0.9.0.jar:0.9.0]
> at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:94) [seata-all-0.9.0.jar:0.9.0]
> at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:101) [seata-all-0.9.0.jar:0.9.0]
> 
> Would you help me ? very thanks.

请查看项目是否连接到seata服务中心,上面的异常貌似是xid传递失败.请问能否一样使用 springcloud-eureka-feign-mybatis-seata ,seata的db设置为本地的库试试有无此异常
