### ISSUE TITLE
使用seata后，如果一次回滚的时候遭遇网络延时，或断点阻隔就会出现这个问题

### ISSUE THREAD

**Issue by wendao8469759** [seata/seata#2046]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_191]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_191]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_191]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_191]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_191]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628) [netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563) [netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) [netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

**Comment by wendao8469759** [comment]
并且会影响项目正常访问，请问此类问题应该如何解决呀 大神~ 就帮助

**Comment by cmonkey** [comment]
能给个测试用例吗

**Comment by wendao8469759** [comment]
这是工程文件

**Comment by wendao8469759** [comment]
项目地址
http://git.81dd.cn/root/test-seata.git

**Comment by a364176773** [comment]
确认下是不是发起者出现的异常,可能是AT模式你的事务较长,处理时间长了,接口返回超时导致的.

**Comment by wendao8469759** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"FUNKYE"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月25日(星期三) 中午1:45
收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;;
抄送:&nbsp;"掌心的溫度丶"<942837091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] 使用seata后，如果一次回滚的时候遭遇网络延时，或断点阻隔就会出现这个问题 (#2046)




确认下是不是发起者出现的异常,可能是AT模式你的事务较长,处理时间长了,接口返回超时导致的.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.




应该是资源为关闭导致的。 1.0版本为出现此问题
