### ISSUE TITLE
docker compose 指定自定义配置文件启动seata-server失败

### ISSUE THREAD

**Issue by niushihao** [seata/seata#2060]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. 错误日志

```
Exception in thread "main" io.seata.common.exception.NotSupportYetException: not support register type: null
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:103)
	at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:87)
	at io.seata.server.metrics.MetricsManager.init(MetricsManager.java:49)
	at io.seata.server.Server.main(Server.java:66)
Caused by: java.lang.IllegalArgumentException: illegal type:null
	at io.seata.config.ConfigType.getType(ConfigType.java:70)
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:101)
	... 3 more
```

#### docker-compose
```
version: '3.5'
services:
  seata-server:
    image: seataio/seata-server
    hostname: seata-server
    ports:
      - "8091:8091"
    volumes:
      - /usr/local/docker/seata/logs:/root/logs/seata
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
      - SEATA_CONFIG_NAME=file:/usr/local/docker/seata/registry
```
#### registry
```
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "file"

  nacos {
    serverAddr = "localhost"
    namespace = ""
    cluster = "default"
  }
  eureka {
    serviceUrl = "http://localhost:8761/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = "0"
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
  }
  etcd3 {
    cluster = "default"
    serverAddr = "http://localhost:2379"
  }
  sofa {
    serverAddr = "127.0.0.1:9603"
    application = "default"
    region = "DEFAULT_ZONE"
    datacenter = "DefaultDataCenter"
    cluster = "default"
    group = "SEATA_GROUP"
    addressWaitTime = "3000"
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "file"

  nacos {
    serverAddr = "localhost"
    namespace = ""
  }
  consul {
    serverAddr = "127.0.0.1:8500"
  }
  apollo {
    app.id = "seata-server"
    apollo.meta = "http://192.168.1.204:8801"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  etcd3 {
    serverAddr = "http://localhost:2379"
  }
  file {
    name = "file.conf"
  }
}
```
#### file
```
service {
  #transaction service group mapping
  vgroup_mapping.my_test_tx_group = "default"
  #only support when registry.type=file, please don't set multiple addresses
  default.grouplist = "127.0.0.1:8091"
  #disable seata
  disableGlobalTransaction = false
}

## transaction log store, only used in seata-server
store {
  ## store mode: file、db
  mode = "file"

  ## file store property
  file {
    ## store location dir
    dir = "sessionStore"
  }

  ## database store property
  db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "dbcp"
    ## mysql/oracle/h2/oceanbase etc.
    db-type = "mysql"
    driver-class-name = "com.mysql.jdbc.Driver"
    url = "jdbc:mysql://127.0.0.1:3306/seata"
    user = "mysql"
    password = "mysql"
  }
}
```

### Ⅳ. 复现

1. 在docker-compose指定外部配置文件配置(SEATA_CONFIG_NAME=file:/usr/local/docker/seata/registry)

### Ⅵ. Environment:

- JDK version :1.8
- OS :mac
- Others: docker version 19.03.1

**Comment by helloworlde** [comment]
配置错了，`SEATA_CONFIG_NAME` 这个配置的路径指向的是容器内的路径，改成`/root/logs/seata`

**Comment by niushihao** [comment]
嗯嗯，谢谢

**Comment by Garlichead** [comment]
> 嗯嗯，谢谢

老铁 您解决了吗 因为我这边也是遇到了同样的问题 我用docker run命令创建了container 我把自定义配置文件复制到了我创建了container 但是我不知道如何使用docker run的参数启动container 因为docker run 默认会去创建一个新的container docker start 似乎后面也不可以设置自定义配置文件启动参数
![image](https://user-images.githubusercontent.com/45086633/78856975-b923d500-7a5a-11ea-9c3a-7fc8ae751b60.png)

**Comment by niushihao** [comment]
可以试试用docker compose启动,或者用docker run -v -e指定参数，不需要自己复制文件

**Comment by Garlichead** [comment]
> 可以试试用docker compose启动,或者用docker run -v -e指定参数，不需要自己复制文件

docker run -v -e 的话 无法制定自定义配置文件吧

**Comment by niushihao** [comment]
-v可以把宿主机和容器的文件建立映射,相当于宿主机的配置被添加到了镜像中

**Comment by Garlichead** [comment]
> -v可以把宿主机和容器的文件建立映射,相当于宿主机的配置被添加到了镜像中

明白 我记得-v 后面有一个置顶配置文件路径的 和那个是冲突的吗
 您这边用compose启动的步骤是什么？

**Comment by helloworlde** [comment]
> > -v可以把宿主机和容器的文件建立映射,相当于宿主机的配置被添加到了镜像中
> 
> 明白 我记得-v 后面有一个置顶配置文件路径的 和那个是冲突的吗
> 您这边用compose启动的步骤是什么？

参考文档 https://seata.io/zh-cn/docs/ops/deploy-by-docker.html

**Comment by Garlichead** [comment]
![image](https://user-images.githubusercontent.com/45086633/78862627-65b98300-7a6a-11ea-9ffb-5895b3643413.png)
老哥 您看我的启动参数里面有 -e -v 了

**Comment by Garlichead** [comment]
![image](https://user-images.githubusercontent.com/45086633/78863070-525ae780-7a6b-11ea-887d-f9b3428f7d7e.png)
老哥 我确定宿主机器的这俩个地址肯定是有文件的

**Comment by helloworlde** [comment]
> ![image](https://user-images.githubusercontent.com/45086633/78862627-65b98300-7a6a-11ea-9ffb-5895b3643413.png)
> 老哥 您看我的启动参数里面有 -e -v 了

看看文档内容怎么写的，先学下 docker 的基础命令，start 启动已有容器，run 创建容器

**Comment by Garlichead** [comment]
![image](https://user-images.githubusercontent.com/45086633/78863509-59cec080-7a6c-11ea-870c-6e792f08762b.png)
万万没想到 我按照这个命令启动了 按照官方文档的命令 一直推送那个异常
