### ISSUE TITLE
seata does not support mybatis feature of batch-update

### ISSUE THREAD

**Issue by uioprty** [seata/seata#2075]
Caused by: java.lang.UnsupportedOperationException: Unsupported SQL: UPDATE merged_coupon
             SET state=4 
             WHERE id = ? 
         ; 
            UPDATE merged_coupon
             SET state=4 
             WHERE id = ?
	at io.seata.rm.datasource.sql.SQLVisitorFactory.get(SQLVisitorFactory.java:52) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.AbstractConnectionProxy.prepareStatement(AbstractConnectionProxy.java:110) ~[seata-all-0.9.0.jar:0.9.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_221]
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55) ~[mybatis-3.4.6.jar:3.4.6]
	at com.sun.proxy.$Proxy184.prepareStatement(Unknown Source) ~[na:na]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:87) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88) ~[mybatis-3.4.6.jar:3.4.6]
	... 31 common frames omitted

**Comment by zjinlei** [comment]
Sorry, temporarily not supported.

**Comment by wuwenhui0917** [comment]
目前不支持批量
