### ISSUE TITLE
registry.conf的config中type=nacos报错：ErrCode:-400, ErrMsg:endpoint is blank

### ISSUE THREAD

**Issue by Licoy** [seata/seata#2079]
### 错误
当registry.conf的config的type=nacos时就会报这个错误，换成file就没有问题，原因未知
### 具体异常信息
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'globalTransactionScanner' defined in class path resource [com/hms/game/service/user/provider/config/SeataAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is java.lang.RuntimeException: ErrCode:-400, ErrMsg:endpoint is blank
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:591) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1246) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:224) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:708) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230) [spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at com.hms.game.service.user.provider.GameServiceUserProviderApplication.main(GameServiceUserProviderApplication.java:30) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is java.lang.RuntimeException: ErrCode:-400, ErrMsg:endpoint is blank
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.RuntimeException: ErrCode:-400, ErrMsg:endpoint is blank
	at io.seata.config.nacos.NacosConfiguration.<init>(NacosConfiguration.java:82) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.config.nacos.NacosConfiguration.getInstance(NacosConfiguration.java:67) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.config.nacos.NacosConfigurationProvider.provide(NacosConfigurationProvider.java:29) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:124) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:87) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:90) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:134) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:123) ~[seata-all-1.0.0.jar:1.0.0]
	at com.hms.game.service.user.provider.config.SeataAutoConfig.globalTransactionScanner(SeataAutoConfig.java:48) ~[classes/:na]
	at com.hms.game.service.user.provider.config.SeataAutoConfig$$EnhancerBySpringCGLIB$$3d86318c.CGLIB$globalTransactionScanner$0(<generated>) ~[classes/:na]
	at com.hms.game.service.user.provider.config.SeataAutoConfig$$EnhancerBySpringCGLIB$$3d86318c$$FastClassBySpringCGLIB$$411bf14e.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at com.hms.game.service.user.provider.config.SeataAutoConfig$$EnhancerBySpringCGLIB$$3d86318c.globalTransactionScanner(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	... 19 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: java.lang.reflect.InvocationTargetException
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:45) ~[nacos-api-1.1.4.jar:na]
	at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:43) ~[nacos-api-1.1.4.jar:na]
	at io.seata.config.nacos.NacosConfiguration.<init>(NacosConfiguration.java:80) ~[seata-all-1.0.0.jar:1.0.0]
	... 37 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_201]
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:42) ~[nacos-api-1.1.4.jar:na]
	... 39 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: endpoint is blank
	at com.alibaba.nacos.client.config.impl.ServerListManager.<init>(ServerListManager.java:154) ~[nacos-client-1.1.4.jar:na]
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.<init>(ServerHttpAgent.java:244) ~[nacos-client-1.1.4.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.<init>(NacosConfigService.java:83) ~[nacos-client-1.1.4.jar:na]
	... 44 common frames omitted
```

**Comment by Licoy** [comment]
启动报错，提示：`ErrCode:-400, ErrMsg:endpoint is blank`

**Comment by Licoy** [comment]
当registry.conf的`config`的`type=nacos`时就会报这个错误，换成`file`就没有问题，原因未知

**Comment by slievrly** [comment]
@Licoy paste the registry.conf file.

**Comment by Licoy** [comment]
现在已经没有错误了，不知怎么回事儿

**Comment by yuluo-yx** [comment]
我也遇到了此问题，您有什么处理方式吗，针对此问题？@Licoy @slievrly 
提问之前，我参考了 seata 官网进行配置。

> seata version: 1.8.0
> nacos version: 2.2.1

```yml
server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${log.home:${user.home}/logs/seata}
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

console:
  user:
    username: seata
    password: seata
seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: nacos
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: nacos
  store:
    # support: file 、 db 、 redis
    mode: db
#  server:
#    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login
```

```conf
config {
  type = "nacos"

  nacos {
    serverAddr = "127.0.0.1:8848"
    username = "nacos"
    password = "nacos"
  }
}
```

启动 seata-server.bat 的堆栈异常
```md
=>
java.lang.ExceptionInInitializerError: null
        at io.seata.server.spring.listener.SeataPropertiesLoader.initialize(SeataPropertiesLoader.java:76) ~[classes!/:1.8.0]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:648) ~[spring-boot-2.5.13.jar:2.5.13]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:417) ~[spring-boot-2.5.13.jar:2.5.13]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.13.jar:2.5.13]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365) ~[spring-boot-2.5.13.jar:2.5.13]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-2.5.13.jar:2.5.13]
        at io.seata.server.ServerApplication.main(ServerApplication.java:31) ~[classes!/:1.8.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[seata-server.jar:1.8.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[seata-server.jar:1.8.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[seata-server.jar:1.8.0]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) ~[seata-server.jar:1.8.0]
Caused by: java.lang.RuntimeException: ErrCode:-400, ErrMsg:endpoint is blank
        at io.seata.config.nacos.NacosConfiguration.<init>(NacosConfiguration.java:100) ~[seata-config-nacos-1.8.0.jar:1.8.0]
        at io.seata.config.nacos.NacosConfiguration.getInstance(NacosConfiguration.java:84) ~[seata-config-nacos-1.8.0.jar:1.8.0]
        at io.seata.config.nacos.NacosConfigurationProvider.provide(NacosConfigurationProvider.java:29) ~[seata-config-nacos-1.8.0.jar:1.8.0]
        at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:160) ~[seata-config-core-1.8.0.jar:1.8.0]
        at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:112) ~[seata-config-core-1.8.0.jar:1.8.0]
        at io.seata.server.store.StoreConfig.<clinit>(StoreConfig.java:33) ~[classes!/:1.8.0]
        ... 15 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: java.lang.reflect.InvocationTargetException
        at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:46) ~[nacos-api-1.4.2.jar:na]
        at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:44) ~[nacos-api-1.4.2.jar:na]
        at io.seata.config.nacos.NacosConfiguration.<init>(NacosConfiguration.java:97) ~[seata-config-nacos-1.8.0.jar:1.8.0]
        ... 20 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
        at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:43) ~[nacos-api-1.4.2.jar:na]
        ... 22 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: endpoint is blank
        at com.alibaba.nacos.client.config.impl.ServerListManager.<init>(ServerListManager.java:183) ~[nacos-client-1.4.2.jar:na]
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.<init>(ServerHttpAgent.java:274) ~[nacos-client-1.4.2.jar:na]
        at com.alibaba.nacos.client.config.NacosConfigService.<init>(NacosConfigService.java:88) ~[nacos-client-1.4.2.jar:na]
        ... 27 common frames omitted
<==

20:54:02.573  WARN --- [                 Thread-0] [mmon.http.HttpClientBeanHolder] [            shutdown]  [] : [HttpClientBeanHolder] Start destroying common HttpClient
20:54:02.573  WARN --- [                 Thread-0] [mmon.http.HttpClientBeanHolder] [            shutdown]  [] : [HttpClientBeanHolder] Destruction of the end
```

**Comment by 3-8UUID** [comment]
I had the same exception when I used the ".zip" suffix for the package. After I changed the package to ".tar.gz" suffix, the exception was resolved.

**Comment by HoldEvan** [comment]
> 我也遇到了此问题，您有什么处理方式吗，针对此问题？@Licoy @slievrly 提问之前，我参考了 seata 官网进行配置。
> 
> > seata version: 1.8.0
> > nacos version: 2.2.1
> 
> ```yaml
> server:
>   port: 7091
> 
> spring:
>   application:
>     name: seata-server
> 
> logging:
>   config: classpath:logback-spring.xml
>   file:
>     path: ${log.home:${user.home}/logs/seata}
>   extend:
>     logstash-appender:
>       destination: 127.0.0.1:4560
>     kafka-appender:
>       bootstrap-servers: 127.0.0.1:9092
>       topic: logback_to_logstash
> 
> console:
>   user:
>     username: seata
>     password: seata
> seata:
>   config:
>     # support: nacos, consul, apollo, zk, etcd3
>     type: nacos
>   registry:
>     # support: nacos, eureka, redis, zk, consul, etcd3, sofa
>     type: nacos
>   store:
>     # support: file 、 db 、 redis
>     mode: db
> #  server:
> #    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
>   security:
>     secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
>     tokenValidityInMilliseconds: 1800000
>     ignore:
>       urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login
> ```
> 
> ```
> config {
>   type = "nacos"
> 
>   nacos {
>     serverAddr = "127.0.0.1:8848"
>     username = "nacos"
>     password = "nacos"
>   }
> }
> ```
> 
> 启动 seata-server.bat 的堆栈异常
> 
> ```
> =>
> java.lang.ExceptionInInitializerError: null
>         at io.seata.server.spring.listener.SeataPropertiesLoader.initialize(SeataPropertiesLoader.java:76) ~[classes!/:1.8.0]
>         at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:648) ~[spring-boot-2.5.13.jar:2.5.13]
>         at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:417) ~[spring-boot-2.5.13.jar:2.5.13]
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.13.jar:2.5.13]
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365) ~[spring-boot-2.5.13.jar:2.5.13]
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-2.5.13.jar:2.5.13]
>         at io.seata.server.ServerApplication.main(ServerApplication.java:31) ~[classes!/:1.8.0]
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
>         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[seata-server.jar:1.8.0]
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[seata-server.jar:1.8.0]
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[seata-server.jar:1.8.0]
>         at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) ~[seata-server.jar:1.8.0]
> Caused by: java.lang.RuntimeException: ErrCode:-400, ErrMsg:endpoint is blank
>         at io.seata.config.nacos.NacosConfiguration.<init>(NacosConfiguration.java:100) ~[seata-config-nacos-1.8.0.jar:1.8.0]
>         at io.seata.config.nacos.NacosConfiguration.getInstance(NacosConfiguration.java:84) ~[seata-config-nacos-1.8.0.jar:1.8.0]
>         at io.seata.config.nacos.NacosConfigurationProvider.provide(NacosConfigurationProvider.java:29) ~[seata-config-nacos-1.8.0.jar:1.8.0]
>         at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:160) ~[seata-config-core-1.8.0.jar:1.8.0]
>         at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:112) ~[seata-config-core-1.8.0.jar:1.8.0]
>         at io.seata.server.store.StoreConfig.<clinit>(StoreConfig.java:33) ~[classes!/:1.8.0]
>         ... 15 common frames omitted
> Caused by: com.alibaba.nacos.api.exception.NacosException: java.lang.reflect.InvocationTargetException
>         at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:46) ~[nacos-api-1.4.2.jar:na]
>         at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:44) ~[nacos-api-1.4.2.jar:na]
>         at io.seata.config.nacos.NacosConfiguration.<init>(NacosConfiguration.java:97) ~[seata-config-nacos-1.8.0.jar:1.8.0]
>         ... 20 common frames omitted
> Caused by: java.lang.reflect.InvocationTargetException: null
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
>         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
>         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
>         at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:43) ~[nacos-api-1.4.2.jar:na]
>         ... 22 common frames omitted
> Caused by: com.alibaba.nacos.api.exception.NacosException: endpoint is blank
>         at com.alibaba.nacos.client.config.impl.ServerListManager.<init>(ServerListManager.java:183) ~[nacos-client-1.4.2.jar:na]
>         at com.alibaba.nacos.client.config.http.ServerHttpAgent.<init>(ServerHttpAgent.java:274) ~[nacos-client-1.4.2.jar:na]
>         at com.alibaba.nacos.client.config.NacosConfigService.<init>(NacosConfigService.java:88) ~[nacos-client-1.4.2.jar:na]
>         ... 27 common frames omitted
> <==
> 
> 20:54:02.573  WARN --- [                 Thread-0] [mmon.http.HttpClientBeanHolder] [            shutdown]  [] : [HttpClientBeanHolder] Start destroying common HttpClient
> 20:54:02.573  WARN --- [                 Thread-0] [mmon.http.HttpClientBeanHolder] [            shutdown]  [] : [HttpClientBeanHolder] Destruction of the end
> ```

解决了吗

**Comment by yuluo-yx** [comment]
> 解决了吗

> s可以参考：https://blog.csdn.net/qq_52397471/article/details/135563989?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522172369784716800207066339%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fblog.%2522%257D&request_id=172369784716800207066339&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~blog~first_rank_ecpm_v1~rank_v31_ecpm-1-135563989-null-null.nonecase&utm_term=seata&spm=1018.2226.3001.4450
