### ISSUE TITLE
seata1.0.0使用HikariDataSource报错

### ISSUE THREAD

**Issue by 852675742** [seata/seata#2083]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用seata1.0.0启动异常，使用的HikariDataSource数据源

Caused by: java.lang.ClassCastException: com.sun.proxy.$Proxy153 cannot be cast to com.zaxxer.hikari.HikariDataSource
	at com.zaxxer.hikari.HikariDataSource$$FastClassBySpringCGLIB$$eeb1ae86.invoke(<generated>) ~[HikariCP-3.2.0.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:136) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at com.zaxxer.hikari.HikariDataSource$$EnhancerBySpringCGLIB$$6a826bb5.getConnection(<generated>) ~[HikariCP-3.2.0.jar:na]
	at io.seata.rm.datasource.DataSourceProxy.init(DataSourceProxy.java:85) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:80) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:69) ~[seata-all-1.0.0.jar:1.0.0]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_91]
	at io.seata.spring.annotation.datasource.DataSourceProxyHolder.putDataSource(DataSourceProxyHolder.java:64) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.postProcessAfterInitialization(GlobalTransactionScanner.java:326) ~[seata-all-1.0.0.jar:1.0.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:429) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.postProcessObjectFromFactoryBean(AbstractAutowireCapableBeanFactory.java:1920) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:116) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	... 43 common frames omitted

![image](https://user-images.githubusercontent.com/19749064/71405789-653edd00-2671-11ea-8b45-0646df9603ae.png)

客户端registry.conf如下
registry {
  # file 、nacos 、eureka、redis、zk
  type = "file"

  nacos {
    serverAddr = "localhost"
    namespace = ""
    cluster = "default"
  }
  eureka {
    serviceUrl = "http://localhost:8761/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6381"
    db = "0"
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk
  type = "file"

  nacos {
    serverAddr = "localhost"
    namespace = ""
    cluster = "default"
  }
  apollo {
    app.id = "fescar-server"
    apollo.meta = "http://192.168.1.204:8801"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  file {
    name = "file.conf"
  }
}

file.conf如下
service {
      vgroup_mapping.my_test_tx_group = "default"
      default.grouplist = "127.0.0.1:8091"
}

数据源配置如下
![image](https://user-images.githubusercontent.com/19749064/71406117-3d03ae00-2672-11ea-8c9e-6e1b943695f0.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
![image](https://user-images.githubusercontent.com/19749064/71405656-0da07180-2671-11ea-9a86-944c538780b0.png)

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows
- Others:

**Comment by zjinlei** [comment]
Thanks!
repeated issue https://github.com/seata/seata/issues/2067

**Comment by xingfudeshi** [comment]
Please provide full exception traces.@852675742

**Comment by xingfudeshi** [comment]
It will be greate if you provide a demo to reproduce this problem.
