### ISSUE TITLE
oracle支持问题，seata在判断oracle表主键的问题

### ISSUE THREAD

**Issue by dadatou20089** [seata/seata#2119]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata在判断表主键的过程中使用了mysql相同的判断方式，这并不适用oracle的情况，例如oracle中除了索引还有约束，约束中区分主键，而索引的类型是没有primary类型的，最常用的是unique, 因此
TableMeta.getPrimaryKeyMap只适用于mysql, oracle需要区分对待。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 通过mybatis编写insert语句
2. 创建oracle表, 表中创建唯一索引，以及主键约束
3. 通过整合seata执行语句

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by huzhanqiu** [comment]
我也遇到这个问题，判断没有猪键报错。
`io.seata.common.exception.NotSupportYetException: TB_ST_AJJBXX needs to contain the primary key.
	at io.seata.rm.datasource.sql.struct.TableMeta.getPrimaryKeyMap(TableMeta.java:129) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.sql.struct.TableMeta.getPrimaryKeyOnlyName(TableMeta.java:143) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.sql.struct.TableMeta.containsPK(TableMeta.java:178) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.exec.UpdateExecutor.buildBeforeImageSQL(UpdateExecutor.java:70) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.exec.UpdateExecutor.beforeImage(UpdateExecutor.java:62) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:72) [seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$0(AbstractDMLBaseExecutor.java:91) [seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:293) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:135) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:90) [seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:58) [seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:95) [seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:101) [seata-all-1.0.0.jar:1.0.0]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:47) [seata-all-1.0.0.jar:1.0.0]`

**Comment by Garlichead** [comment]
不知道这个点解决了吗 正准备打算mysql和oracle和mongodb混合shi yong

**Comment by jsbxyyx** [comment]
The latest version(1.2.0) has been resolved.

**Comment by Xus4** [comment]
> 
> 
> 我也遇到这个问题，判断没有猪键报错。
> `io.seata.common.exception.NotSupportYetException: TB_ST_AJJBXX needs to contain the primary key. at io.seata.rm.datasource.sql.struct.TableMeta.getPrimaryKeyMap(TableMeta.java:129) ~[seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.sql.struct.TableMeta.getPrimaryKeyOnlyName(TableMeta.java:143) ~[seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.sql.struct.TableMeta.containsPK(TableMeta.java:178) ~[seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.exec.UpdateExecutor.buildBeforeImageSQL(UpdateExecutor.java:70) ~[seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.exec.UpdateExecutor.beforeImage(UpdateExecutor.java:62) ~[seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:72) [seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$0(AbstractDMLBaseExecutor.java:91) [seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:293) ~[seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:135) ~[seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:90) [seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:58) [seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:95) [seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:101) [seata-all-1.0.0.jar:1.0.0] at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:47) [seata-all-1.0.0.jar:1.0.0]`

最近搭建新的测试环境，oracle数据库表结构是从现有环境的库导出的用户对象sql（DDL）,然后重新在新的库上执行，部署微服务应用后，保存时seata报错“table xxx needs to contain the primary key”。
经排查该表有主键。问题一度陷入僵局......
后来通过分析seata源码发现，seata是根据indexs来找主键的，所以检查了一下索引，结果发现没有主键id的索引！但是有一个id和typeid的组合索引！
直接上分析结果：
建表sql在创建主键前，先执行了创建id和typeid的组合索引，导致创建主键时，id字段单独的索引没建上；去掉组合索引的创建或者先创建主键再创建组合索引，就有主键id字段单独的索引了，事务也正常了。
