### ISSUE TITLE
如何配置seata server集群

### ISSUE THREAD

**Issue by 852675742** [seata/seata#2138]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
采用eureka server作为注册中心，启动2个seata server，当停止其中一个seata server，微服务客户端一直提示连接；参照文档设置了eureka.lease.renewalInterval=1和eureka.lease.duration=2，仍需要30秒左右才能切换到另外一个正常的seata server。

2020-01-04 23:06:32.896  INFO 4352 --- [imeoutChecker_1] i.s.c.r.netty.NettyClientChannelManager  : will connect to 172.20.10.2:8092
2020-01-04 23:06:32.896  INFO 4352 --- [imeoutChecker_1] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:TMROLE,address:172.20.10.2:8092,msg:< RegisterTMRequest{applicationId='storage-server', transactionServiceGroup='fsp_tx_group'} >
2020-01-04 23:06:32.930  INFO 4352 --- [imeoutChecker_2] i.s.c.r.netty.NettyClientChannelManager  : will connect to 172.20.10.2:8092
2020-01-04 23:06:32.934  INFO 4352 --- [imeoutChecker_2] io.seata.core.rpc.netty.RmRpcClient      : RM will register :jdbc:mysql://127.0.0.1:3306/seat-storage
2020-01-04 23:06:32.934  INFO 4352 --- [imeoutChecker_2] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:RMROLE,address:172.20.10.2:8092,msg:< RegisterRMRequest{resourceIds='jdbc:mysql://127.0.0.1:3306/seat-storage', applicationId='storage-server', transactionServiceGroup='fsp_tx_group'} >
2020-01-04 23:06:34.901  INFO 4352 --- [lector_TMROLE_1] i.s.core.rpc.netty.AbstractRpcRemoting   : ChannelHandlerContext(TmRpcClient#0, [id: 0xbe57b2b9]) will closed
2020-01-04 23:06:34.902 ERROR 4352 --- [imeoutChecker_1] i.s.c.r.netty.NettyClientChannelManager  : 0304 register RM failed.
io.seata.common.exception.FrameworkException: can not connect to services-server.
	at io.seata.core.rpc.netty.RpcClientBootstrap.getNewChannel(RpcClientBootstrap.java:195) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:58) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:34) ~[seata-all-1.0.0.jar:1.0.0]
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220) ~[commons-pool-1.6.jar:1.6]
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:206) [seata-all-1.0.0.jar:1.0.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:103) [seata-all-1.0.0.jar:1.0.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:175) [seata-all-1.0.0.jar:1.0.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient$1.run(AbstractRpcRemotingClient.java:112) [seata-all-1.0.0.jar:1.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.39.Final.jar:4.1.39.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
Caused by: io.seata.common.exception.FrameworkException: connect failed, can not connect to services-server.
	at io.seata.core.rpc.netty.RpcClientBootstrap.getNewChannel(RpcClientBootstrap.java:190) ~[seata-all-1.0.0.jar:1.0.0]
	... 16 common frames omitted

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

![QQ图片20200104230544](https://user-images.githubusercontent.com/19749064/71767440-690f1100-2f47-11ea-9c17-645380a8e82b.png)

```
Just paste your stack trace here!
```
### 

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zjinlei** [comment]
https://github.com/seata/seata/issues/1568
