### ISSUE TITLE
Could not register branch into global session xid 

### ISSUE THREAD

**Issue by liupantao** [seata/seata#2161]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Caused by: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not register branch into global session xid = 192.168.181.1:8091:2032286230 status = AsyncCommitting] ]
	
```

### Ⅲ. Describe what you expected to happen
Caused by: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not register branch into global session xid = 192.168.181.1:8091:2032286230 status = AsyncCommitting] ]
	at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:69)
	at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96)
	at io.seata.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:233)
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:211)
	... 51 common frames omitted

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- OS :
- Others: windows

**Comment by zjinlei** [comment]
https://seata.io/zh-cn/docs/overview/faq.html#6
