### ISSUE TITLE
io.seata.core.rpc.netty.NettyClientChannelManager][205]:0304 register RM failed

### ISSUE THREAD

**Issue by BlueGuo** [seata/seata#2169]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### **Multi module project use dubbo、zookeeper、seata，
dubbo、zookeeper、seata、mysql ... run on the centos 7.6 ，and project run on win10 whit IntelliJ IDEA 2019，the project run normal！
But！！！when the project run on centos 7.6 with tomcat9，provider module A、B、C runs normal，but consume module D could not run normal。**

 ```
           <dependency>
                <groupId>io.seata</groupId>
                <artifactId>seata-all</artifactId>
                <version>${seata.version}</version>
            </dependency>

<seata.version>0.9.0</seata.version>
```
--------------------
Module start sequence
A>B>C>D

=================config file=======================
【registry.conf】
registry {
  type = "file"

  file {
    name = "file.conf"
  }
}
config {
  # file、nacos 、apollo、zk、consul
  type = "file"

  file {
    name = "file.conf"
  }
}

【file.conf】
transport {
  # tcp udt unix-domain-socket
  type = "TCP"
  #NIO NATIVE
  server = "NIO"
  #enable heartbeat
  heartbeat = true
  #thread factory for netty
  thread-factory {
    boss-thread-prefix = "NettyBoss"
    worker-thread-prefix = "NettyServerNIOWorker"
    server-executor-thread-prefix = "NettyServerBizHandler"
    share-boss-worker = false
    client-selector-thread-prefix = "NettyClientSelector"
    client-selector-thread-size = 1
    client-worker-thread-prefix = "NettyClientWorkerThread"
    # netty boss thread size,will not be used for UDT
    boss-thread-size = 1
    #auto default pin or 8
    worker-thread-size = 8
  }
  shutdown {
    # when destroy server, wait seconds
    wait = 3
  }
  serialization = "seata"
  compressor = "none"
}
service {
  #vgroup->rgroup
  vgroup_mapping.beijixing_tx_group = "default"
  #only support single node
  default.grouplist = "192.168.2.167:8091"
  #degrade current not support
  enableDegrade = false
  #disable
  disable = false
  #unit ms,s,m,h,d represents milliseconds, seconds, minutes, hours, days, default permanent
  max.commit.retry.timeout = "-1"
  max.rollback.retry.timeout = "-1"
}

client {
  async.commit.buffer.limit = 10000
  lock {
    retry.internal = 10
    retry.times = 30
  }
  report.retry.count = 5
  tm.commit.retry.count = 1
  tm.rollback.retry.count = 1
}

## transaction log store
store {
  ## store mode: file、db
  mode = "file"

  ## file store
  file {
    dir = "sessionStore"

    # branch session size , if exceeded first try compress lockkey, still exceeded throws exceptions
    max-branch-session-size = 16384
    # globe session size , if exceeded throws exceptions
    max-global-session-size = 512
    # file buffer size , if exceeded allocate new buffer
    file-write-buffer-cache-size = 16384
    # when recover batch read size
    session.reload.read_size = 100
    # async, sync
    flush-disk-mode = async
  }

  ## database store
  db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "dbcp"
    ## mysql/oracle/h2/oceanbase etc.
    db-type = "mysql"
    driver-class-name = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://192.168.2.167:3306/db_xxx"
    user = "xxxx"
    password = "xxxxxxxx"
    min-conn = 1
    max-conn = 3
    global.table = "global_table"
    branch.table = "branch_table"
    lock-table = "lock_table"
    query-limit = 100
  }
}
lock {
  ## the lock store mode: local、remote
  mode = "remote"

  local {
    ## store locks in user's database
  }

  remote {
    ## store locks in the seata's server
  }
}
recovery {
  #schedule committing retry period in milliseconds
  committing-retry-period = 1000
  #schedule asyn committing retry period in milliseconds
  asyn-committing-retry-period = 1000
  #schedule rollbacking retry period in milliseconds
  rollbacking-retry-period = 1000
  #schedule timeout retry period in milliseconds
  timeout-retry-period = 1000
}

transaction {
  undo.data.validation = true
  undo.log.serialization = "jackson"
  undo.log.save.days = 7
  #schedule delete expired undo_log in milliseconds
  undo.log.delete.period = 86400000
  undo.log.table = "undo_log"
}

## metrics settings
metrics {
  enabled = false
  registry-type = "compact"
  # multi exporters use comma divided
  exporter-list = "prometheus"
  exporter-prometheus-port = 9898
}

support {
  ## spring
  spring {
    # auto proxy the DataSource bean
    datasource.autoproxy = false
  }
}

### Ⅱ. Describe what happened

【error logs】

```
[2020-01-10 19:35:00.513][timeoutChecker_1][INFO][io.seata.core.rpc.netty.NettyClientChannelManager][98]:will connect to 192.168.2.167:8091
[2020-01-10 19:35:00.513][timeoutChecker_1][INFO][io.seata.core.rpc.netty.NettyPoolableFactory][58]:NettyPool create channel to transactionRole:TMROLE,address:192.168.2.167:8091,msg:< RegisterTMRequest{applicationId='beijixing-core', transactionServiceGroup='beijixing_tx_group'} >
[2020-01-10 19:35:00.514][timeoutChecker_1][WARN][org.elasticsearch.transport.netty4.Netty4InternalESLogger][149]:Force-closing a channel whose registration task was not accepted by an event loop: [id: 0xefa17999]
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:471) [netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:87) [netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:81) [netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86) [netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:315) [netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155) [netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139) [netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.seata.core.rpc.netty.RpcClientBootstrap.getNewChannel(RpcClientBootstrap.java:184) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:60) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:35) [seata-all-0.9.0.jar:0.9.0]
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220) [commons-pool-1.6.jar:1.6]
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:202) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:102) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:171) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient$1.run(AbstractRpcRemotingClient.java:113) [seata-all-0.9.0.jar:0.9.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.44.Final.jar:4.1.44.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[2020-01-10 19:35:00.516][timeoutChecker_1][ERROR][io.seata.core.rpc.netty.NettyClientChannelManager][205]:0304 register RM failed.
io.seata.common.exception.FrameworkException: can not connect to services-server.
	at io.seata.core.rpc.netty.RpcClientBootstrap.getNewChannel(RpcClientBootstrap.java:195) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:60) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:35) ~[seata-all-0.9.0.jar:0.9.0]
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220) ~[commons-pool-1.6.jar:1.6]
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:202) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:102) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:171) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient$1.run(AbstractRpcRemotingClient.java:113) [seata-all-0.9.0.jar:0.9.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.44.Final.jar:4.1.44.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: io.seata.common.exception.FrameworkException: connect failed, can not connect to services-server.
	at io.seata.core.rpc.netty.RpcClientBootstrap.getNewChannel(RpcClientBootstrap.java:190) ~[seata-all-0.9.0.jar:0.9.0]
	... 15 more
Caused by: java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:471) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:87) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:81) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:315) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139) ~[netty-all-4.1.44.Final.jar:4.1.44.Final]
	at io.seata.core.rpc.netty.RpcClientBootstrap.getNewChannel(RpcClientBootstrap.java:184) ~[seata-all-0.9.0.jar:0.9.0]
	... 15 more
[2020-01-10 19:35:00.517][timeoutChecker_1][ERROR][io.seata.core.rpc.netty.NettyClientChannelManager][173]:0101 can not connect to 192.168.2.167:8091 cause:can not register RM,err:can not connect to services-server.
io.seata.common.exception.FrameworkException: can not register RM,err:can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:206) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:102) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:171) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient$1.run(AbstractRpcRemotingClient.java:113) [seata-all-0.9.0.jar:0.9.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.44.Final.jar:4.1.44.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

### Ⅲ. Describe what you expected to happen
The module usually start normal，and  log like this：
-------------------------------------------------------------------
```
[2020-01-10 19:34:56.384][NettyClientSelector_TMROLE_1][DEBUG][io.seata.core.rpc.netty.AbstractRpcRemotingClient][139]:received PONG from /192.168.2.167:8091
[2020-01-10 19:34:56.468][main-SendThread(192.168.2.167:2181)][DEBUG][org.apache.zookeeper.ClientCnxn$SendThread][742]:Got ping response for sessionid: 0x1009726709f0045 after 0ms
[2020-01-10 19:34:57.088][NettyClientSelector_TMROLE_1][DEBUG][io.seata.core.rpc.netty.AbstractRpcRemotingClient][202]:will send ping msg,channel[id: 0xafe09303, L:/192.168.2.167:49590 - R:/192.168.2.167:8091]
[2020-01-10 19:34:57.089][NettyClientSelector_TMROLE_1][DEBUG][io.seata.core.rpc.netty.AbstractRpcRemoting][304]:write message:services ping, channel:[id: 0xafe09303, L:/192.168.2.167:49590 - R:/192.168.2.167:8091],active?true,writable?true,isopen?true
[2020-01-10 19:34:57.090][NettyClientSelector_TMROLE_1][DEBUG][io.seata.core.rpc.netty.AbstractRpcRemotingClient][139]:received PONG from /192.168.2.167:8091
[2020-01-10 19:34:57.184][NettyClientSelector_TMROLE_1][DEBUG][io.seata.core.rpc.netty.AbstractRpcRemotingClient][202]:will send ping msg,channel[id: 0x69d68980, L:/192.168.2.167:49606 - R:/192.168.2.167:8091]
[2020-01-10 19:34:57.185][NettyClientSelector_TMROLE_1][DEBUG][io.seata.core.rpc.netty.AbstractRpcRemoting][304]:write message:services ping, channel:[id: 0x69d68980, L:/192.168.2.167:49606 - R:/192.168.2.167:8091],active?true,writable?true,isopen?true
[2020-01-10 19:34:57.186][NettyClientSelector_TMROLE_1][DEBUG][io.seata.core.rpc.netty.AbstractRpcRemotingClient][139]:received PONG from /192.168.2.167:8091
[2020-01-10 19:34:57.908][main-SendThread(192.168.2.167:2181)][DEBUG][org.apache.zookeeper.ClientCnxn$SendThread][742]:Got ping response for sessionid: 0x1009726709f0043 after 0ms
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

**1. run module A
2. run module B
3. run module C
4. run module D（error）**

### Ⅴ. Anything else we need to know?
how to deal with it？

### Ⅵ. Environment:

- JDK version :1.8
- OS :centos 7.6
- Others:

**Comment by BlueGuo** [comment]
I had resolved by myself；

first，it is my project self trouble，the project starts with errors，there were ignore by me。

but the project not start success，the seata netty module still works，i thought it not normal。
