### ISSUE TITLE
it will cause IllegalArgumentException that still dependency seata-all-0.9.0 inside seata-spring-boot-starter 1.0.0 

### ISSUE THREAD

**Issue by Isaac-Zhang** [seata/seata#2190]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
it will take illeegal exception when startup the biz application.

> Caused by: java.lang.IllegalArgumentException: illegal type:null
	at io.seata.config.ConfigType.getType(ConfigType.java:70) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:85) ~[seata-all-0.9.0.jar:0.9.0]
	... 34 common frames omitted

### Ⅱ. Describe what happened
![image](https://user-images.githubusercontent.com/4083152/72498331-fc124a00-3869-11ea-83c8-460f3427f5a7.png)

### Ⅲ. Describe what you expected to happen
now, I changed the pom dependecies as blow:
```xml
        <!--seata-->
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.0.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>seata-all</artifactId>
                    <groupId>io.seata</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-all</artifactId>
            <version>1.0.0</version>
        </dependency>
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows/mac
- Others:

**Comment by Isaac-Zhang** [comment]
> Find by idea dependent view.

what's that mean?Can you elaborate more specifically?

**Comment by zjinlei** [comment]
https://www.iteye.com/blog/baowp-1989575
