### ISSUE TITLE
java.lang.OutOfMemoryError: Direct buffer memory when system start up with some client

### ISSUE THREAD

**Issue by NewwayHe** [seata/seata#2202]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
  We use docker-compose script to start up seata. the config file as bellow, The version is 1.0.0 under Centos 7.6.

version: "3.3"
services:
  seata-server:
    image: seataio/seata-server
    hostname: seata-server
    container_name: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - SEATA_IP=172.18.102.181
   volumes:
      - ./config:/seata-server/resources
      - ./logs:/root/logs

but the error happened when some client is going to connect to the server.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
2020-01-18 11:18:53,324 INFO channel exx:Direct buffer memory,channel:[id: 0xf5d8668a, L:/172.27.0.2:8091 - R:/172.18.34.156:41090]

2020-01-18 11:18:53,329 ERROR 0318

java.lang.OutOfMemoryError: Direct buffer memory
	at java.base/java.nio.Bits.reserveMemory(Unknown Source)
	at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. The default memory is set to low?
2. How to set the value of MaxDirectMemorySize in docker-compose file?
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : Centos 7.6
- Others:

**Comment by zjinlei** [comment]
https://github.com/seata/seata/pull/2175

**Comment by zjinlei** [comment]
please add this config in file.conf of server inside
transport {
  #thread factory for netty
  thread-factory {
    #auto default pin or 8
    worker-thread-size = 8
  }
}
