### ISSUE TITLE
JDK1.8 Encode request error

### ISSUE THREAD

**Issue by suhli** [seata/seata#2223]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
using jdk 1.8 got
> 2020-02-03 18:33:30.732 ERROR 41023 --- [lector_RMROLE_1] i.s.core.rpc.netty.v1.ProtocolV1Encoder  : Encode request error!

### Ⅱ. Describe what happened

```
2020-02-03 18:33:30.537  INFO 41023 --- [imeoutChecker_2] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1580726010536 with initial instances count: 11
2020-02-03 18:33:30.551  INFO 41023 --- [imeoutChecker_1] i.s.c.r.netty.NettyClientChannelManager  : will connect to 192.168.175.31:8091
2020-02-03 18:33:30.551  INFO 41023 --- [imeoutChecker_2] i.s.c.r.netty.NettyClientChannelManager  : will connect to 192.168.175.31:8091
2020-02-03 18:33:30.554  INFO 41023 --- [imeoutChecker_2] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:TMROLE,address:192.168.175.31:8091,msg:< RegisterTMRequest{applicationId='f5core', transactionServiceGroup='f5core-fescar-service-group'} >
2020-02-03 18:33:30.682  WARN 41023 --- [nfigOperate_2_2] io.seata.config.FileConfiguration        : Could not found property transport.serialization, try to use default value instead.
2020-02-03 18:33:30.683  WARN 41023 --- [nfigOperate_2_2] io.seata.config.FileConfiguration        : Could not found property transport.compressor, try to use default value instead.
2020-02-03 18:33:30.706  INFO 41023 --- [lector_RMROLE_1] i.s.common.loader.EnhancedServiceLoader  : load Codec[SEATA] extension by class[io.seata.codec.seata.SeataCodec]
2020-02-03 18:33:30.732 ERROR 41023 --- [lector_RMROLE_1] i.s.core.rpc.netty.v1.ProtocolV1Encoder  : Encode request error!

java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at io.seata.codec.seata.SeataCodec.encode(SeataCodec.java:56) ~[seata-codec-seata-1.0.0.jar:na]
	at io.seata.core.rpc.netty.v1.ProtocolV1Encoder.encode(ProtocolV1Encoder.java:95) ~[seata-core-1.0.0.jar:na]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-codec-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:705) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:763) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:698) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:705) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:980) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1032) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:965) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357) [netty-common-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [netty-common-4.0.27.Final.jar:4.0.27.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

2020-02-03 18:33:30.732 ERROR 41023 --- [lector_TMROLE_1] i.s.core.rpc.netty.v1.ProtocolV1Encoder  : Encode request error!

java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at io.seata.codec.seata.SeataCodec.encode(SeataCodec.java:56) ~[seata-codec-seata-1.0.0.jar:na]
	at io.seata.core.rpc.netty.v1.ProtocolV1Encoder.encode(ProtocolV1Encoder.java:95) ~[seata-core-1.0.0.jar:na]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-codec-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:705) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:763) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:698) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:705) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:980) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1032) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:965) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357) [netty-common-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-transport-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [netty-common-4.0.27.Final.jar:4.0.27.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

2020-02-03 18:33:30.762  INFO 41023 --- [lector_TMROLE_1] i.s.c.r.netty.AbstractRpcRemotingClient  : channel inactive: [id: 0xa18d1edf, 0.0.0.0/0.0.0.0:56950 :> /192.168.175.31:8091]
2020-02-03 18:33:30.762  INFO 41023 --- [lector_RMROLE_1] i.s.c.r.netty.AbstractRpcRemotingClient  : channel inactive: [id: 0x0fc2f8ca, 0.0.0.0/0.0.0.0:56951 :> /192.168.175.31:8091]
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. using jdk1.8
2. set transport.serialization = "seata" in file.conf

### Ⅴ. Anything else we need to know?
in io.seata.codec.seata.SeataCodec:56

> byteBuffer.flip();
```
JDK9 breaks compatibility with older versions for ByteBuffer.flip() by returning ByteBuffer instead of Buffer. Compiled code with target 1.6 causes this exception.

This casting can be a solution: ((Buffer) buffer).flip();
```
[source](https://github.com/hazelcast/hazelcast/issues/14214)
### Ⅵ. Environment:

- JDK version :1.8.0_161
- OS :macos
- Others:

**Comment by suhli** [comment]
transport.serialization set to KRYO seems ok

**Comment by slievrly** [comment]
@suhli This is a problem if the target version is 1.6 in the above link. Seata is performed using 1.8.0_181. Is it possible to upgrade your JDK version?

**Comment by slievrly** [comment]
@suhli If the above source code modification can solve your problem, we are happy to modify, you need to verify whether the problem is fixed locally.
`((Buffer) buffer).flip();`

**Comment by suhli** [comment]
> @suhli If the above source code modification can solve your problem, we are happy to modify, you need to verify whether the problem is fixed locally.
> `((Buffer) buffer).flip();`

kryo is ok for me
