### ISSUE TITLE
Saga模式，当注册分支事务失败异常时，状态机退出了，但库里state_machine_inst表status仍任是RU

### ISSUE THREAD

**Issue by bao-hp** [seata/seata#2247]
在并发测试的时候发现，偶尔会出现注册分支事务异常

io.seata.saga.engine.exception.EngineExecutionException: Branch transaction error: BranchRegisterFailed, StateMachine:createOrder, XID: 172.30.101.110:8091:2035750085, State:create, stateId: null, Reason: Runtime
        at io.seata.saga.engine.store.db.DbAndReportTcStateLogStore.branchRegister(DbAndReportTcStateLogStore.java:303)
        at io.seata.saga.engine.store.db.DbAndReportTcStateLogStore.recordStateStarted(DbAndReportTcStateLogStore.java:262)
        at io.seata.saga.engine.pcext.interceptors.ServiceTaskHandlerInterceptor.preProcess(ServiceTaskHandlerInterceptor.java:298)
        at io.seata.saga.engine.pcext.StateMachineProcessHandler.process(StateMachineProcessHandler.java:66)
        at io.seata.saga.proctrl.process.impl.CustomizeBusinessProcessor.process(CustomizeBusinessProcessor.java:70)
        at io.seata.saga.proctrl.impl.ProcessControllerImpl.process(ProcessControllerImpl.java:43)
        at io.seata.saga.proctrl.eventing.impl.ProcessCtrlEventConsumer.process(ProcessCtrlEventConsumer.java:35)
        at io.seata.saga.proctrl.eventing.impl.ProcessCtrlEventConsumer.process(ProcessCtrlEventConsumer.java:28)
        at io.seata.saga.proctrl.eventing.impl.AsyncEventBus$1.run(AsyncEventBus.java:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.seata.core.exception.RmTransactionException: Runtime
        at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:75)
        at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96)
        at io.seata.saga.tm.DefaultSagaTransactionalTemplate.branchRegister(DefaultSagaTransactionalTemplate.java:121)
        at io.seata.saga.engine.store.db.DbAndReportTcStateLogStore.branchRegister(DbAndReportTcStateLogStore.java:297)
        ... 11 more

- JDK version : 1.8
- OS : linux
- Others:

**Comment by long187** [comment]
This is a bug.
StateMachineInstance status is still RU when register branch error, It should be FA/UN.
