### ISSUE TITLE
java.io.IOException: 连接被对方重设

### ISSUE THREAD

**Issue by MrLiuFang** [seata/seata#2252]
### Ⅱ. seata 客户端报错如下

```
2020-02-15 16:39:29.120 ERROR 14303 --- [lector_RMROLE_1] i.s.c.r.netty.AbstractRpcRemotingClient  : 0318

java.io.IOException: 连接被对方重设
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_231]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_231]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_231]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_231]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_231]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247) ~[netty-buffer-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147) ~[netty-buffer-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.43.Final.jar:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]

2020-02-15 16:39:59.100 ERROR 14303 --- [  restartedMain] i.s.core.rpc.netty.AbstractRpcRemoting   : wait response error:cost 30003 ms,ip:null,request:RegisterRMRequest{resourceIds='jdbc:mysql://127.0.0.1:3306/upms', applicationId='lion-upms-user-exposed-impl', transactionServiceGroup='lion-upms-user-exposed-impl-seata-service-group'}
2020-02-15 16:39:59.103 ERROR 14303 --- [  restartedMain] i.s.c.r.netty.NettyClientChannelManager  : 0304 register RM failed.
```

### Ⅲ. seata 服务端报错如下

```
2020-02-15 16:43:12.496 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.DefaultServerMessageListenerImpl.onRegTmMessage:140 -checkAuth for client:127.0.0.1:59250,vgroup:lion-upms-user-exposed-impl-seata-service-group,applicationId:lion-upms-user-exposed-impl
2020-02-15 16:43:15.527 INFO [ServerHandlerThread_1_500]io.seata.core.rpc.DefaultServerMessageListenerImpl.onRegRmMessage:123 -rm register success,message:RegisterRMRequest{resourceIds='jdbc:mysql://127.0.0.1:3306/upms', applicationId='lion-upms-user-exposed-impl', transactionServiceGroup='lion-upms-user-exposed-impl-seata-service-group'},channel:[id: 0x698af9e2, L:/127.0.0.1:8091 - R:/127.0.0.1:59274]
2020-02-15 16:43:22.503 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.RpcServer.exceptionCaught:377 -channel exx:failed to allocate 134217728 byte(s) of direct memory (used: 1073741824, max: 1073741824),channel:[id: 0x220b6cea, L:/127.0.0.1:8091 - R:/127.0.0.1:59248]
2020-02-15 16:43:22.503 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.RpcServer.exceptionCaught:377 -channel exx:failed to allocate 134217728 byte(s) of direct memory (used: 1073741824, max: 1073741824),channel:[id: 0x2d8fa9e0, L:/127.0.0.1:8091 - R:/127.0.0.1:59246]
2020-02-15 16:43:22.503 ERROR[NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:437 -0318
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 134217728 byte(s) of direct memory (used: 1073741824, max: 1073741824)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:652)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:606)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-02-15 16:43:22.503 ERROR[NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:437 -0318
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 134217728 byte(s) of direct memory (used: 1073741824, max: 1073741824)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:652)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:606)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-02-15 16:43:22.503 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:188 -will destroy channel:[id: 0x220b6cea, L:/127.0.0.1:8091 - R:/127.0.0.1:59248],address:127.0.0.1:59248
2020-02-15 16:43:22.503 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:188 -will destroy channel:[id: 0x2d8fa9e0, L:/127.0.0.1:8091 - R:/127.0.0.1:59246],address:127.0.0.1:59246
2020-02-15 16:43:22.503 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.AbstractRpcRemoting.close:458 -ChannelHandlerContext(RpcServer#0, [id: 0x220b6cea, L:/127.0.0.1:8091 - R:/127.0.0.1:59248]) will closed
2020-02-15 16:43:22.503 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.AbstractRpcRemoting.close:458 -ChannelHandlerContext(RpcServer#0, [id: 0x2d8fa9e0, L:/127.0.0.1:8091 - R:/127.0.0.1:59246]) will closed
2020-02-15 16:43:22.504 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.AbstractRpcRemoting.close:458 -ChannelHandlerContext(RpcServer#0, [id: 0x220b6cea, L:/127.0.0.1:8091 ! R:/127.0.0.1:59248]) will closed
2020-02-15 16:43:22.504 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.AbstractRpcRemoting.close:458 -ChannelHandlerContext(RpcServer#0, [id: 0x2d8fa9e0, L:/127.0.0.1:8091 ! R:/127.0.0.1:59246]) will closed
2020-02-15 16:43:22.504 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.RpcServer.handleDisconnect:329 -127.0.0.1:59248 to server channel inactive.
2020-02-15 16:43:22.504 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.RpcServer.handleDisconnect:329 -127.0.0.1:59246 to server channel inactive.
2020-02-15 16:43:22.504 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.RpcServer.handleDisconnect:338 -remove unused channel:[id: 0x220b6cea, L:/127.0.0.1:8091 ! R:/127.0.0.1:59248]
2020-02-15 16:43:22.504 INFO [NettyServerNIOWorker_1_32]io.seata.core.rpc.netty.RpcServer.handleDisconnect:338 -remove unused channel:[id: 0x2d8fa9e0, L:/127.0.0.1:8091 ! R:/127.0.0.1:59246]
```

### Ⅳ. Environment:

- JDK version :1.8
- OS :centos 8
- Others:seata1.0.0 & spring boot 2.2 & dubbo 2.7.4

**Comment by zjinlei** [comment]
https://github.com/seata/seata/pull/2175
