### ISSUE TITLE
seata-all 1.1 + spring-boot-devtools 死循环

### ISSUE THREAD

**Issue by ChesterZheng** [seata/seata#2278]
以下是报错日志

java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@42ab32eb has been closed already
  at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1089) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
  at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1122) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
  at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:93) ~[seata-spring-boot-starter-1.1.0.jar:na]
  at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$100(SpringBootConfigurationProvider.java:43) ~[seata-spring-boot-starter-1.1.0.jar:na]
  at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:56) ~[seata-spring-boot-starter-1.1.0.jar:na]
  at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>) ~[seata-all-1.1.0.jar:1.1.0]
  at io.seata.config.FileConfiguration$FileListener.onChangeEvent(FileConfiguration.java:311) ~[seata-all-1.1.0.jar:1.1.0]
  at io.seata.config.ConfigurationChangeListener.lambda$onProcessEvent$0(ConfigurationChangeListener.java:62) [seata-all-1.1.0.jar:1.1.0]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_172]
  at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_172]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_172]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_172]
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
  at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_172]

2020-02-21 16:37:28.678 ERROR 23232 --- [ fileListener_1] io.seata.config.FileConfiguration        : fileListener execute error:org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@42ab32eb has been closed already

**Comment by slievrly** [comment]
@ChesterZheng can you explain how to reproduce it?

**Comment by ChesterZheng** [comment]
For sure, I've sent a txt file on DingDing

**Comment by TonnyGu** [comment]
how to fix?

**Comment by a871545252** [comment]
how to finally fix?
