### ISSUE TITLE
注入数据源失败，与已有数据源冲突

### ISSUE THREAD

**Issue by lvjun2015** [seata/seata#2304]
公司工程中已有数据源配置如下，并且该代码以jar包形式导入，无法修改
 @Bean
    public SqlSessionFactory sqlSessionFactory() throws Exception {
        SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(dataSource);
        return sessionFactory.getObject();
    }

在与seata集成中 需要注入数据源如下
@Configuration
public class SeataDataSourceProxyConfig {

    @Bean
    @ConfigurationProperties(prefix = "datasource")
    public DataSource dataSource() {
        return new DruidDataSource();
    }

    @Bean
    public DataSourceProxy dataSourceProxy(DataSource dataSource) {
        return new DataSourceProxy(dataSource);
    }

    @Bean
    public SqlSessionFactory sqlSessionFactory(DataSourceProxy dataSourceProxy) throws Exception {
        SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
        sqlSessionFactoryBean.setDataSource(dataSourceProxy);
        return sqlSessionFactoryBean.getObject();
    }
}

项目启动报错，Description:

file [xx.class required a single bean, but 2 were found:
	- sqlSessionFactoryBean: defined by method 'sqlSessionFactoryBean' in class path resource [com/xx/SeataDataSourceProxyConfig.class]
	- sqlSessionFactory: defined by method 'sqlSessionFactory' in class path resource [cn/xx//config/MybatisConfig.class]

请问这种情况如何处理？

**Comment by zjinlei** [comment]
use seata auto DataSource proxy
https://seata.io/zh-cn/docs/ops/deploy-guide-beginner.html

**Comment by lvjun2015** [comment]
@EnableAutoDataSourceProxy
public class Application{}

按照如上方法报以下错

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [xx/DataSourceConfig.class]: Initialization of bean failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:522)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:496)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:627)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:169)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:318)
	... 62 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.alibaba.druid.pool.DruidDataSource$$EnhancerBySpringCGLIB$$ede5d66b.getTargetClass(<generated>)
	at org.springframework.aop.framework.AopProxyUtils.ultimateTargetClass(AopProxyUtils.java:80)
	at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.postProcessAfterInitialization(ScheduledAnnotationBeanPostProcessor.java:310)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	... 73 common frames omitted

**Comment by slievrly** [comment]
@lvjun2015 Does the project depend on seata-all or seata-spring-boot-starter?

**Comment by lvjun2015** [comment]
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2.1.0.RELEASE</version>
        </dependency>

**Comment by lvjun2015** [comment]
还发现一个问题，数据源被代理后，其他逻辑原有的方法的本地事务也失效了

**Comment by slievrly** [comment]
@lvjun2015 please depend on  spring-cloud-alibaba-seata  2.2.0. RELEASE  and reimport seata-spring-boot-starter 1.1.0.

**Comment by xingfudeshi** [comment]
> 还发现一个问题，数据源被代理后，其他逻辑原有的方法的本地事务也失效了

try this PR https://github.com/seata/seata/pull/2323

**Comment by a364176773** [comment]
自动代理开启后
`@Bean
public DataSourceProxy dataSourceProxy(DataSource dataSource) {
    return new DataSourceProxy(dataSource);
}`
没有存在的必要了
