### ISSUE TITLE
At 模式什么时候会支持 复合主键呢？

### ISSUE THREAD

**Issue by YangQiang-ChengDu** [seata/seata#2366]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

Caused by: java.sql.SQLException: io.seata.common.exception.NotSupportYetException: test.t_dist_01 contains multi PK, but current not support.
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:105)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:47)
	at io.seata.rm.datasource.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:64)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
	... 63 more

### Ⅲ. Describe what you expected to happen
 想知道相关的开发计划，有没有计划做符合组件的支持。有的话，大概什么时间会发布？

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
@YangQiang-ChengDu ref #2398 ，you can package locally to verify and feedback the results to us.

**Comment by YangQiang-ChengDu** [comment]
本地打包，测试发现了个问题。针对PGSQL，表名拼接错误。本地进行了修复。打包测试后OK；
![image](https://user-images.githubusercontent.com/47472385/76946755-7aa96780-693f-11ea-88e9-d779a795d8cd.png)

**Comment by Garlichead** [comment]
> 本地打包，测试发现了个问题。针对PGSQL，表名拼接错误。本地进行了修复。打包测试后OK；
> ![image](https://user-images.githubusercontent.com/47472385/76946755-7aa96780-693f-11ea-88e9-d779a795d8cd.png)

厉害 目前本地解决到什么地步了 个人思路 复合主键的解析可以做一个单独的处理接口进行解析处理 使用postgrasql数据源的配置 感觉有点像shardingsphere的思路了

**Comment by Garlichead** [comment]
复合主键无法支持的原因就在于表名拼接错误导致的吗

**Comment by YangQiang-ChengDu** [comment]
使用PG的时候是这个样子的。目前官方还不支持，复合主键。这个分支ref #2398 不知道什么时候会合并

**Comment by Garlichead** [comment]
> 使用PG的时候是这个样子的。目前官方还不支持，复合主键。这个分支ref #2398 不知道什么时候会合并

hope 早点支持复合主键

**Comment by jsbxyyx** [comment]
1.3 support mysql multi primary key.
