### ISSUE TITLE
Oracle Cannot create PoolableConnectionFactory (ORA-00923: 未找到要求的 FROM 关键字

### ISSUE THREAD

**Issue by dongwenting** [seata/seata#2386]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

seata server 1.1.0 启动，配置Oracle时报错，配置MySQL没问题

file.conf

```
store {
  ## store mode: file、db
  mode = "db"

  ## file store property
  file {
    ## store location dir
    dir = "sessionStore"
  }

  ## database store property
  db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "dbcp"
    ## mysql/oracle/h2/oceanbase etc.
    db-type = "oracle"
    driver-class-name = "oracle.jdbc.OracleDriver"
    url = "jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = )(PORT = 1521)) (ADDRESS = (PROTOCOL= TCP)(HOST = )(PORT = 1521))  (LOAD_BALANCE = no) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = ractest) (failover_mode=(type=session)(method=basic))))"
    user = "root"
    password = "123456"
  }
}
```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```
2020-03-10 15:53:38.619 WARN [main]io.seata.core.store.db.LogStoreDataBaseDAO.initTransactionNameSize:468 -global_table table or TRANSACTION_NAME column not found
2020-03-10 15:53:38.671 ERROR[main]io.seata.core.store.db.LogStoreDataBaseDAO.queryTableStructure:508 -query transaction_name size fail, Cannot create PoolableConnectionFactory (ORA-00923: 未找到要求的 FROM 关键字
)
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (ORA-00923: 未找到要求的 FROM 关键字
)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at io.seata.core.store.db.LogStoreDataBaseDAO.queryTableStructure(LogStoreDataBaseDAO.java:482)
	at io.seata.core.store.db.LogStoreDataBaseDAO.initTransactionNameSize(LogStoreDataBaseDAO.java:466)
	at io.seata.core.store.db.LogStoreDataBaseDAO.init(LogStoreDataBaseDAO.java:119)
	at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:365)
	at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:245)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:140)
	at io.seata.server.store.db.DatabaseTransactionStoreManager.init(DatabaseTransactionStoreManager.java:102)
	at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:365)
	at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:245)
	at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:205)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:87)
	at io.seata.server.session.db.DataBaseSessionManager.init(DataBaseSessionManager.java:82)
	at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:365)
	at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:245)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:124)
	at io.seata.server.session.SessionHolder.init(SessionHolder.java:98)
	at io.seata.server.Server.main(Server.java:75)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00923: 未找到要求的 FROM 关键字

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:202)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:45)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:766)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:897)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1034)
	at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1244)
	at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:420)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.apache.commons.dbcp.PoolableConnectionFactory.validateConnection(PoolableConnectionFactory.java:658)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1558)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	... 19 common frames omitted
2020-03-10 15:53:38.672 WARN [main]io.seata.core.store.db.LogStoreDataBaseDAO.initTransactionNameSize:468 -global_table table or TRANSACTION_NAME column not found
2020-03-10 15:53:38.724 ERROR[main]io.seata.core.store.db.LogStoreDataBaseDAO.queryTableStructure:508 -query transaction_name size fail, Cannot create PoolableConnectionFactory (ORA-00923: 未找到要求的 FROM 关键字
)
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (ORA-00923: 未找到要求的 FROM 关键字
)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at io.seata.core.store.db.LogStoreDataBaseDAO.queryTableStructure(LogStoreDataBaseDAO.java:482)
	at io.seata.core.store.db.LogStoreDataBaseDAO.initTransactionNameSize(LogStoreDataBaseDAO.java:466)
	at io.seata.core.store.db.LogStoreDataBaseDAO.init(LogStoreDataBaseDAO.java:119)
	at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:365)
	at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:245)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:140)
	at io.seata.server.store.db.DatabaseTransactionStoreManager.init(DatabaseTransactionStoreManager.java:102)
	at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:365)
	at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:245)
	at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:205)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:87)
	at io.seata.server.session.db.DataBaseSessionManager.init(DataBaseSessionManager.java:82)
	at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:365)
	at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:245)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:124)
	at io.seata.server.session.SessionHolder.init(SessionHolder.java:100)
	at io.seata.server.Server.main(Server.java:75)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00923: 未找到要求的 FROM 关键字

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:202)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:45)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:766)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:897)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1034)
	at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1244)
	at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:420)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.apache.commons.dbcp.PoolableConnectionFactory.validateConnection(PoolableConnectionFactory.java:658)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1558)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	... 19 common frames omitted
2020-03-10 15:53:38.725 WARN [main]io.seata.core.store.db.LogStoreDataBaseDAO.initTransactionNameSize:468 -global_table table or TRANSACTION_NAME column not found
Exception in thread "main" io.seata.common.exception.DataAccessException: Cannot create PoolableConnectionFactory (ORA-00923: 未找到要求的 FROM 关键字
)
	at io.seata.core.store.db.LogStoreDataBaseDAO.getCurrentMaxSessionId(LogStoreDataBaseDAO.java:422)
	at io.seata.core.store.db.LogStoreDataBaseDAO.getCurrentMaxSessionId(LogStoreDataBaseDAO.java:400)
	at io.seata.server.store.db.DatabaseTransactionStoreManager.getCurrentMaxSessionId(DatabaseTransactionStoreManager.java:228)
	at io.seata.server.session.db.DataBaseSessionManager.reload(DataBaseSessionManager.java:198)
	at io.seata.server.session.SessionHolder.reload(SessionHolder.java:130)
	at io.seata.server.session.SessionHolder.init(SessionHolder.java:122)
	at io.seata.server.Server.main(Server.java:75)
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (ORA-00923: 未找到要求的 FROM 关键字
)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at io.seata.core.store.db.LogStoreDataBaseDAO.getCurrentMaxSessionId(LogStoreDataBaseDAO.java:411)
	... 6 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-00923: 未找到要求的 FROM 关键字

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:202)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:45)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:766)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:897)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1034)
	at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1244)
	at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:420)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.apache.commons.dbcp.PoolableConnectionFactory.validateConnection(PoolableConnectionFactory.java:658)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1558)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)

**Comment by zjinlei** [comment]
global_table table or TRANSACTION_NAME column not found

**Comment by bingxueyinlian** [comment]
seata-server默认好像不带oracle驱动包，需要自己复制一个驱动文件（如：`ojdbc6-11.2.0.4.jar`）到seata/lib目录下。
