### ISSUE TITLE
FileConfiguration 在异常情况下会导致CPU飙高

### ISSUE THREAD

**Issue by threefish** [seata/seata#2387]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

`io.seata.config.FileConfiguration`

还未发现如何导致这个异常问题，但是已经多次出现。  此处 while  true 代码在出现异常情况下，Thread.sleep 不会执行，会导致CPU飙高至机器严重卡顿服务不可用。

![image](https://user-images.githubusercontent.com/6268640/76300467-b7e67780-62f7-11ea-8963-9cb45666cfc2.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
异常日志
```
2020-03-10 18:10:18.592 DEBUG org.springframework.boot.devtools.restart.Restarter Line:249 - Restarting application
2020-03-10 18:10:18.594 DEBUG org.springframework.boot.devtools.restart.Restarter Line:305 - Stopping application
2020-03-10 18:10:18.595 DEBUG org.springframework.context.annotation.AnnotationConfigApplicationContext Line:1005 - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@150ab67b, started on Tue Mar 10 18:05:14 CST 2020
2020-03-10 18:10:18.596 DEBUG org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext Line:1005 - Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75, started on Tue Mar 10 18:05:16 CST 2020, parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@150ab67b
2020-03-10 18:10:18.598 DEBUG org.springframework.context.support.DefaultLifecycleProcessor Line:369 - Stopping beans in phase 0
2020-03-10 18:10:18.600 INFO  org.springframework.cloud.alibaba.nacos.registry.NacosServiceRegistry Line:76  - De-registering from Nacos Server now...
2020-03-10 18:10:18.617 INFO  org.springframework.cloud.alibaba.nacos.registry.NacosServiceRegistry Line:95  - De-registration finished.
2020-03-10 18:10:18.618 DEBUG org.springframework.data.redis.listener.RedisMessageListenerContainer Line:229 - Stopped RedisMessageListenerContainer
2020-03-10 18:10:18.619 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Archaius' from the JMX domain
2020-03-10 18:10:18.620 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Beans' from the JMX domain
2020-03-10 18:10:18.620 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Caches' from the JMX domain
2020-03-10 18:10:18.620 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Health' from the JMX domain
2020-03-10 18:10:18.620 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Info' from the JMX domain
2020-03-10 18:10:18.620 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Conditions' from the JMX domain
2020-03-10 18:10:18.620 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Configprops' from the JMX domain
2020-03-10 18:10:18.620 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Env' from the JMX domain
2020-03-10 18:10:18.621 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Loggers' from the JMX domain
2020-03-10 18:10:18.621 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Threaddump' from the JMX domain
2020-03-10 18:10:18.621 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Metrics' from the JMX domain
2020-03-10 18:10:18.621 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Scheduledtasks' from the JMX domain
2020-03-10 18:10:18.621 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Mappings' from the JMX domain
2020-03-10 18:10:18.621 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Nacos-discovery' from the JMX domain
2020-03-10 18:10:18.621 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Refresh' from the JMX domain
2020-03-10 18:10:18.622 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Features' from the JMX domain
2020-03-10 18:10:18.622 DEBUG org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter Line:116 - Unregister endpoint with ObjectName 'org.springframework.boot:type=Endpoint,name=Service-registry' from the JMX domain
2020-03-10 18:10:18.623 INFO  org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor Line:208 - Shutting down ExecutorService 'applicationTaskExecutor'
2020-03-10 18:10:18.628 DEBUG org.springframework.jmx.export.annotation.AnnotationMBeanExporter Line:452 - Unregistering JMX-exposed beans on shutdown
2020-03-10 18:10:18.629 DEBUG org.springframework.jmx.export.annotation.AnnotationMBeanExporter Line:186 - Unregistering JMX-exposed beans
2020-03-10 18:10:18.630 DEBUG org.springframework.context.annotation.AnnotationConfigApplicationContext Line:1005 - Closing FeignContext-flow-center-currency-provider, started on Tue Mar 10 18:05:27 CST 2020, parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75
2020-03-10 18:10:18.630 DEBUG org.springframework.core.env.PropertySourcesPropertyResolver Line:115 - Found key 'spring.liveBeansView.mbeanDomain' in PropertySource 'systemProperties' with value of type String
2020-03-10 18:10:18.635 INFO  com.alibaba.druid.pool.DruidDataSource Line:2003 - {dataSource-1} closing ...
2020-03-10 18:10:18.635 DEBUG com.alibaba.druid.pool.PreparedStatementPool Line:160 - stmt exit cache
2020-03-10 18:10:18.636 DEBUG com.alibaba.druid.pool.PreparedStatementPool Line:160 - stmt exit cache
2020-03-10 18:10:18.636 DEBUG com.alibaba.druid.pool.PreparedStatementPool Line:160 - stmt exit cache
2020-03-10 18:10:18.636 DEBUG com.alibaba.druid.pool.PreparedStatementPool Line:160 - stmt exit cache
2020-03-10 18:10:18.637 DEBUG com.alibaba.druid.pool.PreparedStatementPool Line:160 - stmt exit cache
2020-03-10 18:10:18.642 DEBUG com.alibaba.druid.pool.PreparedStatementPool Line:160 - stmt exit cache
2020-03-10 18:10:18.645 INFO  com.alibaba.druid.pool.DruidDataSource Line:2075 - {dataSource-1} closed
2020-03-10 18:10:18.657 DEBUG io.lettuce.core.RedisChannelHandler Line:123 - close()
2020-03-10 18:10:18.657 DEBUG io.lettuce.core.RedisChannelHandler Line:137 - closeAsync()
2020-03-10 18:10:18.662 DEBUG io.lettuce.core.RedisClient Line:436 - Initiate shutdown (100, 100, MILLISECONDS)
2020-03-10 18:10:18.671 DEBUG io.lettuce.core.resource.DefaultEventLoopGroupProvider Line:162 - Release executor io.netty.channel.nio.NioEventLoopGroup@6bdd4381
2020-03-10 18:10:18.773 DEBUG io.netty.buffer.PoolThreadCache Line:249 - Freed 5 thread-local buffer(s) from thread: lettuce-nioEventLoop-4-1
2020-03-10 18:10:18.781 DEBUG io.lettuce.core.resource.DefaultClientResources Line:601 - Initiate shutdown (0, 2, SECONDS)
2020-03-10 18:10:18.783 DEBUG io.lettuce.core.resource.DefaultEventLoopGroupProvider Line:202 - Initiate shutdown (0, 2, SECONDS)
2020-03-10 18:10:18.795 INFO  io.seata.core.rpc.netty.AbstractRpcRemotingClient Line:325 - channel inactive: [id: 0x3886f879, L:/10.3.29.163:56202 ! R:/10.3.29.163:8091]
2020-03-10 18:10:18.795 INFO  io.seata.core.rpc.netty.NettyClientChannelManager Line:124 - return to pool, rm channel:[id: 0x3886f879, L:/10.3.29.163:56202 ! R:/10.3.29.163:8091]
2020-03-10 18:10:18.796 INFO  io.seata.core.rpc.netty.NettyPoolableFactory Line:131 - channel valid false,channel:[id: 0x3886f879, L:/10.3.29.163:56202 ! R:/10.3.29.163:8091]
2020-03-10 18:10:18.796 INFO  io.seata.core.rpc.netty.NettyPoolableFactory Line:118 - will destroy channel:[id: 0x3886f879, L:/10.3.29.163:56202 ! R:/10.3.29.163:8091]
2020-03-10 18:10:18.796 INFO  io.seata.core.rpc.netty.AbstractRpcRemoting Line:518 - ChannelHandlerContext(AbstractRpcRemotingClient$ClientHandler#0, [id: 0x3886f879, L:/10.3.29.163:56202 ! R:/10.3.29.163:8091]) will closed
2020-03-10 18:10:18.796 INFO  io.seata.core.rpc.netty.AbstractRpcRemoting Line:518 - ChannelHandlerContext(AbstractRpcRemotingClient$ClientHandler#0, [id: 0x3886f879, L:/10.3.29.163:56202 ! R:/10.3.29.163:8091]) will closed
2020-03-10 18:10:36.014 ERROR io.seata.core.rpc.netty.NettyClientChannelManager Line:164 - Failed to get available servers: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1092)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1125)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:93)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$100(SpringBootConfigurationProvider.java:43)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:56)
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>)
	at io.seata.discovery.registry.RegistryFactory.getInstance(RegistryFactory.java:39)
	at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:216)
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:162)
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient$1.run(AbstractRpcRemotingClient.java:115)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-03-10 18:10:36.015 ERROR io.seata.core.rpc.netty.NettyClientChannelManager Line:164 - Failed to get available servers: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1092)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1125)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:93)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$100(SpringBootConfigurationProvider.java:43)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:56)
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>)
	at io.seata.discovery.registry.RegistryFactory.getInstance(RegistryFactory.java:39)
	at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:216)
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:162)
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient$1.run(AbstractRpcRemotingClient.java:115)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-03-10 18:10:36.016 INFO  io.seata.core.rpc.netty.AbstractRpcRemotingClient Line:337 - channel [id: 0xd9c09dd0, L:/10.3.29.163:56203 - R:/10.3.29.163:8091] read idle.
2020-03-10 18:10:36.016 INFO  io.seata.core.rpc.netty.NettyPoolableFactory Line:118 - will destroy channel:[id: 0xd9c09dd0, L:/10.3.29.163:56203 - R:/10.3.29.163:8091]
2020-03-10 18:10:36.016 INFO  io.seata.core.rpc.netty.AbstractRpcRemoting Line:518 - ChannelHandlerContext(AbstractRpcRemotingClient$ClientHandler#0, [id: 0xd9c09dd0, L:/10.3.29.163:56203 - R:/10.3.29.163:8091]) will closed
2020-03-10 18:10:36.016 ERROR io.seata.config.FileConfiguration Line:320 - fileListener execute error:org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1092)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1125)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:93)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$100(SpringBootConfigurationProvider.java:43)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:56)
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>)
	at io.seata.config.FileConfiguration$FileListener.onChangeEvent(FileConfiguration.java:311)
	at io.seata.config.ConfigurationChangeListener.lambda$onProcessEvent$0(ConfigurationChangeListener.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-03-10 18:10:36.018 INFO  io.seata.core.rpc.netty.AbstractRpcRemoting Line:518 - ChannelHandlerContext(AbstractRpcRemotingClient$ClientHandler#0, [id: 0xd9c09dd0, L:/10.3.29.163:56203 ! R:/10.3.29.163:8091]) will closed
2020-03-10 18:10:36.018 DEBUG io.netty.buffer.PoolThreadCache Line:249 - Freed 12 thread-local buffer(s) from thread: NettyClientSelector_TMROLE_1
2020-03-10 18:10:36.019 INFO  io.seata.core.rpc.netty.NettyClientChannelManager Line:124 - return to pool, rm channel:[id: 0xd9c09dd0, L:/10.3.29.163:56203 ! R:/10.3.29.163:8091]
2020-03-10 18:10:36.019 INFO  io.seata.core.rpc.netty.NettyPoolableFactory Line:131 - channel valid false,channel:[id: 0xd9c09dd0, L:/10.3.29.163:56203 ! R:/10.3.29.163:8091]
2020-03-10 18:10:36.019 INFO  io.seata.core.rpc.netty.NettyPoolableFactory Line:118 - will destroy channel:[id: 0xd9c09dd0, L:/10.3.29.163:56203 ! R:/10.3.29.163:8091]
2020-03-10 18:10:36.020 INFO  io.seata.core.rpc.netty.AbstractRpcRemoting Line:518 - ChannelHandlerContext(AbstractRpcRemotingClient$ClientHandler#0, [id: 0xd9c09dd0, L:/10.3.29.163:56203 ! R:/10.3.29.163:8091]) will closed
2020-03-10 18:10:36.021 INFO  io.seata.core.rpc.netty.AbstractRpcRemoting Line:518 - ChannelHandlerContext(AbstractRpcRemotingClient$ClientHandler#0, [id: 0xd9c09dd0, L:/10.3.29.163:56203 ! R:/10.3.29.163:8091]) will closed
2020-03-10 18:10:36.022 INFO  io.seata.core.rpc.netty.AbstractRpcRemotingClient Line:325 - channel inactive: [id: 0xd9c09dd0, L:/10.3.29.163:56203 ! R:/10.3.29.163:8091]
2020-03-10 18:10:36.022 INFO  io.seata.core.rpc.netty.NettyPoolableFactory Line:131 - channel valid false,channel:[id: 0xd9c09dd0, L:/10.3.29.163:56203 ! R:/10.3.29.163:8091]
2020-03-10 18:10:36.023 INFO  io.seata.core.rpc.netty.NettyPoolableFactory Line:118 - will destroy channel:[id: 0xd9c09dd0, L:/10.3.29.163:56203 ! R:/10.3.29.163:8091]
2020-03-10 18:10:36.023 INFO  io.seata.core.rpc.netty.AbstractRpcRemoting Line:518 - ChannelHandlerContext(AbstractRpcRemotingClient$ClientHandler#0, [id: 0xd9c09dd0, L:/10.3.29.163:56203 ! R:/10.3.29.163:8091]) will closed
2020-03-10 18:10:36.024 INFO  io.seata.core.rpc.netty.AbstractRpcRemoting Line:518 - ChannelHandlerContext(AbstractRpcRemotingClient$ClientHandler#0, [id: 0xd9c09dd0, L:/10.3.29.163:56203 ! R:/10.3.29.163:8091]) will closed
2020-03-10 18:10:37.249 DEBUG org.springframework.boot.devtools.restart.Restarter Line:84  - Created RestartClassLoader org.springframework.boot.devtools.restart.classloader.RestartClassLoader@2645f3b4
2020-03-10 18:10:37.251 DEBUG org.springframework.boot.devtools.restart.Restarter Line:281 - Starting application com.flow.demo.FlowDemoBussinessApplication with URLs [file:/D:/WorkSpaces/spring_flow/flow-business-demo/target/classes/]
2020-03-10 18:10:37.251 ERROR io.seata.config.FileConfiguration Line:320 - fileListener execute error:org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1092)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1125)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:93)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$100(SpringBootConfigurationProvider.java:43)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:56)
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>)
	at io.seata.config.FileConfiguration$FileListener.onChangeEvent(FileConfiguration.java:311)
	at io.seata.config.ConfigurationChangeListener.lambda$onProcessEvent$0(ConfigurationChangeListener.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-03-10 18:10:38.129 ERROR io.seata.config.FileConfiguration Line:320 - fileListener execute error:org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1092)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1125)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:93)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$100(SpringBootConfigurationProvider.java:43)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:56)
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>)
	at io.seata.config.FileConfiguration$FileListener.onChangeEvent(FileConfiguration.java:311)
	at io.seata.config.ConfigurationChangeListener.lambda$onProcessEvent$0(ConfigurationChangeListener.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-03-10 18:10:38.812 ERROR io.seata.config.FileConfiguration Line:320 - fileListener execute error:org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1092)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1125)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:93)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$100(SpringBootConfigurationProvider.java:43)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:56)
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>)
	at io.seata.config.FileConfiguration$FileListener.onChangeEvent(FileConfiguration.java:311)
	at io.seata.config.ConfigurationChangeListener.lambda$onProcessEvent$0(ConfigurationChangeListener.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-03-10 18:10:44.786 ERROR io.seata.core.rpc.netty.NettyClientChannelManager Line:164 - Failed to get available servers: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1092)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1125)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:93)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$100(SpringBootConfigurationProvider.java:43)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:56)
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>)
	at io.seata.discovery.registry.RegistryFactory.getInstance(RegistryFactory.java:39)
	at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:216)
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:162)
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient$1.run(AbstractRpcRemotingClient.java:115)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-03-10 18:10:44.787 ERROR io.seata.config.FileConfiguration Line:320 - fileListener execute error:org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@59316e75 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1092)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1125)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:93)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$100(SpringBootConfigurationProvider.java:43)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:56)
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>)
	at io.seata.config.FileConfiguration$FileListener.onChangeEvent(FileConfiguration.java:311)
	at io.seata.config.ConfigurationChangeListener.lambda$onProcessEvent$0(ConfigurationChangeListener.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8_221
- OS :win10

**Comment by a364176773** [comment]
@zjinlei please leave it to me

**Comment by threefish** [comment]
异常日志贴上了，我的观察应该是 org.springframework.boot.devtools.restart.Restarter 热重启服务导致。

**Comment by threefish** [comment]
cpu has behaved normally。thanks
