### ISSUE TITLE
listenedConfigMap 设定service.disableGlobalTransaction错误

### ISSUE THREAD

**Issue by zhangguoye** [seata/seata#2401]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用seata-1.1.0过程中，启动服务时报错

### Ⅱ. Describe what happened
定位在FileConfiguration.addConfigListener(FileConfiguration.java:180)

Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.config.FileConfiguration.addConfigListener(FileConfiguration.java:180) ~[seata-all-1.1.0.jar:1.1.0]
	... 40 common frames omitted

### Ⅲ. Describe what you expected to happen
经过定位，该问题难以避免，将配置文件中  file.conf中改为：
service {
  #transaction service group mapping
  vgroup_mapping.seata-reader-group = "default"
  #only support when registry.type=file, please don't set multiple addresses
  default.grouplist = "127.0.0.1:8091"
  #disable seata
  disableGlobalTransaction = "false"
}
问题仍然存在，会自动转化为false,  无法设置入Map<String, String>

### Ⅵ. Environment:

- JDK version :1.8
- OS :MacOS
- Others: SpringBoot 2.2.0.RELEASE

**Comment by slievrly** [comment]
@zhangguoye   `disableGlobalTransaction = false` ，not contain quotes.

**Comment by david1025** [comment]
> @zhangguoye `disableGlobalTransaction = false` ，not contain quotes.

我也有这个问题，开启全局事务就报这个错

```
service {
  #transaction service group mapping
  vgroupMapping.springcloud-service-group = "default"
  #only support when registry.type=file, please don't set multiple addresses
  default.grouplist = "127.0.0.1:8091"
  #degrade, current not support
  enableDegrade = false
  #disable seata
  disableGlobalTransaction = "false"
}
```
错误信息
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tbOrderController': Unsatisfied dependency expressed through field 'orderServiceImpl'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tbOrderServiceImpl' defined in file [D:\workspace\idea_workspace\spring-cloud-demo\app-order1\target\classes\com\isoft91\apporder1\service\impl\TbOrderServiceImpl.class]: Initialization of bean failed; nested exception is java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at com.isoft91.apporder1.AppOrder1NacosApplication.main(AppOrder1NacosApplication.java:17) [classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tbOrderServiceImpl' defined in file [D:\workspace\idea_workspace\spring-cloud-demo\app-order1\target\classes\com\isoft91\apporder1\service\impl\TbOrderServiceImpl.class]: Initialization of bean failed; nested exception is java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 19 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:243) ~[seata-all-1.1.0.jar:1.1.0]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:431) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 28 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:84) ~[seata-spring-boot-starter-1.0.0.jar:na]
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.addConfigListener(<generated>) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:225) ~[seata-all-1.1.0.jar:1.1.0]
	... 32 common frames omitted
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.config.FileConfiguration.addConfigListener(FileConfiguration.java:180) ~[seata-all-1.1.0.jar:1.1.0]
	... 39 common frames omitted
```

**Comment by david1025** [comment]
> * [ ]  I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
> 
> ### Ⅰ. Issue Description
> 使用seata-1.1.0过程中，启动服务时报错
> 
> ### Ⅱ. Describe what happened
> 定位在FileConfiguration.addConfigListener(FileConfiguration.java:180)
> 
> Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
> at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig() ~[seata-all-1.1.0.jar:1.1.0]
> at io.seata.config.FileConfiguration.addConfigListener(FileConfiguration.java:180) ~[seata-all-1.1.0.jar:1.1.0]
> ... 40 common frames omitted
> 
> ### Ⅲ. Describe what you expected to happen
> 经过定位，该问题难以避免，将配置文件中 file.conf中改为：
> service {
> #transaction service group mapping
> vgroup_mapping.seata-reader-group = "default"
> #only support when registry.type=file, please don't set multiple addresses
> default.grouplist = "127.0.0.1:8091"
> #disable seata
> disableGlobalTransaction = "false"
> }
> 问题仍然存在，会自动转化为false, 无法设置入Map<String, String>
> 
> ### Ⅴ. Anything else we need to know?
> ### Ⅵ. Environment:
> * JDK version :1.8
> * OS :MacOS
> * Others: SpringBoot 2.2.0.RELEASE

你的问题解决了么？

**Comment by zjinlei** [comment]
Problems caused by version dependencies.
sca-seata2.2.0 depends on seata-starter 1.0.0. 
seata-starter uses the file configuration center for dynamic monitoring which requires 1.1.0

**Comment by homw188** [comment]
## The problem still exists. 
### The phenomenon of error reporting is consitent with @david1025 .
My environment:
* JDK: 1.8
* OS: Win10
* Spring-boot：2.2.2.RELEASE
* Spring-cloud：Hoxton.SR1
* spring-cloud-alibaba-dependencies：2.2.0.RELEASE
* seata-all: 1.1.0/1.2.0

**Comment by yoonicoo** [comment]
ConfigurationCache
 public Configuration proxy(Configuration originalConfiguration) {
        return (Configuration)Enhancer.create(Configuration.class,
            (MethodInterceptor)(proxy, method, args, methodProxy) -> {
                if (method.getName().startsWith(METHOD_PREFIX)
                    && !method.getName().equalsIgnoreCase(METHOD_LATEST_CONFIG)) {
                    String rawDataId = (String)args[0];
                    Object result = CONFIG_CACHE.get(rawDataId);
                    if (null == result) {
                        result = method.invoke(originalConfiguration, args);
                        if (result != null) {
                            CONFIG_CACHE.put(rawDataId, result);
                        }
                    }
                    if (null != result && method.getReturnType().equals(String.class)) {
                        return String.valueOf(result);
                    }
                    return result;
                }
                return method.invoke(originalConfiguration, args);
            });
    }

proxy方法中只转化了一个String类型, 使用nacos做配置中心 boolean类型 会出错

**Comment by rainbowyao** [comment]
问题解决了么？我也是同样的问题

2021-03-24 16:13:29,433 [fileListener_3_1] ERROR [io.seata.config.FileConfiguration] FileConfiguration.java:378 - fileListener execute error, dataId :service.disableGlobalTransaction
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor221.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.seata.config.ConfigurationCache.lambda$proxy$1(ConfigurationCache.java:95)
	at io.seata.config.Configuration$$EnhancerByCGLIB$$5b8ab9c0.getLatestConfig(<generated>)
	at io.seata.config.FileConfiguration$FileListener.onChangeEvent(FileConfiguration.java:365)
	at io.seata.config.ConfigurationChangeListener.lambda$onProcessEvent$0(ConfigurationChangeListener.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getLatestConfig(<generated>)
	... 14 common frames omitted

**Comment by qq1146514641** [comment]
@chengshihard 同样的问题，你现在解决了吗
