### ISSUE TITLE
1.1.0 version is registered as file when integrating eureka

### ISSUE THREAD

**Issue by hengboy** [seata/seata#2428]
Use version 0.9.0, check "ConfigurationFactory # CURRENT_FILE_INSTANCE" static constant initialization, you can find "registry.typ" e value is "eureka", and use version 1.1.0 to track the value of the CURRENT_FILE_INSTANCE class, configure the collection and No "registry.type"

**Comment by hengboy** [comment]
No "registry.type = eureka" configuration causes the default file method to be used

**Comment by hengboy** [comment]
```
2020-03-19 22:05:38.789  INFO 1363 --- [           main] i.s.c.r.netty.NettyClientChannelManager  : will connect to 127.0.0.1:8091
2020-03-19 22:05:38.789  INFO 1363 --- [           main] io.seata.core.rpc.netty.RmRpcClient      : RM will register :jdbc:mysql://39.106.161.xxx:3306/iot-service
2020-03-19 22:05:38.791  INFO 1363 --- [           main] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:RMROLE,address:127.0.0.1:8091,msg:< RegisterRMRequest{resourceIds='jdbc:mysql://39.106.161.xxx:3306/iot-service', applicationId='iot-server-service-device', transactionServiceGroup='iot-screen-tx-group'} >
2020-03-19 22:05:38.866  INFO 1363 --- [lector_RMROLE_1] i.s.core.rpc.netty.AbstractRpcRemoting   : ChannelHandlerContext(AbstractRpcRemotingClient$ClientHandler#0, [id: 0xb29f9590]) will closed
2020-03-19 22:05:38.866 ERROR 1363 --- [           main] i.s.c.r.netty.NettyClientChannelManager  : 0304 register RM failed.

io.seata.common.exception.FrameworkException: can not connect to services-server.
	at io.seata.core.rpc.netty.RpcClientBootstrap.getNewChannel(RpcClientBootstrap.java:217) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:58) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:34) ~[seata-all-1.1.0.jar:1.1.0]
```

**Comment by slievrly** [comment]
@hengboy CURRENT_FILE_INSTANCE has always been the file, because it is used for reading configuration files, you should go to see whether can go EurekaRegistryServiceImpl.

**Comment by hengboy** [comment]
@slievrly I encountered this problem when upgrading from 0.9.0 to 1.1.0. The value of the "registry.type" configuration is "eureka". I hit a breakpoint and did not go through "EurekaRegistryServiceImpl"

**Comment by hengboy** [comment]
@slievrly The RegistryType obtained in the "io.seata.discovery.registry.RegistryFactory # getInstance" method is File, which returns "FileRegistryServiceImpl"

**Comment by hengboy** [comment]
**registry.conf：**
```
registry {
  # file、nacos、eureka、redis、zk、consul
  type = "eureka"

  eureka {
    serviceUrl = "http://user:password@39.160.161.xx/eureka"
    application = "seata-server"
    weight = "1"
  }
}

config {
  type = "file"

  file {
    name = "file.conf"
  }
}
```

**Comment by hengboy** [comment]
```java
String registryTypeName = ConfigurationFactory.CURRENT_FILE_INSTANCE.getConfig(
            ConfigurationKeys.FILE_ROOT_REGISTRY + ConfigurationKeys.FILE_CONFIG_SPLIT_CHAR
                + ConfigurationKeys.FILE_ROOT_TYPE);
```
The "registryTypeName" value is "file"，Expected value should be "eureka"
