### ISSUE TITLE
使用mybais,一个sql中含有两个或以上的sql语句,会报错

### ISSUE THREAD

**Issue by sj13824803000** [seata/seata#2436]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.lang.UnsupportedOperationException: Unsupported SQL: CREATE TABLE A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"
(
    "id"           varchar(50) NOT NULL,
    "pid"          varchar(50)  DEFAULT '-1',
    "com_type"     int4         DEFAULT 0,
    "com_name"     varchar(200) DEFAULT '',
    "floor_no"     int4         DEFAULT 0,
    "ele_id"       int4         DEFAULT 0,
    "is_deleted"   int2         DEFAULT 0,
    "gmt_create"   timestamp(255),
    "gmt_modified" timestamp(255),
    PRIMARY KEY ("id")
);
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."id" IS '主键';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."pid" IS '父节点, 根节点为-1';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."com_type" IS '构件类型';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."com_name" IS '构件名称';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."floor_no" IS '楼层';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."ele_id" IS '标高';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."is_deleted" IS '是否删除,逻辑删除标识 0-未删除 1-已删除';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."gmt_create" IS '创建时间';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."gmt_modified" IS '最后修改时间,如果没有修改过,则和创建时间一致';
COMMENT ON TABLE A91A9921630E34C1D9A0CFF7D673005E6."t_com_define" IS '构件定义主表';
### Cause: java.lang.UnsupportedOperationException: Unsupported SQL: CREATE TABLE A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"
(
    "id"           varchar(50) NOT NULL,
    "pid"          varchar(50)  DEFAULT '-1',
    "com_type"     int4         DEFAULT 0,
    "com_name"     varchar(200) DEFAULT '',
    "floor_no"     int4         DEFAULT 0,
    "ele_id"       int4         DEFAULT 0,
    "is_deleted"   int2         DEFAULT 0,
    "gmt_create"   timestamp(255),
    "gmt_modified" timestamp(255),
    PRIMARY KEY ("id")
);
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."id" IS '主键';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."pid" IS '父节点, 根节点为-1';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."com_type" IS '构件类型';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."com_name" IS '构件名称';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."floor_no" IS '楼层';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."ele_id" IS '标高';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."is_deleted" IS '是否删除,逻辑删除标识 0-未删除 1-已删除';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."gmt_create" IS '创建时间';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."gmt_modified" IS '最后修改时间,如果没有修改过,则和创建时间一致';
COMMENT ON TABLE A91A9921630E34C1D9A0CFF7D673005E6."t_com_define" IS '构件定义主表';
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy171.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:294)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy187.executeSql(Unknown Source)
	at com.sjkj.micro.model.app.ext.module.service.impl.ExtDatabaseServiceImpl.createDatabase(ExtDatabaseServiceImpl.java:64)
	at com.sjkj.micro.model.app.ext.module.service.impl.ExtDatabaseServiceImpl$$FastClassBySpringCGLIB$$3c844c0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$1.execute(GlobalTransactionalInterceptor.java:109)
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:64)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:106)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:83)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.sjkj.micro.model.app.ext.module.service.impl.ExtDatabaseServiceImpl$$EnhancerBySpringCGLIB$$c5c40a78.createDatabase(<generated>)
	at com.sjkj.micro.model.app.ext.module.service.impl.ExtDatabaseServiceImpl.initDatabase(ExtDatabaseServiceImpl.java:81)
	at com.sjkj.micro.model.app.ext.module.service.impl.ExtDatabaseServiceImpl$$FastClassBySpringCGLIB$$3c844c0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:87)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.sjkj.micro.model.app.ext.module.service.impl.ExtDatabaseServiceImpl$$EnhancerBySpringCGLIB$$c5c40a78.initDatabase(<generated>)
	at com.sjkj.micro.model.app.ext.module.controller.ExtModelDataController.coverData(ExtModelDataController.java:40)
	at com.sjkj.micro.model.app.ext.module.controller.ExtModelDataController$$FastClassBySpringCGLIB$$2ab8bc72.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.wugh.fast.module.web.ControllerLoggerAspect.doLog(ControllerLoggerAspect.java:47)
	at sun.reflect.GeneratedMethodAccessor378.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.sjkj.micro.model.app.ext.module.controller.ExtModelDataController$$EnhancerBySpringCGLIB$$aab094.coverData(<generated>)
	at sun.reflect.GeneratedMethodAccessor376.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:798)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.wugh.fast.module.mapper.filter.DynamicSchemaFilter.doFilterInternal(DynamicSchemaFilter.java:41)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.wugh.fast.module.mapper.filter.CustomPluginsFilter.doFilterInternal(CustomPluginsFilter.java:29)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:82)
	at org.springframework.cloud.sleuth.instrument.web.LazyTracingFilter.doFilter(TraceWebServletAutoConfiguration.java:145)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:41002)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.lang.UnsupportedOperationException: Unsupported SQL: CREATE TABLE A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"
(
    "id"           varchar(50) NOT NULL,
    "pid"          varchar(50)  DEFAULT '-1',
    "com_type"     int4         DEFAULT 0,
    "com_name"     varchar(200) DEFAULT '',
    "floor_no"     int4         DEFAULT 0,
    "ele_id"       int4         DEFAULT 0,
    "is_deleted"   int2         DEFAULT 0,
    "gmt_create"   timestamp(255),
    "gmt_modified" timestamp(255),
    PRIMARY KEY ("id")
);
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."id" IS '主键';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."pid" IS '父节点, 根节点为-1';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."com_type" IS '构件类型';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."com_name" IS '构件名称';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."floor_no" IS '楼层';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."ele_id" IS '标高';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."is_deleted" IS '是否删除,逻辑删除标识 0-未删除 1-已删除';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."gmt_create" IS '创建时间';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."gmt_modified" IS '最后修改时间,如果没有修改过,则和创建时间一致';
COMMENT ON TABLE A91A9921630E34C1D9A0CFF7D673005E6."t_com_define" IS '构件定义主表';
### Cause: java.lang.UnsupportedOperationException: Unsupported SQL: CREATE TABLE A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"
(
    "id"           varchar(50) NOT NULL,
    "pid"          varchar(50)  DEFAULT '-1',
    "com_type"     int4         DEFAULT 0,
    "com_name"     varchar(200) DEFAULT '',
    "floor_no"     int4         DEFAULT 0,
    "ele_id"       int4         DEFAULT 0,
    "is_deleted"   int2         DEFAULT 0,
    "gmt_create"   timestamp(255),
    "gmt_modified" timestamp(255),
    PRIMARY KEY ("id")
);
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."id" IS '主键';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."pid" IS '父节点, 根节点为-1';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."com_type" IS '构件类型';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."com_name" IS '构件名称';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."floor_no" IS '楼层';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."ele_id" IS '标高';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."is_deleted" IS '是否删除,逻辑删除标识 0-未删除 1-已删除';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."gmt_create" IS '创建时间';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."gmt_modified" IS '最后修改时间,如果没有修改过,则和创建时间一致';
COMMENT ON TABLE A91A9921630E34C1D9A0CFF7D673005E6."t_com_define" IS '构件定义主表';
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at sun.reflect.GeneratedMethodAccessor404.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 131 common frames omitted
Caused by: java.lang.UnsupportedOperationException: Unsupported SQL: CREATE TABLE A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"
(
    "id"           varchar(50) NOT NULL,
    "pid"          varchar(50)  DEFAULT '-1',
    "com_type"     int4         DEFAULT 0,
    "com_name"     varchar(200) DEFAULT '',
    "floor_no"     int4         DEFAULT 0,
    "ele_id"       int4         DEFAULT 0,
    "is_deleted"   int2         DEFAULT 0,
    "gmt_create"   timestamp(255),
    "gmt_modified" timestamp(255),
    PRIMARY KEY ("id")
);
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."id" IS '主键';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."pid" IS '父节点, 根节点为-1';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."com_type" IS '构件类型';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."com_name" IS '构件名称';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."floor_no" IS '楼层';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."ele_id" IS '标高';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."is_deleted" IS '是否删除,逻辑删除标识 0-未删除 1-已删除';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."gmt_create" IS '创建时间';
COMMENT ON COLUMN A91A9921630E34C1D9A0CFF7D673005E6."t_com_define"."gmt_modified" IS '最后修改时间,如果没有修改过,则和创建时间一致';
COMMENT ON TABLE A91A9921630E34C1D9A0CFF7D673005E6."t_com_define" IS '构件定义主表';
	at io.seata.sqlparser.druid.DruidSQLRecognizerFactoryImpl.create(DruidSQLRecognizerFactoryImpl.java:40)
	at io.seata.sqlparser.druid.DruidDelegatingSQLRecognizerFactory.create(DruidDelegatingSQLRecognizerFactory.java:59)
	at io.seata.rm.datasource.sql.SQLVisitorFactory.get(SQLVisitorFactory.java:47)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:73)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:47)
	at io.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:54)
	at sun.reflect.GeneratedMethodAccessor385.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy285.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.GeneratedMethodAccessor405.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy283.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	... 135 common frames omitted

**Comment by zjinlei** [comment]
https://github.com/seata/seata/pull/2112
welcome to review together
