### ISSUE TITLE
Failed to get available servers NPE problem

### ISSUE THREAD

**Issue by hc-wwyz** [seata/seata#2499]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

在k8s环境中使用服务名作为seata server的地址，比如：seata-server:8091,如果seata-server不可用，即无法获取seata-server的IP，则io.seata.common.util.NetUtil.toStringAddress(NetUtil.java:74)会有NPE问题。

```
2020-04-01 09:51:07.208 ERROR 8 --- [           main] i.s.c.r.netty.NettyClientChannelManager  : Failed to get available servers: null

java.lang.NullPointerException: null
	at io.seata.common.util.NetUtil.toStringAddress(NetUtil.java:74) ~[seata-all-1.1.0.jar!/:1.1.0]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_222]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_222]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_222]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_222]
```

### Ⅲ. Describe what you expected to happen
封装此错误，改为警告提示，而不是抛出这个错误

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 在k8s环境部署seata client项目
2. 配置一个不可用的seata server地址

### Ⅵ. Environment:

- version : 1.1.0

**Comment by slievrly** [comment]
@hc-wwyz seata.service.disable-global-transaction=true

**Comment by hc-wwyz** [comment]
这样会不会导致seata不工作呢，使用场景还是希望配置文件配置seata可以工作，即使seata-server不可用，错误提示一下，而不直接报错

**Comment by Garlichead** [comment]
> 这样会不会导致seata不工作呢，使用场景还是希望配置文件配置seata可以工作，即使seata-server不可用，错误提示一下，而不直接报错

这边seata 服务不可用的时候 阻碍了整个seata的执行调用链路吗 会影响到服务的正常运转吗？我记得在之前的文档中又看到 seata对于这块的控制 可以保证seata-server挂了 依然可以运转服务

**Comment by Garlichead** [comment]
this Happening, I think may encounter.

**Comment by slievrly** [comment]
> 这样会不会导致seata不工作呢，使用场景还是希望配置文件配置seata可以工作，即使seata-server不可用，错误提示一下，而不直接报错

When the k8s service of seata-server is unavailable, the distributed transaction service cannot be provided externally, and the business can only choose to take the initiative or automatically degrade.
