### ISSUE TITLE
启动seata后不停的报java.io.IOException: Connection reset by peer 服务却能正常工作

### ISSUE THREAD

**Issue by am-wangjin** [seata/seata#2507]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在docker容器中启动seat后不停的报java.io.IOException: Connection reset by peer 服务却能正常工作

### Ⅱ. Describe what happened

  异常内容如下，大概不到1秒左右刷一次下面的异常,除了请求的端口是随机以外，其他内容
一致:

```
2020-04-03T11:46:57.28417124Z java.io.IOException: Connection reset by peer
2020-04-03T11:46:57.284174038Z 	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
2020-04-03T11:46:57.284177079Z 	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
2020-04-03T11:46:57.284179567Z 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
2020-04-03T11:46:57.284182002Z 	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
2020-04-03T11:46:57.284184329Z 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
2020-04-03T11:46:57.284186715Z 	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
2020-04-03T11:46:57.28418908Z 	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
2020-04-03T11:46:57.28419146Z 	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
2020-04-03T11:46:57.284194061Z 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
2020-04-03T11:46:57.284197642Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
2020-04-03T11:46:57.284201103Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
2020-04-03T11:46:57.284215442Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
2020-04-03T11:46:57.284219232Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
2020-04-03T11:46:57.284221972Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
2020-04-03T11:46:57.284224333Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2020-04-03T11:46:57.284226813Z 	at java.lang.Thread.run(Thread.java:748)
2020-04-03T11:46:57.284274475Z 2020-04-03 11:46:57.284 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0x0824fea4, L:/172.16.1.72:30032 - R:/172.16.1.1:29362],address:172.16.1.1:29362
2020-04-03T11:46:57.284406224Z 2020-04-03 11:46:57.284 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:518 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x0824fea4, L:/172.16.1.72:30032 - R:/172.16.1.1:29362]) will closed
2020-04-03T11:46:57.284607497Z 2020-04-03 11:46:57.284 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:518 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x0824fea4, L:/172.16.1.72:30032 ! R:/172.16.1.1:29362]) will closed
2020-04-03T11:46:57.284727866Z 2020-04-03 11:46:57.284 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:254 -172.16.1.1:29362 to server channel inactive.
2020-04-03T11:46:57.284823229Z 2020-04-03 11:46:57.284 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0x0824fea4, L:/172.16.1.72:30032 ! R:/172.16.1.1:29362]
2020-04-03T11:46:57.602891014Z 2020-04-03 11:46:57.602 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Connection reset by peer,channel:[id: 0xe1db263c, L:/172.16.1.72:30032 - R:/172.16.1.1:26176]
2020-04-03T11:46:57.603198375Z 2020-04-03 11:46:57.602 ERROR[NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:505 -0318
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
@am-wangjin Please send me a log file to see.

**Comment by am-wangjin** [comment]
[seata-server.log](https://github.com/seata/seata/files/4427119/seata-server.log)

**Comment by am-wangjin** [comment]
找到原因了，因为腾讯云的健康检测不停的请求了seat服务的端口，seat不停的拒绝照成的

**Comment by WanghuaNero** [comment]
我也是这个问题，我是在阿里云上的Kubernetes服务，用官网的k8 yaml启动了，服务是正常的，流程都能走通。但是就是一直报Connection reset by peer这个错误。

**Comment by WanghuaNero** [comment]
> 找到原因了，因为腾讯云的健康检测不停的请求了seat服务的端口，seat不停的拒绝照成的

兄弟，我也出现这个问题了，一直报Connection reset by peer，不过我是在阿里云的Kubernetes环境中部署的，但是功能都是正常的，这个要如何处理？
