### ISSUE TITLE
DB模式启动报错

### ISSUE THREAD

**Issue by txlaijava** [seata/seata#2517]
I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
```
ERROR[main]io.seata.core.store.db.LogStoreDataBaseDAO.queryTableStructure:508 -query transaction_name size fail, You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'HAVING TABLE_TYPE IN ('TABLE',null,null,null,null) ORDER BY TABLE_TYPE, TABLE_SC' at line 1
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'HAVING TABLE_TYPE IN ('TABLE',null,null,null,null) ORDER BY TABLE_TYPE, TABLE_SC' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1019)
	at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.executeMetadataQuery(DatabaseMetaDataUsingInfoSchema.java:62)
	at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.getTables(DatabaseMetaDataUsingInfoSchema.java:835)
	at org.apache.commons.dbcp.DelegatingDatabaseMetaData.getTables(DelegatingDatabaseMetaData.java:604)
	at io.seata.core.store.db.LogStoreDataBaseDAO.queryTableStructure(LogStoreDataBaseDAO.java:485)
	at io.seata.core.store.db.LogStoreDataBaseDAO.initTransactionNameSize(LogStoreDataBaseDAO.java:466)
	at io.seata.core.store.db.LogStoreDataBaseDAO.init(LogStoreDataBaseDAO.java:119)
	at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:365)
	at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:245)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:140)
	at io.seata.server.store.db.DatabaseTransactionStoreManager.init(DatabaseTransactionStoreManager.java:102)
	at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:365)
	at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:245)
	at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:205)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:87)
	at io.seata.server.session.db.DataBaseSessionManager.init(DataBaseSessionManager.java:82)
	at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:365)
	at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:245)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:124)
	at io.seata.server.session.SessionHolder.init(SessionHolder.java:100)
	at io.seata.server.Server.main(Server.java:75)

```

### Ⅱ. Describe what happened
驱动已跟换成：mysql-connector-java-8.0.11.jar，数据库版本为8.0。DB配置：
```
db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "dbcp"
    ## mysql/oracle/h2/oceanbase etc.
    dbType = "mysql"
    driverClassName = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://127.0.0.1:3306/seata"
    user = "root"
    password = "hongyunbao123"
    minConn = 1
    maxConn = 10
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    queryLimit = 100
  }
```

### Ⅵ. Environment:

- JDK version :1.8
- OS : mac

**Comment by txlaijava** [comment]
找到问题了，MYSQL版本跟MYSQL驱动版本不一致导致的问题。 THANKS。
