### ISSUE TITLE
怎么解决 "can not register RM,err:can not connect to services-server." ?

### ISSUE THREAD

**Issue by GZHua** [seata/seata#2522]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在使用seata1.1.0运行seata-samples/springcloud-nacos-seata项目时出现这个错误, 我在网上查询尝试了很多方法,也没办法解决这问题.
已确认以下解决方案:
1. config.txt key改为驼峰形式
2. service.vgroupMapping的后缀, seata-server和client配置一致

**这个问题似乎是client无法连接seata server, seata server启动后的IP是个奇怪的IP "169.254.101.48". 这个IP无法ping通, 我想这是问题的关键**
因为报错 "0101 can not connect to 169.254.101.48:8091 cause:can not register RM,err:can not connect to services-server." client无法连接到这个IP, 但是这个IP是 seata-server自己设置的, 启动参数也没有可以设置的 

### Ⅱ. Describe what happened

  我的配置:
seata server:
```txt
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "nacos"

  nacos {
    serverAddr = "localhost"
    namespace = ""
    cluster = "default"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "nacos"

  nacos {
    serverAddr = "localhost"
    namespace = ""
    group = "SEATA_GROUP"
  }
}

```
config.txt:
```
store.mode=db
store.db.driverClassName=com.mysql.cj.jdbc.Driver
store.db.url=jdbc:mysql://localhost:3306/seata?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=UTC
store.db.user=root
store.db.password=root
store.db.branch.table=branch_table
store.db.datasource=dbcp
store.db.dbType=mysql
store.db.global.table=global_table
store.db.lockTable=lock_table
store.db.maxConn=3
store.db.minConn=1
store.db.queryLimit=100
store.file.dir=file_store/data
store.file.fileWriteBufferCacheSize=16384
store.file.flushDiskMode=async
store.file.maxBranchSessionSize=16384
store.file.maxGlobalSessionSize=512
client.async.commit.buffer.limit=10000
client.lock.retry.internal=10
client.lock.retry.times=30
client.report.retry.count=5
client.support.spring.datasource.autoproxy=true
metrics.enabled=false
metrics.exporterList=prometheus
metrics.exporterPrometheusPort=9898
metrics.registryType=compact
recovery.asynCommittingRetryPeriod=1000
recovery.committingRetryPeriod=1000
recovery.rollbackingRetryPeriod=1000
recovery.timeoutRetryPeriod=1000
service.disable=false
service.disableGlobalTransaction=false
service.enableDegrade=false
service.max.commit.retry.timeout=-1
service.max.rollback.retry.timeout=-1
service.default.grouplist=192.168.1.189:8091
store.file.session.reload.read_size=100
transaction.undo.data.validation=true
transaction.undo.log.delete.period=86400000
transaction.undo.log.save.days=7
transaction.undo.log.serialization=jackson
transaction.undo.log.table=undo_log
transport.compressor=none
transport.heartbeat=true
transport.serialization=seata
transport.server=NIO
transport.shutdown.wait=3
transport.threadFactory.bossThreadPrefix=NettyBoss
transport.threadFactory.bossThreadSize=1
transport.threadFactory.clientSelectorThreadPrefix=NettyClientSelector
transport.threadFactory.clientSelectorThreadSize=1
transport.threadFactory.clientWorkerThreadPrefix=NettyClientWorkerThread
transport.threadFactory.serverExecutorThreadPrefix=NettyServerBizHandler
transport.threadFactory.shareBossWorker=false
transport.threadFactory.workerThreadPrefix=NettyServerNIOWorker
transport.threadFactory.workerThreadSize=8
transport.type=TCP

service.vgroupMapping.storageServiceGroup=default
service.vgroupMapping.orderServiceGroup=default
```
MySQL连接驱动我已经更换了, config.txt的已经导入到nacos中
![image](https://user-images.githubusercontent.com/33946039/78850811-b8834280-7a4a-11ea-952e-26809bdeb270.png)

seata-server的启动命令 sh seata-server.sh -p 8091 -h 127.0.0.1 -m db
nacos启动命令 sh startup.sh -m standalone

client:
  registry.conf:
```
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "nacos"

  nacos {
    serverAddr = "localhost"
    namespace = ""
    cluster = "default"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "nacos"

  nacos {
    serverAddr = "localhost"
    namespace = ""
    group = "SEATA_GROUP"
  }
}

```
两个服务的register.conf一样

storage-service: application.properties
```
spring.application.name=storage-service
server.port=9092
# Nacos 注册中心地址
spring.cloud.nacos.discovery.server-addr=localhost
# seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
spring.cloud.alibaba.seata.tx-service-group=storageServiceGroup
logging.level.io.seata=debug
# 数据源配置
spring.datasource.druid.url=jdbc:mysql://localhost:3306/seata_storage?allowMultiQueries=true
spring.datasource.druid.driverClassName=com.mysql.jdbc.Driver
spring.datasource.druid.username=root
spring.datasource.druid.password=root
```

order-service: application.properties
```
spring.application.name=order-service
server.port=9091
# Nacos 注册中心地址
spring.cloud.nacos.discovery.server-addr=localhost
# seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
spring.cloud.alibaba.seata.tx-service-group=orderServiceGroup
logging.level.io.seata=debug
# 数据源配置
spring.datasource.druid.url=jdbc:mysql://localhost:3306/seata_order?allowMultiQueries=true
spring.datasource.druid.driverClassName=com.mysql.jdbc.Driver
spring.datasource.druid.username=root
spring.datasource.druid.password=root
```

所有服务都注册到nacos中了
![image](https://user-images.githubusercontent.com/33946039/78851060-6ee72780-7a4b-11ea-90bf-0b4b6911bddb.png)

 堆栈错误信息:
```
2020-04-09 10:08:57.280 ERROR 7432 --- [nio-9091-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.seata.common.exception.FrameworkException: can not register RM,err:can not connect to services-server.] with root cause

io.seata.common.exception.FrameworkException: can not register RM,err:can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:210) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:103) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.sendMsgWithResponse(AbstractRpcRemotingClient.java:141) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.sendMsgWithResponse(AbstractRpcRemotingClient.java:148) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.tm.DefaultTransactionManager.syncCall(DefaultTransactionManager.java:95) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.tm.DefaultTransactionManager.begin(DefaultTransactionManager.java:53) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.tm.api.DefaultGlobalTransaction.begin(DefaultGlobalTransaction.java:105) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.tm.api.TransactionalTemplate.beginTransaction(TransactionalTemplate.java:123) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:58) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:106) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:83) ~[seata-all-1.1.0.jar:1.1.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at com.work.order.service.OrderService$$EnhancerBySpringCGLIB$$d4e10b8f.placeOrder(<generated>) ~[classes/:na]
	at com.work.order.controller.OrderController.placeOrderCommit(OrderController.java:38) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_211]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) ~[spring-webmvc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) ~[druid-1.1.12.jar:1.1.12]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_211]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]
```

### Ⅲ. Describe what you expected to happen

正常运行, 能测试事务以及回滚

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
1. download and run nacos 1.2.1 
2. download and run seata-server 1.1.0
3. clone seata-samples/springcloud-nacos-seata项目, 使用上述配置运行

### Ⅵ. Environment:

- JDK version : 1.8
- OS : win10,  wsl2 centos 7.5 
- Others:

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/78864914-453ff780-7a6f-11ea-9ca4-c601883cf0a3.png)
@GZHua check seata-server registry ipAddress.

**Comment by GZHua** [comment]
> ![image](https://user-images.githubusercontent.com/8758457/78864914-453ff780-7a6f-11ea-9ca4-c601883cf0a3.png)
> @GZHua check seata-server registry ipAddress.

![image](https://user-images.githubusercontent.com/33946039/78867589-e92ba200-7a73-11ea-8ee9-c49dd9722e50.png)
This is the cause of the error. my ip is 192.168.1.189 and  unknow where the 169.254.101.48  came from
![image](https://user-images.githubusercontent.com/33946039/78867670-052f4380-7a74-11ea-90f7-cf4d5e72f75c.png)

Can I specify this ip?

**Comment by GZHua** [comment]
问题原因就是WSL下seata-server的启动IP不正确  就像docker部署要加-e SEATA_IP=192.168.1.1来强制指定启动IP

**Comment by Garlichead** [comment]
> 问题原因就是WSL下seata-server的启动IP不正确  就像docker部署要加-e SEATA_IP=192.168.1.1来强制指定启动IP

厉害

**Comment by Garlichead** [comment]
在部署 联调过程中 网络还是很关键的

**Comment by chenhaoenen** [comment]
> 问题原因就是WSL下seata-server的启动IP不正确 就像docker部署要加-e SEATA_IP=192.168.1.1来强制指定启动IP

您好，大佬，麻烦问下，我在wsl下加了环境变量 -e SEATA_IP=192.168.1.1 启动seata-server服务，但是 client端还是有
`
2022-10-05 22:59:30.864 ERROR 21900 --- [  restartedMain] i.s.c.r.netty.NettyClientChannelManager  : 0101 can not connect to 192.168.1.1:8091 cause:can not register RM,err:can not connect to services-server.

io.seata.common.exception.FrameworkException: can not register RM,err:can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:250) ~[seata-all-1.5.1.jar:1.5.1]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:112) ~[seata-all-1.5.1.jar:1.5.1]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:196) ~[seata-all-1.5.1.jar:1.5.1]
	at io.seata.core.rpc.netty.TmNettyRemotingClient.init(TmNettyRemotingClient.java:182) [seata-all-1.5.1.jar:1.5.1]
	at io.seata.tm.TMClient.init(TMClient.java:47) [seata-all-1.5.1.jar:1.5.1]
	at io.seata.spring.annotation.GlobalTransactionScanner.initClient(GlobalTransactionScanner.java:220) [seata-all-1.5.1.jar:1.5.1]
	at io.seata.spring.annotation.GlobalTransactionScanner.afterPropertiesSet(GlobalTransactionScanner.java:512) [seata-all-1.5.1.jar:1.5.1]
`
麻烦问下，该怎么处理呢，谢谢大佬！

**Comment by linsiming** [comment]
2024-12-09 13:02:24.341 INFO  1 --- [timeoutChecker_1_1] i.s.c.r.n.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:56): NettyPool create channel to transactionRole:TMROLE,address:10.11.144.232:30095,msg:< RegisterTMRequest{version='1.8.0', applicationId='*******', transactionServiceGroup='my_test_tx_group', extraData='ak=null
digest=my_test_tx_group,172.20.0.7,1733720544341
timestamp=1733720544341
authVersion=V4
vgroup=my_test_tx_group
ip=172.20.0.7
'} >
2024-12-09 13:02:24.951 ERROR 1 --- [timeoutChecker_2_1] i.s.c.r.n.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:239): 0304 register RM failed.
io.seata.common.exception.FrameworkException: can not connect to services-server.

**Comment by linsiming** [comment]
> 2024-12-09 13:02:24.341 INFO 1 --- [timeoutChecker_1_1] i.s.c.r.n.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:56): NettyPool create channel to transactionRole:TMROLE,address:10.11.144.232:30095,msg:< RegisterTMRequest{version='1.8.0', applicationId='*******', transactionServiceGroup='my_test_tx_group', extraData='ak=null digest=my_test_tx_group,172.20.0.7,1733720544341 timestamp=1733720544341 authVersion=V4 vgroup=my_test_tx_group ip=172.20.0.7 '} > 2024-12-09 13:02:24.951 ERROR 1 --- [timeoutChecker_2_1] i.s.c.r.n.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:239): 0304 register RM failed. io.seata.common.exception.FrameworkException: can not connect to services-server.

这是docker环境，且不上一个网段。客户端请求的ip是172.20.0.7，个人理解是这个ip问题导致。
但是如何设置和seata连接是的ip？

**Comment by moontea** [comment]
> 2024-12-09 13:02:24.341 INFO 1 --- [timeoutChecker_1_1] i.s.c.r.n.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:56): NettyPool create channel to transactionRole:TMROLE,address:10.11.144.232:30095,msg:< RegisterTMRequest{version='1.8.0', applicationId='*******', transactionServiceGroup='my_test_tx_group', extraData='ak=null digest=my_test_tx_group,172.20.0.7,1733720544341 timestamp=1733720544341 authVersion=V4 vgroup=my_test_tx_group ip=172.20.0.7 '} > 2024-12-09 13:02:24.951 ERROR 1 --- [timeoutChecker_2_1] i.s.c.r.n.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:239): 0304 register RM failed. io.seata.common.exception.FrameworkException: can not connect to services-server.

你这个SEATA_IP要设置成宿主机IP，应该就可以了
