### ISSUE TITLE
并发测试，报错Global lock acquire failed

### ISSUE THREAD

**Issue by wuyongc** [seata/seata#2555]
seata进行（50）并发测试，报错，感觉是全局锁的问题，这个是什么原因，比较困惑
2020-04-15 11:00:40.088 INFO [batchLoggerPrint_1]io.seata.core.rpc.DefaultServerMessageListenerImpl.run:206 -SeataMergeMessage xid=127.0.0.1:8091:2040644538,branchType=AT,resourceId=jdbc:mysql://127.0.0.1:3307/storage,lockKey=storage:1
,clientIp127.0.0.1,vgroup:my_test_tx_group
2020-04-15 11:00:40.092 INFO [ServerHandlerThread_1_500]io.seata.core.store.db.LockStoreDataBaseDAO.acquireLock:141 -Global lock on [storage:1] is holding by xid 127.0.0.1:8091:2040644537 branchId 2040644597
2020-04-15 11:00:40.094 ERROR[ServerHandlerThread_1_500]io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate:120 -Catch TransactionException while do RPC, request: xid=127.0.0.1:8091:2040644538,branchType=AT,resourceId=jdbc:mysql://127.0.0.1:3307/storage,lockKey=storage:1
io.seata.core.exception.BranchTransactionException: Global lock acquire failed xid = 127.0.0.1:8091:2040644538 branchId = 2040644603
	at io.seata.server.transaction.at.ATCore.branchSessionLock(ATCore.java:48)
	at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:77)
	at io.seata.server.session.GlobalSession.lockAndExecute(GlobalSession.java:616)
	at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:72)
	at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:95)
	at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:188)
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:172)
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:167)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:117)
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:167)
	at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:430)
	at io.seata.core.rpc.DefaultServerMessageListenerImpl.onTrxMessage(DefaultServerMessageListenerImpl.java:91)
	at io.seata.core.rpc.netty.AbstractRpcRemotingServer$ServerHandler.dispatch(AbstractRpcRemotingServer.java:196)
	at io.seata.core.rpc.netty.AbstractRpcRemoting$AbstractHandler$1.run(AbstractRpcRemoting.java:452)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745

**Comment by a364176773** [comment]
正常,因为并发小,效率不是特别高,操作同一条数据需要获取对应全局锁,而上一个拿到锁的事务没处理完,还没释放锁,下一个事务去获取锁的时候,目前默认是300ms,导致很快就超时,get lock fail,但是不影响一致性,失败的就默认回滚.

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/79303564-c55bd680-7f21-11ea-8a6f-cf9203013638.png)
调整这两个参数,使其获取锁周期合理化,减少出现getlockfail的异常

**Comment by wuyongc** [comment]
> ![image](https://user-images.githubusercontent.com/19943636/79303564-c55bd680-7f21-11ea-8a6f-cf9203013638.png)
> 调整这两个参数,使其获取锁周期合理化,减少出现getlockfail的异常
@a364176773 目前是尝试50并发，官方案例，创建订单order后，修改库存storage的同一条数据，失败率很高，参数我也尝试修改为20,60，但是又出现其它问题：TooLongFrameException: Adjusted frame length exceeds 8388608: 4245094388 - discarded；现在对seata是否支持并发有疑问，因为业务上肯定会有并发的情况；

**Comment by a364176773** [comment]
> > ![image](https://user-images.githubusercontent.com/19943636/79303564-c55bd680-7f21-11ea-8a6f-cf9203013638.png)
> > 调整这两个参数,使其获取锁周期合理化,减少出现getlockfail的异常
> > @a364176773 目前是尝试50并发，官方案例，创建订单order后，修改库存storage的同一条数据，失败率很高，参数我也尝试修改为20,60，但是又出现其它问题：TooLongFrameException: Adjusted frame length exceeds 8388608: 4245094388 - discarded；现在对seata是否支持并发有疑问，因为业务上肯定会有并发的情况；

上述异常跟并发无关,自己浏览器什么的访问了8091端口导致的,目前没有控制台不支持该访问形式

**Comment by wuyongc** [comment]
@a364176773  按照官网用用例，进行50并发测试，失败率在80%正常吗？在服务器上也进行过测试，8091端口我进行过检查，目前只有进行seata测试才会用到这个端口，seata不支持高并发吗？，
![image](https://user-images.githubusercontent.com/37923183/79307583-b2e59b00-7f29-11ea-9d48-bea0b55b651c.png)

**Comment by a364176773** [comment]
> @a364176773 按照官网用用例，进行50并发测试，失败率在80%正常吗？在服务器上也进行过测试，8091端口我进行过检查，目前只有进行seata测试才会用到这个端口，seata不支持高并发吗？，
> ![image](https://user-images.githubusercontent.com/37923183/79307583-b2e59b00-7f29-11ea-9d48-bea0b55b651c.png)

所有的分布式事务框架都会带来吞吐下降,特别是对同一个数据修改.还是上面说的,调整上面的锁周期来保证事务的成功率

**Comment by slievrly** [comment]
there is too much hot spot data and acquire locks fail when concurrent run the hot record.

**Comment by al-verson** [comment]
大佬们，我跑了seata-sample的springboot-mybatis模块，30并发就报了同样的错误，而且数据不一致了

**Comment by al-verson** [comment]
> 大佬们，我跑了seata-sample的springboot-mybatis模块，30并发就报了同样的错误，而且数据不一致了，订单，余额扣减完然后库存没扣减对应的数量，这个知道怎么破吗？

**Comment by wuyongc** [comment]
@al-verson 别用@GlobalLock

**Comment by wuyongc** [comment]
> there is too much hot spot data and acquire locks fail when concurrent run the hot record.

We are currently studying the seata transaction processing mechanism, but the concurrency failure rate is too high, it is difficult to control

**Comment by al-verson** [comment]
> @al-verson 别用@GlobalLock
大佬，这个跑的是官方的sample，好像是没有用到@GlobalLock，另外求问一下，出现数据不一致的问题，undo_log表里没有镜像，数据是不可以手动恢复了吗？感谢指教~

**Comment by al-verson** [comment]
> 正常,因为并发小,效率不是特别高,操作同一条数据需要获取对应全局锁,而上一个拿到锁的事务没处理完,还没释放锁,下一个事务去获取锁的时候,目前默认是300ms,导致很快就超时,get lock fail,但是不影响一致性,失败的就默认回滚.

大佬，失败了好像没有回滚，数据不一致了

**Comment by a364176773** [comment]
> > 正常,因为并发小,效率不是特别高,操作同一条数据需要获取对应全局锁,而上一个拿到锁的事务没处理完,还没释放锁,下一个事务去获取锁的时候,目前默认是300ms,导致很快就超时,get lock fail,但是不影响一致性,失败的就默认回滚.
> 
> 大佬，失败了好像没有回滚，数据不一致了

select+forupdate,来开启全局锁重试,检查数据源代理跟xid传递

**Comment by xiaoJiRun** [comment]
![1587553772(1)](https://user-images.githubusercontent.com/17246164/79975027-e34eab80-84cc-11ea-8acd-bb9c0a9c14dd.png)
这种操作如果保证加锁后一定能释放锁

**Comment by Garlichead** [comment]
应该是支持相对高并发性能.

**Comment by pearl88** [comment]
> > 并发运行热点记录时，热点数据过多，并且获取锁失败。
> 
> 我们目前正在研究seata事务处理机制，但是并发失败率太高，难以控制

大佬，怎么样了，并发时，数据不一致，不晓得啥原因，哭哭

**Comment by cmonkey** [comment]
> ![1587553772(1)](https://user-images.githubusercontent.com/17246164/79975027-e34eab80-84cc-11ea-8acd-bb9c0a9c14dd.png)
> 这种操作如果保证加锁后一定能释放锁。 比如释放锁时，获取不到连接，是否当前锁不会再释放了

这个时候你的数据库服务器上面一定有配置rollback timeout 这类参数，这是数据库服务器的行为

**Comment by xiaoJiRun** [comment]
> > ![1587553772(1)](https://user-images.githubusercontent.com/17246164/79975027-e34eab80-84cc-11ea-8acd-bb9c0a9c14dd.png)
> > 这种操作如果保证加锁后一定能释放锁。 比如释放锁时，获取不到连接，是否当前锁不会再释放了
> 
> 这个时候你的数据库服务器上面一定有配置rollback timeout 这类参数，这是数据库服务器的行为

这三次操作是隔离的，seata server 没用控制事务，不然也不用unlock了

**Comment by zhouweijun** [comment]
尝试修改store.db.maxConn 和 store.db.queryLimit 加大该数值进行测试
