### ISSUE TITLE
Postgresql集成报错，偶现，子事务执行报错get tablemeta failed

### ISSUE THREAD

**Issue by MrPassionFruit** [seata/seata#2560]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/36781382/79329809-02888e80-7f4b-11ea-95aa-875c0213cd95.png)

### Ⅱ. Describe what happened

 在springCloud集成seata分布式事务时，，使用oracle数据库没有问题，在使用postgresql的时候出现这个问题，但是在没有任何修改的前提下，执行多次之后，问题就自然解决了。是否是seata1.1.0版本在处理postgresql子事务创建的时候不稳定？

**Comment by MrPassionFruit** [comment]
java.sql.SQLException: Failed to fetch schema of C_AR_METER
	at io.seata.rm.datasource.sql.struct.cache.PostgresqlTableMetaCache.fetchSchema(PostgresqlTableMetaCache.java:77) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.rm.datasource.sql.struct.cache.AbstractTableMetaCache.lambda$getTableMeta$0(AbstractTableMetaCache.java:61) ~[seata-all-1.1.0.jar:1.1.0]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2039) ~[caffeine-2.6.2.jar:na]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853) ~[na:1.8.0_201]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037) ~[caffeine-2.6.2.jar:na]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020) ~[caffeine-2.6.2.jar:na]
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112) ~[caffeine-2.6.2.jar:na]
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54) ~[caffeine-2.6.2.jar:na]
	at io.seata.rm.datasource.sql.struct.cache.AbstractTableMetaCache.getTableMeta(AbstractTableMetaCache.java:59) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.getTableMeta(BaseTransactionalExecutor.java:189) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.getTableMeta(BaseTransactionalExecutor.java:174) ~[seata-all-1.1.0.jar:1.1.0]

**Comment by l81893521** [comment]
Could you mind paste you table structure here?

**Comment by MrPassionFruit** [comment]
我这边定位了一下，在使用Postgresql的时候，如果传的表名是大写的则报图中的错误，如果是小写的表名则没有问题，是否是因为大小写敏感的原因？

**Comment by MrPassionFruit** [comment]
![image](https://user-images.githubusercontent.com/36781382/79409216-ef6bd200-7fcf-11ea-9b92-dc08d039723b.png)
这里Like的时候，表名是大写，查询不到数据库表的结构，如果改成小写则ok

**Comment by l81893521** [comment]
@MrPassionFruit Thanks. Maybe you can try 1.2.0-SNAPSHOT. If the problem still there. Hope you can keep contact us.

**Comment by MrPassionFruit** [comment]
好的，，哪里可以下载1.2.0-SNAPSHOT版本呢？可否告知一下，谢谢！

**Comment by jsbxyyx** [comment]
in pom.xml
```
<repositories>
  <repository>
    <id>elife</id>
    <name>elife</name>
    <url>https://oss.sonatype.org/content/groups/public</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by MrPassionFruit** [comment]
1.2.0正式版本，什么时候可以出呢？

**Comment by MrPassionFruit** [comment]
1.2解决
