### ISSUE TITLE
LockConflictException: get global lock fail

### ISSUE THREAD

**Issue by jipeigong** [seata/seata#2569]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata版本：1.0.0
springcloud+seata+mybatis+mysql,eureka+db模式，使用注释@GlobalTransactional+@Transactional，在跨服务场景下一切正常，但是在单服务场景下的方法上加入两个事务注解运行出现异常（逻辑判断有可能调用其他服务也有可能不调用，问题出现在不调用其他服务的场景下）

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is io.seata.rm.datasource.exec.LockConflictException: get global lock fail, xid:192.168.1.48:8091:4008686782, lockKeys:lesson_topic:1250817221014327297;cancel_lesson:1250817473905692673;lesson_topic:1250817473876332545;lesson_class:1250817221026910209;foreign_teacher_booked_record:1250817473972801537;lesson:1250817473859555329;lesson_class:1250817473888915457;lesson:1250817220997550081
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:332)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:746)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:534)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:305)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$1.execute(GlobalTransactionalInterceptor.java:109)
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:64)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:106)
Caused by: io.seata.rm.datasource.exec.LockConflictException: get global lock fail, xid:192.168.1.48:8091:4008686782, lockKeys:lesson_topic:1250817221014327297;cancel_lesson:1250817473905692673;lesson_topic:1250817473876332545;lesson_class:1250817221026910209;foreign_teacher_booked_record:1250817473972801537;lesson:1250817473859555329;lesson_class:1250817473888915457;lesson:1250817220997550081
	at io.seata.rm.datasource.ConnectionProxy.recognizeLockKeyConflictException(ConnectionProxy.java:149)
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:213)
	at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:190)
	at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:178)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:283)
	at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:177)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:329)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:746)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:534)
```

### Ⅲ. Describe what you expected to happen
数据表操作顺序（单服务单库）：
```
 DELETE FROM lesson_class WHERE lesson_id = ? 
 
 UPDATE lesson SET is_deleted=1 WHERE id=?  AND is_deleted=0
 
 INSERT INTO lesson xxxxx
 
 INSERT INTO lesson_topic (id, lesson_id, gmt_create, gmt_modified) VALUES (?, ?, ?, ?)
 
 INSERT INTO lesson_class (id, lesson_id, class_id, gmt_create, gmt_modified, start_time, end_time, class_name) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
 
 INSERT INTO cancel_lesson (id, lesson_name, lesson_id, cancel_time, cancel_user_id, cancel_role, cancel_time_long_age, gmt_create, gmt_modified) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) 
 
 INSERT INTO foreign_teacher_booked_record (id, lesson_id, foreign_teacher_id, start_time, end_time, gmt_create, gmt_modified) VALUES (?, ?, ?, ?, ?, ?, ?)
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : 阿里云 centos7.6
- Others:

**Comment by a364176773** [comment]
image
调整这两个参数,使其获取锁周期合理化,减少出现getlockfail的异常

**Comment by jipeigong** [comment]
@a364176773 请问是短时间内没有重试取得全局锁导致的吗，我是否应该加大间隔以及增加重试次数来解决这个问题？

**Comment by a364176773** [comment]
> @a364176773 请问是短时间内没有重试取得全局锁导致的吗，我是否应该加大间隔以及增加重试次数来解决这个问题？

对的

**Comment by jipeigong** [comment]
@a364176773 设置参数30ms重试50次，问题依然存在，从现象来看应该是可能存在bug，具体非常明显的特征性，只有在没有跨服务调用的场景下（应该很少有人这么干）加入全局事务会导致此问题（eureka+db集群场景下，单机场景下也是正常的）

**Comment by jipeigong** [comment]
问题已经找到：
java.sql.BatchUpdateException: Data truncation: Data too long for column 'row_key' at row 1
原因是db模式的row_key长度为128，key长度超过了128，扩展了字段长度就正常了

**Comment by mirrorHe** [comment]
你这row_key是什么鬼?

**Comment by Rover-Geek** [comment]
I also met the issue before，then I checked the tables lock_table、global_table、branch_table in db seata，found the PK already exists，deleted it，then it works

**Comment by MarlboroBoy** [comment]
> I also met the issue before，then I checked the tables lock_table、global_table、branch_table in db seata，found the PK already exists，deleted it，then it works

then sama problem and  ok;
