### ISSUE TITLE
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 539959368 - discarded

### ISSUE THREAD

**Issue by HanKaiqiang** [seata/seata#2570]
ERROR[NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:505 -0318
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 539959368 - discarded
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430)
	at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:82)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by slievrly** [comment]
@HanKaiqiang seata-all and seata-server version.

**Comment by HanKaiqiang** [comment]
> @HanKaiqiang seata-all和seata-server版本。

        <revision>1.2.0-SNAPSHOT</revision>

**Comment by a364176773** [comment]
确保你的server端口不会被健康检查或者扫描到,server的8091端口不支持直接访问.直接访问就会出现上面的异常

**Comment by yang-xinfu** [comment]
> 确保你的server端口不会被健康检查或者扫描到,server的8091端口不支持直接访问.直接访问就会出现上面的异常

@a364176773 请问这个不支持直接访问8091端口，是应该要怎么配置去访问吗？ 我现在是用docker起的seata，注册到nacos，然后在起应用程序的时候，seata里报了这个异常。

**Comment by slievrly** [comment]
@HanKaiqiang @yang-xinfu Can this be reproduced in version 1.2.0?

**Comment by yang-xinfu** [comment]
@slievrly 
I have solved this problem。 Maybe this document  need to be updated。Because when I use custom configuration file by docker，this document show:
![image](https://user-images.githubusercontent.com/52365692/80174187-7c440a80-8624-11ea-9ca1-1908f12fc633.png)
url：https://seata.io/en-us/docs/ops/deploy-by-docker.html
 But，should use add `-e SEATA_IP=xxx.xxx.xxx.xxx`. Otherwise ,  will report an error like the issue'title.

**Comment by helloworlde** [comment]
> @slievrly
> I have solved this problem。 Maybe this document need to be updated。Because when I use custom configuration file by docker，this document show:
> ![image](https://user-images.githubusercontent.com/52365692/80174187-7c440a80-8624-11ea-9ca1-1908f12fc633.png)
> url：https://seata.io/en-us/docs/ops/deploy-by-docker.html
> But，should use add `-e SEATA_IP=xxx.xxx.xxx.xxx`. Otherwise , will report an error like the issue'title.

It's not correct, the enviroment `SEATA_IP` specify the IP address for access from out of container, but this issue should be caused by health check from registry center or others which access server port directly by HTTP

**Comment by SiriusZhang** [comment]
> > 确保你的server端口不会被健康检查或者扫描到,server的8091端口不支持直接访问.直接访问就会出现上面的异常
> 
> 我也遇到楼主一样的错误，被健康检查和扫描到是什么意思？
