### ISSUE TITLE
docker 命令启动 seata-server失败 

### ISSUE THREAD

**Issue by a46461440** [seata/seata#2581]
### Ⅰ. Issue Description
报错 
Exception in thread "main" io.seata.common.exception.NotSupportYetException: not support register type: null
        at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:106)
        at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:90)
        at io.seata.server.ParameterParser.init(ParameterParser.java:111)
        at io.seata.server.ParameterParser.<init>(ParameterParser.java:81)
        at io.seata.server.Server.main(Server.java:63)
Caused by: java.lang.IllegalArgumentException: illegal type:null
        at io.seata.config.ConfigType.getType(ConfigType.java:69)
        at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:104)
        ... 4 more

### Ⅱ. Describe what happened
命令行 
docker run --name seata-server \
        -p 8091:8091 \
        -e SEATA_CONFIG_NAME=file:/root/seata-config/registry \
        -e SERVER_NODE=1 \
        -v /data/docker_data/apps/config/seata:/root/seata-config  \
        seataio/seata-server

registry.conf:
registry {
  type = "eureka"
  eureka {
    serviceUrl = "http://192.168.103.240:8761/eureka"
    application = "seata"
    weight = "1"
  }
}
config {
  type = "file"
  file {
    name = "file.conf"
  }
}

file.conf:
service {
  #transaction service group mapping
  vgroupMapping.tx_group = "seata"
  #degrade, current not support
  enableDegrade = false
  #disable seata
  disableGlobalTransaction = false
}
store {
  ## store mode: file、db
  mode = "db"
  ## database store property
  db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "druid"
    ## mysql/oracle/h2/oceanbase etc.
    dbType = "mysql"
    driverClassName = "com.mysql.jdbc.Driver"
    url = "jdbc:mysql:///seata"
    user = "root"
    password = ""
    minConn = 1
    maxConn = 10
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    queryLimit = 100
  }
}
### Ⅵ. Environment:

- JDK version : 1.8
- OS : centos 7
- Others:

**Comment by a46461440** [comment]
在mac是上没问题的

**Comment by a46461440** [comment]
容器内权限有问题 现在解决了
