### ISSUE TITLE
在使用delete语句时，如果表名后跟了别名会报找不到表名

### ISSUE THREAD

**Issue by nikorliu** [seata/seata#2626]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在使用delete语句时，如果表名后跟了别名会报找不到表名
如：delete a from  test_tbl a where a.'id' = ?

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
2020-04-28 01:51:35.438 ERROR 2632 --- [nio-8082-exec-1] i.s.r.d.s.s.c.AbstractTableMetaCache     : get cache error:Table 'db_order.a' doesn't exist

java.sql.SQLSyntaxErrorException: Table 'db_order.a' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1247) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:291) ~[druid-1.1.10.jar:1.1.10]
	at io.seata.rm.datasource.sql.struct.cache.MysqlTableMetaCache.fetchSchema(MysqlTableMetaCache.java:84) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.sql.struct.cache.AbstractTableMetaCache.lambda$getTableMeta$0(AbstractTableMetaCache.java:61) ~[seata-all-1.2.0.jar:1.2.0]

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:
seata：1.2.0
- JDK version :
- OS :
- Others:

**Comment by Garlichead** [comment]
估计没有做别名处理 别用别名了～

**Comment by l81893521** [comment]
Thanks for your report

**Comment by l81893521** [comment]
Would you mind give some information to us like below:
seata version:
database and version:
sql:

**Comment by l81893521** [comment]
Because I found the error and the sql 'delete a from test_tbl a where a.'id' = ?' that you gave was different.

**Comment by nikorliu** [comment]
> Would you mind give some information to us like below:
> seata version: 1.2.0
> database and version: mysql 5.6.25 
> sql:delete a from test_tbl a where a.'id' = ?
