### ISSUE TITLE
saga 模式 出现 NPE

### ISSUE THREAD

**Issue by 1225304143** [seata/seata#2635]
[ERROR][2020-04-09T02:15:17.303+0800][SagaResourceManager.java:155] _undef||traceid=||spanid=||_msg=StateMachine compensate failed, xid: 10.179.250.54:8091:2039041029
java.lang.NullPointerException: null
    at io.seata.saga.rm.SagaResourceManager.branchRollback(SagaResourceManager.java:131)
    at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:124)
    at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:68)
    at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:64)
    at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:117)
    at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:64)
    at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:63)
    at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35)
    at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:149)
    at io.seata.core.rpc.netty.RmMessageListener.handleBranchRollback(RmMessageListener.java:93)
    at io.seata.core.rpc.netty.RmMessageListener.onMessage(RmMessageListener.java:84)
    at io.seata.core.rpc.netty.AbstractRpcRemotingClient$ClientHandler.dispatch(AbstractRpcRemotingClient.java:284)
    at io.seata.core.rpc.netty.AbstractRpcRemoting$AbstractHandler$1.run(AbstractRpcRemoting.java:452)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)

[INFO ][2020-04-09T02:09:55.298+0800][RmMessageListener.java:79] _undef||traceid=||spanid=||_msg=onMessage:xid=10.179.250.54:8091:2039041030,branchId=-1,branchType=SAGA,resourceId=nectar-front#my_test_tx_group,applicationData=TimeoutRollbacking
[INFO ][2020-04-09T02:09:55.305+0800][AbstractRMHandler.java:122] _undef||traceid=||spanid=||_msg=Branch Rollbacking: 10.179.250.54:8091:2039041030 -1 nectar-front#my_test_tx_group
[INFO ][2020-04-09T02:09:55.818+0800][ProcessCtrlStateMachineEngine.java:497] _undef||traceid=||spanid=||_msg=Operation [compensate] start.  stateMachineInstance[id:10.179.250.54:8091:2039041030]
[WARN ][2020-04-09T02:09:56.036+0800][DbAndReportTcStateLogStore.java:162] _undef||traceid=||spanid=||_msg=StateMachineInstance[10.179.250.54:8091:2039041030] is recovery by server, skip recordStateMachineFinished.
[INFO ][2020-04-09T02:09:56.126+0800][EnhancedServiceLoader.java:247] _undef||traceid=||spanid=||_msg=load ContextCore[null] extension by class[io.seata.core.context.FastThreadLocalContextCore]
[INFO ][2020-04-09T02:09:56.128+0800][TaskStateRouter.java:56] _undef||traceid=||spanid=||_msg=StateInstruction is ended, Stop the StateMachine executing. StateMachine[nectar] Current State[null]
[WARN ][2020-04-09T02:09:56.128+0800][DefaultRouterHandler.java:71] _undef||traceid=||spanid=||_msg=route instruction is null, process end
[INFO ][2020-04-09T02:09:56.129+0800][AbstractRMHandler.java:130] _undef||traceid=||spanid=||_msg=Branch Rollbacked result: PhaseTwo_RollbackFailed_Retryable

**Comment by long187** [comment]
升级到1.2.0试试，注意检测一下1.2.0版本的建表语句与你现在的是否一致
