### ISSUE TITLE
XA模式下错误

### ISSUE THREAD

**Issue by nikorliu** [seata/seata#2663]
在XA模式下，当第一次失败回滚后，如果继续请求则会报如下错误：
使用的是sample样例中的seata-xa样例进行测试
mysql:8.0.17
mysql-connector-java:8.0.11
seata:1.2.0

2020-05-07 18:23:43.417  INFO 9372 --- [tch_RMROLE_1_16] i.s.rm.datasource.xa.ResourceManagerXA   : 10.10.19.110:8091:2010953828-2010953834 rollback failed since XAER_NOTA: Unknown XID

com.mysql.cj.jdbc.MysqlXAException: XAER_NOTA: Unknown XID
	at com.mysql.cj.jdbc.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:333) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:318) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.MysqlXAConnection.rollback(MysqlXAConnection.java:235) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at io.seata.rm.datasource.xa.ConnectionProxyXA.xaRollback(ConnectionProxyXA.java:108) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.xa.ResourceManagerXA.finishBranch(ResourceManagerXA.java:72) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.xa.ResourceManagerXA.branchRollback(ResourceManagerXA.java:58) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:126) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:68) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:64) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:64) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:63) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:151) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.core.rpc.netty.RmMessageListener.handleBranchRollback(RmMessageListener.java:93) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.core.rpc.netty.RmMessageListener.onMessage(RmMessageListener.java:84) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient$ClientHandler.dispatch(AbstractRpcRemotingClient.java:284) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.core.rpc.netty.AbstractRpcRemoting$AbstractHandler$1.run(AbstractRpcRemoting.java:452) [seata-all-1.2.0.jar:1.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]
Caused by: java.sql.SQLException: XAER_NOTA: Unknown XID
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:790) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:675) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:312) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	... 20 common frames omitted

**Comment by zjinlei** [comment]
是不是重启了客户端

**Comment by nikorliu** [comment]
> 是不是重启了客户端？

**Comment by nikorliu** [comment]
> 是不是重启了客户端？
没重启之前就报这个错。第一次失败没问题，第二次失败后悔报这个错误。

2020-05-08 11:12:35.049  INFO 5616 --- [tch_RMROLE_1_16] i.s.rm.datasource.xa.ResourceManagerXA   : 10.10.19.110:8091:2010958318-2010958324 rollback failed since XAER_RMFAIL: The command cannot be executed when global transaction is in the  IDLE state

com.mysql.cj.jdbc.MysqlXAException: XAER_RMFAIL: The command cannot be executed when global transaction is in the  IDLE state
	at com.mysql.cj.jdbc.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:333) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:318) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.MysqlXAConnection.rollback(MysqlXAConnection.java:235) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at io.seata.rm.datasource.xa.ConnectionProxyXA.xaRollback(ConnectionProxyXA.java:108) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.xa.ResourceManagerXA.finishBranch(ResourceManagerXA.java:72) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.xa.ResourceManagerXA.branchRollback(ResourceManagerXA.java:58) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:126) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:68) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:64) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:64) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:63) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:151) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.core.rpc.netty.RmMessageListener.handleBranchRollback(RmMessageListener.java:93) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.core.rpc.netty.RmMessageListener.onMessage(RmMessageListener.java:84) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient$ClientHandler.dispatch(AbstractRpcRemotingClient.java:284) [seata-all-1.2.0.jar:1.2.0]
	at io.seata.core.rpc.netty.AbstractRpcRemoting$AbstractHandler$1.run(AbstractRpcRemoting.java:452) [seata-all-1.2.0.jar:1.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]
Caused by: java.sql.SQLException: XAER_RMFAIL: The command cannot be executed when global transaction is in the  IDLE state
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:790) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:675) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	at com.mysql.cj.jdbc.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:312) ~[mysql-connector-java-8.0.11.jar:8.0.11]
	... 20 common frames omitted

**Comment by zjinlei** [comment]
The command cannot be executed when global transaction is in the IDLE state
是不是叠加了spring事务注解，网上搜下资料

**Comment by nikorliu** [comment]
> The command cannot be executed when global transaction is in the IDLE state
> 是不是叠加了spring事务注解，网上搜下资料

整个样例就是seata-samples里的seata-xa。没有添加spring的事务，并且是第一次失败可以回滚的。

**Comment by nikorliu** [comment]
> The command cannot be executed when global transaction is in the IDLE state
> 是不是叠加了spring事务注解，网上搜下资料

发现确实是叠加了spring的事务，谢谢。

风险很大，如果应用到生产环境的话，叠加了spring事务的话会导致数据库锁死的问题。

**Comment by markWord** [comment]
我这里是重启业务服务，就报这个错了Caused by: java.sql.SQLException: XAER_NOTA: Unknown XID，想模拟线上宕机场景的问题，这个要怎么解决？ @zjinlei

**Comment by zjinlei** [comment]
@nikorliu @markWord 请加下seata企业支持钉钉群 23374389，与xa负责人沟通下xa的问题

**Comment by yiyunstart** [comment]
@markWord 最后是怎么解决的这问题Caused by: java.sql.SQLException: XAER_NOTA: Unknown XID

**Comment by tanyaofei** [comment]
一阶段执行完毕，即执行 sql 之后连接会处于 `IDLE` 状态，如果这个连接还到了连接池被别的业务拿去用，就会报这个错。解决办法是开启了 GlobalTransaction 之后，再开启一个 spring 本地 Transaction，这样可以保证连接在本地事务完成之前都不要归还到连接池


![企业微信截图_17137539649327](https://github.com/apache/incubator-seata/assets/46375450/6ce98422-9ef5-41bf-866a-a412ce1d0cb6)
