### ISSUE TITLE
kubernetes中配置mysql数据库报数据源错误java.lang.IllegalArgumentException: the name of service provider for [io.seata.core.store.db.DataSourceGenerator] name is null

### ISSUE THREAD

**Issue by bruce-qin** [seata/seata#2707]
### Ⅰ. the name of service provider for [io.seata.core.store.db.DataSourceGenerator] name is null
 > seata-server:1.2.0配置mysql数据源时报数据源找不到

### Ⅱ. 使用kubernetes configmap配置了file.conf，启动时报数据源生成器找不到，其实是有配置的

```
2020-05-21 02:08:26.648 INFO [main]io.seata.server.ParameterParser.init:90 -The server is running in container.
2020-05-21 02:08:26.728 INFO [main]io.seata.config.FileConfiguration.<init>:121 -The configuration file used is registry-k8s.conf
Exception in thread "main" io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.server.session.SessionManager caused by java.lang.IllegalStateException: Extension instance(definition: io.seata.common.loader.ExtensionDefinition@2b00cfdc, class: interface io.seata.server.session.SessionManager)  could not be instantiated: the name of service provider for [io.seata.core.store.db.DataSourceGenerator] name is null
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:404)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:393)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:358)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:247)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:188)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:80)
	at io.seata.server.session.SessionHolder.init(SessionHolder.java:87)
	at io.seata.server.Server.main(Server.java:75)
Caused by: java.lang.IllegalArgumentException: the name of service provider for [io.seata.core.store.db.DataSourceGenerator] name is null
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:353)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:247)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:188)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:80)
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.<init>(DataBaseTransactionStoreManager.java:98)
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.getInstance(DataBaseTransactionStoreManager.java:84)
	at io.seata.server.storage.db.session.DataBaseSessionManager.init(DataBaseSessionManager.java:81)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:560)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:400)
	... 7 more
```

### Ⅲ. kubernetes 配置文件

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-cluster-conf
data:
  file.conf: |
    store {
      ## store mode: file、db
      mode = "db"
      ## database store property
      db {
        ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
        datasource = "druid"
        ## mysql/oracle/postgresql/h2/oceanbase etc.
        dbType = "mysql"
        driverClassName = "com.mysql.cj.jdbc.Driver"
        url = "jdbc:mysql://mysql-cluster-master-svc:3306/seata"
        user = "mysql"
        password = "mysql"
        minConn = 5
        maxConn = 30
        globalTable = "global_table"
        branchTable = "branch_table"
        lockTable = "lock_table"
        queryLimit = 100
      }
    }
    server {
      recovery {
        #schedule committing retry period in milliseconds
        committingRetryPeriod = 1000
        #schedule asyn committing retry period in milliseconds
        asynCommittingRetryPeriod = 1000
        #schedule rollbacking retry period in milliseconds
        rollbackingRetryPeriod = 1000
        #schedule timeout retry period in milliseconds
        timeoutRetryPeriod = 1000
      }
      undo {
        logSaveDays = 7
        #schedule delete expired undo_log in milliseconds
        logDeletePeriod = 86400000
      }
      #unit ms,s,m,h,d represents milliseconds, seconds, minutes, hours, days, default permanent
      maxCommitRetryTimeout = "-1"
      maxRollbackRetryTimeout = "-1"
      rollbackRetryTimeoutUnlockEnable = false
    }
    metrics {
      enabled = true
      registryType = "compact"
      # multi exporters use comma divided
      exporterList = "prometheus"
      exporterPrometheusPort = 9898
    }
  registry-k8s.conf: |
    registry {
      # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
      type = "nacos"
      nacos {
        application = "seata-server"
        serverAddr = "nacos-svc"
        namespace = "seata"
        cluster = "default"
        username = "seata"
        password = "seata"
      }
    }
    config {
      # file、nacos 、apollo、zk、consul、etcd3
      type = "nacos"
      nacos {
        serverAddr = "nacos-svc"
        namespace = "seata"
        group = "SEATA_GROUP"
        username = "seata"
        password = "seata"
      }
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seata-cluster0
  labels:
    app: seata-cluster0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seata-cluster0
  serviceName: seata-cluster-svc
  template:
    spec:
      volumes:
        - name: seata-cluster-conf
          configMap:
            name: seata-cluster-conf
            items:
              - key: file.conf
                path: file.conf
              - key: registry-k8s.conf
                path: registry-k8s.conf
      containers:
        - name: seata-cluster
          image: seataio/seata-server:1.2.0
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_NODE
              value: "0"
            - name: STORE_MODE
              value: db
            - name: SEATA_ENV
              value: k8s
          volumeMounts:
            - mountPath: /seata-server/resources/file.conf
              name: seata-cluster-conf
              subPath: file.conf
            - mountPath: /seata-server/resources/registry-k8s.conf
              name: seata-cluster-conf
              subPath: registry-k8s.conf
    metadata:
      labels:
        app: seata-cluster0
        kubernetes.io/cluster-service: seata-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seata-cluster1
  labels:
    app: seata-cluster1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seata-cluster1
  serviceName: seata-cluster-svc
  template:
    spec:
      volumes:
        - name: seata-cluster-conf
          configMap:
            name: seata-cluster-conf
            items:
              - key: file.conf
                path: file.conf
              - key: registry-k8s.conf
                path: registry-k8s.conf
      containers:
        - name: seata-cluster
          image: seataio/seata-server:1.2.0
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_NODE
              value: "1"
            - name: STORE_MODE
              value: db
            - name: SEATA_ENV
              value: k8s
          volumeMounts:
            - mountPath: /seata-server/resources/file.conf
              name: seata-cluster-conf
              subPath: file.conf
            - mountPath: /seata-server/resources/registry-k8s.conf
              name: seata-cluster-conf
              subPath: registry-k8s.conf
    metadata:
      labels:
        app: seata-cluster1
        kubernetes.io/cluster-service: seata-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seata-cluster2
  labels:
    app: seata-cluster2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seata-cluster2
  serviceName: seata-cluster-svc
  template:
    spec:
      volumes:
        - name: seata-cluster-conf
          configMap:
            name: seata-cluster-conf
            items:
              - key: file.conf
                path: file.conf
              - key: registry-k8s.conf
                path: registry-k8s.conf
      containers:
        - name: seata-cluster
          image: seataio/seata-server:1.2.0
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_NODE
              value: "2"
            - name: STORE_MODE
              value: db
            - name: SEATA_ENV
              value: k8s
          volumeMounts:
            - mountPath: /seata-server/resources/file.conf
              name: seata-cluster-conf
              subPath: file.conf
            - mountPath: /seata-server/resources/registry-k8s.conf
              name: seata-cluster-conf
              subPath: registry-k8s.conf
    metadata:
      labels:
        app: seata-cluster2
        kubernetes.io/cluster-service: seata-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: seata-cluster-svc
spec:
  selector:
    kubernetes.io/cluster-service: seata-cluster
  ports:
    - port: 8091
      name: seata
      protocol: TCP
  type: ClusterIP

```

### IV. Environment:

- kubernetes : 1.18.2
- OS : centos7
- dockerimage: seataio/seata-server:1.2.0

**Comment by bruce-qin** [comment]
修改了registry的配置
```
    config {
      type = "file"
      file {
        name = "file.conf"
      }
    }
```
现在可以用了
