### ISSUE TITLE
阿里云Kubernetes服务后，一直报java.io.IOException: Connection reset by peer错误，但是功能是能正常调试通的

### ISSUE THREAD

**Issue by WanghuaNero** [seata/seata#2709]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
阿里云Kubernetes服务后，一直报java.io.IOException: Connection reset by peer错误，但是功能是能正常调试通的，这个错误是秒级刷新,日志如下：

### Ⅱ. Describe what happened

2020-05-21 07:11:55.360 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0x3fee7480, L:/172.20.0.189:8091 - R:/192.168.0.20:33332],address:192.168.0.20:33332
2020-05-21 07:11:55.360 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x3fee7480, L:/172.20.0.189:8091 - R:/192.168.0.20:33332]) will closed
2020-05-21 07:11:55.360 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x3fee7480, L:/172.20.0.189:8091 ! R:/192.168.0.20:33332]) will closed
2020-05-21 07:11:55.360 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:254 -192.168.0.20:33332 to server channel inactive.
2020-05-21 07:11:55.360 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0x3fee7480, L:/172.20.0.189:8091 ! R:/192.168.0.20:33332]
2020-05-21 07:11:55.442 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Connection reset by peer,channel:[id: 0xe855d99a, L:/172.20.0.189:8091 - R:/192.168.0.30:21582]
2020-05-21 07:11:55.443 ERROR[NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:584 -0318
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-05-21 07:11:55.443 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0xe855d99a, L:/172.20.0.189:8091 - R:/192.168.0.30:21582],address:192.168.0.30:21582
2020-05-21 07:11:55.443 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0xe855d99a, L:/172.20.0.189:8091 - R:/192.168.0.30:21582]) will closed
2020-05-21 07:11:55.443 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0xe855d99a, L:/172.20.0.189:8091 ! R:/192.168.0.30:21582]) will closed
2020-05-21 07:11:55.443 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:254 -192.168.0.30:21582 to server channel inactive.
2020-05-21 07:11:55.443 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0xe855d99a, L:/172.20.0.189:8091 ! R:/192.168.0.30:21582]
2020-05-21 07:11:55.738 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Connection reset by peer,channel:[id: 0x6d06b51e, L:/172.20.0.189:8091 - R:/192.168.0.18:60401]
2020-05-21 07:11:55.738 ERROR[NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:584 -0318
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-05-21 07:11:55.738 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0x6d06b51e, L:/172.20.0.189:8091 - R:/192.168.0.18:60401],address:192.168.0.18:60401
2020-05-21 07:11:55.739 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x6d06b51e, L:/172.20.0.189:8091 - R:/192.168.0.18:60401]) will closed
2020-05-21 07:11:55.739 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x6d06b51e, L:/172.20.0.189:8091 ! R:/192.168.0.18:60401]) will closed
2020-05-21 07:11:55.739 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:254 -192.168.0.18:60401 to server channel inactive.
2020-05-21 07:11:55.739 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0x6d06b51e, L:/172.20.0.189:8091 ! R:/192.168.0.18:60401]
2020-05-21 07:11:55.967 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Connection reset by peer,channel:[id: 0x4f6d1aa4, L:/172.20.0.189:8091 - R:/192.168.0.18:31107]
2020-05-21 07:11:55.968 ERROR[NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:584 -0318
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-05-21 07:11:55.968 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0x4f6d1aa4, L:/172.20.0.189:8091 - R:/192.168.0.18:31107],address:192.168.0.18:31107
2020-05-21 07:11:55.968 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x4f6d1aa4, L:/172.20.0.189:8091 - R:/192.168.0.18:31107]) will closed
2020-05-21 07:11:55.968 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x4f6d1aa4, L:/172.20.0.189:8091 ! R:/192.168.0.18:31107]) will closed
2020-05-21 07:11:55.968 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:254 -192.168.0.18:31107 to server channel inactive.
2020-05-21 07:11:55.968 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0x4f6d1aa4, L:/172.20.0.189:8091 ! R:/192.168.0.18:31107]
2020-05-21 07:11:56.002 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Connection reset by peer,channel:[id: 0x3badfe88, L:/172.20.0.189:8091 - R:/172.20.0.129:25740]
2020-05-21 07:11:56.003 ERROR[NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:584 -0318
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-05-21 07:11:56.003 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0x3badfe88, L:/172.20.0.189:8091 - R:/172.20.0.129:25740],address:172.20.0.129:25740
2020-05-21 07:11:56.003 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x3badfe88, L:/172.20.0.189:8091 - R:/172.20.0.129:25740]) will closed
2020-05-21 07:11:56.003 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x3badfe88, L:/172.20.0.189:8091 ! R:/172.20.0.129:25740]) will closed
2020-05-21 07:11:56.003 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:254 -172.20.0.129:25740 to server channel inactive.
2020-05-21 07:11:56.003 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0x3badfe88, L:/172.20.0.189:8091 ! R:/172.20.0.129:25740]
2020-05-21 07:11:56.011 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Connection reset by peer,channel:[id: 0x619c893b, L:/172.20.0.189:8091 - R:/192.168.0.30:37785]
2020-05-21 07:11:56.011 ERROR[NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:584 -0318
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-05-21 07:11:56.011 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0x619c893b, L:/172.20.0.189:8091 - R:/192.168.0.30:37785],address:192.168.0.30:37785
2020-05-21 07:11:56.012 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x619c893b, L:/172.20.0.189:8091 - R:/192.168.0.30:37785]) will closed
2020-05-21 07:11:56.012 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x619c893b, L:/172.20.0.189:8091 ! R:/192.168.0.30:37785]) will closed
2020-05-21 07:11:56.012 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:254 -192.168.0.30:37785 to server channel inactive.
2020-05-21 07:11:56.012 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0x619c893b, L:/172.20.0.189:8091 ! R:/192.168.0.30:37785]
2020-05-21 07:11:56.263 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Connection reset by peer,channel:[id: 0x4db06925, L:/172.20.0.189:8091 - R:/172.20.0.129:22221]
2020-05-21 07:11:56.263 ERROR[NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:584 -0318
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-05-21 07:11:56.263 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0x4db06925, L:/172.20.0.189:8091 - R:/172.20.0.129:22221],address:172.20.0.129:22221
2020-05-21 07:11:56.263 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x4db06925, L:/172.20.0.189:8091 - R:/172.20.0.129:22221]) will closed
2020-05-21 07:11:56.264 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x4db06925, L:/172.20.0.189:8091 ! R:/172.20.0.129:22221]) will closed
2020-05-21 07:11:56.264 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:254 -172.20.0.129:22221 to server channel inactive.
2020-05-21 07:11:56.264 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0x4db06925, L:/172.20.0.189:8091 ! R:/172.20.0.129:22221]
2020-05-21 07:11:57.338 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Connection reset by peer,channel:[id: 0x1a443e13, L:/172.20.0.189:8091 - R:/192.168.0.20:36310]
2020-05-21 07:11:57.338 ERROR[NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:584 -0318
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-05-21 07:11:57.340 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0x1a443e13, L:/172.20.0.189:8091 - R:/192.168.0.20:36310],address:192.168.0.20:36310
2020-05-21 07:11:57.341 INFO [NettyServerNIOWorker_1_2]io.seata.core.rpc.netty.AbstractRpcRemoting.close:597 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x1a443e13, L:/172.20.0.189:8091 - R:/192.168.0.20:36310]) will closed

### Ⅴ. Anything else we need to know?
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-ha-server
  namespace: default
  labels:
    app.kubernetes.io/name: seata-ha-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seata-ha-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seata-ha-server
    spec:
      containers:
        - name: seata-ha-server
          image: docker.io/seataio/seata-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SEATA_CONFIG_NAME
              value: file:/root/seata-config/registry
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          volumeMounts:
            - name: seata-config
              mountPath: /root/seata-config
      volumes:
        - name: seata-config
          configMap:
            name: seata-ha-server-config
            
---
apiVersion: v1
kind: Service
metadata:
  name: seata-ha-server
  namespace: default
  labels:
    app.kubernetes.io/name: seata-ha-server
spec:
  selector:
    app.kubernetes.io/name: seata-ha-server
  type: LoadBalancer
  ports:
    - port: 8091
      protocol: TCP
      name: http

<img width="591" alt="image" src="https://user-images.githubusercontent.com/42229487/82535336-51909780-9b79-11ea-832f-433e24fc00c9.png">

### Ⅵ. Environment:

- JDK version :1.8
- OS :Linux AliCloud Kubernetes 
- Others: 采用Seata官网提供的Kubernetes方式部署

**Comment by Garlichead** [comment]
可能是k8s网络这块的问题
