### ISSUE TITLE
seata控制台总是报io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 1411395442 - discarded

### ISSUE THREAD

**Issue by zhujunsheng** [seata/seata#2729]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata1.2+nacos1.7+ springcloud alibaba-2.2.1.RELEASE搭建微服务，全局事务能正常提交和回滚，
但是发现seata控制台不断输出：io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 1411395442 - discarded
完整的异常栈信息如下：
2020-05-25 15:13:06.169 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Adjusted frame length exceeds 8388608: 1411395442 - discarded,channel:[id: 0x94847b0d, L:/127.0.0.1:8849 - R:/127.0.0.1:8051]
2020-05-25 15:13:06.170 ERROR[NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:505 -0318
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 1411395442 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430)
        at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:82)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8-64位
- OS :window10
- Others:

**Comment by zhujunsheng** [comment]
再强调一点，是用的AT模式

**Comment by l81893521** [comment]
what kind of the application in 127.0.0.1:8051?

**Comment by zhujunsheng** [comment]
> what kind of the application in 127.0.0.1:8051?

according the abservation i found the port was used by  the rm transaction which registed to the seate TC besides this port in the exception message would change automatically.

**Comment by zhujunsheng** [comment]
> what kind of the application in 127.0.0.1:8051?

like this over and over again in the console as below:
2020-05-26 09:53:13.730 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0xa0bcc914, L:/127.0.0.1:8849 ! R:/127.0.0.1:5063]
2020-05-26 09:53:23.718 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Adjusted frame length exceeds 8388608: 1411395442 - discarded,channel:[id: 0x42b5282c, L:/127.0.0.1:8849 - R:/127.0.0.1:5067]
2020-05-26 09:53:23.722 ERROR[NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:505 -0318
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 1411395442 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430)
        at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:82)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
2020-05-26 09:53:23.733 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0x42b5282c, L:/127.0.0.1:8849 - R:/127.0.0.1:5067],address:127.0.0.1:5067
2020-05-26 09:53:23.736 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.close:518 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x42b5282c, L:/127.0.0.1:8849 - R:/127.0.0.1:5067]) will closed
2020-05-26 09:53:23.757 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.close:518 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x42b5282c, L:/127.0.0.1:8849 ! R:/127.0.0.1:5067]) will closed
2020-05-26 09:53:23.759 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:254 -127.0.0.1:5067 to server channel inactive.
2020-05-26 09:53:23.765 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0x42b5282c, L:/127.0.0.1:8849 ! R:/127.0.0.1:5067]
2020-05-26 09:53:33.712 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Adjusted frame length exceeds 8388608: 1411395442 - discarded,channel:[id: 0xfe665fc0, L:/127.0.0.1:8849 - R:/127.0.0.1:5072]
2020-05-26 09:53:33.712 ERROR[NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:505 -0318
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 1411395442 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430)
        at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:82)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
2020-05-26 09:53:33.715 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0xfe665fc0, L:/127.0.0.1:8849 - R:/127.0.0.1:5072],address:127.0.0.1:5072
2020-05-26 09:53:33.716 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.close:518 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0xfe665fc0, L:/127.0.0.1:8849 - R:/127.0.0.1:5072]) will closed
2020-05-26 09:53:33.718 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.close:518 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0xfe665fc0, L:/127.0.0.1:8849 ! R:/127.0.0.1:5072]) will closed
2020-05-26 09:53:33.719 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:254 -127.0.0.1:5072 to server channel inactive.
2020-05-26 09:53:33.719 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0xfe665fc0, L:/127.0.0.1:8849 ! R:/127.0.0.1:5072]
2020-05-26 09:53:43.713 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Adjusted frame length exceeds 8388608: 1411395442 - discarded,channel:[id: 0x30c51abc, L:/127.0.0.1:8849 - R:/127.0.0.1:5109]
2020-05-26 09:53:43.714 ERROR[NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:505 -0318
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 1411395442 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430)
        at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:82)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
2020-05-26 09:53:43.715 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0x30c51abc, L:/127.0.0.1:8849 - R:/127.0.0.1:5109],address:127.0.0.1:5109
2020-05-26 09:53:43.719 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.close:518 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x30c51abc, L:/127.0.0.1:8849 - R:/127.0.0.1:5109]) will closed
2020-05-26 09:53:43.720 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemoting.close:518 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x30c51abc, L:/127.0.0.1:8849 ! R:/127.0.0.1:5109]) will closed
2020-05-26 09:53:43.721 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:254 -127.0.0.1:5109 to server channel inactive.
2020-05-26 09:53:43.722 INFO [NettyServerNIOWorker_1_8]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0x30c51abc, L:/127.0.0.1:8849 ! R:/127.0.0.1:5109]

**Comment by l81893521** [comment]
According to your report. Look like some application in 127.0.0.1:5067 send some big message to tc server and tc server could not handler it, because tc server just can handler the max length of frame is 8M.

**Comment by Caratacus** [comment]
2020-06-29 00:21:14.443 INFO [NettyServerNIOWorker_1_4]io.seata.core.rpc.netty.AbstractRpcRemotingServer.handleDisconnect:263 -remove unused channel:[id: 0x5305bf8a, L:/192.168.0.231:8091 ! R:/192.168.0.101:36512]
2020-06-29 00:21:34.446 INFO [NettyServerNIOWorker_1_4]io.seata.core.rpc.netty.AbstractRpcRemotingServer.exceptionCaught:278 -channel exx:Adjusted frame length exceeds 8388608: 539976035 - discarded,channel:[id: 0x2a929c54, L:/192.168.0.231:8091 - R:/192.168.0.101:36536]
2020-06-29 00:21:34.447 ERROR[NettyServerNIOWorker_1_4]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:505 -0318
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 539976035 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430)
        at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:82)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
2020-06-29 00:21:34.447 INFO [NettyServerNIOWorker_1_4]io.seata.core.rpc.netty.AbstractRpcRemotingServer.destroyChannel:171 -will destroy channel:[id: 0x2a929c54, L:/192.168.0.231:8091 - R:/192.168.0.101:36536],address:192.168.0.101:36536
2020-06-29 00:21:34.447 INFO [NettyServerNIOWorker_1_4]io.seata.core.rpc.netty.AbstractRpcRemoting.close:518 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x2a929c54, L:/192.168.0.231:8091 - R:/192.168.0.101:36536]) will closed
2020-06-29 00:21:34.447 INFO [NettyServerNIOWorker_1_4]io.seata.core.rpc.netty.AbstractRpcRemoting.close:518 -ChannelHandlerContext(AbstractRpcRemotingServer$ServerHandler#0, [id: 0x2a929c54, L:/192.168.0.231:8091 ! R:/192.168.0.101:36536]) will closed

**Comment by Caratacus** [comment]
mark
