### ISSUE TITLE
1.2.0并发测试报错（io.seata.rm.datasource.exec.LockConflictException: get global lock fail, xid:xxx, lockKeys:xxx）

### ISSUE THREAD

**Issue by zgz757183190** [seata/seata#2735]
报错1：(10个并发测试的情况下)

io.seata.rm.datasource.exec.LockConflictException: get global lock fail, xid:47.112.208.130:8091:2012755620, lockKeys:t_product:1
	at io.seata.rm.datasource.ConnectionProxy.recognizeLockKeyConflictException(ConnectionProxy.java:155) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:218) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:196) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:184) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:289) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:183) ~[seata-all-1.2.0.jar:1.2.0]
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:330) ~[spring-jdbc-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:744) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:712) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:619) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:372) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at com.sodix.up.service.impl.StorageServiceImpl$$EnhancerBySpringCGLIB$$9d2bf76c.updateById(<generated>) ~[classes/:na]

报错2：(100个并发测试的情况下)

java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: 1d244060-2558-4799-a0d3-61ac029db94f thread-id: 258
	at org.redisson.RedissonLock.lambda$unlockAsync$3(RedissonLock.java:581) ~[redisson-3.12.3.jar:3.12.3]
	at org.redisson.misc.RedissonPromise.lambda$onComplete$0(RedissonPromise.java:187) ~[redisson-3.12.3.jar:3.12.3]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]

io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 47.112.208.130:8091:2012755742, may be has finished.] ]
	at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:69) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:238) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:216) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:196) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:184) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:289) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:183) ~[seata-all-1.2.0.jar:1.2.0]

**Comment by slievrly** [comment]
@zgz757183190 The data needs to be scattered during testing to reduce the relevance of the data.

**Comment by zgz757183190** [comment]
> @zgz757183190 The data needs to be scattered during testing to reduce the relevance of the data.
具体哪些参数呢

**Comment by pansir1314** [comment]
我也遇到了一样的问题~

**Comment by l81893521** [comment]
@zgz757183190 @pansir1314 That means you need to change the different data of different primary key, because seata will lock the data by primary key during the global transaction.

**Comment by a364176773** [comment]
并发操作的数据进行forupdate以保证竞争锁条件生效.同时修改client.rm.lock.retryInterval client.rm.lock.retryTimes 这俩参数配置,达到竞争锁的周期合理性,以减少该异常的发生

**Comment by pansir1314** [comment]
场景是这样的：我需要在全局事务中更新同一张业务表，全局锁就会根据这张表的主键全局锁定，然后提交事务的时候发生了竞争关系，导致获取锁失败，并发数5，执行成功4，失败1
然后，我怎么调整retryInterval 和 retryTimes，还是一样会失败一次~ 我是哪里错了吗~

**Comment by pansir1314** [comment]
lockRetryPolicyBranchRollbackOnConflict 这个参数改为false，才能进入lock的等待，默认参数lockRetryPolicyBranchRollbackOnConflict 为true，设置retryInterval和retryTimes根本就没效果~

改为false后，没有报错了。但对于这个参数不太能理解~

`public static class LockRetryPolicy {
        protected static final boolean LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT = ConfigurationFactory
            .getInstance().getBoolean(ConfigurationKeys.CLIENT_LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT, DEFAULT_CLIENT_LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT);

        public <T> T execute(Callable<T> callable) throws Exception {
            if (LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT) {
                return callable.call();
            } else {
                return doRetryOnLockConflict(callable);
            }
        }`
}

**Comment by a364176773** [comment]
> lockRetryPolicyBranchRollbackOnConflict 这个参数改为false，才能进入lock的等待，默认参数lockRetryPolicyBranchRollbackOnConflict 为true，设置retryInterval和retryTimes根本就没效果~
> 
> 改为false后，没有报错了。但对于这个参数不太能理解~
> 
> ` public <T> T execute(Callable<T> callable) throws Exception { if (LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT) { return callable.call(); } else { return doRetryOnLockConflict(callable); } } }`

lockRetryPolicyBranchRollbackOnConflict 改为false也可以,但是有可能会出现死锁,forupdate情况下更加安全.所以我们默认是forupdate进行竞争锁行为

**Comment by Garlichead** [comment]
> lockRetryPolicyBranchRollbackOnConflict 改为false也可以,但是有可能会出现死锁,forupdate情况下更加安全.所以我们默认是forupdate进行竞争锁行为

forupdate怎么设置retryInterval和retryTimes 会有效 目前单独设置retryInterval和retryTimes没有起到作用

**Comment by jackbauer123** [comment]
我也遇到了这个问题，对于这种获取锁超时导致的事务不一致的情况是怎么处理的？

**Comment by DevilRebirth** [comment]
我也遇到了这个问题，请问具体解决方式是什么？

**Comment by garlichead** [comment]
> 我也遇到了这个问题，请问具体解决方式是什么？

1 升级1.3
2 尝试改模式 at模式性能没有tcc好

**Comment by Monkey-kong** [comment]
> > lockRetryPolicyBranchRollbackOnConflict 这个参数改为false，才能进入lock的等待，默认参数lockRetryPolicyBranchRollbackOnConflict 为true，设置retryInterval和retryTimes根本就没效果~
> > 改为false后，没有报错了。但对于这个参数不太能理解~
> > ` public <T> T execute(Callable<T> callable) throws Exception { if (LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT) { return callable.call(); } else { return doRetryOnLockConflict(callable); } } }`
> 
> lockRetryPolicyBranchRollbackOnConflict 改为false也可以,但是有可能会出现死锁,forupdate情况下更加安全.所以我们默认是forupdate进行竞争锁行为

只有一个更新语句怎么加for update，1.4版本中好像update并发操作还是有这个问题

**Comment by Monkey-kong** [comment]
> > > lockRetryPolicyBranchRollbackOnConflict 这个参数改为false，才能进入lock的等待，默认参数lockRetryPolicyBranchRollbackOnConflict 为true，设置retryInterval和retryTimes根本就没效果~
> > > 改为false后，没有报错了。但对于这个参数不太能理解~
> > > ` public <T> T execute(Callable<T> callable) throws Exception { if (LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT) { return callable.call(); } else { return doRetryOnLockConflict(callable); } } }`
> > 
> > 
> > lockRetryPolicyBranchRollbackOnConflict 改为false也可以,但是有可能会出现死锁,forupdate情况下更加安全.所以我们默认是forupdate进行竞争锁行为
> 
> 只有一个更新语句怎么加for update，1.4版本中好像update并发操作还是有这个问题

@Transactional+@GlobalTransactional就正常等待锁了。开始以为有@GlobalTransactional就不需要@Transactional来控制本地事务了
