### ISSUE TITLE
注册中心为zk，使用安装包无法启动，使用docker可以启动

### ISSUE THREAD

**Issue by suntchi** [seata/seata#2747]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
注册中心为zk，使用安装包无法启动，使用docker可以启动

### Ⅱ. Describe what happened
1. 下载版本为：seata-server-1.2.0.tar.gz，
2. 注册中心为zk
3. 使用安装包启动seata-server无法启动seata-server
4. 使用docker下载last版本，连接同样的配置中心可以启动
5. zk安装在docker里
6. registry.conf的配置如下
```
type = "zk"

  nacos {
    application = "seata-server"
    serverAddr = "localhost"
    namespace = ""
    cluster = "default"
    username = ""
    password = ""
  }
  eureka {
    serviceUrl = "http://localhost:8761/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = 0
    password = ""
    cluster = "default"
    timeout = 0
  }
  zk {
    cluster = "default"
    serverAddr = "172.17.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
  }
  etcd3 {
    cluster = "default"
    serverAddr = "http://localhost:2379"
  }
  sofa {
    serverAddr = "127.0.0.1:9603"
    application = "default"
    region = "DEFAULT_ZONE"
    datacenter = "DefaultDataCenter"
    cluster = "default"
    group = "SEATA_GROUP"
    addressWaitTime = "3000"
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "zk"

  nacos {
    serverAddr = "localhost"
    namespace = ""
    group = "SEATA_GROUP"
    username = ""
    password = ""
  }
  consul {
    serverAddr = "127.0.0.1:8500"
  }
  apollo {
    appId = "seata-server"
    apolloMeta = "http://192.168.1.204:8801"
    namespace = "application"
  }
  zk {
    serverAddr = "172.17.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  etcd3 {
    serverAddr = "http://localhost:2379"
  }
  file {
    name = "file.conf"
  }
}
```
7. 报错如下
```
2020-05-29 07:41:13.192 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig metrics.enabled error or timeout, return defaultValue false, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.StreamCorruptedException: invalid stream header: 66616C73 
2020-05-29 07:41:13.196 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig transport.threadFactory.bossThreadPrefix error or timeout, return defaultValue null, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.StreamCorruptedException: invalid stream header: 4E657474 
2020-05-29 07:41:13.197 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig transport.threadFactory.workerThreadPrefix error or timeout, return defaultValue null, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.StreamCorruptedException: invalid stream header: 4E657474 
2020-05-29 07:41:13.198 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig transport.threadFactory.shareBossWorker error or timeout, return defaultValue false, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.StreamCorruptedException: invalid stream header: 66616C73 
2020-05-29 07:41:13.200 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig transport.type error or timeout, return defaultValue TCP, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.EOFException 
2020-05-29 07:41:13.202 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig transport.threadFactory.workerThreadSize error or timeout, return defaultValue null, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.StreamCorruptedException: invalid stream header: 64656661 
2020-05-29 07:41:13.211 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig transport.server error or timeout, return defaultValue NIO, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.EOFException 
2020-05-29 07:41:13.218 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig transport.heartbeat error or timeout, return defaultValue true, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.StreamCorruptedException: invalid stream header: 74727565 
2020-05-29 07:41:13.238 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig transport.threadFactory.bossThreadSize error or timeout, return defaultValue 1, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.EOFException 
2020-05-29 07:41:13.239 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig transport.threadFactory.bossThreadPrefix error or timeout, return defaultValue NettyBoss, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.StreamCorruptedException: invalid stream header: 4E657474 
2020-05-29 07:41:13.241 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig transport.threadFactory.bossThreadSize error or timeout, return defaultValue 1, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.EOFException 
2020-05-29 07:41:13.289 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig transport.threadFactory.workerThreadPrefix error or timeout, return defaultValue NettyServerNIOWorker, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.StreamCorruptedException: invalid stream header: 4E657474 
2020-05-29 07:41:13.309 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig store.file.sessionReloadReadSize error or timeout, return defaultValue 100, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.EOFException 
2020-05-29 07:41:13.310 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.storage.file.session.FileSessionManager has already been loaded, skipped
2020-05-29 07:41:13.310 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.storage.db.session.DataBaseSessionManager has already been loaded, skipped
2020-05-29 07:41:13.313 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig store.db.queryLimit error or timeout, return defaultValue 100, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.EOFException 
2020-05-29 07:41:13.316 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig store.db.datasource error or timeout, return defaultValue null, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.StreamCorruptedException: invalid stream header: 64727569 
Exception in thread "main" io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.server.session.SessionManager caused by java.lang.IllegalStateException: Extension instance(definition: io.seata.common.loader.ExtensionDefinition@8226eb3f, class: interface io.seata.server.session.SessionManager)  could not be instantiated: the name of service provider for [io.seata.core.store.db.DataSourceGenerator] name is null
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:404)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:393)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:358)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:247)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:188)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:80)
	at io.seata.server.session.SessionHolder.init(SessionHolder.java:87)
	at io.seata.server.Server.main(Server.java:75)
Caused by: java.lang.IllegalArgumentException: the name of service provider for [io.seata.core.store.db.DataSourceGenerator] name is null
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:353)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:247)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:188)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:80)
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.<init>(DataBaseTransactionStoreManager.java:98)
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.getInstance(DataBaseTransactionStoreManager.java:84)
	at io.seata.server.storage.db.session.DataBaseSessionManager.init(DataBaseSessionManager.java:81)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:560)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:400)
	... 7 more
```

### Ⅲ. Describe what you expected to happen
使用同一个注册中心（zk），安装包和docker理论上都可以连接，现在是docker可以正常连接，正常启动，安装包不行

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :java version "1.8.0_251"
- OS :centos7 3.10.0-1127.el7.x86_64
- Others:

**Comment by l81893521** [comment]
Because the config.type also is zookeeper, please make sure the config in zookeeper is right.

**Comment by suntchi** [comment]
我已经将配置信息导入zk了：
![image](https://user-images.githubusercontent.com/20620050/83244837-7d8fc680-a1d2-11ea-8ee5-ec89bce380a8.png)
具体配置文件如下：
```
transport.type=TCP
transport.server=NIO
transport.heartbeat=true
transport.enableClientBatchSendRequest=false
transport.threadFactory.bossThreadPrefix=NettyBoss
transport.threadFactory.workerThreadPrefix=NettyServerNIOWorker
transport.threadFactory.serverExecutorThreadPrefix=NettyServerBizHandler
transport.threadFactory.shareBossWorker=false
transport.threadFactory.clientSelectorThreadPrefix=NettyClientSelector
transport.threadFactory.clientSelectorThreadSize=1
transport.threadFactory.clientWorkerThreadPrefix=NettyClientWorkerThread
transport.threadFactory.bossThreadSize=1
transport.threadFactory.workerThreadSize=default
transport.shutdown.wait=3
service.vgroupMapping.seata_tx_group=default
service.default.grouplist=127.0.0.1:8091
service.enableDegrade=false
service.disableGlobalTransaction=false
client.rm.asyncCommitBufferLimit=10000
client.rm.lock.retryInterval=10
client.rm.lock.retryTimes=30
client.rm.lock.retryPolicyBranchRollbackOnConflict=true
client.rm.reportRetryCount=5
client.rm.tableMetaCheckEnable=false
client.rm.sqlParserType=druid
client.rm.reportSuccessEnable=false
client.rm.sagaBranchRegisterEnable=false
client.tm.commitRetryCount=5
client.tm.rollbackRetryCount=5
store.mode=db
store.file.dir=file_store/data
store.file.maxBranchSessionSize=16384
store.file.maxGlobalSessionSize=512
store.file.fileWriteBufferCacheSize=16384
store.file.flushDiskMode=async
store.file.sessionReloadReadSize=100
store.db.datasource=druid
store.db.dbType=mysql
store.db.driverClassName=com.mysql.jdbc.Driver
store.db.url=jdbc:mysql://172.17.0.1:3306/seata
store.db.user=root
store.db.password=root
store.db.minConn=5
store.db.maxConn=30
store.db.globalTable=global_table
store.db.branchTable=branch_table
store.db.queryLimit=100
store.db.lockTable=lock_table
store.db.maxWait=5000
server.recovery.committingRetryPeriod=1000
server.recovery.asynCommittingRetryPeriod=1000
server.recovery.rollbackingRetryPeriod=1000
server.recovery.timeoutRetryPeriod=1000
server.maxCommitRetryTimeout=-1
server.maxRollbackRetryTimeout=-1
server.rollbackRetryTimeoutUnlockEnable=false
client.undo.dataValidation=true
client.undo.logSerialization=jackson
server.undo.logSaveDays=7
server.undo.logDeletePeriod=86400000
client.undo.logTable=undo_log
client.log.exceptionRate=100
transport.serialization=seata
transport.compressor=none
metrics.enabled=false
metrics.registryType=compact
metrics.exporterList=prometheus
metrics.exporterPrometheusPort=9898

```

启动时会一直报：
```
 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:120 -getConfig transport.threadFactory.workerThreadPrefix error or timeout, return defaultValue null, exception:org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.StreamCorruptedException: invalid stream header: 4E657474
```
这种错误，无法启动

我将配置中心换成了nacos，配置如上配置一样，是可以正常启动和注册的

**Comment by suntchi** [comment]
问题已经解决了，直接使用script包下的zk-config.sh推送至zk无法后，通过zkclient访问会出现序列化异常。
我这边是自己写了代码，通过zkclient推送到zk，这样启动seata就能正常读取了，我自己的代码如下：
```
ZookeeperConfiguration zookeeperConfiguration = new ZookeeperConfiguration();
        final long timeout = 2000;
        final String splitConfig = "=";

        InputStream in = AddConfig.class.getResourceAsStream("/config.txt");
        Reader f = new InputStreamReader(in);
        BufferedReader fb = new BufferedReader(f);

        String s = "";
        while ((s = fb.readLine()) != null) {
            if(StringUtils.isNotBlank(s) && s.contains(splitConfig)){
                String dataId = s.split(splitConfig)[0];
                String content = s.split(splitConfig)[1];
                zookeeperConfiguration.removeConfig(dataId,timeout);
                zookeeperConfiguration.putConfig(dataId,content,timeout);
            }
        }

        in.close();
        fb.close();
```

**Comment by easonjim** [comment]
我也出现了这个问题，希望官方可以解决下
