### ISSUE TITLE
seata1.2    -   Duplicate entry '2012931336' for key 'PRIMARY'

### ISSUE THREAD

**Issue by SessionBest** [seata/seata#2748]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
`io.seata.core.exception.BranchTransactionException: Failed to store branch xid = 172.16.0.131:8091:2012931626 branchId = 2012931336
        at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:83)
        at io.seata.server.storage.db.session.DataBaseSessionManager.lockAndExecute(DataBaseSessionManager.java:198)
        at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:266)
        at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:72)
        at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:97)
        at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:192)
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184)
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179)
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116)
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179)
        at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:427)
        at io.seata.core.rpc.DefaultServerMessageListenerImpl.onTrxMessage(DefaultServerMessageListenerImpl.java:101)
        at io.seata.core.rpc.netty.AbstractRpcRemotingServer$ServerHandler.dispatch(AbstractRpcRemotingServer.java:196)
        at io.seata.core.rpc.netty.AbstractRpcRemoting$AbstractHandler$1.run(AbstractRpcRemoting.java:452)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.seata.common.exception.StoreException: Duplicate entry '2012931336' for key 'PRIMARY'
        at io.seata.server.storage.db.store.LogStoreDataBaseDAO.insertBranchTransactionDO(LogStoreDataBaseDAO.java:338)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.writeSession(DataBaseTransactionStoreManager.java:112)
        at io.seata.server.storage.db.session.DataBaseSessionManager.addBranchSession(DataBaseSessionManager.java:131)
        at io.seata.server.session.AbstractSessionManager.onAddBranch(AbstractSessionManager.java:133)
        at io.seata.server.session.GlobalSession.addBranch(GlobalSession.java:241)
        at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:79)
        ... 18 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2012931336' for key 'PRIMARY'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
        at com.mysql.jdbc.Util.getInstance(Util.java:372)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
        at io.seata.server.storage.db.store.LogStoreDataBaseDAO.insertBranchTransactionDO(LogStoreDataBaseDAO.java:336)
        ... 23 common frames omitted`

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : centos7
- Others: seata1.2

**Comment by slievrly** [comment]
@SessionBest when server startup use `-n  $nodeId` startup param ,need to make sure that each server is different

**Comment by SessionBest** [comment]
@slievrly thanks
