### ISSUE TITLE
cloud alibaba启动时seata报错，server.disableGlobalTransaction类型转换失败

### ISSUE THREAD

**Issue by wdxngtzy** [seata/seata#2781]
### Ⅰ. Issue Description
cloud alibaba版本2.2.0.RELEASE ，seata版本 1.2.0，启动报错，seata属性server.disableGlobalTransaction类型转换失败

### Ⅱ. Describe what happened

 Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:238) ~[seata-all-1.2.0.jar:1.2.0]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:431) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 31 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:84) ~[seata-spring-boot-starter-1.0.0.jar:na]
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.addConfigListener(<generated>) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:220) ~[seata-all-1.2.0.jar:1.2.0]
	... 35 common frames omitted
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>) ~[seata-all-1.2.0.jar:1.2.0]
	at io.seata.config.FileConfiguration.addConfigListener(FileConfiguration.java:185) ~[seata-all-1.2.0.jar:1.2.0]
	... 42 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:52351', transport: 'socket'

Process finished with exit code 1

###iii. Environment:

- JDK version : 1.8.0_71
- OS : wind10
- Others:

**Comment by wxbty** [comment]
@wdxngtzy  可以贴下配置文件，另外seata-spring-boot-starter版本号是1.0.0，seata-all为什么用1.2.0？

**Comment by wdxngtzy** [comment]
> @wdxngtzy 可以贴下配置文件，另外seata-spring-boot-starter版本号是1.0.0，seata-all为什么用1.2.0？

已解决，还是版本引用问题，本来想排除spring-cloud-starter-alibaba-seata中的seata-all，见如下注释部分，注释掉就可以正常启动了。感谢回复！
  










        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-all</artifactId>
            <version>1.2.0</version>
        </dependency>
