### ISSUE TITLE
1.2.0版本 windows环境下 nocas 中配置store.db.db-type 不生效

### ISSUE THREAD

**Issue by zzh1ad** [seata/seata#2814]
在根据seata-spring-boot-starter-samples项目配置时
使用nocas导入配置后 
nocas中存在 store.db.db-type=mysql
seate-server启动失败

```
Exception in thread "main" io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.server.session.SessionManager caused by java.lang.IllegalStateException: Extension instance(definition: io.seata.common.loader.ExtensionDefinition@afd05712, class: interface io.seata.server.session.SessionManager)  could not be instantiated: unknown dbtype:null
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:404)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:393)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:358)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:247)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:188)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:80)
        at io.seata.server.session.SessionHolder.init(SessionHolder.java:87)
        at io.seata.server.Server.main(Server.java:75)
Caused by: java.lang.IllegalArgumentException: unknown dbtype:null
        at io.seata.core.constants.DBType.valueof(DBType.java:89)
        at io.seata.core.store.db.AbstractDataSourceGenerator.getDBType(AbstractDataSourceGenerator.java:69)
        at io.seata.server.store.DbcpDataSourceGenerator.generateDataSource(DbcpDataSourceGenerator.java:50)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.<init>(DataBaseTransactionStoreManager.java:99)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.getInstance(DataBaseTransactionStoreManager.java:84)
        at io.seata.server.storage.db.session.DataBaseSessionManager.init(DataBaseSessionManager.java:81)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:560)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:400)
        ... 7 more
```

最后添加 store.db.dbType=mysql 后启动成功

**Comment by zzh1ad** [comment]
![image](https://user-images.githubusercontent.com/28721263/85088750-6eb99400-b213-11ea-80a3-51a988c59ddb.png)
统一转为驼峰格式。。。
