### ISSUE TITLE
Druid解析SQL出现错误：using nextval('jv_snapshot_pk_seq') * 100 for insert SQL

### ISSUE THREAD

**Issue by mac8088** [seata/seata#2821]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

出现此问题的技术条件：

基于Seata1.2.0 + Druid 1.12 or Druid 1.22 + Javers 5.8.13 + PostgreSQL 11.6

如果不启用Seata + Druid, 在微服务调用中，当保存entity的时候，使用 Javers 可以保存 audit trail ，也就是实体前后变化的对照。

如果启用Seata + Druid, 上述的操作由于底层的audit trail 的保存失败，而整体回滚。

目前判断是：Seata所仰仗的Druid是无法处理类似 Insert SQL:

INSERT INTO jv_snapshot ( type, global_id_fk, commit_fk, version, state, changed_properties, managed_type, snapshot_pk ) VALUES  ( ?,?,?,?,?,?,?,nextval('jv_snapshot_pk_seq') * 100 )

而上面的SQL语句，打开一个SQL client 通过手工调整数据的方式，是可以被成功执行的。

### Ⅱ. Describe what happened

020-06-20 16:20:11.466 ERROR 5304 --- [  XNIO-1 task-2] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

org.javers.common.exception.JaversException: SQL_EXCEPTION: io.seata.sqlparser.SQLParsingException: Unknown SQLExpr: class com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr nextval('jv_snapshot_pk_seq') * 100
while executing sql: INSERT INTO jv_snapshot ( type, global_id_fk, commit_fk, version, state, changed_properties, managed_type, snapshot_pk ) VALUES  ( ?,?,?,?,?,?,?,nextval('jv_snapshot_pk_seq') * 100 )
	at org.javers.repository.sql.session.PreparedStatementExecutor.wrapExceptionAndCall(PreparedStatementExecutor.java:120)
	at org.javers.repository.sql.session.PreparedStatementExecutor.runVoidSql(PreparedStatementExecutor.java:110)
	at org.javers.repository.sql.session.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:39)
	at org.javers.repository.sql.session.Session.execute(Session.java:105)
	at org.javers.repository.sql.session.Session.executeInsert(Session.java:75)
	at org.javers.repository.sql.session.InsertBuilder.execute(InsertBuilder.java:58)
	at org.javers.repository.sql.repositories.CdoSnapshotRepository.save(CdoSnapshotRepository.java:37)
	at org.javers.repository.sql.JaversSqlRepository.persist(JaversSqlRepository.java:87)
	at org.javers.repository.api.JaversExtendedRepository.persist(JaversExtendedRepository.java:154)
	at org.javers.core.JaversCore.persist(JaversCore.java:105)
	at org.javers.core.JaversCore.commit(JaversCore.java:86)
	at org.javers.spring.jpa.JaversTransactionalDecorator.commit(JaversTransactionalDecorator.java:82)
	at org.javers.spring.jpa.JaversTransactionalDecorator$$FastClassBySpringCGLIB$$acb40bd0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.javers.spring.jpa.JaversTransactionalDecorator$$EnhancerBySpringCGLIB$$1830d8ca.commit(<generated>)
	at org.javers.spring.auditable.aspect.JaversCommitAdvice.commitObject(JaversCommitAdvice.java:81)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at org.javers.spring.auditable.aspect.springdata.AbstractSpringAuditableRepositoryAspect.lambda$onSave$0(AbstractSpringAuditableRepositoryAspect.java:28)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 使用Jhipster产生一个微服务工程，实现一个JPA实体的CURD.
2. 在此项目的基础上，集成一个 Javers, https://javers.org/documentation/spring-boot-integration/

@Repository
@JaversSpringDataAuditable
public interface UserInfoRepository extends JpaRepository<UserInfo, Long>, JpaSpecificationExecutor<UserInfo> {
....
}

3. 不启用Seata (Durid), 使用hikari是可以实现： 保存实体的同时，自动保存 Entity Audit Trail.

4. 启用Seata, Durid 替换hikari，则出现所描述的SQL错误。

### Ⅴ. Anything else we need to know?

我也类似的SIR给Druid: https://github.com/alibaba/druid/issues/3840

### Ⅵ. Environment:

- JDK version : openjdk version "11.0.6" 2020-01-14
- OS : window 10
- Others: Seata 1.2.0, Druid 1.12 or Druid 1.22 
- Javers 5.8.13 + PostgreSQL 11.6

**Comment by mac8088** [comment]
![the root cause in Seata code](https://user-images.githubusercontent.com/26015839/85199556-1671b780-b323-11ea-93f7-604c12e2e323.png)

io.seata.sqlparser.druid.postgresql.PostgresqlInsertRecognizer

might be method that exist this problem: 
public List<List<Object>> getInsertRows() {
}

**Comment by mac8088** [comment]
![workaround fix in javers](https://user-images.githubusercontent.com/26015839/85199584-40c37500-b323-11ea-9353-47719051a5ac.png)

**Comment by jsbxyyx** [comment]
@mac8088 not support this expression.

**Comment by jsbxyyx** [comment]
@mac8088 1.3  not primary key column will support any expression.

**Comment by mac8088** [comment]
@jsbxyyx  is this issue fixed inside the seata release 1.3?

**Comment by jsbxyyx** [comment]
@mac8088 1.3 version support not primary key column any expression.
