### ISSUE TITLE
seata引入seata无法启动项目,两个TimeOutChecker形成死锁

### ISSUE THREAD

**Issue by yueyuanyu** [seata/seata#2857]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

在尝试seata与项目整合过程中首先是与springbatch不兼容,提前初始化了被stepscope注解注上的bean,此issue:https://github.com/seata/seata/issues/2815 已在@wangliang1986 pr上解决(排除不想代理的类),但接下来项目在启动到flyway初始化结束后卡死,查看jstack发现发生死锁
### Ⅱ. Describe what happened

 这里是jstack详情:
![QQ图片20200704174951](https://user-images.githubusercontent.com/33542699/86510006-cf092200-be1e-11ea-97db-15b092888b48.png)
长图的最下面，那里显示着死锁的两个线程，下面那个main线程调用了两次seata的服务发现功能，死锁了。io.seata.discovery.registry.registryFactory

### Ⅲ. Describe what you expected to happen

急需解决此bug(基本上与springbatch整合发生很多问题,建议考虑与springbatch整合情况)

### Ⅵ. Environment:

- JDK version : 1.8
- Others: springboot 1.5.6 springbatch 3.0.8

**Comment by cmofustb-bit** [comment]
向同一TC注册RM和TM时，出现同样的问题，导致服务启动失败

**Comment by wangliang1986** [comment]
> 
> 
>     * [ ]  I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
> 
> 
> ### Ⅰ. Issue Description
> 
> 在尝试seata与项目整合过程中首先是与springbatch不兼容,提前初始化了被stepscope注解注上的bean,此issue:#2815 已在@wangliang1986 pr上解决(排除不想代理的类),但接下来项目在启动到flyway初始化结束后卡死,查看jstack发现发生死锁
> ### Ⅱ. Describe what happened
> 
> 这里是jstack详情:
> ![QQ图片20200704174951](https://user-images.githubusercontent.com/33542699/86510006-cf092200-be1e-11ea-97db-15b092888b48.png)
> 长图的最下面，那里显示着死锁的两个线程，下面那个main线程调用了两次seata的服务发现功能，死锁了。io.seata.discovery.registry.registryFactory
> ### Ⅲ. Describe what you expected to happen
> 
> 急需解决此bug(基本上与springbatch整合发生很多问题,建议考虑与springbatch整合情况)
> ### Ⅵ. Environment:
> 
>     * JDK version : 1.8
> 
>     * Others: springboot 1.5.6 springbatch 3.0.8

能否提供一个简单的复现demo？

**Comment by wangliang1986** [comment]
能否提供一个复现的demo？

**Comment by cmofustb-bit** [comment]
不是必现，jstack内容供参考。

Found one Java-level deadlock:
=============================
"main":
  waiting to lock monitor 0x00007fe824012898 (object 0x000000076f20c078, a java.lang.Object),
  which is held by "timeoutChecker_2"
"timeoutChecker_2":
  waiting to lock monitor 0x00007fe8240121b8 (object 0x00000006c2ca1a38, a java.util.concurrent.ConcurrentHashMap),
  which is held by "main"

Java stack information for the threads listed above:
===================================================
"main":
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:103)
	- waiting to lock <0x000000076f20c078> (a java.lang.Object)
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:175)
	at io.seata.core.rpc.netty.RmRpcClient.registerResource(RmRpcClient.java:198)
	at io.seata.rm.AbstractResourceManager.registerResource(AbstractResourceManager.java:120)
	at io.seata.rm.datasource.DataSourceManager.registerResource(DataSourceManager.java:149)
	at io.seata.rm.DefaultResourceManager.registerResource(DefaultResourceManager.java:114)
	at io.seata.rm.datasource.DataSourceProxy.init(DataSourceProxy.java:93)
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:82)
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:71)
	at io.seata.spring.annotation.datasource.DataSourceProxyHolder$$Lambda$645/1453921354.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	- locked <0x000000076f71ad68> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at io.seata.spring.annotation.datasource.DataSourceProxyHolder.putDataSource(DataSourceProxyHolder.java:64)
	at io.seata.spring.annotation.datasource.SeataAutoDataSourceProxyAdvice.invoke(SeataAutoDataSourceProxyAdvice.java:34)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.alibaba.druid.pool.DruidDataSource$$EnhancerBySpringCGLIB$$6dbf6009.unwrap(<generated>)
	at org.springframework.boot.jdbc.DataSourceUnwrapper.safeUnwrap(DataSourceUnwrapper.java:79)
	at org.springframework.boot.jdbc.DataSourceUnwrapper.unwrap(DataSourceUnwrapper.java:57)
	at org.springframework.boot.autoconfigure.jdbc.metadata.DataSourcePoolMetadataProvidersConfiguration$HikariPoolDataSourceMetadataProviderConfiguration.lambda$hikariPoolDataSourceMetadataProvider$0(DataSourcePoolMetadataProvidersConfiguration.java:66)
	at org.springframework.boot.autoconfigure.jdbc.metadata.DataSourcePoolMetadataProvidersConfiguration$HikariPoolDataSourceMetadataProviderConfiguration$$Lambda$706/779865426.getDataSourcePoolMetadata(Unknown Source)
	at org.springframework.boot.jdbc.metadata.CompositeDataSourcePoolMetadataProvider.getDataSourcePoolMetadata(CompositeDataSourcePoolMetadataProvider.java:54)
	at org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration.getValidationQuery(DataSourceHealthIndicatorAutoConfiguration.java:115)
	at org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration.createHealthIndicator(DataSourceHealthIndicatorAutoConfiguration.java:110)
	at org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration.createHealthIndicator(DataSourceHealthIndicatorAutoConfiguration.java:59)
	at org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration$$EnhancerBySpringCGLIB$$70a7b013.createHealthIndicator(<generated>)
	at org.springframework.boot.actuate.autoconfigure.health.CompositeHealthIndicatorConfiguration.lambda$createHealthIndicator$0(CompositeHealthIndicatorConfiguration.java:49)
	at org.springframework.boot.actuate.autoconfigure.health.CompositeHealthIndicatorConfiguration$$Lambda$714/769298867.accept(Unknown Source)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.springframework.boot.actuate.autoconfigure.health.CompositeHealthIndicatorConfiguration.createHealthIndicator(CompositeHealthIndicatorConfiguration.java:48)
	at org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration.dbHealthIndicator(DataSourceHealthIndicatorAutoConfiguration.java:105)
	at org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration$$EnhancerBySpringCGLIB$$70a7b013.CGLIB$dbHealthIndicator$1(<generated>)
	at org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration$$EnhancerBySpringCGLIB$$70a7b013$$FastClassBySpringCGLIB$$7b799d17.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration$$EnhancerBySpringCGLIB$$70a7b013.dbHealthIndicator(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$140/1910098693.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	- locked <0x00000006c2ca1a38> (a java.util.concurrent.ConcurrentHashMap)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	- locked <0x00000006c1adc870> (a java.lang.Object)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.xiaomi.browser.newsfeed.NewsFeedApiSpringbootApplication.main(NewsFeedApiSpringbootApplication.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
"timeoutChecker_2":
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:179)
	- waiting to lock <0x00000006c2ca1a38> (a java.util.concurrent.ConcurrentHashMap)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:493)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:514)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:485)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:462)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:407)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:341)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:335)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1123)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:93)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:82)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$200(SpringBootConfigurationProvider.java:43)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:58)
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>)
	at io.seata.core.protocol.ProtocolConstants.<clinit>(ProtocolConstants.java:79)
	at io.seata.core.rpc.netty.AbstractRpcRemoting.sendAsyncRequest(AbstractRpcRemoting.java:206)
	at io.seata.core.rpc.netty.AbstractRpcRemoting.sendAsyncRequestWithResponse(AbstractRpcRemoting.java:181)
	at io.seata.core.rpc.netty.AbstractRpcRemoting.sendAsyncRequestWithResponse(AbstractRpcRemoting.java:163)
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:66)
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:34)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:206)
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:103)
	- locked <0x000000076f20c078> (a java.lang.Object)
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:175)
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient$1.run(AbstractRpcRemotingClient.java:115)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.

**Comment by cmofustb-bit** [comment]
![image](https://user-images.githubusercontent.com/68105673/87142848-b80f7780-c2d7-11ea-848a-479d3aad149f.png)

**Comment by wangliang1986** [comment]
你们两个的死锁的情况不一样。
@yueyuanyu  一个是main函数自己跟自己死锁了，你暂时在main线程里禁用AT就行，之前提供的那行代码。暂时先处理一下，后面我会跟进查明具体的原因并提供更好的解决方案。
@cmofustb-bit 你的是main和rpc的一个定时任务产生的死锁，这个应该可以将定时任务延后执行来解决。
最好都提供一下demo。

**Comment by yueyuanyu** [comment]
> 能否提供一个复现的demo？

还有一个 偶尔发生的死锁 定位到 seata的configcache

**Comment by yueyuanyu** [comment]
都是checkouttimer引起的

**Comment by wangliang1986** [comment]
我重新看了一下你们的两个问题，都是由timeoutChecker的SpringBootConfigurationProvider尝试获取配置bean和main获取bean造成的死锁。
#2879 ，这个PR，你们试一下看看吧。
这个PR调整了两个内容：
1、配置bean的创建提前到了Seata的其他所有bean。
2、在不需要执行AT时，不走代理。

**Comment by wangliang181230** [comment]
@yueyuanyu 你的死锁问题，已经在 PR #3130 里解决了，已经合并了。
@cmofustb-bit 你的死锁问题，还需要等 PR #2879 合并后，才能解决。

**Comment by wangliang181230** [comment]
PR #3130 已经合并，目前最新镜像版本（1.5.0-SNAPSHOT）可以使用。
