### ISSUE TITLE
No application config found or it's not a valid config! Please add <dubbo:application name="..." /> to your spring config.

### ISSUE THREAD

**Issue by liubenlong** [seata/seata#2911]
启动官方实例[transfer-tcc-sample]的时候，master分支。报错: 

2020-07-21 14:27:19.453 ERROR[main]org.apache.zookeeper.server.NIOServerCnxnFactory.uncaughtException:92 -Thread Thread[main,5,main] died
java.lang.IllegalStateException: No application config found or it's not a valid config! Please add <dubbo:application name="..." /> to your spring config.
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateApplicationConfig(ConfigValidationUtils.java:371)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.checkGlobalConfigs(DubboBootstrap.java:529)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.initialize(DubboBootstrap.java:514)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:698)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:52)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:45)
	at org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener.onApplicationEvent(OneTimeExecutionApplicationContextEventListener.java:40)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
	at io.seata.samples.tcc.transfer.starter.TransferProviderStarter.main(TransferProviderStarter.java:21)

**Comment by liubenlong** [comment]
没问题了，编译启动应该使用Java8，我用的11所以有问题。

**Comment by kebukeyi** [comment]
我换成了jdk8 没问题了，之前是jdk11有问题；dubbo：2.7.8；
