### ISSUE TITLE
seata 在 k8s 环境下（服务治理：istio）  客户端和服务端无法通信的问题：Adjusted frame length exceeds 8388608: 1345270062 - discarded

### ISSUE THREAD

**Issue by i-tudou** [seata/seata#2927]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

我这边测试环境是k8s，使用istio做的服务治理。seata  用的是 db模式，服务发现用的是redis。开发环境是完全OK的，部署到测试环境后 连接tc会报：Adjusted frame length exceeds 8388608: 1345270062 

### Ⅱ. Describe what happened

Seata Client 异常信息如下：

```
2020-07-27 11:45:01.990  INFO 7 --- [eoutChecker_2_1] i.s.c.r.netty.NettyClientChannelManager  : will connect to 10.2.49.245:8091
2020-07-27 11:45:01.990  INFO 7 --- [eoutChecker_1_1] i.s.c.r.netty.NettyClientChannelManager  : will connect to 10.2.49.245:8091
2020-07-27 11:45:01.996  INFO 7 --- [eoutChecker_2_1] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:RMROLE,address:10.2.49.245:8091,msg:< RegisterRMRequest{resourceIds='null', applicationId='szdk-tp-system', transactionServiceGroup='seata-server-group'} >
2020-07-27 11:45:01.996  INFO 7 --- [eoutChecker_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:TMROLE,address:10.2.49.245:8091,msg:< RegisterTMRequest{applicationId='szdk-tp-system', transactionServiceGroup='seata-server-group'} >
2020-07-27 11:45:02.045  WARN 7 --- [ctor_RMROLE_1_1] ServiceLoader$InnerEnhancedServiceLoader : Load [io.seata.serializer.hessian.HessianSerializer] class fail. com/caucho/hessian/io/AbstractHessianOutput
2020-07-27 11:45:02.084 ERROR 7 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : 0318

io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 1345270062 - discarded
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:82) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar!/:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]

2020-07-27 11:45:02.084 ERROR 7 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : 0318

io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 1345270062 - discarded
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:82) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) [netty-transport-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.33.Final.jar!/:4.1.33.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar!/:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]

2020-07-27 11:45:07.027 DEBUG 7 --- [SchedulerThread] org.quartz.core.QuartzSchedulerThread    : batch acquisition of 0 triggers
2020-07-27 11:45:09.437  INFO 7 --- [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats    : WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
2020-07-27 11:45:30.303 DEBUG 7 --- [SchedulerThread] org.quartz.core.QuartzSchedulerThread    : batch acquisition of 0 triggers
2020-07-27 11:45:32.020 ERROR 7 --- [eoutChecker_1_1] i.s.c.rpc.netty.AbstractNettyRemoting    : wait response error:cost 30006 ms,ip:/10.2.49.245:8091,request:RegisterTMRequest{applicationId='szdk-tp-system', transactionServiceGroup='seata-server-group'}
2020-07-27 11:45:32.020 ERROR 7 --- [eoutChecker_2_1] i.s.c.rpc.netty.AbstractNettyRemoting    : wait response error:cost 30006 ms,ip:/10.2.49.245:8091,request:RegisterRMRequest{resourceIds='null', applicationId='szdk-tp-system', transactionServiceGroup='seata-server-group'}
2020-07-27 11:45:32.022 ERROR 7 --- [eoutChecker_1_1] i.s.c.r.netty.NettyClientChannelManager  : 0304 register RM failed.

io.seata.common.exception.FrameworkException: register TMROLE error, errMsg:cost 30006 ms
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:78) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:34) ~[seata-all-1.3.0.jar!/:1.3.0]
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220) ~[commons-pool-1.6.jar!/:1.6]
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:206) [seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:103) [seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:175) [seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:106) [seata-all-1.3.0.jar!/:1.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_192]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_192]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_192]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar!/:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]

2020-07-27 11:45:32.022 ERROR 7 --- [eoutChecker_2_1] i.s.c.r.netty.NettyClientChannelManager  : 0304 register RM failed.

io.seata.common.exception.FrameworkException: register RMROLE error, errMsg:cost 30006 ms
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:78) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:34) ~[seata-all-1.3.0.jar!/:1.3.0]
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220) ~[commons-pool-1.6.jar!/:1.6]
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:206) [seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:103) [seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:175) [seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:106) [seata-all-1.3.0.jar!/:1.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_192]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_192]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_192]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar!/:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]

2020-07-27 11:45:32.023 ERROR 7 --- [eoutChecker_1_1] i.s.c.r.netty.NettyClientChannelManager  : 0101 can not connect to 10.2.49.245:8091 cause:can not register RM,err:register TMROLE error, errMsg:cost 30006 ms

io.seata.common.exception.FrameworkException: can not register RM,err:register TMROLE error, errMsg:cost 30006 ms
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:210) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:103) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:175) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:106) [seata-all-1.3.0.jar!/:1.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_192]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_192]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_192]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar!/:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]

2020-07-27 11:45:32.023 ERROR 7 --- [eoutChecker_2_1] i.s.c.r.netty.NettyClientChannelManager  : 0101 can not connect to 10.2.49.245:8091 cause:can not register RM,err:register RMROLE error, errMsg:cost 30006 ms

io.seata.common.exception.FrameworkException: can not register RM,err:register RMROLE error, errMsg:cost 30006 ms
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:210) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:103) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:175) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:106) [seata-all-1.3.0.jar!/:1.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_192]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_192]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_192]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar!/:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?

当把测试环境的istio的注入的代理（envoy）拿掉之后，服务端和客户端可以正常通信。

猜测：第一次客户端是连上服务端了，但是后续服务端对响应时istio的代理（envoy）将响应报文代理改写了，导致客户端解析报文时出错。

seata server配置如下：
```yml
apiVersion: v1
kind: Service
metadata:
  name: seata-server
  namespace: szdk
  labels:
    app: seata-server
spec:
  type: NodePort
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: http
  selector:
    app: seata-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seata-server
  namespace: szdk
  labels:
    app: seata-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seata-server
  template:
    metadata:
      name: seata-server
      labels:
        app: seata-server
    spec:
      containers:
        - name: seata-server
          image: docker.io/seataio/seata-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SEATA_CONFIG_NAME
              value: file:/root/seata-config/registry
            - name: STORE_MODE
              value: db
            - name: SEATA_PORT
              value: "8091"
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          volumeMounts:
            - name: seata-config
              mountPath: /root/seata-config
      volumes:
        - name: seata-config
          configMap:
            name: seata-server-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
  namespace: szdk
data:
  file.conf: |
    store{
        mode = "db"
        db {
            datasource = "druid"
            dbType = "mysql"
            driverClassName = "com.mysql.jdbc.Driver"
            url = "jdbc:mysql://192.168.20.236:3306/seata?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai"
            user = "dbuser"
            password = "123456"
            minConn = 5
            maxConn = 30
            globalTable = "global_table"
            branchTable = "branch_table"
            lockTable = "lock_table"
            queryLimit = 100
            maxWait = 5000
        }
    }
  registry.conf: |
    registry {
        type = "redis"
        redis {
          serverAddr = "192.168.20.233:6379"
          db = 31
          password = ""
          cluster = "seata-server"
          timeout = 20000
        }
    }
    config {
      type = "file"
      file {
        name = "file:/root/seata-config/file.conf"
      }
    }
```
    
seata client配置：

依赖：
```xml
<!--seata-->
<dependency>
   <groupId>io.seata</groupId>
   <artifactId>seata-spring-boot-starter</artifactId>
   <version>1.3.0</version>
</dependency>
```

配置文件：
```yml
seata:
  enabled: true #开启seata分布式事务
  application-id: ${spring.application.name} #client 服务名称
  tx-service-group: seata-server-group #该名称必须和 service.vgroup-mapping 下相同
  enable-auto-data-source-proxy: false #关闭数据源自动代理，框架已经集成，包括多数据源
  service:
    vgroup-mapping:
      seata-server-group: seata-server #服务发现组件上的 seata-server 服务名
  registry:
    type: redis
    redis:
      serverAddr: ${spring.redis.host}:${spring.redis.port:6379}
      cluster: seata-server
      db: ${spring.redis.database}
      timeout: ${spring.redis.timeout}
```

### Ⅵ. Environment:
- JDK version : 8+
- OS : k8s + istio
- seata version： 1.3.0
- K8S version：v1.14.8 
- istio version：1.3.5

**Comment by slievrly** [comment]
@i-tudou has the problem been solved?

**Comment by SiriusZhang** [comment]
这个问题解决了吗？怎么解决？
how to solve the problem

**Comment by i-tudou** [comment]
> 这个问题解决了吗？怎么解决？
> how to solve the problem

问题没有解决呢，目前我们将envoy关闭了，将就着用呢，seata 1.4的版本还是有这个问题。

**Comment by i-tudou** [comment]
问题已解决。

**Comment by i-tudou** [comment]
> @i-tudou has the problem been solved?

问题已解决。解决方式：部署seata server时将port name 修改为seata或其它，不能使用http。具体原理的话没有深入排查，估计是envoy对指定的name有特殊的处理。

处理后配置如下：

```yaml
apiVersion: v1
kind: Service
metadata:
  name: seata-server
  namespace: szdk
  labels:
    app: seata-server
spec:
  type: NodePort
  ports:
    - port: 30091
      targetPort: 30091
      nodePort: 30091
      protocol: TCP
      name: seata    #此处原为http修改为seata
  selector:
    app: seata-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seata-server
  namespace: szdk
  labels:
    app: seata-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seata-server
  template:
    metadata:
      name: seata-server
      labels:
        app: seata-server
      annotations:
        sidecar.istio.io/inject: "false"  #seata server 没有http请求的需求，关闭代理
    spec:
      containers:
        - name: seata-server
          image: docker.io/seataio/seata-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SEATA_CONFIG_NAME
              value: file:/root/seata-config/registry
            - name: STORE_MODE
              value: db
            - name: SEATA_PORT
              value: "30091"
            - name: SEATA_IP
              value: 192.168.20.33
          ports:
            - name: seata   #此处原为http修改为seata
              containerPort: 30091
              protocol: TCP
          volumeMounts:
            - name: seata-config
              mountPath: /root/seata-config
      volumes:
        - name: seata-config
          configMap:
            name: seata-server-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
  namespace: szdk
data:
  file.conf: |
    store{
        mode = "db"
        db {
            datasource = "druid"
            dbType = "mysql"
            driverClassName = "com.mysql.jdbc.Driver"
            url = "jdbc:mysql://192.168.20.236:3306/seata?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai"
            user = "dbuser"
            password = "123456"
            minConn = 5
            maxConn = 30
            globalTable = "global_table"
            branchTable = "branch_table"
            lockTable = "lock_table"
            queryLimit = 100
            maxWait = 5000
        }
    }
  registry.conf: |
    registry {
        type = "redis"
        redis {
          serverAddr = "192.168.20.233:6379"
          db = 31
          password = ""
          cluster = "seata-server"
          timeout = 20000
        }
    }
    config {
      type = "file"
      file {
        name = "file:/root/seata-config/file.conf"
      }
    }
```

**Comment by catman002** [comment]
3   克油，我也遇到这样问题，试试。

**Comment by catman002** [comment]
@i-tudou 
部署的时候k8s 理还要配 ? :    这个油什么用
```
  - name: SEATA_IP
              value: 192.168.20.33
```

我用的也是istio 1.9x发布微服务，但是链接seata的时候老是报错误：
```
init datasource error, url: jdbc:mysql://192.168.1.145:3306/MXL-TEST?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.19.jar!/:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar!/:8.0.19]

。。。。

	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:maixiaolan-0.0.1-SNAPSHOT]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[na:na]
```

帮看看呗。。。。

**Comment by i-tudou** [comment]
> @i-tudou
> 部署的时候k8s 理还要配 ? : 这个油什么用
> 
> ```
>   - name: SEATA_IP
>               value: 192.168.20.33
> ```
> 
> 我用的也是istio 1.9x发布微服务，但是链接seata的时候老是报错误：
> 
> ```
> init datasource error, url: jdbc:mysql://192.168.1.145:3306/MXL-TEST?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
> 
> java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.19.jar!/:8.0.19]
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar!/:8.0.19]
> 
> 。。。。
> 
> 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:maixiaolan-0.0.1-SNAPSHOT]
> Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
> 
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[na:na]
> ```
> 
> 帮看看呗。。。。

```yml
- name: SEATA_IP
   value: 192.168.20.33
```
这段不需要配置的，应该是之前测试的时候遗留的配置。
