### ISSUE TITLE
使用application.yml配置registry, 报io.seata.common.exception.NotSupportYetException: config type can not be null

### ISSUE THREAD

**Issue by cay914** [seata/seata#2959]
使用application.yml配置registry, 报io.seata.common.exception.NotSupportYetException: config type can not be null

不想使用registry.conf文件和file.conf文件配置seata，直接在application.yml配置seata连接nacos的注册中心和配置中心。
但是好像不生效

Excetion stack:
Connected to the target VM, address: '127.0.0.1:2884', transport: 'socket'
2020-07-31 21:42:35.554  INFO 21192 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$457e18c0] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.1.10.RELEASE)

2020-07-31 21:42:37.054  INFO 21192 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource {name='NACOS', propertySources=[NacosPropertySource {name='order-service.yaml'}]}
2020-07-31 21:42:37.060  INFO 21192 --- [           main] com.codebattery.Application              : No active profile set, falling back to default profiles: default
2020-07-31 21:42:38.505  WARN 21192 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'nacos-config' contains invalid characters, please migrate to a valid format.
2020-07-31 21:42:38.508  WARN 21192 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'nacos-discovery' contains invalid characters, please migrate to a valid format.
2020-07-31 21:42:38.868  INFO 21192 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2020-07-31 21:42:38.868  INFO 21192 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-07-31 21:42:38.991  INFO 21192 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 113ms. Found 1 repository interfaces.
2020-07-31 21:42:39.008  INFO 21192 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2020-07-31 21:42:39.010  INFO 21192 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-07-31 21:42:39.036  INFO 21192 --- [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.codebattery.repository.OrderRepository. If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository.
2020-07-31 21:42:39.036  INFO 21192 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 15ms. Found 0 repository interfaces.
2020-07-31 21:42:39.171  WARN 21192 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
2020-07-31 21:42:39.667  INFO 21192 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=c5ca8343-8930-3dcd-a0dd-641b465c81df
2020-07-31 21:42:39.893  INFO 21192 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'stringToNoneShardingStrategyConfigurationConverter' of type [org.apache.shardingsphere.spring.boot.converter.StringToNoneShardingStrategyConfigurationConverter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-31 21:42:39.899  INFO 21192 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.cloud.alibaba.seata-com.alibaba.cloud.seata.SeataProperties' of type [com.alibaba.cloud.seata.SeataProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-31 21:42:39.900  INFO 21192 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'com.alibaba.cloud.seata.GlobalTransactionAutoConfiguration' of type [com.alibaba.cloud.seata.GlobalTransactionAutoConfiguration$$EnhancerBySpringCGLIB$$b6901f3e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-31 21:42:53.234  WARN 21192 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'globalTransactionScanner' defined in class path resource [com/alibaba/cloud/seata/GlobalTransactionAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is io.seata.common.exception.NotSupportYetException: config type can not be null
2020-07-31 21:42:53.258  INFO 21192 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-07-31 21:42:53.292 ERROR 21192 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'globalTransactionScanner' defined in class path resource [com/alibaba/cloud/seata/GlobalTransactionAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is io.seata.common.exception.NotSupportYetException: config type can not be null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$144/1189651769.getObject(Unknown Source) ~[na:na]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:228) ~[spring-context-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:721) ~[spring-context-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:534) ~[spring-context-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) [spring-boot-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) [spring-boot-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) [spring-boot-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at com.codebattery.Application.main(Application.java:27) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is io.seata.common.exception.NotSupportYetException: config type can not be null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	... 20 common frames omitted
Caused by: io.seata.common.exception.NotSupportYetException: **config type can not be null**
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:106) ~[seata-all-1.3.0.jar:1.3.0]
	at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:90) ~[seata-all-1.3.0.jar:1.3.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:81) ~[seata-all-1.3.0.jar:1.3.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:125) ~[seata-all-1.3.0.jar:1.3.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:114) ~[seata-all-1.3.0.jar:1.3.0]
	at com.alibaba.cloud.seata.GlobalTransactionAutoConfiguration.globalTransactionScanner(GlobalTransactionAutoConfiguration.java:58) ~[spring-cloud-alibaba-seata-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at com.alibaba.cloud.seata.GlobalTransactionAutoConfiguration$$EnhancerBySpringCGLIB$$b6901f3e.CGLIB$globalTransactionScanner$0(<generated>) ~[spring-cloud-alibaba-seata-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at com.alibaba.cloud.seata.GlobalTransactionAutoConfiguration$$EnhancerBySpringCGLIB$$b6901f3e$$FastClassBySpringCGLIB$$49d1a1f5.invoke(<generated>) ~[spring-cloud-alibaba-seata-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at com.alibaba.cloud.seata.GlobalTransactionAutoConfiguration$$EnhancerBySpringCGLIB$$b6901f3e.globalTransactionScanner(<generated>) ~[spring-cloud-alibaba-seata-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	... 21 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:2884', transport: 'socket'

Process finished with exit code 1

环境:
JDK 1.8
Spring Cloud Greenwich.SR4

spring-cloud-starter-alibaba-seata:2.1.10.RELEASE
io.seata:seata-all:1.3.0

使用到的配置
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  data-source-proxy-mode: XA
  use-jdk-proxy: false
#  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 192.168.3.31:8091
    enable-degrade: false
    disable-global-transaction: false
  config:
    type: nacos
    nacos:
      namespace: bde377f9-9270-4b3d-a5ee-a29c5f5672cc
      serverAddr: 192.168.3.31:8848
      group: seata
      username: ""
      password: ""
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.3.31:8848
      group : seata
      namespace: bde377f9-9270-4b3d-a5ee-a29c5f5672cc
      username: ""
      password: ""

**Comment by slievrly** [comment]
@cay914  What is the seata-spring-boot-starter version?

**Comment by LiuRuiPeng2333** [comment]
一样，请问怎么解决的

**Comment by czq3** [comment]
> @ cay914 什么是seata-spring-boot-starter版本？

咋解决啊大佬

**Comment by amazingman128** [comment]
I have the save issue in using docker-compose. 

the docker-compose.yml file is below 



``` version: "3.1"
  
services:

  seata-server:
    image: seataio/seata-server:1.3.0
    hostname: gtmall-seata-server
    ports:
      - 8091:8091
    environment:
      - SEATA_PORT=8091
      - SEATA_CONFIG_NAME=file:/usr/local/data/seata/conf/resources/registry
    expose:
      - 8091
```
and the registry.conf file 

```registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "nacos"

  nacos {
    application = "seata-server"
    serverAddr = "10.13.10.212:8848"
    group = "SEATA_GROUP"
    namespace = ""
    cluster = "default"
    username = ""
    password = ""
  }
  eureka {
    serviceUrl = "http://localhost:8761/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = 0
    password = ""
    cluster = "default"
    timeout = 0
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
  }
  etcd3 {
    cluster = "default"
    serverAddr = "http://localhost:2379"
  }
  sofa {
    serverAddr = "127.0.0.1:9603"
    application = "default"
    region = "DEFAULT_ZONE"
    datacenter = "DefaultDataCenter"
    cluster = "default"
    group = "SEATA_GROUP"
    addressWaitTime = "3000"
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "nacos"

  nacos {
    serverAddr = "10.13.10.212:8848"
    namespace = ""
    group = "SEATA_GROUP"
    username = ""
    password = ""
  }
  consul {
    serverAddr = "127.0.0.1:8500"
  }
  apollo {
    appId = "seata-server"
    apolloMeta = "http://192.168.1.204:8801"
    namespace = "application"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  etcd3 {
    serverAddr = "http://localhost:2379"
  }
  file {
    name = "file.conf"
  }
}
```

the error message 

```[root@localhost seata]# docker-compose -f docker-compose.yml up
Starting seata_seata-server_1 ... done
Attaching to seata_seata-server_1
seata-server_1  | 2020-08-31 07:48:23.276  INFO --- [           main] io.seata.server.Server                   : The server is running in container.
seata-server_1  | Exception in thread "main" io.seata.common.exception.NotSupportYetException: config type can not be null
seata-server_1  |       at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:106)
seata-server_1  |       at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:90)
seata-server_1  |       at io.seata.server.ParameterParser.init(ParameterParser.java:87)
seata-server_1  |       at io.seata.server.ParameterParser.<init>(ParameterParser.java:60)
seata-server_1  |       at io.seata.server.Server.main(Server.java:72)
seata_seata-server_1 exited with code 1
```

**Comment by wangfy1989** [comment]
> yml

mee too

**Comment by cay914** [comment]
![image](https://user-images.githubusercontent.com/6037435/92326793-5f661c00-f087-11ea-8012-16f53abe9683.png)
seata-spring-boot-starter is **2.1.10.RELEASE**

**Comment by YClimb** [comment]
> I have the save issue in using docker-compose.
> 
> the docker-compose.yml file is below
> 
> ```
>   
> services:
> 
>   seata-server:
>     image: seataio/seata-server:1.3.0
>     hostname: gtmall-seata-server
>     ports:
>       - 8091:8091
>     environment:
>       - SEATA_PORT=8091
>       - SEATA_CONFIG_NAME=file:/usr/local/data/seata/conf/resources/registry
>     expose:
>       - 8091
> ```
> 
> and the registry.conf file
> 
> ```
>   # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
>   type = "nacos"
> 
>   nacos {
>     application = "seata-server"
>     serverAddr = "10.13.10.212:8848"
>     group = "SEATA_GROUP"
>     namespace = ""
>     cluster = "default"
>     username = ""
>     password = ""
>   }
>   eureka {
>     serviceUrl = "http://localhost:8761/eureka"
>     application = "default"
>     weight = "1"
>   }
>   redis {
>     serverAddr = "localhost:6379"
>     db = 0
>     password = ""
>     cluster = "default"
>     timeout = 0
>   }
>   zk {
>     cluster = "default"
>     serverAddr = "127.0.0.1:2181"
>     sessionTimeout = 6000
>     connectTimeout = 2000
>     username = ""
>     password = ""
>   }
>   consul {
>     cluster = "default"
>     serverAddr = "127.0.0.1:8500"
>   }
>   etcd3 {
>     cluster = "default"
>     serverAddr = "http://localhost:2379"
>   }
>   sofa {
>     serverAddr = "127.0.0.1:9603"
>     application = "default"
>     region = "DEFAULT_ZONE"
>     datacenter = "DefaultDataCenter"
>     cluster = "default"
>     group = "SEATA_GROUP"
>     addressWaitTime = "3000"
>   }
>   file {
>     name = "file.conf"
>   }
> }
> 
> config {
>   # file、nacos 、apollo、zk、consul、etcd3
>   type = "nacos"
> 
>   nacos {
>     serverAddr = "10.13.10.212:8848"
>     namespace = ""
>     group = "SEATA_GROUP"
>     username = ""
>     password = ""
>   }
>   consul {
>     serverAddr = "127.0.0.1:8500"
>   }
>   apollo {
>     appId = "seata-server"
>     apolloMeta = "http://192.168.1.204:8801"
>     namespace = "application"
>   }
>   zk {
>     serverAddr = "127.0.0.1:2181"
>     sessionTimeout = 6000
>     connectTimeout = 2000
>     username = ""
>     password = ""
>   }
>   etcd3 {
>     serverAddr = "http://localhost:2379"
>   }
>   file {
>     name = "file.conf"
>   }
> }
> ```
> 
> the error message
> 
> ```
> Starting seata_seata-server_1 ... done
> Attaching to seata_seata-server_1
> seata-server_1  | 2020-08-31 07:48:23.276  INFO --- [           main] io.seata.server.Server                   : The server is running in container.
> seata-server_1  | Exception in thread "main" io.seata.common.exception.NotSupportYetException: config type can not be null
> seata-server_1  |       at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:106)
> seata-server_1  |       at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:90)
> seata-server_1  |       at io.seata.server.ParameterParser.init(ParameterParser.java:87)
> seata-server_1  |       at io.seata.server.ParameterParser.<init>(ParameterParser.java:60)
> seata-server_1  |       at io.seata.server.Server.main(Server.java:72)
> seata_seata-server_1 exited with code 1
> ```

使用 docker-compose.yaml 时，需要 SEATA_CONFIG_NAME=file:/root/seata-config/registry(docker目录)；
然后再下面再使用 volumes: - /本地目录/config:/root/seata-config

**Comment by jiekexu** [comment]
请问解决了吗

**Comment by vwer** [comment]
请问最后解决了吗

**Comment by dubaoliang834** [comment]
我也遇到了这个问题；我这里的原因是把registry.conf和file.conf放到了项目根目录下的resources文件下，把这俩配置文件放到src/main/resources下就可以正常运行了。

**Comment by baoyinlei** [comment]
```
<dependency>
        <groupId>io.seata</groupId>
        <artifactId>seata-spring-boot-starter</artifactId>
        <version>最新版</version>
</dependency>
<dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
        <version>2.2.1.RELEASE</version>
        <exclusions>
            <exclusion>
                <groupId>io.seata</groupId>
                <artifactId>seata-spring-boot-starter</artifactId>
            </exclusion>
        </exclusions>
</dependency>
```

**Comment by dshengping** [comment]
这个问题是怎么解决的。我也是这个问题。

**Comment by fzy-Line** [comment]
遇到了同样的问题，请问最后是怎么解决的？

**Comment by lvxianzheng** [comment]
我遇到的问题原因：
默认是读取resource/registry.conf，如果src/下这个文件没有重新编译打包，这个文件可能没有复制到 target/classes目录下
解决办法：重新打包 maven package

**Comment by suinxinliulang** [comment]
貌似使用docker-compose启动需要将registry.conf先放到指定的那个目录里，貌似不会自动将配置文件自动复制出来，而且进去发现`/root/seata-server/`空空如也，然后就不会报错了并且nacos上也出现了seata的服务

**Comment by czq3** [comment]
没解决






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "seata/seata"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年1月13日(星期三) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [seata/seata] 使用application.yml配置registry, 报io.seata.common.exception.NotSupportYetException: config type can not be null (#2959)





 
遇到了同样的问题，请问最后是怎么解决的？

**Comment by czq3** [comment]
没有用docker




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "seata/seata"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月1日(星期一) 晚上9:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [seata/seata] 使用application.yml配置registry, 报io.seata.common.exception.NotSupportYetException: config type can not be null (#2959)





 
貌似使用docker-compose启动需要将registry.conf先放到指定的那个目录里，貌似不会自动将配置文件自动复制出来，而且进去发现/root/seata-server/空空如也，然后就不会报错了并且nacos上也出现了seata的服务

**Comment by fankuizhi** [comment]
setat-all的依赖没有把META-INF/services/io.seata.config.ExtConfigurationProvider文件加进来，所以用SpringBootConfigurationProvider来加载配置，要将依赖改为
`
           <dependency>
                <groupId>io.seata</groupId>
                <artifactId>seata-spring-boot-starter</artifactId>
                <version>${seata.version}</version>
            </dependency>
`

**Comment by iockx** [comment]
20年的问题 现在还是老样子
