### ISSUE TITLE
XA模式下数据一致性问题

### ISSUE THREAD

**Issue by nimeijian** [seata/seata#2971]
我们先来看两段代码，关于TC端发起全局事务提交以及XA模式下RM端是如何处理的：
1.TC端全局提交：
``` 
public class DefaultCore implements Core {
    public boolean doGlobalCommit(GlobalSession globalSession, boolean retrying) throws TransactionException {
        boolean success = true;
        // start committing event
        eventBus.post(new GlobalTransactionEvent(globalSession.getTransactionId(), GlobalTransactionEvent.ROLE_TC,
            globalSession.getTransactionName(), globalSession.getBeginTime(), null, globalSession.getStatus()));

        if (globalSession.isSaga()) {
            success = getCore(BranchType.SAGA).doGlobalCommit(globalSession, retrying);
        } else {
            for (BranchSession branchSession : globalSession.getSortedBranches()) {
                BranchStatus currentStatus = branchSession.getStatus();
                if (currentStatus == BranchStatus.PhaseOne_Failed) {
                    globalSession.removeBranch(branchSession);
                    continue;
                }
                try {
                    BranchStatus branchStatus = getCore(branchSession.getBranchType()).branchCommit(globalSession, branchSession);

                    switch (branchStatus) {
                        case PhaseTwo_Committed:
                            globalSession.removeBranch(branchSession);
                            continue;
                        case PhaseTwo_CommitFailed_Unretryable:
                            if (globalSession.canBeCommittedAsync()) {
                                LOGGER.error(
                                    "Committing branch transaction[{}], status: PhaseTwo_CommitFailed_Unretryable, please check the business log.", branchSession.getBranchId());
                                continue;
                            } else {
                                SessionHelper.endCommitFailed(globalSession);
                                LOGGER.error("Committing global transaction[{}] finally failed, caused by branch transaction[{}] commit failed.", globalSession.getXid(), branchSession.getBranchId());
                                return false;
                            }
                        default:
                            if (!retrying) {
                                globalSession.queueToRetryCommit();
                                return false;
                            }
                            if (globalSession.canBeCommittedAsync()) {
                                LOGGER.error("Committing branch transaction[{}], status:{} and will retry later",
                                    branchSession.getBranchId(), branchStatus);
                                continue;
                            } else {
                                LOGGER.error(
                                    "Committing global transaction[{}] failed, caused by branch transaction[{}] commit failed, will retry later.", globalSession.getXid(), branchSession.getBranchId());
                                return false;
                            }
                    }
                } catch (Exception ex) {
                    StackTraceLogger.error(LOGGER, ex, "Committing branch transaction exception: {}",
                        new String[] {branchSession.toString()});
                    if (!retrying) {
                        globalSession.queueToRetryCommit();
                        throw new TransactionException(ex);
                    }
                }
            }
            if (globalSession.hasBranch()) {
                LOGGER.info("Committing global transaction is NOT done, xid = {}.", globalSession.getXid());
                return false;
            }
        }
        if (success) {
            SessionHelper.endCommitted(globalSession);

            // committed event
            eventBus.post(new GlobalTransactionEvent(globalSession.getTransactionId(), GlobalTransactionEvent.ROLE_TC,
                globalSession.getTransactionName(), globalSession.getBeginTime(), System.currentTimeMillis(),
                globalSession.getStatus()));

            LOGGER.info("Committing global transaction is successfully done, xid = {}.", globalSession.getXid());
        }
        return success;
    }
}
```
2.XA模式下RM端 branchCommit：
```
public class ResourceManagerXA extends AbstractDataSourceCacheResourceManager {
    private BranchStatus finishBranch(boolean committed, BranchType branchType, String xid, long branchId, String resourceId,
                                       String applicationData) throws TransactionException {
        XAXid xaBranchXid = XAXidBuilder.build(xid, branchId);
        Resource resource = dataSourceCache.get(resourceId);
        if (resource instanceof AbstractDataSourceProxyXA) {
            try (ConnectionProxyXA connectionProxyXA = ((AbstractDataSourceProxyXA)resource).getConnectionForXAFinish(xaBranchXid)) {
                **if (committed) {
                    connectionProxyXA.xaCommit(xid, branchId, applicationData);
                    LOGGER.info(xaBranchXid + " was committed.");
                    return BranchStatus.PhaseTwo_Committed;
                }** else {
                    connectionProxyXA.xaRollback(xid, branchId, applicationData);
                    LOGGER.info(xaBranchXid + " was rolled back.");
                    return BranchStatus.PhaseTwo_Rollbacked;
                }
            } catch (XAException | SQLException sqle) {
                if (committed) {
                    LOGGER.info(xaBranchXid + " commit failed since " + sqle.getMessage(), sqle);
                    // FIXME: case of PhaseTwo_CommitFailed_Unretryable
                    return BranchStatus.PhaseTwo_CommitFailed_Retryable;
                } else {
                    LOGGER.info(xaBranchXid + " rollback failed since " + sqle.getMessage(), sqle);
                    // FIXME: case of PhaseTwo_RollbackFailed_Unretryable
                    return BranchStatus.PhaseTwo_RollbackFailed_Retryable;
                }
            }
        } else {
            LOGGER.error("Unknown Resource for XA resource " + resourceId + " " + resource);
            if (committed) {
                return BranchStatus.PhaseTwo_CommitFailed_Unretryable;
            } else {
                return BranchStatus.PhaseTwo_RollbackFailed_Unretryable;
            }
        }
    }
}
```
我们关注RM端加粗的代码：
```
if (committed) {
    connectionProxyXA.xaCommit(xid, branchId, applicationData);
    LOGGER.info(xaBranchXid + " was committed.");
    return BranchStatus.PhaseTwo_Committed;
}
```
假设这里成功执行了xaCommit， 但TC端报TimeoutException，则会结束本次retryCommitting任务，不再给其它分支事务发送BranchCommitRequest请求，1s后会再次进入retryCommitting任务，这次该分支会报com.mysql.jdbc.jdbc2.optional.MysqlXAException: XAER_NOTA: Unknown XID异常，然后TC端进入 switch 的 default 分支并返回false，仍然不再执行本全局事务的其它分支事务，永远走不到 SessionHelper.endCommitted(globalSession)，那么该全局事务的事务日志会一直存在于branch_table和global_table中，TC端会一直捞出来重试，TC和RM端也会一直报错，并导致事务一致性问题。其异常堆栈分别为：
TC端：
```
ERROR --- [yCommitting_1_1] io.seata.server.coordinator.DefaultCore  : Committing global transaction[172.36.1.96:18091:33960714003550208] failed, caused by branch transaction[33960715031154689] commit failed, will retry later.
```
RM端：
```
com.mysql.jdbc.jdbc2.optional.MysqlXAException: XAER_NOTA: Unknown XID
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:583) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:568) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.commit(MysqlXAConnection.java:545) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at io.seata.rm.datasource.xa.ConnectionProxyXA.xaCommit(ConnectionProxyXA.java:95) ~[classes/:na]
	at io.seata.rm.datasource.xa.ResourceManagerXA.finishBranch(ResourceManagerXA.java:68) [classes/:na]
	at io.seata.rm.datasource.xa.ResourceManagerXA.branchCommit(ResourceManagerXA.java:52) [classes/:na]
	at io.seata.rm.AbstractRMHandler.doBranchCommit(AbstractRMHandler.java:98) [classes/:na]
	at io.seata.rm.AbstractRMHandler$1.execute(AbstractRMHandler.java:54) [classes/:na]
	at io.seata.rm.AbstractRMHandler$1.execute(AbstractRMHandler.java:50) [classes/:na]
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116) [classes/:na]
	at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:50) [classes/:na]
	at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:58) [classes/:na]
	at io.seata.core.protocol.transaction.BranchCommitRequest.handle(BranchCommitRequest.java:35) [classes/:na]
	at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150) [classes/:na]
	at io.seata.core.rpc.processor.client.RmBranchCommitProcessor.handleBranchCommit(RmBranchCommitProcessor.java:63) [classes/:na]
	at io.seata.core.rpc.processor.client.RmBranchCommitProcessor.process(RmBranchCommitProcessor.java:58) [classes/:na]
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:261) [classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_211]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_211]
Caused by: java.sql.SQLException: XAER_NOTA: Unknown XID
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:829) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:729) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:562) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	... 19 common frames omitted

```

该问题可以如下重现以模拟Timeout：
在RM端的上述ResourceManagerXA类的如下几行打断点，等待一会儿，TC端就会catch到TimeoutException，然后出现上述问题：
```
connectionProxyXA.xaCommit(xid, branchId, applicationData);
LOGGER.info(xaBranchXid + " was committed.");
return BranchStatus.PhaseTwo_Committed;
```

**Comment by a364176773** [comment]
@sharajava please pay attention to this problem

**Comment by sharajava** [comment]
是的，目前 XA 模式的异常处理不完善。根本上说 RM 和 TC 的交互需要更明确的含义，比如，上述情况下 RM 分支提交时的 XAER_NOTA: Unknown XID 应该进一步解析上下文，反馈给 TC 该分支已经提交，TC 不必再重试。

**Comment by a364176773** [comment]
are you willing to deal with this problem?

**Comment by a364176773** [comment]
这个问题暂时交给我吧，如果有兴趣认领的可以联系我
