### ISSUE TITLE
docker部署使用自定义配置文件后文件，无法启动镜像config type can not be null

### ISSUE THREAD

**Issue by 418545106** [seata/seata#3034]
在使用docker部署镜像启动，按照文档上的命令
```
$ docker run --name seata-server \
        -p 8091:8091 \
        -e SEATA_CONFIG_NAME=file:/root/seata-config/registry \
        -v /User/seata/config:/root/seata-config  \
        seataio/seata-server
```
我的服务器系统是centos7 我在 /root/seata-config 文件夹下放置了 registry.conf 和 file.conf 
registry.conf的配置也是按照文档上要求配置
```
config {
  type = "file"

  file {
    name = "file:/root/seata-config/file.conf"
  }
}
```
然后启动镜像就闪退，并且logs里面信息只有如下所示
```

[0.001s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/var/log/seata_gc.log instead.
[0.009s][info   ][gc] Using G1
2020-08-18 03:55:36.429  INFO --- [           main] io.seata.server.Server                   : The server is running in container.
Exception in thread "main" io.seata.common.exception.NotSupportYetException: config type can not be null
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:106)
	at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:90)
	at io.seata.server.ParameterParser.init(ParameterParser.java:87)
	at io.seata.server.ParameterParser.<init>(ParameterParser.java:60)
	at io.seata.server.Server.main(Server.java:72)

```

**Comment by a364176773** [comment]
没读到你的配置，并且不支持name = "file:/root/seata-config/file.conf"

**Comment by 418545106** [comment]
请问一下我该如何解决这个问题，因为我之前都是按照官方文档上给的步骤操作的。

**Comment by a364176773** [comment]
> 请问一下我该如何解决这个问题，因为我之前都是按照官方文档上给的步骤操作的。

直接用环境变量，或者从容器外编辑好文件cp进去

**Comment by slievrly** [comment]
@418545106 `/root/seata-config/registry` include registry.conf ?

**Comment by 418545106** [comment]
include

**Comment by 418545106** [comment]
```Dockerfile
FROM seataio/seata-server

COPY registry.conf /seata-server/resources/registry.conf

COPY file.conf /seata-server/resources/file.conf

EXPOSE 8091

```
最后自己重新封装了镜像运行
