### ISSUE TITLE
获取锁失败会重复注册分支问题

### ISSUE THREAD

**Issue by yougecn** [seata/seata#3039]
1、环境
client是1.3 release；tc端是1.4.0-SNAPSHOT
2、问题描述
store mode是redis时存在重复注册问题；
store mode是file、db时正常
调用场景：
A服务无数据库，开启分布式事务，调用远程B服务，再调用远程C服务；
其中A服务有嵌套本地事务，两个事务操作不同的表

3、日志
**tc的日志**
[2m2020-08-18 11:38:56.230[0;39m [31mERROR[0;39m [2m---[0;39m [2m[rThread_1_5_500][0;39m [36mi.s.c.e.AbstractExceptionHandler        [0;39m [2m:[0;39m Catch TransactionException while do RPC, request: xid=192.168.44.1:8091:38951387203112960,branchType=AT,resourceId=jdbc:mysql://127.0.0.1:3306/cs,lockKey=t_zz:e42e8994674943c190567b4e983d2ad0;t_zz:05e20bec135044b18ce1df891535986b;t_zz:3d7f86f694b14b84911e26e4452f888b;t_zz:d14896a0fd3041ecb45626c46f44454d;t1:123;t_zz:001becd7117f49b78cd14009e10e5105
==>
io.seata.core.exception.BranchTransactionException: Global lock acquire failed xid = 192.168.44.1:8091:38951387203112960 branchId = 38951394824163328
        at io.seata.server.transaction.at.ATCore.branchSessionLock(ATCore.java:48)
        at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:77)
        at io.seata.server.storage.redis.session.RedisSessionManager.lockAndExecute(RedisSessionManager.java:194)
        at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:275)
        at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:72)
        at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:97)
        at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:192)
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184)
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179)
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116)
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179)
        at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:427)
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:116)
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77)
        at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
<==

[2m2020-08-18 11:38:56.253[0;39m [32m INFO[0;39m [2m---[0;39m [2m[LoggerPrint_1_1][0;39m [36mi.s.c.r.p.server.BatchLogHandler        [0;39m [2m:[0;39m SeataMergeMessage xid=192.168.44.1:8091:38951387203112960,branchType=AT,resourceId=jdbc:mysql://127.0.0.1:3306/cs,lockKey=t_zz:e42e8994674943c190567b4e983d2ad0;t_zz:05e20bec135044b18ce1df891535986b;t_zz:3d7f86f694b14b84911e26e4452f888b;t_zz:d14896a0fd3041ecb45626c46f44454d;t1:123;t_zz:001becd7117f49b78cd14009e10e5105
,clientIp:127.0.0.1,vgroup:my_test_tx_group
[2m2020-08-18 11:38:56.255[0;39m [31mERROR[0;39m [2m---[0;39m [2m[rThread_1_6_500][0;39m [36mi.s.c.e.AbstractExceptionHandler        [0;39m [2m:[0;39m Catch TransactionException while do RPC, request: xid=192.168.44.1:8091:38951387203112960,branchType=AT,resourceId=jdbc:mysql://127.0.0.1:3306/cs,lockKey=t_zz:e42e8994674943c190567b4e983d2ad0;t_zz:05e20bec135044b18ce1df891535986b;t_zz:3d7f86f694b14b84911e26e4452f888b;t_zz:d14896a0fd3041ecb45626c46f44454d;t1:123;t_zz:001becd7117f49b78cd14009e10e5105
==>
io.seata.core.exception.BranchTransactionException: Global lock acquire failed xid = 192.168.44.1:8091:38951387203112960 branchId = 38951395017101313
        at io.seata.server.transaction.at.ATCore.branchSessionLock(ATCore.java:48)
        at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:77)
        at io.seata.server.storage.redis.session.RedisSessionManager.lockAndExecute(RedisSessionManager.java:194)
        at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:275)
        at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:72)
        at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:97)
        at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:192)
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184)
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179)
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116)
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179)
        at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:427)
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:116)
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77)
        at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
<==

**Comment by a364176773** [comment]
已定位到问题，我会跟进

**Comment by dongfsgf** [comment]
> 已定位到问题，我会跟进

@a364176773  啥问题啊，我也遇到了
