### ISSUE TITLE
分支事务不能注册到全局session 中

### ISSUE THREAD

**Issue by wangfy1989** [seata/seata#3094]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
==>
io.seata.core.exception.GlobalTransactionException: Could not register branch into global session xid = 192.168.1.249:8091:46691762445512704 status = AsyncCommitting, cause by globalSession not active
	at io.seata.server.coordinator.AbstractCore.globalSessionStatusCheck(AbstractCore.java:96) ~[classes/:na]
	at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:73) ~[classes/:na]
	at io.seata.server.storage.file.session.FileSessionManager.lockAndExecute(FileSessionManager.java:135) ~[classes/:na]
	at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:275) ~[classes/:na]
	at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:72) ~[classes/:na]
	at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:97) ~[classes/:na]
	at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:192) ~[classes/:na]
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184) ~[classes/:na]
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179) ~[classes/:na]
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116) ~[seata-core-1.4.0-SNAPSHOT.jar:na]
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179) ~[classes/:na]
	at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136) ~[seata-core-1.4.0-SNAPSHOT.jar:na]
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:427) ~[classes/:na]
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:124) ~[seata-core-1.4.0-SNAPSHOT.jar:na]
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77) ~[seata-core-1.4.0-SNAPSHOT.jar:na]
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:265) ~[seata-core-1.4.0-SNAPSHOT.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
<==
2020-09-08 12:16:39.307 ERROR --- [Thread_1_33_500] i.s.c.e.AbstractExceptionHandler         : Catch TransactionException while do RPC, request: xid=192.168.1.249:8091:46691762445512704,branchType=AT,resourceId=jdbc:mysql://localhost:3306/test,lockKey=yf_store_spu:26;yf_store_ro:42;yf_store:41;yf_log_operation:1599567395000;yf_store_price:33;yf_store_room_type:27;yf_image:41;yf_store_room_sku:2020090800000100000026,2020090900000100000026,2020091000000100000026,2020091100000100000026,2020091200000100000026,2020091300000100000026,2020091400000100000026,2020091500000100000026,2020091600000100000026,2020091700000100000026,2020091800000100000026,2020091900000100000026,2020092000000100000026,2020092100000100000026,2020092200000100000026,2020092300000100000026,2020092400000100000026,2020092500000100000026,2020092600000100000026,2020092700000100000026,2020092800000100000026,2020092900000100000026,2020093000000100000026,2020100100000100000026,2020100200000100000026,2020100300000100000026,2020100400000100000026,2020100500000100000026,2020100600000100000026,2020100700000100000026,2020100800000100000026,2020100900000100000026,2020101000000100000026,2020101100000100000026,2020101200000100000026,2020101300000100000026,2020101400000100000026,2020101500000100000026,2020101600000100000026,2020101700000100000026,2020101800000100000026,2020101900000100000026,2020102000000100000026,2020102100000100000026,2020102200000100000026,2020102300000100000026,2020102400000100000026,2020102500000100000026,2020102600000100000026,2020102700000100000026,2020102800000100000026,2020102900000100000026,2020103000000100000026,2020103100000100000026,2020110100000100000026,2020110200000100000026,2020110300000100000026,2020110400000100000026,2020110500000100000026,2020110600000100000026,2020110700000100000026,2020110800000100000026,2020110900000100000026,2020111000000100000026,2020111100000100000026,2020111200000100000026,2020111300000100000026,2020111400000100000026,2020111500000100000026,2020111600000100000026,2020111700000100000026,2020111800000100000026,2020111900000100000026,2020112000000100000026,2020112100000100000026,2020112200000100000026,2020112300000100000026,2020112400000100000026,2020112500000100000026,2020112600000100000026,2020112700000100000026,2020112800000100000026,2020112900000100000026,2020113000000100000026,2020120100000100000026,2020120200000100000026,2020120300000100000026,2020120400000100000026,2020120500000100000026,2020120600000100000026,2020120700000100000026,2020120800000100000026,2020120900000100000026,2020121000000100000026,2020121100000100000026,2020121200000100000026,2020121300000100000026,2020121400000100000026,2020121500000100000026,2020121600000100000026,2020121700000100000026,2020121800000100000026,2020121900000100000026,2020122000000100000026,2020122100000100000026,2020122200000100000026,2020122300000100000026,2020122400000100000026,2020122500000100000026,2020122600000100000026,2020122700000100000026,2020122800000100000026,2020122900000100000026,2020123000000100000026,2020123100000100000026,2021010100000100000026,2021010200000100000026,2021010300000100000026,2021010400000100000026,2021010500000100000026,2021010600000100000026,2021010700000100000026,2021010800000100000026,2021010900000100000026,2021011000000100000026,2021011100000100000026,2021011200000100000026,2021011300000100000026,2021011400000100000026,2021011500000100000026,2021011600000100000026,2021011700000100000026,2021011800000100000026,2021011900000100000026,2021012000000100000026,2021012100000100000026,2021012200000100000026,2021012300000100000026,2021012400000100000026,2021012500000100000026,2021012600000100000026,2021012700000100000026,2021012800000100000026,2021012900000100000026,2021013000000100000026,2021013100000100000026,2021020100000100000026,2021020200000100000026,2021020300000100000026,2021020400000100000026,2021020500000100000026,2021020600000100000026,2021020700000100000026,2021020800000100000026,2021020900000100000026,2021021000000100000026,2021021100000100000026,2021021200000100000026,2021021300000100000026,2021021400000100000026,2021021500000100000026,2021021600000100000026,2021021700000100000026,2021021800000100000026,2021021900000100000026,2021022000000100000026,2021022100000100000026,2021022200000100000026,2021022300000100000026,2021022400000100000026,2021022500000100000026,2021022600000100000026,2021022700000100000026,2021022800000100000026,2021030100000100000026,2021030200000100000026,2021030300000100000026,2021030400000100000026,2021030500000100000026,2021030600000100000026;yf_store_room_servers:11

**Comment by a364176773** [comment]
保证你的服务不会自动重试，导致出现幂等性问题，这个是为了防止全局事务已经到了二阶段以后还有一阶段的事务去注册，保证了全局事务的一致性

**Comment by wangfy1989** [comment]
> 保证你的服务不会自动重试，导致出现幂等性问题，这个是为了防止全局事务已经到了二阶段以后还有一阶段的事务去注册，保证了全局事务的一致性

那么请教您， 我该怎么修复这个报错？
