### ISSUE TITLE
mybatis plus代理数据源后启动报错

### ISSUE THREAD

**Issue by maodunluoxuan** [seata/seata#3099]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
代理数据源后启动报错

### Ⅱ. Describe what happened

```
Caused by: io.seata.common.exception.ShouldNeverHappenException: Can't find any object of class org.springframework.context.ApplicationContext
	at io.seata.common.holder.ObjectHolder.lambda$getObject$0(ObjectHolder.java:40)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.seata.common.holder.ObjectHolder.getObject(ObjectHolder.java:40)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:93)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$100(SpringBootConfigurationProvider.java:43)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:56)
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>)
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:101)
	at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:90)
	at io.seata.rm.datasource.DataSourceProxy.<clinit>(DataSourceProxy.java:57)
	... 139 common frames omitted
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by wangliang181230** [comment]
bean加载优先级问题。
你是不是自己创建的AT代理数据源？

**Comment by maodunluoxuan** [comment]
> bean加载顺序问题。
> 你是不是自己创建的AT代理数据源？
> 如果是的话，请在配置类上添加`@AutoConfigureAfter(SeataAutoConfiguration.class)`。

谢谢，确实是加载顺序的问题，shiro先加载引起的
