### ISSUE TITLE
fileListener execute error:null

### ISSUE THREAD

**Issue by ricky0215** [seata/seata#3135]
2020-09-21 18:59:27.791 ERROR 10672 --- [ileListener_2_1] io.seata.config.FileConfiguration        : fileListener execute error:null

**Comment by slievrly** [comment]
@ricky0215 pls upgrade seata dependency to 1.3.0

**Comment by subenkun** [comment]
1.3.0同样存在此问题

**Comment by mac8088** [comment]
1.4.0 也有类似问题。

2020-11-05 14:56:12.305 ERROR 15604 --- [ileListener_3_1] io.seata.config.FileConfiguration        : fileListener execute error, dataId :service.disableGlobalTransaction

java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.seata.config.ConfigurationCache.lambda$proxy$1(ConfigurationCache.java:95)
	at io.seata.config.Configuration$$EnhancerByCGLIB$$95b52655.getLatestConfig(<generated>)
	at io.seata.config.FileConfiguration$FileListener.onChangeEvent(FileConfiguration.java:365)
	at io.seata.config.ConfigurationChangeListener.lambda$onProcessEvent$0(ConfigurationChangeListener.java:62)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getLatestConfig(<generated>)
	... 14 common frames omitted

**Comment by ls9527** [comment]
> cannot

检查 service.disableGlobalTransaction的值是不是布尔值， 如果是的话， 检查空格。  

这个错误看起来是你在运行时修改了配置.  但是结果不是布尔值

**Comment by mac8088** [comment]
service {
  #transaction service group mapping
  vgroupMapping.adm-txgroup = "seata"
  #degrade, current not support
  enableDegrade = false
  #disable seata
  disableGlobalTransaction = false
}

我觉得配置没有啥毛病吧？

@ls9527

**Comment by ls9527** [comment]
> service {
> #transaction service group mapping
> vgroupMapping.adm-txgroup = "seata"
> #degrade, current not support
> enableDegrade = false
> #disable seata
> disableGlobalTransaction = false
> }
> 
> 我觉得配置没有啥毛病吧？
> 
> @ls9527

发一下JDK的详细版本。  还有确认一下seata依赖的所有依赖1.4.0.    保证项目的seata版本是一致的

**Comment by ls9527** [comment]
> service {
> #transaction service group mapping
> vgroupMapping.adm-txgroup = "seata"
> #degrade, current not support
> enableDegrade = false
> #disable seata
> disableGlobalTransaction = false
> }
> 
> 我觉得配置没有啥毛病吧？
> 
> @ls9527

发一下JDK的详细版本。  还有确认一下seata依赖的所有依赖1.4.0.    保证项目的seata版本是一致的

**Comment by 781797330** [comment]
13:27:07.483 [fileListener_3_1] ERROR i.s.c.FileConfiguration - [onChangeEvent,325] - fileListener execute error:null
13:27:07.483 [fileListener_2_1] ERROR i.s.c.FileConfiguration - [onChangeEvent,325] - fileListener execute error:null

**Comment by wsq93** [comment]
我也遇到了这个问题，不过我这边搭建的情况找到处理方法了。我用的nacos-server是2.0.3版本，seata-server是1.4.2版本，项目搭建时使用了spring-boot-devtools，一改代码就重新自动启动了，然后这个服务控制台之后打印的内容就出现这个死循环。经过一番测试，后来发现要去掉spring-boot-devtools，然后只要到nacos监控页面刷新一下服务列表 等待服务健康状态刷新之后就OK了！

**Comment by caofanqi** [comment]
我报这个错误的原因是，因为启动了dubbo-admin，与它里面的dubbo.protocol.port重复了，我也是醉了

**Comment by lostspirit2022** [comment]
监听函数重名

**Comment by mkerj** [comment]
[fileListener_1_1] ERROR i.s.c.FileConfiguration - [onChangeEvent,325] - fileListener execute error:null。我也是这个错误。在windows上用maven打包上传到linux服务器上没有问题。在jenkins下打包上传到生产服务器就报错。打包的java 1.8u202版本是一样的。

**Comment by ricky0215** [comment]
您好，您的来信我已经收到，我会尽快给您回复的。
