### ISSUE TITLE
bug:JedisDataException: WRONGTYPE Operation against a key holding the wrong kind of value at 

### ISSUE THREAD

**Issue by lightClouds917** [seata/seata#3149]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

the lock has this key,it is a name of hash:
private static final String DEFAULT_REDIS_SEATA_GLOBAL_LOCK_PREFIX = "SEATA_GLOBAL_LOCK";
the session has this key,it is a name of string:
private static final String DEFAULT_REDIS_SEATA_GLOBAL_PREFIX = "SEATA_GLOBAL_";

They have the same prefix :SEATA_GLOBAL_
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
redis.clients.jedis.exceptions.JedisDataException: WRONGTYPE Operation against a key holding the wrong kind of value
	at redis.clients.jedis.Protocol.processError(Protocol.java:132)
	at redis.clients.jedis.Protocol.process(Protocol.java:166)
	at redis.clients.jedis.Protocol.read(Protocol.java:220)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318)
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:255)
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:245)
	at redis.clients.jedis.Jedis.get(Jedis.java:181)
	at io.seata.server.storage.redis.store.RedisTransactionStoreManager.readSession(RedisTransactionStoreManager.java:230)
	at io.seata.server.storage.redis.store.RedisTransactionStoreManager.readSession(RedisTransactionStoreManager.java:290)
	at io.seata.server.storage.redis.session.RedisSessionManager.findGlobalSessions(RedisSessionManager.java:188)
	at io.seata.server.storage.redis.session.RedisSessionManager.allSessions(RedisSessionManager.java:178)
	at io.seata.server.coordinator.DefaultCoordinator.timeoutCheck(DefaultCoordinator.java:216)
	at io.seata.server.coordinator.DefaultCoordinator.lambda$init$20(DefaultCoordinator.java:404)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at 
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by lightClouds917** [comment]
https://github.com/seata/seata/pull/3148
