### ISSUE TITLE
将seata服務连接的库中表字段 application_data 类型改成 text 类型

### ISSUE THREAD

**Issue by handsomeLinzr** [seata/seata#3154]
## Why you need it?
在用seata的tcc模式时候，有时候会出现保存到 application_data 的数据过大，导致错误：
io.seata.core.exception.BranchTransactionException: Failed to store branch xid = 10.42.6.150:8091:53523771501928448 branchId = 53523773443891201 
	at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:83) ~[classes/:na] 
	at io.seata.server.storage.db.session.DataBaseSessionManager.lockAndExecute(DataBaseSessionManager.java:197) ~[classes/:na] 
	at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:275) ~[classes/:na] 
	at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:72) ~[classes/:na] 
	at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:97) ~[classes/:na] 
	at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:192) [classes/:na] 
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184) ~[classes/:na] 
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179) ~[classes/:na] 
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116) ~[seata-core-1.3.0.jar:na] 
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179) [classes/:na] 
	at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136) [seata-core-1.3.0.jar:na] 
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:427) [classes/:na] 
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:124) [seata-core-1.3.0.jar:na] 
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77) [seata-core-1.3.0.jar:na] 
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:265) [seata-core-1.3.0.jar:na] 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212] 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212] 
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final] 
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212] 
Caused by: io.seata.common.exception.StoreException: Data truncation: Data too long for column 'application_data' at row 1 
	at io.seata.server.storage.db.store.LogStoreDataBaseDAO.insertBranchTransactionDO(LogStoreDataBaseDAO.java:329) ~[classes/:na] 
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.writeSession(DataBaseTransactionStoreManager.java:110) ~[classes/:na] 
	at io.seata.server.storage.db.session.DataBaseSessionManager.addBranchSession(DataBaseSessionManager.java:130) ~[classes/:na] 
	at io.seata.server.session.AbstractSessionManager.onAddBranch(AbstractSessionManager.java:133) ~[classes/:na] 
	at io.seata.server.session.GlobalSession.addBranch(GlobalSession.java:241) ~[classes/:na] 
	at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:79) ~[classes/:na] 
	... 18 common frames omitted 
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'application_data' at row 1 
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3833) ~[mysql-connector-java-5.1.35.jar:5.1.35] 
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771) ~[mysql-connector-java-5.1.35.jar:5.1.35] 
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.35.jar:5.1.35] 
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.35.jar:5.1.35] 
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535) ~[mysql-connector-java-5.1.35.jar:5.1.35] 
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911) ~[mysql-connector-java-5.1.35.jar:5.1.35] 
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145) ~[mysql-connector-java-5.1.35.jar:5.1.35] 
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081) ~[mysql-connector-java-5.1.35.jar:5.1.35] 
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066) ~[mysql-connector-java-5.1.35.jar:5.1.35] 
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:256) ~[druid-1.1.12.jar:1.1.12] 
	at io.seata.server.storage.db.store.LogStoreDataBaseDAO.insertBranchTransactionDO(LogStoreDataBaseDAO.java:327) ~[classes/:na] 
	... 23 common frames omitted 
<== 
想要将其中 application_data 字段的类型给为text，大大增加保存到这个字段的长度

## How it could be?
修改seata服务连接的数据库中表的字段application_data 的类型，改成 text 

## Other related information
无

**Comment by slievrly** [comment]
@handsomeLinzr even if this field is changed to text, there may still be a length requirement beyond the text type, so change this to suit your business needs.

**Comment by liangyao375** [comment]
那这种情况该如何解决呢？
