### ISSUE TITLE
并发下由于主键冲突创建分支事务失败

### ISSUE THREAD

**Issue by GraceYuan** [seata/seata#3193]
在并发测试的时候，Seata server 1.3.0报错，大概是因为insertBranchTransactionDO时，主键已存在导致的，请问怎么办

以下为相关log

2020-10-15 10:58:47.157 ERROR --- [ServerHandlerThread_1_40_500] i.s.c.e.AbstractExceptionHandler         : Catch TransactionException while do RPC, request: xid=192.168.2.101:8091:59959786489253888,branchType=AT,resourceId=jdbc:mysql://192.168.2.12:3360/seata_account,lockKey=account:1
==>
io.seata.core.exception.BranchTransactionException: Failed to store branch xid = 192.168.2.101:8091:59959786489253888 branchId = 59959786711552001
        at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:83) ~[seata-server-1.3.0.jar:na]
        at io.seata.server.storage.db.session.DataBaseSessionManager.lockAndExecute(DataBaseSessionManager.java:197) ~[seata-server-1.3.0.jar:na]
        at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:275) ~[seata-server-1.3.0.jar:na]
        at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:72) ~[seata-server-1.3.0.jar:na]
        at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:97) ~[seata-server-1.3.0.jar:na]
        at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:192) [seata-server-1.3.0.jar:na]
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184) ~[seata-server-1.3.0.jar:na]
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179) ~[seata-server-1.3.0.jar:na]
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116) ~[seata-core-1.3.0.jar:na]
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179) [seata-server-1.3.0.jar:na]
        at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136) [seata-core-1.3.0.jar:na]
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:427) [seata-server-1.3.0.jar:na]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:124) [seata-core-1.3.0.jar:na]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77) [seata-core-1.3.0.jar:na]
        at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:265) [seata-core-1.3.0.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: io.seata.common.exception.StoreException: Duplicate entry '59959786711552001' for key 'PRIMARY'
        at io.seata.server.storage.db.store.LogStoreDataBaseDAO.insertBranchTransactionDO(LogStoreDataBaseDAO.java:329) ~[seata-server-1.3.0.jar:na]
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.writeSession(DataBaseTransactionStoreManager.java:110) ~[seata-server-1.3.0.jar:na]
        at io.seata.server.storage.db.session.DataBaseSessionManager.addBranchSession(DataBaseSessionManager.java:130) ~[seata-server-1.3.0.jar:na]
        at io.seata.server.session.AbstractSessionManager.onAddBranch(AbstractSessionManager.java:133) ~[seata-server-1.3.0.jar:na]
        at io.seata.server.session.GlobalSession.addBranch(GlobalSession.java:241) ~[seata-server-1.3.0.jar:na]
        at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:79) ~[seata-server-1.3.0.jar:na]
        ... 18 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '59959786711552001' for key 'PRIMARY'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_121]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_121]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_121]

**Comment by slievrly** [comment]
@GraceYuan Are you running multiple seata-server on the same IP address?

**Comment by GraceYuan** [comment]
@slievrly No, three instances run on three virtual machines

**Comment by GraceYuan** [comment]
In the nacos service details, I can see that three instances of the seata-server cluster run on three different IP addresses
