### ISSUE TITLE
seata 使用oracle数据库不同用户下的表 get tablemeta failed

### ISSUE THREAD

**Issue by miqiang1986** [seata/seata#3226]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

springcloud项目。使用的是oracle数据库，连接配置的是A用户，通过A用户给B用户的表中插入数据时报错（A用户有访问B用户从权限）

### Ⅱ. Describe what happened

```
Caused by: org.apache.ibatis.executor.ExecutorException: Error preparing statement.  Cause: io.seata.common.exception.ShouldNeverHappenException: [xid:222.30.195.152:8091:64378890993893376]get tablemeta failed
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:97) ~[mybatis-3.5.5.jar:3.5.5]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59) ~[mybatis-3.5.5.jar:3.5.5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49) ~[mybatis-3.5.5.jar:3.5.5]
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:82) ~[mybatis-plus-extension-3.4.0.jar:3.4.0]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.5.5.jar:3.5.5]
	at com.sun.proxy.$Proxy252.prepare(Unknown Source) ~[na:na]
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:94) ~[mybatis-plus-core-3.4.0.jar:3.4.0]
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:55) ~[mybatis-plus-core-3.4.0.jar:3.4.0]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.5.5.jar:3.5.5]
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:85) ~[mybatis-plus-core-3.4.0.jar:3.4.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49) ~[mybatis-3.5.5.jar:3.5.5]
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:82) ~[mybatis-plus-extension-3.4.0.jar:3.4.0]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.5.5.jar:3.5.5]
	at com.sun.proxy.$Proxy251.update(Unknown Source) ~[na:na]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197) ~[mybatis-3.5.5.jar:3.5.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184) ~[mybatis-3.5.5.jar:3.5.5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) ~[mybatis-spring-2.0.5.jar:2.0.5]
	... 118 common frames omitted
Caused by: io.seata.common.exception.ShouldNeverHappenException [xid:222.30.195.152:8091:64378890993893376]get tablemeta failed
	at io.seata.rm.datasource.sql.struct.cache.AbstractTableMetaCache.getTableMeta(AbstractTableMetaCache.java:69) ~[seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.datasource.AbstractConnectionProxy.prepareStatement(AbstractConnectionProxy.java:117) ~[seata-all-1.3.0.jar:1.3.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55) ~[mybatis-3.5.5.jar:3.5.5]
	at com.sun.proxy.$Proxy253.prepareStatement(Unknown Source) ~[na:na]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86) ~[mybatis-3.5.5.jar:3.5.5]
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88) ~[mybatis-3.5.5.jar:3.5.5]
	... 146 common frames omitted
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS :
- Others:seata-spring-boot-starter1.3 +>spring-cloud-starter-alibaba-seata[2.2.1.RELEASE]

**Comment by miqiang1986** [comment]
mybatisPlus 3.4.0

**Comment by ls9527** [comment]
发一下操作语句看看。  seata 有支持这个，  这个是查询B库的表的元数据的时候失败了。   你写操作B库的表的时候是不是没有写B库的用户名。  

```
// 表名 或者 用户名.表名  为空就报错， 很明显不是这里
 if (StringUtils.isNullOrEmpty(tableName)) {
            throw new IllegalArgumentException("TableMeta cannot be fetched without tableName");
        }
```
```
  String[] schemaTable = tableName.split("\\.");
// 拿到schema名字
        String schemaName = schemaTable.length > 1 ? schemaTable[0] : dbmd.getUserName();
// 拿到表明
        tableName = schemaTable.length > 1 ? schemaTable[1] : tableName;
// 拿到schema的名字然后如果是有双引号就不大写。  应该是这里和你那里不匹配
        if (schemaName.contains("\"")) {
            schemaName = schemaName.replace("\"", "");
        } else {
            schemaName = schemaName.toUpperCase();
        }
```

**Comment by miqiang1986** [comment]
> 发一下操作语句看看。 seata 有支持这个， 这个是查询B库的表的元数据的时候失败了。 你写操作B库的表的时候是不是没有写B库的用户名。
> 
> ```
> // 表名 或者 用户名.表名  为空就报错， 很明显不是这里
>  if (StringUtils.isNullOrEmpty(tableName)) {
>             throw new IllegalArgumentException("TableMeta cannot be fetched without tableName");
>         }
> ```
> 
> ```
>   String[] schemaTable = tableName.split("\\.");
> // 拿到schema名字
>         String schemaName = schemaTable.length > 1 ? schemaTable[0] : dbmd.getUserName();
> // 拿到表明
>         tableName = schemaTable.length > 1 ? schemaTable[1] : tableName;
> // 拿到schema的名字然后如果是有双引号就不大写。  应该是这里和你那里不匹配
>         if (schemaName.contains("\"")) {
>             schemaName = schemaName.replace("\"", "");
>         } else {
>             schemaName = schemaName.toUpperCase();
>         }
> ```

<img width="1071" alt="图片" src="https://user-images.githubusercontent.com/36885190/97287964-2d4f8a00-1880-11eb-85a6-fd1ecd181582.png">

**Comment by miqiang1986** [comment]
> 发一下操作语句看看。 seata 有支持这个， 这个是查询B库的表的元数据的时候失败了。 你写操作B库的表的时候是不是没有写B库的用户名。
> 
> ```
> // 表名 或者 用户名.表名  为空就报错， 很明显不是这里
>  if (StringUtils.isNullOrEmpty(tableName)) {
>             throw new IllegalArgumentException("TableMeta cannot be fetched without tableName");
>         }
> ```
> 
> ```
>   String[] schemaTable = tableName.split("\\.");
> // 拿到schema名字
>         String schemaName = schemaTable.length > 1 ? schemaTable[0] : dbmd.getUserName();
> // 拿到表明
>         tableName = schemaTable.length > 1 ? schemaTable[1] : tableName;
> // 拿到schema的名字然后如果是有双引号就不大写。  应该是这里和你那里不匹配
>         if (schemaName.contains("\"")) {
>             schemaName = schemaName.replace("\"", "");
>         } else {
>             schemaName = schemaName.toUpperCase();
>         }
> ```

应该是我的schemaName既小写又带双引号了，改成大写后问题解决了，谢谢。

**Comment by l81893521** [comment]
If problem had solved. I will close this issue and waiting for you next report.

**Comment by dongshengjun** [comment]
如何是参与事物的表未加主键，也可能出现这个异常，mark一下，
异常如下：
errorMsg:
### Error updating database.  Cause: java.sql.SQLException: io.seata.common.exception.ShouldNeverHappenException: [xid:139.217.95.47:8091:99902589762727936]get tablemeta failed
### The error may exist in com/xxxx/xxx/xxxx/mapper/xxxxMapper.java (best guess)
### The error may involve com.xxxx.xxx.xxx.mapper.xxxxMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO xxxx  ( logType, Path, `Desc`, RequestData, ResponseData, Tenant, CreateBy, CreateTime )  VALUES  ( ?, ?, ?, ?, ?, ?, ?, ? )
### Cause: java.sql.SQLException: io.seata.common.exception.ShouldNeverHappenException: [xid:139.217.95.47:8091:99902589762727936]get tablemeta failed
; uncategorized SQLException; SQL state [null]; error code [0]; io.seata.common.exception.ShouldNeverHappenException: [xid:139.217.95.47:8091:99902589762727936]get tablemeta failed; nested exception is java.sql.SQLException: io.seata.common.exception.ShouldNeverHappenException: [xid:139.217.95.47:8091:99902589762727936]get tablemeta failed--BaseException(code=9999)
