### ISSUE TITLE
Saga 模式下，分支事务启动异常，上报tc状态不正确

### ISSUE THREAD

**Issue by anselleeyy** [seata/seata#3284]
- [X] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

当 saga 的 stateInst 记录过程出现异常，比如数据库写入失败，会导致 decideOnTaskStateFail 判断全局事务状态不正确，针对 IsForUpdate为true的情况下，仍然判断是 FA

### Ⅱ. Describe what happened

在 1.4 版本中，当 `io.seata.saga.engine.pcext.interceptors.ServiceTaskHandlerInterceptor`，Line 182 进行 state inst 记录时，抛出异常，发现上报全局事务状态不正确，导致事务结束

### Ⅲ. Describe what you expected to happen

我认为这里应该继续让tc执行下一次重试，decideOnTaskStateFail 判断过程中，缺少了本次事务的信息，导致 `hasUnsuccessService` 并不是 true

### Ⅵ. Environment:

- JDK version : 1.8
- OS : Linux
- Others: seata 1.4.0

**Comment by anselleeyy** [comment]
#3281

**Comment by anselleeyy** [comment]
> * [x]  I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
> 
> ### Ⅰ. Issue Description
> 当 saga 的 stateInst 记录过程出现异常，比如数据库写入失败，会导致 decideOnTaskStateFail 判断全局事务状态不正确，针对 IsForUpdate为true的情况下，仍然判断是 FA
> 
> ### Ⅱ. Describe what happened
> 在 1.4 版本中，当 `io.seata.saga.engine.pcext.interceptors.ServiceTaskHandlerInterceptor`，Line 182 进行 state inst 记录时，抛出异常，发现上报全局事务状态不正确，导致事务结束
> 
> ### Ⅲ. Describe what you expected to happen
> 我认为这里应该继续让tc执行下一次重试，decideOnTaskStateFail 判断过程中，缺少了本次事务的信息，导致 `hasUnsuccessService` 并不是 true
> 
> ### Ⅳ. How to reproduce it (as minimally and precisely as possible)
> ### Ⅴ. Anything else we need to know?
> ### Ⅵ. Environment:
> * JDK version : 1.8
> * OS : Linux
> * Others: seata 1.4.0

#3281 

> * [x]  I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
> 
> ### Ⅰ. Issue Description
> 当 saga 的 stateInst 记录过程出现异常，比如数据库写入失败，会导致 decideOnTaskStateFail 判断全局事务状态不正确，针对 IsForUpdate为true的情况下，仍然判断是 FA
> 
> ### Ⅱ. Describe what happened
> 在 1.4 版本中，当 `io.seata.saga.engine.pcext.interceptors.ServiceTaskHandlerInterceptor`，Line 182 进行 state inst 记录时，抛出异常，发现上报全局事务状态不正确，导致事务结束
> 
> ### Ⅲ. Describe what you expected to happen
> 我认为这里应该继续让tc执行下一次重试，decideOnTaskStateFail 判断过程中，缺少了本次事务的信息，导致 `hasUnsuccessService` 并不是 true
> 
> ### Ⅳ. How to reproduce it (as minimally and precisely as possible)
> ### Ⅴ. Anything else we need to know?
> ### Ⅵ. Environment:
> * JDK version : 1.8
> * OS : Linux
> * Others: seata 1.4.0

#3281  bugfix: fix wrong status when exception

**Comment by long187** [comment]
@anselleeyy 这个问题，当时是这样设计的，在`io.seata.saga.engine.pcext.interceptors.ServiceTaskHandlerInterceptor#preProcess` 方法实际上是还没有执行这个服务，所以发生异常，不会把这个服务的执行结果放到整体事务状态的判断里，所以当第一个服务执行就因为写state_inst表失败了，则整体事务是没有执行过任何服务，所以是FA，不会由server进行重试，而是需要业务上重新发起一笔新交易。

**Comment by anselleeyy** [comment]
@long187 是这样的，我在验证重试的过程中，引入了一些异常场景，比如数据库的主备切换，导致 state_inst 写过程中抛出数据库异常，上报 TC 状态 FA，我认为这种情况下上报UN是更加合理的；

针对你说的第一个服务就因为写 state_inst 失败，我理解我将这个事务结果放到判断集合中，在 `decideOnTaskStateFail` 的过程中，`hasSuccessUpdateService` 仍然是false的，这样的话判断 status 为 FA，是不会有问题的

**Comment by long187** [comment]
@anselleeyy 如果不是第一个服务在preProcess方法就出错，且有更新类服务已执行成功，则状态机状态为UN，会进行重试。如果没有数据不一致就是FA，不会进行重试，比如执行了几个查询服务，然后执行一个更新类服务时preProcess方法就出错，这种情况可以理解为：在没有分布式事务场景下，因为数据库异常、抖动，发生了本地事务回滚。我们在传统的本地事务场景下事务回滚成功了，也不会有重试机制，也是需要业务重新发起一笔。

对于是说的”在preProcess失败的情况下把服务执行结果放到判断集合中，不会影响整体事务结果“ 这个从代码上看确实是这样，不过既然没有执行过这个服务，而把这个stateInst放入stateInstList里，不合理的。同时既然对结果没有影响也没有必要放进去。

**Comment by anselleeyy** [comment]
@long187 “比如执行了几个查询服务，然后执行一个更新类服务时preProcess方法就出错“，这个场景，实际如果执行的都是更新类服务，而本次服务结果由于并不在判断集合中，集合中只有之前几次成功的更新类事务数据，会导致判断 `hasUnsuccessService` 为 false，无法判断状态，随后在 `setMachineStatusBasedOnException` 中，也无法根据数据库异常，判断出是 UN，实际看下来判断的是一个默认值：FA，这样是不是不太正确？

**Comment by long187** [comment]
@anselleeyy 不是的，会在setMachineStatusBasedOnException方法里根据exception，判断出是 UN，无法识别的异常它默认就是UN

**Comment by anselleeyy** [comment]
@long187 `setMachineStatusBasedOnException`中，我看下来，line 152这里会去判断整个异常栈，`io.seata.saga.engine.utils.ExceptionUtils#getNetExceptionType`，这里去分析异常栈的过程中，如果没有符合网络相关的问题时，返回默认是：`NetExceptionType.NOT_NET_EXCEPTION`，从而命中 line 154 的第一个if判断，返回 FA 状态。。

我看下来是这样的，不知是否理解的不对。。

**Comment by long187** [comment]
@anselleeyy 是的，不过这个分支是为了应对服务没有配置Status映射时的默认规则，就是如果用户没有配置发生异常时的Status映射关系，则去解析这个异常是不是建立网络连接异常，如是说明这次服务调用没有发生，则是FA，如果是网络读写超时，则并不知道服务是否被调用成功，则是UN，其它情况UN。 如果是数据库异常，这里不会是建立网络链接异常，不会出现FA

**Comment by anselleeyy** [comment]
``` java
public static void main(String[] args) {
    StoreException storeException = new StoreException(new SQLException("some exception"));
    EngineExecutionException root = ExceptionUtils.createEngineExecutionException(storeException, FrameworkErrorCode.ExceptionCaught, "", null, "");
    System.out.println(ExceptionUtils.getNetExceptionType(root)); // this return NOT_NET_EXCEPTION
}
```

@long187 上述的逻辑我的理解是同在 [这里](https://github.com/seata/seata/blob/be83b1e6785b1edc1b77f3b1ac367ffe26cdf17e/saga/seata-saga-engine/src/main/java/io/seata/saga/engine/utils/ExceptionUtils.java#L109) 得到的一样的结果，

这里我发生问题时的一个堆栈，这里由于 `setMachineStatusBasedOnException` 返回的是 FA，导致上报 tc 为 `Rollbacked`，不知是否我这里使用或理解有问题。。另外[这里](https://github.com/seata/seata/blob/be83b1e6785b1edc1b77f3b1ac367ffe26cdf17e/saga/seata-saga-engine/src/main/java/io/seata/saga/engine/strategy/impl/DefaultStatusDecisionStrategy.java#L154)判断时，是否将 `t.equals(NetExceptionType.NOT_NET_EXCEPTION)` 去掉比较合适？

```sh
2020-11-17 16:10:27.712 [rpcDispatch_RMROLE_1_5_48] ERROR i.s.saga.engine.impl.ProcessCtrlStateMachineEngine - Operation [forward] failed
io.seata.saga.engine.exception.EngineExecutionException: Record state[RefreshYuewenBillingCache] started failed, stateMachineInstance[10.58.81.67:10043:71996995618742272], Reason: xxxxxxxxxx'
 at io.seata.saga.engine.utils.ExceptionUtils.createEngineExecutionException(ExceptionUtils.java:63)
 at io.seata.saga.engine.pcext.interceptors.ServiceTaskHandlerInterceptor.preProcess(ServiceTaskHandlerInterceptor.java:189)
 at io.seata.saga.engine.pcext.StateMachineProcessHandler.process(StateMachineProcessHandler.java:66)
 at io.seata.saga.proctrl.process.impl.CustomizeBusinessProcessor.process(CustomizeBusinessProcessor.java:69)
 at io.seata.saga.proctrl.impl.ProcessControllerImpl.process(ProcessControllerImpl.java:43)
 at io.seata.saga.proctrl.eventing.impl.ProcessCtrlEventConsumer.process(ProcessCtrlEventConsumer.java:35)
 at io.seata.saga.proctrl.eventing.impl.ProcessCtrlEventConsumer.process(ProcessCtrlEventConsumer.java:28)
 at io.seata.saga.proctrl.eventing.impl.DirectEventBus.offer(DirectEventBus.java:69)
 at io.seata.saga.proctrl.eventing.impl.DirectEventBus.offer(DirectEventBus.java:33)
 at io.seata.saga.proctrl.eventing.impl.ProcessCtrlEventPublisher.publish(ProcessCtrlEventPublisher.java:34)
 at io.seata.saga.engine.impl.ProcessCtrlStateMachineEngine.forwardInternal(ProcessCtrlStateMachineEngine.java:315)
 at io.seata.saga.engine.impl.ProcessCtrlStateMachineEngine.forward(ProcessCtrlStateMachineEngine.java:192)
 at io.seata.saga.rm.SagaResourceManager.branchCommit(SagaResourceManager.java:88)
 at io.seata.rm.AbstractRMHandler.doBranchCommit(AbstractRMHandler.java:98)
 at io.seata.rm.AbstractRMHandler$1.execute(AbstractRMHandler.java:54)
 at io.seata.rm.AbstractRMHandler$1.execute(AbstractRMHandler.java:50)
 at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116)
 at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:50)
 at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:57)
 at io.seata.core.protocol.transaction.BranchCommitRequest.handle(BranchCommitRequest.java:35)
 at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150)
 at io.seata.core.rpc.processor.client.RmBranchCommitProcessor.handleBranchCommit(RmBranchCommitProcessor.java:63)
 at io.seata.core.rpc.processor.client.RmBranchCommitProcessor.process(RmBranchCommitProcessor.java:58)
 at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:278)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.lang.Thread.run(Thread.java:748)
Caused by: io.seata.common.exception.StoreException: xxxxxxxxxx
 at io.seata.saga.engine.store.db.AbstractStore.executeUpdate(AbstractStore.java:150)
 at io.seata.saga.engine.store.db.DbAndReportTcStateLogStore.recordStateStarted(DbAndReportTcStateLogStore.java:276)
 at io.seata.saga.engine.pcext.interceptors.ServiceTaskHandlerInterceptor.preProcess(ServiceTaskHandlerInterceptor.java:183)
 ... 26 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: xxxxxxxxxx
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
 at com.mysql.jdbc.Util.getInstance(Util.java:408)
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
 at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
 at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
 at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
 at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133)
 at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2067)
 at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5175)
 at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2052)
 at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
 at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
 at io.seata.saga.engine.store.db.AbstractStore.executeUpdate(AbstractStore.java:144)
 ... 28 common frames omitted
```

**Comment by long187** [comment]
@long187 嗯嗯，你说得对，那应该是要把  t.equals(NetExceptionType.NOT_NET_EXCEPTION) 这个判断去掉，然后加一个else { stateMachineInstance.setStatus(ExecutionStatus.UN); }

**Comment by anselleeyy** [comment]
@long187 嗯嗯，那我调整下修改
