### ISSUE TITLE
对接测试seata rpc，TCC 事务流程在二阶段报错 No channel is available for resource ，麻烦各位老哥看下，哪个请求参数填错了

### ISSUE THREAD

**Issue by JerryZhou343** [seata/seata#3285]
seata版本 v1.2.0 用了官方的docker镜像
decode： protobuf
TM, RM 注册成功，开启全局事物成功，注册分支事物成功，上报分支事物成功，但是提交事物的时候失败了。找不对应的RM 无法回调rm commit；日志如下：
```shell
2020-11-15 15:21:20.419 INFO [NettyServerNIOWorker_1_4]io.seata.core.rpc.DefaultServerMessageListenerImpl.onRegTmMessage:153 -TM register success,message:RegisterTMRequest{applicationId='app', transactionServiceGroup=''},channel:[id: 0x7ebae56e, L:/172.17.0.2:8091 - R:/172.17.0.1:41076]
2020-11-15 15:21:24.884 INFO [ServerHandlerThread_1_500]io.seata.core.rpc.DefaultServerMessageListenerImpl.onRegRmMessage:127 -RM register success,message:RegisterRMRequest{resourceIds='serviceA', applicationId='app', transactionServiceGroup=''},channel:[id: 0xf96ce0a4, L:/172.17.0.2:8091 - R:/172.17.0.1:41080]
2020-11-15 15:21:28.513 INFO [ServerHandlerThread_1_500]io.seata.core.rpc.DefaultServerMessageListenerImpl.onRegRmMessage:127 -RM register success,message:RegisterRMRequest{resourceIds='serviceB', applicationId='app', transactionServiceGroup=''},channel:[id: 0x2a371ddf, L:/172.17.0.2:8091 - R:/172.17.0.1:41084]
2020-11-15 15:21:34.593 INFO [batchLoggerPrint_1]io.seata.core.rpc.DefaultServerMessageListenerImpl.run:214 -timeout=10000000,transactionName=app.mung,clientIp:172.17.0.1,vgroup:
2020-11-15 15:21:34.594 INFO [ServerHandlerThread_1_500]io.seata.server.coordinator.DefaultCoordinator.doGlobalBegin:159 -Begin new global transaction applicationId: app,transactionServiceGroup: , transactionName: app.mung,timeout:10000000,xid:172.17.0.2:8091:2027615785
2020-11-15 15:21:34.619 INFO [batchLoggerPrint_1]io.seata.core.rpc.DefaultServerMessageListenerImpl.run:214 -xid=172.17.0.2:8091:2027615785,extraData=,clientIp:172.17.0.1,vgroup:
2020-11-15 15:21:34.632 INFO [batchLoggerPrint_1]io.seata.core.rpc.DefaultServerMessageListenerImpl.run:214 -xid=172.17.0.2:8091:2027615785,branchType=TCC,resourceId=ServiceA,lockKey=,clientIp:172.17.0.1,vgroup:
2020-11-15 15:21:34.632 INFO [ServerHandlerThread_1_500]io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0:87 -Register branch successfully, xid = 172.17.0.2:8091:2027615785, branchId = 2027615786, resourceId = ServiceA ,lockKeys = 
2020-11-15 15:21:39.648 INFO [batchLoggerPrint_1]io.seata.core.rpc.DefaultServerMessageListenerImpl.run:214 -xid=172.17.0.2:8091:2027615785,branchId=2027615786,resourceId=ServiceA,status=PhaseOne_Done,applicationData=,clientIp:172.17.0.1,vgroup:
2020-11-15 15:21:39.649 INFO [ServerHandlerThread_1_500]io.seata.server.coordinator.AbstractCore.branchReport:138 -Report branch status successfully, xid = 172.17.0.2:8091:2027615785, branchId = 2027615786
2020-11-15 15:21:39.657 INFO [batchLoggerPrint_1]io.seata.core.rpc.DefaultServerMessageListenerImpl.run:214 -xid=172.17.0.2:8091:2027615785,branchType=TCC,resourceId=ServiceB,lockKey=,clientIp:172.17.0.1,vgroup:
2020-11-15 15:21:39.658 INFO [ServerHandlerThread_1_500]io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0:87 -Register branch successfully, xid = 172.17.0.2:8091:2027615785, branchId = 2027615787, resourceId = ServiceB ,lockKeys = 
2020-11-15 15:21:44.672 INFO [batchLoggerPrint_1]io.seata.core.rpc.DefaultServerMessageListenerImpl.run:214 -xid=172.17.0.2:8091:2027615785,branchId=2027615787,resourceId=ServiceB,status=PhaseOne_Done,applicationData=,clientIp:172.17.0.1,vgroup:
2020-11-15 15:21:44.674 INFO [ServerHandlerThread_1_500]io.seata.server.coordinator.AbstractCore.branchReport:138 -Report branch status successfully, xid = 172.17.0.2:8091:2027615785, branchId = 2027615787
2020-11-15 15:21:44.680 INFO [batchLoggerPrint_1]io.seata.core.rpc.DefaultServerMessageListenerImpl.run:214 -xid=172.17.0.2:8091:2027615785,extraData=,clientIp:172.17.0.1,vgroup:
2020-11-15 15:21:44.680 INFO [ServerHandlerThread_1_500]io.seata.core.rpc.ChannelManager.getChannel:296 -No channel is available for resource[ServiceA]
2020-11-15 15:21:44.682 ERROR[ServerHandlerThread_1_500]io.seata.server.coordinator.DefaultCore.error:61 -Committing branch transaction exception: BR:2027615786/2027615785
2020-11-15 15:21:44.682 ERROR[ServerHandlerThread_1_500]io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate:119 -Catch TransactionException while do RPC, request: xid=172.17.0.2:8091:2027615785,extraData=
io.seata.core.exception.TransactionException: java.lang.RuntimeException: rm client is not connected. dbkey:ServiceA,clientId:app:172.17.0.1:41080
	at io.seata.server.coordinator.DefaultCore.doGlobalCommit(DefaultCore.java:223)
	at io.seata.server.coordinator.DefaultCore.commit(DefaultCore.java:165)
	at io.seata.server.coordinator.DefaultCoordinator.doGlobalCommit(DefaultCoordinator.java:167)
	at io.seata.server.AbstractTCInboundHandler$2.execute(AbstractTCInboundHandler.java:95)
	at io.seata.server.AbstractTCInboundHandler$2.execute(AbstractTCInboundHandler.java:90)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116)
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:90)
	at io.seata.core.protocol.transaction.GlobalCommitRequest.handle(GlobalCommitRequest.java:34)
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:427)
	at io.seata.core.rpc.DefaultServerMessageListenerImpl.onTrxMessage(DefaultServerMessageListenerImpl.java:101)
	at io.seata.core.rpc.netty.AbstractRpcRemotingServer$ServerHandler.dispatch(AbstractRpcRemotingServer.java:196)
	at io.seata.core.rpc.netty.AbstractRpcRemoting$AbstractHandler$1.run(AbstractRpcRemoting.java:452)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: rm client is not connected. dbkey:ServiceA,clientId:app:172.17.0.1:41080
	at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:112)
	at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:164)
	at io.seata.server.coordinator.AbstractCore.branchCommitSend(AbstractCore.java:168)
	at io.seata.server.coordinator.AbstractCore.branchCommit(AbstractCore.java:158)
	at io.seata.server.coordinator.DefaultCore.doGlobalCommit(DefaultCore.java:187)
	... 15 common frames omitted
2020-11-15 15:21:45.659 ERROR[RetryCommitting_1]io.seata.server.coordinator.DefaultCoordinator.handleRetryCommitting:310 -Global transaction commit retry timeout and has removed [172.17.0.2:8091:2027615785]

```
请问各位老哥，是什么原因导致找不对对应的channel，看日志channel 注册也是ok的呀。

**Comment by JerryZhou343** [comment]
注册RM 的资源信息需要和 try阶段填的资源名相同；问题中，注册的是serviceA 但是 try的时候给的是ServiceA，所以报错。
