### ISSUE TITLE
Seata + JPA + IDEA + jrebel debug启动报错

### ISSUE THREAD

**Issue by casuak** [seata/seata#3298]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Seata + JPA + IDEA + jrebel debug启动报错
jrebel是IDEA的一个热部署插件，不用这个插件时可以正常启动

### Ⅱ. Describe what happened

启动报错：
Caused by: java.lang.NoSuchFieldException: advised
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[na:1.8.0_171]
	at io.seata.spring.util.SpringProxyUtils.getAdvisedSupport(SpringProxyUtils.java:107) ~[seata-all-1.4.0.jar:1.4.0]
	at io.seata.spring.util.SpringProxyUtils.findTargetClass(SpringProxyUtils.java:51) ~[seata-all-1.4.0.jar:1.4.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:256) ~[seata-all-1.4.0.jar:1.4.0]
	... 29 common frames omitted

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

我的项目环境是springboot + dubbo + seata + jpa，使用IDEA的jrebel插件启动项目就会报错

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zqxin45** [comment]
大佬，碰到相同问题了，怎么解决的

**Comment by casuak** [comment]
不用jpa，改用mybatis-plus

**Comment by zqxin45** [comment]
这有点难啊，先不用了jrebel

**Comment by 54zhangjunzhe** [comment]
怎么解决呢？就是不兼容不要用jrebel对吗？

**Comment by guiqingle520** [comment]
最近我也遇到了，这个问题还有大佬跟进或者解决了吗？？

**Comment by 54zhangjunzhe** [comment]
没有解决，应该是jar包冲突了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月10日(周五) 上午10:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [apache/incubator-seata] Seata + JPA + IDEA + jrebel debug启动报错 (#3298)




 
最近我也遇到了，这个问题还有大佬跟进或者解决了吗？？

**Comment by liuzhenggang** [comment]
![image](https://github.com/apache/incubator-seata/assets/30791522/63303a4d-b0d9-461e-8e3a-95eec594c63f)

seate源码根据proxy创建的InvocationHandler不一样。

- 不用jrebel启动时：

![image](https://github.com/apache/incubator-seata/assets/30791522/fe24c918-9581-4a45-8258-a7740dbe4150)
能根据反射获取到获取advised字段。

- 使用jrebel时：

![image](https://github.com/apache/incubator-seata/assets/30791522/c42b2767-3e84-4aca-bcd6-ca146800594b)
不能根据反射获取到获取advised字段。

**Comment by JiangJuHong** [comment]
通过禁用seata可以解决此问题，在 seata.yaml 中配置`seata.enabled: false`（仅适用于开发环境，生产环境别乱搞），此解决方案属于临时解决方案，理想中的方案还是seata和jrebel能够同时存在，坐等官方回复

**Comment by funky-eyes** [comment]
> 通过禁用seata可以解决此问题，在 seata.yaml 中配置`seata.enabled: false`（仅适用于开发环境，生产环境别乱搞），此解决方案属于临时解决方案，理想中的方案还是seata和jrebel能够同时存在，坐等官方回复

你可以自定义跳过bean扫描的逻辑
You can customize the logic of skipping bean scans

**Comment by JiangJuHong** [comment]
> > 通过禁用seata可以解决此问题，在 seata.yaml 中配置`seata.enabled: false`（仅适用于开发环境，生产环境别乱搞），此解决方案属于临时解决方案，理想中的方案还是seata和jrebel能够同时存在，坐等官方回复
> 
> 你可以自定义跳过bean扫描的逻辑 You can customize the logic of skipping bean scans

麻烦问下有Example或相关Issus吗

**Comment by imyuyu** [comment]
今天也遇到了，4年过去了还没解决吗？

**Comment by Kai-Ch** [comment]
Can't solve it or don't want to solve it?

**Comment by breezefaith** [comment]
2025年了我也遇到这个问题了，还是没解决吗？

**Comment by JiangJuHong** [comment]
参考官方评论，使用自定义跳过bean逻辑，#1458，我的项目是 Mongo + Mybatis + Seata + JRebel，通过以下配置不扫描mongo能够解决此问题，同理，如果是jpa，将 `if (bean instanceof MongoRepository) return false;` 替换为对应 Repository 即可.
> 通过 ConditionalOnExpression 限定仅在开发环境启用此配置，可根据需求决定是否使用.

示例代码:
```java
/**
 * 自定义Seata扫描配置，解决：Seata + JPA(Mongo) + JRebel 项目无法启动问题
 * 注意：此配置类仅在dev模式下生效
 */
@Slf4j
@Configuration
@ConditionalOnExpression("'${spring.profiles.active:}'.contains('dev')")
public class CustomSeataScannerCheckerConfig implements ScannerChecker {

    public CustomSeataScannerCheckerConfig() {
        log.info("CustomSeataScannerCheckerConfig init, seata dev skip MongoRepository check!");
    }

    @Override
    public boolean check(Object bean, String beanName, @Nullable ConfigurableListableBeanFactory beanFactory) throws Exception {
        if (bean instanceof MongoRepository) return false;
        return true;
    }
}

```

**Comment by breezefaith** [comment]
已收到您的来信，非常感谢
