### ISSUE TITLE
Caused by: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not register branch into global session xid = localhost:8091:77779511492571136 status = AsyncCommitting, cause by globalSession not active] ]

### ISSUE THREAD

**Issue by bf1090** [seata/seata#3331]
seata-spring-boot-starter 1.4.0报下面错误，请问该如何激活globalSession？

Caused by: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not register branch into global session xid = localhost:8091:77779511492571136 status = AsyncCommitting, cause by globalSession not active] ]
   at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:69)
	at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96)
	at io.seata.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:241)
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:219)
	... 90 common frames omitted

**Comment by a364176773** [comment]
检查是不是发起者没加全局事务注解，而是发起者本地的一个函数加了，导致传递xid的时候，那个函数执行完了，提交了全局事务。或者看下是不是分支异步了，或者服务重试导致

**Comment by bf1090** [comment]
dubbo重试了一次服务，那可能是这个原因，多谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "seata/seata"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 晚上6:42
收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;;
抄送:&nbsp;"MDZZ"<1533964916@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] Caused by: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not register branch into global session xid = localhost:8091:77779511492571136 status = AsyncCommitting, cause by globalSession not active] ] (#3331)





 
检查是不是发起者没加全局事务注解，而是发起者本地的一个函数加了，导致传递xid的时候，那个函数执行完了，提交了全局事务。或者看下是不是分支异步了，或者服务重试导致
