### ISSUE TITLE
seata 1.2~1.4使用nacos /api//nacos/v1/ns/instanc 403 无权限

### ISSUE THREAD

**Issue by ilkm** [seata/seata#3332]
我将注册中心从eurka迁移到nacos，为了保证配置信息的安全，nacos开启了：nacos.core.auth.enabled=true
若nacos.core.auth.enabled=false时一切正常，file.conf,registry.conf均配置好了
nacos-config.txt与nacos-config.sh也进行配置过了
微服务组建切换成功后，切换seata的时候出现一下错误：
➜  bin ./seata-server.sh 
Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file /Users/zi/Downloads/seata/logs/seata_gc.log due to No such file or directory

19:34:15,185 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
19:34:15,185 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
19:34:15,185 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/zi/Downloads/seata/conf/logback.xml]
19:34:15,186 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
19:34:15,186 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/zi/Downloads/seata/lib/seata-server-1.2.0.jar!/logback.xml]
19:34:15,186 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/Users/zi/Downloads/seata/conf/logback.xml]
19:34:15,255 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
19:34:15,261 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/Users/zi/Downloads/seata/conf/logback.xml] 
19:34:15,261 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 1 minutes
19:34:15,264 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
19:34:15,267 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [stdout]
19:34:15,322 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
19:34:15,325 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [seata-default]
19:34:15,332 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1824835605 - Archive files will be limited to [2048 MB] each.
19:34:15,335 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1824835605 - No compression will be used
19:34:15,337 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1824835605 - Will use the pattern /Users/zi/logs/seata/seata-server.log.%d{yyyy-MM-dd}.%i for the active file
19:34:15,339 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3a82f6ef - The date pattern is 'yyyy-MM-dd' from file name pattern '/Users/zi/logs/seata/seata-server.log.%d{yyyy-MM-dd}.%i'.
19:34:15,341 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3a82f6ef - Roll-over at midnight.
19:34:15,344 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3a82f6ef - Setting initial period to Thu Dec 03 19:32:25 CST 2020
19:34:15,346 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1824835605 - Cleaning on start up
19:34:15,347 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - first clean up after appender initialization
19:34:15,347 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Multiple periods, i.e. 32 periods, seem to have elapsed. This is expected at application start.
19:34:15,347 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
19:34:15,349 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[seata-default] - Active log file name: /Users/zi/logs/seata/seata-server.log
19:34:15,349 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[seata-default] - File property is set to [/Users/zi/logs/seata/seata-server.log]
19:34:15,351 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [io.seata.server.storage.file.store.FileTransactionStoreManager] to false
19:34:15,351 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - io.seata.server.storage.file.store.FileTransactionStoreManager level set to INFO
19:34:15,351 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [seata-default] to Logger[io.seata.server.storage.file.store.FileTransactionStoreManager]
19:34:15,352 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
19:34:15,352 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [seata-default] to Logger[ROOT]
19:34:15,352 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stdout] to Logger[ROOT]
19:34:15,352 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
19:34:15,352 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@100fc185 - Registering current configuration as safe fallback point

2020-12-03 19:34:15.453 INFO [main]io.seata.config.FileConfiguration.<init>:121 -The configuration file used is registry.conf
2020-12-03 19:34:15.520 INFO [main]io.seata.config.FileConfiguration.<init>:121 -The configuration file used is file.conf
2020-12-03 19:34:15.629 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.storage.file.session.FileSessionManager has already been loaded, skipped
2020-12-03 19:34:15.630 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.storage.db.session.DataBaseSessionManager has already been loaded, skipped
2020-12-03 19:34:15.652 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.store.DbcpDataSourceGenerator has already been loaded, skipped
2020-12-03 19:34:15.652 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.store.DruidDataSourceGenerator has already been loaded, skipped
2020-12-03 19:34:15.992 INFO [main]com.alibaba.druid.pool.DruidDataSource.init:947 -{dataSource-1} inited
2020-12-03 19:34:16.087 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.transaction.at.ATCore has already been loaded, skipped
2020-12-03 19:34:16.088 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.transaction.tcc.TccCore has already been loaded, skipped
2020-12-03 19:34:16.088 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.transaction.saga.SagaCore has already been loaded, skipped
2020-12-03 19:34:16.088 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.transaction.xa.XACore has already been loaded, skipped
2020-12-03 19:34:16.092 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.storage.db.lock.DataBaseLockManager has already been loaded, skipped
2020-12-03 19:34:16.093 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.storage.file.lock.FileLockManager has already been loaded, skipped
2020-12-03 19:34:26.192 INFO [main]io.seata.core.rpc.netty.RpcServerBootstrap.start:155 -Server started ... 
2020-12-03 19:34:26.458 ERROR[main]io.seata.server.Server.main:95 -rpcServer init error:ErrCode:403, ErrMsg:failed to req API:/api//nacos/v1/ns/instance after all servers([172.16.8.231]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Dec 03 06:34:26 EST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
java.lang.RuntimeException: ErrCode:403, ErrMsg:failed to req API:/api//nacos/v1/ns/instance after all servers([172.16.8.231]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Dec 03 06:34:26 EST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
	at io.seata.core.rpc.netty.RpcServerBootstrap.start(RpcServerBootstrap.java:160)
	at io.seata.core.rpc.netty.AbstractRpcRemotingServer.init(AbstractRpcRemotingServer.java:140)
	at io.seata.core.rpc.netty.RpcServer.init(RpcServer.java:59)
	at io.seata.server.Server.main(Server.java:93)
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance after all servers([172.16.8.231]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Dec 03 06:34:26 EST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:490)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:395)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:391)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:210)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:207)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:182)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:170)
	at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:84)
	at io.seata.core.rpc.netty.RpcServerBootstrap.start(RpcServerBootstrap.java:156)
	... 3 common frames omitted
2020-12-03 19:34:26.462 INFO [ShutdownHook]io.seata.core.rpc.netty.RpcServer.destroy:69 -destroyed rpcServer

**Comment by ilkm** [comment]
当时依赖比较混乱，调整依赖后问题解决

**Comment by cnscottluo** [comment]
@ilkm 怎么解决的
