### ISSUE TITLE
seata 1.4 不支持mysql 8.0

### ISSUE THREAD

**Issue by cslvista1** [seata/seata#3379]
环境：
seata 1.4
mysql 8.0.22
nacos 1.2
spring-cloud-starter-alibaba-seata 2.0.0 RELEASE
XA模式
spring cloud 2.2
mysql-connector-java 8.0.19

问题描述：
当进入启用@GlobalTransactional注解的方法时，报如下错误，我看了一下jar包，应该是com.mysql.cj.jdbc.JdbcConnection，下面报错多了一个api
java.lang.ClassNotFoundException: com.mysql.cj.api.jdbc.JdbcConnection
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.alibaba.druid.util.MySqlUtils.createXAConnection(MySqlUtils.java:110)
	at io.seata.rm.datasource.util.XAUtils.createXAConnection(XAUtils.java:62)
	at io.seata.rm.datasource.util.XAUtils.createXAConnection(XAUtils.java:41)
	at io.seata.rm.datasource.xa.DataSourceProxyXA.getConnectionProxyXA(DataSourceProxyXA.java:84)
	at io.seata.rm.datasource.xa.DataSourceProxyXA.getConnectionProxy(DataSourceProxyXA.java:73)
	at io.seata.rm.datasource.xa.DataSourceProxyXA.getConnection(DataSourceProxyXA.java:60)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:523)

**Comment by cmonkey** [comment]
这是druid抛的问题，你可以把druid项目clone 下来，然后将mysql 的依赖修改为自己现在这个项目的版本，然后运行MySqlUtilsTest, 看看测试是否通过。

PS: 你可能需要修改一下MySqlUtilsTest.test_xa method , 因为majorVersion 等于8时，没有case 被执行

**Comment by a364176773** [comment]
mysql的驱动换8.0.11版本
