### ISSUE TITLE
获取Global lock 失败时，仍然提交了本地事务

### ISSUE THREAD

**Issue by arnozhai** [seata/seata#3387]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
启动一个全局事务 tx1， 在订单表中insert 了一条记录，tx1未完成提交前，启动了另一个全局事务 tx2，修改了tx1 提交的记录，日志中提示获取 Global lock 失败，本地事务最终完成没有回滚。

### Ⅱ. Describe what happened

seata-server
```
[2m2020-12-18 14:29:39.727[0;39m [32m INFO[0;39m [2m---[0;39m [2m[LoggerPrint_1_1][0;39m [36mi.s.c.r.p.server.BatchLogHandler        [0;39m [2m:[0;39m SeataMergeMessage xid=192.168.31.36:8091:83205678771093504,branchType=AT,resourceId=jdbc:mysql://127.0.0.1:3306/example,lockKey=order:42
,clientIp:192.168.31.36,vgroup:fsp_tx_group
[2m2020-12-18 14:29:39.728[0;39m [32m INFO[0;39m [2m---[0;39m [2m[Thread_1_49_500][0;39m [36mi.s.s.s.db.lock.LockStoreDataBaseDAO    [0;39m [2m:[0;39m Global lock on [order:42] is holding by xid 192.168.31.36:8091:83205610190028800 branchId 83205611007918081
[2m2020-12-18 14:29:39.728[0;39m [31mERROR[0;39m [2m---[0;39m [2m[Thread_1_49_500][0;39m [36mi.s.c.e.AbstractExceptionHandler        [0;39m [2m:[0;39m Catch TransactionException while do RPC, request: xid=192.168.31.36:8091:83205678771093504,branchType=AT,resourceId=jdbc:mysql://127.0.0.1:3306/example,lockKey=order:42
==>
io.seata.core.exception.BranchTransactionException: Global lock acquire failed xid = 192.168.31.36:8091:83205678771093504 branchId = 83205678863368193
        at io.seata.server.transaction.at.ATCore.branchSessionLock(ATCore.java:48)
        at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:77)
        at io.seata.server.storage.db.session.DataBaseSessionManager.lockAndExecute(DataBaseSessionManager.java:197)
        at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:275)
        at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:72)
        at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:97)
        at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:192)
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184)
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179)
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116)
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179)
        at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:427)
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:116)
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77)
        at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
<==

```

seata 数据库
```
2020-12-18T06:29:39.706293Z	    9 Query	select @@session.tx_read_only
2020-12-18T06:29:39.706495Z	    9 Query	insert into global_table(xid, transaction_id, status, application_id, transaction_service_group, transaction_name, timeout, begin_time, application_data, gmt_create, gmt_modified) values ('192.168.31.36:8091:83205678771093504', 83205678771093504, 1, 'order-server', 'fsp_tx_group', 'fsp-update-order', 60000, 1608272979705, null, now(), now())
2020-12-18T06:29:39.727639Z	    9 Query	select xid, transaction_id, status, application_id, transaction_service_group, transaction_name, timeout, begin_time, application_data, gmt_create, gmt_modified  from global_table where xid = '192.168.31.36:8091:83205678771093504'
2020-12-18T06:29:39.727973Z	    9 Query	SET autocommit=0
2020-12-18T06:29:39.728163Z	    9 Query	select xid, transaction_id, branch_id, resource_id, table_name, pk, row_key, gmt_create, gmt_modified from lock_table where row_key in ('jdbc:mysql://127.0.0.1:3306/example^^^order^^^42')
2020-12-18T06:29:39.728726Z	    9 Query	rollback
2020-12-18T06:29:39.728885Z	    9 Query	SET autocommit=1
```

客户端数据库  tx2 日志
```
2020-12-18T06:29:39.719039Z	   32 Query	SET autocommit=0
2020-12-18T06:29:39.723200Z	   32 Query	SELECT id, money, status FROM `order` WHERE id = 42 FOR UPDATE
2020-12-18T06:29:39.723816Z	   32 Query	select @@session.tx_read_only
2020-12-18T06:29:39.725188Z	   32 Query	UPDATE `order` SET money = money - 1,status = 99
    where id = 42
2020-12-18T06:29:39.725987Z	   32 Query	SELECT id, money, status FROM `order` WHERE (id) in ( (42) )
2020-12-18T06:29:39.731804Z	   32 Query	rollback
2020-12-18T06:29:39.744271Z	   32 Query	SELECT id, money, status FROM `order` WHERE id = 42 FOR UPDATE
2020-12-18T06:29:39.744939Z	   32 Query	select @@session.tx_read_only
2020-12-18T06:29:39.745259Z	   32 Query	UPDATE `order` SET money = money - 1,status = 99
    where id = 42
2020-12-18T06:29:39.746024Z	   32 Query	SELECT id, money, status FROM `order` WHERE (id) in ( (42) )
2020-12-18T06:29:39.746448Z	   32 Query	commit
2020-12-18T06:29:39.747689Z	   32 Query	SET autocommit=1
```

tx1 最终提交日志
```
2020-12-18T06:30:14.200363Z	   32 Query	SET autocommit=0
2020-12-18T06:30:14.201082Z	   32 Query	SELECT id, money, status FROM `order` WHERE user_id = 1
AND status = 0 FOR UPDATE
2020-12-18T06:30:14.201488Z	   32 Query	select @@session.tx_read_only
2020-12-18T06:30:14.201720Z	   32 Query	UPDATE `order` SET money = money - 9.00,status = 1
    where user_id = 1 and status = 0
2020-12-18T06:30:14.202135Z	   32 Query	commit
2020-12-18T06:30:14.202270Z	   32 Query	SET autocommit=1
```

应用日志：
```
2020-12-18 14:29:39.704 DEBUG 11480 --- [nio-8180-exec-1] i.s.c.r.n.AbstractNettyRemotingClient    : offer message: timeout=60000,transactionName=fsp-update-order
2020-12-18 14:29:39.704 DEBUG 11480 --- [Send_TMROLE_1_1] i.s.c.rpc.netty.AbstractNettyRemoting    : write message:SeataMergeMessage timeout=60000,transactionName=fsp-update-order
, channel:[id: 0x174a08ab, L:/192.168.31.36:61613 - R:/192.168.31.36:8091],active?true,writable?true,isopen?true
2020-12-18 14:29:39.708 DEBUG 11480 --- [ctor_TMROLE_1_1] i.s.c.rpc.netty.AbstractNettyRemoting    : io.seata.core.rpc.netty.TmNettyRemotingClient@1be2a508 msgId:8, body:MergeResultMessage xid=192.168.31.36:8091:83205678771093504;extraData=;

2020-12-18 14:29:39.708 DEBUG 11480 --- [nio-8180-exec-1] io.seata.core.context.RootContext        : bind 192.168.31.36:8091:83205678771093504
2020-12-18 14:29:39.708  INFO 11480 --- [nio-8180-exec-1] i.seata.tm.api.DefaultGlobalTransaction  : Begin new global transaction [192.168.31.36:8091:83205678771093504]
2020-12-18 14:29:39.712 DEBUG 11480 --- [nio-8180-exec-1] io.seata.sample.dao.OrderDao.updateById  : ==>  Preparing: UPDATE `order` SET money = money - ?,status = 99 where id = ? ; 
2020-12-18 14:29:39.717 DEBUG 11480 --- [nio-8180-exec-1] io.seata.sample.dao.OrderDao.updateById  : ==> Parameters: 1(BigDecimal), 42(Long)
2020-12-18 14:29:39.718 DEBUG 11480 --- [igOperate_2_1_2] io.seata.config.FileConfiguration        : Could not found property client.undo.onlyCareUpdateColumns, try to use default value instead. exception:No configuration setting found for key 'client.undo.onlyCareUpdateColumns'
2020-12-18 14:29:39.726 DEBUG 11480 --- [igOperate_1_1_2] io.seata.config.FileConfiguration        : Could not found property registry.loadBalance, try to use default value instead. exception:No configuration setting found for key 'registry.loadBalance'
2020-12-18 14:29:39.726 DEBUG 11480 --- [nio-8180-exec-1] i.s.c.r.n.AbstractNettyRemotingClient    : offer message: xid=192.168.31.36:8091:83205678771093504,branchType=AT,resourceId=jdbc:mysql://127.0.0.1:3306/example,lockKey=order:42
2020-12-18 14:29:39.726 DEBUG 11480 --- [Send_RMROLE_1_1] i.s.c.rpc.netty.AbstractNettyRemoting    : write message:SeataMergeMessage xid=192.168.31.36:8091:83205678771093504,branchType=AT,resourceId=jdbc:mysql://127.0.0.1:3306/example,lockKey=order:42
, channel:[id: 0x81283426, L:/192.168.31.36:61547 - R:/192.168.31.36:8091],active?true,writable?true,isopen?true
2020-12-18 14:29:39.729 DEBUG 11480 --- [ctor_RMROLE_1_1] i.s.c.rpc.netty.AbstractNettyRemoting    : io.seata.core.rpc.netty.RmNettyRemotingClient@7f11402e msgId:14, body:MergeResultMessage BranchRegisterResponse: branchId=0,result code =Failed,getMsg =TransactionException[Global lock acquire failed xid = 192.168.31.36:8091:83205678771093504 branchId = 83205678863368193]

2020-12-18 14:29:39.747 DEBUG 11480 --- [nio-8180-exec-1] io.seata.sample.dao.OrderDao.updateById  : <==    Updates: 1
2020-12-18 14:29:46.325 DEBUG 11480 --- [igOperate_1_1_2] io.seata.config.FileConfiguration        : Could not found property registry.loadBalance, try to use default value instead. exception:No configuration setting found for key 'registry.loadBalance'
2020-12-18 14:29:46.325 DEBUG 11480 --- [nio-8180-exec-1] i.s.c.r.n.AbstractNettyRemotingClient    : offer message: xid=192.168.31.36:8091:83205678771093504,extraData=null
2020-12-18 14:29:46.326 DEBUG 11480 --- [Send_TMROLE_1_1] i.s.c.rpc.netty.AbstractNettyRemoting    : write message:SeataMergeMessage xid=192.168.31.36:8091:83205678771093504,extraData=null
, channel:[id: 0x174a08ab, L:/192.168.31.36:61613 - R:/192.168.31.36:8091],active?true,writable?true,isopen?true
2020-12-18 14:29:46.333 DEBUG 11480 --- [freshExecutor-0] i.s.d.r.e.EurekaRegistryServiceImpl      : refreshCluster success, cluster: {ORDER-SERVER=[/192.168.31.36:8180], ACCOUNT-SERVER=[/192.168.31.36:8181], STORAGE-SERVER=[/192.168.31.36:8182], DEFAULT=[/192.168.31.36:8091]}
2020-12-18 14:29:46.337 DEBUG 11480 --- [ctor_TMROLE_1_1] i.s.c.rpc.netty.AbstractNettyRemoting    : io.seata.core.rpc.netty.TmNettyRemotingClient@1be2a508 msgId:10, body:MergeResultMessage globalStatus=Committed,ResultCode=Success,Msg=null

2020-12-18 14:29:50.576 DEBUG 11480 --- [nio-8180-exec-1] io.seata.core.context.RootContext        : unbind 192.168.31.36:8091:83205678771093504 
2020-12-18 14:29:50.577 DEBUG 11480 --- [nio-8180-exec-1] i.seata.tm.api.DefaultGlobalTransaction  : Suspending current transaction, xid = 192.168.31.36:8091:83205678771093504
2020-12-18 14:29:50.581  INFO 11480 --- [nio-8180-exec-1] i.seata.tm.api.DefaultGlobalTransaction  : [192.168.31.36:8091:83205678771093504] commit status: Committed
```

### Ⅵ. Environment:

- seata-server：1.3.0
- spring-cloud-alibaba-seata： 2.1.0.RELEASE
- JDK version :  1.8.0_221
- OS : win10
- mysql :  5.7.32-log

**Comment by a364176773** [comment]
请升级最新版检查问题是否存在,如果存在,请提供复现demo,在源码connectionProxy中,如果在注册阶段抛出了异常,是不会走向connection.commit的

**Comment by starjiang** [comment]
这个问题产生的原因是
当获取全局锁失败，分支自己会回滚，回滚代码里面调用了context.reset()，把context 里面的xid 给清空了，然后重试获取全局锁的时候，分支事物会判断成本地事物，直接就提交了。

//第一次提交获取全局锁失败，调用以下函数回滚本地事物，context.reset() 把xid 给清空了，这个问题，算是比较严重的了，会把数据写脏。
    @Override
    public void rollback() throws SQLException {
        targetConnection.rollback();
        if (context.inGlobalTransaction() && context.isBranchRegistered()) {
            report(false);
        }
        context.reset();//这里把xid 给清空了，理论上应该调用 context.reset(context.getXid()) 保留xid
    }

  //第二次提交直接判断为地事务，结果数据就脏写了
    private void doCommit() throws SQLException {
        if (context.inGlobalTransaction()) { //这里会根据xid!=null 来判定是否是全局事物
            processGlobalTransactionCommit();
        } else if (context.isGlobalLockRequire()) {
            processLocalCommitWithGlobalLocks();
        } else {
            targetConnection.commit(); //xid==null 直接走到这个分支了，导致数据脏写
        }
    }

**Comment by luoyonghui55** [comment]
现在这个问题解决了吗？

**Comment by shaowin16** [comment]
遇到同样的问题。
现象：300并发压50000请求，发现最终扣减库存50000，创建订单49999，扣钱49999，与正确结果相差1个库存
压测demo逻辑：每次请求先到storage服务扣1个库存，再到account服务扣1块钱，再到order服务下单
查看日志：下面一个xid存在错误日志
xid=118767181818236947

9：38：22.743：business开启全局事务
9：38：22.882：storage提交前获取全局锁失败，进入重试阶段(Global lock acquire failed)
9：38：25.946: tc服务端提示回滚完成
9：38：25.952：business打印全局事务回滚完成状态
9：38：25.981~983：account提示事务已经完结报错(Could not found global transaction xid = 10.201.12.20:8091:118767181818236947, may be has finished)

最终结果：storage没有回滚(正常应该storage回滚才对）

分析：（1）storage执行了没做回滚
应该是由于调用account服务超时（应该是3s）,触发全局事务回滚，而由于storage第一次获取全局锁失败后，把xid给清空了，第二次提交变成了本地事务直接提交了，所以并没有undo_log日志，不做任何回滚。

所以是rollback()函数的bug吗，想确认一下
```
 @Override
    public void rollback() throws SQLException {
        targetConnection.rollback();
        if (context.inGlobalTransaction() && context.isBranchRegistered()) {
            report(false);
        }
        context.reset();//这里把xid 给清空了，理论上应该调用 context.reset(context.getXid()) 保留xid
    }
```

**Comment by starjiang** [comment]
1.5 版本修复了这个问题，但是还没有发布

**Comment by starjiang** [comment]
数据写脏，是大问题，理论上要发一个紧急修复版本来修复这个问题，等1.5 发布估计还要好几月
