### ISSUE TITLE
`lock_table`.`table_name`    Data too long

### ISSUE THREAD

**Issue by zlwtrouble** [seata/seata#3446]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata server保存锁信息时失败
1.4中提供到mysql脚本中表`lock_table`，字段`table_name` VARCHAR(32) 长度太短，mysql5.7表名最大长度可以到64个字符

### Ⅱ. Describe what happened

**seata server error.log：**
2021-01-06 20:55:00.673  INFO --- [          batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : SeataMergeMessage xid=192.168.173.71:8091:90188024456941568,branchType=AT,resourceId=jdbc:mysql://192.168.173.71:3306/report,lockKey=customer_sales_profit_breakdown_info:553682112742457344;warehouse_data_cost_analysis:553682112704708608;sales_profit_breakdown_info:553682112755040256;sales_send_receive_summary:553682112704708608;outbound_reconciliation_detail:553682112729874432
,clientIp:192.168.158.173,vgroup:my_mro_tx_group
2021-01-06 20:55:00.674 ERROR --- [  ServerHandlerThread_1_36_500] i.s.s.s.db.lock.LockStoreDataBaseDAO     : Global lock batch acquire error: Data truncation: Data too long for column 'table_name' at row 1
==>
java.sql.BatchUpdateException: Data truncation: Data too long for column 'table_name' at row 1
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1819)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1281)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeBatch(DruidPooledPreparedStatement.java:565)
	at io.seata.server.storage.db.lock.LockStoreDataBaseDAO.doAcquireLocks(LockStoreDataBaseDAO.java:344)
	at io.seata.server.storage.db.lock.LockStoreDataBaseDAO.acquireLock(LockStoreDataBaseDAO.java:170)
	at io.seata.server.storage.db.lock.DataBaseLocker.acquireLock(DataBaseLocker.java:59)
	at io.seata.server.lock.AbstractLockManager.acquireLock(AbstractLockManager.java:59)
	at io.seata.server.session.BranchSession.lock(BranchSession.java:278)
	at io.seata.server.transaction.at.ATCore.branchSessionLock(ATCore.java:46)

### Ⅲ. Describe what you expected to happen
是否需要将mysql serever端提供的脚本`lock_table`.`table_name` VARCHAR(64)  调整到64长度或更大 

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

customer_sales_profit_breakdown_info

### Ⅵ. Environment:

- JDK version :1.8
- OS : centos7
- Others:  seata 1.4

**Comment by a364176773** [comment]
自己调整大小，这是允许的
