### ISSUE TITLE
Seata 1.4.0与spring-cloud-starter-openfeign兼容问题？

### ISSUE THREAD

**Issue by Jian0110** [seata/seata#3449]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
当我是用Seata 1.4.0整合spring-cloud-starter-openfeign 2.2.0.RELEASE时候出现以下异常，之后将2.0.更改为2.1.2.RELEASE、2.2.1.RELEASE、2.2.3.RELEASE都会出现如下异常，但我去掉openfeign能正常运行

### Ⅱ. Describe what happened

 exception trace:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'feignClient' defined in class path resource [org/springframework/cloud/openfeign/ribbon/DefaultFeignLoadBalancedConfiguration.class]: Initialization of bean failed; nested exception is java.lang.IllegalAccessError: tried to access class org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient from class com.alibaba.cloud.seata.feign.SeataFeignObjectWrapper
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at com.springcloud.SeataOrderServiceApplication.main(SeataOrderServiceApplication.java:16) [classes/:na]
Caused by: java.lang.IllegalAccessError: tried to access class org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient from class com.alibaba.cloud.seata.feign.SeataFeignObjectWrapper
	at com.alibaba.cloud.seata.feign.SeataFeignObjectWrapper.wrap(SeataFeignObjectWrapper.java:54) ~[spring-cloud-starter-alibaba-seata-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at com.alibaba.cloud.seata.feign.SeataLoadBalancerFeignClient.<init>(SeataLoadBalancerFeignClient.java:39) ~[spring-cloud-starter-alibaba-seata-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at com.alibaba.cloud.seata.feign.SeataFeignObjectWrapper.wrap(SeataFeignObjectWrapper.java:52) ~[spring-cloud-starter-alibaba-seata-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at com.alibaba.cloud.seata.feign.SeataBeanPostProcessor.postProcessBeforeInitialization(SeataBeanPostProcessor.java:36) ~[spring-cloud-starter-alibaba-seata-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	... 15 common frames omitted
```

### Ⅲ. Describe what you expected to happen
是否是版本兼容问题，或者是其它？我的版本请看下面

### Ⅵ. Environment:

- JDK version : 1.8
- OS :
- Others: 
```
      <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>2.2.0.RELEASE</version>
        </dependency>
     <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.4.0</version>
        </dependency>
     <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2.2.1.RELEASE</version>
            <!-- 2.2.1内嵌seata-spring-boot-starter 1.1.0 -->
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
       </dependency>
```

**Comment by litianyu1992** [comment]
可以提交一个复现demo么

**Comment by Jian0110** [comment]
> 可以提交一个复现demo么

[seata.zip](https://github.com/seata/seata/files/5780060/seata.zip)

其中order-servie通过feign调用account与storage服务，order服务启动报异常，account与storage没有异常，正常运行能注册nacos 1.1.4

**Comment by litianyu1992** [comment]
![image](https://user-images.githubusercontent.com/33249961/103865702-8a2cb380-50ff-11eb-8f03-7ebdb3ed8647.png)
这是你的父工程么

**Comment by litianyu1992** [comment]
你的demo编译报错，我复制了你的pom，去除了nacos和服务注册中心。启动没有问题

**Comment by Jian0110** [comment]
对的，不好意思，刚才没发全，我重新重构了下Demo结构
[cloud-alibaba-seat.zip](https://github.com/seata/seata/files/5780300/cloud-alibaba-seat.zip)
seata的父工程现在是：com:cloud-alibaba

**Comment by litianyu1992** [comment]
公司网不行。。。 maven 我更新不动。。。

**Comment by Jian0110** [comment]
后来发现spring-cloud-starter-alibaba-seata中的SeataFeignObjectWrapper依赖：

1. `org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient`，而引入的openfeign没有BlockingLoadBalancerClient这个类，需要的单独再引入spring-cloud-starter-loadbalancer包，而奇怪的是openfeign中虽然引入了spring-cloud-starter-loadbalancer包，但没有`BlockingLoadBalancerClient`这个类，查看源码，如下图红字部分表示找不到该路径下的类：
![SeataFeignObjectWrapper](https://user-images.githubusercontent.com/33727408/103969680-69b53580-51a1-11eb-92f8-c4058c24b815.png)

2. 就是 `SeataFeignObjectWrapper`引入的负载器`FeignBlockingLoadBalancerClient`，在openfeign包不是public类，无法被外部引用。这点issue中有人有类似的错误：`nested exception is java.lang.IllegalAccessError: tried to access class org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient from class com.alibaba.cloud.seata.feign.SeataFeignObjectWrapper`
[SeataFeignObjectWrapper 创建 feignClient 失败 #3115](https://github.com/seata/seata/issues/3115)

这是选择openfeign版本问题吗？

**Comment by szwkang** [comment]
@Jian0110 请问这个问题解决了啊

**Comment by MrYangJ** [comment]
父工程的pom    dependencyManagement
`<spring.cloud.version>Hoxton.SR7</spring.cloud.version>`

`      <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>`


子工程真正的整合feign
` 
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>guava</artifactId>
                    <groupId>com.google.guava</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-loadbalancer</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>guava</artifactId>
                    <groupId>com.google.guava</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        `


老哥 我之前也遇到你说的问题，后来换了一个spring cloud的版本 就没这个问题
springboot 是2.2.8.RELEASE
spring cloud alibaba是2.2.3.RELEASE
希望对你有所帮助

**Comment by a364176773** [comment]
此问题应该反馈到spring cloud alibaba社区

**Comment by wangrqsh** [comment]
<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-seata</artifactId>
			<version>2.2.0.RELEASE</version>
		</dependency>
