### ISSUE TITLE
偶发空指针异常

### ISSUE THREAD

**Issue by aluohe** [seata/seata#3489]
Caused by: java.lang.NullPointerException: null
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:159)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:83)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.kamowl.kamo.cloud.order.center.service.impl.SysOrderServiceImpl$$EnhancerBySpringCGLIB$$1.doLoading(<generated>)
	at com.kamowl.kamo.cloud.order.center.controller.SysOrderController.doLoading(SysOrderController.java:441)
	... 140 common frames omitted

**Comment by a364176773** [comment]
请问是什么版本呢？

**Comment by aluohe** [comment]
1.2.0 版本，事务回滚时，10-30次异常回滚会触发一次该空指针异常，导致事务回滚不完整，产生脏数据

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/105945478-4f83be80-60a0-11eb-9b95-519175975f89.png)
![image](https://user-images.githubusercontent.com/8758457/105945544-6de9ba00-60a0-11eb-9874-f4320abe8dc7.png)
![image](https://user-images.githubusercontent.com/8758457/105945565-7e019980-60a0-11eb-8eb1-88a35656ff4c.png)

**Comment by aluohe** [comment]
seata 版本问题，1.3之前版本 无序，之后有序 timestamp 添加精度
