### ISSUE TITLE
Nacos为注册中心并修改密码（含特殊字符）后，Seata1.4.0无法正确识别密码并注册到Nacos中

### ISSUE THREAD

**Issue by nicollcheng** [seata/seata#3511]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
当使用Nacos(已设置访问Nacos的需要认证)作为注册中心时，且成功修改nacos的密码为`!Y@Z#F$A%R.1\2/3^4&5*6(7)8_9+a{f}a|s'f,a?s<d>s~f`，然后将该Nacos作为Seata的注册中心，当我配置完成Seata配置文件后，无法启动Seata服务端

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
```
SLF4J: A number (18) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
11:42:24.550  INFO --- [                     main] io.seata.config.FileConfiguration        : The file name of the operation is registry
11:42:24.557  INFO --- [                     main] io.seata.config.FileConfiguration        : The configuration file used is D:\SimpleCode\seata\conf\registry.conf
11:42:24.646  INFO --- [                     main] io.seata.config.FileConfiguration        : The file name of the operation is file.conf
11:42:24.647  INFO --- [                     main] io.seata.config.FileConfiguration        : The configuration file used is file.conf
11:42:26.134  INFO --- [                     main] i.s.core.rpc.netty.NettyServerBootstrap  : Server started, listen port: 8091
11:42:27.606 ERROR --- [                     main] io.seata.server.Server                   : nettyServer init error:ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Sun Feb 07 11:42:27 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
==>
java.lang.RuntimeException: ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Sun Feb 07 11:42:27 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
        at io.seata.core.rpc.netty.NettyServerBootstrap.start(NettyServerBootstrap.java:157) ~[seata-core-1.4.0.jar:na]
        at io.seata.core.rpc.netty.AbstractNettyRemotingServer.init(AbstractNettyRemotingServer.java:55) ~[seata-core-1.4.0.jar:na]
        at io.seata.core.rpc.netty.NettyRemotingServer.init(NettyRemotingServer.java:52) ~[seata-core-1.4.0.jar:na]
        at io.seata.server.Server.main(Server.java:102) ~[seata-server-1.4.0.jar:na]
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Sun Feb 07 11:42:27 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:552) ~[nacos-client-1.3.3.jar:na]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491) ~[nacos-client-1.3.3.jar:na]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486) ~[nacos-client-1.3.3.jar:na]
        at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:239) ~[nacos-client-1.3.3.jar:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:200) ~[nacos-client-1.3.3.jar:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:185) ~[nacos-client-1.3.3.jar:na]
        at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:85) ~[seata-discovery-nacos-1.4.0.jar:na]
        at io.seata.core.rpc.netty.NettyServerBootstrap.start(NettyServerBootstrap.java:153) ~[seata-core-1.4.0.jar:na]
        ... 3 common frames omitted
<==
```

### Ⅲ. Describe what you expected to happen
既然在Nacos中可以成功修改为带特殊字符的密码，我想在支持使用Nacos为注册/配置中心的Seata应该也支持解析配置的该密码

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 使用Nacos 1.4.1 作为注册中心，并开启认证
2. 修改nacos的密码为`!Y@Z#F$A%R.1\2/3^4&5*6(7)8_9+a{f}a|s'f,a?s<d>s~f`
3. 配置Seata1.4.0的注册中心为该Nacos
4. 启动Seata就无法连接到Nacos

### Ⅴ. Anything else we need to know?
`registry.conf`中，下面为相关配置

```conf
type = "nacos"
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "nacos"
  loadBalance = "RandomLoadBalance"
  loadBalanceVirtualNodes = 10

  nacos {
    application = "seata-server"
    serverAddr = "127.0.0.1:8848"
    group = "SEATA_GROUP"
    namespace = ""
    cluster = "default"
    username = "nacos"
    password = "!Y@Z#F$A%R.1\2/3^4&5*6(7)8_9+a{f}a|s'f,a?s<d>s~f"
  }
}
```

源码对应异常信息：
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.seata.server.ParameterParser.init(ParameterParser.java:87)
	at io.seata.server.ParameterParser.<init>(ParameterParser.java:60)
	at io.seata.server.Server.main(Server.java:72)
Caused by: io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.config.file.FileConfig caused by java.lang.IllegalStateException: Extension instance(definition: io.seata.common.loader.ExtensionDefinition@7df258d5, class: interface io.seata.config.file.FileConfig)  could not be instantiated: null
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:399)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:388)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:356)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:281)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$400(EnhancedServiceLoader.java:190)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:128)
	at io.seata.config.FileConfigFactory.loadService(FileConfigFactory.java:63)
	at io.seata.config.FileConfigFactory.load(FileConfigFactory.java:49)
	at io.seata.config.FileConfiguration.<init>(FileConfiguration.java:113)
	at io.seata.config.ConfigurationFactory.load(ConfigurationFactory.java:63)
	at io.seata.config.ConfigurationFactory.<clinit>(ConfigurationFactory.java:48)
	at io.seata.server.ParameterParser.init(ParameterParser.java:87)
	at io.seata.server.ParameterParser.<init>(ParameterParser.java:60)
	at io.seata.server.Server.main(Server.java:72)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:558)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:395)
	... 13 more
Caused by: com.typesafe.config.ConfigException$Parse: registry.conf: 14: in value for key 'password': backslash followed by '2', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)
	at com.typesafe.config.impl.Parser$ParseContext.nextToken(Parser.java:279)
	at com.typesafe.config.impl.Parser$ParseContext.nextTokenIgnoringNewline(Parser.java:302)
	at com.typesafe.config.impl.Parser$ParseContext.consolidateValueTokens(Parser.java:393)
	at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:796)
	at com.typesafe.config.impl.Parser$ParseContext.parseValue(Parser.java:520)
	at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:803)
	at com.typesafe.config.impl.Parser$ParseContext.parseValue(Parser.java:520)
	at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:803)
	at com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993)
	at com.typesafe.config.impl.Parser.parse(Parser.java:34)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:602)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:554)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:148)
	at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:172)
	at com.typesafe.config.impl.ConfigImpl.parseResourcesAnySyntax(ConfigImpl.java:128)
	at com.typesafe.config.ConfigFactory.parseResourcesAnySyntax(ConfigFactory.java:811)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:113)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:74)
	at io.seata.config.file.SimpleFileConfig.<init>(SimpleFileConfig.java:45)
	... 19 more
```

个人发现应该是配置文件解析问题
![image](https://user-images.githubusercontent.com/64319004/107135755-49130380-6938-11eb-83fc-1a9cd8a697cc.png)

### Ⅵ. Environment:

- JDK version : 1.8
- OS : Window、Linux
- Others: Nacos 1.4.1、Seata 1.4.0

**Comment by caohdgege** [comment]
`!Y@Z#F$A%R.1\\2/3^4&5*6(7)8_9+a{f}a|s'f,a?s<d>s~f` 试一下这样？

**Comment by nicollcheng** [comment]
@caohdgege 还是一样报错，其中我使用过的密码，其中有一个@字符也是不行的，其他字符没有测试过

**Comment by a364176773** [comment]
配置的时候配置成转义后的字符可行吗？

**Comment by slievrly** [comment]
@nicollcheng to manually modify the password for nacos configuration center under ` !Y@Z#F$A%R.1\2/3^4&5*6(7)8_9+a{f}a|s'f,a?s<d>s~f` to solve the problem

**Comment by nicollcheng** [comment]
I know this plan. But I think we should specify in Seata's documentation that Seata supports the password requirements for parsing, to prevent users from setting complex passwords with special symbols in Nacos, but Seata cannot resolve them and cause Seata services to fail to start. @slievrly
