### ISSUE TITLE
seata1.3 at模式下 偶发出现 locktable写入时主键重复

### ISSUE THREAD

**Issue by livingstone29** [seata/seata#3521]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
TC端偶发的报错 看异常信息应该是写入locktable时主键重复

### Ⅱ. Describe what happened
偶发
TC端日志 
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'jdbc:mysql://10.5.9.42:3306/interfacecenter^^^t_dmsif_jk003_01' for
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
        at io.seata.server.storage.db.lock.LockStoreDataBaseDAO.doAcquireLock(LockStoreDataBaseDAO.java:313)
        ... 24 common frames omitted

客户端日志
PreparedStatementCallback; uncategorized SQLException for SQL [DELETE FROM T_DMSIF_JK513_01 WHERE IIDMS_ID =? ]; SQL state [null]; error code [0]; io.seata.core.exception.RmTransactionException: Response[ TransactionException[branch register request failed. xid=10.128.45.55:8091:105037255928934400, msg=Duplicate entry 'jdbc:mysql:/ ]; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[branch register request failed. xid=10.128.45.55:8091:105037255928934400, msg=Duplicate entry 'jdbc:mysql:/ ]

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : openshift 
- Others: springboot 2.1.9

**Comment by a364176773** [comment]
原因已查明,tc的数据库存在读写分离的情况,导致锁重入时无法剔除已经持有的锁信息(因为从库还没同步到),导致又去竞争了已持有的锁,出现了冲突.
说明:分布式事务是一个一致性的场景,保证一致性就不应该让tc使用的库存在读写分离的情况,否者将造成不一致情况,比如查询从库分支事务数据的时候,因为没同步到,导致漏了一个分支事务没去提交,一致性就会受到破坏.
