### ISSUE TITLE
seata1.4.0 启动报错

### ISSUE THREAD

**Issue by tanggen** [seata/seata#3525]
重启seata服务时，报错如下，导致无法启动
Caused by: java.lang.NullPointerException
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.seata.server.storage.redis.store.RedisTransactionStoreManager.readBranchSessionByXid(RedisTransactionStoreManager.java:463)
	at io.seata.server.storage.redis.store.RedisTransactionStoreManager.readSession(RedisTransactionStoreManager.java:318)
	at io.seata.server.storage.redis.store.RedisTransactionStoreManager.lambda$readSession$2(RedisTransactionStoreManager.java:357)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

**Comment by tanggen** [comment]
升级到1.4.1后，看代码这块是没动过，所以这个问题还是存在，运行一会之后就会报错，看样子是gmtCreate为空，导致排序时报空指针

**Comment by xingfudeshi** [comment]
@tanggen Can you submit a PR to fix it?

**Comment by tanggen** [comment]
@xingfudeshi 陈健斌已修复此问题，我进行压力测试，检查问题是否修复
