### ISSUE TITLE
seata is not compatible with mysql-connector 8.0.22 when using shardingjdbc

### ISSUE THREAD

**Issue by techa03** [seata/seata#3541]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata 1.3+shardingjdbc4.1.1+mysql-connector

```
  @DubboReference
    private SeckillService seckillService;
    @DubboReference
    private GoodsService goodsService;

    /**
     * 测试seata分布式事务
     */
    @GetMapping("/test")
    @GlobalTransactional
    public void testGlobalTransaction() {
        Goods goods = new Goods();
        goods.setName("test");
        goodsService.addGoods(goods, null);
        Seckill seckill = seckillService.getById(1001L);
        seckill.setNumber(seckill.getNumber() - 1);
        seckillService.saveOrUpdate(seckill);
        // 测试异常情况
        throw new RuntimeException();
    }
```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

when I use mysql-connector-java 8.0.21 driver it works fine,but when I swtich to 8.0.22 the console prints the error message like this:
```
17:21:15.973 [DubboServerHandler-192.168.2.143:20880-thread-21] INFO  ShardingSphere-SQL - Logic SQL: INSERT INTO undo_log (branch_id, xid, context, rollback_info, log_status, log_created, log_modified) VALUES (?, ?, ?, ?, ?, now(6), now(6))
17:21:15.973 [DubboServerHandler-192.168.2.143:20880-thread-21] INFO  ShardingSphere-SQL - SQLStatement: InsertStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.InsertStatement@1bf41792, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@fa81293), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@fa81293, columnNames=[branch_id, xid, context, rollback_info, log_status, log_created, log_modified], insertValueContexts=[InsertValueContext(parametersCount=5, valueExpressions=[ParameterMarkerExpressionSegment(startIndex=109, stopIndex=109, parameterMarkerIndex=0), ParameterMarkerExpressionSegment(startIndex=112, stopIndex=112, parameterMarkerIndex=1), ParameterMarkerExpressionSegment(startIndex=115, stopIndex=115, parameterMarkerIndex=2), ParameterMarkerExpressionSegment(startIndex=118, stopIndex=118, parameterMarkerIndex=3), ParameterMarkerExpressionSegment(startIndex=121, stopIndex=121, parameterMarkerIndex=4), org.apache.shardingsphere.sql.parser.sql.segment.dml.item.ExpressionProjectionSegment@6bb8a8cd, org.apache.shardingsphere.sql.parser.sql.segment.dml.item.ExpressionProjectionSegment@309a9f30], parameters=[102455421153374208, 192.168.2.143:8091:102455407425417216, serializer=jackson, javax.sql.rowset.serial.SerialBlob@1af7721d, 0])], generatedKeyContext=Optional.empty)
17:21:15.973 [DubboServerHandler-192.168.2.143:20880-thread-21] INFO  ShardingSphere-SQL - Actual SQL: ds0 ::: INSERT INTO undo_log (branch_id, xid, context, rollback_info, log_status, log_created, log_modified) VALUES (?, ?, ?, ?, ?, now(6), now(6)) ::: [102455421153374208, 192.168.2.143:8091:102455407425417216, serializer=jackson, javax.sql.rowset.serial.SerialBlob@1af7721d, 0]
17:21:16.026 [rpcDispatch_RMROLE_1_2_8] INFO  i.s.c.r.p.c.RmBranchRollbackProcessor - rm handle branch rollback process:xid=192.168.2.143:8091:102455407425417216,branchId=102455421153374208,branchType=AT,resourceId=jdbc:mysql://mysql:3306/seckill,applicationData=null
17:21:16.067 [rpcDispatch_RMROLE_1_2_8] INFO  i.s.r.AbstractRMHandler - Branch Rollbacking: 192.168.2.143:8091:102455407425417216 102455421153374208 jdbc:mysql://mysql:3306/seckill
17:21:16.087 [rpcDispatch_RMROLE_1_2_8] INFO  ShardingSphere-SQL - Logic SQL: SELECT * FROM undo_log WHERE branch_id = ? AND xid = ? FOR UPDATE
17:21:16.087 [rpcDispatch_RMROLE_1_2_8] INFO  ShardingSphere-SQL - SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@74c75df4, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@244d9163), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@244d9163, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=7, distinctRow=false, projections=[ShorthandProjection(owner=Optional.empty, actualColumns=[ColumnProjection(owner=null, name=id, alias=Optional.empty), ColumnProjection(owner=null, name=branch_id, alias=Optional.empty), ColumnProjection(owner=null, name=xid, alias=Optional.empty), ColumnProjection(owner=null, name=context, alias=Optional.empty), ColumnProjection(owner=null, name=rollback_info, alias=Optional.empty), ColumnProjection(owner=null, name=log_status, alias=Optional.empty), ColumnProjection(owner=null, name=log_created, alias=Optional.empty), ColumnProjection(owner=null, name=log_modified, alias=Optional.empty), ColumnProjection(owner=null, name=ext, alias=Optional.empty)])]), groupByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.groupby.GroupByContext@63949b71, orderByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.orderby.OrderByContext@42b32cdc, paginationContext=org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext@cd5f183, containsSubquery=false)
17:21:16.087 [rpcDispatch_RMROLE_1_2_8] INFO  ShardingSphere-SQL - Actual SQL: ds0 ::: SELECT * FROM undo_log WHERE branch_id = ? AND xid = ? FOR UPDATE ::: [102455421153374208, 192.168.2.143:8091:102455407425417216]
17:21:16.098 [rpcDispatch_RMROLE_1_2_8] ERROR i.s.r.d.u.p.JacksonUndoLogParser - json decode exception, Unexpected character ('¬' (code 172)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"�� sr "javax.sql.rowset.serial.SerialBlob��kQ��� J lenJ origLenL blobt Ljava/sql/Blob;[ buft [Bxp      E      Epur [B���T�  xp  E{"@class":"io.seata.rm.datasource.undo.BranchUndoLog","xid":"192.168.2.143:8091:102455407425417216","branchId":102455421153374208,"sqlUndoLogs":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.undo.SQLUndoLog","sqlType":"INSERT","tableName":"seckill","beforeImage":{"@class":"io.seata.rm.datasource.sql.struct.TableRecords$EmptyTableRecords","t"[truncated 1509 bytes]; line: 1, column: 2]
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('¬' (code 172)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"�� sr "javax.sql.rowset.serial.SerialBlob��kQ��� J lenJ origLenL blobt Ljava/sql/Blob;[ buft [Bxp      E      Epur [B���T�  xp  E{"@class":"io.seata.rm.datasource.undo.BranchUndoLog","xid":"192.168.2.143:8091:102455407425417216","branchId":102455421153374208,"sqlUndoLogs":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.undo.SQLUndoLog","sqlType":"INSERT","tableName":"seckill","beforeImage":{"@class":"io.seata.rm.datasource.sql.struct.TableRecords$EmptyTableRecords","t"[truncated 1509 bytes]; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:632)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2686)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:865)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:757)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4664)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4513)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3529)
	at io.seata.rm.datasource.undo.parser.JacksonUndoLogParser.decode(JacksonUndoLogParser.java:139)
	at io.seata.rm.datasource.undo.AbstractUndoLogManager.undo(AbstractUndoLogManager.java:276)
	at io.seata.rm.datasource.DataSourceManager.branchRollback(DataSourceManager.java:178)
	at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:125)
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:67)
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:63)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116)
	at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:63)
	at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:63)
	at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35)
	at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150)
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.handleBranchRollback(RmBranchRollbackProcessor.java:63)
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.process(RmBranchRollbackProcessor.java:58)
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:265)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
17:21:16.117 [rpcDispatch_RMROLE_1_2_8] INFO  i.s.r.d.DataSourceManager - branchRollback failed. branchType:[AT], xid:[192.168.2.143:8091:102455407425417216], branchId:[102455421153374208], resourceId:[jdbc:mysql://mysql:3306/seckill], applicationData:[null]. reason:[Branch session rollback failed and try again later xid = 192.168.2.143:8091:102455407425417216 branchId = 102455421153374208 com.fasterxml.jackson.core.JsonParseException: Unexpected character ('¬' (code 172)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"�� sr "javax.sql.rowset.serial.SerialBlob��kQ��� J lenJ origLenL blobt Ljava/sql/Blob;[ buft [Bxp      E      Epur [B���T�  xp  E{"@class":"io.seata.rm.datasource.undo.BranchUndoLog","xid":"192.168.2.143:8091:102455407425417216","branchId":102455421153374208,"sqlUndoLogs":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.undo.SQLUndoLog","sqlType":"INSERT","tableName":"seckill","beforeImage":{"@class":"io.seata.rm.datasource.sql.struct.TableRecords$EmptyTableRecords","t"[truncated 1509 bytes]; line: 1, column: 2]]
17:21:16.122 [rpcDispatch_RMROLE_1_2_8] INFO  i.s.r.AbstractRMHandler - Branch Rollbacked result: PhaseTwo_RollbackFailed_Retryable
17:21:16.144 [http-nio-8080-exec-3] INFO  i.s.t.a.DefaultGlobalTransaction - [192.168.2.143:8091:102455407425417216] rollback status: RollbackRetrying
17:21:16.155 [http-nio-8080-exec-3] WARN  i.s.t.a.DefaultFailureHandlerImpl - Retrying to rollback transaction[192.168.2.143:8091:102455407425417216]
17:21:16.168 [http-nio-8080-exec-3] ERROR o.s.w.c.GlobalExceptionHandler - null
java.lang.RuntimeException: null
	at org.seckill.web.controller.GoodsController.add(GoodsController.java:46)
	at org.seckill.web.controller.GoodsController$$FastClassBySpringCGLIB$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$1.execute(GlobalTransactionalInterceptor.java:150)
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:104)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:147)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:122)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at org.seckill.web.controller.GoodsController$$EnhancerBySpringCGLIB$$1.add(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.cloud.sleuth.instrument.web.servlet.TracingFilter.doFilter(TracingFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.knife4j.spring.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.knife4j.spring.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:90)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:141)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.cloud.sleuth.instrument.web.servlet.TracingFilter.doFilter(TracingFilter.java:89)
	at org.springframework.cloud.sleuth.autoconfig.instrument.web.LazyTracingFilter.doFilter(TraceWebServletConfiguration.java:121)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:97)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:41002)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
17:21:16.658 [rpcDispatch_RMROLE_1_3_8] INFO  i.s.c.r.p.c.RmBranchRollbackProcessor - rm handle branch rollback process:xid=192.168.2.143:8091:102455407425417216,branchId=102455421153374208,branchType=AT,resourceId=jdbc:mysql://mysql:3306/seckill,applicationData=null
17:21:16.658 [rpcDispatch_RMROLE_1_3_8] INFO  i.s.r.AbstractRMHandler - Branch Rollbacking: 192.168.2.143:8091:102455407425417216 102455421153374208 jdbc:mysql://mysql:3306/seckill
```

### Ⅲ. Describe what you expected to happen
I expected the global transation can be rolled back

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

```
  @DubboReference
    private SeckillService seckillService;
    @DubboReference
    private GoodsService goodsService;

    /**
     * 测试seata分布式事务
     */
    @GetMapping("/test")
    @GlobalTransactional
    public void testGlobalTransaction() {
        Goods goods = new Goods();
        goods.setName("test");
        goodsService.addGoods(goods, null);
        Seckill seckill = seckillService.getById(1001L);
        seckill.setNumber(seckill.getNumber() - 1);
        seckillService.saveOrUpdate(seckill);
        // 测试异常情况
        throw new RuntimeException();
    }
```
1.use seata-server 1.3+
2.use shardingsphere-jdbc4.1.1
3.user mysql-connector-java 8.0.22 driver

here is the maven dependencies:
```
<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-seata</artifactId>
         <version>2.2.3.RELEASE</version>
</dependency>
<dependency>
	<groupId>mysql</groupId>
	<artifactId>mysql-connector-java</artifactId>
        <version>8.0.22</version>
</dependency>
<dependency>
           <groupId>org.apache.shardingsphere</groupId>
           <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
          <version>4.1.1</version>
</dependency>
```
### Ⅵ. Environment:

- JDK version : JDK11
- OS : any
- Others: mysql server 8.0.22

**Comment by caohdgege** [comment]
对这个进行一个简单的复盘，

首先Seata会记录数据插入的前后镜像，然后插入到一张undo_log表，这个就不在重复了。。。

然后你这个是MySQL的，在插入undo_log的时候，seata用的setBlob去设置rollback_info这个字段，接下来到shardingjdbc部分的代码，跟踪之后发现，他其实是把外层的setXXX统一转成了setObject(index, obj)了。

然后根据你所说的，在connector-java 8.0.21的时候是没问题的，在connector-java 8.0.22才会有问题，重点跟踪了一下他们两个的setObject的方法的区别。

对于8.0.22，可以重点关注这里(过程不贴了，debug过程有兴趣可以自己跟一下)：
![image](https://user-images.githubusercontent.com/22959373/109522926-c1a95200-7ae9-11eb-96f7-2fade581a421.png)

对于8.0.21，可以重点关注这里：
![image](https://user-images.githubusercontent.com/22959373/109523016-d71e7c00-7ae9-11eb-840d-61301055a44f.png)
![image](https://user-images.githubusercontent.com/22959373/109523240-19e05400-7aea-11eb-95e0-b6c31b6cd69c.png)



可以很明显的看出，在8.0.21的版本下，使用x.getBinaryStream去获得字节流，然后再去设值的；在8.0.22的版本下，是有使用obj.toString()这个方法，从而改变了我们的blob的变量的值，从而导致取出的数据是不正确的。
所以严格意义上来说，这个应该算是jdbc驱动的bug。。。seata这边的话，会优化一下，避免在数据源为MySQL的情况下使用setBlob。

**Comment by caohdgege** [comment]
可以关注一下#3555，看是否解决了你这个问题。
