### ISSUE TITLE
DataSourceProvider name is null

### ISSUE THREAD

**Issue by suinxinliulang** [seata/seata#3564]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用docker-compose启动 **seata-server 1.4.1** 启动失败，报错提示：
`the name of service provider for [io.seata.core.store.db.DataSourceProvider] name is null`

### Ⅱ. Describe what happened
- 如果`STORE_MODE=file`是可以启动的，只修改registry中的配置也可以正常启动，能在nacos中看到seata-server服务
- 若配置`STORE_MODE=db`就会启动失败
- 使用二级制文件，然后将mode改为db，在本地windows中可以正常启动，怀疑docker镜像有问题
错误栈信息如下：
```
seata-server    | 01:25:18.536  INFO --- [                     main] io.seata.config.FileConfiguration        : The configuration file used is /root/seata-config/registry.conf
seata-server    | Exception in thread "main" io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.server.session.SessionManager caused by java.lang.IllegalStateException: Extension instance(definition: io.seata.common.loader.ExtensionDefinition@ef0a1b29, class: interface io.seata.server.session.SessionManager)  could not be instantiated: the name of service provider for [io.seata.core.store.db.DataSourceProvider] name is null
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:399)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:388)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:356)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:245)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:190)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:82)
seata-server    |       at io.seata.server.session.SessionHolder.init(SessionHolder.java:90)
seata-server    |       at io.seata.server.Server.main(Server.java:84)
seata-server    | Caused by: java.lang.IllegalArgumentException: the name of service provider for [io.seata.core.store.db.DataSourceProvider] name is null
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:351)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:245)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:190)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:82)
seata-server    |       at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.<init>(DataBaseTransactionStoreManager.java:95)
seata-server    |       at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.getInstance(DataBaseTransactionStoreManager.java:81)
seata-server    |       at io.seata.server.storage.db.session.DataBaseSessionManager.init(DataBaseSessionManager.java:77)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:564)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:395)
seata-server    |       ... 7 more
seata-server    |
seata-server exited with code 1
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
docker-compose配置如下:
```yml
version: "3"
services:
  seata-server:
    image: seataio/seata-server:1.4.1
    hostname: seata-server
    container_name: seata-server
    ports:
      - 8091:8091
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=db
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      - ./config:/root/seata-config
    networks:
      - union-net

networks:
  union-net:
    external: true
```

对应 registry.conf配置如下：
```text
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "nacos"
  loadBalance = "RandomLoadBalance"
  loadBalanceVirtualNodes = 10

  nacos {
    application = "seata-server"
    serverAddr = "localhost:8848"
    group = "SEATA_GROUP"
    namespace = ""
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "nacos"

  nacos {
    serverAddr = "localhost:8848"
    namespace = ""
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
  }
}
```

### Ⅴ. Anything else we need to know?
None

### Ⅵ. Environment:
- JDK version : jdk1.8.0_281
- OS :  win10子系统Ubuntu20.04LTS
- Others:  none

**Comment by a364176773** [comment]
nacos中配置
store.db.datasource=druid

**Comment by suinxinliulang** [comment]
> nacos中配置
> store.db.datasource=druid

谢谢

**Comment by jasmine4y** [comment]
为什么我还是启动不了，报一样的错,@suinxinliulang
![image](https://user-images.githubusercontent.com/29448988/110411954-64536900-80c6-11eb-9f2b-8b1ef642ba0a.png)
![image](https://user-images.githubusercontent.com/29448988/110411977-703f2b00-80c6-11eb-9df8-84594521f4d1.png)
![image](https://user-images.githubusercontent.com/29448988/110412001-792ffc80-80c6-11eb-98cd-2960b2194bec.png)

**Comment by czbxyls** [comment]
我也是这个问题，解决了。如果nacos也是用docker启动的话，会出现这个问题。一种解决方案是把mysql、nacos、seata配置在同一网桥，将serverAddr = "localhost:8848"的localhost改成nacos在docker 网桥中的地址 ，这样在docker容器中seata才能正常访问到nacos。(docker network inspect {net_name}可查看网桥中容器的IP地址)

**Comment by Contentsearch** [comment]
不是docker部署的也出现这种错误，是什么原因
