### ISSUE TITLE
使用最新的spring cloud 2020.0.2 无法启动

### ISSUE THREAD

**Issue by aohanhe** [seata/seata#3609]
应该是新版本的openfeign没有使用ribbon,结果程序启动时报以下错误，从而没有办法启动。
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.openfeign.ribbon.CachingSpringLoadBalancerFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
        ... 45 common frames omitted

**Comment by a364176773** [comment]
请反馈给springcloudalibaba社区

**Comment by fliu0721** [comment]
怎么解决的?
