### ISSUE TITLE
1.4.1升级到1.4.2后,apollo config 报错

### ISSUE THREAD

**Issue by lehug** [seata/seata#3677]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata server 1.4.1 -> 1.4.2, registry config from apollo, not change codes or configs.
1.4.1 works well, but 1.4.2 cannot run

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
SLF4J: A number (17) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
02:10:00.280  INFO --- [                     main] io.seata.server.Server                   : The server is running in container.
02:10:00.380  INFO --- [                     main] io.seata.config.FileConfiguration        : The file name of the operation is file:/root/seata-config/registry
02:10:00.382  INFO --- [                     main] io.seata.config.FileConfiguration        : The configuration file used is /root/seata-config/registry.conf
Exception in thread "main" java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:460)
        at java.util.Properties.setProperty(Properties.java:166)
        at java.lang.System.setProperty(System.java:798)
        at io.seata.config.apollo.ApolloConfiguration.readyApolloConfig(ApolloConfiguration.java:188)
        at io.seata.config.apollo.ApolloConfiguration.<init>(ApolloConfiguration.java:77)
        at io.seata.config.apollo.ApolloConfiguration.getInstance(ApolloConfiguration.java:111)
        at io.seata.config.apollo.ApolloConfigurationProvider.provide(ApolloConfigurationProvider.java:29)
        at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:131)
        at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:94)
        at io.seata.server.ParameterParser.init(ParameterParser.java:84)
        at io.seata.server.ParameterParser.<init>(ParameterParser.java:60)
        at io.seata.server.Server.main(Server.java:63)

```

**Comment by lehug** [comment]
[#3116] support configuring apollo configService and cluster  
relate to this commit

**Comment by a364176773** [comment]
请先回退1.4.1或之前版本，此问题将在1.5.0上被修复

**Comment by lightClouds917** [comment]
assign to me,i will fix
