### ISSUE TITLE
 服务启，Druid数库链接代理报错。。。。

### ISSUE THREAD

**Issue by catman002** [seata/seata#3682]
### Ⅲ. Describe what you expected to happen
我的业务服务启动的时候，经常报下面的错误（10次启动有8次报下面的错，偶尔有成功的时候），帮看下怎么解决吧。
```
2021-04-28 13:22:19.411  INFO 1 --- [           main] c.netflix.config.DynamicPropertyFactory  : DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@6573d2f7
01:22:20,877 [main] ERROR com.alibaba.druid.pool.DruidDataSource  - init datasource error, url: jdbc:mysql://192.168.1.145:3306/MXL-TEST
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
....
....
```
我的数据库是5.7x, 数据链接用 8和5的都不行，驱动用了8.019或5.x x x：
···
spring.datasource.db1.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.db1.driverClassName=com.mysql.jdbc.Driver
spring.datasource.db1.url=jdbc:mysql://192.168.1.145:3306/MXL-TEST
#spring.datasource.db1.url=jdbc:mysql://192.168.1.148:3306/MXL-TEST
#spring.datasource.db1.url=jdbc:mysql://192.168.1.148:3306/MXL-TEST?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
···

### Ⅵ. Environment:

- JDK version :15
- OS :cenos
- Others: seata 1.4.2
- mysql5.7x or mysql8.x

**Comment by slievrly** [comment]
@catman002 Do you have a more detailed error message? It is not clear from the above that it is associated with Seata.

**Comment by a364176773** [comment]
seata不会去更改你的datasource，只会利用他，底层的连接seata不会影响，出现这个问题应该去排查自己的配置或者网络问题
