### ISSUE TITLE
k8s 环境下的微服务，使用seata ，查看服务日志频繁出错！

### ISSUE THREAD

**Issue by catman002** [seata/seata#3688]
k8s环境部署服务，经常出现下面的错误：
```
2021-04-28 19:50:54.569  INFO 1 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : channel inactive: [id: 0x8e3a10d7, L:/10.244.135.44:58192 ! R:/192.168.1.148:8091]
2021-04-28 19:51:01.931 ERROR 1 --- [eoutChecker_2_1] i.s.c.rpc.netty.AbstractNettyRemoting    : wait response error:cost 30001 ms,ip:/192.168.1.148:8091,request:RegisterRMRequest{resourceIds='null', applicationId='basetask', transactionServiceGroup='seata_basetask_group'}
2021-04-28 19:51:01.932 ERROR 1 --- [eoutChecker_2_1] i.s.c.r.netty.NettyClientChannelManager  : 0304 register RM failed.

io.seata.common.exception.FrameworkException: register RMROLE error, errMsg:cost 30001 ms
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:78) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:34) ~[seata-all-1.3.0.jar!/:1.3.0]
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220) ~[commons-pool-1.6.jar!/:1.6]
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:206) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:103) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:175) ~[seata-all-1.3.0.jar!/:1.3.0]
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:106) ~[seata-all-1.3.0.jar!/:1.3.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.55.Final.jar!/:4.1.55.Final]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

2021-04-28 19:51:01.932  INFO 1 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : channel valid false,channel:[id: 0x0e374da0, L:/10.244.135.44:57740 ! R:/192.168.1.148:8091]
2021-04-28 19:51:01.932  INFO 1 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x0e374da0, L:/10.244.135.44:57740 ! R:/192.168.1.148:8091]
```

**Comment by HelloWorldHelloPKU** [comment]
同样出现 用到最初的demo，一会连接成功了，一会0304了，交替出现

**Comment by a364176773** [comment]
192.168.1.148 8091
检查网络
