### ISSUE TITLE
app.jar在主机环境（nacos作为注册中心和配置中心+seata）下无报错，但将app.jar打成镜像在主机模式下部署seata报错

### ISSUE THREAD

**Issue by 123Sayhi** [seata/seata#3691]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

因为公司目前在尝试将业务系统容器化，所以我尝试把jar包（nacos，seata这些还是在主机上部署，并未容器化）在主机模式下build & run，网关，权限这些build & run都可以正常注册到nacos，可以正常使用。但是一些使用了seata的jar包，在我build & run之后（docker run -p 9007:9007 --name contract 10.11.210.122:5000/contract:1.0）
报错如下

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[07:28:54:835] [ERROR] - org.springframework.boot.SpringApplication.reportFailure(SpringApplication.java:826) - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'globalTransactionScanner' defined in class path resource [io/seata/spring/boot/autoconfigure/SeataAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:229) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:722) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
        at com.cscec.informationcenter.contract_relative.ContractRelative.main(ContractRelative.java:16) [classes!/:1.0.0]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [1.0.0.jar:1.0.0]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        ... 27 more
Caused by: java.lang.ExceptionInInitializerError
        at net.sf.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:166) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:116) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:104) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69) ~[cglib-3.1.jar!/:?]
        at io.seata.config.ConfigurationCache.proxy(ConfigurationCache.java:79) ~[seata-all-1.3.0.jar!/:1.3.0]
        at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:140) ~[seata-all-1.3.0.jar!/:1.3.0]
        at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:90) ~[seata-all-1.3.0.jar!/:1.3.0]
        at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:81) ~[seata-all-1.3.0.jar!/:1.3.0]
        at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:136) ~[seata-all-1.3.0.jar!/:1.3.0]
        at io.seata.spring.boot.autoconfigure.SeataAutoConfiguration.globalTransactionScanner(SeataAutoConfiguration.java:67) ~[seata-spring-boot-starter-1.3.0.jar!/:?]
        at io.seata.spring.boot.autoconfigure.SeataAutoConfiguration$$EnhancerBySpringCGLIB$$f2df85f7.CGLIB$globalTransactionScanner$2(<generated>) ~[seata-spring-boot-starter-1.3.0.jar!/:?]
        at io.seata.spring.boot.autoconfigure.SeataAutoConfiguration$$EnhancerBySpringCGLIB$$f2df85f7$$FastClassBySpringCGLIB$$56e05f5e.invoke(<generated>) ~[seata-spring-boot-starter-1.3.0.jar!/:?]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at io.seata.spring.boot.autoconfigure.SeataAutoConfiguration$$EnhancerBySpringCGLIB$$f2df85f7.globalTransactionScanner(<generated>) ~[seata-spring-boot-starter-1.3.0.jar!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        ... 27 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @73035e27
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at net.sf.cglib.core.ReflectUtils$2.run(ReflectUtils.java:56) ~[cglib-3.1.jar!/:?]
        at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]
        at net.sf.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:46) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:166) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:116) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:104) ~[cglib-3.1.jar!/:?]
        at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69) ~[cglib-3.1.jar!/:?]
        at io.seata.config.ConfigurationCache.proxy(ConfigurationCache.java:79) ~[seata-all-1.3.0.jar!/:1.3.0]
        at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:140) ~[seata-all-1.3.0.jar!/:1.3.0]
        at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:90) ~[seata-all-1.3.0.jar!/:1.3.0]
        at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:81) ~[seata-all-1.3.0.jar!/:1.3.0]
        at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:136) ~[seata-all-1.3.0.jar!/:1.3.0]
        at io.seata.spring.boot.autoconfigure.SeataAutoConfiguration.globalTransactionScanner(SeataAutoConfiguration.java:67) ~[seata-spring-boot-starter-1.3.0.jar!/:?]
        at io.seata.spring.boot.autoconfigure.SeataAutoConfiguration$$EnhancerBySpringCGLIB$$f2df85f7.CGLIB$globalTransactionScanner$2(<generated>) ~[seata-spring-boot-starter-1.3.0.jar!/:?]
        at io.seata.spring.boot.autoconfigure.SeataAutoConfiguration$$EnhancerBySpringCGLIB$$f2df85f7$$FastClassBySpringCGLIB$$56e05f5e.invoke(<generated>) ~[seata-spring-boot-starter-1.3.0.jar!/:?]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at io.seata.spring.boot.autoconfigure.SeataAutoConfiguration$$EnhancerBySpringCGLIB$$f2df85f7.globalTransactionScanner(<generated>) ~[seata-spring-boot-starter-1.3.0.jar!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
        ... 27 more
```
我以为正常情况下，这个容器也可以正常注册到nacos并提供服务，但是好像出现了常量初始化的错误，以及反射方面的问题，导致bean globalTransactionScanner创建失败，初始化Global Transaction Client失败。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 单机部署nacos，在业务方面使用seata作为分布式事务解决方案，并将nacos作为seata server的注册中心和配置中心
2. 在主机上部署了两个seata节点
3. 将包含seata的业务系统与主机共享ip并打成镜像运行在docker上

### Ⅴ. Anything else we need to know?
在该问题出现后，我在主机上直接运行该jar包是没问题的，但是打包成镜像后运行就有问题，我google了一些解决方案，比如nacos、seata、spring cloud alibaba版本不一致，我使用的openjdk:lastest镜像与本地jdk1.8不同等，但是都不能解决问题，可能是因为前一段时间我将nacos升级到2.0.0版本的原因，导致某些不同，但是在主机环境下运行该系统是没问题的，着实让人困惑，直接运行jar包和打包成镜像运行到底有什么不同。

### Ⅵ. Environment:

- JDK version :主机1.8，docker image openjdk:lastest
- OS :centos 7,docker engine 19.03.5
- Others:nacos 2.0.0 seata server1.3.0
- pom片段
-       <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-seata</artifactId>
            <version>2.2.0.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.3.0</version>
        </dependency>
application-dev.yml中对于seata的配置
#seata配置
spring.cloud.alibaba.seata.tx-service-group=seata_tx_group
seata.enabled=true
seata.application-id=seata-server
seata.tx-service-group=seata_tx_group
seata.enable-auto-data-source-proxy=true
seata.use-jdk-proxy=false
seata.client.rm.async-commit-buffer-limit=1000
seata.client.rm.report-retry-count=5
seata.client.rm.table-meta-check-enable=false
seata.client.rm.report-success-enable=false
seata.client.rm.saga-branch-register-enable=false
seata.client.rm.lock.retry-interval=10
seata.client.rm.lock.retry-times=30
seata.client.rm.lock.retry-policy-branch-rollback-on-conflict=true
seata.client.tm.commit-retry-count=5
seata.client.tm.rollback-retry-count=5
seata.client.undo.data-validation=true
seata.client.undo.log-serialization=jackson
seata.client.undo.log-table=undo_log
seata.client.log.exceptionRate=100
seata.service.vgroup-mapping.seata_tx_group=seatacluster
seata.service.enable-degrade=false
seata.service.disable-global-transaction=false
seata.transport.shutdown.wait=3
seata.transport.thread-factory.boss-thread-prefix=NettyBoss
seata.transport.thread-factory.worker-thread-prefix=NettyServerNIOWorker
seata.transport.thread-factory.server-executor-thread-prefix=NettyServerBizHandler
seata.transport.thread-factory.share-boss-worker=false
seata.transport.thread-factory.client-selector-thread-prefix=NettyClientSelector
seata.transport.thread-factory.client-selector-thread-size=1
seata.transport.thread-factory.client-worker-thread-prefix=NettyClientWorkerThread
seata.transport.thread-factory.worker-thread-size=default
seata.transport.thread-factory.boss-thread-size=1
seata.transport.type=TCP
seata.transport.server=NIO
seata.transport.heartbeat=true
seata.transport.serialization=seata
seata.transport.compressor=none
seata.transport.enable-client-batch-send-request=true
#seata配置中心类型
seata.config.type=nacos
#seata配置中心配置
seata.config.nacos.serverAddr=*.*.*.*:8848
seata.config.nacos.group=SEATA_GROUP
#seata注册类型
seata.registry.type=nacos
#seata注册中心配置
seata.registry.nacos.application=seata-server
seata.registry.nacos.server-addr=*.*.*.*:8848
seata.registry.nacos.group=SEATA_GROUP

**Comment by drgnchan** [comment]
为何docker镜像使用openjdk latest，而不是1.8对应的呢

**Comment by 123Sayhi** [comment]
> 为何码头工人使用openjdk最新，而不是1.8对应的呢

对，解决了，今天我把registry，本地的，远程服务器的镜像全部删除，然后拉取java:8打包运行，然后就成功了！！！！！因为我在docker hub搜java，第一条就是openjdk，然后就没考虑那么多，现在发现的确是java版本的问题~。
