### ISSUE TITLE
使用 redis 注册的问题

### ISSUE THREAD

**Issue by qianxunclub** [seata/seata#3704]
io.seata.discovery.registry.redis.RedisRegistryServiceImpl.java 79行

```
redisConfig.setTestOnBorrow(seataConfig.getBoolean(REDIS_FILEKEY_PREFIX + "test.on.borrow", true));
redisConfig.setTestOnReturn(seataConfig.getBoolean(REDIS_FILEKEY_PREFIX + "test.on.return", false));
redisConfig.setTestWhileIdle(seataConfig.getBoolean(REDIS_FILEKEY_PREFIX + "test.while.idle", false));
```

不知道这几个作用是什么，截取后的字符串不能对应 PropertyClass

```
io.seata.common.exception.ShouldNeverHappenException: PropertyClass for prefix: [seata.registry.redis.test.on] should not be null.
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:106)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:85)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$200(SpringBootConfigurationProvider.java:46)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:61)
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getBoolean(<generated>)
	at io.seata.discovery.registry.redis.RedisRegistryServiceImpl.<init>(RedisRegistryServiceImpl.java:79)
	at io.seata.discovery.registry.redis.RedisRegistryServiceImpl.getInstance(RedisRegistryServiceImpl.java:133)
	at io.seata.discovery.registry.redis.RedisRegistryProvider.provide(RedisRegistryProvider.java:29)
	at io.seata.discovery.registry.RegistryFactory.buildRegistryService(RegistryFactory.java:63)
	at io.seata.discovery.registry.RegistryFactory.getInstance(RegistryFactory.java:43)
	at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:231)
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:166)
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by a364176773** [comment]
问题存在，感谢反馈

**Comment by neighbor-uncleWang** [comment]
@a364176773  从命名上看，这是一个测试的Config，我的理解的话，现阶段直接把这三个干掉。我可以这样做吗？

**Comment by lightClouds917** [comment]
> 问题存在，感谢反馈

Assign to me,thanks.I will fix it.

**Comment by caohdgege** [comment]
> @a364176773 从命名上看，这是一个测试的Config，我的理解的话，现阶段直接把这三个干掉。我可以这样做吗？

这几个其实是jedis的连接参数来的，然后在这里的`test`的含义其实更类似于我们平常说的`心跳检测`，用来测试连接是否依然有效，test.xxx 翻译做在xxx节点检测连接是否有效，如果调整成true会对性能有一定的损耗。

**Comment by neighbor-uncleWang** [comment]
@caohdgege 哦，明白了

**Comment by BillBillLi** [comment]
> > @a364176773 从命名上看，这是一个测试的Config，我的理解的话，现阶段直接把这三个干掉。我可以这样做吗？
> 
> 这几个其实是jedis的连接参数来的，然后在这里的`test`的含义其实更类似于我们平常说的`心跳检测`，用来测试连接是否依然有效，test.xxx 翻译做在xxx节点检测连接是否有效，如果调整成true会对性能有一定的损耗。

1.4.2中没法解决这个问题吗

**Comment by Pinocchio2018** [comment]
Assign to me 
我准备改下配置名
像这样的都改下。比如 `seata.registry.redis.test.on.borrow`  改成  `seata.registry.redis.test-on-borrow`
