### ISSUE TITLE
请问，TCC模式下，rm端线程池默认值是不是太小了？压测时，tcc同步调用rm端commit方法时，会超时

### ISSUE THREAD

**Issue by Pinocchio2018** [seata/seata#3711]
TCC模式，seata server在同步调用rm的commit方法时，会出现
```java
2021-05-08 14:22:25.102 ERROR --- [ ServerHandlerThread_1_10_1000] i.s.c.e.AbstractExceptionHandler         : Catch TransactionException while do RPC, request: xid=10.11.117.6:4426:8845200782043429105,extraData=null
==>
io.seata.core.exception.TransactionException: io.seata.core.exception.BranchTransactionException: Send branch commit failed, xid = 10.11.117.6:4426:8845200782043429105 branchId = 7494120885082147938
        at io.seata.server.coordinator.DefaultCore.lambda$doGlobalCommit$1(DefaultCore.java:240) ~[seata-server-1.4.2.jar:na]
        at io.seata.server.session.SessionHelper.forEach(SessionHelper.java:182) ~[seata-server-1.4.2.jar:na]
        at io.seata.server.coordinator.DefaultCore.doGlobalCommit(DefaultCore.java:192) ~[seata-server-1.4.2.jar:na]
        at io.seata.server.coordinator.DefaultCore.commit(DefaultCore.java:168) ~[seata-server-1.4.2.jar:na]
        at io.seata.server.coordinator.DefaultCoordinator.doGlobalCommit(DefaultCoordinator.java:170) [seata-server-1.4.2.jar:na]
        at io.seata.server.AbstractTCInboundHandler$2.execute(AbstractTCInboundHandler.java:95) ~[seata-server-1.4.2.jar:na]
        at io.seata.server.AbstractTCInboundHandler$2.execute(AbstractTCInboundHandler.java:90) ~[seata-server-1.4.2.jar:na]
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:124) ~[seata-core-1.4.2.jar:na]
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:90) [seata-server-1.4.2.jar:na]
        at io.seata.core.protocol.transaction.GlobalCommitRequest.handle(GlobalCommitRequest.java:34) [seata-core-1.4.2.jar:na]
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:473) [seata-server-1.4.2.jar:na]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:116) [seata-core-1.4.2.jar:na]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77) [seata-core-1.4.2.jar:na]
        at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:279) [seata-core-1.4.2.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: io.seata.core.exception.BranchTransactionException: Send branch commit failed, xid = 10.11.117.6:4426:8845200782043429105 branchId = 7494120885082147938
        at io.seata.server.coordinator.AbstractCore.branchCommit(AbstractCore.java:167) ~[seata-server-1.4.2.jar:na]
        at io.seata.server.coordinator.DefaultCore.lambda$doGlobalCommit$1(DefaultCore.java:204) ~[seata-server-1.4.2.jar:na]
        ... 17 common frames omitted
Caused by: java.util.concurrent.TimeoutException: cost 30000 ms
        at io.seata.core.protocol.MessageFuture.get(MessageFuture.java:62) ~[seata-core-1.4.2.jar:na]
        at io.seata.core.rpc.netty.AbstractNettyRemoting.sendSync(AbstractNettyRemoting.java:197) [seata-core-1.4.2.jar:na]
        at io.seata.core.rpc.netty.AbstractNettyRemotingServer.sendSyncRequest(AbstractNettyRemotingServer.java:71) ~[seata-core-1.4.2.jar:na]
        at io.seata.server.coordinator.AbstractCore.branchCommitSend(AbstractCore.java:174) ~[seata-server-1.4.2.jar:na]
        at io.seata.server.coordinator.AbstractCore.branchCommit(AbstractCore.java:164) ~[seata-server-1.4.2.jar:na]
        ... 18 common frames omitted
```
我个人认为，RmNettyRemotingClient中，内部的messageExecutor的线程数太小了。
我在配置中心里加了这个参数`transport.threadFactory.workerThreadSize`能改善这个问题。

但是，io.seata.core.rpc.netty.NettyBaseConfig#WORKER_THREAD_SIZE 这个变量会用于server的serverSelectorThreads和serverWorkerThreads。

是不是在tcc模式中，单独给rm的线程池一个参数，会好些？

如果有说错的地方，请指教，谢谢！~

**Comment by a364176773** [comment]
1.4.2 启动参数加-d,自己来配置以下的几个线程池参数
transport.keepAliveTime
transport.maxTaskQueueSize
transport.minServerPoolSize
transport.maxServerPoolSize

**Comment by Pinocchio2018** [comment]
> 1.4.2 启动参数加-d,自己来配置以下的几个线程池参数
> transport.keepAliveTime
> transport.maxTaskQueueSize
> transport.minServerPoolSize
> transport.maxServerPoolSize

@a364176773 大佬，我觉得，你说的是设置seata-server的线程池呀。我觉得太小的是seata-client启动时候的线程池呀。
```java
    public static RmNettyRemotingClient getInstance() {
        if (instance == null) {
            synchronized (RmNettyRemotingClient.class) {
                if (instance == null) {
                    NettyClientConfig nettyClientConfig = new NettyClientConfig();
                    final ThreadPoolExecutor messageExecutor = new ThreadPoolExecutor(
                        nettyClientConfig.getClientWorkerThreads(), nettyClientConfig.getClientWorkerThreads(),  //这里太小了
                        KEEP_ALIVE_TIME, TimeUnit.SECONDS, new LinkedBlockingQueue<>(MAX_QUEUE_SIZE),
                        new NamedThreadFactory(nettyClientConfig.getRmDispatchThreadPrefix(),
                            nettyClientConfig.getClientWorkerThreads()), new ThreadPoolExecutor.CallerRunsPolicy());
                    instance = new RmNettyRemotingClient(nettyClientConfig, null, messageExecutor);
                }
            }
        }
        return instance;
    }

public class NettyClientConfig extends NettyBaseConfig {
    private int clientWorkerThreads = WORKER_THREAD_SIZE;
}
```

**Comment by a364176773** [comment]
> > 1.4.2 启动参数加-d,自己来配置以下的几个线程池参数
> > transport.keepAliveTime
> > transport.maxTaskQueueSize
> > transport.minServerPoolSize
> > transport.maxServerPoolSize
> 
> @a364176773 大佬，我觉得，你说的是设置seata-server的线程池呀。我觉得太小的是seata-client启动时候的线程池呀。
> 
> ```java
>     public static RmNettyRemotingClient getInstance() {
>         if (instance == null) {
>             synchronized (RmNettyRemotingClient.class) {
>                 if (instance == null) {
>                     NettyClientConfig nettyClientConfig = new NettyClientConfig();
>                     final ThreadPoolExecutor messageExecutor = new ThreadPoolExecutor(
>                         nettyClientConfig.getClientWorkerThreads(), nettyClientConfig.getClientWorkerThreads(),  //这里太小了
>                         KEEP_ALIVE_TIME, TimeUnit.SECONDS, new LinkedBlockingQueue<>(MAX_QUEUE_SIZE),
>                         new NamedThreadFactory(nettyClientConfig.getRmDispatchThreadPrefix(),
>                             nettyClientConfig.getClientWorkerThreads()), new ThreadPoolExecutor.CallerRunsPolicy());
>                     instance = new RmNettyRemotingClient(nettyClientConfig, null, messageExecutor);
>                 }
>             }
>         }
>         return instance;
>     }
> 
> public class NettyClientConfig extends NettyBaseConfig {
>     private int clientWorkerThreads = WORKER_THREAD_SIZE;
> }
> ```

抱歉看错了,

> > 1.4.2 启动参数加-d,自己来配置以下的几个线程池参数
> > transport.keepAliveTime
> > transport.maxTaskQueueSize
> > transport.minServerPoolSize
> > transport.maxServerPoolSize
> 
> @a364176773 大佬，我觉得，你说的是设置seata-server的线程池呀。我觉得太小的是seata-client启动时候的线程池呀。
> 
> ```java
>     public static RmNettyRemotingClient getInstance() {
>         if (instance == null) {
>             synchronized (RmNettyRemotingClient.class) {
>                 if (instance == null) {
>                     NettyClientConfig nettyClientConfig = new NettyClientConfig();
>                     final ThreadPoolExecutor messageExecutor = new ThreadPoolExecutor(
>                         nettyClientConfig.getClientWorkerThreads(), nettyClientConfig.getClientWorkerThreads(),  //这里太小了
>                         KEEP_ALIVE_TIME, TimeUnit.SECONDS, new LinkedBlockingQueue<>(MAX_QUEUE_SIZE),
>                         new NamedThreadFactory(nettyClientConfig.getRmDispatchThreadPrefix(),
>                             nettyClientConfig.getClientWorkerThreads()), new ThreadPoolExecutor.CallerRunsPolicy());
>                     instance = new RmNettyRemotingClient(nettyClientConfig, null, messageExecutor);
>                 }
>             }
>         }
>         return instance;
>     }
> 
> public class NettyClientConfig extends NettyBaseConfig {
>     private int clientWorkerThreads = WORKER_THREAD_SIZE;
> }
> ```

抱歉看错了,你可以看下这块代码
```
        String workerThreadSize = CONFIG.getConfig(ConfigurationKeys.WORKER_THREAD_SIZE);
        if (StringUtils.isNotBlank(workerThreadSize) && StringUtils.isNumeric(workerThreadSize)) {
            WORKER_THREAD_SIZE = Integer.parseInt(workerThreadSize);
        } else if (WorkThreadMode.getModeByName(workerThreadSize) != null) {
            WORKER_THREAD_SIZE = WorkThreadMode.getModeByName(workerThreadSize).getValue();
        } else {
            WORKER_THREAD_SIZE = WorkThreadMode.Default.getValue();
        }
```

**Comment by a364176773** [comment]
transport.threadFactory.workerThreadSize

**Comment by Pinocchio2018** [comment]
@a364176773 大佬，我的意思是，我在配置中心里加上这个配置去修改客户端的`WORKER_THREAD_SIZE`话，**会影响seata-server的**。
```java
public class NettyServerConfig extends NettyBaseConfig {
    private int serverSelectorThreads = Integer.parseInt(System.getProperty(
            ConfigurationKeys.TRANSPORT_PREFIX + "serverSelectorThreads", String.valueOf(WORKER_THREAD_SIZE)));

    private int serverWorkerThreads = Integer.parseInt(System.getProperty(
            ConfigurationKeys.TRANSPORT_PREFIX + "serverWorkerThreads", String.valueOf(WORKER_THREAD_SIZE)));
}
```
如果设置上千，seata-server启动的时候会报错的（好像是too many open files）。

**Comment by xyz327** [comment]
@a364176773 我觉得这个 timeout 问题并不是有 tm 线程设置问题导致到。而是有 tc 的线程池设置导致的。把 tc 的线程池设置为 1 必然会出现这个 timeout 问题 参见我的 [tcc-timeout-demo 项目](https://github.com/xyz327/seata-tcc-timeout-demo).
