### ISSUE TITLE
@GlobalTransactional注解下的全局事务有没有类似TransactionSynchronizationManager.registerSynchronization的机制，可以在事务成功后触发执行

### ISSUE THREAD

**Issue by greper** [seata/seata#3756]
想通过`TransactionSynchronizationManager.registerSynchronization` 注册事务完成后执行方法

1、service方法上 只写@GlobalTransactional， 会报如下异常
```
java.lang.IllegalStateException: Transaction synchronization is not active
	at org.springframework.transaction.support.TransactionSynchronizationManager.registerSynchronization(TransactionSynchronizationManager.java:297) ~[spring-tx-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at com.yonsz.common.event.EventPublishUtil.publishAfterTransactional(EventPublishUtil.java:48) ~[classes/:?]
	at com.yonsz.cloud.hotel.service.CheckInServiceImpl.checkOut(CheckInServiceImpl.java:270) ~[classes/:?]
	at com.yonsz.cloud.hotel.service.CheckInServiceImpl.checkOut(CheckInServiceImpl.java:245) ~[classes/:?]

```

2、如果@GlobalTransactional 和@Transactional 同时写  ，就没有问题
但好像只是本地事务成功就触发了执行。
假如分支事务失败，导致回滚。那么实际期望是注册的方法不应该执行

**Comment by xyz327** [comment]
https://github.com/seata/seata/blob/develop/tm/src/main/java/io/seata/tm/api/transaction/TransactionHook.java  这个 tm 的 hook 不知道满不满足你的需求

**Comment by greper** [comment]
> https://github.com/seata/seata/blob/develop/tm/src/main/java/io/seata/tm/api/transaction/TransactionHook.java 这个 tm 的 hook 不知道满不满足你的需求

great， 就是要这个

**Comment by greper** [comment]
好像这只是本地事务的hook，有没有全局事务结束的hook？

**Comment by xyz327** [comment]
TM(标记了@GlobalTransactional 的) 做为全局事务的开启者。结束也就是全局事务的结束

**Comment by greper** [comment]
噢，对，TM成功后发射事件没问题
那如果是分支事务有这样的需求呢？

service A                serviceB                              serviceC 
  TM ----- invoke--->RM (事务成功后发射事件)
  TM ----------------invoke---------------------->RM（执行失败 rollback）

这里serviceC 执行失败触发rollback，那serviceB的事件就不应该发送。所以RM如何知道全局事务已完成？

**Comment by xyz327** [comment]
RM 没有这种 hook 机制。感觉可以自定义实现 io.seata.rm.AbstractRMHandler (io.seata.rm.RMClient#init) 然后在两个 handle 方法里面去发射你说的事件。

**Comment by greper** [comment]
好的,我去看看，非常感谢您的解答 [抱拳][抱拳][抱拳]
