### ISSUE TITLE
1.4.2 springboot 启动过程中 'main' 和 'timeoutChecker' 线程的死锁重现了

### ISSUE THREAD

**Issue by aoyvx** [seata/seata#3767]
### Ⅰ. Issue Description
我在使用io.seata:seata-spring-boot-starter:1.4.2的时候,springboot 启动过程中 'main' 线程 和 'timeoutChecker' 线程发生死锁,原因是SpringBootConfigurationProvider间接进行Spring上下文的依赖查找.

### Ⅱ. Describe what happened
这个问题和 #2857 应该是一样的,然后 #2879 通过StarterConstants#PROPERTY_BEAN_MAP做属性缓存解决了这个死锁问题,可是 #3431 又废弃掉了PROPERTY_BEAN_MAP缓存功效,并且现在1.4.2的PROPERTY_BEAN_MAP和1.4.0的PROPERTY_MAP作用看起来没有太大差别,然后现在 #2879 的死锁问题又重现了,这令我很困惑.

### Ⅲ. Describe what you expected to happen
我希望有方法可以解决现在存在的死锁问题.
是否需要我将seata-spring-boot-starter和seata server的版本降低到1.4.1然后等待1.5.x的发布.

### Ⅵ. Environment:

- JDK version : 1.8
- OS : centos7
- Others: io.seata:seata-spring-boot-starter:1.4.2

**Comment by wangliang181230** [comment]
1.4.1的问题还是比较多的。建议继续保留在1.4.2。
我先问一下，你们是不是使用了什么与数据源相关的组件？我认为这个问题的根本原因是自动装配顺序问题。
应该是你们使用的组件的自动装配优先级比Seata的要高，而触发了死锁。

能否将您的死锁情况和 #2857 issue里一样，截图或者text发上来。

**Comment by wangliang181230** [comment]
在 #3431 中废弃掉，主要是为了代码的优雅度。

**Comment by wangliang181230** [comment]
![图片](https://user-images.githubusercontent.com/1527893/119601253-5ab2e500-be1b-11eb-8a76-56678d057077.png)

@aoyvx 如果确实是装配顺序问题的话，你可以参考springboot中的这个配置文件，来调整自动装配的顺序。

**Comment by wangliang181230** [comment]
这个也碰到过的，我记得是概率出现的一个死锁吧。

**Comment by aoyvx** [comment]
确实是很小概率才能出现,通常情况下不会出现这个问题.

**Comment by wangliang181230** [comment]
这个问题，我有时间再考虑一下。
之前是考虑直接从springboot的环境中读取配置值，而不是从properties配置类中读取。

**Comment by aoyvx** [comment]
我有一个想法,但是不知道是否优雅.
如果我们在GlobalTransactionScanner# afterPropertiesSet方法中添加下面这段代码,在main线程中将seata所有可能需要的配置bean安全的初始化,那么后面就不会发生多线程初始化单例bean的锁竞争问题了,那么也就不会死锁了.
```
for (Class propertyClass : PROPERTY_BEAN_MAP.values()) {
    beanFactory.getBeansOfType(propertyClass);
}
```

**Comment by wangliang181230** [comment]
可以是可以，但也只是解决了这一种死锁而已。
另外还有数据源代理初始化时和timeoutChecker造成的死锁。

终级解决，还是得直接从环境里读，环境是最先加载的。也没有加载bean的锁问题。

**Comment by aoyvx** [comment]
我理解您所提出解决问题的方案,但是我不太清楚您提到的另外一种锁会是在哪个位置出现.
我认为只要是因为properties bean引起的死锁问题都可以用提前初始化解决.
您可以将第二种死锁出现的情景告诉我吗?

**Comment by wangliang181230** [comment]
另一个是bean自动装配顺序的问题，那时候Scanner也没有被加载到。
你无法保证properties bean的加载优先级比其他任何第三方组件要高。
为了规避这个问题，只能是不去加载bean。

**Comment by aoyvx** [comment]
您的意思是datasource因为其他原因初始化早于Scanner的初始吗?
如果是这样的话由于SeataDataSourceBeanPostProcessor中所有涉及到的后续操作都是同步的,并且这里会连接seata server间接初始化所有所需的properties bean.
那么等到Scanner初始化和timeoutChecker执行的时候就应该不会涉及到properties bean的初始化问题了.

**Comment by wangliang181230** [comment]
1. 第三方组件加载bean，它依赖于数据源的bean。
2. 数据源bean被seata代理。
3. Seata代理时，加载Properties Bean。
第一步的加载bean和第3步的加载bean就会死锁。

**Comment by aoyvx** [comment]
....但是这时候他们都是在主线程中执行啊,synchronized的可重入性让他们不会死锁的啊.我们需要解决的问题是多线程初始化导致的锁.

**Comment by wangliang181230** [comment]
加载bean的锁和seata里还有个加载配置的锁。
你可以去看一下原来那几个issue的记录。

**Comment by wangliang181230** [comment]
https://github.com/seata/seata/issues/2857

**Comment by wangliang181230** [comment]
详细的我也有些记不清了，还是看历史记录吧。

**Comment by aoyvx** [comment]
确实在Scanner中初始化bean properties是不太严谨的表现.因为我才发现Client#init会在多个地方调用.
我目前的解决方法是在一个BeanPostProcessor的setApplicationContext初始化的bean properties,因为我确信在这个阶段它不不会出现问题.
期待您更好的实现,这个问题可能会在哪一个发行版本中解决呢,我注意下好升级版本.

**Comment by lightClouds917** [comment]
我去看排查处理一下 @a364176773

**Comment by aoyvx** [comment]
😂如果现在没有更多时间解决这个问题可以参考我目前的解决方案.
我这边目前是将SpringBootConfigurationProvider#get(String dataId)修改为
```
private Object get(String dataId) throws IllegalAccessException, InstantiationException {
        String propertyPrefix = getPropertyPrefix(dataId);
        String propertySuffix = getPropertySuffix(dataId);
        ApplicationContext applicationContext = (ApplicationContext) ObjectHolder.INSTANCE.getObject(OBJECT_KEY_SPRING_APPLICATION_CONTEXT);
        Class<?> propertyClass = PROPERTY_BEAN_MAP.get(propertyPrefix);
        Object valueObject = null;
        if (propertyClass != null) {
            try {
                Object propertyBean = applicationContext.getBean(NAME_MAP.computeIfAbsent(propertyClass, aClass -> {
                    final AnnotationBeanNameGenerator nameGenerator = new AnnotationBeanNameGenerator();
                    AnnotatedBeanDefinition bd = new AnnotatedGenericBeanDefinition(aClass);
                    return nameGenerator.generateBeanName(bd, null);
                }));
                valueObject = getFieldValue(propertyBean, propertySuffix, dataId);
            } catch (NoSuchBeanDefinitionException ignore) {

            }
        } else {
            throw new ShouldNeverHappenException("PropertyClass for prefix: [" + propertyPrefix + "] should not be null.");
        }
        if (valueObject == null) {
            valueObject = getFieldValue(propertyClass.newInstance(), propertySuffix, dataId);
        }

        return valueObject;
    }
```
并提前初始化了所有配置bean,然后就没有出现死锁的情况了

**Comment by a364176773** [comment]
> > 能否将您的死锁情况和 #2857 issue里一样，截图或者text发上来。
> 
> 很抱歉昨天没有贴上异常文档,我对比了下,我这边产生死锁的原因和 #2857 不太一样,最末的是我的死锁线程详情.
> 
> > @aoyvx 如果确实是装配顺序问题的话，你可以参考springboot中的这个配置文件，来调整自动装配的顺序。
> 
> 今天我仔细查看了下产生死锁的原因,发现是io.seata:seata-spring-boot-starter内部的一些原因导致的死锁,当然由于这种情况非常特殊,所以可能之前没有人遇见过.下面是我的一些发现,或许可以帮您节约一些时间.
> 
> 1. GlobalTransactionScanner#afterPropertiesSet会初始化RmNettyRemotingClient,这时候调用AbstractNettyRemotingClient#init方法向timeoutChecker注册一个一分钟重连一次的transaction service 的定时任务,然后由于我完全依赖seata-spring-boot-starter的自动装配,所以RmNettyRemotingClient#init不会进行第一次非异步的线程transaction service连接.
> 2. InitializingBean执行完后到达postProcessAfterInitialization阶段,最终会到达RmNettyRemotingClient#registerResource的方法并连接transaction service.
> 3. 因为我的配置中心使用的是nacos,所以在连接transaction service的时候会调用NacosRegistryServiceImpl的lookup方法做一次配置加载,其中lookup方法是加上了一把对象锁的,并且NettyClientChannelManager属于单例对象.
> 4. 由于一些特殊的原因,我的应用在线上启动的会比较慢,所以afterPropertiesSet执行之后SeataDataSourceBeanPostProcessor#postProcessAfterInitialization之前中间时间可能会大于一分钟,然后一个很长的依赖链末端是datasource.
> 5. 在我完全实例化第一个DataSource依赖链的时候,timeoutChecker执行了第一次重连任务并获取到NacosRegistryServiceImpl#lookup的对象锁,这同时也是第一次获取Seata相关配置Bean的时间,所以需要对seata配置bean进行实例化.
> 6. 这时候DataSource的生命周期还未完全走完,而spring单例写是加锁的,所以timeoutChecker被堵塞.
> 7. 由于前面没有和transaction service建立起连接,所以SeataDataSourceBeanPostProcessor#postProcessAfterInitialization会再调用一次建立连接的方法,这时候main线程被NacosRegistryServiceImpl#lookup的对象锁堵塞.
> 
> ```
> "timeoutChecker_2_1":
>   waiting to lock monitor 0x00007f445c064b98 (object 0x00000000ec2bd450, a java.util.concurrent.ConcurrentHashMap),
>   which is held by "main"
> "main":
>   waiting to lock monitor 0x00007f4470003b98 (object 0x00000000ee09c928, a java.lang.Object),
>   which is held by "timeoutChecker_2_1"
> 
> Java stack information for the threads listed above:
> ===================================================
> "timeoutChecker_2_1":
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.java:986)
> 	- waiting to lock <0x00000000ec2bd450> (a java.util.concurrent.ConcurrentHashMap)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:884)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:619)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:536)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:495)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:480)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:473)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1159)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:420)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:350)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:343)
> 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1127)
> 	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:100)
> 	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:85)
> 	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$200(SpringBootConfigurationProvider.java:46)
> 	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:61)
> 	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>)
> 	at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.getServiceName(NacosRegistryServiceImpl.java:214)
> 	at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.lookup(NacosRegistryServiceImpl.java:129)
> 	- locked <0x00000000ee09c928> (a java.lang.Object)
> 	at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:232)
> 	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:166)
> 	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:114)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:748)
> "main":
> 	at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.lookup(NacosRegistryServiceImpl.java:126)
> 	- waiting to lock <0x00000000ee09c928> (a java.lang.Object)
> 	at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:232)
> 	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:166)
> 	at io.seata.core.rpc.netty.RmNettyRemotingClient.registerResource(RmNettyRemotingClient.java:194)
> 	at io.seata.rm.AbstractResourceManager.registerResource(AbstractResourceManager.java:121)
> 	at io.seata.rm.datasource.DataSourceManager.registerResource(DataSourceManager.java:90)
> 	at io.seata.rm.DefaultResourceManager.registerResource(DefaultResourceManager.java:114)
> 	at io.seata.rm.datasource.DataSourceProxy.init(DataSourceProxy.java:110)
> 	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:96)
> 	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:81)
> 	at io.seata.spring.annotation.datasource.DataSourceProxyHolder.createDsProxyByMode(DataSourceProxyHolder.java:97)
> 	at io.seata.spring.annotation.datasource.DataSourceProxyHolder.putDataSource(DataSourceProxyHolder.java:88)
> 	- locked <0x00000000ee95c748> (a java.util.HashMap)
> 	at io.seata.spring.annotation.datasource.SeataDataSourceBeanPostProcessor.postProcessAfterInitialization(SeataDataSourceBeanPostProcessor.java:58)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:430)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1798)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$203/1856128687.getObject(Unknown Source)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
> 	- locked <0x00000000ec2bd450> (a java.util.concurrent.ConcurrentHashMap)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
> 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
> 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
> 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:538)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$203/1856128687.getObject(Unknown Source)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
> 	- locked <0x00000000ec2bd450> (a java.util.concurrent.ConcurrentHashMap)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
> 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1509)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1404)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$203/1856128687.getObject(Unknown Source)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
> 	- locked <0x00000000ec2bd450> (a java.util.concurrent.ConcurrentHashMap)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
> 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
> 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1420)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$203/1856128687.getObject(Unknown Source)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
> 	- locked <0x00000000ec2bd450> (a java.util.concurrent.ConcurrentHashMap)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
> 	- locked <0x00000000ec271360> (a java.lang.Object)
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
> 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
> ```

getSingleton的方法块早就已经结束了,理论上已经释放了singletonObjects这个锁,为何到了timeoutchecker线程里还会被阻塞,lookup存在一个阻塞情况,因为lookup线程里即便去获取getServiceName()时,singletonObjects也已经被释放了,而main线程被阻塞在lookup,有点奇怪,你实现新版本还有这个问题不

**Comment by aoyvx** [comment]
> getSingleton的方法块早就已经结束了,理论上已经释放了singletonObjects这个锁,为何到了timeoutchecker线程里还会被阻塞,lookup存在一个阻塞情况,因为lookup线程里即便去获取getServiceName()时,singletonObjects也已经被释放了,而main线程被阻塞在lookup,有点奇怪,你实现新版本还有这个问题不

在我实现的版本中这个问题已经解决了,后续几个月没有重现过.由于DataSource还处于实例化后处理阶段,所以singletonObjects还没有释放.
由于这件事过去的时间有点旧了,具体的细节我记得不太清楚.我去找找我以前的代码,或许可以给您一些建议.

**Comment by a364176773** [comment]
> > getSingleton的方法块早就已经结束了,理论上已经释放了singletonObjects这个锁,为何到了timeoutchecker线程里还会被阻塞,lookup存在一个阻塞情况,因为lookup线程里即便去获取getServiceName()时,singletonObjects也已经被释放了,而main线程被阻塞在lookup,有点奇怪,你实现新版本还有这个问题不
> 
> 在我实现的版本中这个问题已经解决了,后续几个月没有重现过.由于DataSource还处于实例化后处理阶段,所以singletonObjects还没有释放. 由于这件事过去的时间有点旧了,具体的细节我记得不太清楚.我去找找我以前的代码,或许可以给您一些建议.

懂了，我看错了，是datasource实例化导致的，你这个做法是可以解决的，但是我们想看看有没有更优的解法，谢谢你的反馈

**Comment by a364176773** [comment]
我觉得直接让lookup在一分钟内直接进行，使timeoutchecker线程去lookup的时候，只能拿到map里的值，而不会走到下面去获取锁，这样就解开了死锁的问题，提前先执行一遍lookup即可

**Comment by aoyvx** [comment]
> 我觉得直接让lookup在一分钟内直接进行，使timeoutchecker线程去lookup的时候，只能拿到map里的值，而不会走到下面去获取锁，这样就解开了死锁的问题，提前先执行一遍lookup即可

这样确实是简单有效的. 或许可以直接在注册timeoutchecker线程前先加载配置项,并不用关心具体时间.
