### ISSUE TITLE
ONLY SUPPORT SAME TYPE (UPDATE OR DELETE) MULTI SQL

### ISSUE THREAD

**Issue by Heuan** [seata/seata#3859]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. 请问是否支持MySQL的批量插入，删除，更新的的批量操作，如果支持需要怎么配置。使用中出现如下错误：
Caused by: java.lang.UnsupportedOperationException: ONLY SUPPORT SAME TYPE (UPDATE OR DELETE) MULTI SQL -
at io.seata.sqlparser.druid.DruidSQLRecognizerFactoryImpl.create(DruidSQLRecognizerFactoryImpl.java:46) ~[seata-all-1.4.0.jar!/:1.4.0]
	at io.seata.sqlparser.druid.DruidDelegatingSQLRecognizerFactory.create(DruidDelegatingSQLRecognizerFactory.java:60) ~[seata-all-1.4.0.jar!/:1.4.0]
	at io.seata.rm.datasource.sql.SQLVisitorFactory.get(SQLVisitorFactory.java:49) ~[seata-all-1.4.0.jar!/:1.4.0]
	at io.seata.rm.datasource.AbstractConnectionProxy.prepareStatement(AbstractConnectionProxy.java:112) ~[seata-all-1.4.0.jar!/:1.4.0]

**Comment by Heuan** [comment]
### 补充
Mybatis 写法是,插入和更新也一样差不多写法，如下：
<insert  ...>
<foreach ....>
insert into ...... 循环多条插入语句
</foreach>
</insert >

**Comment by a364176773** [comment]
insert into values(),(),()这种写法支持

**Comment by Heuan** [comment]
问题已解决，谢谢
