### ISSUE TITLE
使用store.mode设置为redis，300并发用户持续压测30min中，server端崩溃

### ISSUE THREAD

**Issue by zzhangzd** [seata/seata#3862]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
server：4核8G
store.mode=redis
模式：AT

并发用户：300
压测时长：30min

问题：
使用300用户持续压测30min中时，在redis中存储的事务会话数据超过18000行，server端CPU使用率达80%以上，server崩溃不可连接

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
@zzhangzd  the server log  can be provided?

**Comment by zzhangzd** [comment]
> @zzhangzd the server log can be provided?

只有下面的一点报错,异步提交请求会不断累计，最后崩溃

02:27:44.026 ERROR --- [verHandlerThread_1_44_500] i.s.c.rpc.netty.AbstractNettyRemoting : 0104

==>

java.lang.RuntimeException: channel is error.

at io.seata.core.rpc.netty.AbstractNettyRemotingServer.sendAsyncResponse(AbstractNettyRemotingServer.java:104) ~[seata-core-1.4.0.jar:na]

at io.seata.core.rpc.processor.server.RegRmProcessor.onRegRmMessage(RegRmProcessor.java:83) ~[seata-core-1.4.0.jar:na]

at io.seata.core.rpc.processor.server.RegRmProcessor.process(RegRmProcessor.java:57) ~[seata-core-1.4.0.jar:na]

at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:278) ~[seata-core-1.4.0.jar:na]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]

at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]

<==

**Comment by zzhangzd** [comment]
> @zzhangzd the server log can be provided?

02:34:13.250 ERROR --- [verHandlerThread_1_37_500] i.s.c.rpc.netty.AbstractNettyRemoting : 0104

==>

java.lang.RuntimeException: channel is error.

at io.seata.core.rpc.netty.AbstractNettyRemotingServer.sendAsyncResponse(AbstractNettyRemotingServer.java:104) ~[seata-core-1.4.0.jar:na]

at io.seata.core.rpc.processor.server.RegRmProcessor.onRegRmMessage(RegRmProcessor.java:83) ~[seata-core-1.4.0.jar:na]

at io.seata.core.rpc.processor.server.RegRmProcessor.process(RegRmProcessor.java:57) ~[seata-core-1.4.0.jar:na]

at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:278) ~[seata-core-1.4.0.jar:na]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]

at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]

<==

02:34:10.650 ERROR --- [verHandlerThread_1_30_500] i.s.c.rpc.netty.AbstractNettyRemoting : 0104

==>

java.lang.NullPointerException: null

at io.seata.core.rpc.netty.ChannelManager.getSameClientChannel(ChannelManager.java:243) ~[seata-core-1.4.0.jar:na]

at io.seata.core.rpc.netty.AbstractNettyRemotingServer.sendAsyncResponse(AbstractNettyRemotingServer.java:96) ~[seata-core-1.4.0.jar:na]

at io.seata.core.rpc.processor.server.RegRmProcessor.onRegRmMessage(RegRmProcessor.java:83) ~[seata-core-1.4.0.jar:na]

at io.seata.core.rpc.processor.server.RegRmProcessor.process(RegRmProcessor.java:57) ~[seata-core-1.4.0.jar:na]

at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:278) ~[seata-core-1.4.0.jar:na]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]

at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]

<==

02:34:29.117 INFO --- [ RetryRollbacking_1_1] io.seata.core.rpc.netty.ChannelManager : No channel is available for resource[jdbc:mysql://10.233.68.225:8019/seata] as alternative of storage-seata-example:10.233.66.204:49828

02:34:27.936 INFO --- [ttyServerNIOWorker_1_4_16] i.s.c.r.n.AbstractNettyRemotingServer : remove unused channel:[id: 0x03941aa5, L:0.0.0.0/0.0.0.0:8091 ! R:/10.233.68.225:46186]

**Comment by a364176773** [comment]
> > @zzhangzd the server log can be provided?
> 
> 只有下面的一点报错,异步提交请求会不断累计，最后崩溃
> 
> 02:27:44.026 ERROR --- [verHandlerThread_1_44_500] i.s.c.rpc.netty.AbstractNettyRemoting : 0104
> 
> ==>
> 
> java.lang.RuntimeException: channel is error.
> 
> at io.seata.core.rpc.netty.AbstractNettyRemotingServer.sendAsyncResponse(AbstractNettyRemotingServer.java:104) ~[seata-core-1.4.0.jar:na]
> 
> at io.seata.core.rpc.processor.server.RegRmProcessor.onRegRmMessage(RegRmProcessor.java:83) ~[seata-core-1.4.0.jar:na]
> 
> at io.seata.core.rpc.processor.server.RegRmProcessor.process(RegRmProcessor.java:57) ~[seata-core-1.4.0.jar:na]
> 
> at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:278) ~[seata-core-1.4.0.jar:na]
> 
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
> 
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
> 
> at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
> 
> at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
> 
> <==

这点后面会出分布式锁来保证，多tc争抢，导致重复的从redis读数据，导致每个tc压力都很大的问题，develop分支已经实现了redis的版本，欢迎试用给我们反馈
