### ISSUE TITLE
FastjsonUndoLogParser 关于 datatime 类型的bug 导致事务不能回滚

### ISSUE THREAD

**Issue by zongf0504** [seata/seata#3866]
## 1. 问题

 当使用 fastjson 序列化 undoLog 时, 对于 datetime 类型的字段会导致事务回滚操作失败。通过阅读源码，发现 seata 的 DataCompareUtils.convertType 方法，未针对 java8 的 LocalDateTime 做特殊处理。在 jdbc 8.x 驱动中，对于 datetime 类型会自动映射为java 的 LocalDateTime 类型，而 FastJson 对其序列化格式为: yyyy:MM:ddTHH:mm:ss。
而在执行回滚操作时，在比较 Field 类型时，使用 TimeStamp.valueOf(String) 方法会抛出异常，导致事务无法回滚。

## 2. 数据库中 rollback_info 字段值

```json
{"branchId":8737137583306362964,"sqlUndoLogs":[{"afterImage":{"rows":[{"fields":[{"keyType":"PRIMARY_KEY","name":"id","type":-5,"value":1414624248579997696},{"keyType":"NULL","name":"create_time","type":93,"value":"2021-07-12T16:34:38"},{"keyType":"NULL","name":"update_time","type":93,"value":"2021-07-12T16:34:38"},{"keyType":"NULL","name":"version","type":4,"value":1},{"keyType":"NULL","name":"del","type":-7,"value":false},{"keyType":"NULL","name":"user_id","type":-5,"value":1414596331305070592},{"keyType":"NULL","name":"type","type":-6,"value":1},{"keyType":"NULL","name":"amount_before","type":3,"value":760.00},{"keyType":"NULL","name":"amount","type":3,"value":10.00},{"keyType":"NULL","name":"amount_after","type":3,"value":750.00},{"keyType":"NULL","name":"description","type":12,"value":"扣减"}]}],"tableName":"t_account_detail"},"beforeImage":{"rows":[],"tableName":"t_account_detail"},"sqlType":"INSERT","tableName":"t_account_detail"}],"xid":"172.17.0.1:8091:8737137583306362957"}
```
**java内存** 

![输入图片说明](https://images.gitee.com/uploads/images/2021/0713/004254_6966b746_5223378.png "seata.png")

## 3. 修改方案
DataCompareUtils.convertType 方法需添加对 LocalDateTime 类型的处理逻辑

![输入图片说明](https://images.gitee.com/uploads/images/2021/0713/172754_13f487e8_5223378.png "屏幕截图.png")

**Comment by jsbxyyx** [comment]
请使用除fastjson以外的序列化方式

**Comment by zongf0504** [comment]
这明显是个bug，得修复一下吧。用默认的 jackson 也会有问题，因为 Field的 Value 类型为 Object 无法解析。

```
### Cause: java.sql.SQLException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Type id handling not implemented for type java.lang.Object (by serializer of type com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer) (through reference chain: io.seata.rm.datasource.undo.BranchUndoLog["sqlUndoLogs"]->java.util.ArrayList[0]->io.seata.rm.datasource.undo.SQLUndoLog["beforeImage"]->io.seata.rm.datasource.sql.struct.TableRecords["rows"]->java.util.ArrayList[0]->io.seata.rm.datasource.sql.struct.Row["fields"]->java.util.ArrayList[4]->io.seata.rm.datasource.sql.struct.Field["value"])] with root cause

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Type id handling not implemented for type java.lang.Object (by serializer of type com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer) (through reference chain: io.seata.rm.datasource.undo.BranchUndoLog["sqlUndoLogs"]->java.util.ArrayList[0]->io.seata.rm.datasource.undo.SQLUndoLog["beforeImage"]->io.seata.rm.datasource.sql.struct.TableRecords["rows"]->java.util.ArrayList[0]->io.seata.rm.datasource.sql.struct.Row["fields"]->java.util.ArrayList[4]->io.seata.rm.datasource.sql.struct.Field["value"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1276) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.JsonSerializer.serializeWithType(JsonSerializer.java:160) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:730) ~[jackson-databind-2.12.3.jar:2.12.3]
```

**Comment by jsbxyyx** [comment]
请问一下数据库字段类型是什么？

**Comment by slievrly** [comment]
@zongf0504 I notice that you have a solution, please send a pr to fix the issue.
