### ISSUE TITLE
io.seata.core.exception.RmTransactionException: Response[ TransactionException[Failed to store branch xid = xxx

### ISSUE THREAD

**Issue by doveylovey** [seata/seata#3915]
Caused by: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Failed to store branch xid = 127.0.0.1:8091:163755026395705344 branchId = 163755028367028225] ]
        at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:69)
        at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96)
        at io.seata.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:238)
        at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:216)
        ... 81 common frames omitted

**Comment by a364176773** [comment]
请查看该时间端,xid和branch在tc端的异常

**Comment by lixz123** [comment]
{[TID:0d6a967b6ccb407f9d5206a9ae72973e.2338.16408466977230351] - 2021-12-30 14:44:59,289 - [http-nio-8080-exec-1] ERROR io.seata.rm.tcc.interceptor.ActionInterceptorHandler:122 - TCC branch Register error, xid: 10.150.84.142:8091:4512818949601857719} io.seata.core.exception.RmTransactionException: Response[ TransactionException[Failed to store branch xid = 10.150.84.142:8091:4512818949601857719 branchId = 4512818949601857724] ] at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:69) at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96) at io.seata.rm.tcc.interceptor.ActionInterceptorHandler.doTccActionLogStore(ActionInterceptorHandler.java:117) at io.seata.rm.tcc.interceptor.ActionInterceptorHandler.proceed(ActionInterceptorHandler.java:68) at io.seata.spring.tcc.TccActionInterceptor.invoke(TccActionInterceptor.java:84) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) at
