### ISSUE TITLE
springboot 使用@Scope注解，request范围，启动失败。

### ISSUE THREAD

**Issue by dume2007** [seata/seata#3919]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
springboot 使用@Scope注解，request范围，启动失败。
是不是这个request范围的注解在seata框架里用不了了？或是要改用其他使用方式？

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

我就用了这个bean类，用于存储全局用户信息，启动后就报错了。我如何规避这个错误？
```
@Data
@Component
@Scope(value = "request", proxyMode = ScopedProxyMode.TARGET_CLASS)
public class SessionUser implements Serializable {
    private static final long serialVersionUID = 3990902963179534578L;
    private int id = 0;
    private TokenBody tokenBody;
}
```

报错信息：
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionUser': Post-processing of FactoryBean's singleton object failed; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.sessionUser': Scope 'request' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:119)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1827)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1265)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 25 common frames omitted
```

### Ⅵ. Environment:

- JDK version : jdk8
- OS : Mac OS
- Others:

**Comment by dume2007** [comment]
#3288 我看之前也有人提过，但没解决方案？

**Comment by a364176773** [comment]
用prototype
