### ISSUE TITLE
dubbo+zk+springboot+seata全局事务失效问题

### ISSUE THREAD

**Issue by hylyLLL** [seata/seata#3976]
@GlobalTransactional
    @Override
    public void create() {
        SysUser sysUser = new SysUser();
        sysUser.setUserName("test");
        sysUser.setPassword("3243242");
        iSysUserService.save(sysUser);
        int a = 10 / 0;
        SysUser sysUser2 = new SysUser();
        sysUser2.setUserName("test2222");
        sysUser2.setPassword("3243242");
        iSysUserService.save(sysUser2);
    }

    @GlobalTransactional
    @Override
    public JsonResultT<Boolean> create(CarInfoCreateBean bean) {
        dataHostService.save(new DataHost(bean.getHostNumber()));
        int a = 10 / 0;
        CarInfo entity = new CarInfo();
        entity.setHostNumber(bean.getHostNumber());
        entity.setCarNo(bean.getCarNo());
        save(entity);
    }

同一个模块的两个方法，上面那个可以正常回滚，下面的方法就直接走本地事务了，不走seata的全局事务了，save方法都是mybatis的

**Comment by a364176773** [comment]
Seata常见问题：http://seata.io/zh-cn/docs/overview/faq.html

Seata整合1.2教程: https://www.bilibili.com/video/BV12Q4y1A7Nt

升级1.3教程: https://www.bilibili.com/video/BV1Cf4y1X7vR

TCC整合教程: http://seata.io/zh-cn/blog/integrate-seata-tcc-mode-with-spring-cloud.html

文字版教程

https://mp.weixin.qq.com/s/2KSidJ72YsovpJ94P1aK1g

tcc+at 整合demo:
https://github.com/wangliang181230/seata-starters-and-demos

springcloud整合demo:

https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo 
（上述demo内附1.3整合文字版）

**Comment by hylyLLL** [comment]
> Seata常见问题：http://seata.io/zh-cn/docs/overview/faq.html
> 
> Seata整合1.2教程: https://www.bilibili.com/video/BV12Q4y1A7Nt
> 
> 升级1.3教程: https://www.bilibili.com/video/BV1Cf4y1X7vR
> 
> TCC整合教程: http://seata.io/zh-cn/blog/integrate-seata-tcc-mode-with-spring-cloud.html
> 
> 文字版教程
> 
> https://mp.weixin.qq.com/s/2KSidJ72YsovpJ94P1aK1g
> 
> tcc+at 整合demo:
> https://github.com/wangliang181230/seata-starters-and-demos
> 
> springcloud整合demo:
> 
> https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo
> （上述demo内附1.3整合文字版）

你好，我这边配置都是正常的，没有报什么错误，但是在使用@GlobalTransactional时，下面那个案例就是不触发，走的本地事务

**Comment by hylyLLL** [comment]
还有就是，一直报内存分配失败，但是内存已经调大了：
 237:8091 ! R:/172.20.0.6:42424]
2021-08-24 09:13:47.163 INFO [NettyServerNIOWorker_12_12]io.seata.core.rpc.netty.RpcServer.exceptionCaught:381 -channel exx:failed to allocate 134217728 byte(s) of d      irect memory (used: 536870912, max: 536870912),channel:[id: 0x347b42f0, L:/192.168.3.237:8091 - R:/172.20.0.6:42426]
2021-08-24 09:13:47.164 ERROR[NettyServerNIOWorker_12_12]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:424 -0318
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 134217728 byte(s) of direct memory (used: 536870912, max: 536870912)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:652)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:606)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
        at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
        at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by hylyLLL** [comment]
> Seata常见问题：http://seata.io/zh-cn/docs/overview/faq.html
> 
> Seata整合1.2教程: https://www.bilibili.com/video/BV12Q4y1A7Nt
> 
> 升级1.3教程: https://www.bilibili.com/video/BV1Cf4y1X7vR
> 
> TCC整合教程: http://seata.io/zh-cn/blog/integrate-seata-tcc-mode-with-spring-cloud.html
> 
> 文字版教程
> 
> https://mp.weixin.qq.com/s/2KSidJ72YsovpJ94P1aK1g
> 
> tcc+at 整合demo:
> https://github.com/wangliang181230/seata-starters-and-demos
> 
> springcloud整合demo:
> 
> https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo
> （上述demo内附1.3整合文字版）

你好，我这边确认了问题，最后发现是由于springboot循环引用造成的全局事务失效
