### ISSUE TITLE
ErrMsg:failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848])

### ISSUE THREAD

**Issue by aSingleDragon** [seata/seata#3990]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
docker启动seata失败

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
SLF4J: A number (17) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay

11:41:58.160  INFO --- [                     main] io.seata.server.Server                   : The server is running in container.
11:41:58.168  INFO --- [                     main] io.seata.config.FileConfiguration        : The file name of the operation is file:/root/seata-config/registry
11:41:58.172  INFO --- [                     main] io.seata.config.FileConfiguration        : The configuration file used is /root/seata-config/registry.conf
11:42:12.479  INFO --- [                     main] i.s.core.rpc.netty.NettyServerBootstrap  : Server started, listen port: 8091
11:42:12.561 ERROR --- [                     main] io.seata.server.Server                   : nettyServer init error:ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: java.net.ConnectException: Connection refused (Connection refused)
==>
java.lang.RuntimeException: ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: java.net.ConnectException: Connection refused (Connection refused)
	at io.seata.core.rpc.netty.NettyServerBootstrap.start(NettyServerBootstrap.java:157) ~[seata-core-1.4.2.jar:na]
	at io.seata.core.rpc.netty.AbstractNettyRemotingServer.init(AbstractNettyRemotingServer.java:55) ~[seata-core-1.4.2.jar:na]
	at io.seata.core.rpc.netty.NettyRemotingServer.init(NettyRemotingServer.java:52) ~[seata-core-1.4.2.jar:na]
	at io.seata.server.Server.main(Server.java:98) ~[classes/:na]
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: java.net.ConnectException: Connection refused (Connection refused)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:552) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:239) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:200) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:185) ~[nacos-client-1.3.3.jar:na]
	at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:86) ~[seata-discovery-nacos-1.4.2.jar:na]
	at io.seata.core.rpc.netty.NettyServerBootstrap.start(NettyServerBootstrap.java:153) ~[seata-core-1.4.2.jar:na]
	... 3 common frames omitted
<==

```

### Ⅲ. Describe what you expected to happen
seata-server成功启动并注册到nacos中

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
**以下文件中出现的行号是为了方便您阅读，实际文件中并没有行号**
1. docker pull seataio/seata-server:1.4.2
2. 拷贝[GitHub上的Seata-1.4.2](https://github.com/seata/seata/tree/1.4.2/script/server/config)版本的配置文件file.conf及registry.conf至本地目录/Users/hll/config/seata-config
3. 修改这两个配置文件分别如下
**registry.conf**
```
  1 ## https://github.com/seata/seata/blob/1.4.2/script/server/config/registry.conf
  2 registry {
  3   type = "nacos"
  4
  5   nacos {
  6     application = "seata-server"
  7     serverAddr = "127.0.0.1:8848"
  8     group = "SEATA_GROUP"
  9     namespace = ""
 10     cluster = "default"
 11     username = ""
 12     password = ""
 13   }
 14   file {
 15     name = "file.conf"
 16   }
 17 }
 18
 19 config {
 20   type = "nacos"
 21
 22   nacos {
 23     serverAddr = "127.0.0.1:8848"
 24     namespace = ""
 25     group = "SEATA_GROUP"
 26     username = ""
 27     password = ""
 28     dataId = "seataServer.properties"
 29   }
 30
 31   file {
 32     name = "file:/root/seata-config/file.conf"
 33   }
 34 }
```
file.conf:
```
 1 ## https://github.com/seata/seata/blob/1.4.2/script/server/config/file.conf
  2 store {
  3   mode = "db"
  4
  5   db {
  6     datasource = "druid"
  7     dbType = "mysql"
  8     driverClassName = "com.mysql.jdbc.Driver"
  9     url = "jdbc:mysql://127.0.0.1:3306/seata?rewriteBatchedStatements=true"
 10     user = "root"
 11     password = "Sunzi,.741"
 12     minConn = 5
 13     maxConn = 100
 14     globalTable = "global_table"
 15     branchTable = "branch_table"
 16     lockTable = "lock_table"
 17     queryLimit = 100
 18     maxWait = 5000
 19   }
 20 }
```
4. 制作容器并启动
```
docker run --name seata-server \
        -d -p 8091:8091 \
        -e SEATA_CONFIG_NAME=file:/root/seata-config/registry \
        -v /Users/hll/config/seata-config:/root/seata-config   \
        seataio/seata-server
```
5. 

### Ⅴ. Anything else we need to know?
nacos是docker部署的：
```
docker run --name nacos-standalone \ 
             -e MODE=standalone 
             -d -p 8848:8848 
             -p 9848:9848 
             nacos/nacos-server:2.0.3
```
配置中心[config-center](https://github.com/seata/seata/tree/1.4.2/script/config-center)的config.txt已推送至nacos且内容（修改后的）如下：
```
  1 transport.type=TCP
  2 transport.server=NIO
  3 transport.heartbeat=true
  4 transport.enableClientBatchSendRequest=false
  5 transport.threadFactory.bossThreadPrefix=NettyBoss
  6 transport.threadFactory.workerThreadPrefix=NettyServerNIOWorker
  7 transport.threadFactory.serverExecutorThreadPrefix=NettyServerBizHandler
  8 transport.threadFactory.shareBossWorker=false
  9 transport.threadFactory.clientSelectorThreadPrefix=NettyClientSelector
 10 transport.threadFactory.clientSelectorThreadSize=1
 11 transport.threadFactory.clientWorkerThreadPrefix=NettyClientWorkerThread
 12 transport.threadFactory.bossThreadSize=1
 13 transport.threadFactory.workerThreadSize=default
 14 transport.shutdown.wait=3
 15 service.vgroupMapping.my_test_tx_group=default
 16 service.default.grouplist=127.0.0.1:8091
 17 service.enableDegrade=false
 18 service.disableGlobalTransaction=false
 19 client.rm.asyncCommitBufferLimit=10000
 20 client.rm.lock.retryInterval=10
 21 client.rm.lock.retryTimes=30
 22 client.rm.lock.retryPolicyBranchRollbackOnConflict=true
 23 client.rm.reportRetryCount=5
 24 client.rm.tableMetaCheckEnable=false
 25 client.rm.tableMetaCheckerInterval=60000
 26 client.rm.sqlParserType=druid
 27 client.rm.reportSuccessEnable=false
 28 client.rm.sagaBranchRegisterEnable=false
 29 client.tm.commitRetryCount=5
 30 client.tm.rollbackRetryCount=5
 31 client.tm.defaultGlobalTransactionTimeout=60000
 32 client.tm.degradeCheck=false
 33 client.tm.degradeCheckAllowTimes=10
 34 client.tm.degradeCheckPeriod=2000
 35 store.mode=db
 36 store.publicKey=
 37 store.file.dir=file_store/data
 38 store.file.maxBranchSessionSize=16384
 39 store.file.maxGlobalSessionSize=512
 40 store.file.fileWriteBufferCacheSize=16384
 41 store.file.flushDiskMode=async
 42 store.file.sessionReloadReadSize=100
 43 store.db.datasource=druid
 44 store.db.dbType=mysql
 45 store.db.driverClassName=com.mysql.jdbc.Driver
 46 store.db.url=jdbc:mysql://127.0.0.1:3306/seata?useUnicode=true&rewriteBatchedStatements=true
 47 store.db.user=root
 48 store.db.password=Sunzi,.741
 49 store.db.minConn=5
 50 store.db.maxConn=30
 51 store.db.globalTable=global_table
 52 store.db.branchTable=branch_table
 53 store.db.queryLimit=100
 54 store.db.lockTable=lock_table
 55 store.db.maxWait=5000
 56 store.redis.mode=single
 57 store.redis.single.host=127.0.0.1
 58 store.redis.single.port=6379
 59 store.redis.sentinel.masterName=
 60 store.redis.sentinel.sentinelHosts=
 61 store.redis.maxConn=10
 62 store.redis.minConn=1
 63 store.redis.maxTotal=100
 64 store.redis.database=0
 65 store.redis.password=
 28 client.rm.sagaBranchRegisterEnable=false
 29 client.tm.commitRetryCount=5
 30 client.tm.rollbackRetryCount=5
 31 client.tm.defaultGlobalTransactionTimeout=60000
 32 client.tm.degradeCheck=false
 33 client.tm.degradeCheckAllowTimes=10
 34 client.tm.degradeCheckPeriod=2000
 35 store.mode=db
 36 store.publicKey=
 37 store.file.dir=file_store/data
 38 store.file.maxBranchSessionSize=16384
 39 store.file.maxGlobalSessionSize=512
 40 store.file.fileWriteBufferCacheSize=16384
 41 store.file.flushDiskMode=async
 42 store.file.sessionReloadReadSize=100
 43 store.db.datasource=druid
 44 store.db.dbType=mysql
 45 store.db.driverClassName=com.mysql.jdbc.Driver
 46 store.db.url=jdbc:mysql://127.0.0.1:3306/seata?useUnicode=true&rewriteBatchedStatements=true
 47 store.db.user=root
 48 store.db.password=Sunzi,.741
 49 store.db.minConn=5
 50 store.db.maxConn=30
 51 store.db.globalTable=global_table
 52 store.db.branchTable=branch_table
 53 store.db.queryLimit=100
 54 store.db.lockTable=lock_table
 55 store.db.maxWait=5000
 56 store.redis.mode=single
 57 store.redis.single.host=127.0.0.1
 58 store.redis.single.port=6379
 59 store.redis.sentinel.masterName=
 60 store.redis.sentinel.sentinelHosts=
 61 store.redis.maxConn=10
 62 store.redis.minConn=1
 63 store.redis.maxTotal=100
 64 store.redis.database=0
 65 store.redis.password=
 66 store.redis.queryLimit=100
 67 server.recovery.committingRetryPeriod=1000
 68 server.recovery.asynCommittingRetryPeriod=1000
 69 server.recovery.rollbackingRetryPeriod=1000
 70 server.recovery.timeoutRetryPeriod=1000
 71 server.maxCommitRetryTimeout=-1
 72 server.maxRollbackRetryTimeout=-1
 73 server.rollbackRetryTimeoutUnlockEnable=false
 74 client.undo.dataValidation=true
 75 client.undo.logSerialization=jackson
 76 client.undo.onlyCareUpdateColumns=true
 77 server.undo.logSaveDays=7
 78 server.undo.logDeletePeriod=86400000
 79 client.undo.logTable=undo_log
 80 client.undo.compress.enable=true
 81 client.undo.compress.type=zip
 82 client.undo.compress.threshold=64k
 83 log.exceptionRate=100
 84 transport.serialization=seata
 85 transport.compressor=none
 86 metrics.enabled=false
 87 metrics.registryType=compact
 88 metrics.exporterList=prometheus
 89 metrics.exporterPrometheusPort=9898
```
### Ⅵ. Environment:
- JDK version : openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
- OS : macOS Big Sur 11.5.2
- Nacos version: 2.0.3
- Mysql version: 8.0.25

### Ⅶ. Some Trys:
- 尝试了docker seata latest版本 能启动 但是无法注册到nacos中  
- 尝试了docker seata 1.1.0版本

**Comment by a364176773** [comment]
先试试低版本的nacos?

**Comment by aSingleDragon** [comment]
> 先试试低版本的nacos?

您好，我使用了1.4.2版本的nacos
```
docker pull nacos/nacos-server
docker run --name nacos-standalone-1.4.2 \ 
       -e MODE=standalone 
       -d -p 8848:8848 
       nacos/nacos-server:1.4.2
```
启动1.4.2版本的seata-server，还是会报之前的错误：
```
SLF4J: A number (17) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay

14:34:59.514  INFO --- [                     main] io.seata.server.Server                   : The server is running in container.
14:34:59.535  INFO --- [                     main] io.seata.config.FileConfiguration        : The file name of the operation is file:/root/seata-config/registry
14:34:59.542  INFO --- [                     main] io.seata.config.FileConfiguration        : The configuration file used is /root/seata-config/registry.conf

14:35:14.242  INFO --- [                     main] i.s.core.rpc.netty.NettyServerBootstrap  : Server started, listen port: 8091

14:35:14.396 ERROR --- [                     main] io.seata.server.Server                   : nettyServer init error:ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: java.net.ConnectException: Connection refused (Connection refused)
==>
java.lang.RuntimeException: ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: java.net.ConnectException: Connection refused (Connection refused)
	at io.seata.core.rpc.netty.NettyServerBootstrap.start(NettyServerBootstrap.java:157) ~[seata-core-1.4.2.jar:na]
	at io.seata.core.rpc.netty.AbstractNettyRemotingServer.init(AbstractNettyRemotingServer.java:55) ~[seata-core-1.4.2.jar:na]
	at io.seata.core.rpc.netty.NettyRemotingServer.init(NettyRemotingServer.java:52) ~[seata-core-1.4.2.jar:na]
	at io.seata.server.Server.main(Server.java:98) ~[classes/:na]
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: java.net.ConnectException: Connection refused (Connection refused)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:552) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:239) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:200) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:185) ~[nacos-client-1.3.3.jar:na]
	at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:86) ~[seata-discovery-nacos-1.4.2.jar:na]
	at io.seata.core.rpc.netty.NettyServerBootstrap.start(NettyServerBootstrap.java:153) ~[seata-core-1.4.2.jar:na]
	... 3 common frames omitted
<==
```

**Comment by Tarrowren** [comment]
用容器名代替ip地址
```yml
services:
  nacos-server:
    image: nacos/nacos-server:1.4.2
    ports:
      - 8848:8848
```
```
registry {
  type = "nacos"

  nacos {
    application = "seata-server"
    serverAddr = "nacos-server:8848" 不要用127.0.0.1
    group = "REN_GROUP"
    namespace = ""
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
}

config {
  type = "nacos"

  nacos {
    serverAddr = "nacos-server:8848" 不要用127.0.0.1
    group = "REN_GROUP"
    namespace = ""
    username = "nacos"
    password = "nacos"
  }
}
```

**Comment by hunny-sketch** [comment]
No one can resolved?

**Comment by lvjiecn** [comment]
你把nacos的data文件夹删了，重启下

**Comment by FreedomRights** [comment]
我在下方nacos版本说明配置好版本后，把nacos的data文件夹删了，重启后，解决了这个问题。
https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by huangheLee** [comment]
seata 配置项中 seata.config.nacos.server-addr= 后面是ip:port,     我试过， ip改成域名就可以了


例如   1.1.1.1:8848
改为： abc.domain.com:8848

**Comment by fclever1122** [comment]
> seata 配置项中 seata.config.nacos.server-addr= 后面是ip:port, 我试过， ip改成域名就可以了
> 
> 例如 1.1.1.1:8848 改为： abc.domain.com:8848

我使用这个办法解决了，seata.config和registry都把ip换成了localhost就行了
alibaba版本：2.1.0.RELEASE  nacos2.1.1  seata1.7.0

**Comment by fclever1122** [comment]
> > seata 配置项中 seata.config.nacos.server-addr= 后面是ip:port, 我试过， ip改成域名就可以了
> > 例如 1.1.1.1:8848 改为： abc.domain.com:8848
> 
> 我使用这个办法解决了，seata.config和registry都把ip换成了localhost就行了 alibaba版本：2.1.0.RELEASE nacos2.1.1 seata1.7.0

还有一个办法：删掉nacos的data目录，重启nacos，再重启seata也可以

**Comment by lijian12345** [comment]
在本地用nacos 2.2 + seata 1.7试了，不管是改成localhost还是删除nacos的data目录重启，都不管用，不知道为啥

**Comment by lijian12345** [comment]
> 在本地用nacos 2.2 + seata 1.7试了，不管是改成localhost还是删除nacos的data目录重启，都不管用，不知道为啥

试了一下需要把ip换成类似172.17.0.2的容器内部ip才行。这是因为我的nacos和seata没有写在同一个docker-compose里的原因吗

**Comment by lijian12345** [comment]
> > 在本地用nacos 2.2 + seata 1.7试了，不管是改成localhost还是删除nacos的data目录重启，都不管用，不知道为啥
> 
> 试了一下需要把ip换成类似172.17.0.2的容器内部ip才行。这是因为我的nacos和seata没有写在同一个docker-compose里的原因吗

还有一个办法，把localhost改成host.docker.internal

**Comment by Freezeu** [comment]
是容器之间没法互相请求，用docker 启动nacos和seata的时候可以通过network建立虚拟子网和指定容器hostname来解决
