### ISSUE TITLE
数据量较大的情况下，tm 端与 server 端 rpc 通信超时导致请求失败

### ISSUE THREAD

**Issue by shanglangxin** [seata/seata#4003]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Seata 1.4.0 ，AT 模式，通过 feign 进行远程调用，在数据量较大的情况下，tm 端与 server 端 rpc 通信超时导致请求失败，其他的小数据量正常执行。

file.conf 配置
````
 db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp)/HikariDataSource(hikari) etc.
    datasource = "druid"
    ## mysql/oracle/postgresql/h2/oceanbase etc.
    dbType = "mysql"
    driverClassName = "com.mysql.jdbc.Driver"
    url = "jdbc:mysql://192.168.0.243:3306/seata?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai"
    minConn = 5
    maxConn = 100
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    queryLimit = 100
    maxWait = 5000
  }

````

spring application 配置
````
spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.0.243:3306/kyedu-student?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false&requireSSL=true&allowMultiQueries=true&serverTimezone=GMT%2b8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 100
      idle-timeout: 18000000
      max-lifetime: 28770000
      connection-timeout: 30000
      connection-test-query: SELECT 1
````

调用方
````
  @Async
  @Transactional
  @GlobalTransactional
  public void updateExecutionPlanCourseMapping(List<StudentCourseMapping> mappings,
      List<String> majorIds) {
    Map<String, List<StudentCourseMapping>> mappingsByMajorId = mappings.stream()
        .collect(Collectors.groupingBy(StudentCourseMapping::getMajorId));
    for (String majorId : majorIds) {
      UpdateStudentCourseMappingInnerRequest request = new UpdateStudentCourseMappingInnerRequest();
      request.setMappings(MapUtils.get(mappingsByMajorId, majorId, Collections.emptyList()));
      request.setMajorIds(Collections.singletonList(majorId));
     // 调用超时任务
      remoteStudentCourseMappingFacade.updateForInner(request);
    }
  }
````

被调用方
````
 @Override
  @Transactional
  @GlobalTransactional
  public List<StudentCourseMapping> updateForInner(UpdateStudentCourseMappingInnerRequest request) {
    if(ListUtils.isEmpty(request.getMajorIds())){
      throw new BadRequestException("未选中任何教学计划");
    }
    List<StudentCourseMapping> mappings = request.getMappings();
    List<Student> students = listStudentByMajorIds(request.getMajorIds());
    if(ListUtils.isEmpty(students)){
      throw new NotFoundException("获取更新学籍信息为空");
    }
    List<StudentCourseMapping> saveMappings = buildMappingForStudents(students, mappings);
    baseMapper.removeByUserIds(ListUtils.toList(students, Student::getAccountId));
    // 直接调用 mybatis-plus 插入操作
    baseMapper.batchSave(saveMappings);
    return saveMappings;
  }
````

### Ⅱ. Describe what happened

被调用服务报错：
```
2021-09-06 11:06:44.949  INFO 26336 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : channel [id: 0x698e4da2, L:/192.168.0.112:50974 - R:/192.168.0.243:8091] read idle.
2021-09-06 11:06:44.950  INFO 26336 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x698e4da2, L:/192.168.0.112:50974 - R:/192.168.0.243:8091]
2021-09-06 11:06:44.951  INFO 26336 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x698e4da2, L:/192.168.0.112:50974 - R:/192.168.0.243:8091]) will closed
2021-09-06 11:06:44.956  INFO 26336 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x698e4da2, L:/192.168.0.112:50974 ! R:/192.168.0.243:8091]) will closed
2021-09-06 11:06:44.957  INFO 26336 --- [ctor_RMROLE_1_1] i.s.c.r.netty.NettyClientChannelManager  : return to pool, rm channel:[id: 0x698e4da2, L:/192.168.0.112:50974 ! R:/192.168.0.243:8091]
2021-09-06 11:06:44.957  INFO 26336 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : channel valid false,channel:[id: 0x698e4da2, L:/192.168.0.112:50974 ! R:/192.168.0.243:8091]
2021-09-06 11:06:44.957  INFO 26336 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x698e4da2, L:/192.168.0.112:50974 ! R:/192.168.0.243:8091]
2021-09-06 11:06:44.958  INFO 26336 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x698e4da2, L:/192.168.0.112:50974 ! R:/192.168.0.243:8091]) will closed
2021-09-06 11:06:44.958  INFO 26336 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x698e4da2, L:/192.168.0.112:50974 ! R:/192.168.0.243:8091]) will closed
2021-09-06 11:06:44.959  INFO 26336 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : channel inactive: [id: 0x698e4da2, L:/192.168.0.112:50974 ! R:/192.168.0.243:8091]
2021-09-06 11:06:44.960  INFO 26336 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : channel valid false,channel:[id: 0x698e4da2, L:/192.168.0.112:50974 ! R:/192.168.0.243:8091]
2021-09-06 11:06:44.960  INFO 26336 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x698e4da2, L:/192.168.0.112:50974 ! R:/192.168.0.243:8091]
2021-09-06 11:06:44.961  INFO 26336 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x698e4da2, L:/192.168.0.112:50974 ! R:/192.168.0.243:8091]) will closed
2021-09-06 11:06:44.961  INFO 26336 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x698e4da2, L:/192.168.0.112:50974 ! R:/192.168.0.243:8091]) will closed
2021-09-06 11:06:52.877  INFO 26336 --- [eoutChecker_2_1] i.s.c.r.netty.NettyClientChannelManager  : will connect to 192.168.0.243:8091
2021-09-06 11:06:52.878  INFO 26336 --- [eoutChecker_2_1] i.s.c.rpc.netty.RmNettyRemotingClient    : RM will register :jdbc:mysql://192.168.0.243:3306/kyedu-student
2021-09-06 11:06:52.880  INFO 26336 --- [eoutChecker_2_1] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:RMROLE,address:192.168.0.243:8091,msg:< RegisterRMRequest{resourceIds='jdbc:mysql://192.168.0.243:3306/kyedu-student', applicationId='student', transactionServiceGroup='seata_tx_group'} >
2021-09-06 11:06:52.895  INFO 26336 --- [eoutChecker_2_1] i.s.c.rpc.netty.RmNettyRemotingClient    : register RM success. client version:1.4.0, server version:1.4.0,channel:[id: 0x5609da6d, L:/192.168.0.112:54724 - R:/192.168.0.243:8091]
2021-09-06 11:06:52.896  INFO 26336 --- [eoutChecker_2_1] i.s.core.rpc.netty.NettyPoolableFactory  : register success, cost 10 ms, version:1.4.0,role:RMROLE,channel:[id: 0x5609da6d, L:/192.168.0.112:54724 - R:/192.168.0.243:8091]
2021-09-06 11:07:05.770 ERROR 26336 --- [nio-5100-exec-3] i.s.c.r.n.AbstractNettyRemotingClient    : wait response error:cost 30043 ms,ip:192.168.0.243:8091,request:xid=192.168.0.243:8091:178100179513061376,branchType=AT,resourceId=jdbc:mysql://192.168.0.243:3306/kyedu-student,lockKey=......
2021-09-06 11:07:06.728  INFO 26336 --- [h_RMROLE_1_2_12] i.s.c.r.p.c.RmBranchRollbackProcessor    : rm handle branch rollback process:xid=192.168.0.243:8091:178100179513061376,branchId=178100198274183169,branchType=AT,resourceId=jdbc:mysql://192.168.0.243:3306/kyedu-student,applicationData=null
2021-09-06 11:07:06.731  INFO 26336 --- [h_RMROLE_1_2_12] io.seata.rm.AbstractRMHandler            : Branch Rollbacking: 192.168.0.243:8091:178100179513061376 178100198274183169 jdbc:mysql://192.168.0.243:3306/kyedu-student
2021-09-06 11:07:06.744  INFO 26336 --- [h_RMROLE_1_2_12] i.s.r.d.undo.AbstractUndoLogManager      : xid 192.168.0.243:8091:178100179513061376 branch 178100198274183169, undo_log added with GlobalFinished
2021-09-06 11:07:06.746  INFO 26336 --- [h_RMROLE_1_2_12] io.seata.rm.AbstractRMHandler            : Branch Rollbacked result: PhaseTwo_Rollbacked
2021-09-06 11:07:06.892  INFO 26336 --- [h_RMROLE_1_3_12] i.s.c.r.p.c.RmBranchRollbackProcessor    : rm handle branch rollback process:xid=192.168.0.243:8091:178100179513061376,branchId=178100198274183169,branchType=AT,resourceId=jdbc:mysql://192.168.0.243:3306/kyedu-student,applicationData=null
2021-09-06 11:07:06.893  INFO 26336 --- [h_RMROLE_1_3_12] io.seata.rm.AbstractRMHandler            : Branch Rollbacking: 192.168.0.243:8091:178100179513061376 178100198274183169 jdbc:mysql://192.168.0.243:3306/kyedu-student
2021-09-06 11:07:06.899  INFO 26336 --- [h_RMROLE_1_3_12] i.s.r.d.undo.AbstractUndoLogManager      : xid 192.168.0.243:8091:178100179513061376 branch 178100198274183169, ignore 1 undo_log
2021-09-06 11:07:06.901  INFO 26336 --- [h_RMROLE_1_3_12] io.seata.rm.AbstractRMHandler            : Branch Rollbacked result: PhaseTwo_Rollbacked
2021-09-06 11:07:07.014  INFO 26336 --- [nio-5100-exec-3] i.seata.tm.api.DefaultGlobalTransaction  : [192.168.0.243:8091:178100179513061376] rollback status: Rollbacked
2021-09-06 11:07:07.107 ERROR 26336 --- [nio-5100-exec-3] c.k.c.w.c.GlobalExceptionHandler         : 未知异常！原因是

org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: RPC Timeout
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:332)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:633)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:386)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$2.execute(GlobalTransactionalInterceptor.java:184)
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:127)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:181)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:150)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.kyedu.student.service.impl.StudentCourseMappingServiceImpl$$EnhancerBySpringCGLIB$$1.updateForInner(<generated>)
	at com.kyedu.student.controller.inner.StudentCourseMappingInnerController.updateForInner(StudentCourseMappingInnerController.java:74)
	at com.kyedu.student.controller.inner.StudentCourseMappingInnerController$$FastClassBySpringCGLIB$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.kyedu.auth.permission.aspect.InnerServiceAspect.around(InnerServiceAspect.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.kyedu.student.controller.inner.StudentCourseMappingInnerController$$EnhancerBySpringCGLIB$$1.updateForInner(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.kyedu.core.web.filter.XssFilter.doFilterInternal(XssFilter.java:31)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.kyedu.core.web.filter.AuthDataInitFilter.doFilterInternal(AuthDataInitFilter.java:19)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:41002)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: io.seata.core.exception.RmTransactionException: RPC Timeout
	at io.seata.rm.datasource.ConnectionProxy.recognizeLockKeyConflictException(ConnectionProxy.java:157)
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:221)
	at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:199)
	at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:184)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:292)
	at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:183)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:329)
	... 100 common frames omitted
Caused by: io.seata.core.exception.RmTransactionException: RPC Timeout
	at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:73)
	at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96)
	at io.seata.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:241)
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:219)
	... 105 common frames omitted
Caused by: java.util.concurrent.TimeoutException: cost 30043 ms
	at io.seata.core.protocol.MessageFuture.get(MessageFuture.java:62)
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient.sendSyncRequest(AbstractNettyRemotingClient.java:169)
	at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:67)
	... 108 common frames omitted
```

seata-server 报错: 
```
java.lang.NullPointerException: null
	at io.seata.core.rpc.netty.ChannelManager.getSameClientChannel(ChannelManager.java:243) ~[seata-core-1.4.0.jar:na]
	at io.seata.core.rpc.netty.AbstractNettyRemotingServer.sendAsyncResponse(AbstractNettyRemotingServer.java:96) ~[seata-core-1.4.0.jar:na]
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:120) ~[seata-core-1.4.0.jar:na]
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77) ~[seata-core-1.4.0.jar:na]
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:278) ~[seata-core-1.4.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_211]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_211]
```

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by a364176773** [comment]
数据量大概多大？

**Comment by shanglangxin** [comment]
6k，先删除，后插入

**Comment by a364176773** [comment]
> 6k，先删除，后插入

这6k的操作数据量是在一个本地事务完成的吗？或者说在同一个rm完成的吗？如果是在一个rm中完成，是否在操作6k数据的时候再这个地方加了@transactional注解？

**Comment by shanglangxin** [comment]
> > 6k，先删除，后插入
> 
> 这6k的操作数据量是在一个本地事务完成的吗？或者说在同一个rm完成的吗？如果是在一个rm中完成，是否在操作6k数据的时候再这个地方加了@transactional注解？

该操作是同一个 rm 完成，这个操作的方法上同时添加 @transactional @GlobalTransactional 两个注解

**Comment by a364176773** [comment]
> > > 6k，先删除，后插入
> > 
> > 
> > 这6k的操作数据量是在一个本地事务完成的吗？或者说在同一个rm完成的吗？如果是在一个rm中完成，是否在操作6k数据的时候再这个地方加了@transactional注解？
> 
> 该操作是同一个 rm 完成，这个操作的方法上同时添加 @transactional @GlobalTransactional 两个注解

好的，我晚点试试这个数据量，暂时的话，拆成几个transactional，删除单独一个，插入也单独一个试试，或者你有什么想法可以在这继续沟通

**Comment by a364176773** [comment]
请问一下tc存储是db还是redis?

**Comment by shanglangxin** [comment]
> 请问一下tc存储是db还是redis?

用的是 db

**Comment by shanglangxin** [comment]
当前 seata 存储配置
```
store.mode=db
store.db.datasource=druid
store.db.dbType=mysql
store.db.driverClassName=com.mysql.jdbc.Driver
store.db.minConn=5
store.db.maxConn=30
store.db.globalTable=global_table
store.db.branchTable=branch_table
store.db.queryLimit=100
store.db.lockTable=lock_table
store.db.maxWait=5000

```

**Comment by shanglangxin** [comment]
后续补充：移除插入操作后，仅进行删除操作，删除数据量为6K，依旧出现上述问题

**Comment by pikachulight** [comment]
> 后续补充：移除插入操作后，仅进行删除操作，删除数据量为6K，依旧出现上述问题

增加心跳时间应该可以解决

**Comment by shanglangxin** [comment]
> > 后续补充：移除插入操作后，仅进行删除操作，删除数据量为6K，依旧出现上述问题
> 
> 增加心跳时间应该可以解决

在 seata 文档说明中没有提供心跳时间设置的字段。增加心跳时间 是指哪个字段呢？

**Comment by caohdgege** [comment]
6000好像数据量也不大，如果方便的话贴一下你写的关键代码(伪代码)。还有你的Seata的版本和store.db.url配置(可以把host, db_name, port脱敏，其他的不要改)。

**Comment by shanglangxin** [comment]
> 6000好像数据量也不大，如果方便的话贴一下你写的关键代码(伪代码)。还有你的Seata的版本和store.db.url配置(可以把host, db_name, port脱敏，其他的不要改)。

部分代码和配置已在问题描述模块补充

**Comment by pikachulight** [comment]
> > > 后续补充：移除插入操作后，仅进行删除操作，删除数据量为6K，依旧出现上述问题
> > 
> > 
> > 增加心跳时间应该可以解决
> 
> 在 seata 文档说明中没有提供心跳时间设置的字段。增加心跳时间 是指哪个字段呢？

我之前是改的源码重新编译的

**Comment by caohdgege** [comment]
![image](https://user-images.githubusercontent.com/22959373/134792873-db40a182-3ffc-418c-a255-9f1b5903f4c5.png)
url加上这一段再试试。

原因见官网参数配置-附录7
http://seata.io/zh-cn/docs/user/configurations.html

**Comment by shanglangxin** [comment]
> > > > 后续补充：移除插入操作后，仅进行删除操作，删除数据量为6K，依旧出现上述问题
> > > 
> > > 
> > > 增加心跳时间应该可以解决
> > 
> > 
> > 在 seata 文档说明中没有提供心跳时间设置的字段。增加心跳时间 是指哪个字段呢？
> 
> 我之前是改的源码重新编译的

好的 我后续尝试一下
