### ISSUE TITLE
in the development version,unregister service fails

### ISSUE THREAD

**Issue by a364176773** [seata/seata#4028]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![lALPDiCpwRkCepXNASjNBxg_1816_296](https://user-images.githubusercontent.com/19943636/133924567-b6d69972-6902-4e36-b0ed-dd954a042586.png)
```
19:36:58.442  INFO --- [SpringContextShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
19:37:00.965 ERROR --- [             ShutdownHook] i.s.core.rpc.netty.NettyServerBootstrap  : shutdown execute error:org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5a4c638d has been closed already
==>
java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5a4c638d has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1093) ~[spring-context-5.2.14.RELEASE.jar:5.2.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1126) ~[spring-context-5.2.14.RELEASE.jar:5.2.14.RELEASE]
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:100) ~[classes/:na]
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:85) ~[classes/:na]
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$200(SpringBootConfigurationProvider.java:46) ~[classes/:na]
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:61) ~[classes/:na]
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>) ~[classes/:na]
	at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.getServiceName(NacosRegistryServiceImpl.java:214) ~[classes/:na]
	at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.unregister(NacosRegistryServiceImpl.java:92) ~[classes/:na]
	at io.seata.core.rpc.netty.NettyServerBootstrap.shutdown(NettyServerBootstrap.java:187) ~[classes/:na]
	at io.seata.core.rpc.netty.AbstractNettyRemotingServer.destroy(AbstractNettyRemotingServer.java:126) ~[classes/:na]
	at io.seata.core.rpc.ShutdownHook$DisposablePriorityWrapper.destroy(ShutdownHook.java:113) ~[classes/:na]
	at io.seata.core.rpc.ShutdownHook.destroyAll(ShutdownHook.java:82) ~[classes/:na]
	at io.seata.core.rpc.ShutdownHook.run(ShutdownHook.java:66) ~[classes/:na]
<==
```
1.5.0-snapshot下,seata-server是利用applicationcontext获取配置,而runtime.shutdownhook是异步进行,导致spring容器关闭后,才去做相关操作,导致注册中心主动下线服务失败
Under 1.5.0-snapshot, seata-server uses applicationcontext to obtain configuration, and runtime.shutdownhook is performed asynchronously, which causes the spring container to be closed before performing related operations, which causes the registry to actively offline service failure 

Process finished with exit code 130

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by lvekee** [comment]
Please assign it to me

**Comment by Pinocchio2018** [comment]
@a364176773 hello大佬，我问问，该如何正确复现这个报错呢？

我的测试步骤：
1. 切到最新版 develop
![image](https://user-images.githubusercontent.com/24909409/133963929-21fdcc09-a197-451a-8cc3-f57128dec0d3.png)

2. 本地使用nacos v1.4.2启动
![image](https://user-images.githubusercontent.com/24909409/133964097-239836bd-3d40-4859-a22f-8ded592dade0.png)

3. 修改applicationyml
![image](https://user-images.githubusercontent.com/24909409/133964253-1a778960-b457-44b3-8fa3-5c99ba4a702e.png)

4. 在idea内，run `io.seata.server.ServerApplication`
![image](https://user-images.githubusercontent.com/24909409/133964396-3f90b80c-f36f-4094-b4ff-1e3810ea2d0b.png)

5. 可以在nacos看到seata server已经注册成功了
![image](https://user-images.githubusercontent.com/24909409/133964486-1784d36c-398d-46a6-b077-6f2859b37e1d.png)

6. 点击下线后，并未发现报错...

**Comment by Pinocchio2018** [comment]
我想说下我的看法，大家看看对不对。

目前发生这个报错的原因是，销毁的时候交给了 jvm自带的`ShutdownHook`来处理了，导致轮到`ShutdownHook`做销毁的时候，spring context已经关闭了。

是不是只要把`AbstractNettyRemotingServer`的生命周期，交给spring来管理，就不会发生这个报错了啊？

**Comment by a364176773** [comment]
> @a364176773 hello大佬，我问问，该如何正确复现这个报错呢？
> 
> 我的测试步骤：
> 
> 1. 切到最新版 develop
>    ![image](https://user-images.githubusercontent.com/24909409/133963929-21fdcc09-a197-451a-8cc3-f57128dec0d3.png)
> 2. 本地使用nacos v1.4.2启动
>    ![image](https://user-images.githubusercontent.com/24909409/133964097-239836bd-3d40-4859-a22f-8ded592dade0.png)
> 3. 修改applicationyml
>    ![image](https://user-images.githubusercontent.com/24909409/133964253-1a778960-b457-44b3-8fa3-5c99ba4a702e.png)
> 4. 在idea内，run `io.seata.server.ServerApplication`
>    ![image](https://user-images.githubusercontent.com/24909409/133964396-3f90b80c-f36f-4094-b4ff-1e3810ea2d0b.png)
> 5. 可以在nacos看到seata server已经注册成功了
>    ![image](https://user-images.githubusercontent.com/24909409/133964486-1784d36c-398d-46a6-b077-6f2859b37e1d.png)
> 6. 点击下线后，并未发现报错...

就是这样的步骤，说明不是必现，因为这个shutdown是异步的

**Comment by a364176773** [comment]
> 我想说下我的看法，大家看看对不对。
> 
> 目前发生这个报错的原因是，销毁的时候交给了 jvm自带的`ShutdownHook`来处理了，导致轮到`ShutdownHook`做销毁的时候，spring context已经关闭了。
> 
> 是不是只要把`AbstractNettyRemotingServer`的生命周期，交给spring来管理，就不会发生这个报错了啊？

可以这么说，应该用spring的DisposableBean来触发，但是切记不要影响rm 和 tm的shut down hook正常运行
