### ISSUE TITLE
AT 全局事务过长

### ISSUE THREAD

**Issue by HelloWorldwangjiacheng** [seata/seata#4106]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata AT模式下全局事务过长。

### Ⅱ. Describe what happened
全局事务采用AT模式。
场景链路描述：
1. 创建订单（createOrder），创建订单的时候先创建业务订单，然后远程调用支付系统，创建支付订单，然后更新业务订单中的payOrderId这个字段。
2. 创建订单成功后，前端感知到后，再调用微信支付接口(wxPay)，
3. 微信支付接口，在具体的实现类中更新业务订单相关信息，没有异步操作。

问题：
理想状态：
      因为@GlobalTransactional是放在createOrder方法上，所以正常来说1应该是一个全局事务，涉及到了两个模块（业务系统和支付系统），2应该是不算。
现实情况：
     现在全局事务貌似将1、2、3三个过程（一个链路）都放在一个全局事务中了，在3中提交commit的时候说找不到XID，于是无法提交，本身SQL是没有问题的，因为没用分布式事务之前也是这么写，没有异常过的。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
 重现的话也是很奇怪的，因为重启支付系统之后，一到两天内这个问题很少出现，但时间异常就开始了。而且就是很简单的支付。

### Ⅴ. Anything else we need to know?
我觉得错误信息还是需要贴一下。当然其中一些非技术信息会模糊处理
`2021-10-31 21:44:37,132 [http-nio-10400-exec-34] ERROR [com.smartCommit.core.aop.GlobalExceptionHandler] - - - 运行时异常, 路径:/api/wx/pay/wxpay, 异常:{}
org.springframework.jdbc.UncategorizedSQLException: 
### Cause: java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.110:8091:999991287687454314, may be has finished.] ]
; uncategorized SQLException; SQL state [null]; error code [0]; io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.110:8091:999991287687454314, may be has finished.] ]; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.110:8091:999991287687454314, may be has finished.] ]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
        at com.sun.proxy.$Proxy166.update(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:294)
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:69)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
        at com.sun.proxy.$Proxy173.update(Unknown Source)
        at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.update(ServiceImpl.java:213)
        at com.smartCommit.pay.service.pay.impl.OrderServiceImpl.getWxPaySign(OrderServiceImpl.java:386)
        at com.smartCommit.pay.service.pay.impl.OrderServiceImpl$$FastClassBySpringCGLIB$$438f7778.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
        at com.smartCommit.pay.service.pay.impl.OrderServiceImpl$$EnhancerBySpringCGLIB$$3e81f092.getWxPaySign(<generated>)
        at com.smartCommit.pay.service.pay.impl.OrderServiceImpl$$FastClassBySpringCGLIB$$438f7778.invoke(<generated>)
`

### Ⅵ. Environment:

- JDK version :  1.8
- Seata version:  1.4.2
- OS : centos7
- Others:  spring全家桶、sharing-jdbc4.1

**Comment by a364176773** [comment]
1.如果tc是一个高可用集群部署，就要保证不要让store使用file模式
2.多个tc的时区统一与数据库保持一致
3.排查这个xid在发起方的什么时间点决议，看下状态是什么，有没有异常，而不是在抛出异常的节点3去排查

**Comment by HelloWorldwangjiacheng** [comment]
你好，tc是一个seata-server，不是集群，内存大小默认，最大可分配2G，所以建议1和2其实可以略过。
其实，我这边有一个疑问，两个接口理论上来说是隔离，业务链路上:
 创建订单（createOrder）->前端获取成功返回结果, 请求通用支付接口->微信支付（doWxPay）
理论上，两个接口是隔离，事实上，大部分订单也是没问题的。
但全局事务却包括了createOrder和doWxPay 这两个接口， 
其实seata它说XID找不到，这是正常的。不正常的是，它为什么要去找XID??? createOrder 和 doWxPay应该是两个事务，而不是一个事务。
createOrder成功之后，前端获取返回值之前，就应该提交数据库，持久化了。
这样，我先复现问题，再debug看一下。
谢谢你的回复，万分感谢

**Comment by a364176773** [comment]
xid是一个全局的事务，createOrder和doWxPay只是xid下的分支事务，要去向这个xid的全局事务注册分支，如果注册不上，你要看下传递到你这xid的发起方那边的日志是什么情况，按xid查找日志即可，把相关发起方的这个xid的日志贴上来
