### ISSUE TITLE
客户端访问接口，Failed to get available servers: register eureka is error!

### ISSUE THREAD

**Issue by ihusky** [seata/seata#4124]
1.服务端启动可以正常注册到eukera, 客户端启动没问题，访问接口报错 io.seata.common.exception.EurekaRegistryException: register eureka is error!

服务端：registry.conf
  eureka {
    serviceUrl = "http://eureka-k8s:8761/eureka/"
    application = "seata-server"
    weight = "1"
  }

客户端：
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: seata_tx_group
  service:
    vgroup-mapping:
      seata_tx_group: seata-server
  config:
    type: file
    file:
      name: file.conf
  registry:
    type: eureka
    eureka:
      service-url: http://eureka-k8s:8761/eureka/
      weight: 1

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.3
- OS : 
- Others:

**Comment by a364176773** [comment]
堆栈能给详细点不？

**Comment by ihusky** [comment]
> 堆栈能给详细点不？

[https://image.myxkcdn.com/xk/image/project_1/mch/20211110/6a43ed02-b5ad-8291-3393-4dbed1ba7189](url)

**Comment by ihusky** [comment]
> 堆栈能给详细点不？

2021-11-10 15:02:40.701 [timeoutChecker_2_1] WARN  com.netflix.discovery.internal.util.Archaius1Utils - Cannot find the properties specified : eureka-client. This may be okay if there are other environment specific properties or the configuration is installed with a different mechanism.
2021-11-10 15:02:40.701 [timeoutChecker_2_1] INFO  c.n.a.p.EurekaConfigBasedInstanceInfoProvider - Setting initial instance status as: STARTING
2021-11-10 15:02:40.702 [timeoutChecker_2_1] WARN  com.netflix.discovery.internal.util.Archaius1Utils - Cannot find the properties specified : eureka-client. This may be okay if there are other environment specific properties or the configuration is installed with a different mechanism.
2021-11-10 15:02:40.702 [timeoutChecker_2_1] INFO  com.netflix.discovery.DiscoveryClient - Initializing Eureka in region us-east-1
2021-11-10 15:02:40.703 [timeoutChecker_2_1] ERROR io.seata.core.rpc.netty.NettyClientChannelManager - Failed to get available servers: register eureka is error!
io.seata.common.exception.EurekaRegistryException: register eureka is error!
	at io.seata.discovery.registry.eureka.EurekaRegistryServiceImpl.getEurekaClient(EurekaRegistryServiceImpl.java:231)
	at io.seata.discovery.registry.eureka.EurekaRegistryServiceImpl.refreshCluster(EurekaRegistryServiceImpl.java:153)
	at io.seata.discovery.registry.eureka.EurekaRegistryServiceImpl.lookup(EurekaRegistryServiceImpl.java:132)
	at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:217)
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:162)
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to initialize DiscoveryClient!
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:411)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:269)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:265)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:257)
	at io.seata.discovery.registry.eureka.EurekaRegistryServiceImpl.getEurekaClient(EurekaRegistryServiceImpl.java:227)
	... 14 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/netflix/discovery/shared/transport/jersey/EurekaJerseyClientImpl$EurekaJerseyClientBuilder$MyDefaultApacheHttpClient4Config
	at com.netflix.discovery.shared.transport.jersey.EurekaJerseyClientImpl$EurekaJerseyClientBuilder.build(EurekaJerseyClientImpl.java:178)
	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory$JerseyEurekaHttpClientFactoryBuilder.buildLegacy(JerseyEurekaHttpClientFactory.java:230)
	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory$JerseyEurekaHttpClientFactoryBuilder.build(JerseyEurekaHttpClientFactory.java:204)
	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory.create(JerseyEurekaHttpClientFactory.java:161)
	at com.netflix.discovery.shared.transport.jersey.Jersey1TransportClientFactories.newTransportClientFactory(Jersey1TransportClientFactories.java:59)
	at com.netflix.discovery.DiscoveryClient.scheduleServerEndpointTask(DiscoveryClient.java:485)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:398)
	... 18 common frames omitted
2021-11-10 15:02:50.670 [timeoutChecker_1_1] WARN  com.netflix.discovery.internal.util.Archaius1Utils - Cannot find the properties specified : eureka-client. This may be okay if there are other environment specific properties or the configuration is installed with a different mechanism.
2021-11-10 15:02:50.670 [timeoutChecker_1_1] INFO  c.n.a.p.EurekaConfigBasedInstanceInfoProvider - Setting initial instance status as: STARTING
2021-11-10 15:02:50.671 [timeoutChecker_1_1] WARN  com.netflix.discovery.internal.util.Archaius1Utils - Cannot find the properties specified : eureka-client. This may be okay if there are other environment specific properties or the configuration is installed with a different mechanism.
2021-11-10 15:02:50.671 [timeoutChecker_1_1] INFO  com.netflix.discovery.DiscoveryClient - Initializing Eureka in region us-east-1
2021-11-10 15:02:50.672 [timeoutChecker_1_1] ERROR io.seata.core.rpc.netty.NettyClientChannelManager - Failed to get available servers: register eureka is error!
io.seata.common.exception.EurekaRegistryException: register eureka is error!
	at io.seata.discovery.registry.eureka.EurekaRegistryServiceImpl.getEurekaClient(EurekaRegistryServiceImpl.java:231)
	at io.seata.discovery.registry.eureka.EurekaRegistryServiceImpl.refreshCluster(EurekaRegistryServiceImpl.java:153)
	at io.seata.discovery.registry.eureka.EurekaRegistryServiceImpl.lookup(EurekaRegistryServiceImpl.java:132)
	at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:217)
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:162)
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to initialize DiscoveryClient!
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:411)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:269)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:265)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:257)
	at io.seata.discovery.registry.eureka.EurekaRegistryServiceImpl.getEurekaClient(EurekaRegistryServiceImpl.java:227)
	... 14 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/netflix/discovery/shared/transport/jersey/EurekaJerseyClientImpl$EurekaJerseyClientBuilder$MyDefaultApacheHttpClient4Config
	at com.netflix.discovery.shared.transport.jersey.EurekaJerseyClientImpl$EurekaJerseyClientBuilder.build(EurekaJerseyClientImpl.java:178)
	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory$JerseyEurekaHttpClientFactoryBuilder.buildLegacy(JerseyEurekaHttpClientFactory.java:230)
	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory$JerseyEurekaHttpClientFactoryBuilder.build(JerseyEurekaHttpClientFactory.java:204)
	at com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory.create(JerseyEurekaHttpClientFactory.java:161)
	at com.netflix.discovery.shared.transport.jersey.Jersey1TransportClientFactories.newTransportClientFactory(Jersey1TransportClientFactories.java:59)
	at com.netflix.discovery.DiscoveryClient.scheduleServerEndpointTask(DiscoveryClient.java:485)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:398)
	... 18 common frames omitted

**Comment by ihusky** [comment]
> 堆栈能给详细点不？

在上面了，谢谢

**Comment by a364176773** [comment]
NoClassDefFoundError 检查是否有依赖冲突
