### ISSUE TITLE
open-feign远程调用报错

### ISSUE THREAD

**Issue by IvanCai** [seata/seata#4129]
java.lang.IllegalArgumentException: Could not find class [org.springframework.boot.autoconfigure.condition.OnPropertyCondition]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:334) ~[spring-core-5.3.4.jar!/:5.3.4]
	at org.springframework.context.annotation.ConditionEvaluator.getCondition(ConditionEvaluator.java:124) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:96) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:88) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:71) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.doRegisterBean(AnnotatedBeanDefinitionReader.java:254) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:147) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.register(AnnotatedBeanDefinitionReader.java:137) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.register(AnnotationConfigApplicationContext.java:168) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:122) ~[spring-cloud-context-3.0.2.jar!/:3.0.2]
	at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:101) ~[spring-cloud-context-3.0.2.jar!/:3.0.2]
	at org.springframework.cloud.context.named.NamedContextFactory.getInstances(NamedContextFactory.java:181) ~[spring-cloud-context-3.0.2.jar!/:3.0.2]
	at org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient.execute(FeignBlockingLoadBalancerClient.java:85) ~[spring-cloud-openfeign-core-3.0.2.jar!/:3.0.2]
	at com.alibaba.cloud.seata.feign.SeataFeignBlockingLoadBalancerClient.execute(SeataFeignBlockingLoadBalancerClient.java:46) ~[spring-cloud-starter-alibaba-seata-2021.1.jar!/:2021.1]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119) ~[feign-core-10.10.1.jar!/:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[feign-core-10.10.1.jar!/:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[feign-core-10.10.1.jar!/:na]
	at com.sun.proxy.$Proxy175.getWarehouseProductInfo(Unknown Source) ~[na:na]
	at com.tudgo.warehouse.service.product.impl.ProductServiceImpl.saveOrUpdateProduct(ProductServiceImpl.java:58) ~[service-1.0.0.RELEASE.jar!/:na]
	at com.tudgo.warehouse.service.product.impl.ProductServiceImpl$$FastClassBySpringCGLIB$$909dee1.invoke(<generated>) ~[service-1.0.0.RELEASE.jar!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at com.tudgo.warehouse.service.product.impl.ProductServiceImpl$$EnhancerBySpringCGLIB$$cf6e946c.saveOrUpdateProduct(<generated>) ~[service-1.0.0.RELEASE.jar!/:na]
	at com.tudgo.warehouse.service.warehouseproduct.impl.WarehouseProductServiceImpl.doMandatoryDistributionReduceWarehouseStock(WarehouseProductServiceImpl.java:1057) ~[service-1.0.0.RELEASE.jar!/:na]
	at com.tudgo.warehouse.service.warehouseproduct.impl.WarehouseProductServiceImpl$$FastClassBySpringCGLIB$$deb80349.invoke(<generated>) ~[service-1.0.0.RELEASE.jar!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:128) ~[seata-all-1.3.0.jar!/:1.3.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at com.tudgo.warehouse.service.warehouseproduct.impl.WarehouseProductServiceImpl$$EnhancerBySpringCGLIB$$239f02a4.doMandatoryDistributionReduceWarehouseStock(<generated>) ~[service-1.0.0.RELEASE.jar!/:na]
	at com.tudgo.warehouse.service.warehouseproduct.impl.WarehouseProductServiceImpl.lambda$mandatoryDistributionReduceWarehouseStock$39(WarehouseProductServiceImpl.java:880) ~[service-1.0.0.RELEASE.jar!/:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.autoconfigure.condition.OnPropertyCondition
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:398) ~[na:na]
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284) ~[spring-core-5.3.4.jar!/:5.3.4]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:324) ~[spring-core-5.3.4.jar!/:5.3.4]
	... 41 common frames omitted
已经正常运行了一段时间，突然就报了这种错误。

**Comment by a364176773** [comment]
ClassNotFoundException 你应该自己排查下是不是有相关的依赖冲突，缺依赖之类的情况，建议去sca社区提issue，这堆栈里没有seata相关信息
