### ISSUE TITLE
get global lock fail, xid:xxx:8091:9205983199890188,lockKeys:sg_storage:7564566

### ISSUE THREAD

**Issue by 1317963611** [seata/seata#4139]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
io.seata.rm.datasource.exec.LockConflictException: get global lock fail

### Ⅱ. Describe what happened
我在尝试对两个服务（分布式）之间做并发压力测试时，遇到了此问题，翻阅过Seata的官方文档后，更改了 ：

1. client.rm.lock.retryPolicyBranchRollbackOnConflict=false

2.client.rm.lock.retryInterval=300 (间隔300毫秒)

3.client.rm.lock.retryTimes=200（重试200次）

4.查看了row_key的长度，没有问题，因为我已经将其改为了text

5.单个接口测试下没有问题，现在是并发200，出现了此问题 。

========================================
但是我在查看日志时，发现并没有生效，程序很快就报错了 。
因此有些不解，困扰了挺久

```
* org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is io.seata.rm.datasource.exec.LockConflictException: get global lock fail, xid:172.19.202.10:8091:9205983199890188, lockKeys:sg_storage:7564566;sg_storage:7564720;sg_storage:7564321;sg_storage:7564684;sg_storage:7563992;sg_storage:7564003;sg_storage:7564286;sg_storage:7564363;sg_storage:7564561;sg_storage:7564042;sg_storage:7564087;sg_storage:7564164;sg_storage:7564362;sg_storage:7564280;sg_storage:7564607;sg_storage:7564527;sg_storage:7564604;sg_storage:7564605;sg_storage:7564569;sg_storage:7564646;sg_storage:7564723;sg_storage:7564205;sg_storage:7563982;sg_storage:7564235;sg_storage:7563983;sg_storage:7564032;sg_storage:7564197;sg_storage:7564271;sg_storage:7564272;sg_storage:7564192;sg_storage:7563984;sg_storage:7564755;sg_storage:7564225;sg_storage:7564343;sg_storage:7564421;sg_storage:7564144;sg_storage:7564386;sg_storage:7564540;sg_storage:7564748;sg_storage:7564226;sg_storage:7564502;sg_storage:7564134;sg_storage:7564256;sg_storage:7564572;sg_storage:7564131;sg_storage:7564571;sg_storage:7564171;sg_storage_ftp:2030656,2030657,2030666,2030635,2030667,2030636,2030668,2030637,2030669,2030638,2030670,2030639,2030671,2030640,2030672,2030641,2030673,2030642,2030674,2030643,2030675,2030658,2030644,2030676,2030645,2030677,2030646,2030678,2030647,2030679,2030648,2030680,2030649,2030681,2030650,2030682,2030651,2030683,2030652,2030684,2030653,2030659,2030654,2030655,2030660,2030661,2030662,2030663,2030664,2030665;sg_storage_ftp:2030688,2030720,2030689,2030721,2030698,2030730,2030699,2030731,2030700,2030732,2030701,2030733,2030702,2030734,2030703,2030704,2030705,2030706,2030707,2030690,2030722,2030708,2030709,2030710,2030711,2030712,2030713,2030714,2030715,2030716,2030685,2030717,2030691,2030723,2030686,2030718,2030687,2030719,2030692,2030724,2030693,2030725,2030694,2030726,2030695,2030727,2030696,2030728,2030697,2030729;sg_storage:7564536;sg_storage:7564658;sg_storage:7564578
*         at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:332) ~[spring-jdbc-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
*         at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743) ~[spring-tx-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711) ~[spring-tx-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:633) ~[spring-tx-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:386) ~[spring-tx-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
*         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
*         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
*         at com.mg.drp.sk.controller.SgUpdateStorageController$$EnhancerBySpringCGLIB$$d0428db4.updateAndReleaseStorage(<generated>) ~[classes!/:?]
*         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
*         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_301]
*         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_301]
*         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_301]
*         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) ~[spring-webmvc-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.45.jar!/:?]
*         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at com.mg.kernel.xss.XssFilter.doFilter(XssFilter.java:80) ~[mg-kernel-framework-1.4.38.jar!/:?]
*         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.3.10.RELEASE.jar!/:2.3.10.RELEASE]
*         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.14.RELEASE.jar!/:5.2.14.RELEASE]
*         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.StandardHostValve.invoke$original$xRtvHvXd(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.StandardHostValve.invoke$original$xRtvHvXd$accessor$Vewzdfug(StandardHostValve.java) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.StandardHostValve$auxiliary$UadYpDid.call(Unknown Source) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86) ~[skywalking-agent.jar:8.0.1]
*         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
*         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
*         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.45.jar!/:?]
*         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]

```

### Ⅲ. Describe what you expected to happen

如何让“全局锁重试”功能生效？目前看来并没有生效

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:   1.4.2
- OS : Centos 
- Others:

**Comment by 1317963611** [comment]
OS : 阿里云Centos:7.8

**Comment by a364176773** [comment]
开启本地事务时，锁竞争周期是失效的，这将在1.5.0中进行修复，先拿掉translational注解看看吧

**Comment by 1317963611** [comment]
> 开启本地事务时，锁竞争周期是失效的，这将在1.5.0中进行修复，先拿掉translational注解看看吧

嗯，是作为被调用方拿掉Transactional ？

**Comment by a364176773** [comment]
任何dml操作的地方，有translational注解就会使竞争锁周期失效，如果想让transactional下也能竞争锁，需要@Trancational+对即将修改的数据进行select for update 再进行update等操作

**Comment by 1317963611** [comment]
> 任何dml操作的地方，有translational注解就会使竞争锁周期失效，如果想让transactional下也能竞争锁，需要@Trancational+对即将修改的数据进行select for update 再进行update等操作

这样子对目前代码改动太大了，1.5.0什么时候发布呢

**Comment by 1317963611** [comment]
感谢来信，已收到
