### ISSUE TITLE
AT模式下使用跨表更新时出现SQLTableSource强转错误

### ISSUE THREAD

**Issue by he953481025-debug** [seata/seata#4147]
堆栈信息如下

Caused by: java.lang.ClassCastException: com.alibaba.druid.sql.ast.statement.SQLJoinTableSource cannot be cast to com.alibaba.druid.sql.ast.statement.SQLExprTableSource
        at io.seata.sqlparser.druid.mysql.MySQLUpdateRecognizer.getTableName(MySQLUpdateRecognizer.java:129) ~[seata-all-1.3.0.jar:1.3.0]
        at io.seata.rm.datasource.exec.BaseTransactionalExecutor.getTableMeta(BaseTransactionalExecutor.java:206) ~[seata-all-1.3.0.jar:1.3.0]
        at io.seata.rm.datasource.exec.UpdateExecutor.beforeImage(UpdateExecutor.java:69) ~[seata-all-1.3.0.jar:1.3.0]
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:92) ~[seata-all-1.3.0.jar:1.3.0]
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$0(AbstractDMLBaseExecutor.java:111) ~[seata-all-1.3.0.jar:1.3.0]
        at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:299) ~[seata-all-1.3.0.jar:1.3.0]
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:155) ~[seata-all-1.3.0.jar:1.3.0]
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:110) ~[seata-all-1.3.0.jar:1.3.0]
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:74) ~[seata-all-1.3.0.jar:1.3.0]
        at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:115) ~[seata-all-1.3.0.jar:1.3.0]
        at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:113) ~[seata-all-1.3.0.jar:1.3.0]
        ... 106 common frames omitted

**Comment by a364176773** [comment]
不支持join

**Comment by caohdgege** [comment]
same with https://github.com/seata/seata/issues/4118
