### ISSUE TITLE
一直报错0318，不影响使用

### ISSUE THREAD

**Issue by 303470934** [seata/seata#4155]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata可以正常工作，但是项目一直输出这个错误。我的Linux服务器已经重启过了，seata重新启动，项目重新启动，依然报错，依然无法解决。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
`2021-11-26 18:20:04.205 ERROR 22760 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : 0318

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_131]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2021-11-26 18:20:04.205  INFO 22760 --- [ctor_RMROLE_1_1] i.s.c.r.netty.NettyClientChannelManager  : return to pool, rm channel:[id: 0x284ebcbc, L:/172.16.19.240:3880 - R:/192.144.237.180:8091]
2021-11-26 18:20:04.205  INFO 22760 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : remove exception rm channel:[id: 0x284ebcbc, L:/172.16.19.240:3880 - R:/192.144.237.180:8091]
2021-11-26 18:20:04.205  WARN 22760 --- [ctor_RMROLE_1_1] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_131]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2021-11-26 18:20:04.206  INFO 22760 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : channel inactive: [id: 0x284ebcbc, L:/172.16.19.240:3880 ! R:/192.144.237.180:8091]
2021-11-26 18:20:04.206  INFO 22760 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : channel valid false,channel:[id: 0x284ebcbc, L:/172.16.19.240:3880 ! R:/192.144.237.180:8091]
2021-11-26 18:20:04.206  INFO 22760 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x284ebcbc, L:/172.16.19.240:3880 ! R:/192.144.237.180:8091]
2021-11-26 18:20:04.206  INFO 22760 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x284ebcbc, L:/172.16.19.240:3880 ! R:/192.144.237.180:8091]) will closed
2021-11-26 18:20:04.206  INFO 22760 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x284ebcbc, L:/172.16.19.240:3880 ! R:/192.144.237.180:8091]) will closed
2021-11-26 18:20:14.013  INFO 22760 --- [eoutChecker_1_1] i.s.c.r.netty.NettyClientChannelManager  : will connect to 192.144.237.180:8091
2021-11-26 18:20:14.013  INFO 22760 --- [eoutChecker_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : channel valid false,channel:[id: 0x49fd0840, L:/172.16.19.240:3879 ! R:/192.144.237.180:8091]
2021-11-26 18:20:14.013  INFO 22760 --- [eoutChecker_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x49fd0840, L:/172.16.19.240:3879 ! R:/192.144.237.180:8091]
2021-11-26 18:20:14.014  INFO 22760 --- [eoutChecker_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:TMROLE,address:192.144.237.180:8091,msg:< RegisterTMRequest{applicationId='service-one', transactionServiceGroup='my_test_tx_group'} >
2021-11-26 18:20:14.103  INFO 22760 --- [eoutChecker_1_1] i.s.c.rpc.netty.TmNettyRemotingClient    : register TM success. client version:1.4.2, server version:1.4.2,channel:[id: 0xa8639c8a, L:/172.16.19.240:3917 - R:/192.144.237.180:8091]
2021-11-26 18:20:14.103  INFO 22760 --- [eoutChecker_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : register success, cost 38 ms, version:1.4.2,role:TMROLE,channel:[id: 0xa8639c8a, L:/172.16.19.240:3917 - R:/192.144.237.180:8091]
2021-11-26 18:20:14.106  INFO 22760 --- [eoutChecker_2_1] i.s.c.r.netty.NettyClientChannelManager  : will connect to 192.144.237.180:8091
2021-11-26 18:20:14.106  INFO 22760 --- [eoutChecker_2_1] i.s.c.rpc.netty.RmNettyRemotingClient    : RM will register :jdbc:mysql://192.144.237.180:3306/zt_shard_one
2021-11-26 18:20:14.106  INFO 22760 --- [eoutChecker_2_1] i.s.core.rpc.netty.NettyPoolableFactory  : channel valid false,channel:[id: 0x284ebcbc, L:/172.16.19.240:3880 ! R:/192.144.237.180:8091]
2021-11-26 18:20:14.106  INFO 22760 --- [eoutChecker_2_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x284ebcbc, L:/172.16.19.240:3880 ! R:/192.144.237.180:8091]
2021-11-26 18:20:14.107  INFO 22760 --- [eoutChecker_2_1] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:RMROLE,address:192.144.237.180:8091,msg:< RegisterRMRequest{resourceIds='jdbc:mysql://192.144.237.180:3306/zt_shard_one', applicationId='service-one', transactionServiceGroup='my_test_tx_group'} >
2021-11-26 18:20:14.244  INFO 22760 --- [eoutChecker_2_1] i.s.c.rpc.netty.RmNettyRemotingClient    : register RM success. client version:1.4.2, server version:1.4.2,channel:[id: 0xac9795f4, L:/172.16.19.240:3918 - R:/192.144.237.180:8091]
2021-11-26 18:20:14.245  INFO 22760 --- [eoutChecker_2_1] i.s.core.rpc.netty.NettyPoolableFactory  : register success, cost 109 ms, version:1.4.2,role:RMROLE,channel:[id: 0xac9795f4, L:/172.16.19.240:3918 - R:/192.144.237.180:8091]
2021-11-26 18:21:04.147 ERROR 22760 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : 0318

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_131]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2021-11-26 18:21:04.147  INFO 22760 --- [ctor_TMROLE_1_1] i.s.c.r.netty.NettyClientChannelManager  : return to pool, rm channel:[id: 0xa8639c8a, L:/172.16.19.240:3917 - R:/192.144.237.180:8091]
2021-11-26 18:21:04.147  INFO 22760 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : remove exception rm channel:[id: 0xa8639c8a, L:/172.16.19.240:3917 - R:/192.144.237.180:8091]
2021-11-26 18:21:04.147  WARN 22760 --- [ctor_TMROLE_1_1] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_131]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2021-11-26 18:21:04.148  INFO 22760 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : channel inactive: [id: 0xa8639c8a, L:/172.16.19.240:3917 ! R:/192.144.237.180:8091]
2021-11-26 18:21:04.148  INFO 22760 --- [ctor_TMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : channel valid false,channel:[id: 0xa8639c8a, L:/172.16.19.240:3917 ! R:/192.144.237.180:8091]
2021-11-26 18:21:04.148  INFO 22760 --- [ctor_TMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0xa8639c8a, L:/172.16.19.240:3917 ! R:/192.144.237.180:8091]
2021-11-26 18:21:04.148  INFO 22760 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0xa8639c8a, L:/172.16.19.240:3917 ! R:/192.144.237.180:8091]) will closed
2021-11-26 18:21:04.148  INFO 22760 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0xa8639c8a, L:/172.16.19.240:3917 ! R:/192.144.237.180:8091]) will closed
2021-11-26 18:21:04.209 ERROR 22760 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : 0318

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_131]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2021-11-26 18:21:04.210  INFO 22760 --- [ctor_RMROLE_1_1] i.s.c.r.netty.NettyClientChannelManager  : return to pool, rm channel:[id: 0xac9795f4, L:/172.16.19.240:3918 - R:/192.144.237.180:8091]
2021-11-26 18:21:04.210  INFO 22760 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : remove exception rm channel:[id: 0xac9795f4, L:/172.16.19.240:3918 - R:/192.144.237.180:8091]
2021-11-26 18:21:04.210  WARN 22760 --- [ctor_RMROLE_1_1] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_131]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]`
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.4.2
- OS : centos7.6
- Others:

**Comment by a364176773** [comment]
ping 你的seata服务器 延迟是多少?

**Comment by 303470934** [comment]
> ping 你的seata服务器 延迟是多少?

ping 了5次，最大25ms。
目前是重启Linux，运行seata server，项目client也仅仅启动，并没有进行服务调用。仅仅是启动服务，未进行seata使用，就不停报错了。

**Comment by a364176773** [comment]
> > ping 你的seata服务器 延迟是多少?
> 
> ping 了5次，最大25ms。 目前是重启Linux，运行seata server，项目client也仅仅启动，并没有进行服务调用。仅仅是启动服务，未进行seata使用，就不停报错了。

直接将你的应用部署到seata-server所在服务器试试，先判断下是否网络因素

**Comment by 303470934** [comment]
> > > ping 你的seata服务器 延迟是多少?
> > 
> > 
> > ping 了5次，最大25ms。 目前是重启Linux，运行seata server，项目client也仅仅启动，并没有进行服务调用。仅仅是启动服务，未进行seata使用，就不停报错了。
> 
> 直接将你的应用部署到seata-server所在服务器试试，先判断下是否网络因素

今天什么都没动，试了下，又没有这个问题了。建议优化下这问题，因为除了seata的neety连接一直报超时，其他服务都非常正常，没有出现这个情况。
期待您这边的回复，如果两天内没回复，我就关闭这个问题了。

**Comment by a364176773** [comment]
> > > > ping 你的seata服务器 延迟是多少?
> > > 
> > > 
> > > ping 了5次，最大25ms。 目前是重启Linux，运行seata server，项目client也仅仅启动，并没有进行服务调用。仅仅是启动服务，未进行seata使用，就不停报错了。
> > 
> > 
> > 直接将你的应用部署到seata-server所在服务器试试，先判断下是否网络因素
> 
> 今天什么都没动，试了下，又没有这个问题了。建议优化下这问题，因为除了seata的neety连接一直报超时，其他服务都非常正常，没有出现这个情况。 期待您这边的回复，如果两天内没回复，我就关闭这个问题了。

你这个是个例问题，没有提供有价值的信息，初步判断应该很网络因素有关

**Comment by 303470934** [comment]
> > > > > ping 你的seata服务器 延迟是多少?
> > > > 
> > > > 
> > > > ping 了5次，最大25ms。 目前是重启Linux，运行seata server，项目client也仅仅启动，并没有进行服务调用。仅仅是启动服务，未进行seata使用，就不停报错了。
> > > 
> > > 
> > > 直接将你的应用部署到seata-server所在服务器试试，先判断下是否网络因素
> > 
> > 
> > 今天什么都没动，试了下，又没有这个问题了。建议优化下这问题，因为除了seata的neety连接一直报超时，其他服务都非常正常，没有出现这个情况。 期待您这边的回复，如果两天内没回复，我就关闭这个问题了。
> 
> 你这个是个例问题，没有提供有价值的信息，初步判断应该跟网络因素有关

问题先关闭了。我会持续跟踪。后续如果有其他发现，我会同步到这边的。
