### ISSUE TITLE
Seata接入Redis哨兵集群失败

### ISSUE THREAD

**Issue by zzhangzd** [seata/seata#4161]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Seata1.4.2版本，接入Redis哨兵集群的时候，假如哨兵节点配置密码的话，jedis客户端接入失败，报权限认证失败的错误。jedis客户端不支持sentinel节点设置密码,JedisSentinelPool 类中，74行 sentinelPassword 项默认为null导致的。
假如将客户端改为spring-boot-starter-data-redis， 2.3.4.RELEASE版本以上可配置sentinelPassword

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
client端没有使用redis，tc端的redis用的Jedis，跟spring-boot-starter-data-redis无关，如果你是client端连不上redissentinel，那么跟seata是无关的

**Comment by zzhangzd** [comment]
是我上面的说明写的有点偏差，seata1.4.2版本里面用的是jedis，服务端配置redis哨兵模式的时候，假如哨兵节点设置了密码，seata服务端是连接不是redis的
14:04:47.094  WARN --- [                     main] redis.clients.jedis.JedisSentinelPool    : Cannot get master address from sentinel running @ *.*.*.*:26379. Reason: redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.. Trying next one.
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: All sentinels down, cannot determine where is mymaster master is running...
	at redis.clients.jedis.JedisSentinelPool.initSentinels(JedisSentinelPool.java:206)
	at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:112)
	at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:91)
	at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:85)
	at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:73)
	at io.seata.server.storage.redis.JedisPooledFactory.getJedisPoolInstance(JedisPooledFactory.java:106)
	at io.seata.server.storage.redis.JedisPooledFactory.getJedisInstance(JedisPooledFactory.java:134)
	at io.seata.server.storage.redis.store.RedisTransactionStoreManager.readSession(RedisTransactionStoreManager.java:348)
	at io.seata.server.storage.redis.store.RedisTransactionStoreManager.readSession(RedisTransactionStoreManager.java:389)
	at io.seata.server.storage.redis.session.RedisSessionManager.findGlobalSessions(RedisSessionManager.java:185)
	at io.seata.server.storage.redis.session.RedisSessionManager.allSessions(RedisSessionManager.java:175)
	at io.seata.server.session.SessionHolder.reload(SessionHolder.java:143)
	at io.seata.server.session.SessionHolder.init(SessionHolder.java:130)
	at io.seata.server.Server.main(Server.java:80)

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/144053234-aa33c8aa-9631-4164-9455-a694ecd24b0d.png)

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/144053651-d18f11f9-461d-4a06-a271-4d9a418edb73.png)

**Comment by zzhangzd** [comment]
![image](https://user-images.githubusercontent.com/16184461/144204338-65653b51-e6c1-4dce-a0ea-817039cbcc2f.png)

**Comment by zzhangzd** [comment]
@a364176773 您图中的密码是master和slave节点的密码，sentinel节点假如也设置了密码，jedis是不支持设置的，seata1.4.2里面是取不到sentinel节点的密码的
![image](https://user-images.githubusercontent.com/16184461/144205692-4db2584c-c278-4629-bc6e-cdd56aa21059.png)

**Comment by a364176773** [comment]
> @a364176773 您图中的密码是master和slave节点的密码，sentinel节点假如也设置了密码，jedis是不支持设置的，seata1.4.2里面是取不到sentinel节点的密码的 ![image](https://user-images.githubusercontent.com/16184461/144205692-4db2584c-c278-4629-bc6e-cdd56aa21059.png)

明白了，你愿意提个pr来支持它吗？

**Comment by zzhangzd** [comment]
欧克，很荣幸能参与进来

**Comment by a364176773** [comment]
@zzhangzd 还在吗？这个pr还没提呦

**Comment by PeppaO** [comment]
plz assign to me
