### ISSUE TITLE
K8s环境下使用SLB创建service后服务报警告

### ISSUE THREAD

**Issue by InGramViking** [seata/seata#4166]
- [-] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Kubernetes环境下使用LoadBalancer创建service后，pod报java.io.IOException: Connection reset by peer

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
SLF4J: A number (17) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
05:02:14.855  INFO --- [                     main] io.seata.server.Server                   : The server is running in container.
05:02:14.872  INFO --- [                     main] io.seata.config.FileConfiguration        : The file name of the operation is file:/root/seata-config/registry
05:02:14.875  INFO --- [                     main] io.seata.config.FileConfiguration        : The configuration file used is /root/seata-config/registry.conf
05:02:16.813  INFO --- [                     main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
05:02:17.040  INFO --- [                     main] i.s.core.rpc.netty.NettyServerBootstrap  : Server started, listen port: 8091
05:03:37.197  INFO --- [ettyServerNIOWorker_1_1_2] i.s.c.r.n.AbstractNettyRemotingServer    : channel exx:Connection reset by peer,channel:[id: 0xb191e08c, L:/172.22.0.169:8091 - R:/10.0.0.224:31708]
05:03:37.203  WARN --- [ettyServerNIOWorker_1_1_2] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
==>
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_212]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_212]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_212]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_212]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_212]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
<==
05:03:37.603  INFO --- [ettyServerNIOWorker_1_2_2] i.s.c.r.n.AbstractNettyRemotingServer    : 10.0.0.226:46876 to server channel inactive.
05:03:37.603  INFO --- [ettyServerNIOWorker_1_2_2] i.s.c.r.n.AbstractNettyRemotingServer    : remove unused channel:[id: 0xd203d3df, L:/172.22.0.169:8091 ! R:/10.0.0.226:46876]
05:03:39.788  INFO --- [ettyServerNIOWorker_1_1_2] i.s.c.r.n.AbstractNettyRemotingServer    : channel exx:Connection reset by peer,channel:[id: 0xb2abcd64, L:/172.22.0.169:8091 - R:/172.22.0.129:56632]
05:03:39.791  WARN --- [ettyServerNIOWorker_1_1_2] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
==>
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_212]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_212]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_212]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_212]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_212]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
<==
05:03:39.798  INFO --- [ettyServerNIOWorker_1_1_2] i.s.c.r.n.AbstractNettyRemotingServer    : 172.22.0.129:56632 to server channel inactive.
05:03:39.798  INFO --- [ettyServerNIOWorker_1_1_2] i.s.c.r.n.AbstractNettyRemotingServer    : remove unused channel:[id: 0xb2abcd64, L:/172.22.0.169:8091 ! R:/172.22.0.129:56632]
05:03:39.798  INFO --- [ettyServerNIOWorker_1_2_2] i.s.c.r.n.AbstractNettyRemotingServer    : channel exx:Connection reset by peer,channel:[id: 0xee0a43c4, L:/172.22.0.169:8091 - R:/10.0.0.226:52003]
05:03:39.799  WARN --- [ettyServerNIOWorker_1_2_2] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
==>
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_212]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_212]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_212]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_212]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_212]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
<==
```

### Ⅲ. Describe what you expected to happen
修复停止报警，业务服务可以通过SLB IP连接seata

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

config.txt配置：
```bash
# 分支1.4.2获取的
……
store.mode=db
……
service.default.grouplist=127.0.0.1:8091
……
```

seata-pod.yaml：
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-server
  namespace: seata
  labels:
    k8s-app: seata-server
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: seata-server
  template:
    metadata:
      labels:
        k8s-app: seata-server
    spec:
      containers:
        - name: seata-server
          image: docker.io/seataio/seata-server:1.4.2
          imagePullPolicy: IfNotPresent
          env:
            - name: SEATA_CONFIG_NAME
              value: file:/root/seata-config/registry
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          volumeMounts:
            - name: seata-config
              mountPath: /root/seata-config
      volumes:
        - name: seata-config
          configMap:
            name: seata-server-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
  namespace: seata
data:
  registry.conf: |
    registry {
        type = "nacos"
        nacos {
          application = "seata-server"
          serverAddr = "10.1.0.100:8848"
          username = "nacos"
          password = "password"
        }
    }
    config {
      type = "nacos"
      nacos {
        serverAddr = "10.1.0.100:8848"
        group = "SEATA_GROUP"
        username = "nacos"
        password = "password"
      }
    }
```
seata-slb-service.yaml
```yaml
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: 'lb-abcdefghijklmn'
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: 'true'
  name: seata-ha-server
  namespace: seata
  labels:
    k8s-app: seata-server
spec:
  type: LoadBalancer
  ports:
    - port: 8091
      protocol: TCP
      name: http
  selector:
    k8s-app: seata-server
```

### Ⅴ. Anything else we need to know?
pod的错误是在创建svc后出现，还没有业务代码连接
node ip：10.0.0.226，10.0.0.224，10.0.0.225
SLB IP：10.1.0.192

### Ⅵ. Environment:

- JDK version :  oracle jdk11
- Seata version:  1.4.2
- OS :  Kubernetes ACK 1.20.11-aliyun.1
- Others:

**Comment by slievrly** [comment]
Long connections through load balancing will lead to load imbalance. It is recommended to use the registry to expose services.

**Comment by wushangzi** [comment]
I hava the same problem like yours. now i hava sloved the issure. slb hava it own health check.it always send tcp package to your port which export. so you can close the health check in slb.
