### ISSUE TITLE
执行原生sql生成主键进行插入报错

### ISSUE THREAD

**Issue by hylyLLL** [seata/seata#4171]
我的sql是原生sql，然后我生成主键是表达式，seata判定成了自增主键生成，但实际上我数据库并没有配置自增，就导致抛出错误
Caused by: io.seata.common.exception.ShouldNeverHappenException: null
        at io.seata.rm.datasource.exec.mysql.MySQLInsertExecutor.getPkValuesByAuto(MySQLInsertExecutor.java:119)
        at io.seata.rm.datasource.exec.mysql.MySQLInsertExecutor.getPkValuesByColumn(MySQLInsertExecutor.java:159)
        at io.seata.rm.datasource.exec.mysql.MySQLInsertExecutor.getPkValues(MySQLInsertExecutor.java:78)
        at io.seata.rm.datasource.exec.BaseInsertExecutor.afterImage(BaseInsertExecutor.java:76)
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:103)
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:86)
        at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:113)
        at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:111)

**Comment by hylyLLL** [comment]
seat版本为1.4，是seata不支持这种写法吗

**Comment by a364176773** [comment]
sql发出来

**Comment by hylyLLL** [comment]
insert (id,name) values(replace(uuid(),'-',''),'张三')
类似这种的

**Comment by a364176773** [comment]
> insert (id,name) values(replace(uuid(),'-',''),'张三') 类似这种的

目前不支持

**Comment by hylyLLL** [comment]
> > insert (id,name) values(replace(uuid(),'-',''),'张三') 类似这种的
> 
> 目前不支持

好的，谢谢

**Comment by caohdgege** [comment]
你们可以使用Java生成的UUID，然后作为参数传进去，这样就支持了

**Comment by caohdgege** [comment]
> 请问可以通过仿照类似这个连接中的方式解决吗： [5f2a144#diff-497d2a229a93b0d6343cfef8a6c62f3573a9b270ac0ed0f5a9cf51c9055b6570](https://github.com/seata/seata/commit/5f2a144666070daeda0d2a3c222dc83e6eca79c4#diff-497d2a229a93b0d6343cfef8a6c62f3573a9b270ac0ed0f5a9cf51c9055b6570)

受MySQL的限制，你上面的那种MySQL生成的非auto_increment的主键都没办法获取，其实是没办法支持的，除非像上面说的，在代码生成UUID传进去。

**Comment by hylyLLL** [comment]
> 你们可以使用Java生成的UUID，然后作为参数传进去，这样就支持了

对的，这样使用是可以的，用原生sql生成id，是因为seata源码中判断了id的值
