### ISSUE TITLE
close() method in RedisRegistryServiceImpl was invoked twice during seata server shutting down

### ISSUE THREAD

**Issue by Pinocchio2018** [seata/seata#4172]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
**in version 1.5.0-SNAPSHOT**
I start seata server in IDEA. I meet `java.lang.IllegalStateException: Pool not open` error log  while shutting down seata server.
I use redis as registry center.

### Ⅱ. Describe what happened

 I see this error log
```java
16:58:17.615 ERROR --- [SpringContextShutdownHook] i.s.core.rpc.netty.NettyServerBootstrap  : shutdown execute error:Could not get a resource from the pool
==>
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:288)
	at io.seata.discovery.registry.redis.RedisRegistryServiceImpl.unregister(RedisRegistryServiceImpl.java:171)
	at io.seata.core.rpc.netty.NettyServerBootstrap.shutdown(NettyServerBootstrap.java:187)
	at io.seata.core.rpc.netty.AbstractNettyRemotingServer.destroy(AbstractNettyRemotingServer.java:126)
	at io.seata.server.ServerRunner.destroy(ServerRunner.java:75)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:199)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1092)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1085)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1030)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:170)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:949)
Caused by: java.lang.IllegalStateException: Pool not open
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.assertOpen(BaseGenericObjectPool.java:770)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:407)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 15 common frames omitted
<==


Process finished with exit code 130

```
I think we got this error because  the `RegistryService` was destroyed twice.

I try to find out when `RegistryService` was closed first time. I changed the code like this,
```java
public class RedisRegistryServiceImpl implements RegistryService<RedisListener> {

    @Override
    public void close() throws Exception {
        try {
            throw new RuntimeException("!!!");
        } catch (Exception e) {
            LOGGER.error("11", e);
        }
        jedisPool.destroy();
    }

}
```
now I know the first time the `RegistryService` was closed
```
16:58:13.599 ERROR --- [SpringContextShutdownHook] i.s.d.r.redis.RedisRegistryServiceImpl   : 11
==>
java.lang.RuntimeException: !!!
	at io.seata.discovery.registry.redis.RedisRegistryServiceImpl.close(RedisRegistryServiceImpl.java:238)
	at io.seata.core.rpc.netty.NettyServerBootstrap.shutdown(NettyServerBootstrap.java:188)
	at io.seata.core.rpc.netty.AbstractNettyRemotingServer.destroy(AbstractNettyRemotingServer.java:126)
	at io.seata.server.coordinator.DefaultCoordinator.destroy(DefaultCoordinator.java:463)
	at io.seata.server.ServerRunner.destroy(ServerRunner.java:75)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:199)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1092)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1085)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1030)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:170)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:949)
<==

```
Obviously,  `RegistryService` was closed from two place 
- first close from `DefaultCoordinator`
```java
public class DefaultCoordinator extends AbstractTCInboundHandler implements TransactionMessageHandler, Disposable {
    @Override
    public void destroy() {
        // 1. first shutdown timed task
        retryRollbacking.shutdown();
        retryCommitting.shutdown();
        asyncCommitting.shutdown();
        timeoutCheck.shutdown();
        try {
            retryRollbacking.awaitTermination(TIMED_TASK_SHUTDOWN_MAX_WAIT_MILLS, TimeUnit.MILLISECONDS);
            retryCommitting.awaitTermination(TIMED_TASK_SHUTDOWN_MAX_WAIT_MILLS, TimeUnit.MILLISECONDS);
            asyncCommitting.awaitTermination(TIMED_TASK_SHUTDOWN_MAX_WAIT_MILLS, TimeUnit.MILLISECONDS);
            timeoutCheck.awaitTermination(TIMED_TASK_SHUTDOWN_MAX_WAIT_MILLS, TimeUnit.MILLISECONDS);
        } catch (InterruptedException ignore) {

        }
        // 2. second close netty flow
        if (remotingServer instanceof NettyRemotingServer) {
            ((NettyRemotingServer) remotingServer).destroy();  // first close!!!
        }
        // 3. last destroy SessionHolder
        SessionHolder.destroy();
    }
}
```
- second close from `NettyServerBootstrap`
```java
public class NettyServerBootstrap implements RemotingBootstrap {

    @Override
    public void shutdown() {
        try {
            if (LOGGER.isDebugEnabled()) {
                LOGGER.debug("Shutting server down. ");
            }
            if (initialized.get()) {
                RegistryFactory.getInstance().unregister(new InetSocketAddress(XID.getIpAddress(), XID.getPort()));
                RegistryFactory.getInstance().close();  // second close here!!!
                //wait a few seconds for server transport
                TimeUnit.SECONDS.sleep(nettyServerConfig.getServerShutdownWaitTime());
            }

            this.eventLoopGroupBoss.shutdownGracefully();
            this.eventLoopGroupWorker.shutdownGracefully();
        } catch (Exception exx) {
            LOGGER.error("shutdown execute error:{}",exx.getMessage(),exx);
        }
    }
}
```

### Ⅲ. Describe what you expected to happen
we need to optimize `close()` method in `RedisRegistryServiceImpl`

force it do close only once.
1. shutdown threadPoolExecutor in it
2. do unregister
3. destroy JedisPool

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. use redis as registry center
2. stop server and check error log

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.5.0-SNAPSHOT
- OS :
- Others:

**Comment by Pinocchio2018** [comment]
assign to me

**Comment by Pinocchio2018** [comment]
I meet a problem. I want to make  `close()` method only do one  close  resource.
我遇到个问题，我准备把close改成下方这样，只做一次回收工作

```java
public class RedisRegistryServiceImpl implements RegistryService<RedisListener> {

    private final AtomicBoolean closed = new AtomicBoolean(false);

    @Override
    public void close() throws Exception {
        if (closed.compareAndSet(false, true)) {
            threadPoolExecutorForSubscribe.shutdown();
            threadPoolExecutorForUpdateMap.shutdown();
            RegistryHeartBeats.close();
            this.unregister(new InetSocketAddress(XID.getIpAddress(), XID.getPort()));
            jedisPool.destroy();
        }
    }

}
```
but, before the second close,`unregister()` is invoked. At this time jedispool is closed, so it 'll throw an exception
但是，在第二次回收之前，会调用一个`unregister()`，此时jedis pool已经关闭了，所以会抛出异常来。
```java
public class NettyServerBootstrap implements RemotingBootstrap {

    @Override
    public void shutdown() {
        try {
            if (LOGGER.isDebugEnabled()) {
                LOGGER.debug("Shutting server down. ");
            }
            if (initialized.get()) {
                RegistryFactory.getInstance().unregister(new InetSocketAddress(XID.getIpAddress(), XID.getPort()));
                RegistryFactory.getInstance().close();  // second close here!!!
                //wait a few seconds for server transport
                TimeUnit.SECONDS.sleep(nettyServerConfig.getServerShutdownWaitTime());
            }

            this.eventLoopGroupBoss.shutdownGracefully();
            this.eventLoopGroupWorker.shutdownGracefully();
        } catch (Exception exx) {
            LOGGER.error("shutdown execute error:{}",exx.getMessage(),exx);
        }
    }
}
```
error log.
异常日志
```
21:15:08.507 ERROR --- [SpringContextShutdownHook] i.s.core.rpc.netty.NettyServerBootstrap  : shutdown execute error:Could not get a resource from the pool
==>
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59) ~[jedis-3.3.0.jar:na]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:288) ~[jedis-3.3.0.jar:na]
	at io.seata.discovery.registry.redis.RedisRegistryServiceImpl.unregister(RedisRegistryServiceImpl.java:181) ~[classes/:na]
	at io.seata.core.rpc.netty.NettyServerBootstrap.shutdown(NettyServerBootstrap.java:187) ~[classes/:na]
	at io.seata.core.rpc.netty.AbstractNettyRemotingServer.destroy(AbstractNettyRemotingServer.java:126) [classes/:na]
	at io.seata.core.rpc.netty.NettyRemotingServer.destroy(NettyRemotingServer.java:126) [classes/:na]
	at io.seata.server.ServerRunner.destroy(ServerRunner.java:75) [classes/:na]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:199) [spring-beans-5.2.14.RELEASE.jar:5.2.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) [spring-beans-5.2.14.RELEASE.jar:5.2.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) [spring-beans-5.2.14.RELEASE.jar:5.2.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1092) [spring-beans-5.2.14.RELEASE.jar:5.2.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) [spring-beans-5.2.14.RELEASE.jar:5.2.14.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1085) [spring-beans-5.2.14.RELEASE.jar:5.2.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061) [spring-context-5.2.14.RELEASE.jar:5.2.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1030) [spring-context-5.2.14.RELEASE.jar:5.2.14.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:170) [spring-boot-2.3.10.RELEASE.jar:2.3.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:949) [spring-context-5.2.14.RELEASE.jar:5.2.14.RELEASE]
Caused by: java.lang.IllegalStateException: Pool not open
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.assertOpen(BaseGenericObjectPool.java:770) ~[commons-pool2-2.8.1.jar:2.8.1]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:407) ~[commons-pool2-2.8.1.jar:2.8.1]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354) ~[commons-pool2-2.8.1.jar:2.8.1]
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50) ~[jedis-3.3.0.jar:na]
	... 16 common frames omitted
<==
```
I need a advice.
怎么改比较好呢？
