### ISSUE TITLE
postgresql数据连接异常

### ISSUE THREAD

**Issue by hylyLLL** [seata/seata#4223]
seata版本为1.4
pg版本为14
驱动版本为42.2.5
账号密码都正常，pg的配置也没有做ip限制。

seata启动时报错

Exception in thread "main" io.seata.common.exception.DataAccessException: wait millis 5000, active 0, maxActive 20, creating 0, createErrorCount 22
        at io.seata.server.storage.db.store.LogStoreDataBaseDAO.queryGlobalTransactionDO(LogStoreDataBaseDAO.java:182)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.readSession(DataBaseTransactionStoreManager.java:182)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.readSession(DataBaseTransactionStoreManager.java:212)
        at io.seata.server.storage.db.session.DataBaseSessionManager.findGlobalSessions(DataBaseSessionManager.java:188)
        at io.seata.server.storage.db.session.DataBaseSessionManager.allSessions(DataBaseSessionManager.java:177)
        at io.seata.server.session.SessionHolder.reload(SessionHolder.java:136)
        at io.seata.server.session.SessionHolder.init(SessionHolder.java:123)
        at io.seata.server.Server.main(Server.java:84)
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 5000, active 0, maxActive 20, creating 0, createErrorCount 22
        at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1732)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1404)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1384)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:98)
        at io.seata.server.storage.db.store.LogStoreDataBaseDAO.queryGlobalTransactionDO(LogStoreDataBaseDAO.java:164)
        ... 7 more
Caused by: org.postgresql.util.PSQLException: 不支援 10 验证类型。请核对您已经组态 pg_hba.conf 文件包含客户端的IP位址或网路区段，以及驱动程序所支援的验证架构模式已被支援。
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:614)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
        at org.postgresql.Driver.makeConnection(Driver.java:450)
        at org.postgresql.Driver.connect(Driver.java:252)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1710)
        at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2774)

请问这是版本问题吗？

**Comment by GoodBoyCoder** [comment]
数据库连接问题，与Seata无关，建议检查一下数据库驱动版本或者pg_hba.conf的相关连接配置

**Comment by hylyLLL** [comment]
> 数据库连接问题，与Seata无关，建议检查一下数据库驱动版本或者pg_hba.conf的相关连接配置

pg_hba.conf的配置是所有都放行了的
![image](https://user-images.githubusercontent.com/46893979/147040900-9ca1c0c3-446f-4756-8f29-0816367f3fef.png)

**Comment by hylyLLL** [comment]
> 数据库连接问题，与Seata无关，建议检查一下数据库驱动版本或者pg_hba.conf的相关连接配置

问题找到了，由于运行的服务器是搭建的pve环境，容器搭建的有问题，导致ip错乱了
