### ISSUE TITLE
nacos密码含有特殊字符，在seata1.4.2的registry.conf中使用dataId = "seataServer.properties"提示unknow user

### ISSUE THREAD

**Issue by duhongx** [seata/seata#4224]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

+ 1、之前seata版本为1.3.0，不支持设置defaultGlobalTransactionTimeout，将seata升级到1.4.2，顺便把nacos也升级到2.0.3，在kuebrnetes中直接修改镜像版本来升级。
+ 2、之前seata的配置采用python脚本上传config.txt到nacos的SEATA_GROUP，seata中的registry.conf中nacos密码含有特殊字符无任何问题。

### Ⅱ. Describe what happened

 + 3、将seata升级到1.4.2之后，看官网介绍支持将seata里的文件写入一个properties中，于是在registry.conf中添加dataId = "seataServer.properties"，然后把config.txt贴到seataServer.properties中，重启seata容器，seata报错提示unknow user。

```
03:10:04.390 ERROR --- [                     main] i.seata.config.nacos.NacosConfiguration  : <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Dec 22 11:10:04 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
03:10:04.470  INFO --- [                     main] i.s.core.rpc.netty.NettyServerBootstrap  : Server started, listen port: 8091
03:10:04.624 ERROR --- [                     main] io.seata.server.Server                   : nettyServer init error:ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance after all servers([nacos.default.svc:8848]) tried: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Dec 22 11:10:04 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
==>
java.lang.RuntimeException: ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance after all servers([nacos.default.svc:8848]) tried: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Dec 22 11:10:04 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
	at io.seata.core.rpc.netty.NettyServerBootstrap.start(NettyServerBootstrap.java:157) ~[seata-core-1.4.2.jar:na]
	at io.seata.core.rpc.netty.AbstractNettyRemotingServer.init(AbstractNettyRemotingServer.java:55) ~[seata-core-1.4.2.jar:na]
	at io.seata.core.rpc.netty.NettyRemotingServer.init(NettyRemotingServer.java:52) ~[seata-core-1.4.2.jar:na]
	at io.seata.server.Server.main(Server.java:98) ~[classes/:na]
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([nacos.default.svc:8848]) tried: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Dec 22 11:10:04 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:552) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:239) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:200) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:185) ~[nacos-client-1.3.3.jar:na]
	at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:86) ~[seata-discovery-nacos-1.4.2.jar:na]
	at io.seata.core.rpc.netty.NettyServerBootstrap.start(NettyServerBootstrap.java:153) ~[seata-core-1.4.2.jar:na]
	... 3 common frames omitted
<==

```

+4 、猜测是nacos密码含有特殊字符，seata拼接nacos 用户名密码+seataServer.properties的时候异常，导致seata提示unknow user。将nacos密码改成nacos后重启seata容器后正常，改成不含特殊字符后测试也正常。

### Ⅲ. Describe what you expected to happen

如上

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

如上

### Ⅴ. Anything else we need to know?

后续seata采用dataId = "seataServer.properties"这种方式是否支持nacos密码含有特殊字符？

### Ⅵ. Environment:

kubernetes: 1.16.14
nacos:  nacos/nacos-server:2.0.3
seata: docker.io/seataio/seata-server:1.4.2

**Comment by a364176773** [comment]
1.5会修复该问题，1.4.2可以尝试密码转义，或者改密码先，也可以尝试直接把1.4.2文件夹lib里的nacos的jar依赖换成1.4.2的nacos依赖试试

**Comment by kamyam** [comment]
> 

目前是不支持yaml吗
