### ISSUE TITLE
Shardingshpere5.0.1+seata 1.4.2启动失败

### ISSUE THREAD

**Issue by GreekPanda** [seata/seata#4248]
### Ⅰ. Issue Description
Shardingshpere5.0.1+seata 1.4.2启动失败

### Ⅱ. Describe what happened
[WARN ] 2021-12-30 17:22:23.939 [main] i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader - Load [io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider] class fail. org/springframework/beans/factory/NoSuchBeanDefinitionException
Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException
        at io.seata.config.nacos.NacosConfigurationProvider.provide(NacosConfigurationProvider.java:29)
        at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:131)
        at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:94)
        at io.seata.core.rpc.netty.NettyBaseConfig.<clinit>(NettyBaseConfig.java:54)
        at io.seata.core.rpc.netty.TmNettyRemotingClient.getInstance(TmNettyRemotingClient.java:113)
        at io.seata.core.rpc.netty.TmNettyRemotingClient.getInstance(TmNettyRemotingClient.java:96)
        at io.seata.tm.TMClient.init(TMClient.java:46)
        at io.seata.tm.TMClient.init(TMClient.java:34)
        at org.apache.shardingsphere.transaction.base.seata.at.SeataATShardingSphereTransactionManager.initSeataRPCClient(SeataATShardingSphereTransactionManager.java:78)
        at org.apache.shardingsphere.transaction.base.seata.at.SeataATShardingSphereTransactionManager.init(SeataATShardingSphereTransactionManager.java:71)
        at org.apache.shardingsphere.transaction.ShardingSphereTransactionManagerEngine.lambda$init$0(ShardingSphereTransactionManagerEngine.java:71)
        at java.util.Map.forEach(Map.java:630)
        at org.apache.shardingsphere.transaction.ShardingSphereTransactionManagerEngine.init(ShardingSphereTransactionManagerEngine.java:71)
        at org.apache.shardingsphere.mode.manager.memory.MemoryContextManagerBuilder.createTransactionContexts(MemoryContextManagerBuilder.java:68)
        at org.apache.shardingsphere.mode.manager.memory.MemoryContextManagerBuilder.build(MemoryContextManagerBuilder.java:56)
        at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.initContext(BootstrapInitializer.java:79)
        at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:70)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:47)
Caused by: java.lang.ClassNotFoundException: com.alibaba.nacos.api.exception.NacosException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 18 more

### Ⅲ. Describe what you expected to happen
可以正常启动

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.  在shardingshpere-proxy 5.0.1中增加了seata-all-1.4.2.,ar
2.  启动shardingshpere-proxy失败

### Ⅵ. Environment:

- JDK version : 1.8.0_271
- Seata version:  1.4.2
- OS : Centos  CentOS Linux release 7.5.1804
- Others: Shardingshpere-proxy 5.0.1

**Comment by a364176773** [comment]
java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException

**Comment by GreekPanda** [comment]
> java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException

Hi, @a364176773 咋弄？我已经把nacos相关的包都引入了，还是报错。

**Comment by a364176773** [comment]
> > java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException
> 
> Hi, @a364176773 咋弄？我已经把nacos相关的包都引入了，还是报错。

检查依赖冲突

**Comment by GreekPanda** [comment]
> > > java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException
> > 
> > 
> > Hi, @a364176773 咋弄？我已经把nacos相关的包都引入了，还是报错。
> 
> 检查依赖冲突

具体怎么搞？两个都是开源的东西，难不成搞源代码debug?

**Comment by a364176773** [comment]
> > > > java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException
> > > 
> > > 
> > > Hi, @a364176773 咋弄？我已经把nacos相关的包都引入了，还是报错。
> > 
> > 
> > 检查依赖冲突
> 
> 具体怎么搞？两个都是开源的东西，难不成搞源代码debug?

NoClassDefFoundError 不是开源社区引起的,这属于需要你来debug和依赖检查,难道是开源的东西就不需要debug了?

**Comment by GreekPanda** [comment]
> > > > > java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException
> > > > 
> > > > 
> > > > Hi, @a364176773 咋弄？我已经把nacos相关的包都引入了，还是报错。
> > > 
> > > 
> > > 检查依赖冲突
> > 
> > 
> > 具体怎么搞？两个都是开源的东西，难不成搞源代码debug?
> 
> NoClassDefFoundError 不是开源社区引起的,这属于需要你来debug和依赖检查,难道是开源的东西就不需要debug了?

你这很不友好啊，就是因为没有思路，按你说的已经排查了依赖了，还是没有找出问题。算了，不扯了，关贴。
