### ISSUE TITLE
回滚的时候Geometry类型无法反序列化

### ISSUE THREAD

**Issue by yiyutao** [seata/seata#4249]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
无法反序列化com.mysql.cj.jdbc.Blob

### Ⅱ. Describe what happened
集成了shardingsphere-jdbc
字段类型为Geometry类型，回滚的时候报错
com.mysql.cj.jdbc.Blob没有无参构造，反序列化不了

- JDK version :1.8
- Seata version:  1.5.0
- OS :
- Others:

**Comment by a364176773** [comment]
请提供异常的堆栈信息,以便排查

**Comment by yiyutao** [comment]
```shell
10:42:13.087 [rpcDispatch_RMROLE_1_7_24] ERROR i.s.r.d.u.p.JacksonUndoLogParser - [decode,195] - json decode exception, Cannot construct instance of `com.mysql.cj.jdbc.Blob` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"@class":"io.seata.rm.datasource.undo.BranchUndoLog","xid":"192.168.0.82:8091:18220712402352135","branchId":18220712402352159,"sqlUndoLogs":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.undo.SQLUndoLog","sqlType":"INSERT","tableName":"distribution_push_log","beforeImage":{"@class":"io.seata.rm.datasource.sql.struct.TableRecords$EmptyTableRecords","tableName":"distribution_push_log","rows":["java.util.ArrayList",[]]},"afterImage":{"@class":"io.seata.rm.datasource.sql.struct.TableReco"[truncated 2903 bytes]; line: 1, column: 2419] (through reference chain: io.seata.rm.datasource.undo.BranchUndoLog["sqlUndoLogs"]->java.util.ArrayList[0]->io.seata.rm.datasource.undo.SQLUndoLog["afterImage"]->io.seata.rm.datasource.sql.struct.TableRecords["rows"]->java.util.ArrayList[0]->io.seata.rm.datasource.sql.struct.Row["fields"]->java.util.ArrayList[11]->io.seata.rm.datasource.sql.struct.Field["value"])
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.mysql.cj.jdbc.Blob` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"@class":"io.seata.rm.datasource.undo.BranchUndoLog","xid":"192.168.0.82:8091:18220712402352135","branchId":18220712402352159,"sqlUndoLogs":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.undo.SQLUndoLog","sqlType":"INSERT","tableName":"distribution_push_log","beforeImage":{"@class":"io.seata.rm.datasource.sql.struct.TableRecords$EmptyTableRecords","tableName":"distribution_push_log","rows":["java.util.ArrayList",[]]},"afterImage":{"@class":"io.seata.rm.datasource.sql.struct.TableReco"[truncated 2903 bytes]; line: 1, column: 2419] (through reference chain: io.seata.rm.datasource.undo.BranchUndoLog["sqlUndoLogs"]->java.util.ArrayList[0]->io.seata.rm.datasource.undo.SQLUndoLog["afterImage"]->io.seata.rm.datasource.sql.struct.TableRecords["rows"]->java.util.ArrayList[0]->io.seata.rm.datasource.sql.struct.Row["fields"]->java.util.ArrayList[11]->io.seata.rm.datasource.sql.struct.Field["value"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1615)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1077)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1332)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:199)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:132)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:710)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:132)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1209)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:292)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserializeWithType(CollectionDeserializer.java:318)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:132)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1209)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:292)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserializeWithType(CollectionDeserializer.java:318)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:132)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1209)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:132)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1209)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:292)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserializeWithType(CollectionDeserializer.java:318)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:132)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1209)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3529)
	at io.seata.rm.datasource.undo.parser.JacksonUndoLogParser.decode(JacksonUndoLogParser.java:191)
	at io.seata.rm.datasource.undo.AbstractUndoLogManager.undo(AbstractUndoLogManager.java:297)
	at io.seata.rm.datasource.DataSourceManager.branchRollback(DataSourceManager.java:122)
	at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:125)
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:67)
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:63)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:124)
	at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:63)
	at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:68)
	at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35)
	at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150)
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.handleBranchRollback(RmBranchRollbackProcessor.java:63)
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.process(RmBranchRollbackProcessor.java:58)
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:281)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by a364176773** [comment]
暂时替换成kryo,fst之类的序列化方式(记得删除对应的undolog,重新来过)是否可以解决?

**Comment by a364176773** [comment]
1.4.2下,可以尝试用seata的plugin去扩展jackson的相关类型序列化适配,或者改用kryo,fst等测试下是否可以先解决

**Comment by GoodBoyCoder** [comment]
Please assign it to me.

**Comment by yiyutao** [comment]
替换成kyro不行，报错
```shell
11:20:14.135 [PollingServerListUpdater-1] INFO  c.n.c.ChainedDynamicProperty - [checkAndFlip,115] - Flipping property: hnhg-cchs-system.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
11:20:14.187 [rpcDispatch_RMROLE_1_10_24] INFO  i.s.c.r.p.c.RmBranchRollbackProcessor - [process,56] - rm handle branch rollback process:xid=192.168.0.82:8091:18220712403007373,branchId=18220712403007396,branchType=AT,resourceId=jdbc:mysql://192.168.0.75:3306/order-center,applicationData=null
11:20:14.188 [rpcDispatch_RMROLE_1_10_24] INFO  i.s.r.AbstractRMHandler - [doBranchRollback,123] - Branch Rollbacking: 192.168.0.82:8091:18220712403007373 18220712403007396 jdbc:mysql://192.168.0.75:3306/order-center
11:20:14.200 [rpcDispatch_RMROLE_1_10_24] INFO  i.s.r.d.DataSourceManager - [info,43] - branchRollback failed. branchType:[AT], xid:[192.168.0.82:8091:18220712403007373], branchId:[18220712403007396], resourceId:[jdbc:mysql://192.168.0.75:3306/order-center], applicationData:[null]. reason:[Branch session rollback failed and try again later xid = 192.168.0.82:8091:18220712403007373 branchId = 18220712403007396 Class cannot be created (missing no-arg constructor): com.mysql.cj.jdbc.Blob
Serialization trace:
value (io.seata.rm.datasource.sql.struct.Field)
fields (io.seata.rm.datasource.sql.struct.Row)
rows (io.seata.rm.datasource.sql.struct.TableRecords)
afterImage (io.seata.rm.datasource.undo.SQLUndoLog)
sqlUndoLogs (io.seata.rm.datasource.undo.BranchUndoLog)]
```
替换成fastjson也不行，
```shell
11:42:41.704 [rpcDispatch_RMROLE_1_19_24] INFO  i.s.r.d.u.AbstractUndoExecutor - [dataValidationAndGoOn,265] - Field not equals, name customer_location, old value com.mysql.cj.jdbc.Blob@771f67a0, new value com.mysql.cj.jdbc.Blob@7c5a2ead
```
fastjson反序列后，反序列化的Blob对象里面的binaryData是null

**Comment by a364176773** [comment]
> 替换成kyro不行，报错
> 
> ```shell
> 11:20:14.135 [PollingServerListUpdater-1] INFO  c.n.c.ChainedDynamicProperty - [checkAndFlip,115] - Flipping property: hnhg-cchs-system.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
> 11:20:14.187 [rpcDispatch_RMROLE_1_10_24] INFO  i.s.c.r.p.c.RmBranchRollbackProcessor - [process,56] - rm handle branch rollback process:xid=192.168.0.82:8091:18220712403007373,branchId=18220712403007396,branchType=AT,resourceId=jdbc:mysql://192.168.0.75:3306/order-center,applicationData=null
> 11:20:14.188 [rpcDispatch_RMROLE_1_10_24] INFO  i.s.r.AbstractRMHandler - [doBranchRollback,123] - Branch Rollbacking: 192.168.0.82:8091:18220712403007373 18220712403007396 jdbc:mysql://192.168.0.75:3306/order-center
> 11:20:14.200 [rpcDispatch_RMROLE_1_10_24] INFO  i.s.r.d.DataSourceManager - [info,43] - branchRollback failed. branchType:[AT], xid:[192.168.0.82:8091:18220712403007373], branchId:[18220712403007396], resourceId:[jdbc:mysql://192.168.0.75:3306/order-center], applicationData:[null]. reason:[Branch session rollback failed and try again later xid = 192.168.0.82:8091:18220712403007373 branchId = 18220712403007396 Class cannot be created (missing no-arg constructor): com.mysql.cj.jdbc.Blob
> Serialization trace:
> value (io.seata.rm.datasource.sql.struct.Field)
> fields (io.seata.rm.datasource.sql.struct.Row)
> rows (io.seata.rm.datasource.sql.struct.TableRecords)
> afterImage (io.seata.rm.datasource.undo.SQLUndoLog)
> sqlUndoLogs (io.seata.rm.datasource.undo.BranchUndoLog)]
> ```
> 
> 替换成fastjson也不行，
> 
> ```shell
> 11:42:41.704 [rpcDispatch_RMROLE_1_19_24] INFO  i.s.r.d.u.AbstractUndoExecutor - [dataValidationAndGoOn,265] - Field not equals, name customer_location, old value com.mysql.cj.jdbc.Blob@771f67a0, new value com.mysql.cj.jdbc.Blob@7c5a2ead
> ```
> 
> fastjson反序列后，反序列化的Blob对象里面的binaryData是null

看来是要适配一下，你可以参考目前的plugin的做法自己扩展一下，或者直接继承jackson的实现自己spi再加一种序列化的处理，
你上面那个kryo是不是没生效，看着不太像是kryo

**Comment by yiyutao** [comment]
> 
> 看来是要适配一下，你可以参考目前的plugin的做法自己扩展一下，或者直接继承jackson的实现自己spi再加一种序列化的处理， 你上面那个kryo是不是没生效，看着不太像是kryo

有生效，通过配置的方式指定没有生效，直接改的源码，DefaultValues类中DEFAULT_TRANSACTION_UNDO_LOG_SERIALIZATION常量。嗯，周末试下扩展下。

**Comment by GoodBoyCoder** [comment]
如果可以，请提供一下shardingsphere-jdbc的版本以供验证

**Comment by a364176773** [comment]
> > 看来是要适配一下，你可以参考目前的plugin的做法自己扩展一下，或者直接继承jackson的实现自己spi再加一种序列化的处理， 你上面那个kryo是不是没生效，看着不太像是kryo
> 
> 有生效，通过配置的方式指定没有生效，直接改的源码，DefaultValues类中DEFAULT_TRANSACTION_UNDO_LOG_SERIALIZATION常量。嗯，周末试下扩展下。

这个要根据你给seata使用的配置中心是什么，配置到对应的配置中心去才会生效

**Comment by yiyutao** [comment]
> 如果可以，请提供一下shardingsphere-jdbc的版本以供验证

1.5.0

**Comment by yiyutao** [comment]
> > > 如果可以，请提供一下shardingsphere-jdbc的版本以供验证
> > 
> > 
> > shardingsphere-jdbc：5.0.0 seata-all：1.5.0
> 
> PR#4278 可以尝试一下该PR修改是否能够解决（记得删除原有undolog）

可以正常回滚了。感谢
