### ISSUE TITLE
外键关联自身表其他字段，批量插入数据的情况下，回滚失败。

### ISSUE THREAD

**Issue by josh1707** [seata/seata#4272]
### Ⅰ. Issue Description

如果表存在外键关联自身，例如 parent_id 外键关联自己 id，批量插入的情况下，发生回滚时，会回滚失败。

### Ⅱ. Describe what happened

- 回滚失败：

```
2022-01-07 16:30:28.967 []  INFO 17052 [rpcDispatch_RMROLE_1_1_32] io.seata.rm.datasource.undo.AbstractUndoLogManager xid 10.10.10.63:8091:810833176844463780 branch 810833176844463795, undo_log inserted, retry rollback

java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`testdb`.`tree_table`, CONSTRAINT `pk_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `tree_table` (`id`))
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1350)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255)
	at io.seata.rm.datasource.undo.AbstractUndoExecutor.executeOn(AbstractUndoExecutor.java:135)
	at io.seata.rm.datasource.undo.AbstractUndoLogManager.undo(AbstractUndoLogManager.java:312)
	at io.seata.rm.datasource.DataSourceManager.branchRollback(DataSourceManager.java:122)
	at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:125)
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:67)
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:63)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:124)
	at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:63)
	at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:68)
	at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35)
	at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150)
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.handleBranchRollback(RmBranchRollbackProcessor.java:63)
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.process(RmBranchRollbackProcessor.java:58)
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

- afterImage row 有两条记录

![image](https://user-images.githubusercontent.com/3355202/148517552-d9f759c9-f716-474e-9082-eff1c5a74417.png)

- 回滚时候，按照顺序回滚，则会违法外键约束报错。

![image](https://user-images.githubusercontent.com/3355202/148517915-ba5512c6-d87c-43ae-94b4-ca481caf8ce6.png)

回滚时，rows是否也应该倒叙执行

### Ⅲ. Describe what you expected to happen

希望可以正常回滚。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.  创建表，外键指向自己表中其他字段，例如parent_id 指向 id
create table if not exists tree_table
(
	id varchar(50) not null primary key ,
	name varchar(100) null,
	parent_id varchar(50) null,
	constraint table_table_id_uindex
		unique (id),
	constraint pk_parent_id
		foreign key (parent_id) references tree_table (id)
);
2. 程序批量插入两条数据，第二条外键指向第一条ID
insert into tree_table(id, name, parent_id)
        values ('a', 'a', null), ('b', 'b', 'a')

3. 触发分布式事务回滚。

### Ⅴ. Environment:

- JDK version : 1.8
- Seata version:  1.4.2，模式试用默认的 AT模式。

**Comment by a364176773** [comment]
暂不支持外键约束
