### ISSUE TITLE
seata-server不停报错打印日志导致磁盘占用100%

### ISSUE THREAD

**Issue by yiyutao** [seata/seata#4279]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
重启seata-server服务后，数据库undo_log日志表数据没有异步删除，seata-server不停打印错误日志。但是业务正常。
未重启前seata-server是正常的，undo_log日志表不会有老数据，都被异步删除。
重启前和重启后未改变客户端和服务端版本

### Ⅱ. Describe what happened

```
io.seata.common.exception.RedisException: EXECABORT Transaction discarded because of previous errors.
        at io.seata.server.storage.redis.store.RedisTransactionStoreManager.updateGlobalTransactionDO(RedisTransactionStoreManager.java:296) ~[classes/:na]
        at io.seata.server.storage.redis.store.RedisTransactionStoreManager.writeSession(RedisTransactionStoreManager.java:100) ~[classes/:na]
        at io.seata.server.storage.redis.session.RedisSessionManager.updateGlobalSessionStatus(RedisSessionManager.java:98) ~[classes/:na]
        at io.seata.server.session.AbstractSessionManager.onStatusChange(AbstractSessionManager.java:122) ~[classes/:na]
        at io.seata.server.session.GlobalSession.changeStatus(GlobalSession.java:191) ~[classes/:na]
        at io.seata.server.session.SessionHelper.endRollbacked(SessionHelper.java:122) ~[classes/:na]
        at io.seata.server.coordinator.DefaultCore.doGlobalRollback(DefaultCore.java:359) ~[classes/:na]
        at io.seata.server.coordinator.DefaultCoordinator.lambda$handleRetryRollbacking$2(DefaultCoordinator.java:301) [classes/:na]
        at io.seata.server.session.SessionHelper.forEach(SessionHelper.java:161) ~[classes/:na]
        at io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking(DefaultCoordinator.java:281) [classes/:na]
        at io.seata.server.coordinator.DefaultCoordinator.lambda$init$5(DefaultCoordinator.java:403) [classes/:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
Caused by: redis.clients.jedis.exceptions.JedisDataException: EXECABORT Transaction discarded because of previous errors.
        at redis.clients.jedis.Protocol.processError(Protocol.java:132) ~[jedis-3.2.0.jar:na]
        at redis.clients.jedis.Protocol.process(Protocol.java:166) ~[jedis-3.2.0.jar:na]
        at redis.clients.jedis.Protocol.read(Protocol.java:220) ~[jedis-3.2.0.jar:na]
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318) ~[jedis-3.2.0.jar:na]
        at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:280) ~[jedis-3.2.0.jar:na]
        at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:285) ~[jedis-3.2.0.jar:na]
        at redis.clients.jedis.Transaction.exec(Transaction.java:46) ~[jedis-3.2.0.jar:na]
        at io.seata.server.storage.redis.store.RedisTransactionStoreManager.updateGlobalTransactionDO(RedisTransactionStoreManager.java:266) ~[classes/:na]
        ... 18 common frames omitted
<==

2022-01-10 12:45:08.421 ERROR --- [            TxTimeoutCheck_1_1] io.seata.server.session.SessionHelper    : handle global session failed: 172.16.32.222:8091:18232923460293610
```

### Ⅵ. Environment:

- JDK version : 1.8
- Seata Client version:  1.5.0
- Seata Server version: 1.4.2(docker部署，集群方式，三台seata-server，store.mode=redis)

**Comment by caohdgege** [comment]
1. 请问可以提供一下 hgetall "172.16.32.222:8091:18232923460293610" 的结果吗？

**Comment by yiyutao** [comment]
> 1. 请问可以提供一下 hgetall "172.16.32.222:8091:18232923460293610" 的结果吗？
> 2. 请问方便提供一下Redis的版本？

返回结果：empty array
redis信息：
redis_version:5.2.0
redis_mode:cluster

**Comment by a364176773** [comment]
是否是多tc部署？

**Comment by yiyutao** [comment]
> 是否是多tc部署？

部署了三台seata-server。

**Comment by slievrly** [comment]
redis cluster？

**Comment by yiyutao** [comment]
> redis cluster？

腾讯云的redis cluster，支持所有命令

**Comment by yiyutao** [comment]
> > > redis cluster？
> > 
> > 
> > 腾讯云的redis cluster，支持所有命令
> 
> 不支持redis cluster,试着直接用主备的redis吧或者redis-sentinel

之前两个一直都可以，什么都没变动，只重启了一下seata-server，就一直报这个错。现在生成换成单机版的，可以了。

**Comment by yiyutao** [comment]
刚搭建了一套全新的redis和seata-server，redis用集群分3片，seata-server用1.4.2，还是会报错。应该是redis集群的原因。很好奇什么都没动，之前也是腾讯云redis集群，之前可以，突然就不行了。
