### ISSUE TITLE
seata-server startup failed

### ISSUE THREAD

**Issue by kaixinbaba** [seata/seata#4357]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
I `registry` and `config` use **zk** mode 
here is the `registry.conf`
```
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "zk"

  ...
  zk {
    cluster = "default"
    # serverAddr = "localhost:2181"
    serverAddr = "172.19.37.255:2181"
    sessionTimeout = 10000
    connectTimeout = 10000
    username = ""
    password = ""
  }
}
config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "zk"
  zk {
    # serverAddr = "localhost:2181"
    serverAddr = "172.19.37.74:2181"
    sessionTimeout = 10000
    connectTimeout = 10000
    username = ""
    password = ""
    nodePath = "/seata/seata.properties"
  }
   ...
}
```
I have tried `localhost` or `127.0.0.1` or `my network ip` for zk's `serverAddr`
Startup cmd is 
```bash
./bin/seata-server.sh -p 8091 -h 127.0.0.1 -m db
```

### Ⅱ. Describe what happened
Got exception log like this:
```
... other log
17:44:10.741  INFO --- [                     main] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=172.19.37.74:2181 sessionTimeout=10000 watcher=org.I0Itec.zkclient.ZkClient@3f56875e
17:44:10.755  INFO --- [                     main] org.I0Itec.zkclient.ZkClient             : Waiting for keeper state SyncConnected
17:44:10.759  INFO --- [Thread(172.19.37.74:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 172.19.37.74/<unresolved>:2181
17:44:10.778  WARN --- [Thread(172.19.37.74:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server 172.19.37.74/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
==>
java.nio.channels.UnresolvedAddressException: null
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1017)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
<==

17:44:11.888  INFO --- [Thread(172.19.37.74:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 172.19.37.74/<unresolved>:2181
17:44:11.888  WARN --- [Thread(172.19.37.74:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server 172.19.37.74/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
==>
java.nio.channels.UnresolvedAddressException: null
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1017)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
<==

17:44:12.996  INFO --- [Thread(172.19.37.74:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 172.19.37.74/<unresolved>:2181
17:44:12.997  WARN --- [Thread(172.19.37.74:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server 172.19.37.74/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
==>
java.nio.channels.UnresolvedAddressException: null
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1017)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
<==

17:44:14.106  INFO --- [Thread(172.19.37.74:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 172.19.37.74/<unresolved>:2181
17:44:14.107  WARN --- [Thread(172.19.37.74:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server 172.19.37.74/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
==>
java.nio.channels.UnresolvedAddressException: null
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1017)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
<==

17:44:15.216  INFO --- [Thread(172.19.37.74:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 172.19.37.74/<unresolved>:2181
17:44:15.217  WARN --- [Thread(172.19.37.74:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server 172.19.37.74/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
==>
java.nio.channels.UnresolvedAddressException: null
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1017)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
<==
```

### Ⅲ. Describe what you expected to happen
How to startup successful? Did I miss something?

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. download zk 3.4.14 version and startup
2. modify registry.conf to change mode as 'zk'
3. download seata-server-1.4.2 and use `./bin/seata-server.sh -p 8091 -h 127.0.0.1 -m db` to startup

### Ⅴ. Anything else we need to know?
I also use the springboot-dubbo-seata-zk project to play seata demo, in this project `AccountExampleApplication` and `OrderExampleApplication` and `StorageExampleApplication` startup successful!

### Ⅵ. Environment:

- JDK version : java version "1.8.0_301"
- Seata version:  seata-server-1.4.2
- OS : macOS Monterey 12.1 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
- Others: ZK version 3.4.14

---
I expect quietly for the good news～

**Comment by a364176773** [comment]
看着不像是jdk8 你用的是jdk11还是jdk17？
It doesn't look like JDK8 are you using JDK11 or JDK17?

**Comment by kaixinbaba** [comment]
认真查看启动脚本发现，启动脚本中会优先查看 `/usr/libexec/java_home` 执行文件是否存在，该执行文件在我的电脑上指向 openjdk17，修改启动脚本（我没有尝试卸载该 openjdk17）强制 `JAVACMD` 指向 jdk8 路径即可。
之后根据文档中的步骤，将相关配置提交至 zk，seata 启动成功。

虽然我的 demo 玩起来还有点问题，正在排查，这个 issue 就先关闭了
