### ISSUE TITLE
并发压测tcc模式时，seata服务端从数据库(TDSQL)报出一个数组越界的异常，详细描述见正文

### ISSUE THREAD

**Issue by 1929776951** [seata/seata#4361]
各位老师好
    在做seata的tcc模式的高并发压测时，seata服务端数据库操作时偶尔会报出一个数组越界的异常，详细信息如下
     1、目前发现并发高时出现频率很高，并发不高，但是长时间压测时会出现此问题，出现频率不高
            一组数据作为参考：tps350左右，seata服务端部署三台，1500万交易，出现10次左右
     2、seata版本1.4.2  jdk版本1.8
     3、使用的数据库信息和驱动版本为：
                 数据库版本： TDSql(8.0.22-v18-txsql-2.0.1-V2.0R690D002-20210111-1048)
                 数据库驱动:mysql-connector-java:8.0.25
     4、具体堆栈信息如下：
  io.seata.core.exception.TransactionException: branch register request failed. xid=xx.xx.xx.xx:xxx:8430967792927778161, msg=java.lang.ArrayIndexOutOfBoundsException: 12
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:187)
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:124)
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179)
	at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:473)
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:116)
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77)
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.seata.common.exception.DataAccessException: java.lang.ArrayIndexOutOfBoundsException: 12
	at io.seata.server.storage.db.store.LogStoreDataBaseDAO.queryGlobalTransactionDO(LogStoreDataBaseDAO.java:127)
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.readSession(DataBaseTransactionStoreManager.java:157)
	at io.seata.server.storage.db.session.DataBaseSessionManager.findGlobalSession(DataBaseSessionManager.java:162)
	at io.seata.server.session.SessionHolder.findGlobalSession(SessionHolder.java:319)
	at io.seata.server.coordinator.AbstractCore.assertGlobalSessionNotNull(AbstractCore.java:123)
	at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:76)
	at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:100)
	at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:199)
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184)
	... 12 common frames omitted
Caused by: java.sql.SQLException: java.lang.ArrayIndexOutOfBoundsException: 12
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:441)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at io.seata.server.storage.db.store.LogStoreDataBaseDAO.queryGlobalTransactionDO(LogStoreDataBaseDAO.java:120)
	... 20 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: 12
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:382)
	at com.mysql.cj.protocol.a.ColumnDefinitionReader.unpackField(ColumnDefinitionReader.java:99)
	at com.mysql.cj.protocol.a.ColumnDefinitionReader.read(ColumnDefinitionReader.java:77)
	at com.mysql.cj.protocol.a.ColumnDefinitionReader.read(ColumnDefinitionReader.java:40)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1575)
	at com.mysql.cj.protocol.a.BinaryResultsetReader.read(BinaryResultsetReader.java:70)
	at com.mysql.cj.protocol.a.BinaryResultsetReader.read(BinaryResultsetReader.java:50)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1588)
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1642)
	at com.mysql.cj.ServerPreparedQuery.readExecuteResult(ServerPreparedQuery.java:390)
	at com.mysql.cj.ServerPreparedQuery.serverExecute(ServerPreparedQuery.java:208)
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:635)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418)
	... 24 common frames omitted

**Comment by a364176773** [comment]
鉴于日志的异常抛出位于驱动层面，建议先于tdsql技术支持取得联系，判断是否驱动不兼容等问题导致，后续若解决该问题，欢迎留言此issue避免后续有同学踩坑

**Comment by 1929776951** [comment]
将seata服务端的tdsql驱动改成tdsql官方提供的驱动包后，不再出现这个错误。

**Comment by a364176773** [comment]
感谢反馈
