### ISSUE TITLE
AT模式下，批量插入batch insert时报错，ArrayIndexOutOfBoundsException 和 connection holder is null 

### ISSUE THREAD

**Issue by zhenglei01** [seata/seata#4405]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
不加分布式事务时可以执行，加上就报错

### Ⅱ. Describe what happened
客户端部分日志：
2022-02-25 15:26:09 [ERROR][druid.sql.Statement][statementLogError][152]-> {conn-10008, pstmt-20004} execute error.   INSERT INTO PDSS_UC_LABLE_INFO (E_LABLE_NUM,LABEL_F,LABEL_S,STATUS,SOURCE_UNIT,CREATE_TIME)  values(?,?,?,?,?,? ) 
java.lang.ArrayIndexOutOfBoundsException: 4001
	at oracle.jdbc.driver.T4CVarcharAccessor.unmarshalOneRow(T4CVarcharAccessor.java:312)
	at oracle.jdbc.driver.T4C8Oall.readRXD(T4C8Oall.java:696)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:340)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
	at oracle.jdbc.driver.OraclePreparedStatement.executeForRowsWithTimeout(OraclePreparedStatement.java:10143)
	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:10249)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:230)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2708)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeBatch(FilterAdapter.java:2496)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeBatch(FilterEventAdapter.java:279)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2706)
	at com.alibaba.druid.filter.FilterAdapter.statement_executeBatch(FilterAdapter.java:2496)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_executeBatch(FilterEventAdapter.java:279)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2706)
	at com.alibaba.druid.wall.WallFilter.statement_executeBatch(WallFilter.java:502)
	at com.alibaba.druid.filter.FilterChainImpl.statement_executeBatch(FilterChainImpl.java:2706)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.executeBatch(StatementProxyImpl.java:202)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeBatch(DruidPooledPreparedStatement.java:560)
	at io.seata.rm.datasource.StatementProxy.lambda$executeBatch$9(StatementProxy.java:129)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:93)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$0(AbstractDMLBaseExecutor.java:111)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:299)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:155)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:110)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:74)
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:115)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:113)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:51)
	at io.seata.rm.datasource.StatementProxy.executeBatch(StatementProxy.java:129)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$batchUpdate$2(JdbcTemplate.java:938)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:605)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:634)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:924)
	at org.springframework.jdbc.core.namedparam.NamedParameterBatchUpdateUtils.executeBatchUpdateWithNamedParameters(NamedParameterBatchUpdateUtils.java:43)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.batchUpdate(NamedParameterJdbcTemplate.java:355)
。。。
。。。
2022-02-25 15:26:09 [ERROR][com.alibaba.druid.util.JdbcUtils][close][75]-> close connection error
java.sql.SQLException: Protocol violation
	at oracle.jdbc.driver.T4CTTIfun.readRXD(T4CTTIfun.java:579)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:340)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:61)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:543)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:3984)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:175)
	at com.alibaba.druid.filter.FilterAdapter.connection_close(FilterAdapter.java:776)
	at com.alibaba.druid.filter.logging.LogFilter.connection_close(LogFilter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:171)
	at com.alibaba.druid.filter.stat.StatFilter.connection_close(StatFilter.java:261)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:171)
	at com.alibaba.druid.filter.FilterAdapter.connection_close(FilterAdapter.java:776)
	at com.alibaba.druid.filter.FilterChainImpl.connection_close(FilterChainImpl.java:171)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.close(ConnectionProxyImpl.java:115)
。。。
。。。
2022-02-25 15:26:09 [ERROR][com.alibaba.druid.pool.DruidDataSource][handleConnectionException][1486]-> discard connection
java.sql.SQLException: Protocol violation: [0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:464)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOROLLBACK(T4C7Ocommoncall.java:68)
	at oracle.jdbc.driver.T4CConnection.doRollback(T4CConnection.java:694)
	at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:3943)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:584)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:973)
	at com.alibaba.druid.filter.logging.LogFilter.connection_rollback(LogFilter.java:404)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:580)
	at com.alibaba.druid.filter.stat.StatFilter.connection_rollback(StatFilter.java:275)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:580)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:973)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:580)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.rollback(ConnectionProxyImpl.java:400)
	at com.alibaba.druid.pool.DruidPooledConnection.rollback(DruidPooledConnection.java:782)
。。。
。。。
2022-02-25 15:26:09 [ERROR][io.seata.rm.datasource.exec.AbstractDMLBaseExecutor][executeAutoCommitTrue][117]-> execute executeAutoCommitTrue error:Protocol violation: [0]
java.sql.SQLException: Protocol violation: [0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:464)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOROLLBACK(T4C7Ocommoncall.java:68)
	at oracle.jdbc.driver.T4CConnection.doRollback(T4CConnection.java:694)
	at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:3943)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:584)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:973)
	at com.alibaba.druid.filter.logging.LogFilter.connection_rollback(LogFilter.java:404)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:580)
	at com.alibaba.druid.filter.stat.StatFilter.connection_rollback(StatFilter.java:275)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:580)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:973)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:580)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.rollback(ConnectionProxyImpl.java:400
。。。
。。。
2022-02-25 15:26:09 [INFO][org.springframework.beans.factory.xml.XmlBeanDefinitionReader][loadBeanDefinitions][317]-> Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2022-02-25 15:26:10 [INFO][io.seata.tm.api.DefaultGlobalTransaction][rollback][179]-> [10.43.50.17:61111:240497646253379584] rollback status: Rollbacked
2022-02-25 15:26:10 [ERROR][org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter][doFilter][51]-> Uncaught exception thrown
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.RuntimeException: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [  INSERT INTO PDSS_UC_LABLE_INFO (E_LABLE_NUM,LABEL_F,LABEL_S,STATUS,SOURCE_UNIT,CREATE_TIME)  values(?,?,?,?,?,? ) ]; SQL state [null]; error code [0]; connection holder is null; nested exception is java.sql.SQLException: connection holder is null
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:86)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:155)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:123)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [  INSERT INTO PDSS_UC_LABLE_INFO (E_LABLE_NUM,LABEL_F,LABEL_S,STATUS,SOURCE_UNIT,CREATE_TIME)  values(?,?,?,?,?,? ) ]; SQL state [null]; error code [0]; connection holder is null; nested exception is java.sql.SQLException: connection holder is null
	at com.chinatower.product.realize.module.service.impl.AssetsInfoService.createMarkInfo(AssetsInfoService.java:71)
	at com.chinatower.product.realize.module.service.impl.AssetsInfoService.createMarkInfo1(AssetsInfoService.java:626)
	at com.chinatower.product.realize.module.service.impl.AssetsInfoService$$FastClassBySpringCGLIB$$8c7b538b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$1.execute(GlobalTransactionalInterceptor.java:150)
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:104)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:147)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:122)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.chinatower.product.realize.module.service.impl.AssetsInfoService$$EnhancerBySpringCGLIB$$4aa5e480.createMarkInfo1(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:223)
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:494)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.chinatower.product.realize.module.service.impl.AssetsInfoService$$EnhancerBySpringCGLIB$$f3456310.createMarkInfo1(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	... 57 common frames omitted
Caused by: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [  INSERT INTO PDSS_UC_LABLE_INFO (E_LABLE_NUM,LABEL_F,LABEL_S,STATUS,SOURCE_UNIT,CREATE_TIME)  values(?,?,?,?,?,? ) ]; SQL state [null]; error code [0]; connection holder is null; nested exception is java.sql.SQLException: connection holder is null
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1402)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:620)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:634)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:924)
	at org.springframework.jdbc.core.namedparam.NamedParameterBatchUpdateUtils.executeBatchUpdateWithNamedParameters(NamedParameterBatchUpdateUtils.java:43)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.batchUpdate(NamedParameterJdbcTemplate.java:355)
	at com.chinatower.product.realize.module.service.impl.AssetsInfoServiceImpl.insertAll(AssetsInfoServiceImpl.java:559)
	at com.chinatower.product.realize.module.service.impl.AssetsInfoServiceImpl.createMarkInfo(AssetsInfoServiceImpl.java:101)
	at com.chinatower.product.realize.module.service.impl.AssetsInfoServiceImpl$$FastClassBySpringCGLIB$$70636c4b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.chinatower.product.realize.module.service.impl.AssetsInfoServiceImpl$$EnhancerBySpringCGLIB$$933cf08.createMarkInfo(<generated>)
	at com.chinatower.product.realize.module.service.impl.AssetsInfoService.createMarkInfo(AssetsInfoService.java:69)
	... 93 common frames omitted
Caused by: java.sql.SQLException: connection holder is null
	at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1156)
	at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1149)
	at com.alibaba.druid.pool.DruidPooledConnection.getAutoCommit(DruidPooledConnection.java:737)
	at io.seata.rm.datasource.AbstractConnectionProxy.getAutoCommit(AbstractConnectionProxy.java:144)
	at io.seata.rm.datasource.ConnectionProxy.setAutoCommit(ConnectionProxy.java:254)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:124)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:74)
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:115)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:113)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:51)
	at io.seata.rm.datasource.StatementProxy.executeBatch(StatementProxy.java:129)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$batchUpdate$2(JdbcTemplate.java:938)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:605)
	... 104 common frames omitted
Caused by: java.sql.SQLException: Protocol violation: [0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:464)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOROLLBACK(T4C7Ocommoncall.java:68)
	at oracle.jdbc.driver.T4CConnection.doRollback(T4CConnection.java:694)
	at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:3943)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:584)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:973)
	at com.alibaba.druid.filter.logging.LogFilter.connection_rollback(LogFilter.java:404)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:580)
	at com.alibaba.druid.filter.stat.StatFilter.connection_rollback(StatFilter.java:275)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:580)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:973)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:580)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.rollback(ConnectionProxyImpl.java:400)
	at com.alibaba.druid.pool.DruidPooledConnection.rollback(DruidPooledConnection.java:782)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.onException(AbstractDMLBaseExecutor.java:167)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:304)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:155)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:110)
	... 111 common frames omitted

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. oracle数据库 JDBC最新驱动
2. batch insert批量操作
3. xxx

### Ⅵ. Environment:

- JDK version :8
- Seata version:  1.3
- OS :
- Others:

**Comment by a364176773** [comment]
oracle不支持

**Comment by panpana849** [comment]
楼主最后怎么解决的吗
