### ISSUE TITLE
com.alibaba.cloud:spring-cloud-starter-alibaba-seata:2021.1会导致Activiti7加载失败

### ISSUE THREAD

**Issue by tiger822** [seata/seata#4598]
### Ⅰ. Issue Description
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'repositoryServiceBean' defined in class path resource [org/activiti/spring/boot/ProcessEngineAutoConfiguration.class]: Unsatisfied dependency expressed through method 'repositoryServiceBean' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine': FactoryBean threw exception on object creation; nested exception is org.activiti.engine.ActivitiException: Could not set database schema on connection
...
**Caused by: org.activiti.engine.ActivitiException: Could not set database schema on connection
	at org.activiti.engine.impl.db.DbSqlSessionFactory.openSession(DbSqlSessionFactory.java:80) ~[activiti-engine-7.1.0.M6.jar:na]**
	at org.activiti.engine.impl.interceptor.CommandContext.getSession(CommandContext.java:299) ~[activiti-engine-7.1.0.M6.jar:na]

### Ⅱ. Describe what happened
就是在org.activiti.engine.impl.db.DbSqlSessionFactory#openSession的 dbSqlSession.getSqlSession().getConnection().setSchema(getDatabaseSchema());这句发生的，因为activiti初始化时一定会跑这个。
然而查了一天才发现是seata-all和spring-cloud-starter-alibaba-nacos-config两个包里面包含的druid造成的！

com.alibaba.druid.pool.DruidPooledConnection#setSchema 直接就来这句：
    public void setSchema(String schema) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

自己手动将这两个包的druid排除掉就没事！大佬能否别引用druid？？！！或者说如果我用boot默认的连接池，seata/nacos client会正常工作吗？？

**Comment by a364176773** [comment]
你可以用hikari作为数据源，seata使用druid主要是用作sqlparser

**Comment by tiger822** [comment]
上述那两个包只包含了druid而未包含它的自动配置包理应是不可能会自动完成Druid配置的，但是我这个项目用了dubbo/nacos/seata/sentinel阿里生态圈，不知道哪里出了问题，我看了maven依赖树，并没包含druid-spring-boot-starter

**Comment by tiger822** [comment]
已找到根源，谢谢回复。
