### ISSUE TITLE
Seata 1.0.0 running error with more than 30934 port

### ISSUE THREAD

**Issue by haroldyong** [seata/seata#4614]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  When I run io.seata.server.Server.main with  java arg "-p 30935"  , there is  always 
"java.lang.RuntimeException: java.net.BindException: Address already in use: bind
	at io.seata.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:160)
	at io.seata.core.rpc.netty.RpcServer.init(RpcServer.java:129)"
 
```
Just paste your stack trace here!
```

java.lang.RuntimeException: java.net.BindException: Address already in use: bind
	at io.seata.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:160)
	at io.seata.core.rpc.netty.RpcServer.init(RpcServer.java:129)
	at io.seata.server.Server.main(Server.java:92)
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:459)
	at java.base/sun.nio.ch.Net.bind(Net.java:448)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:232)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:130)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:955)
2022-05-16 11:28:20.169 | INFO  | ShutdownHook | TID: N/A | io.seata.core.rpc.netty.RpcServer 175 | destroyed rpcServer
Disconnected from the target VM, address: '127.0.0.1:6725', transport: 'socket'

### Ⅲ. Describe what you expected to happen

if i use 30934 or less , it works fine. 

if 30935 or above , there alway error. "Address already in use: bind"

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : java 11 . idea internal
- Seata version:  1.0.0
- OS : windows10 pro.
- Others:

**Comment by a364176773** [comment]
Address already in use: bind
你该去排查这个原因
