### ISSUE TITLE
java.util.ConcurrentModificationException occured in seata server

### ISSUE THREAD

**Issue by caozhiyuan** [seata/seata#4667]
### Ⅰ. Issue Description

java.util.ConcurrentModificationException occured in seata server

### Ⅱ. Describe what happened

```
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at io.seata.server.storage.redis.store.RedisTransactionStoreManager.dogetXidsForTargetMapRecursive(RedisTransactionStoreManager.java:728)
	at io.seata.server.storage.redis.store.RedisTransactionStoreManager.dogetXidsForTargetMapRecursive(RedisTransactionStoreManager.java:753)
	at io.seata.server.storage.redis.store.RedisTransactionStoreManager.readSession(RedisTransactionStoreManager.java:436)
	at io.seata.server.storage.redis.store.RedisTransactionStoreManager.readSession(RedisTransactionStoreManager.java:486)
	at io.seata.server.storage.redis.session.RedisSessionManager.findGlobalSessions(RedisSessionManager.java:186)
	at io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking(DefaultCoordinator.java:352)
	at io.seata.server.session.SessionHolder.distributedLockAndExecute(SessionHolder.java:398)
```

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.5.0
- OS : win 11
- Others:

**Comment by wingchi-leung** [comment]
cool, I try to fix it.
