### ISSUE TITLE
Could not register branch into global session  status = TimeoutRollbacking while expecting Begin

### ISSUE THREAD

**Issue by llsydn** [seata/seata#4675]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
无法注册分支事务。（偶尔报错）

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
io.seata.core.exception.GlobalTransactionException: Could not register branch into global session xid = 192.168.4.38:8091:278168510721318912 status = TimeoutRollbacking while expecting Begin
        at io.seata.server.coordinator.AbstractCore.globalSessionStatusCheck(AbstractCore.java:102) ~[seata-server-1.4.1.1.jar:na]
        at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:73) ~[seata-server-1.4.1.1.jar:na]
        at io.seata.server.storage.db.session.DataBaseSessionManager.lockAndExecute(DataBaseSessionManager.java:194) ~[seata-server-1.4.1.1.jar:na]
        at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:324) ~[seata-server-1.4.1.1.jar:na]
        at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:72) ~[seata-server-1.4.1.1.jar:na]
        at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:97) ~[seata-server-1.4.1.1.jar:na]
        at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:192) [seata-server-1.4.1.1.jar:na]
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184) ~[seata-server-1.4.1.1.jar:na]
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179) ~[seata-server-1.4.1.1.jar:na]
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116) ~[seata-core-1.4.1.1.jar:na]
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179) [seata-server-1.4.1.1.jar:na]
        at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136) [seata-core-1.4.1.1.jar:na]
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:427) [seata-server-1.4.1.1.jar:na]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:124) [seata-core-1.4.1.1.jar:na]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77) [seata-core-1.4.1.1.jar:na]
        at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:278) [seata-core-1.4.1.1.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_201]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.4.1
- OS :  linux centos 7
- Others:

**Comment by a364176773** [comment]
通过日志查询begin的时间，再根据异常的时间看下timeout设置是否合理，如果不合理自行调整
如果是没有到timeout设置时间就超时，那么检查tc和数据库的时区是否一致，不一致修改为一致来处理
