### ISSUE TITLE
seata 1.5.1  是不是还不支持  MySQL 8 ？

### ISSUE THREAD

**Issue by panhc1997** [seata/seata#4686]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata 1.5.1 使用MySQL 8.0.25 作为服务端数据库
seata 1.5.1  是不是还不支持  MySQL 8 ？
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen

Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:677)
        ... 35 common frames omitted
<==

15:09:39.812  WARN --- [                     main] i.s.s.s.db.store.LogStoreDataBaseDAO     : global_table table or TRANSACTION_NAME column not found
15:09:39.982  INFO --- [                     main] i.s.core.rpc.netty.NettyServerBootstrap  : Server started, service listen port: 11006
15:09:39.999  INFO --- [                     main] com.alibaba.nacos.client.naming          : initializer namespace from System Property :null
15:09:40.027  INFO --- [                     main] com.alibaba.nacos.client.naming          : [BEAT] adding beat: BeatInfo{port=11006, ip='***.***.***.***', weight=1.0, serviceName='THING@@seata-server', cluste
r='default', metadata={}, scheduled=false, period=5000, stopped=false} to beat map.
15:09:40.029  INFO --- [                     main] com.alibaba.nacos.client.naming          : [REGISTER-SERVICE] 10e2e18f-43a0-4f6c-9a52-7770027d76f9 registering service THING@@seata-server with instance: In
stance{instanceId='null', ip='172.16.8.162', port=11006, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='default', serviceName='null', metadata={}}
15:09:40.035  INFO --- [                     main] io.seata.server.ServerRunner             : seata server started in 637 millSeconds
15:09:44.857  INFO --- [       TxTimeoutCheck_1_1] io.seata.server.session.SessionHolder    : Exception running function with key = TxTimeoutCheck
==>
java.lang.NullPointerException: null
        at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1731)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1419)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1399)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1389)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:100)
        at io.seata.server.storage.db.lock.DataBaseDistributedLocker.acquireLock(DataBaseDistributedLocker.java:111)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  1.5.1
- OS :
- Others:  MySQL 8.0.25

**Comment by slievrly** [comment]
@panhc1997  1.4.2 supports mysql8. But in 1.5.1, you need to manually add mysql8 dependency to seata-server.jar classpath.

**Comment by panhc1997** [comment]
通过替换seata-server.jar中的mysql驱动包已经解决，但是这种用springboot-maven插件打包的方式，对替换jar包不太方便。
不如1.4 那样替换方便
