### ISSUE TITLE
1.5.1版本里面没有mysql8.0的依赖

### ISSUE THREAD

**Issue by xiamo6666** [seata/seata#4712]
![image](https://user-images.githubusercontent.com/46433683/174263504-861f674f-1162-41d2-ac42-27346ea08eb9.png)
只有mysql5.1的依赖，使用mysql8，启动报错
java.sql.SQLException: com.mysql.cj.jdbc.Driver
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:679)
        at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1214)
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:883)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1393)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1389)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:100)
        at io.seata.server.storage.db.store.LogStoreDataBaseDAO.queryTableStructure(LogStoreDataBaseDAO.java:473)
        at io.seata.server.storage.db.store.LogStoreDataBaseDAO.initTransactionNameSize(LogStoreDataBaseDAO.java:457)
        at io.seata.server.storage.db.store.LogStoreDataBaseDAO.<init>(LogStoreDataBaseDAO.java:106)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.<init>(DataBaseTransactionStoreManager.java:94)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.getInstance(DataBaseTransactionStoreManager.java:79)
        at io.seata.server.storage.db.session.DataBaseSessionManager.init(DataBaseSessionManager.java:76)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:628)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:459)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:452)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:420)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:309)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:242)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:82)
        at io.seata.server.session.SessionHolder.init(SessionHolder.java:105)
        at io.seata.server.Server.start(Server.java:73)
        at io.seata.server.ServerRunner.run(ServerRunner.java:50)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:808)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:792)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:346)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318)
        at io.seata.server.ServerApplication.main(ServerApplication.java:30)
Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:677)
        ... 27 common frames omitted

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/4686
