### ISSUE TITLE
NullException at TableMeta.lambda$getPrimaryKeyMap$0 when use mycat

### ISSUE THREAD

**Issue by zt9788** [seata/seata#4735]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
NullException at  TableMeta.lambda$getPrimaryKeyMap$0  when use Mycat 1.X (JDK17) 
There is no Error when change the url to mysql.
How can i use Mycat? 

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
java.lang.NullPointerException: Cannot invoke "io.seata.rm.datasource.sql.struct.ColumnMeta.getColumnName()" because "col" is null
	at io.seata.rm.datasource.sql.struct.TableMeta.lambda$getPrimaryKeyMap$0(TableMeta.java:120) ~[seata-all-1.4.2.jar:1.4.2]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at io.seata.rm.datasource.sql.struct.TableMeta.getPrimaryKeyMap(TableMeta.java:117) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.sql.struct.TableMeta.getPrimaryKeyOnlyName(TableMeta.java:140) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.mysql.MySQLInsertExecutor.getPkValues(MySQLInsertExecutor.java:84) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.BaseInsertExecutor.afterImage(BaseInsertExecutor.java:76) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:101) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:140) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:343) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:184) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:139) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:82) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:113) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:111) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:50) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:55) ~[seata-all-1.4.2.jar:1.4.2]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59) ~[mybatis-3.5.10.jar:3.5.10]
	at jdk.proxy3.$Proxy653.execute(Unknown Source) ~[?:?]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47) ~[mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) ~[mybatis-3.5.10.jar:3.5.10]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64) ~[mybatis-3.5.10.jar:3.5.10]
	at jdk.proxy2.$Proxy652.update(Unknown Source) ~[?:?]
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

spring2.6.x + mybaits-plus+seata

1. change mysql url to mycat 
2. rollback some data

### Ⅵ. Environment:

- JDK version : 17
- Seata version:   1.4.2/1.5.1.1
- OS : ubuntu
- Others: mycat version: 1.6.7.3

**Comment by zt9788** [comment]
need to upgrade mycat to 1.6.7.6
