### ISSUE TITLE
1.5连接mysql8不识别驱动包

### ISSUE THREAD

**Issue by slw07** [seata/seata#4767]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata1.5 通过nginx注册nacos集群，linux上启动seata报错

### Ⅱ. Describe what happened

 java.sql.SQLException: com.mysql.cj.jdbc.Driver
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:679)
        at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1214)
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:883)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1393)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1389)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:100)
        at io.seata.server.storage.db.store.LogStoreDataBaseDAO.queryTableStructure(LogStoreDataBaseDAO.java:473)
        at io.seata.server.storage.db.store.LogStoreDataBaseDAO.initTransactionNameSize(LogStoreDataBaseDAO.java:457)
        at io.seata.server.storage.db.store.LogStoreDataBaseDAO.<init>(LogStoreDataBaseDAO.java:106)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.<init>(DataBaseTransactionStoreManager.java:94)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.getInstance(DataBaseTransactionStoreManager.java:79)
        at io.seata.server.storage.db.session.DataBaseSessionManager.init(DataBaseSessionManager.java:76)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:628)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:459)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:452)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:420)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:309)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:242)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:82)
        at io.seata.server.session.SessionHolder.init(SessionHolder.java:105)
        at io.seata.server.Server.start(Server.java:73)
        at io.seata.server.ServerRunner.run(ServerRunner.java:50)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:808)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:792)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:346)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318)
        at io.seata.server.ServerApplication.main(ServerApplication.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:677)
        ... 35 common frames omitted
Just paste your stack trace here!
```


### Ⅲ. Describe what you expected to happen


### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?


### Ⅵ. Environment:

- JDK version :1.8
- Seata version:  1.5
- OS :
- Others:

**Comment by a364176773** [comment]
1.5没有搭载mysql8的驱动包,等1.5.2吧

**Comment by slw07** [comment]
好的-------- 原始邮件 --------发件人： FUNKYE ***@***.***>日期： 2022年7月10日周日 晚上9:47收件人： seata/seata ***@***.***>抄送： slw07 ***@***.***>, Author ***@***.***>主    题： Re: [seata/seata] 1.5连接mysql8不识别驱动包 (Issue #4767)

1.5没有搭载mysql8的驱动包,等1.5.2吧
