### ISSUE TITLE
ERROR: duplicate key value violates unique constraint "idx_45452_ux_undo_log"

### ISSUE THREAD

**Issue by 1jinxin** [seata/seata#4775]
seata 版本：seata 1.4.2  
问题原因：undo_log 表发生主键冲突
【undo_log deleted with GlobalFinished】，【undo_log added with GlobalFinished 】   

[2022-07-13 16:29:39.920] [INFO] [rpcDispatch_RMROLE_1_1_4] [] xid 172.16.2.197:8091:6386385551898582818 branch 6386385551898588877, undo_log deleted with GlobalFinished [AbstractUndoLogManager.java:333] 
[2022-07-13 16:29:39.920] [INFO] [rpcDispatch_RMROLE_1_1_4] [] Branch Rollbacked result: PhaseTwo_Rollbacked [AbstractRMHandler.java:131] 
[2022-07-13 16:29:39.921] [INFO] [rpcDispatch_RMROLE_1_3_4] [] xid 172.16.2.197:8091:6386385551898582818 branch 6386385551898588877, undo_log added with GlobalFinished [AbstractUndoLogManager.java:340] 
[2022-07-13 16:29:39.921] [INFO] [rpcDispatch_RMROLE_1_3_4] [] Branch Rollbacked result: PhaseTwo_Rollbacked [AbstractRMHandler.java:131] 
[2022-07-13 16:29:39.921] [ERROR] [rpcDispatch_RMROLE_1_2_4] [] {conn-10192, pstmt-585867} execute error. INSERT INTO undo_log (id,branch_id, xid, context, rollback_info, log_status, log_created, log_modified)VALUES (nextval('undo_log_id_seq'), ?, ?, ?, ?, ?, now(), now()) [Slf4jLogFilter.java:149] 
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_45452_ux_undo_log"
  Detail: Key (xid, branch_id)=(172.16.2.197:8091:6386385551898582818, 6386385551898588877) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3253)
	at com.alibaba.druid.wall.WallFilter.preparedStatement_executeUpdate(WallFilter.java:662)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3251)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_executeUpdate(FilterAdapter.java:1092)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeUpdate(FilterEventAdapter.java:491)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3251)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_executeUpdate(FilterAdapter.java:1092)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3251)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_executeUpdate(FilterAdapter.java:1092)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeUpdate(FilterEventAdapter.java:491)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3251)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeUpdate(PreparedStatementProxyImpl.java:194)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255)
	at io.seata.rm.datasource.undo.postgresql.PostgresqlUndoLogManager.insertUndoLog(PostgresqlUndoLogManager.java:99)
	at io.seata.rm.datasource.undo.postgresql.PostgresqlUndoLogManager.insertUndoLogWithGlobalFinished(PostgresqlUndoLogManager.java:85)
	at io.seata.rm.datasource.undo.AbstractUndoLogManager.undo(AbstractUndoLogManager.java:337)
	at io.seata.rm.datasource.DataSourceManager.branchRollback(DataSourceManager.java:122)
	at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:125)
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:67)
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:63)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:124)
	at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:63)
	at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:68)
	at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35)
	at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150)
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.handleBranchRollback(RmBranchRollbackProcessor.java:63)
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.process(RmBranchRollbackProcessor.java:58)
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[2022-07-13 16:29:39.922] [INFO] [rpcDispatch_RMROLE_1_2_4] [] branchRollback failed. branchType:[AT], xid:[172.16.2.197:8091:6386385551898582818], branchId:[6386385551898588877], resourceId:[jdbc:postgresql://20.58.68.26:15432/powerresourcedb?currentSchema=middleground_busi], applicationData:[null]. reason:[Branch session rollback failed and try again later xid = 172.16.2.197:8091:6386385551898582818 branchId = 6386385551898588877 ERROR: duplicate key value violates unique constraint "idx_45452_ux_undo_log"
  Detail: Key (xid, branch_id)=(172.16.2.197:8091:6386385551898582818, 6386385551898588877) already exists.] [StackTraceLogger.java:43]

**Comment by a364176773** [comment]
建议看下官网faq防悬挂
