### ISSUE TITLE
io.seata.rm.RMHandlerAT - Failed to delete expired undo_log, error:ERROR: cannot execute DELETE in a read-only transaction org.postgresql.util.PSQLException: ERROR: cannot execute DELETE in a read-only transaction

### ISSUE THREAD

**Issue by 110117** [seata/seata#4786]
数据库：两主两从
分库分表：shardingJdbc
2022-07-17  INFO [ io.seata.core.rpc.processor.client.RmUndoLogProcessor - rm handle undo log process:UndoLogDeleteRequest{resourceId='jdbc:postgresql://xx.xx.xx.xx', saveDays=7, branchType=AT} 主库
2022-07-17  INFO [] io.seata.core.rpc.processor.client.RmUndoLogProcessor - rm handle undo log process:UndoLogDeleteRequest{resourceId='jdbc:postgresql://xx.xx.xx.xx', saveDays=7, branchType=AT} 从库
2022-07-17  INFO [] io.seata.core.rpc.processor.client.RmUndoLogProcessor - rm handle undo log process:UndoLogDeleteRequest{resourceId='jdbc:postgresql://xx.xx.xx.xx', saveDays=7, branchType=AT} 主库
2022-07-17  INFO [] io.seata.core.rpc.processor.client.RmUndoLogProcessor - rm handle undo log process:UndoLogDeleteRequest{resourceId='jdbc:postgresql://xx.xx.xx.xx', saveDays=7, branchType=AT} 从库
2022-07-17  ERROR [] io.seata.rm.RMHandlerAT - Failed to delete expired undo_log, error:ERROR: cannot execute DELETE in a read-only transaction
org.postgresql.util.PSQLException: ERROR: cannot execute DELETE in a read-only transaction
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255)
        at io.seata.rm.datasource.undo.postgresql.PostgresqlUndoLogManager.deleteUndoLogByLogCreated(PostgresqlUndoLogManager.java:59)
        at io.seata.rm.RMHandlerAT.handle(RMHandlerAT.java:59)
        at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:73)
        at io.seata.core.protocol.transaction.UndoLogDeleteRequest.handle(UndoLogDeleteRequest.java:70)
        at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150)
不应该 清除从库的undo_log ，这问题如何解决？？

**Comment by a364176773** [comment]
不要代理从库，多数据源改为手动代理

**Comment by a364176773** [comment]
建议关闭自动代理

**Comment by 110117** [comment]
enable-auto-data-source-proxy: false
自动代理已经关掉了，没用呢

**Comment by a364176773** [comment]
> enable-auto-data-source-proxy: false 自动代理已经关掉了，没用呢

数据先删掉重新测试，这是因为你代理了从库，走到从库去删除了，所有的增删改不要走从库，所有不要代理从库，如果是shardingJdbc那边把从库代理了，建议你去问下他们那边怎么关

**Comment by 110117** [comment]
io.seata.core.rpc.processor.client.RmUndoLogProcessor  这是服务端发起的定时任务，还是客户端的？？
