### ISSUE TITLE
io.seata.core.rpc.processor.client.RmUndoLogProcessor 有定时任务执行吗

### ISSUE THREAD

**Issue by 110117** [seata/seata#4791]
数据库：两主两从
分库分表：shardingJdbc
2022-07-17  INFO [ io.seata.core.rpc.processor.client.RmUndoLogProcessor - rm handle undo log process:UndoLogDeleteRequest{resourceId='jdbc:postgresql://xx.xx.xx.xx', saveDays=7, branchType=AT} 主库
2022-07-17  INFO [] io.seata.core.rpc.processor.client.RmUndoLogProcessor - rm handle undo log process:UndoLogDeleteRequest{resourceId='jdbc:postgresql://xx.xx.xx.xx', saveDays=7, branchType=AT} 从库
2022-07-17  INFO [] io.seata.core.rpc.processor.client.RmUndoLogProcessor - rm handle undo log process:UndoLogDeleteRequest{resourceId='jdbc:postgresql://xx.xx.xx.xx', saveDays=7, branchType=AT} 主库
2022-07-17  INFO [] io.seata.core.rpc.processor.client.RmUndoLogProcessor - rm handle undo log process:UndoLogDeleteRequest{resourceId='jdbc:postgresql://xx.xx.xx.xx', saveDays=7, branchType=AT} 从库
2022-07-17  ERROR [] io.seata.rm.RMHandlerAT - Failed to delete expired undo_log, error:ERROR: cannot execute DELETE in a read-only transaction
org.postgresql.util.PSQLException: ERROR: cannot execute DELETE in a read-only transaction
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255)
        at io.seata.rm.datasource.undo.postgresql.PostgresqlUndoLogManager.deleteUndoLogByLogCreated(PostgresqlUndoLogManager.java:59)
        at io.seata.rm.RMHandlerAT.handle(RMHandlerAT.java:59)
        at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:73)
        at io.seata.core.protocol.transaction.UndoLogDeleteRequest.handle(UndoLogDeleteRequest.java:70)
        at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150)

**Comment by a364176773** [comment]
不要代理从库

**Comment by a364176773** [comment]
> io.seata.core.rpc.processor.client.RmUndoLogProcessor 这个类会有定时模块执行吗

由tc定时下发执行，请不要把从库代理，这样就不会受到影响
