### ISSUE TITLE
1.5.2版本无法启动

### ISSUE THREAD

**Issue by GreenCypress** [seata/seata#4803]
找不到是因为什么原因，1.5.1版本可以。
### 环境
jdk：1.8

### 启动报错信息如下：
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
	at io.seata.server.ServerApplication.main(ServerApplication.java:30)
	... 8 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 9 more
```

**Comment by slievrly** [comment]
@GreenCypress any more information? Start by  source, release package or Docker?

**Comment by GreenCypress** [comment]
> 
release package

**Comment by GreenCypress** [comment]
@slievrly release package

**Comment by a364176773** [comment]
cd bin/seata-server.sh  
sh seata-server.sh
因为spring的loader.path写成了../lib所以会加载不到相关的依赖

**Comment by liujunlin5168** [comment]
你好  请问一下 你应用服务接入seata后可以正常启动么，我本地应用服务启动报错（服务yaml文件没有添加seata.transport.rpcRmRequestTimeout配置）
应用服务依赖信息如下：
seata服务端版本是1.5.2，client端引用seata版本1.5.2,spring版本5.3.7.RELEASE
seata依赖如下：
<dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.5.2</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2021.1</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

应用服务接入seata启动报错，错误信息如下：
APPLICATION FAILED TO START
***************************

Description:

Configuration property name 'seata.transport.rpcRmRequestTimeout' is not valid:

    Invalid characters: 'R', 'R', 'T'
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

Action:

Modify 'seata.transport.rpcRmRequestTimeout' so that it conforms to the canonical names requirements.

2022-07-26 11:08:11.362 ERROR 15504 --- [           main] c.t.c.a.Slf4jFailureAnalysisReporter     : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Configuration property name 'seata.transport.rpcRmRequestTimeout' is not valid:

    Invalid characters: 'R', 'R', 'T'
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

Action:

Modify 'seata.transport.rpcRmRequestTimeout' so that it conforms to the canonical names requirements.
