### ISSUE TITLE
版本1.4.2，RM启动后第一次提交事务会失败，第二次开始就正常，这是为啥？

### ISSUE THREAD

**Issue by linchaorong** [seata/seata#4851]
Caused by: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 172.19.80.15:8091:9052489585195824275, may be has finished.] ]
	at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:69)
	at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96)
	at io.seata.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:272)
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:250)
	... 137 common frames omitted

**Comment by a364176773** [comment]
看tm端的异常是什么，应该是第一次没有预热，请求耗时较久，a调b可能直接超时了，a就决议了
