### ISSUE TITLE
Could not found global transaction xid

### ISSUE THREAD

**Issue by dev-leic** [seata/seata#4866]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
找不到全局事务xid

### Ⅱ. Describe what happened

```
18:31:34.059  INFO --- [verHandlerThread_1_13_500] i.s.c.r.processor.server.RegRmProcessor  : RM register success,message:RegisterRMRequest{resourceIds='jdbc:mysql://192.168.1.175:3306/system', applicationId='system', transactionServiceGroup='common-tx-group'},channel:[id: 0x893bcce5, L:/192.168.1.161:8091 - R:/192.168.1.13:64188],client version:1.4.0
18:31:42.449  INFO --- [verHandlerThread_1_14_500] i.s.c.r.processor.server.RegRmProcessor  : RM register success,message:RegisterRMRequest{resourceIds='jdbc:mysql://192.168.1.175:3306/user', applicationId='user', transactionServiceGroup='common-tx-group'},channel:[id: 0x1d303f4f, L:/192.168.1.161:8091 - R:/192.168.1.13:64196],client version:1.4.0
18:32:12.581  INFO --- [ettyServerNIOWorker_1_3_8] i.s.c.r.processor.server.RegTmProcessor  : TM register success,message:RegisterTMRequest{applicationId='user', transactionServiceGroup='common-tx-group'},channel:[id: 0xc24f2907, L:/192.168.1.161:8091 - R:/192.168.1.13:64241],client version:1.4.0
18:32:12.593  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : timeout=60000,transactionName=addExpert(com.cmnt.cloud.user.param.expert.AddExpertParam),clientIp:192.168.1.13,vgroup:common-tx-group
18:32:12.722  INFO --- [verHandlerThread_1_15_500] i.s.s.coordinator.DefaultCoordinator     : Begin new global transaction applicationId: user,transactionServiceGroup: common-tx-group, transactionName: addExpert(com.cmnt.cloud.user.param.expert.AddExpertParam),timeout:60000,xid:192.168.1.161:8091:302511376897679360
18:32:15.765  INFO --- [verHandlerThread_1_16_500] i.s.c.r.processor.server.RegRmProcessor  : RM register success,message:RegisterRMRequest{resourceIds='jdbc:mysql://192.168.1.175:3306/system', applicationId='system', transactionServiceGroup='common-tx-group'},channel:[id: 0x893bcce5, L:/192.168.1.161:8091 - R:/192.168.1.13:64188],client version:1.4.0
18:32:16.238  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : xid=192.168.1.161:8091:302511376897679360,branchType=AT,resourceId=jdbc:mysql://192.168.1.175:3306/system,lockKey=role_user:62fa20ae839d1698e2d77cc0,clientIp:192.168.1.13,vgroup:common-tx-group
18:32:16.253 ERROR --- [verHandlerThread_1_17_500] i.s.c.e.AbstractExceptionHandler         : Catch TransactionException while do RPC, request: xid=192.168.1.161:8091:302511376897679360,branchType=AT,resourceId=jdbc:mysql://192.168.1.175:3306/system,lockKey=role_user:62fa20ae839d1698e2d77cc0
==>
io.seata.core.exception.GlobalTransactionException: Could not found global transaction xid = 192.168.1.161:8091:302511376897679360, may be has finished.
        at io.seata.server.coordinator.AbstractCore.assertGlobalSessionNotNull(AbstractCore.java:120) ~[seata-server-1.4.0.jar:na]
        at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:71) ~[seata-server-1.4.0.jar:na]
        at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:97) ~[seata-server-1.4.0.jar:na]
        at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:192) [seata-server-1.4.0.jar:na]
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184) ~[seata-server-1.4.0.jar:na]
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179) ~[seata-server-1.4.0.jar:na]
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116) ~[seata-core-1.4.0.jar:na]
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179) [seata-server-1.4.0.jar:na]
        at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136) [seata-core-1.4.0.jar:na]
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:427) [seata-server-1.4.0.jar:na]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:124) [seata-core-1.4.0.jar:na]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77) [seata-core-1.4.0.jar:na]
        at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:278) [seata-core-1.4.0.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
<==
```

### Ⅲ. Describe what you expected to happen

能够匹配上xid，不报错

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. user通过feign调用system
2. user方法已加    
@GlobalTransactional(timeoutMills = 60000)
3. 匹配xid错误

### Ⅴ. Anything else we need to know?
feign拦截器已增加 xid header

String xid = RootContext.getXID();
requestTemplate.header(RootContext.KEY_XID, xid);

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.4
- OS :
- Others:

**Comment by a364176773** [comment]
跟你tc部署有关,集群部署的tc的外部存储不一致导致数据不共享,看日志前面刚begin,而且没有决议的日志直接找不到xid,基本上是这个原因

**Comment by TodyPlay** [comment]
单机部署也是这样咋搞

2022-10-19 22:42:13.930  INFO --- [          batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : xid=172.18.0.20:8091:180462466153357316,extraData=null,clientIp:172.18.0.16,vgroup:ftc-tx-group
2022-10-19 22:46:55.750  INFO --- [          batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : timeout=60000,transactionName=submit(com.iss.dtg.idms.eamc.invoice.invoiceapply.app.dto.InvoiceApplyDTO),clientIp:172.18.0.16,vgroup:ftc-tx-group
2022-10-19 22:46:55.781  INFO --- [  ServerHandlerThread_1_39_500] i.s.s.coordinator.DefaultCoordinator     : Begin new global transaction applicationId: idms-application-ebank,transactionServiceGroup: ftc-tx-group, transactionName: submit(com.iss.dtg.idms.eamc.invoice.invoiceapply.app.dto.InvoiceApplyDTO),timeout:60000,xid:172.18.0.20:8091:180462466153357319
2022-10-19 22:46:58.872  INFO --- [          batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : xid=172.18.0.20:8091:180462466153357319,branchType=TCC,resourceId=invoiceApplySubmitAction,lockKey=null,clientIp:172.18.0.16,vgroup:ftc-tx-group
2022-10-19 22:46:58.898 ERROR --- [  ServerHandlerThread_1_40_500] i.s.c.e.AbstractExceptionHandler         : Catch TransactionException while do RPC, request: xid=172.18.0.20:8091:180462466153357319,branchType=TCC,resourceId=invoiceApplySubmitAction,lockKey=null
==>
io.seata.core.exception.GlobalTransactionException: Could not found global transaction xid = 172.18.0.20:8091:180462466153357319, may be has finished.
	at io.seata.server.coordinator.AbstractCore.assertGlobalSessionNotNull(AbstractCore.java:126) ~[seata-server-1.4.2.1.jar:na]
	at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:76) ~[seata-server-1.4.2.1.jar:na]
	at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:100) ~[seata-server-1.4.2.1.jar:na]
	at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:199) [seata-server-1.4.2.1.jar:na]
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184) ~[seata-server-1.4.2.1.jar:na]
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179) ~[seata-server-1.4.2.1.jar:na]
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:124) ~[seata-core-1.4.2.1.jar:na]
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179) [seata-server-1.4.2.1.jar:na]
	at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136) [seata-core-1.4.2.1.jar:na]
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:473) [seata-server-1.4.2.1.jar:na]
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:124) [seata-core-1.4.2.1.jar:na]
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77) [seata-core-1.4.2.1.jar:na]
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:279) [seata-core-1.4.2.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_232]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]
<==
