### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by xiankaihong** [seata/seata#4871]
nginx部署的nacos集群，统一端口映射后，修改seata配置无法启动seata报错
![Uploading a52f7d59ef2a8f2a58e697b3734aa94.jpg…]()

**Comment by elrond-g** [comment]
图裂了？

**Comment by xiankaihong** [comment]
Caused by: com alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after al1 servers([127.0.0.1:80/nacos])tried:ErrCode:404，Errlsg:htm1><body><h1>Whitelabel Error Page</h1><p>This application has no ex olicit mapping for /error. so you are seeing this as a fallback.</p >divid=’created’>Wed Aug 17 17:01:08 CST 2022</div o<div>There was an unexpected error (type=Not Found, status=404).</div><div>No message available</div></body></html)
at comalibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy. java:552) ~[nacos-client-1. 3.3. jar:na at comalibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy. java:491) ~[nacos-client-1.3.3.jar:na at comalibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy. java:486) ~[nacos-client-1. 3.3. jar :na]
at com alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy. java:239)~[nacos-client-1.3.3.ja ar:na]
at comalibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:200) Lnacos-cli ent-1.3.3.jar:nal at com alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService. java:185) ~[nacos-clin ent-1.33.jar:na.
at io.seata.discovery.registry.nacos.NacosRegistryServiceImp1.register(NacosRegistryServiceImp1.java:85) [seata a-discovery-nacos-1.4.0.jar:na]
at io.seata.core.rpc.netty.NettyServerBootstrap.start(NettyServerBootstrap.java:153) Lseata-core-1.4.0.jar:na. 
3 conmon frames omitted

**Comment by xiankaihong** [comment]
上边是报错信息：
配置文件内容如下：
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "nacos"
  loadBalance = "RandomLoadBalance"
  loadBalanceVirtualNodes = 10

  nacos {
    application = "seata-server"
    serverAddr = "127.0.0.1:80/nacos"
    group = "SEATA_GROUP"
    namespace = ""
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
  eureka {
    serviceUrl = "http://localhost:8761/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = 0
    password = ""
    cluster = "default"
    timeout = 0
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
  }
  etcd3 {
    cluster = "default"
    serverAddr = "http://localhost:2379"
  }
  sofa {
    serverAddr = "127.0.0.1:9603"
    application = "default"
    region = "DEFAULT_ZONE"
    datacenter = "DefaultDataCenter"
    cluster = "default"
    group = "SEATA_GROUP"
    addressWaitTime = "3000"
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "file"

  nacos {
    serverAddr = "127.0.0.1:80/nacos"
    namespace = ""
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
  }
  consul {
    serverAddr = "127.0.0.1:8500"
  }
  apollo {
    appId = "seata-server"
    apolloMeta = "http://192.168.1.204:8801"
    namespace = "application"
    apolloAccesskeySecret = ""
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  etcd3 {
    serverAddr = "http://localhost:2379"
  }
  file {
    name = "file.conf"
  }
}

**Comment by a364176773** [comment]
serverAddr = "127.0.0.1:80/nacos"  不需要加/nacos
