### ISSUE TITLE
Server start failed, the listen port: 9002 

### ISSUE THREAD

**Issue by renjiangyang** [seata/seata#4875]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
无法启动，报错如下：
14:01:29.737  INFO --- [                     main] o.a.coyote.http11.Http11NioProtocol      : Starting ProtocolHandler ["http-nio-8002"]
14:01:29.763  INFO --- [                     main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8002 (http) with context path ''
14:01:29.784  INFO --- [                     main] io.seata.server.ServerApplication        : Started ServerApplication in 6.228 seconds (JVM running for 7.879)
14:01:30.170 ERROR --- [                     main] io.seata.server.ServerRunner             : seata server start error: Server start failed, the listen port: 9002 
==>
java.lang.RuntimeException: Server start failed, the listen port: 9002
        at io.seata.core.rpc.netty.NettyServerBootstrap.start(NettyServerBootstrap.java:174)
        at io.seata.core.rpc.netty.AbstractNettyRemotingServer.init(AbstractNettyRemotingServer.java:56)
        at io.seata.core.rpc.netty.NettyRemotingServer.init(NettyRemotingServer.java:61)
        at io.seata.server.Server.start(Server.java:93)
        at io.seata.server.ServerRunner.run(ServerRunner.java:50)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:808)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:792)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:346)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318)
        at io.seata.server.ServerApplication.main(ServerApplication.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:438)
        at sun.nio.ch.Net.bind(Net.java:430)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:225)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 配置中没有9002端口的配置，与nacos（也没有配置9002的地方）冲突

### Ⅴ. Anything else we need to know?
同一服务器上，允许nacos和seata同时启动

### Ⅵ. Environment:

- JDK version : 1，8
- Seata version:  1.5.1
- OS : Centos7.6
- Others:

**Comment by a364176773** [comment]
Address already in use 请自行排查下端口冲突问题，且seata-server的http端口和netty的tcp端口不要设置成同一个
