### ISSUE TITLE
GlobalTransactionException: Could not found global transaction xid = xxxxxxxxxxx:8091:5674781293195218178, may be has finished.

### ISSUE THREAD

**Issue by zhangnix2** [seata/seata#4898]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
单机，storemode=db部署，业务是AT模式下订单服务通过feign调用库存服务。从前天开始在我的一个环境出现该问题。出现的概率大概是1/3-1/4. 然后我加了点日志放上去，发现在失败的情况下，没有事务发起方的add记录。其它的issues超时，file事务无法同步等因素
均已自查。也尝试升级过客户端版本至1.5.2但是仍然不起作用。
### Ⅱ. Describe what happened

 成功的日志：
```
2022-08-31 21:17:43.313  INFO --- [  ServerHandlerThread_1_23_500] i.s.s.s.d.s.DataBaseSessionManager       : 开启事务, xid: xxxxxxxxxxx:8091:308351234998353920, tid: 308351234998353920, aid: service-order
2022-08-31 21:17:43.535  INFO --- [  ServerHandlerThread_1_23_500] i.s.s.s.db.store.LogStoreDataBaseDAO     : 执行全局事务,INSERT, globalTransactionDO: {"applicationId":"service-order","beginTime":1661951863312,"status":1,"timeout":60000,"transactionId":308351234998353920,"transactionName":"create(com.xxxxxx.esorder.frontend.request.OrderCreateRequest, java.lang.Long, java.lang.String, java.lang.String, java.lang.String)","transactionServiceGroup":"my_test_tx_group","xid":"xxxxxxxxxxx:8091:308351234998353920"}
2022-08-31 21:17:43.598  INFO --- [  ServerHandlerThread_1_23_500] i.s.s.coordinator.DefaultCoordinator     : Begin new global transaction applicationId: service-order,transactionServiceGroup: my_test_tx_group, transactionName: create(com.xxxxxx.esorder.frontend.request.OrderCreateRequest, java.lang.Long, java.lang.String, java.lang.String, java.lang.String),timeout:60000,xid:xxxxxxxxxxx:8091:308351234998353920
2022-08-31 21:17:48.912  INFO --- [          batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : xid=xxxxxxxxxxx:8091:308351234998353920,branchType=AT,resourceId=jdbc:mysql://xxxxxxxxxxx:3306/xxxxxxxxx,lockKey=t_es_warehouse_inventory:1058,clientIp:192.168.110.21,vgroup:my_test_tx_group
2022-08-31 21:17:48.914  INFO --- [  ServerHandlerThread_1_24_500] i.s.s.s.db.store.LogStoreDataBaseDAO     : 根据xid查询全局事务, globalTransactionDO: {"applicationId":"service-order","beginTime":1661951863312,"gmtCreate":1661951863000,"gmtModified":1661951863000,"status":1,"timeout":60000,"transactionId":308351234998353920,"transactionName":"create(com.xxxxxx.esorder.frontend.request.OrderCreateRequest, java.lang.Long, java.lang.String, java.lang.String, java.lang.St","transactionServiceGroup":"my_test_tx_group","xid":"xxxxxxxxxxx:8091:308351234998353920"}
2022-08-31 21:17:48.938  INFO --- [  ServerHandlerThread_1_24_500] i.s.s.s.db.store.LogStoreDataBaseDAO     : 分支事务记录insertBranchTransactionDO, branchTransactionDO: {"applicationData":"{\"autoCommit\":false}","branchId":308351258536787968,"branchType":"AT","clientId":"service-inventory:192.168.110.21:51016","resourceId":"jdbc:mysql://xxxxxxxxxxx:3306/xxxxxxxxx","status":0,"transactionId":308351234998353920,"xid":"xxxxxxxxxxx:8091:308351234998353920"}
2022-08-31 21:17:48.942  INFO --- [  ServerHandlerThread_1_24_500] i.seata.server.coordinator.AbstractCore  : Register branch successfully, xid = xxxxxxxxxxx:8091:308351234998353920, branchId = 308351258536787968, resourceId = jdbc:mysql://xxxxxxxxxxx:3306/xxxxxxxxx ,lockKeys = t_es_warehouse_inventory:1058
2022-08-31 21:17:49.018  INFO --- [          batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : xid=xxxxxxxxxxx:8091:308351234998353920,branchType=AT,resourceId=jdbc:mysql://xxxxxxxxxxx:3306/xxxxxxxxx,lockKey=t_es_order_status_flow:63999;t_es_order_promotion:2608;t_es_order:63039;t_es_order_item:64006,clientIp:192.168.110.21,vgroup:my_test_tx_group
2022-08-31 21:17:49.019  INFO --- [  ServerHandlerThread_1_25_500] i.s.s.s.db.store.LogStoreDataBaseDAO     : 根据xid查询全局事务, globalTransactionDO: {"applicationId":"service-order","beginTime":1661951863312,"gmtCreate":1661951863000,"gmtModified":1661951863000,"status":1,"timeout":60000,"transactionId":308351234998353920,"transactionName":"create(com.xxxxxx.esorder.frontend.request.OrderCreateRequest, java.lang.Long, java.lang.String, java.lang.String, java.lang.St","transactionServiceGroup":"my_test_tx_group","xid":"xxxxxxxxxxx:8091:308351234998353920"}
2022-08-31 21:17:49.041  INFO --- [  ServerHandlerThread_1_25_500] i.s.s.s.db.store.LogStoreDataBaseDAO     : 分支事务记录insertBranchTransactionDO, branchTransactionDO: {"branchId":308351258939441153,"branchType":"AT","clientId":"service-order:192.168.110.21:50548","resourceId":"jdbc:mysql://xxxxxxxxxxx:3306/xxxxxxxxx","status":0,"transactionId":308351234998353920,"xid":"xxxxxxxxxxx:8091:308351234998353920"}
2022-08-31 21:17:49.043  INFO --- [  ServerHandlerThread_1_25_500] i.seata.server.coordinator.AbstractCore  : Register branch successfully, xid = xxxxxxxxxxx:8091:308351234998353920, branchId = 308351258939441153, resourceId = jdbc:mysql://xxxxxxxxxxx:3306/xxxxxxxxx ,lockKeys = t_es_order_status_flow:63999;t_es_order_promotion:2608;t_es_order:63039;t_es_order_item:64006
2022-08-31 21:17:49.137  INFO --- [          batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : xid=xxxxxxxxxxx:8091:308351234998353920,extraData=null,clientIp:192.168.110.21,vgroup:my_test_tx_group
2022-08-31 21:17:49.139  INFO --- [  ServerHandlerThread_1_26_500] i.s.s.s.db.store.LogStoreDataBaseDAO     : 根据xid查询全局事务, globalTransactionDO: {"applicationId":"service-order","beginTime":1661951863312,"gmtCreate":1661951863000,"gmtModified":1661951863000,"status":1,"timeout":60000,"transactionId":308351234998353920,"transactionName":"create(com.xxxxxx.esorder.frontend.request.OrderCreateRequest, java.lang.Long, java.lang.String, java.lang.String, java.lang.St","transactionServiceGroup":"my_test_tx_group","xid":"xxxxxxxxxxx:8091:308351234998353920"}
2022-08-31 21:17:49.148  INFO --- [  ServerHandlerThread_1_26_500] i.s.s.s.d.s.DataBaseSessionManager       : 开启事务, xid: xxxxxxxxxxx:8091:308351234998353920, tid: 308351234998353920, aid: service-order
2022-08-31 21:17:49.149  INFO --- [  ServerHandlerThread_1_26_500] i.s.s.s.db.store.LogStoreDataBaseDAO     : 执行全局事务,UPDATE, globalTransactionDO: {"applicationId":"service-order","beginTime":1661951863312,"status":1,"timeout":60000,"transactionId":308351234998353920,"transactionName":"create(com.xxxxxx.esorder.frontend.request.OrderCreateRequest, java.lang.Long, java.lang.String, java.lang.String, java.lang.St","transactionServiceGroup":"my_test_tx_group","xid":"xxxxxxxxxxx:8091:308351234998353920"}
2022-08-31 21:17:49.151  INFO --- [  ServerHandlerThread_1_26_500] i.s.s.s.db.store.LogStoreDataBaseDAO     : 执行全局事务,UPDATE, globalTransactionDO: {"applicationId":"service-order","beginTime":1661951863312,"status":8,"timeout":60000,"transactionId":308351234998353920,"transactionName":"create(com.xxxxxx.esorder.frontend.request.OrderCreateRequest, java.lang.Long, java.lang.String, java.lang.String, java.lang.St","transactionServiceGroup":"my_test_tx_group","xid":"xxxxxxxxxxx:8091:308351234998353920"}
2022-08-31 21:17:49.564  INFO --- [           AsyncCommitting_1_1] i.s.s.s.db.store.LogStoreDataBaseDAO     : 分支事务记录deleteBranchTransactionDO, branchTransactionDO: {"applicationData":"{\"autoCommit\":false}","branchId":308351258536787968,"branchType":"AT","clientId":"service-inventory:192.168.110.21:51016","resourceId":"jdbc:mysql://xxxxxxxxxxx:3306/xxxxxxxxx","status":0,"transactionId":308351234998353920,"xid":"xxxxxxxxxxx:8091:308351234998353920"}
2022-08-31 21:17:49.854  INFO --- [           AsyncCommitting_1_1] i.s.s.s.db.store.LogStoreDataBaseDAO     : 分支事务记录deleteBranchTransactionDO, branchTransactionDO: {"branchId":308351258939441153,"branchType":"AT","clientId":"service-order:192.168.110.21:50548","resourceId":"jdbc:mysql://xxxxxxxxxxx:3306/xxxxxxxxx","status":0,"transactionId":308351234998353920,"xid":"xxxxxxxxxxx:8091:308351234998353920"}
2022-08-31 21:17:49.860  INFO --- [           AsyncCommitting_1_1] i.s.s.s.db.store.LogStoreDataBaseDAO     : 执行全局事务,UPDATE, globalTransactionDO: {"applicationId":"service-order","beginTime":1661951863312,"status":9,"timeout":60000,"transactionId":308351234998353920,"transactionName":"create(com.xxxxxx.esorder.frontend.request.OrderCreateRequest, java.lang.Long, java.lang.String, java.lang.String, java.lang.St","transactionServiceGroup":"my_test_tx_group","xid":"xxxxxxxxxxx:8091:308351234998353920"}
2022-08-31 21:17:49.862  INFO --- [           AsyncCommitting_1_1] i.s.s.s.db.store.LogStoreDataBaseDAO     : 执行全局事务,DELETE, globalTransactionDO: {"applicationId":"service-order","beginTime":1661951863312,"status":9,"timeout":60000,"transactionId":308351234998353920,"transactionName":"create(com.xxxxxx.esorder.frontend.request.OrderCreateRequest, java.lang.Long, java.lang.String, java.lang.String, java.lang.St","transactionServiceGroup":"my_test_tx_group","xid":"xxxxxxxxxxx:8091:308351234998353920"}
2022-08-31 21:17:49.864  INFO --- [           AsyncCommitting_1_1] io.seata.server.coordinator.DefaultCore  : Committing global transaction is successfully done, xid = xxxxxxxxxxx:8091:308351234998353920.
```
失败的日志:
```
2022-08-31 21:24:41.067  INFO --- [  ServerHandlerThread_1_29_500] i.s.s.s.db.store.LogStoreDataBaseDAO     : 根据xid查询全局事务, NOT FOUND, xid: xxxxxxxxxxx:8091:5674781293195218178
2022-08-31 21:24:41.072 ERROR --- [  ServerHandlerThread_1_29_500] i.s.c.e.AbstractExceptionHandler         : Catch TransactionException while do RPC, request: xid=xxxxxxxxxxx:8091:5674781293195218178,branchType=AT,resourceId=jdbc:mysql://xxxxxxxxxxx:3306/xxxxxxxxx,lockKey=t_es_warehouse_inventory:1058
==>
io.seata.core.exception.GlobalTransactionException: Could not found global transaction xid = xxxxxxxxxxx:8091:5674781293195218178, may be has finished.
	at io.seata.server.coordinator.AbstractCore.assertGlobalSessionNotNull(AbstractCore.java:120) ~[seata-server-1.4.0.jar:na]
	at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:71) ~[seata-server-1.4.0.jar:na]
	at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:97) ~[seata-server-1.4.0.jar:na]
	at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:192) [seata-server-1.4.0.jar:na]
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184) ~[seata-server-1.4.0.jar:na]
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179) ~[seata-server-1.4.0.jar:na]
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116) ~[seata-core-1.4.0.jar:na]
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179) [seata-server-1.4.0.jar:na]
	at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136) [seata-core-1.4.0.jar:na]
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:427) [seata-server-1.4.0.jar:na]
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:124) [seata-core-1.4.0.jar:na]
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77) [seata-core-1.4.0.jar:na]
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:278) [seata-core-1.4.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
<==
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 单机部署seata，store mode选择db
2. at模式，使用spring cloud feign进行服务间调用

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  server 1.4 client 1.3
- OS : centos 7
- Others:

**Comment by a364176773** [comment]
检查异常是否被捕获,没有抛至tm端,如rm存在全局异常捕获器,rm将异常包装成了一个正常的result响应给了tm,导致seata的事务拦截器无法发现事务出现了异常,此时自行在代码中根据result中的code之类可判断业务出现异常的返回内容进行抛出异常,或者使用[Seata api](https://seata.io/zh-cn/docs/user/api.html) 进行回滚,切记api回滚必须结束调用,假设tm调用了rm1就出现错误,进行了api回滚,那么不应该让这个调用链再走到rm2去,应该直接return结束方法调用
检查是否rm服务抛出异常导致进行了熔断降级处理,如果是请参考方案上述方案进行处理
如确认无上述可能,异常明确抛出,请通过相关的xid到tc端和tm和rm检索xid的决议结果和rm注册情况,当rm分支注册时,通过xid可以检索到Register branch successfully, xid = 10.242.2.19:8094:3404997337200687005 , branchId = xxxx的日志,如果没有说明分支没有注册,如是AT或XA模式请检查数据源代理或xid传递问题,如分支已注册,那么检查决议结果,如事务提交,tm端会有类似[10.242.2.19:8094:3404997337200687005] commit status: Committed的日志,如果是回滚那么相关关键字为rollback status: Rollbacked等,如果抛出异常决议缺是commit,那么99%的情况为异常被吞,请仔细检查第一点和第二点的情况,切记不要把日志打印堆栈认为是抛出了异常堆栈!!!!
如决议结果是回滚,但是rm没注册,可在rm调用端通过Rootcontext.getXid来判断是否有值,如果无值请参考Q24
如何判断数据源是否代理,如果是AT模式请在ConnectionProxy#registry打上断点,看是否会进入,XA模式ConnectionProxyXA#commit 打断点看是否会进入,切记是不回滚的分支!!!

**Comment by a364176773** [comment]
先按照上面排查,registry失败起码server会有相关xid信息自行进行日志回溯该xid事务做了什么处理导致被删除了
Q: 22. AT 模式和 Spring @Transactional 注解连用时需要注意什么 ？
A:

@Transactional 可与 DataSourceTransactionManager 和 JTATransactionManager 连用分别表示本地事务和XA分布式事务，大家常用的是与本地事务结合。当与本地事务结合时，@Transactional和@GlobalTransaction连用，@Transactional 只能位于标注在@GlobalTransaction的同一方法层次或者位于@GlobalTransaction 标注方法的内层。这里分布式事务的概念要大于本地事务，若将 @Transactional 标注在外层会导致分布式事务空提交，当@Transactional 对应的 connection 提交时会报全局事务正在提交或者全局事务的xid不存在。

**Comment by zhangnix2** [comment]
异常是否没有抛至tm端：抛出了，我们有异常传递的机制
是否导致熔断降级：未熔断降级
tm端日志输出正常，rm端日志输出也正常。不正常的地方是在异常发生的server端日志，没有发现tm与tc通信的日志，只有rm的查询日志。
Q22 可以排除。
因为是有概率出异常不是必现
所以我觉得很可能是你说的网络通信问题
1. 服务间确实存在通信问题，但是未被观测到（我的tm和rm位于同一台机器
2. 因为在异常的情况下，没有观察到tm与tc的通信日志，所以我比较倾向与是这里的原因

**Comment by zhangnix2** [comment]
异常是否没有抛至tm端：抛出了，我们有异常传递的机制
是否导致熔断降级：未熔断降级
tm端日志输出正常，rm端日志输出也正常。不正常的地方是在异常发生的server端日志，没有发现tm与tc通信的日志，只有rm的查询日志。
Q22 可以排除。
因为是有概率出异常不是必现
所以我觉得很可能是你说的网络通信问题
1. 服务间确实存在通信问题，但是未被观测到（我的tm和rm位于同一台机器
2. 因为在异常的情况下，没有观察到tm与tc的通信日志，所以我比较倾向与是这里的原因

**Comment by a364176773** [comment]
异常的时间点立马去tc看日志这个xid的一个状态把日志放到issue来，我帮你看下

**Comment by zhangnix2** [comment]
我上面贴的失败情况的日志就是根据xid在seata-server.8091.*.log下能搜到的所有日志了
所以我很诧异为什么没有tm的交互日志

**Comment by zhangnix2** [comment]
我找到原因了。
原因是因为一台机器上的order服务启动参数seata.registry...等配置被删去了。然后项目resources下的默认配置是另一个环境的.
所以tm的事务请求就请求到另一个环境去了。
但是rm不存在这种情况，所以rm拿着另一个环境的xid自然就查不到了。
太乌龙了。
非常感谢您的时间
