### ISSUE TITLE
postgrasql使用注解@GlobalLock导致数据库插入报错Invalid column count. Cannot be less or equal to zero

### ISSUE THREAD

**Issue by 404008945** [seata/seata#4904]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
方法上加上@GlobalLock注解，执行插入操作，报错java.sql.SQLException: Invalid column count. Cannot be less or equal to zero，看代码是获取自增主键失败，数据库主键自增是没问题的
![image](https://user-images.githubusercontent.com/39762246/188253259-d7038faa-5247-490d-8754-e52cde5f222c.png)

### Ⅱ. Describe what happened

```
java.sql.SQLException: Invalid column count. Cannot be less or equal to zero
	at javax.sql.rowset.RowSetMetaDataImpl.setColumnCount(RowSetMetaDataImpl.java:128) ~[na:1.8.0_202]
	at com.sun.rowset.CachedRowSetImpl.initMetaData(CachedRowSetImpl.java:717) ~[na:1.8.0_202]
	at com.sun.rowset.CachedRowSetImpl.populate(CachedRowSetImpl.java:639) ~[na:1.8.0_202]
	at io.seata.rm.datasource.AbstractStatementProxy.getGeneratedKeys(AbstractStatementProxy.java:249) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.BaseInsertExecutor.getGeneratedKeys(BaseInsertExecutor.java:227) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.postgresql.PostgresqlInsertExecutor.getPkValues(PostgresqlInsertExecutor.java:73) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.BaseInsertExecutor.afterImage(BaseInsertExecutor.java:76) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:101) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:140) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:343) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:184) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:139) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:82) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:113) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:111) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:50) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:55) [seata-all-1.4.2.jar:1.4.2]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46) [mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) [mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50) [mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) [mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) [mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198) [mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185) [mybatis-3.4.6.jar:3.4.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) [mybatis-spring-1.3.2.jar:1.3.2]
	at com.sun.proxy.$Proxy75.insert(Unknown Source) [na:na]
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278) [mybatis-spring-1.3.2.jar:1.3.2]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:58) [mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59) [mybatis-3.4.6.jar:3.4.6]
	at com.sun.proxy.$Proxy76.insert(Unknown Source) [na:na]
	at io.seata.samples.integration.stock.service.TStockServiceImpl.decreaseStock(TStockServiceImpl.java:29) [classes/:na]
	at io.seata.samples.integration.stock.service.TStockServiceImpl$$FastClassBySpringCGLIB$$7214e2e9.invoke(<generated>) [classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) [spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at io.seata.samples.integration.stock.service.TStockServiceImpl$$EnhancerBySpringCGLIB$$573ed1d7.decreaseStock(<generated>) [classes/:na]
	at io.seata.samples.integration.stock.dubbo.StockDubboServiceImpl.decreaseStock(StockDubboServiceImpl.java:31) [classes/:na]
	at io.seata.samples.integration.stock.dubbo.StockDubboServiceImpl$$FastClassBySpringCGLIB$$f8ef8cec.invoke(<generated>) [classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) [spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) [spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$1.execute(GlobalTransactionalInterceptor.java:164) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.GlobalLockTemplate.execute(GlobalLockTemplate.java:40) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalLock(GlobalTransactionalInterceptor.java:161) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:152) [seata-all-1.4.2.jar:1.4.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) [spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) [spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at io.seata.samples.integration.stock.dubbo.StockDubboServiceImpl$$EnhancerBySpringCGLIB$$b7cf2809.decreaseStock(<generated>) [classes/:na]
	at org.apache.dubbo.common.bytecode.Wrapper0.invokeMethod(Wrapper0.java) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) [dubbo-2.7.14.jar:2.7.14]
	at io.seata.integration.dubbo.ApacheDubboTransactionPropagationFilter.invoke(ApacheDubboTransactionPropagationFilter.java:69) [seata-all-1.4.2.jar:1.4.2]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) [dubbo-2.7.14.jar:2.7.14]
	at com.alibaba.dubbo.rpc.Invoker$CompatibleInvoker.invoke(Invoker.java:55) [dubbo-2.7.14.jar:2.7.14]
	at io.seata.integration.dubbo.alibaba.AlibabaDubboTransactionPropagationFilter.invoke(AlibabaDubboTransactionPropagationFilter.java:45) [seata-all-1.4.2.jar:1.4.2]
	at com.alibaba.dubbo.rpc.Filter.invoke(Filter.java:29) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:77) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:46) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:91) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:52) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:192) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:129) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:148) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) [dubbo-2.7.14.jar:2.7.14]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) [dubbo-2.7.14.jar:2.7.14]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41) [dubbo-2.7.14.jar:2.7.14]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]
```

### Ⅲ. Describe what you expected to happen
使用@GlobalLock的情况下，预期结果为数据库正常操作并且能够发挥全局锁的作用

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 在需要加锁的方法上加上@GlobalLock注解
   
![image](https://user-images.githubusercontent.com/39762246/188253087-9349c95c-8d31-4126-b630-4806c8b87d22.png)

2. 执行插入操作
![image](https://user-images.githubusercontent.com/39762246/188253151-1d856441-b936-4bf9-9fb5-9e8b265a8b71.png)

3. 插入失败，报错Invalid column count. Cannot be less or equal to zero

### Ⅴ. Anything else we need to know?
报错方法
io.seata.rm.datasource.exec.BaseInsertExecutor#afterImage

![image](https://user-images.githubusercontent.com/39762246/188253500-43acbf18-d905-428d-9293-5ca805ca5164.png)
AT模式下是正常的，猜想跟这里有关
io.seata.rm.datasource.AbstractConnectionProxy#prepareStatement(java.lang.String)
![image](https://user-images.githubusercontent.com/39762246/188253634-4d1f2b5e-1204-4b9a-82f4-180ef4966ffa.png)

### Ⅵ. Environment:

- JDK version :1.8
- Seata version:  1.4.2
- OS :win10
- Others:
- postgis-jdbc-2.5.0

**Comment by slievrly** [comment]
@GlobalLock just for read. It is positioned to prevent dirty data from being read.
