### ISSUE TITLE
postgresql seata 1.4.2 shardingsphere4.1.1 tableMeta有误

### ISSUE THREAD

**Issue by yanghuii** [seata/seata#4927]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
表1 uc_person 
表2 uc_person_change
表3 uc_person_snapshot
我删除 uc_person 表中的数据，居然出现了表3的里面的字段
tenant_id, person_id, person_name, person_tag, person_tag_time, person_state, year 这些字段 uc_person 里面不存在的。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@3c62e552] was not registered for synchronization because synchronization is not active
JDBC Connection [io.seata.rm.datasource.ConnectionProxy@79607cba] will not be managed by Spring
==>  Preparing: **DELETE FROM uc_person WHERE (id = ? AND tenant_id = ?)**
==> Parameters: 7da7c1dcd6c158a87d170667b680ff57(String), -1(String)
2022-09-10 23:42:57.493  INFO 14740 --- [nio-9520-exec-5] ShardingSphere-SQL                       : Logic SQL: SELECT id, name, sex_code, birth_day, id_card_num, nation_code, birth_place_code, occupation, education, mobile, person_type, is_householder, is_labor_force, out_coming_home, out_coming_home_time, out_type, out_addr, vehicle, train_number, is_locality, is_valid, create_time, creater, update_time, updater, **tenant_id, person_id, person_name, person_tag, person_tag_time, person_state, year** FROM uc_person WHERE id = ?
AND tenant_id = ? FOR UPDATE
2022-09-10 23:42:57.493  INFO 14740 --- [nio-9520-exec-5] ShardingSphere-SQL                       : SQLStatement: SelectStatementContext(super=CommonSQLStatementContext(sqlStatement=org.apache.shardingsphere.sql.parser.sql.statement.dml.SelectStatement@3821195b, tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@1b69162a), tablesContext=org.apache.shardingsphere.sql.parser.binder.segment.table.TablesContext@1b69162a, projectionsContext=ProjectionsContext(startIndex=7, stopIndex=388, distinctRow=false, projections=[ColumnProjection(owner=null, name=id, alias=Optional.empty), ColumnProjection(owner=null, name=name, alias=Optional.empty), ColumnProjection(owner=null, name=sex_code, alias=Optional.empty), ColumnProjection(owner=null, name=birth_day, alias=Optional.empty), ColumnProjection(owner=null, name=id_card_num, alias=Optional.empty), ColumnProjection(owner=null, name=nation_code, alias=Optional.empty), ColumnProjection(owner=null, name=birth_place_code, alias=Optional.empty), ColumnProjection(owner=null, name=occupation, alias=Optional.empty), ColumnProjection(owner=null, name=education, alias=Optional.empty), ColumnProjection(owner=null, name=mobile, alias=Optional.empty), ColumnProjection(owner=null, name=person_type, alias=Optional.empty), ColumnProjection(owner=null, name=is_householder, alias=Optional.empty), ColumnProjection(owner=null, name=is_labor_force, alias=Optional.empty), ColumnProjection(owner=null, name=out_coming_home, alias=Optional.empty), ColumnProjection(owner=null, name=out_coming_home_time, alias=Optional.empty), ColumnProjection(owner=null, name=out_type, alias=Optional.empty), ColumnProjection(owner=null, name=out_addr, alias=Optional.empty), ColumnProjection(owner=null, name=vehicle, alias=Optional.empty), ColumnProjection(owner=null, name=train_number, alias=Optional.empty), ColumnProjection(owner=null, name=is_locality, alias=Optional.empty), ColumnProjection(owner=null, name=is_valid, alias=Optional.empty), ColumnProjection(owner=null, name=create_time, alias=Optional.empty), ColumnProjection(owner=null, name=creater, alias=Optional.empty), ColumnProjection(owner=null, name=update_time, alias=Optional.empty), ColumnProjection(owner=null, name=updater, alias=Optional.empty), ColumnProjection(owner=null, name=tenant_id, alias=Optional.empty), ColumnProjection(owner=null, name=person_id, alias=Optional.empty), ColumnProjection(owner=null, name=person_name, alias=Optional.empty), ColumnProjection(owner=null, name=person_tag, alias=Optional.empty), ColumnProjection(owner=null, name=person_tag_time, alias=Optional.empty), ColumnProjection(owner=null, name=person_state, alias=Optional.empty), ColumnProjection(owner=null, name=year, alias=Optional.empty)]), groupByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.groupby.GroupByContext@48d382b8, orderByContext=org.apache.shardingsphere.sql.parser.binder.segment.select.orderby.OrderByContext@6330b685, paginationContext=org.apache.shardingsphere.sql.parser.binder.segment.select.pagination.PaginationContext@194f83f5, containsSubquery=false)
2022-09-10 23:42:57.493  INFO 14740 --- [nio-9520-exec-5] ShardingSphere-SQL                       : Actual SQL: ds0 ::: SELECT id, name, sex_code, birth_day, id_card_num, nation_code, birth_place_code, occupation, education, mobile, person_type, is_householder, is_labor_force, out_coming_home, out_coming_home_time, out_type, out_addr, vehicle, train_number, is_locality, is_valid, create_time, creater, update_time, updater, tenant_id, person_id, person_name, person_tag, person_tag_time, person_state, year FROM uc_person_4 WHERE id = ?
AND tenant_id = ? FOR UPDATE ::: [7da7c1dcd6c158a87d170667b680ff57, -1]
2022-09-10 23:43:04.758  INFO 14740 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : channel [id: 0x257f19f7, L:/192.168.133.24:52201 - R:/192.168.133.180:18091] read idle.
2022-09-10 23:43:04.758  INFO 14740 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : channel [id: 0x722ca619, L:/192.168.133.24:52195 - R:/192.168.133.180:18091] read idle.
2022-09-10 23:43:04.758  INFO 14740 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x257f19f7, L:/192.168.133.24:52201 - R:/192.168.133.180:18091]
2022-09-10 23:43:04.758  INFO 14740 --- [ctor_TMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x722ca619, L:/192.168.133.24:52195 - R:/192.168.133.180:18091]
2022-09-10 23:43:04.758  INFO 14740 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x257f19f7, L:/192.168.133.24:52201 - R:/192.168.133.180:18091]) will closed
2022-09-10 23:43:04.758  INFO 14740 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x722ca619, L:/192.168.133.24:52195 - R:/192.168.133.180:18091]) will closed
2022-09-10 23:43:04.758  INFO 14740 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x722ca619, L:/192.168.133.24:52195 ! R:/192.168.133.180:18091]) will closed
2022-09-10 23:43:04.758  INFO 14740 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x257f19f7, L:/192.168.133.24:52201 ! R:/192.168.133.180:18091]) will closed
2022-09-10 23:43:04.758  INFO 14740 --- [ctor_TMROLE_1_1] i.s.c.r.netty.NettyClientChannelManager  : return to pool, rm channel:[id: 0x722ca619, L:/192.168.133.24:52195 ! R:/192.168.133.180:18091]
2022-09-10 23:43:04.758  INFO 14740 --- [ctor_RMROLE_1_1] i.s.c.r.netty.NettyClientChannelManager  : return to pool, rm channel:[id: 0x257f19f7, L:/192.168.133.24:52201 ! R:/192.168.133.180:18091]
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : channel valid false,channel:[id: 0x257f19f7, L:/192.168.133.24:52201 ! R:/192.168.133.180:18091]
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_TMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : channel valid false,channel:[id: 0x722ca619, L:/192.168.133.24:52195 ! R:/192.168.133.180:18091]
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x257f19f7, L:/192.168.133.24:52201 ! R:/192.168.133.180:18091]
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_TMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x722ca619, L:/192.168.133.24:52195 ! R:/192.168.133.180:18091]
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x722ca619, L:/192.168.133.24:52195 ! R:/192.168.133.180:18091]) will closed
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x722ca619, L:/192.168.133.24:52195 ! R:/192.168.133.180:18091]) will closed
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x257f19f7, L:/192.168.133.24:52201 ! R:/192.168.133.180:18091]) will closed
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : channel inactive: [id: 0x722ca619, L:/192.168.133.24:52195 ! R:/192.168.133.180:18091]
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x257f19f7, L:/192.168.133.24:52201 ! R:/192.168.133.180:18091]) will closed
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_TMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : channel valid false,channel:[id: 0x722ca619, L:/192.168.133.24:52195 ! R:/192.168.133.180:18091]
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_TMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x722ca619, L:/192.168.133.24:52195 ! R:/192.168.133.180:18091]
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x722ca619, L:/192.168.133.24:52195 ! R:/192.168.133.180:18091]) will closed
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : channel inactive: [id: 0x257f19f7, L:/192.168.133.24:52201 ! R:/192.168.133.180:18091]
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x722ca619, L:/192.168.133.24:52195 ! R:/192.168.133.180:18091]) will closed
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : channel valid false,channel:[id: 0x257f19f7, L:/192.168.133.24:52201 ! R:/192.168.133.180:18091]
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_RMROLE_1_1] i.s.core.rpc.netty.NettyPoolableFactory  : will destroy channel:[id: 0x257f19f7, L:/192.168.133.24:52201 ! R:/192.168.133.180:18091]
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x257f19f7, L:/192.168.133.24:52201 ! R:/192.168.133.180:18091]) will closed
2022-09-10 23:43:04.759  INFO 14740 --- [ctor_RMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x257f19f7, L:/192.168.133.24:52201 ! R:/192.168.133.180:18091]) will closed
2022-09-10 23:43:04.762 ERROR 14740 --- [nio-9520-exec-5] i.s.r.d.exec.AbstractDMLBaseExecutor     : execute executeAutoCommitTrue error:ERROR: column "person_id" does not exist
  位置：319

org.postgresql.util.PSQLException: ERROR: column "person_id" does not exist
  位置：319
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114) ~[postgresql-42.3.1.jar:42.3.1]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:213) ~[druid-1.2.11.jar:1.2.11]
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.getQueryResult(PreparedStatementExecutor.java:109) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.access$200(PreparedStatementExecutor.java:45) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$2.executeSQL(PreparedStatementExecutor.java:101) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$2.executeSQL(PreparedStatementExecutor.java:97) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:82) ~[sharding-core-execute-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:58) ~[sharding-core-execute-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.syncExecute(ExecutorEngine.java:97) ~[shardingsphere-executor-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.serialExecute(ExecutorEngine.java:82) ~[shardingsphere-executor-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.underlying.executor.engine.ExecutorEngine.execute(ExecutorEngine.java:76) ~[shardingsphere-executor-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:68) ~[sharding-core-execute-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.sharding.execute.sql.execute.SQLExecuteTemplate.execute(SQLExecuteTemplate.java:51) ~[sharding-core-execute-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:129) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.executeQuery(PreparedStatementExecutor.java:104) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:118) ~[sharding-jdbc-core-4.1.1.jar:4.1.1]
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.buildTableRecords(BaseTransactionalExecutor.java:362) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.DeleteExecutor.beforeImage(DeleteExecutor.java:61) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:99) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:140) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:343) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:184) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:139) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:82) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:113) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:111) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:50) [seata-all-1.4.2.jar:1.4.2]
	at io.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:55) [seata-all-1.4.2.jar:1.4.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_291]
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59) [mybatis-3.5.10.jar:3.5.10]
	at com.sun.proxy.$Proxy220.execute(Unknown Source) [na:na]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47) [mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) [mybatis-3.5.10.jar:3.5.10]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_291]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64) [mybatis-3.5.10.jar:3.5.10]
	at com.sun.proxy.$Proxy218.update(Unknown Source) [na:na]
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50) [mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) [mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) [mybatis-3.5.10.jar:3.5.10]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_291]
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49) [mybatis-3.5.10.jar:3.5.10]
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106) [mybatis-plus-extension-3.5.2.jar:3.5.2]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62) [mybatis-3.5.10.jar:3.5.10]
	at com.sun.proxy.$Proxy217.update(Unknown Source) [na:na]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194) [mybatis-3.5.10.jar:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:209) [mybatis-3.5.10.jar:3.5.10]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_291]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427) [mybatis-spring-2.0.7.jar:2.0.7]
	at com.sun.proxy.$Proxy100.delete(Unknown Source) [na:na]
	at org.mybatis.spring.SqlSessionTemplate.delete(SqlSessionTemplate.java:304) [mybatis-spring-2.0.7.jar:2.0.7]
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:69) [mybatis-plus-core-3.5.2.jar:3.5.2]
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148) [mybatis-plus-core-3.5.2.jar:3.5.2]
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89) [mybatis-plus-core-3.5.2.jar:3.5.2]
	at com.sun.proxy.$Proxy172.delete(Unknown Source) [na:na]
	at com.baomidou.mybatisplus.extension.service.IService.remove(IService.java:149) [mybatis-plus-extension-3.5.2.jar:3.5.2]
	at com.topeak.governance.service.impl.UcPersonServiceImpl.deleteByPersonId(UcPersonServiceImpl.java:125) [classes/:na]
	at com.topeak.governance.service.impl.UcPersonServiceImpl$$FastClassBySpringCGLIB$$4b790522.invoke(<generated>) [classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.3.15.jar:5.3.15]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) [spring-aop-5.3.15.jar:5.3.15]
	at com.topeak.governance.service.impl.UcPersonServiceImpl$$EnhancerBySpringCGLIB$$2eddafe0.deleteByPersonId(<generated>) [classes/:na]
```

### Ⅲ. Describe what you expected to happen
我希望删除 uc_person表时，能够正确的获取 tableMeta，而不是读取一个错误的tableMeta

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
```
pg库 一个schema  里面有三个表
uc_person 分16个表  0~15
CREATE TABLE "uc_person" (
  "id" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(100) COLLATE "pg_catalog"."default",
  "sex_code" varchar(50) COLLATE "pg_catalog"."default",
  "birth_day" timestamp(6),
  "id_card_num" varchar(30) COLLATE "pg_catalog"."default",
  "nation_code" varchar(50) COLLATE "pg_catalog"."default",
  "birth_place_code" varchar(32) COLLATE "pg_catalog"."default",
  "occupation" varchar(50) COLLATE "pg_catalog"."default",
  "education" varchar(50) COLLATE "pg_catalog"."default",
  "mobile" varchar(30) COLLATE "pg_catalog"."default",
  "person_type" varchar(50) COLLATE "pg_catalog"."default",
  "is_householder" varchar(10) COLLATE "pg_catalog"."default",
  "is_labor_force" varchar(10) COLLATE "pg_catalog"."default",
  "out_coming_home" varchar(50) COLLATE "pg_catalog"."default",
  "out_coming_home_time" timestamp(6),
  "out_type" varchar(50) COLLATE "pg_catalog"."default",
  "out_addr" varchar(255) COLLATE "pg_catalog"."default",
  "vehicle" varchar(50) COLLATE "pg_catalog"."default",
  "train_number" varchar(100) COLLATE "pg_catalog"."default",
  "is_locality" varchar(10) COLLATE "pg_catalog"."default",
  "is_valid" varchar(10) COLLATE "pg_catalog"."default",
  "create_time" timestamp(6),
  "creater" varchar(32) COLLATE "pg_catalog"."default",
  "update_time" timestamp(6),
  "updater" varchar(32) COLLATE "pg_catalog"."default",
  "tenant_id" varchar(32) COLLATE "pg_catalog"."default",
  CONSTRAINT "uc_person_pkey" PRIMARY KEY ("id")
)

uc_person_change  分64个表  0~63
CREATE TABLE "uc_person_change" (
  "id" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "person_id" varchar(255) COLLATE "pg_catalog"."default",
  "person_name" varchar(255) COLLATE "pg_catalog"."default",
  "person_tag" varchar(255) COLLATE "pg_catalog"."default",
  "person_tag_time" timestamp(6),
  "tenant_id" varchar(32) COLLATE "pg_catalog"."default",
  "person_state" varchar(255) COLLATE "pg_catalog"."default",
  "create_time" timestamp(6),
  "creater" varchar(32) COLLATE "pg_catalog"."default",
  "update_time" timestamp(6),
  "updater" varchar(32) COLLATE "pg_catalog"."default",
  CONSTRAINT "uc_person_change_pkey" PRIMARY KEY ("id")
)
uc_person_snapshot 分64个表  0~63
CREATE TABLE "governance"."uc_person_snapshot" (
  "id" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(100) COLLATE "pg_catalog"."default",
  "sex_code" varchar(50) COLLATE "pg_catalog"."default",
  "birth_day" timestamp(6),
  "id_card_num" varchar(30) COLLATE "pg_catalog"."default",
  "nation_code" varchar(50) COLLATE "pg_catalog"."default",
  "birth_place_code" varchar(32) COLLATE "pg_catalog"."default",
  "occupation" varchar(50) COLLATE "pg_catalog"."default",
  "education" varchar(50) COLLATE "pg_catalog"."default",
  "mobile" varchar(30) COLLATE "pg_catalog"."default",
  "person_type" varchar(50) COLLATE "pg_catalog"."default",
  "is_householder" varchar(10) COLLATE "pg_catalog"."default",
  "is_labor_force" varchar(10) COLLATE "pg_catalog"."default",
  "out_coming_home" varchar(50) COLLATE "pg_catalog"."default",
  "out_coming_home_time" timestamp(6),
  "out_type" varchar(50) COLLATE "pg_catalog"."default",
  "out_addr" varchar(255) COLLATE "pg_catalog"."default",
  "vehicle" varchar(50) COLLATE "pg_catalog"."default",
  "train_number" varchar(100) COLLATE "pg_catalog"."default",
  "is_locality" varchar(10) COLLATE "pg_catalog"."default",
  "is_valid" varchar(10) COLLATE "pg_catalog"."default",
  "tenant_id" varchar(32) COLLATE "pg_catalog"."default",
  "create_time" timestamp(6),
  "creater" varchar(32) COLLATE "pg_catalog"."default",
  "update_time" timestamp(6),
  "updater" varchar(32) COLLATE "pg_catalog"."default",
  "year" varchar(4) COLLATE "pg_catalog"."default",
  CONSTRAINT "uc_person_snapshot_pkey" PRIMARY KEY ("id")
);
```
```
        <spring-boot.version>2.6.3</spring-boot.version>
        <spring-cloud.version>2021.0.1</spring-cloud.version>
        <spring-cloud-alibaba.version>2021.0.1.0</spring-cloud-alibaba.version>
        <sharding-sphere.version>4.1.1</sharding-sphere.version>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>${sharding-sphere.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-transaction-base-seata-at</artifactId>
            <version>${sharding-sphere.version}</version>
        </dependency>
```

### Ⅴ. Anything else we need to know?
单独使用 seata 1.4.2 全局事务能够生效
单独使用shardingphere 4.1.1 也能正常分表
但是 seata 1.4.2 + shardingsphere 4.1.1 + seata-AT就不能正常的工作了。
### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:   1.4.2
- OS : linux
- Others: 
shardingphere 4.1.1 
postgresql 14
springboot 2.6.3
springcloud 2021.0.1
springcloud alibaba 2021.0.1.0

**Comment by a364176773** [comment]
请提供一个可复现的demo

**Comment by yanghuii** [comment]
> 请提供一个可复现的demo
问题解决了，把数据源代理设置为false就好了
