### ISSUE TITLE
io.seata.core.exception.BranchTransactionException: Failed to store branch xid = 10.131.54.229:8092:311513412066611200 branchId = 311513412360212481

### ISSUE THREAD

**Issue by lichao5188150** [seata/seata#4930]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
生产环境频繁报错  Failed to store branch xid  使用的1.4.2的AT模式  store db模式  服务注册nacos 
下面报错日志是从seata-server日志捞的

### Ⅱ. Describe what happened

io.seata.core.exception.BranchTransactionException: Failed to store branch xid = 10.131.54.229:8092:311513412066611200 branchId = 311513412360212481
	at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:83) ~[seata-server-1.3.0.jar:na]
	at io.seata.server.storage.db.session.DataBaseSessionManager.lockAndExecute(DataBaseSessionManager.java:197) ~[seata-server-1.3.0.jar:na]
	at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:275) ~[seata-server-1.3.0.jar:na]
	at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:72) ~[seata-server-1.3.0.jar:na]
	at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:97) ~[seata-server-1.3.0.jar:na]
	at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:192) [seata-server-1.3.0.jar:na]
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184) ~[seata-server-1.3.0.jar:na]
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179) ~[seata-server-1.3.0.jar:na]
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116) ~[seata-core-1.3.0.jar:na]
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179) [seata-server-1.3.0.jar:na]
	at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136) [seata-core-1.3.0.jar:na]
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:427) [seata-server-1.3.0.jar:na]
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:116) [seata-core-1.3.0.jar:na]
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77) [seata-core-1.3.0.jar:na]
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:265) [seata-core-1.3.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: io.seata.common.exception.StoreException: Duplicate entry '311513412360212481' for key 'PRIMARY'
	at io.seata.server.storage.db.store.LogStoreDataBaseDAO.insertBranchTransactionDO(LogStoreDataBaseDAO.java:329) ~[seata-server-1.3.0.jar:na]
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.writeSession(DataBaseTransactionStoreManager.java:110) ~[seata-server-1.3.0.jar:na]
	at io.seata.server.storage.db.session.DataBaseSessionManager.addBranchSession(DataBaseSessionManager.java:130) ~[seata-server-1.3.0.jar:na]
	at io.seata.server.session.AbstractSessionManager.onAddBranch(AbstractSessionManager.java:133) ~[seata-server-1.3.0.jar:na]
	at io.seata.server.session.GlobalSession.addBranch(GlobalSession.java:241) ~[seata-server-1.3.0.jar:na]
	at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:79) ~[seata-server-1.3.0.jar:na]
	... 18 common frames omitted
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '311513412360212481' for key 'PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[na:na]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[na:na]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[na:na]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[na:na]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) ~[na:na]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) ~[na:na]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347) ~[na:na]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025) ~[na:na]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:256) ~[druid-1.1.12.jar:1.1.12]
	at io.seata.server.storage.db.store.LogStoreDataBaseDAO.insertBranchTransactionDO(LogStoreDataBaseDAO.java:327) ~[seata-server-1.3.0.jar:na]
	... 23 common frames omitted

### Ⅲ. Describe what you expected to happen

 希望知道因为什么导致的 
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.42
- OS : 
- Others:

**Comment by a364176773** [comment]
升级1.5.2
