### ISSUE TITLE
RmTransactionException: Could not found global transaction, may be has finished.

### ISSUE THREAD

**Issue by zhangxi25** [seata/seata#4977]
### Ⅰ. Issue Description
使用seata的时候，A服务调用B服务，A服务上添加了@GlobalTransactional， B服务作为被调用方，方法上面添加了@Transaction注解。 
但是某些时候，事务并不能回滚，会抛出如下异常：
```java
io.seata.rm.datasource.exec.AbstractDMLBaseExecutor [146] -| execute executeAutoCommitTrue error:io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 10.*****:8091:7404225675246635483, may be has finished.] ]
java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 10.74.197.30:8091:7404225675246635483, may be has finished.] ]
        at io.seata.rm.datasource.ConnectionProxy.recognizeLockKeyConflictException(ConnectionProxy.java:161)
        at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:252)
        at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:230)
        at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:188)
        at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:333)
        at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:187)
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:141)
        at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:343)
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:184)
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:139)
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:82)
        at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:113)
        at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:111)
        at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:50)
        at io.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:55)
        at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
--
2022-10-02 10:50:52.718 |-ERROR [http-nio-8299-exec-7] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] [175] -| Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 10.****:8091:7404225675246635483, may be has finished.] ]
### The error may exist in /dao/db2/WalletMapper.java (best guess)
### The error may involve db2.WalletMapper.updateById-Inline
### The error occurred while setting parameters
### SQL: UPDATE wallet  SET corporate_id=?, wallet_type=?, balance=?,  update_time=?,   freezing_total=?, payment_total=?, refund_total=?  WHERE id=?
### Cause: java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 10.****:8091:7404225675246635483, may be has finished.] ]] with root cause
io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 10.****:8091:7404225675246635483, may be has finished.] ]
        at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:69)
        at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96)
        at io.seata.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:272)
        at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:250)
        at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:230)
        at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:188)
        at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:333)
        at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:187)
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:141)
        at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:343)
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:184)
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:139)
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:82)
```

检查发现没有其他线程同时修改相同数据。

同时在B服务有发现如下日志：
```java
2022-10-02 10:50:52.701 |-ERROR [http-nio-8299-exec-8] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] [175] -| Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLException: io.seata.core.exception.RmTransactionException: RPC Timeout
### The error may exist in dao/db2/WalletMapper.java (best guess)
### The error may involve WalletMapper.updateById-Inline
### The error occurred while setting parameters
### SQL: UPDATE wallet  SET corporate_id=?, wallet_type=?, balance=?,  update_time=?,   freezing_total=?, payment_total=?, refund_total=?  WHERE id=?
### Cause: java.sql.SQLException: io.seata.core.exception.RmTransactionException: RPC Timeout] with root cause
java.util.concurrent.TimeoutException: cost 30001 ms
        at io.seata.core.protocol.MessageFuture.get(MessageFuture.java:62)
        at io.seata.core.rpc.netty.AbstractNettyRemoting.sendSync(AbstractNettyRemoting.java:197)
        at io.seata.core.rpc.netty.AbstractNettyRemotingClient.sendSyncRequest(AbstractNettyRemotingClient.java:186)
        at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:67)
        at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96)
        at io.seata.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:272)
        at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:250)
        at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:230)
        at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:188)
        at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:333)
        at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:187)
        at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:141)
        at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:343)
```
B服务作为被调用方并没有调用其他接口，为什么还有RPC超时？？？

**Comment by a364176773** [comment]
检查异常是否被捕获,没有抛至tm端,如rm存在全局异常捕获器,rm将异常包装成了一个正常的result响应给了tm,导致seata的事务拦截器无法发现事务出现了异常,此时自行在代码中根据result中的code之类可判断业务出现异常的返回内容进行抛出异常,或者使用[Seata api](https://seata.io/zh-cn/docs/user/api.html) 进行回滚,切记api回滚必须结束调用,假设tm调用了rm1就出现错误,进行了api回滚,那么不应该让这个调用链再走到rm2去,应该直接return结束方法调用
检查是否rm服务抛出异常导致进行了熔断降级处理,如果是请参考方案上述方案进行处理
如确认无上述可能,异常明确抛出,请通过相关的xid到tc端和tm和rm检索xid的决议结果和rm注册情况,当rm分支注册时,通过xid可以检索到Register branch successfully, xid = 10.242.2.19:8094:3404997337200687005 , branchId = xxxx的日志,如果没有说明分支没有注册,如是AT或XA模式请检查数据源代理或xid传递问题,如分支已注册,那么检查决议结果,如事务提交,tm端会有类似[10.242.2.19:8094:3404997337200687005] commit status: Committed的日志,如果是回滚那么相关关键字为rollback status: Rollbacked等,如果抛出异常决议缺是commit,那么99%的情况为异常被吞,请仔细检查第一点和第二点的情况,切记不要把日志打印堆栈认为是抛出了异常堆栈!!!!
如决议结果是回滚,但是rm没注册,可在rm调用端通过Rootcontext.getXid来判断是否有值,如果无值请参考Q24
如何判断数据源是否代理,如果是AT模式请在ConnectionProxy#registry打上断点,看是否会进入,XA模式ConnectionProxyXA#commit 打断点看是否会进入,切记是不回滚的分支!!!
