### ISSUE TITLE
seata1.4.2 使用sprintboot /actuator/shutdown停服时异常，fileListener execute error

### ISSUE THREAD

**Issue by chenj321** [seata/seata#4986]
fileListener execute error, dataId :service.disableGlobalTransaction

java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.seata.config.ConfigurationCache.lambda$proxy$1(ConfigurationCache.java:108)
	at io.seata.config.Configuration$$EnhancerByCGLIB$$c361623a.getLatestConfig(<generated>)
	at io.seata.config.FileConfiguration$FileListener.onChangeEvent(FileConfiguration.java:399)
	at io.seata.config.ConfigurationChangeListener.lambda$onProcessEvent$0(ConfigurationChangeListener.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@3daf03d8 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1138)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1171)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:100)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:85)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.get(SpringBootConfigurationProvider.java:80)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider.access$300(SpringBootConfigurationProvider.java:46)
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:63)
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getLatestConfig(<generated>)
	... 14 common frames omitted

**Comment by a364176773** [comment]
不影响，由于容器被关闭而线程还在跑抛出来的，建议升级1.5.2解决此问题
