### ISSUE TITLE
seata客户端回滚一直报sql查询错误

### ISSUE THREAD

**Issue by zhhui** [seata/seata#4988]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

seata客户端服务 一直在报这么一个错.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
2022-10-11 17:43:36.689 [] ERROR [rpcDispatch_RMROLE_1_1_2] jdbc.sqlonly[144]  3045. PreparedStatement.executeQuery() SELECT * FROM bz_order_pay WHERE (pay_id,pay_sn) in ( (16183,'1122101123990441'),(?,?) ) FOR
UPDATE
java.sql.SQLException: No value specified for parameter 3
  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
  at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
  at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1020)
  at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
  at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
  at net.sf.log4jdbc.sql.jdbcapi.PreparedStatementSpy.executeQuery(PreparedStatementSpy.java:780)
  at io.seata.rm.datasource.undo.AbstractUndoExecutor.queryCurrentRecords(AbstractUndoExecutor.java:315)
  at io.seata.rm.datasource.undo.AbstractUndoExecutor.dataValidationAndGoOn(AbstractUndoExecutor.java:241)
  at io.seata.rm.datasource.undo.AbstractUndoExecutor.executeOn(AbstractUndoExecutor.java:116)
  at io.seata.rm.datasource.undo.AbstractUndoLogManager.undo(AbstractUndoLogManager.java:291)
  at io.seata.rm.datasource.DataSourceManager.branchRollback(DataSourceManager.java:152)
  at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:125)
  at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:67)
  at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:63)
  at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:116)
  at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:63)
  at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:62)
  at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35)
  at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150)
  at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.handleBranchRollback(RmBranchRollbackProcessor.java:63)
  at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.process(RmBranchRollbackProcessor.java:58)
  at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:278)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.4.1
- OS : linux 
- mysql driver: mysql-conector-java:8.0.19
- Others:

**Comment by a364176773** [comment]
先尝试升级seata版本和driver版本试试

**Comment by slievrly** [comment]
@zhhui Provide the original business SQL statements and table structure.
