### ISSUE TITLE
seata1.5.2+oracle启动报java.sql.SQLException: 关闭的语句

### ISSUE THREAD

**Issue by sixlei** [seata/seata#5030]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
如题，seata1.5.2
使用druid 1.2.6  ，ojdbc8：19.14.0.0    ，orai18n：19.14.0.0
启动时会报错java.sql.SQLException: 关闭的语句

java.sql.SQLException: 关闭的语句
	at oracle.jdbc.driver.OracleClosedStatement.exitImplicitCacheToActive(OracleClosedStatement.java:2957)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.exitImplicitCacheToActive(OraclePreparedStatementWrapper.java:1249)
	at com.alibaba.druid.util.OracleUtils.exitImplicitCacheToActive(OracleUtils.java:94)
	at com.alibaba.druid.pool.PreparedStatementPool.get(PreparedStatementPool.java:66)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:361)
	at io.seata.server.storage.db.lock.DataBaseDistributedLocker.getDistributedLockDO(DataBaseDistributedLocker.java:210)
	at io.seata.server.storage.db.lock.DataBaseDistributedLocker.acquireLock(DataBaseDistributedLocker.java:115)
	at io.seata.server.session.SessionHolder.acquireDistributedLock(SessionHolder.java:375)
	at io.seata.server.session.SessionHolder.distributedLockAndExecute(SessionHolder.java:397)
	at io.seata.server.coordinator.DefaultCoordinator.lambda$init$7(DefaultCoordinator.java:491)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

### Ⅱ. Describe what happened
经排查发现是io.seata.server.coordinator.DefaultCoordinator#init启动的定时任务去查distributed_lock表。每个线程每隔一秒查一次，每个线程执行的sql是一样的。
第一次能查询成功，后面就会报“关闭的语句”。
目前验证了用druid整合oracle循环执行一条sql，是会报上面的报错的，原因是druid使用了oracle的缓存机制，上一次执行了sql后，关闭PreparedStatement，下一次执行sql会获取到一个关闭的statement。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
验证sql为：
 @Test
    public void testQuery() throws SQLException, InterruptedException {
        DruidDataSource ds = new DruidDataSource();
        ds.setDriverClassName("oracle.jdbc.driver.OracleDriver");
        ds.setUrl("jdbc:oracle:thin:@127.0.0.1:1521/orcl");
        ds.setUsername("test");
        ds.setPassword("test");

        ds.setDriverClassLoader(ClassLoader.getSystemClassLoader());
        ds.setInitialSize(5);
        ds.setMaxActive(30);
        ds.setMinIdle(5);
        ds.setMaxWait(5000);
        ds.setTimeBetweenEvictionRunsMillis(120000);
        ds.setMinEvictableIdleTimeMillis(300000);
        ds.setTestWhileIdle(true);
        ds.setTestOnBorrow(false);
        ds.setPoolPreparedStatements(true);
        ds.setMaxPoolPreparedStatementPerConnectionSize(20);
        ds.setValidationQuery("select sysdate from dual");
        ds.setDefaultAutoCommit(true);

        while (true) {
            DruidPooledConnection connection = null;
            boolean originalAutoCommit = false;
            try {
                connection = ds.getConnection();
                originalAutoCommit = connection.getAutoCommit();
                connection.setAutoCommit(false);
                String sql = "SELECT lock_key,lock_value,expire FROM distributed_lock WHERE lock_key = ? FOR UPDATE";
                try (PreparedStatement pst = connection.prepareStatement(sql)) {
                    pst.setString(1, "AsyncCommitting");
                    ResultSet resultSet = pst.executeQuery();
                    if (resultSet.next()) {
                        DistributedLockDO distributedLock = new DistributedLockDO();
                        distributedLock.setExpireTime(resultSet.getLong(ServerTableColumnsName.DISTRIBUTED_LOCK_EXPIRE));
                        distributedLock.setLockValue(resultSet.getString(ServerTableColumnsName.DISTRIBUTED_LOCK_VALUE));
                        distributedLock.setLockKey("AsyncCommitting");
                        System.out.println(distributedLock);
                    }
                }
                connection.commit();
            } catch (Exception e) {
                LOGGER.error("execute acquire lock failure, key is: {}", "AsyncCommitting", e);
                try {
                    if (connection != null) {
                        connection.rollback();
                    }
                } catch (SQLException ex) {
                    LOGGER.warn("rollback fail because of {}", ex.getMessage(), ex);
                }
            } finally {
                try {
                    if (originalAutoCommit) {
                        connection.setAutoCommit(true);
                    }
                    IOUtil.close(connection);
                } catch (SQLException ignore) {
                }
            }

            Thread.sleep(1000);
        }

    }

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:   1.5.2
- OS :
- Others:

**Comment by a364176773** [comment]
建议这个问题反馈至druid，当其修复后我们会升级版本，你可以改为store.db.datasource=hikari放在你给seata指定的配置中心中，替换druid

**Comment by sixlei** [comment]
> 

嗯嗯。改成hikari是可以的，或者还有个解决办法是给druid数据源设置useOracleImplicitCache参数为false。这个问题应该是druid的，我会去反馈的，感谢大佬

**Comment by a364176773** [comment]
> > 
> 
> 嗯嗯。改成hikari是可以的，或者还有个解决办法是给druid数据源设置useOracleImplicitCache参数为false。这个问题应该是druid的，我会去反馈的，感谢大佬

useOracleImplicitCache为false的代码你可以提个pr给我们吗？避免有其他用户也遇到相似问题
