### ISSUE TITLE
正常启动时会偶尔报错：分支主键重复

### ISSUE THREAD

**Issue by zhuangzhuangdashen** [seata/seata#5048]
1. Seata版本：1.0.0；
2. 部署方式 K8S Pod;
3. 连接方式：K8S Service方式 指向后端8093端口
4. Server部署数量：2

复现方式：正常启动
复现几率：偶发

报错信息：
Caused by: io.seata.common.exception.StoreException: Duplicate entry '2286039159' for key 'PRIMARY'
	at io.seata.core.store.db.LogStoreDataBaseDAO.insertBranchTransactionDO(LogStoreDataBaseDAO.java:347)
	at io.seata.server.store.db.DatabaseTransactionStoreManager.writeSession(DatabaseTransactionStoreManager.java:118)
	at io.seata.server.session.db.DataBaseSessionManager.addBranchSession(DataBaseSessionManager.java:128)
	at io.seata.server.session.AbstractSessionManager.onAddBranch(AbstractSessionManager.java:133)
	at io.seata.server.session.GlobalSession.addBranch(GlobalSession.java:223)
	at io.seata.server.coordinator.DefaultCore.lambda$branchRegister$0(DefaultCore.java:91)

**Comment by a364176773** [comment]
1.0.0 启动需要添加-n 否者生产的id可能冲突
