### ISSUE TITLE
生产环境seata-server1.4.2分布式事务提交时出现io.seata.common.exception.StoreException: Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by chenj321** [seata/seata#5081]
io.seata.common.exception.StoreException: Deadlock found when trying to get lock; try restarting transaction
        at io.seata.server.storage.db.lock.LockStoreDataBaseDAO.unLock(LockStoreDataBaseDAO.java:269)
        at io.seata.server.storage.db.lock.DataBaseLocker.releaseLock(DataBaseLocker.java:103)
        at io.seata.server.storage.db.lock.DataBaseLockManager.releaseGlobalSessionLock(DataBaseLockManager.java:79)
        at io.seata.server.session.GlobalSession.clean(GlobalSession.java:230)
        at io.seata.server.session.GlobalSession.closeAndClean(GlobalSession.java:243)
        at io.seata.server.coordinator.DefaultCore.lambda$commit$0(DefaultCore.java:154)
        at io.seata.server.storage.db.session.DataBaseSessionManager.lockAndExecute(DataBaseSessionManager.java:194)
        at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:331)
        at io.seata.server.coordinator.DefaultCore.commit(DefaultCore.java:152)
        at io.seata.server.coordinator.DefaultCoordinator.doGlobalCommit(DefaultCoordinator.java:170)
        at io.seata.server.AbstractTCInboundHandler$2.execute(AbstractTCInboundHandler.java:95)
        at io.seata.server.AbstractTCInboundHandler$2.execute(AbstractTCInboundHandler.java:90)
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:124)
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:90)
        at io.seata.core.protocol.transaction.GlobalCommitRequest.handle(GlobalCommitRequest.java:34)
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:473)
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:116)
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77)
        at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:279)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/4750

**Comment by sixlei** [comment]
请问一下，这个问题后面解决了吗，是哪里发生的死锁
