### ISSUE TITLE
can not register RM,err:register TMROLE error, errMsg:null ,cost: 30019 ms

### ISSUE THREAD

**Issue by Kesling515** [seata/seata#5103]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
can not register RM client to seata server.

### Ⅱ. Describe what happened

  The exception trace:

```
2022-11-23 10:27:56.062 [main] ERROR i.s.c.r.n.NettyClientChannelManager - [reconnect,199] - 0101 can not connect to xx.xx.xx.xx:18091 cause:can not register RM,err:register TMROLE error, errMsg:null ,cost: 30019 ms
        at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:250)
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:112)
        at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:196)
        at io.seata.core.rpc.netty.TmNettyRemotingClient.init(TmNettyRemotingClient.java:198)
        at io.seata.tm.TMClient.init(TMClient.java:47)
        at io.seata.spring.annotation.GlobalTransactionScanner.initClient(GlobalTransactionScanner.java:220)
        at io.seata.spring.annotation.GlobalTransactionScanner.afterPropertiesSet(GlobalTransactionScanner.java:512)
        ......
```

### Ⅲ. Describe what you expected to happen
I deployed seata server(version:1.5.2) by docker compose, and the server started successfully. When I started my own application to register RM to seata server, but it is failed. 

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.5.2
- OS : ubuntu18

**Comment by Kesling515** [comment]
> Did you expose the port of the container?Pls show me your yml configuration.

@xingfudeshi Hi
I had changed the server port to 17091, and I exposed port 17091 and 18091 in my docker compose file.

docker-compose.yml :
```yaml
version: "3.1"  
services: 
  seata:
    image: seataio/seata-server:1.5.2
    container_name: seata
    ports:
      - "18091:18901"
      - "17091:17901"
    environment:
      - TZ=Asia/Shanghai
      - STORE_MODE=db
      - SEATA_PORT=18091
      - SEATA_IP=xx.xx.xx.xx
    volumes:
      - "./resources/application.yml:/seata-server/resources/application.yml"
```

application.yml :
```yaml
server:
  port: 17091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata

console:
  user:
    username: seata
    password: seata

seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: nacos
    nacos:
      server-addr: xx.xx.xx.xx:8848
      namespace: seata
      group: SEATA_GROUP
      username: nacos
      password: nacos
      data-id: seataServer.properties
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: nacos
    nacos:
      application: seata-server
      server-addr: xx.xx.xx.xx:8848
      group: SEATA_GROUP
      cluster: default
      username: nacos
      password: nacos

  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/api/v1/auth/login
```

**Comment by a364176773** [comment]
你可以使用telnet在client侧自行判断端口是否通,如果没有说明网络存在问题
