### ISSUE TITLE
PgSQL 执行插入具有multi pk 特性的表, 出现空指针异常

### ISSUE THREAD

**Issue by lavenwl** [seata/seata#5240]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
我使用的版本: seata-all:1.6.0
我的表为分区表: form, 其中主键为(form_id, bu_id) (bu_id为分区键, form_id为未分区前的业务主键)
分区表的form_id采用了数据库自增特性
现在对form表执行插入操作, 需要有全局事务控制, 添加了@GlobalTransaction注解
结果报空指针异常
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
2023-01-09 14:23:40.069 [TID:19c8ba3313cc470386af1f0888f3d4f2.186.16732444819040003] [http-nio-11212-exec-2] ERROR com.wditech.tpm.service.dependency.exception.GlobalExceptionHandler - 兜底异常处理: 
### Error updating database.  Cause: java.sql.SQLException: java.lang.NullPointerException
### The error may exist in com/wditech/tpm/bus/common/infrastructure/repository/mapper/FormMapper.java (best guess)
### The error may involve com.wditech.tpm.bus.common.infrastructure.repository.mapper.FormMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO form  ( bu_Id, form_no, process_id,   status_id, user_id, position_id, dept_id,   form_type_id, page_group_id, page_type_id, submit_date, amount, summary,   in_turn_user_names, in_turn_position_ids,      last_approved_date, warning_ids,  export_status,    submit_date_original )  VALUES  ( ?, ?, ?,   ?, ?, ?, ?,   ?, ?, ?, ?, ?, ?,   ?, ?,      ?, ?,  ?,    ? )
### Cause: java.sql.SQLException: java.lang.NullPointerException
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLException: java.lang.NullPointerException
### The error may exist in com/wditech/tpm/bus/common/infrastructure/repository/mapper/FormMapper.java (best guess)
### The error may involve com.wditech.tpm.bus.common.infrastructure.repository.mapper.FormMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO form  ( bu_Id, form_no, process_id,   status_id, user_id, position_id, dept_id,   form_type_id, page_group_id, page_type_id, submit_date, amount, summary,   in_turn_user_names, in_turn_position_ids,      last_approved_date, warning_ids,  export_status,    submit_date_original )  VALUES  ( ?, ?, ?,   ?, ?, ?, ?,   ?, ?, ?, ?, ?, ?,   ?, ?,      ?, ?,  ?,    ? )
### Cause: java.sql.SQLException: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	at com.sun.proxy.$Proxy169.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:60)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:96)
	at com.sun.proxy.$Proxy178.insert(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.IService.save(IService.java:59)
	at com.baomidou.mybatisplus.extension.service.IService$$FastClassBySpringCGLIB$$f8525d18.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.wditech.tpm.bus.common.infrastructure.repository.FormRepositoryImpl$$EnhancerBySpringCGLIB$$120c9300.save(<generated>)
	at com.wditech.tpm.bus.project.domain.service.impl.FormBudgetProjectServiceImpl.create(FormBudgetProjectServiceImpl.java:91)
	at com.wditech.tpm.bus.project.domain.service.impl.FormBudgetProjectServiceImpl$$FastClassBySpringCGLIB$$6700d7d9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$2.execute(GlobalTransactionalInterceptor.java:204)
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:130)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:201)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:171)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.wditech.tpm.bus.project.domain.service.impl.FormBudgetProjectServiceImpl$$EnhancerBySpringCGLIB$$efe55ce9.create(<generated>)
	at com.wditech.tpm.bus.project.application.service.impl.FormBudgetProjectApplicationServiceImpl.apply(FormBudgetProjectApplicationServiceImpl.java:194)
	at com.wditech.tpm.bus.project.application.service.impl.GeneralFormBudgetProjectApplicationService.apply(GeneralFormBudgetProjectApplicationService.java:29)
	at com.wditech.tpm.bus.project.controller.ButtonsController.apply$original$IGCXqL8Y(ButtonsController.java:83)
	at com.wditech.tpm.bus.project.controller.ButtonsController.apply$original$IGCXqL8Y$accessor$t0bmjf72(ButtonsController.java)
	at com.wditech.tpm.bus.project.controller.ButtonsController$auxiliary$QeWsl42M.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at com.wditech.tpm.bus.project.controller.ButtonsController.apply(ButtonsController.java)
	at com.wditech.tpm.bus.project.controller.ButtonsController$$FastClassBySpringCGLIB$$c3903034.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.wditech.tpm.bus.project.controller.ButtonsController$$EnhancerBySpringCGLIB$$24c69e88.apply(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.wditech.tpm.service.dependency.config.MyFilter.doFilter(MyFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke$original$7CIw0ueW(StandardHostValve.java:135)
	at org.apache.catalina.core.StandardHostValve.invoke$original$7CIw0ueW$accessor$lt3L4p5p(StandardHostValve.java)
	at org.apache.catalina.core.StandardHostValve$auxiliary$yQzq70fk.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLException: java.lang.NullPointerException
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:141)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:56)
	at io.seata.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:55)
	at jdk.internal.reflect.GeneratedMethodAccessor277.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy401.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy400.update(Unknown Source)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:54)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.update(MybatisCachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	... 113 common frames omitted
Caused by: java.lang.NullPointerException: null
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.buildTableRecords(BaseTransactionalExecutor.java:515)
	at io.seata.rm.datasource.exec.BaseInsertExecutor.afterImage(BaseInsertExecutor.java:79)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:98)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:137)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:356)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:180)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:136)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:82)
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:125)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:137)
	... 132 common frames omitted
```

### Ⅲ. Describe what you expected to happen
期望执行插入成功

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 数据表脚本
```
create table form
(
    form_id              serial,
    bu_id                smallint,
    form_no              varchar(64)
) PARTITION BY LIST (bu_id);

CREATE TABLE form_bu1 PARTITION OF form FOR VALUES in(1);
CREATE TABLE form_bu2 PARTITION OF form FOR VALUES in(2);
CREATE TABLE form_bu3 PARTITION OF form FOR VALUES in(3);

alter table form add primary key (form_id, bu_id);
```
2. 对表执行插入操作的方法添加@GlobalTransaction注解
3. 报错

### Ⅴ. Anything else we need to know?
1. 110行获取的insertColumns变量中, 不包含form_id(是否是因为我使用form_id的自增, 所以这里获取不到自增的列), 只有bu_id, form_no
![image](https://user-images.githubusercontent.com/7322393/211251858-acd8ced3-615f-4cda-b727-fecd50e068d7.png)
2. 导致513行中pkValuesMap只有一个bu_id, 而pkColumnNameList则有form_id, bu_id两个, 最终导致空指针
![image](https://user-images.githubusercontent.com/7322393/211252598-dd8354fa-44d6-4891-89b2-2cbdb87299f2.png)

### Ⅵ. Environment:

- JDK version : 
  % Java -version
  java version "11.0.16" 2022-07-19 LTS
  Java(TM) SE Runtime Environment 18.9 (build 11.0.16+11-LTS-199)
  Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.16+11-LTS-199, mixed mode)
- Seata version:  1.6.0
- OS : Mac OS 13.1 (22C65) Apple M1 Pro
- Others:

**Comment by lavenwl** [comment]
没有使用联合主键前我这个form表只有form_id一个主键, 那个时候也是用的自增特性, seata运行正常的, 前段时间对表进行了分区, pgsql对分区表的主键强制添加分区键, 所以才把主键改成(form_id, bu_id), 然后执行插入的时候, seata就报错了, 我看pgsql支持联合主键是1.6.0这个版本刚上的功能, 是不是这个feature暂未考虑自增这种情况呢?

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/211259776-4b36f009-001a-42da-9cf3-aaad0d7ccb61.png)
From the code, it appears that self-incrementing column primary keys are not supported, which is an issue to be discussed

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/5264
It was an oversight on my part and has been confirmed as a bug
