### ISSUE TITLE
 get table meta error:Failed to fetch schema of t_order_2

### ISSUE THREAD

**Issue by longkaimao** [seata/seata#5444]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata：1.6.0
ShardingSphere：5.2.0

### Ⅱ. Describe what happened

When I configure the property 'enable-auto-data-source-proxy' with true,then report the error

```
2023-03-15 09:20:17.940 ERROR 78148 --- [MetaChecker_3_1] i.s.r.d.s.s.c.AbstractTableMetaCache     : get table meta error:Failed to fetch schema of t_order_2

java.sql.SQLException: Failed to fetch schema of t_order_2
	at io.seata.rm.datasource.sql.struct.cache.MysqlTableMetaCache.fetchSchema(MysqlTableMetaCache.java:87) ~[seata-all-1.6.0.jar:1.6.0]
	at io.seata.rm.datasource.sql.struct.cache.AbstractTableMetaCache.refresh(AbstractTableMetaCache.java:82) ~[seata-all-1.6.0.jar:1.6.0]
	at io.seata.rm.datasource.DataSourceProxy.lambda$init$0(DataSourceProxy.java:127) [seata-all-1.6.0.jar:1.6.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_152]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) ~[na:1.8.0_152]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_152]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.74.Final.jar:4.1.74.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_152]
Caused by: io.seata.common.exception.ShouldNeverHappenException: Could not found any index in the table: t_order
	at io.seata.rm.datasource.sql.struct.cache.MysqlTableMetaCache.resultSetMetaToSchema(MysqlTableMetaCache.java:182) ~[seata-all-1.6.0.jar:1.6.0]
	at io.seata.rm.datasource.sql.struct.cache.MysqlTableMetaCache.fetchSchema(MysqlTableMetaCache.java:83) ~[seata-all-1.6.0.jar:1.6.0]
	... 11 common frames omitted
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?
If I configure the property 'enable-auto-data-source-proxy' with false,then the error not happen

### Ⅵ. Environment:

- JDK version :1.8.0
- Seata version:  1.6.0
- OS : window10
- Others: ShardingSphere 5.2.0

**Comment by l81893521** [comment]
what is the database and version. And please check the table  `t_other` whether exist index.

**Comment by longkaimao** [comment]
database：mysql5.7，exist index

**Comment by l81893521** [comment]
> database：mysql5.7，exist index

Can you provide the create table sql script?

**Comment by longkaimao** [comment]
```sql
CREATE TABLE `t_order_2` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT(20) NULL DEFAULT NULL COMMENT '用户id',
	`product_id` BIGINT(20) NULL DEFAULT NULL COMMENT '产品id',
	`count` INT(11) NULL DEFAULT NULL COMMENT '数量',
	`money` DECIMAL(11,0) NULL DEFAULT NULL COMMENT '金额',
	`status` INT(11) NULL DEFAULT NULL COMMENT '订单状态：0：创建中；1：已完结',
	`create_time` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
	`update_time` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
	`ts` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
	`version` INT(11) NULL DEFAULT '0' COMMENT '版本号',
	`deleted` TINYINT(1) NULL DEFAULT '0' COMMENT '逻辑删除标志',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='订单'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=142372668304261129
;
```

**Comment by longkaimao** [comment]
When I configure the following property, the error is not happened again.
`client.rm.tableMetaCheckEnable=false`

But,I do not know whether it has other problems.

**Comment by l81893521** [comment]
> ```
> CREATE TABLE `t_order_2` (
> 	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
> 	`user_id` BIGINT(20) NULL DEFAULT NULL COMMENT '用户id',
> 	`product_id` BIGINT(20) NULL DEFAULT NULL COMMENT '产品id',
> 	`count` INT(11) NULL DEFAULT NULL COMMENT '数量',
> 	`money` DECIMAL(11,0) NULL DEFAULT NULL COMMENT '金额',
> 	`status` INT(11) NULL DEFAULT NULL COMMENT '订单状态：0：创建中；1：已完结',
> 	`create_time` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
> 	`update_time` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
> 	`ts` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
> 	`version` INT(11) NULL DEFAULT '0' COMMENT '版本号',
> 	`deleted` TINYINT(1) NULL DEFAULT '0' COMMENT '逻辑删除标志',
> 	PRIMARY KEY (`id`) USING BTREE
> )
> COMMENT='订单'
> COLLATE='utf8_general_ci'
> ENGINE=InnoDB
> AUTO_INCREMENT=142372668304261129
> ;
> ```

This script do not have any index, so why cause the problem

**Comment by l81893521** [comment]
> ```sql
> CREATE TABLE `t_order_2` (
> 	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
> 	`user_id` BIGINT(20) NULL DEFAULT NULL COMMENT '用户id',
> 	`product_id` BIGINT(20) NULL DEFAULT NULL COMMENT '产品id',
> 	`count` INT(11) NULL DEFAULT NULL COMMENT '数量',
> 	`money` DECIMAL(11,0) NULL DEFAULT NULL COMMENT '金额',
> 	`status` INT(11) NULL DEFAULT NULL COMMENT '订单状态：0：创建中；1：已完结',
> 	`create_time` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
> 	`update_time` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
> 	`ts` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
> 	`version` INT(11) NULL DEFAULT '0' COMMENT '版本号',
> 	`deleted` TINYINT(1) NULL DEFAULT '0' COMMENT '逻辑删除标志',
> 	PRIMARY KEY (`id`) USING BTREE
> )
> COMMENT='订单'
> COLLATE='utf8_general_ci'
> ENGINE=InnoDB
> AUTO_INCREMENT=142372668304261129
> ;
> ```

I will check this later, please keep on touch in this issue.

**Comment by wt-better** [comment]
> 

Whether the table information is configured multiple times？

**Comment by wt-better** [comment]
> When I configure the following property, the error is not happened again. `client.rm.tableMetaCheckEnable=false`
> 
> But,I do not know whether it has other problems.

Whether the table information is configured multiple times？

**Comment by l81893521** [comment]
> When I configure the following property, the error is not happened again. `client.rm.tableMetaCheckEnable=false`
> 
> But,I do not know whether it has other problems.

Please provide the sql
