### ISSUE TITLE
关于数据库报主键重复未回滚的问题

### ISSUE THREAD

**Issue by sesame8** [seata/seata#5445]
您好，请教一下，一个事务中同时操作2个数据源，正常情况事务也正常，如果是出现往业务表中添加数据时主键重复值或[唯一索引重复异常时并不会回滚？造成第1个添加成功第2个添加失败。

![image](https://user-images.githubusercontent.com/5035551/225272004-e41a6c0a-a0eb-449a-8181-d8ef158f2fcb.png)

2023-03-15 17:25:52.129  INFO -- [nio-8090-exec-2] efaultGlobalTransaction : Begin new global transaction [169.254.110.162:8091:2612458175525326880]
2023-03-15 17:25:52.130  INFO -- [nio-8090-exec-2] o.t.h.osql.core.ObjSQL  : [Bee] insert SQL: insert into PZCSM(BH) values (?)   [values]: zxz(String)
2023-03-15 17:25:52.130  INFO -- [nio-8090-exec-2] o.t.h.osql.core.ObjSQL  : [Bee] insert SQL:  ( ExecutableSql )
insert into ZCSM(BH) values ('zxz') ;
2023-03-15 17:25:52.131  INFO -- [nio-8090-exec-2] o.t.h.o.core.BeeFactory : [Bee] ========= the current DataSource name is :ds
2023-03-15 17:25:52.171  INFO -- [nio-8090-exec-2] o.t.h.osql.core.SqlLib  : [Bee]  | <--  Affected rows: 1
2023-03-15 17:25:52.173  INFO -- [nio-8090-exec-2] o.t.h.osql.core.ObjSQL  : [Bee] insert SQL: insert into GXXX_EN(BH,MC) values (?,?)   [values]: zxz(String),zxzmc(String)
2023-03-15 17:25:52.173  INFO -- [nio-8090-exec-2] o.t.h.osql.core.ObjSQL  : [Bee] insert SQL:  ( ExecutableSql )
insert into GXXX_EN(DWBH,DWMC) values ('zxz','zxzmc') ;
2023-03-15 17:25:52.173  INFO -- [nio-8090-exec-2] o.t.h.o.core.BeeFactory : [Bee] ========= the current DataSource name is :campusds
2023-03-15 17:25:52.205 ERROR -- [nio-8090-exec-2] AbstractDMLBaseExecutor : execute executeAutoCommitTrue error:Duplicate entry 'zxz' for key 'gxxx_dw_en.PRIMARY'
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'zxz' for key 'gxxx_en.PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:241)
	at io.seata.rm.datasource.PreparedStatementProxy.lambda$executeUpdate$2(PreparedStatementProxy.java:65)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:97)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:137)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:356)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:180)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:136)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:82)
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:125)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:137)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:56)
	at io.seata.rm.datasource.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:65)
	at org.teasoft.honey.osql.core.SqlLib.modify(SqlLib.java:424)
	at org.teasoft.honey.osql.core.ObjSQL.insert(ObjSQL.java:141)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$2.execute(GlobalTransactionalInterceptor.java:204)
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:130)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:201)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:171)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.github.xiaoymin.knife4j.spring.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at prd.conf.web.PrdFilter.doFilter(PrdFilter.java:128)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:114)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at cn.dev33.satoken.filter.SaServletFilter.doFilter(SaServletFilter.java:179)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2023-03-15 17:25:52.210  WARN -- [nio-8090-exec-2] o.t.h.osql.core.SqlLib  : Duplicate entry 'zxz' for key 'gxxx_en.PRIMARY'
2023-03-15 17:25:52.230  INFO -- [nio-8090-exec-2] efaultGlobalTransaction : Suspending current transaction, xid = 169.254.110.162:8091:2612458175525326880
2023-03-15 17:25:52.230  INFO -- [nio-8090-exec-2] efaultGlobalTransaction : [169.254.110.162:8091:2612458175525326880] commit status: Committed
ppppppjava.io.BufferedInputStream@3d86f5f5
2023-03-15 17:25:52.549  INFO -- [ch_RMROLE_1_3_8] RmBranchCommitProcessor : rm client handle branch commit process:xid=169.254.110.162:8091:2612458175525326880,branchId=2612458175525326881,branchType=AT,resourceId=jdbc:mysql://192.xx:3306/db2,applicationData={"skipCheckLock":true}
2023-03-15 17:25:52.549  INFO -- [ch_RMROLE_1_3_8] i.s.r.AbstractRMHandler : Branch committing: 169.254.110.162:8091:2612458175525326880 2612458175525326881 jdbc:mysql://192.xx:3306/db2 {"skipCheckLock":true}
2023-03-15 17:25:52.549  INFO -- [ch_RMROLE_1_3_8] i.s.r.AbstractRMHandler : Branch commit result: PhaseTwo_Committed

JDK version :1.8.0
Seata version: 1.6.1
OS : window10
database：mysql8.0

**Comment by pengten** [comment]
Make sure all data sources are proxied as DataSourceProxy or DataSourceProxyXA
