### ISSUE TITLE
Using @GlobalTransactional in RM, when RM rolls back, ShouldNeverHappenException will be thrown

### ISSUE THREAD

**Issue by pengten** [seata/seata#5460]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Using @GlobalTransactional in RM, when RM rolls back, ShouldNeverHappenException will be thrown

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
io.seata.common.exception.ShouldNeverHappenException: Unknown TransactionalExecutor.Code: Unknown
	at io.seata.integration.tx.api.interceptor.handler.GlobalTransactionalInterceptorHandler.handleGlobalTransaction(GlobalTransactionalInterceptorHandler.java:272)
	at io.seata.integration.tx.api.interceptor.handler.GlobalTransactionalInterceptorHandler.doInvoke(GlobalTransactionalInterceptorHandler.java:165)
	at io.seata.integration.tx.api.interceptor.handler.AbstractProxyInvocationHandler.invoke(AbstractProxyInvocationHandler.java:35)
	at io.seata.spring.annotation.AdapterSpringSeataInterceptor.invoke(AdapterSpringSeataInterceptor.java:45)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at io.seata.samples.service.AccountService$$EnhancerBySpringCGLIB$$be2d9441.reduce(<generated>)
	at io.seata.samples.controller.AccountController.reduce(AccountController.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  2.0.0-SNAPSHOT
- OS : windows11
- Others:

**Comment by slievrly** [comment]
@pengten what is the value of `e.getCode()` ?
