### ISSUE TITLE
使用@GlobalTransactional注解，单个方法回滚失败

### ISSUE THREAD

**Issue by banmajio** [seata/seata#5466]
## 1. 出现的情况
只添加@GlobalTransactional在单表操作的接口上，不涉及远程调用，事务不回滚。并且debug到抛出异常的上一步，发现undo_log中没有数据。
## 2. 版本信息
seata-server： v1.6.1
springcloud版本的pom。
服务里使用了 dynamic-datasource-spring-boot-starter
服务的配置文件中seata的配置添加了enable-auto-data-source-proxy: false
## 3. 业务代码
这个接口中只写了一个单表的更新语句，然后抛出异常
```java
@Override
    @GlobalTransactional(rollbackFor = Exception.class)
    public void testMethod()  {

        System.out.println("********"+RootContext.getXID());
        serviceLogService.update(new LambdaUpdateWrapper<ServiceLog>()
                .set(ServiceLog::getCourseCode,"aaaaaa")
                .eq(ServiceLog::getId,6661719));

        int i = 1/0;
    }
```
## 4. 控制台信息
```java
2023-03-23 15:54:20.558  INFO 50273 --- [nio-7300-exec-1] 40 io.seata.tm.TransactionManagerHolder     : TransactionManager Singleton io.seata.tm.DefaultTransactionManager@20ebaddd
2023-03-23 15:54:20.574  INFO 50273 --- [nio-7300-exec-1] 118 i.seata.tm.api.DefaultGlobalTransaction  : Begin new global transaction [10.152.164.91:8091:3585238521828881942]
********10.152.164.91:8091:3585238521828881942
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@7fb9278] was not registered for synchronization because synchronization is not active
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@6b61ea44] will not be managed by Spring
==>  Preparing: UPDATE service_log SET course_code=? WHERE (id = ?) 
==> Parameters: aaaaaa(String), 6661719(Integer)
<==    Updates: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@7fb9278]
2023-03-23 15:54:27.289  INFO 50273 --- [nio-7300-exec-1] 199 i.seata.tm.api.DefaultGlobalTransaction  : Suspending current transaction, xid = 10.152.164.91:8091:3585238521828881942
2023-03-23 15:54:27.290  INFO 50273 --- [nio-7300-exec-1] 189 i.seata.tm.api.DefaultGlobalTransaction  : [10.152.164.91:8091:3585238521828881942] rollback status: Rollbacked
2023-03-23 15:54:27.293 ERROR 50273 --- [nio-7300-exec-1] 43 c.r.c.s.handler.GlobalExceptionHandler   : / by zero

java.lang.ArithmeticException: / by zero
	at cn.xx.xx.xx.memoriwords.service.impl.SelfTestingServiceImpl.testMethod(SelfTestingServiceImpl.java:363)
	at cn.xx.xx.xx.memoriwords.service.impl.SelfTestingServiceImpl$$FastClassBySpringCGLIB$$f95bb032.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$2.execute(GlobalTransactionalInterceptor.java:204)
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:130)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:201)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:171)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at cn.xx.xx.xx.memoriwords.service.impl.SelfTestingServiceImpl$$EnhancerBySpringCGLIB$$70f00ec9.testMethod(<generated>)
	at xx.xx.xx.xx.memoriwords.controller.SelfTestingController.testMethod(SelfTestingController.java:425)
	at xx.xx.xx.xx.memoriwords.controller.SelfTestingController$$FastClassBySpringCGLIB$$72438e2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at cn.xx.xx.xx.memoriwords.controller.SelfTestingController$$EnhancerBySpringCGLIB$$f715d4fd.testMethod(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pengten** [comment]
设置enable-auto-data-source-proxy: true

**Comment by banmajio** [comment]
> 设置enable-auto-data-source-proxy: true

当然数据也没有回滚

**Comment by banmajio** [comment]
> 具体报什么错，多数据源情况下每个数据源都需要用seata进行代理。确认下是否都代理了，可以看官网faq有讲怎么代理https://seata.io/zh-cn/docs/overview/faq.html

感谢，已经解决了，排查了一下是因为多数据源的配置没有开启seata代理。
`spring.datasource.dynamic.seata`属性设置为`true`就可以解决事务失效问题了。
`seata.enable-auto-data-source-proxy`为`false`可以解决事务执行完成undo_log表中日志未清除问题。

**Comment by slievrly** [comment]
> spring.datasource.dynamic.seata

`spring.datasource.dynamic.seata` is custom configuration?

**Comment by 18601920849** [comment]
我单数据源，单个方法@GlobalTransactional事物回滚失败，这是为什么
