### ISSUE TITLE
使用docker部署之后，一直报错Connection reset by peer异常

### ISSUE THREAD

**Issue by zhaoyunlai** [seata/seata#5499]
10:58:34.188  INFO --- [ettyServerNIOWorker_1_1_4] i.s.c.r.n.AbstractNettyRemotingServer    : 223.99.197.199:13028 to server channel inactive.
10:58:34.188  INFO --- [ettyServerNIOWorker_1_1_4] i.s.c.r.n.AbstractNettyRemotingServer    : remove channel:[id: 0x4cd39450, L:/172.17.0.6:8091 ! R:/223.99.197.199:13028]context:RpcContext{applicationId='order-service', transactionServiceGroup='seata-demo', clientId='order-service:223.99.197.199:13028', channel=[id: 0x4cd39450, L:/172.17.0.6:8091 ! R:/223.99.197.199:13028], resourceSets=null}
10:58:34.188  WARN --- [ettyServerNIOWorker_1_3_4] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
==>
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_212]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_212]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_212]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_212]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_212]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
<==

**Comment by a364176773** [comment]
检查应用所在机器与容器的网络,这与seata无关

**Comment by zsp419** [comment]
请问楼主，解决了吗，我遇到了同样的问题
