### ISSUE TITLE
mariadb 支持问题

### ISSUE THREAD

**Issue by yechangfeng47** [seata/seata#5518]
Microsoft Windows [版本 10.0.22000.527]
(c) Microsoft Corporation。保留所有权利。

D:\seata\bin>seata-server.bat
[0.002s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:D:\seata\bin\\../logs/seata_gc.log instead.
[0.036s][info   ][gc] Using G1
16:46:35,193 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:46:35,193 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
16:46:35,195 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/D:/seata/conf/logback.xml]
16:46:35,196 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
16:46:35,196 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/D:/seata/conf/logback.xml]
16:46:35,196 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/D:/seata/lib/seata-server-1.3.0.jar!/logback.xml]
16:46:35,289 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:46:35,294 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/D:/seata/conf/logback.xml]
16:46:35,294 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 1 minutes
16:46:35,296 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Adding LoggerContextListener of type [io.seata.server.logging.listener.SystemPropertyLoggerContextListener] to the object stack
16:46:35,296 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
16:46:35,296 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word clr with class [io.seata.server.logging.logback.ColorConverter]
16:46:35,296 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wex with class [io.seata.server.logging.logback.WhitespaceThrowableProxyConverter]
16:46:35,296 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wEx with class [io.seata.server.logging.logback.ExtendedWhitespaceThrowableProxyConverter]
16:46:35,298 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:46:35,300 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
16:46:35,304 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:46:35,350 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
16:46:35,352 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ALL]
16:46:35,357 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1961176822 - Archive files will be limited to [2048 MB] each.
16:46:35,359 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1961176822 - Will use gz compression
16:46:35,359 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1961176822 - Will use the pattern C:/Users/Lenovo/logs/seata/history/txc.8091.all.%d{yyyy-MM-dd}.%i.log for the active file
16:46:35,361 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6ed3ccb2 - The date pattern is 'yyyy-MM-dd' from file name pattern 'C:/Users/Lenovo/logs/seata/history/txc.8091.all.%d{yyyy-MM-dd}.%i.log.gz'.
16:46:35,361 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6ed3ccb2 - Roll-over at midnight.
16:46:35,366 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6ed3ccb2 - Setting initial period to Mon Apr 17 16:44:05 CST 2023
16:46:35,367 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1961176822 - Cleaning on start up
16:46:35,368 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:46:35,367 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - first clean up after appender initialization
16:46:35,368 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Multiple periods, i.e. 32 periods, seem to have elapsed. This is expected at application start.
16:46:35,372 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ALL] - Active log file name: C:\Users\Lenovo/logs/seata/txc.8091.all.log
16:46:35,372 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ALL] - File property is set to [C:\Users\Lenovo/logs/seata/txc.8091.all.log]
16:46:35,375 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
16:46:35,375 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [WARN]
16:46:35,377 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Removed  0 Bytes of files
16:46:35,379 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@442987331 - Archive files will be limited to [2048 MB] each.
16:46:35,379 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@442987331 - Will use gz compression
16:46:35,379 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@442987331 - Will use the pattern C:/Users/Lenovo/logs/seata/history/txc.8091.warn.%d{yyyy-MM-dd}.%i.log for the active file
16:46:35,380 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@15de0b3c - The date pattern is 'yyyy-MM-dd' from file name pattern 'C:/Users/Lenovo/logs/seata/history/txc.8091.warn.%d{yyyy-MM-dd}.%i.log.gz'.
16:46:35,380 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@15de0b3c - Roll-over at midnight.
16:46:35,380 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@15de0b3c - Setting initial period to Mon Apr 17 15:23:57 CST 2023
16:46:35,380 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@442987331 - Cleaning on start up
16:46:35,380 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - first clean up after appender initialization
16:46:35,380 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Multiple periods, i.e. 32 periods, seem to have elapsed. This is expected at application start.
16:46:35,380 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:46:35,382 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[WARN] - Active log file name: C:\Users\Lenovo/logs/seata/txc.8091.warn.log
16:46:35,382 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[WARN] - File property is set to [C:\Users\Lenovo/logs/seata/txc.8091.warn.log]
16:46:35,382 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
16:46:35,382 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ERROR]
16:46:35,385 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1217467887 - Archive files will be limited to [2048 MB] each.
16:46:35,385 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1217467887 - Will use gz compression
16:46:35,385 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1217467887 - Will use the pattern C:/Users/Lenovo/logs/seata/history/txc.8091.error.%d{yyyy-MM-dd}.%i.log for the active file
16:46:35,385 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Removed  0 Bytes of files
16:46:35,386 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3857f613 - The date pattern is 'yyyy-MM-dd' from file name pattern 'C:/Users/Lenovo/logs/seata/history/txc.8091.error.%d{yyyy-MM-dd}.%i.log.gz'.
16:46:35,386 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3857f613 - Roll-over at midnight.
16:46:35,387 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@3857f613 - Setting initial period to Mon Apr 17 16:44:05 CST 2023
16:46:35,387 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1217467887 - Cleaning on start up
16:46:35,387 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - first clean up after appender initialization
16:46:35,387 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Multiple periods, i.e. 32 periods, seem to have elapsed. This is expected at application start.
16:46:35,388 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:46:35,388 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR] - Active log file name: C:\Users\Lenovo/logs/seata/txc.8091.error.log
16:46:35,388 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR] - File property is set to [C:\Users\Lenovo/logs/seata/txc.8091.error.log]
16:46:35,389 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
16:46:35,389 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ALL] to Logger[ROOT]
16:46:35,389 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [WARN] to Logger[ROOT]
16:46:35,389 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ERROR] to Logger[ROOT]
16:46:35,389 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
16:46:35,390 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:46:35,390 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@198b6731 - Registering current configuration as safe fallback point

[2m2023-04-17 16:46:35.480[0;39m [32m INFO[0;39m [2m---[0;39m [2m[           main][0;39m [36mio.seata.config.FileConfiguration       [0;39m [2m:[0;39m The configuration file used is registry.conf
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$2 (file:/D:/seata/lib/cglib-3.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2m2023-04-17 16:46:43.646[0;39m [31mERROR[0;39m [2m---[0;39m [2m[           main][0;39m [36mcom.zaxxer.hikari.HikariConfig          [0;39m [2m:[0;39m Failed to load driver class org.mariadb.jdbc.Driver from HikariConfig class classloader jdk.internal.loader.ClassLoaders$AppClassLoader@45ff54e6
Exception in thread "main" io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.server.session.SessionManager caused by java.lang.IllegalStateException: Extension instance(definition: io.seata.common.loader.ExtensionDefinition@6cf5b018, class: interface io.seata.server.session.SessionManager)  could not be instantiated: not found service provider for : io.seata.core.store.db.DataSourceProvider caused by java.lang.IllegalStateException: Extension instance(definition: io.seata.common.loader.ExtensionDefinition@dfcc7289, class: interface io.seata.core.store.db.DataSourceProvider)  could not be instantiated: Failed to load driver class org.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:406)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:388)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:360)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:249)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:190)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:82)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.<init>(DataBaseTransactionStoreManager.java:97)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.getInstance(DataBaseTransactionStoreManager.java:83)
        at io.seata.server.storage.db.session.DataBaseSessionManager.init(DataBaseSessionManager.java:80)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:576)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:402)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:395)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:360)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:249)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:190)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:82)
        at io.seata.server.session.SessionHolder.init(SessionHolder.java:87)
        at io.seata.server.Server.main(Server.java:84)
Caused by: java.lang.RuntimeException: Failed to load driver class org.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
        at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:486)
        at io.seata.server.store.HikariDataSourceProvider.generate(HikariDataSourceProvider.java:49)
        at io.seata.core.store.db.AbstractDataSourceProvider.init(AbstractDataSourceProvider.java:71)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:576)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:402)
        ... 17 more

        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:406)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:395)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:360)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:249)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:190)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:82)
        at io.seata.server.session.SessionHolder.init(SessionHolder.java:87)
        at io.seata.server.Server.main(Server.java:84)
Caused by: io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.core.store.db.DataSourceProvider caused by java.lang.IllegalStateException: Extension instance(definition: io.seata.common.loader.ExtensionDefinition@dfcc7289, class: interface io.seata.core.store.db.DataSourceProvider)  could not be instantiated: Failed to load driver class org.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:406)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:388)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:360)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:249)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:190)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:82)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.<init>(DataBaseTransactionStoreManager.java:97)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.getInstance(DataBaseTransactionStoreManager.java:83)
        at io.seata.server.storage.db.session.DataBaseSessionManager.init(DataBaseSessionManager.java:80)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:576)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:402)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:395)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:360)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:249)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:190)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:82)
        at io.seata.server.session.SessionHolder.init(SessionHolder.java:87)
        at io.seata.server.Server.main(Server.java:84)
Caused by: java.lang.RuntimeException: Failed to load driver class org.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
        at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:486)
        at io.seata.server.store.HikariDataSourceProvider.generate(HikariDataSourceProvider.java:49)
        at io.seata.core.store.db.AbstractDataSourceProvider.init(AbstractDataSourceProvider.java:71)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:576)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:402)
        ... 17 more

D:\seata\bin>

**Comment by a364176773** [comment]
使用mysql driver或者cp将mariadb的driver放置server的libs下
