### ISSUE TITLE
求助：seata注册到nacos集群报错

### ISSUE THREAD

**Issue by white1208** [seata/seata#5525]
三台虚拟机部署nacos V2.2.2，nginx做负载均衡，之后启动seata V1.6.1 注册到Nacos负载均衡地址报错

报错日志
2023-04-21T11:53:20.224576141Z 11:53:20.222  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/api/v1/auth/login'] with []
2023-04-21T11:53:20.343802956Z 11:53:20.343  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will not secure any request
2023-04-21T11:53:20.505878117Z 11:53:20.505  INFO --- [                     main] o.a.coyote.http11.Http11NioProtocol      : Starting ProtocolHandler ["http-nio-7091"]
2023-04-21T11:53:20.624750467Z 11:53:20.623  INFO --- [                     main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 7091 (http) with context path ''
2023-04-21T11:53:20.648063899Z 11:53:20.646  INFO --- [                     main] io.seata.server.ServerApplication        : Started ServerApplication in 19.528 seconds (JVM running for 22.532)
2023-04-21T11:53:23.918500505Z 11:53:23.917  INFO --- [                     main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2023-04-21T11:53:25.071377928Z 11:53:25.061  INFO --- [                     main] i.s.core.rpc.netty.NettyServerBootstrap  : Server started, service listen port: 8091
2023-04-21T11:53:25.157767048Z 11:53:25.155  INFO --- [                     main] com.alibaba.nacos.client.naming          : initializer namespace from System Property :null
2023-04-21T11:53:25.473892360Z 11:53:25.466  INFO --- [                     main] com.alibaba.nacos.client.naming          : [BEAT] adding beat: BeatInfo{port=8091, ip='192.168.31.91', weight=1.0, serviceName='seata_group@@seata-server', cluster='default', metadata={}, scheduled=false, period=5000, stopped=false} to beat map.
2023-04-21T11:53:25.483660886Z 11:53:25.478  INFO --- [                     main] com.alibaba.nacos.client.naming          : [REGISTER-SERVICE] fad5f583-536d-4272-88b2-1f1ee8f70eb3 registering service seata_group@@seata-server with instance: Instance{instanceId='null', ip='192.168.31.91', port=8091, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='default', serviceName='null', metadata={}}
2023-04-21T11:53:25.947521762Z 11:53:25.941 ERROR --- [                     main] com.alibaba.nacos.client.naming          : [NA] failed to request
2023-04-21T11:53:25.947559584Z ==>
2023-04-21T11:53:25.947568129Z com.alibaba.nacos.api.exception.NacosException: <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
2023-04-21T11:53:25.947582745Z  at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615)
2023-04-21T11:53:25.947589292Z  at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526)
2023-04-21T11:53:25.947595666Z  at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
2023-04-21T11:53:25.947601821Z  at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493)
2023-04-21T11:53:25.947620999Z  at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:246)
2023-04-21T11:53:25.947628714Z  at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:212)
2023-04-21T11:53:25.947635204Z  at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:196)
2023-04-21T11:53:25.947641655Z  at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:112)
2023-04-21T11:53:25.947647980Z  at io.seata.core.rpc.netty.NettyServerBootstrap.start(NettyServerBootstrap.java:173)
2023-04-21T11:53:25.947654128Z  at io.seata.core.rpc.netty.AbstractNettyRemotingServer.init(AbstractNettyRemotingServer.java:56)
2023-04-21T11:53:25.947660852Z  at io.seata.core.rpc.netty.NettyRemotingServer.init(NettyRemotingServer.java:61)
2023-04-21T11:53:25.947667082Z  at io.seata.server.Server.start(Server.java:87)
2023-04-21T11:53:25.947673118Z  at io.seata.server.ServerRunner.run(ServerRunner.java:50)
2023-04-21T11:53:25.947679291Z  at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:812)
2023-04-21T11:53:25.947685930Z  at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:796)
2023-04-21T11:53:25.947692366Z  at org.springframework.boot.SpringApplication.run(SpringApplication.java:346)
2023-04-21T11:53:25.947700013Z  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365)
2023-04-21T11:53:25.947706235Z  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
2023-04-21T11:53:25.947712268Z  at io.seata.server.ServerApplication.main(ServerApplication.java:30)
2023-04-21T11:53:25.947718451Z <==
2023-04-21T11:53:25.947724519Z 
2023-04-21T11:53:26.103943887Z 11:53:26.103  INFO --- [                     main] io.seata.server.ServerRunner             : seata server started in 5450 millSeconds
2023-04-21T11:53:30.924701304Z 11:53:30.922 ERROR --- [.nacos.naming.beat.sender] com.alibaba.nacos.client.naming          : [NA] failed to request

seata配置

server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

console:
  user:
    username: seata
    password: seata

seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: nacos
    nacos:
      server-addr: 192.168.31.91:8848 # nginx负载均衡地址
      namespace: fad5f583-536d-4272-88b2-1f1ee8f70eb3
      group: seata_group
      username: nacos
      password: nacos
      data-id: seataServer.properties
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.31.91:8848
      group: seata_group
      namespace: fad5f583-536d-4272-88b2-1f1ee8f70eb3
      cluster: default
      username: nacos
      password: nacos

注册到单机的nacos就没事，集群模式+nginx就报错

**Comment by a364176773** [comment]
检查grpc端口是否代理,堆栈不清不楚如何诊断问题所在,这个问题不属于seata造成的
