### ISSUE TITLE
docker-compsoe部署。seata获取不到配置

### ISSUE THREAD

**Issue by zxk175** [seata/seata#5527]
nacos 版本 v2.2.0
seata 版本 1.6.1

docker-compose
<img width="837" alt="image" src="https://user-images.githubusercontent.com/10259995/233777360-51de5706-158e-40f4-97bd-83c869830fac.png">

nacos 配置
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/10259995/233777318-72355e8f-b150-4108-803d-073857d72cdd.png">

application.yml
<img width="831" alt="image" src="https://user-images.githubusercontent.com/10259995/233777408-4abcf401-4465-4157-b70b-33775470a11d.png">

```
2023-04-22 17:56:34 09:56:34.149  INFO --- [                     main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-04-22 17:56:34 09:56:34.151  INFO --- [                     main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.62]
2023-04-22 17:56:34 09:56:34.257  INFO --- [                     main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-04-22 17:56:34 09:56:34.259  INFO --- [                     main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1627 ms
2023-04-22 17:56:34 09:56:34.348 ERROR --- [                     main] c.a.n.client.config.impl.ClientWorker    : [fixed-nacos_standalone_mysql_8848-5aa1df41-2aa4-4707-b494-fe1d39ebb2ed] [sub-server-error]  dataId=store.db.branchTable, group=SEATA_GROUP, tenant=5aa1df41-2aa4-4707-b494-fe1d39ebb2ed, code=400
2023-04-22 17:56:34 09:56:34.353  WARN --- [                     main] c.a.n.client.config.NacosConfigService   : [fixed-nacos_standalone_mysql_8848-5aa1df41-2aa4-4707-b494-fe1d39ebb2ed] [get-config] get from server error, dataId=store.db.branchTable, group=SEATA_GROUP, tenant=5aa1df41-2aa4-4707-b494-fe1d39ebb2ed, msg=ErrCode:400, ErrMsg:http error, code=400,dataId=store.db.branchTable,group=SEATA_GROUP,tenant=5aa1df41-2aa4-4707-b494-fe1d39ebb2ed
2023-04-22 17:56:34 09:56:34.356  WARN --- [                     main] c.a.n.client.config.NacosConfigService   : [fixed-nacos_standalone_mysql_8848-5aa1df41-2aa4-4707-b494-fe1d39ebb2ed] [get-config] get snapshot ok, dataId=store.db.branchTable, group=SEATA_GROUP, tenant=5aa1df41-2aa4-4707-b494-fe1d39ebb2ed, config=
2023-04-22 17:56:34 09:56:34.363 ERROR --- [                     main] c.a.n.client.config.impl.ClientWorker    : [fixed-nacos_standalone_mysql_8848-5aa1df41-2aa4-4707-b494-fe1d39ebb2ed] [sub-server-error]  dataId=store.db.dbType, group=SEATA_GROUP, tenant=5aa1df41-2aa4-4707-b494-fe1d39ebb2ed, code=400
2023-04-22 17:56:34 09:56:34.365  WARN --- [                     main] c.a.n.client.config.NacosConfigService   : [fixed-nacos_standalone_mysql_8848-5aa1df41-2aa4-4707-b494-fe1d39ebb2ed] [get-config] get from server error, dataId=store.db.dbType, group=SEATA_GROUP, tenant=5aa1df41-2aa4-4707-b494-fe1d39ebb2ed, msg=ErrCode:400, ErrMsg:http error, code=400,dataId=store.db.dbType,group=SEATA_GROUP,tenant=5aa1df41-2aa4-4707-b494-fe1d39ebb2ed
2023-04-22 17:56:34 09:56:34.367  WARN --- [                     main] c.a.n.client.config.NacosConfigService   : [fixed-nacos_standalone_mysql_8848-5aa1df41-2aa4-4707-b494-fe1d39ebb2ed] [get-config] get snapshot ok, dataId=store.db.dbType, group=SEATA_GROUP, tenant=5aa1df41-2aa4-4707-b494-fe1d39ebb2ed, config=
2023-04-22 17:56:34 09:56:34.372  WARN --- [                     main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'branchSessionController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'branchSessionDBServiceImpl' defined in file [/seata-server/classes/io/seata/server/console/impl/db/BranchSessionDBServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.server.console.impl.db.BranchSessionDBServiceImpl$$EnhancerBySpringCGLIB$$91ac8763]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: store.db.dbType should not be blank
2023-04-22 17:56:34 09:56:34.379  INFO --- [                     main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-04-22 17:56:34 09:56:34.454  INFO --- [                     main] ConditionEvaluationReportLoggingListener : 
2023-04-22 17:56:34 
2023-04-22 17:56:34 Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-04-22 17:56:34 09:56:34.475 ERROR --- [                     main] o.s.boot.SpringApplication               : Application run failed
2023-04-22 17:56:34 ==>
2023-04-22 17:56:34 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'branchSessionController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'branchSessionDBServiceImpl' defined in file [/seata-server/classes/io/seata/server/console/impl/db/BranchSessionDBServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.server.console.impl.db.BranchSessionDBServiceImpl$$EnhancerBySpringCGLIB$$91ac8763]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: store.db.dbType should not be blank
2023-04-22 17:56:34     at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
2023-04-22 17:56:34     at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
2023-04-22 17:56:34     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
2023-04-22 17:56:34     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
2023-04-22 17:56:34     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
2023-04-22 17:56:34     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448)
2023-04-22 17:56:34     at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
2023-04-22 17:56:34     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365)
2023-04-22 17:56:34     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
2023-04-22 17:56:34     at io.seata.server.ServerApplication.main(ServerApplication.java:30)
2023-04-22 17:56:34 Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'branchSessionDBServiceImpl' defined in file [/seata-server/classes/io/seata/server/console/impl/db/BranchSessionDBServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.server.console.impl.db.BranchSessionDBServiceImpl$$EnhancerBySpringCGLIB$$91ac8763]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: store.db.dbType should not be blank
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
2023-04-22 17:56:34     at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
2023-04-22 17:56:34     at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:544)
2023-04-22 17:56:34     at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:520)
2023-04-22 17:56:34     at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:673)
2023-04-22 17:56:34     at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:228)
2023-04-22 17:56:34     at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
2023-04-22 17:56:34     at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:329)
2023-04-22 17:56:34     ... 17 common frames omitted
2023-04-22 17:56:34 Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.server.console.impl.db.BranchSessionDBServiceImpl$$EnhancerBySpringCGLIB$$91ac8763]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: store.db.dbType should not be blank
2023-04-22 17:56:34     at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
2023-04-22 17:56:34     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326)
2023-04-22 17:56:34     ... 33 common frames omitted
2023-04-22 17:56:34 Caused by: java.lang.IllegalArgumentException: store.db.dbType should not be blank
2023-04-22 17:56:34     at io.seata.server.console.impl.db.BranchSessionDBServiceImpl.<init>(BranchSessionDBServiceImpl.java:66)
2023-04-22 17:56:34     at io.seata.server.console.impl.db.BranchSessionDBServiceImpl$$EnhancerBySpringCGLIB$$91ac8763.<init>(<generated>)
2023-04-22 17:56:34     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-04-22 17:56:34     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2023-04-22 17:56:34     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2023-04-22 17:56:34     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2023-04-22 17:56:34     at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
2023-04-22 17:56:34     ... 35 common frames omitted
2023-04-22 17:56:34 <==
2023-04-22 17:56:34 
```

**Comment by a364176773** [comment]
400，估计nacos地址配置有误，自行排查一下

**Comment by zxk175** [comment]
好的。谢谢

**Comment by zxk175** [comment]
改成nacos 的docker ip 就可以了
<img width="781" alt="image" src="https://user-images.githubusercontent.com/10259995/233785583-7fec213f-7c66-463d-b3f5-1a5ff741ce51.png">

又出现了另外的问题

```
2023-04-22 20:37:57.239  INFO --- [                          main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 7091 (http) with context path ''
2023-04-22 20:37:57.281  INFO --- [                          main] io.seata.server.ServerApplication        : Started ServerApplication in 9.805 seconds (JVM running for 10.635)
2023-04-22 20:37:59.261  INFO --- [                          main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2023-04-22 20:38:00.336  INFO --- [                          main] i.s.core.rpc.netty.NettyServerBootstrap  : Server started, service listen port: 8091
2023-04-22 20:38:00.418  INFO --- [                          main] com.alibaba.nacos.client.naming          : initializer namespace from System Property :null
2023-04-22 20:38:00.934 ERROR --- [                          main] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:00 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:00 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
2023-04-22 20:38:01.014  INFO --- [                          main] com.alibaba.nacos.client.naming          : [BEAT] adding beat: BeatInfo{port=8091, ip='172.30.0.4', weight=1.0, serviceName='SEATA_GROUP@@seata-server', cluster='default', metadata={}, scheduled=false, period=5000, stopped=false} to beat map.
2023-04-22 20:38:01.039  INFO --- [                          main] com.alibaba.nacos.client.naming          : [REGISTER-SERVICE] 5aa1df41-2aa4-4707-b494-fe1d39ebb2ed registering service SEATA_GROUP@@seata-server with instance: Instance{instanceId='null', ip='172.30.0.4', port=8091, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='default', serviceName='null', metadata={}}
2023-04-22 20:38:01.088  INFO --- [                          main] io.seata.server.ServerRunner             : seata server started in 3797 millSeconds
2023-04-22 20:38:01.270 ERROR --- [ba.nacos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:00 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:00 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
2023-04-22 20:38:06.501 ERROR --- [ba.nacos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:06 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:06 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
2023-04-22 20:38:11.688 ERROR --- [ba.nacos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:11 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:11 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
2023-04-22 20:38:16.851 ERROR --- [ba.nacos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:16 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:16 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
2023-04-22 20:38:21.989 ERROR --- [ba.nacos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:21 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:21 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
2023-04-22 20:38:27.119 ERROR --- [ba.nacos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:27 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:27 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
2023-04-22 20:38:32.242 ERROR --- [ba.nacos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:32 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:32 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
2023-04-22 20:38:37.365 ERROR --- [ba.nacos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:37 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:37 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
2023-04-22 20:38:42.484 ERROR --- [ba.nacos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:42 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:42 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
2023-04-22 20:38:47.606 ERROR --- [ba.nacos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:47 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:47 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
2023-04-22 20:38:52.721 ERROR --- [ba.nacos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:52 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:52 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
2023-04-22 20:38:57.835 ERROR --- [ba.nacos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Authorization":"Bearer","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Sat, 22 Apr 2023 12:38:57 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Authorization":["Bearer"],"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Sat, 22 Apr 2023 12:38:57 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}

```

**Comment by a364176773** [comment]
user not found  应该够明确了,这个问题跟seata没什么关系,完全取决你是否熟悉docker和nacos的使用
