### ISSUE TITLE
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 539959368 - discarded

### ISSUE THREAD

**Issue by 1169119512** [seata/seata#5536]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### 一.问题描述
在docker上部署v1.4.2和latest(v1.6.1)的seata在进行访问localhost:8091时都出现了io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 539959368 - discarded
补充个小细节，在启动命令使用seata_ip注册到nacos服务列表里的seata的ip地址都还是容器内部地址172.17.0.6，这个ip地址并没有被改变

使用的启动命令：
docker run --name seata-server -p 8091:8091 -e SEATA_CONFIG_NAME=file:/seata-server/resource/registry  -e SEATA_IP=192.168.136.1  -v D:\JRE\Docker\seata_old\resource:/seata-server/resource  seataio/seata-server:1.4.2

docker run --name seata -d -p 8091:8091   -e  SEATA_IP=192.168.136.1  -v D:\JRE\Docker\seata_new\resources:/seata-server/resources seataio/seata-server:latest

错误的堆栈信息如下：
18:17:20.183  WARN --- [ttyServerNIOWorker_1_3_16] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
==>
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 539959368 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:83) ~[seata-core-1.4.2.jar:na]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
<==

### 六.环境：
1.seata:seataio/seata-server:1.4.2和seataio/seata-server:latest(1.6.1)版本。
2.docker:docker desktop: 4.18.0 (104112) 
3.操作系统：win10

**Comment by 1169119512** [comment]
> Adjusted frame length exceeds 8388608: 539959368 - discarded的堆栈只会在1.5以下打印，如果1.6还会打印请确认你的版本，至于seata_ip这个环境变量不生效高版本也已经修复了，确认你的seata到底是什么版本

上面那个错误的堆栈信息是运行1.4.2版本的，在运行latest版本的时候出现的是如下的问题：
13:21:23.430 ERROR --- [ttyServerNIOWorker_1_1_16] i.s.core.rpc.netty.v1.ProtocolV1Decoder  : Decode frame error, cause: Adjusted frame length exceeds 8388608: 539959368 - discarded

这两个版本都出现了相同的问题

**Comment by a364176773** [comment]
说明你或者有其它组件访问了7091端口导致的,7091端口不允许其他非seata私有协议的请求

**Comment by 1169119512** [comment]
> 说明你或者有其它组件访问了8091端口导致的,8091端口不允许其他非seata私有协议的请求

![image](https://user-images.githubusercontent.com/58873696/234294728-27b2295e-3ee8-4f42-b7ba-8dec413c4f9b.png)
在关闭docker内的seata服务前后端口占用如图，这应该说明了只有seata这个组件占用了这个端口，还有没有别的情况的可能性？

**Comment by a364176773** [comment]
不是占用,是有请求,大概是http请求了8091端口,如一些健康检查,8091不是一个http协议的接口,该异常也不影响seata,http请求是个短连接,也不可能随便使用netstat一下就找到

**Comment by 1169119512** [comment]
> 不是占用,是有请求,大概是http请求了8091端口,如一些健康检查,8091不是一个http协议的接口,该异常也不影响seata,http请求是个短连接,也不可能随便使用netstat一下就找到

感谢，应该是这个问题，我换了一个端口号7091就能够访问了……

我把启动命令修改成了：
docker run --name seata-server       -p 8091:8091      -p 7091:7091    -e SEATA_IP=192.168.136.1    -e SEATA_PORT=8091  -v D:\JRE\Docker\seata_new\resources:/seata-server/resources seataio/seata-server:latest
