### ISSUE TITLE
DataSourceProvider name is null

### ISSUE THREAD

**Issue by Contentsearch** [seata/seata#5546]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata 服务端版本1.5.2 
我在*windows*上部署 seata 服务端时使用db模式启动，集成了nacos(版本2.1.1，容器部署)注册和配置中心，服务端配置如下:
```yaml
server:
  port: 7091

spring:
  application:
    name: seata-server

seata:
  config:
    type: nacos
    nacos:
      server-addr: ...
      namespace: 7bc4...
      group: DEFAULT_GROUP
      username: dev
      password: ...
 #     data-id: seata-server.properties
  registry:

    type: nacos
    nacos:
      application: seata-server
      server-addr: ...
      group: DEFAULT_GROUP
      namespace: 7bc4...
      cluster: default
      username: dev
      password: ...
```

服务端nacos配置 seata-server 如下
```yaml
store.mode=db
store.db.datasource=druid
store.db.dbType=mysql
store.db.driverClassName=com.mysql.jdbc.Driver
store.db.url=jdbc:mysql://...:3306/dev-seata?rewriteBatchedStatements=true
store.db.user=...
store.db.password=...
......

```

### Ⅱ. Describe what happened

通过命令启动服务端` sh seata-server.sh -h 127.0.0.1 -p 8091 -m db` 日志输出报错 堆栈如下：
```java
11:51:37.722  INFO --- [                     main] io.seata.server.ServerApplication        : Started ServerApplication in 3.532 seconds (JVM running for 4.108)
11:51:38.332 ERROR --- [                     main] io.seata.server.ServerRunner             : seata server start error: not found service provider for : io.seata.server.session.SessionManager caused by java.lang.IllegalStateException: Extension instance(definition: io.seata.common.loader.ExtensionDefinition@835a3457, class: interface io.seata.server.session.SessionManager)  could not be instantiated: the name of service provider for [io.seata.core.store.db.DataSourceProvider] name is null
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:462)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:452)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:420)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:311)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:245)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:87)
        at io.seata.server.session.SessionHolder.init(SessionHolder.java:105)
        at io.seata.server.Server.start(Server.java:73)
        at io.seata.server.ServerRunner.run(ServerRunner.java:50)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:808)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:792)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:346)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318)
        at io.seata.server.ServerApplication.main(ServerApplication.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.IllegalArgumentException: the name of service provider for [io.seata.core.store.db.DataSourceProvider] name is null
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:415)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:311)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:245)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:87)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.<init>(DataBaseTransactionStoreManager.java:93)
        at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.getInstance(DataBaseTransactionStoreManager.java:79)
        at io.seata.server.storage.db.session.DataBaseSessionManager.init(DataBaseSessionManager.java:76)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:634)
        at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:459)
        ... 22 more

==>
```
>1. 我在issue中找到类似的问题，但是他是docker上部署的原因，我也按其方案排查未有成效；
>2. 在集成nacos之前，使用file模式是能正常启动使用的；
### Ⅲ. Describe what you expected to happen
希望能正常启动，并在nacos上找到服务

### Environment:

- JDK version(e.g. `java -version`): 1.8
- Seata client/server version:  1.5.2
- nacos : 2.1.1
- Database version: 5.7
- OS(e.g. `uname -a`): windows

**Comment by Contentsearch** [comment]
我在服务端打开日志debug，看到了原因：连接nacos dataId 404 ，所以怀疑是dataId配置错误；
于是乎我加上了配置
```yaml
data-id: seata-server
```
没有后缀，我上面贴出来的有*.properties*后缀所有404找不到
