### ISSUE TITLE
seata1.4.2/1.6.0使用postgresql15.2数据库的时候报错

### ISSUE THREAD

**Issue by duhongx** [seata/seata#5572]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

> 将nacos从1.4.2升级到2.2.2，nacos2.2.2使用postgresql15.2启动正常，顺便将seata的数据从mysql迁移到postgresql15.2，seata1.4.2启动报错。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
使用seata1.4.2将mysql更换成postgresql15.2启动，日志提示postgresql链接异常
02:49:09.780 ERROR --- [ionPool-Create-2024240125] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:postgresql://192.168.1.34:5432/juyijt?tcpKeepAlive=true&reWriteBatchedInserts=true, errorCode 0, state 08004
==>
org.postgresql.util.PSQLException: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:614) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.Driver.makeConnection(Driver.java:450) ~[postgresql-42.1.4.jar:42.1.4]
	at org.postgresql.Driver.connect(Driver.java:252) ~[postgresql-42.1.4.jar:42.1.4]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644) ~[druid-1.1.23.jar:1.1.23]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1710) ~[druid-1.1.23.jar:1.1.23]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2774) ~[druid-1.1.23.jar:1.1.23]
<==

使用postgresql的工具用seata账号登录juyijt这个database都可以正常访问
[postgres@cicd data]$ psql -U seata -d juyijt -h 192.168.1.34 -p 5432
Password for user seata: 
Type "help" for help.

df_his=> \d
                     List of relations
 Schema |            Name            |   Type   |  Owner   
--------+----------------------------+----------+----------
 seata  | branch_table               | table    | seata
 seata  | distributed_lock           | table    | seata
 seata  | global_table               | table    | seata
 seata  | lock_table                 | table    | seata
(6 rows)

推测为seata1.4.2引用的postgresql驱动版本太低，换成seata1.6.0再次启动还是这个错误。

重新搭建了一套postgresql13.3，将seata相关的表导入，seata1.4.2链接postgresql13.3启动成功。

```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 1.8.0_372
- Seata client/server version:  seata1.4.0/seata1.6.0
- Database version:  postgresql15.2/postgresql13.3
- OS(e.g. `uname -a`):  Linux pg-1 5.14.0-162.22.2.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 17:01:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

- Others:

**Comment by a364176773** [comment]
尝试手动替换driver？

**Comment by duhongx** [comment]
直接基于dockerhub上的镜像，放在kubernetes里运行的。我去看看seata-docker里的Dockerfile重做一下镜像试试。
谢谢！

**Comment by a364176773** [comment]
如果升级driver即可，欢迎提交相关pr来解决问题，升级driver需要考虑向下兼容
