### ISSUE TITLE
TCC 模式，微服务数据库使用sqlserver时，启动报错。切换成mysql则正常启动。

### ISSUE THREAD

**Issue by Davis966** [seata/seata#5574]
2023-05-13 16:45:57 ERROR lidas-server-test Druid-ConnectionPool-Create-2021254060 com.alibaba.druid.pool.DruidDataSource create connection SQLException, url: jdbc:sqlserver://120.79.88.173:1433;DataBaseName=lidas, errorCode 0, state null
java.sql.SQLException: validateConnection false
	at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1418)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1733)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2801)
Caused by: java.lang.NullPointerException: null
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.ensureSQLSyntax(SQLServerStatement.java:804)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:848)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:793)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7417)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3488)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:237)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute$original$AiAfX73u(SQLServerStatement.java:766)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute$original$AiAfX73u$accessor$g59WBBgZ(SQLServerStatement.java)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$auxiliary$6wScfFfP.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:3010)
	at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2484)
	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:188)
	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:3008)
	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:147)
	at com.alibaba.druid.pool.vendor.MSSQLValidConnectionChecker.isValidConnection(MSSQLValidConnectionChecker.java:50)
	at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1398)
	... 2 common frames omitted

**Comment by a364176773** [comment]
完整堆栈发出来，这个堆栈明显少了部分信息
