### ISSUE TITLE
1.5.2版本 AT模式，删除再批量插入数据，seata提示主键冲突

### ISSUE THREAD

**Issue by aacopy** [seata/seata#5587]
@Override
    @GlobalTransactional
    public void change(Integer num) {
        List<Bb> bbs = selectList(new EntityWrapper<Bb>().eq("pid", "af0ddb25-53be-4e79-9245-dba7c838c5cb"));
        delete(new EntityWrapper<Bb>().eq("pid", "af0ddb25-53be-4e79-9245-dba7c838c5cb"));
        Integer now = selectCount(new EntityWrapper<Bb>().eq("pid", "af0ddb25-53be-4e79-9245-dba7c838c5cb"));
        System.out.println(now); // 这里已经为0
        insertBatch(bbs);
    }

相关日志：

[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.575 DEBUG 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.core.context.RootContext 118 bind 192.168.10.35:8091:8691753641158784751
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.575 DEBUG 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.integration.http.TransactionPropagationInterceptor 43 xid in RootContext[192.168.10.35:8091:8691753641158784751] xid in HttpContext[192.168.10.35:8091:8691753641158784751]
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.591 INFO 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.tm.TransactionManagerHolder 40 TransactionManager Singleton io.seata.tm.DefaultTransactionManager@32381f88
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.592 DEBUG 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.tm.api.DefaultGlobalTransaction 95 Ignore Begin(): just involved in global transaction [192.168.10.35:8091:8691753641158784751]
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@e568d88] was not registered for synchronization because synchronization is not active
JDBC Connection [io.seata.rm.datasource.ConnectionProxy@6571f2d7] will not be managed by Spring
==>  Preparing: SELECT id AS id,num,pid,`name` FROM bb WHERE (pid = ?) 
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.679 DEBUG 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader 537 The same extension io.seata.sqlparser.druid.mysql.MySQLOperateRecognizerHolder has already been loaded, skipped
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.679 DEBUG 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader 537 The same extension io.seata.sqlparser.druid.oracle.OracleOperateRecognizerHolder has already been loaded, skipped
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.680 DEBUG 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader 537 The same extension io.seata.sqlparser.druid.postgresql.PostgresqlOperateRecognizerHolder has already been loaded, skipped
==> Parameters: af0ddb25-53be-4e79-9245-dba7c838c5cb(String)
<==    Columns: id, num, pid, name
<==        Row: 4, 1459821919, af0ddb25-53be-4e79-9245-dba7c838c5cb, ef0abc9b-d16d-427e-90e3-1a9e3be6fa61
<==        Row: 6, 346696175, af0ddb25-53be-4e79-9245-dba7c838c5cb, 46ec02f1-977a-4c27-9f02-13ca60678ecd
<==      Total: 2
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@e568d88]
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@387d4c2c] was not registered for synchronization because synchronization is not active
JDBC Connection [io.seata.rm.datasource.ConnectionProxy@6c138e20] will not be managed by Spring
==>  Preparing: DELETE FROM bb WHERE (pid = ?) 
==> Parameters: af0ddb25-53be-4e79-9245-dba7c838c5cb(String)
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.721 INFO 23236 [http-nio-8090-exec-1] [TID: N/A] com.alibaba.nacos.client.config.impl.ClientWorker 197 [fixed-192.168.10.35_8848-06166fdf-7416-4744-b8d6-8b87c52ae9f8] [subscribe] client.rm.lock.retryInterval+DEFAULT_GROUP+06166fdf-7416-4744-b8d6-8b87c52ae9f8
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.721 INFO 23236 [http-nio-8090-exec-1] [TID: N/A] com.alibaba.nacos.client.config.impl.CacheData 92 [fixed-192.168.10.35_8848-06166fdf-7416-4744-b8d6-8b87c52ae9f8] [add-listener] ok, tenant=06166fdf-7416-4744-b8d6-8b87c52ae9f8, dataId=client.rm.lock.retryInterval, group=DEFAULT_GROUP, cnt=1
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.721 INFO 23236 [http-nio-8090-exec-1] [TID: N/A] com.alibaba.nacos.client.config.impl.CacheData 92 [fixed-192.168.10.35_8848-06166fdf-7416-4744-b8d6-8b87c52ae9f8] [add-listener] ok, tenant=06166fdf-7416-4744-b8d6-8b87c52ae9f8, dataId=client.rm.lock.retryInterval, group=DEFAULT_GROUP, cnt=2
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.722 INFO 23236 [http-nio-8090-exec-1] [TID: N/A] com.alibaba.nacos.client.config.impl.ClientWorker 197 [fixed-192.168.10.35_8848-06166fdf-7416-4744-b8d6-8b87c52ae9f8] [subscribe] client.rm.lock.retryTimes+DEFAULT_GROUP+06166fdf-7416-4744-b8d6-8b87c52ae9f8
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.722 INFO 23236 [http-nio-8090-exec-1] [TID: N/A] com.alibaba.nacos.client.config.impl.CacheData 92 [fixed-192.168.10.35_8848-06166fdf-7416-4744-b8d6-8b87c52ae9f8] [add-listener] ok, tenant=06166fdf-7416-4744-b8d6-8b87c52ae9f8, dataId=client.rm.lock.retryTimes, group=DEFAULT_GROUP, cnt=1
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.722 INFO 23236 [http-nio-8090-exec-1] [TID: N/A] com.alibaba.nacos.client.config.impl.CacheData 92 [fixed-192.168.10.35_8848-06166fdf-7416-4744-b8d6-8b87c52ae9f8] [add-listener] ok, tenant=06166fdf-7416-4744-b8d6-8b87c52ae9f8, dataId=client.rm.lock.retryTimes, group=DEFAULT_GROUP, cnt=2
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.807 DEBUG 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader 537 The same extension io.seata.discovery.loadbalance.RoundRobinLoadBalance has already been loaded, skipped
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.808 DEBUG 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader 537 The same extension io.seata.discovery.loadbalance.RandomLoadBalance has already been loaded, skipped
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.808 DEBUG 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader 537 The same extension io.seata.discovery.loadbalance.ConsistentHashLoadBalance has already been loaded, skipped
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.808 DEBUG 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader 537 The same extension io.seata.discovery.loadbalance.LeastActiveLoadBalance has already been loaded, skipped
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.862 DEBUG 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.rm.datasource.undo.AbstractUndoLogManager 235 Flushing UNDO LOG: {"@class":"io.seata.rm.datasource.undo.BranchUndoLog","xid":"192.168.10.35:8091:8691753641158784751","branchId":8691753641158784759,"sqlUndoLogs":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.undo.SQLUndoLog","sqlType":"DELETE","tableName":"bb","beforeImage":{"@class":"io.seata.rm.datasource.sql.struct.TableRecords","tableName":"bb","rows":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.sql.struct.Row","fields":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"num","keyType":"NULL","type":4,"value":1459821919},{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"name","keyType":"NULL","type":12,"value":"ef0abc9b-d16d-427e-90e3-1a9e3be6fa61"},{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"pid","keyType":"NULL","type":12,"value":"af0ddb25-53be-4e79-9245-dba7c838c5cb"},{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"id","keyType":"PRIMARY_KEY","type":-5,"value":["java.lang.Long",4]}]]},{"@class":"io.seata.rm.datasource.sql.struct.Row","fields":["java.util.ArrayList",[{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"num","keyType":"NULL","type":4,"value":346696175},{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"name","keyType":"NULL","type":12,"value":"46ec02f1-977a-4c27-9f02-13ca60678ecd"},{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"pid","keyType":"NULL","type":12,"value":"af0ddb25-53be-4e79-9245-dba7c838c5cb"},{"@class":"io.seata.rm.datasource.sql.struct.Field","name":"id","keyType":"PRIMARY_KEY","type":-5,"value":["java.lang.Long",6]}]]}]]},"afterImage":{"@class":"io.seata.rm.datasource.sql.struct.TableRecords$EmptyTableRecords","tableName":"bb","rows":["java.util.ArrayList",[]]}}]]}
<==    Updates: 2
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@387d4c2c]
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@45e9078] was not registered for synchronization because synchronization is not active
JDBC Connection [io.seata.rm.datasource.ConnectionProxy@7c1edc20] will not be managed by Spring
==>  Preparing: SELECT COUNT(1) FROM bb WHERE (pid = ?) 
==> Parameters: af0ddb25-53be-4e79-9245-dba7c838c5cb(String)
<==    Columns: COUNT(1)
<==        Row: 0
<==      Total: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@45e9078]
0
JDBC Connection [io.seata.rm.datasource.ConnectionProxy@7d19b17] will not be managed by Spring
==>  Preparing: INSERT INTO bb ( id, num, pid, `name` ) VALUES ( ?, ?, ?, ? ) 
==> Parameters: 4(Long), 1459821919(Integer), af0ddb25-53be-4e79-9245-dba7c838c5cb(String), ef0abc9b-d16d-427e-90e3-1a9e3be6fa61(String)
==> Parameters: 6(Long), 346696175(Integer), af0ddb25-53be-4e79-9245-dba7c838c5cb(String), 46ec02f1-977a-4c27-9f02-13ca60678ecd(String)
[quectel-seata-b:10.66.38.40:8090] 2023-05-18 14:41:20.934 ERROR 23236 [http-nio-8090-exec-1] [TID: N/A] io.seata.rm.datasource.exec.AbstractDMLBaseExecutor 149 execute executeAutoCommitTrue error:io.seata.core.exception.RmTransactionException: Response[ TransactionException[branch register request failed. xid=192.168.10.35:8091:8691753641158784751, msg=Duplicate entry 'jdbc:mysql://192.168.25.216:3306/seata-test1^^^bb^^^6' for key 'PRIMARY'] ]

java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[branch register request failed. xid=192.168.10.35:8091:8691753641158784751, msg=Duplicate entry 'jdbc:mysql://192.168.25.216:3306/seata-test1^^^bb^^^6' for key 'PRIMARY'] ]
	at io.seata.rm.datasource.ConnectionProxy.recognizeLockKeyConflictException(ConnectionProxy.java:161)
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:252)
	at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:230)
	at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:188)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:343)
	at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:187)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:144)
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:355)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:186)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:142)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:82)
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:126)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:126)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:54)
	at io.seata.rm.datasource.StatementProxy.executeBatch(StatementProxy.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:78)
	at com.sun.proxy.$Proxy197.executeBatch(Unknown Source)
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:122)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122)
	at org.apache.ibatis.executor.CachingExecutor.flushStatements(CachingExecutor.java:114)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.flushStatements(DefaultSqlSession.java:253)
	at com.baomidou.mybatisplus.service.impl.ServiceImpl.insertBatch(ServiceImpl.java:135)
	at com.baomidou.mybatisplus.service.impl.ServiceImpl.insertBatch(ServiceImpl.java:110)
	at cn.aacopy.demo.quectelseatab.service.impl.BbServiceImpl.change(BbServiceImpl.java:35)
	at cn.aacopy.demo.quectelseatab.service.impl.BbServiceImpl$$FastClassBySpringCGLIB$$a0ca4b44.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$2.execute(GlobalTransactionalInterceptor.java:205)
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:127)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:202)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:172)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at cn.aacopy.demo.quectelseatab.service.impl.BbServiceImpl$$EnhancerBySpringCGLIB$$68a078ee.change(<generated>)
	at cn.aacopy.demo.quectelseatab.controller.BbController.change(BbController.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.quectel.web.cloud.ribbon.filter.LbIsolationFilter.doFilterInternal(LbIsolationFilter.java:43)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at com.quectel.web.cloud.common.security.filter.ServerAccessInterceptor.doFilter(ServerAccessInterceptor.java:46)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.seata.core.exception.RmTransactionException: Response[ TransactionException[branch register request failed. xid=192.168.10.35:8091:8691753641158784751, msg=Duplicate entry 'jdbc:mysql://192.168.25.216:3306/seata-test1^^^bb^^^6' for key 'PRIMARY'] ]
	at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:69)
	at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96)
	at io.seata.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:273)
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:250)
	... 144 common frames omitted

**Comment by a364176773** [comment]
升级1.6.1

**Comment by aacopy** [comment]
除了升级还有其它方式吗，比如补丁文件啥的
我就是先用的1.6.1，然后遇到关键字冲突，同一个事务中更新数据后，再查询还是旧数据的 这些问题，然后把版本降到1.5.2的
