### ISSUE TITLE
Possible conflict between asyncCommitting thread and retryCommitting thread

### ISSUE THREAD

**Issue by a364176773** [seata/seata#5605]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
asyncCommitting 线程将所有异步提交的事务进行提交,此时会删除undolog->update status为committed->delete global session
而retryCommitting 会读取到commtting,retrycommitting,committed,假设在上面线程运行到修改事务状态为committed时 改retry线程读取到这条数据,并且对他进行commit补偿,就可能出现delete globalsession和update globalsession并发,或者前者再后者之后才触发的问题(线程调度),导致retry committing线程运行报错,虽然对事务一致性,和进程没有影响,但是可能造成一些不必要的误解
```
21:50:01.418 ERROR --- [      AsyncCommitting_1_1] [server.coordinator.DefaultCore] [               error]  [192.168.31.181:8091:1549633538246713498] : Committing branch transaction exception:retrying=true, BR:1549633538246713500/1549633538246713498, Global commit continue
21:50:01.419  INFO --- [      AsyncCommitting_1_1] [.core.rpc.netty.ChannelManager] [          getChannel]  [192.168.31.181:8091:1549633538246713498] : Choose [id: 0xf298d649, L:/192.168.31.181:8091 - R:/192.168.31.181:58141] on the same IP[192.168.31.181] as alternative of product-service:192.168.31.181:57527
21:50:01.421  INFO --- [     batchLoggerPrint_1_1] [ocessor.server.BatchLogHandler] [                 run]  [] : receive msg[single]: BranchCommitResponse{xid='192.168.31.181:8091:1549633538246713498', branchId=1549633538246713502, branchStatus=PhaseTwo_Committed, resultCode=Success, msg='null'}, clientIp: 192.168.31.181, vgroup: default_tx_group
21:50:01.432  INFO --- [      AsyncCommitting_1_1] [server.coordinator.DefaultCore] [bda$doGlobalCommit$1]  [192.168.31.181:8091:1549633538246713498] : Commit branch transaction successfully, xid = 192.168.31.181:8091:1549633538246713498 branchId = 1549633538246713502
21:50:05.882  INFO --- [      AsyncCommitting_1_1] [.core.rpc.netty.ChannelManager] [          getChannel]  [192.168.31.181:8091:1549633538246713498] : Choose [id: 0xf298d649, L:/192.168.31.181:8091 - R:/192.168.31.181:58141] on the same IP[192.168.31.181] as alternative of product-service:192.168.31.181:57527
21:50:05.889  INFO --- [     batchLoggerPrint_1_1] [ocessor.server.BatchLogHandler] [                 run]  [] : receive msg[single]: BranchCommitResponse{xid='192.168.31.181:8091:1549633538246713498', branchId=1549633538246713500, branchStatus=PhaseTwo_Committed, resultCode=Success, msg='null'}, clientIp: 192.168.31.181, vgroup: default_tx_group
21:50:05.900  INFO --- [      AsyncCommitting_1_1] [server.coordinator.DefaultCore] [bda$doGlobalCommit$1]  [192.168.31.181:8091:1549633538246713498] : Commit branch transaction successfully, xid = 192.168.31.181:8091:1549633538246713498 branchId = 1549633538246713500
21:50:05.925 ERROR --- [      RetryCommitting_1_1] [a.server.session.SessionHelper] [    lambda$forEach$0]  [192.168.31.181:8091:1549633538246713498] : handle global session failed: 192.168.31.181:8091:1549633538246713498
==>
io.seata.common.exception.StoreException: updateGlobalSessionStatus failed.
	at io.seata.server.storage.db.session.DataBaseSessionManager.updateGlobalSessionStatus(DataBaseSessionManager.java:78)
	at io.seata.server.session.GlobalSession.changeGlobalStatus(GlobalSession.java:214)
	at io.seata.server.session.SessionHelper.endCommitted(SessionHelper.java:136)
	at io.seata.server.coordinator.DefaultCoordinator.lambda$handleRetryCommitting$3(DefaultCoordinator.java:427)
	at io.seata.server.session.SessionHelper.lambda$forEach$0(SessionHelper.java:291)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
	at io.seata.server.session.SessionHelper.forEach(SessionHelper.java:288)
	at io.seata.server.session.SessionHelper.forEach(SessionHelper.java:307)
	at io.seata.server.coordinator.DefaultCoordinator.handleRetryCommitting(DefaultCoordinator.java:410)
	at io.seata.server.session.SessionHolder.distributedLockAndExecute(SessionHolder.java:315)
	at io.seata.server.coordinator.DefaultCoordinator.lambda$init$6(DefaultCoordinator.java:494)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
<==

21:50:05.927  INFO --- [      AsyncCommitting_1_1] [server.coordinator.DefaultCore] [      doGlobalCommit]  [192.168.31.181:8091:1549633538246713498] : Committing global transaction is successfully done, xid = 192.168.31.181:8091:1549633538246713498.

```
看上面的日志,可以明确看到remove和update行为基本上是并发进行的(commtting这个日志一定是删完了才打印,所以可以这么判断)
而retrycommit线程对committed状态的主要目的是为了兜底一些tc非优雅下线,或者网络抖动,导致部分事务保持在committed的状态没有从数据库中被删除(重启seata-server会进行删除,但是如果遇到一些缩容tc的情况,部分节点也没有重新启动,就会保持这些事务没被删除的情况,对事务一致性是没有任何影响),所以我个人认为在committed事务状态的时候也进行与committing一样判断isDeadSession,如果为true再进行end,而且状态已经是终态了也不应该发出update的sql
![image](https://github.com/seata/seata/assets/19943636/4493b836-828d-428d-917c-3f7c3de90f5b)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by slievrly** [comment]
I agree.

**Comment by sixlei** [comment]
Please assign it to me
