### ISSUE TITLE
seata 1.6.1 jdk 17  module java.base does not "opens java.lang.reflect" to unnamed module 

### ISSUE THREAD

**Issue by JavaLionLi** [seata/seata#5609]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://github.com/seata/seata/assets/31852897/07912c51-3c18-490c-ac38-3db564101789)
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.lang.reflect.InvocationHandler java.lang.reflect.Proxy.h accessible: module java.base does not "opens java.lang.reflect" to unnamed module @4efc180e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at io.seata.spring.util.SpringProxyUtils.getAdvisedSupport(SpringProxyUtils.java:94)
	at io.seata.spring.util.SpringProxyUtils.findInterfaces(SpringProxyUtils.java:64)
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:289)
	... 42 common frames omitted
```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by JavaLionLi** [comment]
Currently, the JVM parameter needs to be added. --add-opens java.base/java.lang.reflect=ALL-UNNAMED
But hopefully not, because it's unfriendly. Hope the community can fix this problem

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/5201
