### ISSUE TITLE
seate1.4.2有时出现0304 register RM failed问题

### ISSUE THREAD

**Issue by GalenZhang** [seata/seata#5704]
seata1.4.2有时出现 `0304 register RM failed` 问题，一段时间后又自动恢复正常了

```shell
2023-07-05 17:28:25.009 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.RmNettyRemotingClient - RM will register :jdbc:mysql://rr-xxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod,jdbc:mysql://rm-xxxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod
2023-07-05 17:28:25.010 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyPoolableFactory - NettyPool create channel to transactionRole:RMROLE,address:172.27.80.44:8091,msg:< RegisterRMRequest{resourceIds='jdbc:mysql://rr-xxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod,jdbc:mysql://rm-xxxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod', applicationId='nuode-module-order', transactionServiceGroup='nuode-module-order-group'} >
2023-07-05 17:28:25.014 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.RmNettyRemotingClient - register RM success. client version:1.4.2, server version:1.4.2,channel:[id: 0x8ae20aa0, L:/172.27.80.46:50672 - R:/172.27.80.44:8091]
2023-07-05 17:28:25.014 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyPoolableFactory - register success, cost 2 ms, version:1.4.2,role:RMROLE,channel:[id: 0x8ae20aa0, L:/172.27.80.46:50672 - R:/172.27.80.44:8091]
2023-07-05 17:28:25.014 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyClientChannelManager - will connect to 172.27.82.22:8091
2023-07-05 17:28:25.014 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.RmNettyRemotingClient - RM will register :jdbc:mysql://rr-xxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod,jdbc:mysql://rm-xxxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod
2023-07-05 17:28:25.014 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyPoolableFactory - NettyPool create channel to transactionRole:RMROLE,address:172.27.82.22:8091,msg:< RegisterRMRequest{resourceIds='jdbc:mysql://rr-xxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod,jdbc:mysql://rm-xxxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod', applicationId='nuode-module-order', transactionServiceGroup='nuode-module-order-group'} >
2023-07-05 17:28:25.016 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.RmNettyRemotingClient - register RM success. client version:1.4.2, server version:1.4.2,channel:[id: 0x2907ccc7, L:/172.27.80.46:46980 - R:/172.27.82.22:8091]
2023-07-05 17:28:25.016 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyPoolableFactory - register success, cost 0 ms, version:1.4.2,role:RMROLE,channel:[id: 0x2907ccc7, L:/172.27.80.46:46980 - R:/172.27.82.22:8091]
2023-07-05 17:28:48.555 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyClientChannelManager - will connect to 172.27.80.182:8091
2023-07-05 17:28:48.555 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.RmNettyRemotingClient - RM will register :jdbc:mysql://rr-xxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod,jdbc:mysql://rm-xxxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod
2023-07-05 17:28:48.555 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyPoolableFactory - NettyPool create channel to transactionRole:RMROLE,address:172.27.80.182:8091,msg:< RegisterRMRequest{resourceIds='jdbc:mysql://rr-xxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod,jdbc:mysql://rm-xxxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod', applicationId='nuode-module-order', transactionServiceGroup='nuode-module-order-group'} >
"2023-07-05 17:29:13.553 ERROR [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyClientChannelManager - 0304 register RM failed.
io.seata.common.exception.FrameworkException: can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientBootstrap.getNewChannel(NettyClientBootstrap.java:182)
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:58)
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:34)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:221)
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:107)
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:189)
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.seata.common.exception.FrameworkException: connect failed, can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientBootstrap.getNewChannel(NettyClientBootstrap.java:177)
	... 15 common frames omitted"
"2023-07-05 17:29:13.553 ERROR [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyClientChannelManager - 0101 can not connect to 172.27.80.182:8091 cause:can not register RM,err:can not connect to services-server.
io.seata.common.exception.FrameworkException: can not register RM,err:can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:225)
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:107)
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:189)
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)"
2023-07-05 17:29:13.553 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyClientChannelManager - will connect to 172.27.80.44:8091
2023-07-05 17:29:13.553 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.RmNettyRemotingClient - RM will register :jdbc:mysql://rr-xxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod,jdbc:mysql://rm-xxxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod
2023-07-05 17:29:13.553 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyPoolableFactory - NettyPool create channel to transactionRole:RMROLE,address:172.27.80.44:8091,msg:< RegisterRMRequest{resourceIds='jdbc:mysql://rr-xxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod,jdbc:mysql://rm-xxxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod', applicationId='nuode-module-order', transactionServiceGroup='nuode-module-order-group'} >
"2023-07-05 17:29:37.065 ERROR [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyClientChannelManager - 0304 register RM failed.
io.seata.common.exception.FrameworkException: can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientBootstrap.getNewChannel(NettyClientBootstrap.java:182)
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:58)
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:34)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:221)
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:107)
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:189)
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.seata.common.exception.FrameworkException: connect failed, can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientBootstrap.getNewChannel(NettyClientBootstrap.java:177)
	... 15 common frames omitted"
"2023-07-05 17:29:37.066 ERROR [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyClientChannelManager - 0101 can not connect to 172.27.80.44:8091 cause:can not register RM,err:can not connect to services-server.
io.seata.common.exception.FrameworkException: can not register RM,err:can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:225)
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:107)
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:189)
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$1.run(AbstractNettyRemotingClient.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)"
2023-07-05 17:29:37.066 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyClientChannelManager - will connect to 172.27.82.22:8091
2023-07-05 17:29:37.066 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.RmNettyRemotingClient - RM will register :jdbc:mysql://rr-xxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod,jdbc:mysql://rm-xxxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod
2023-07-05 17:29:37.066 INFO  [nuode-module-order,,] [timeoutChecker_2_1] io.seata.core.rpc.netty.NettyPoolableFactory - NettyPool create channel to transactionRole:RMROLE,address:172.27.82.22:8091,msg:< RegisterRMRequest{resourceIds='jdbc:mysql://rr-xxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod,jdbc:mysql://rm-xxxxxx.mysql.rds.aliyuncs.com:3306/nodo_prod', applicationId='nuode-module-order', transactionServiceGroup='nuode-module-order-group'} >
```

**Comment by GalenZhang** [comment]
是生产环境中出现的问题(linux服务器)
间隔一段时间，某个节点上会出现 0304 register RM failed 问题

**Comment by 0x9bb1** [comment]
我也遇到了这个问题。
aliyun ack环境下，seata server 1.4 client 1.3 pod to pod 通信，0304 register RM failed.
同时，seata server cpu几乎打满。
蹲一个原因

**Comment by leizhiyuan** [comment]
如果能复现，在出现cpu 高负载的时候，执行一下这个脚本

https://github.com/oldratlee/useful-scripts/blob/dev-2.x/bin/show-busy-java-threads 看看最高cpu的线程是哪个

**Comment by 0x9bb1** [comment]
> 如果能复现，在出现cpu 高负载的时候，执行一下这个脚本
> 
> https://github.com/oldratlee/useful-scripts/blob/dev-2.x/bin/show-busy-java-threads 看看最高cpu的线程是哪个

生产环境来不及保留现场只能先重启了，重启完几分钟后恢复了。我觉得cpu高负载是因为大量的register 请求导致的。主要原因还是这个网络的问题。

**Comment by aking23** [comment]
请问后面这个问题解决了吗？我们这同样的版本容器部署，每天都会在某个时间点出现同样的问题？大部分时候都能正常提供服务

**Comment by 0x9bb1** [comment]
> 请问后面这个问题解决了吗？我们这同样的版本容器部署，每天都会在某个时间点出现同样的问题？大部分时候都能正常提供服务

没有呀。后来没出现了。但是始终是个雷...

**Comment by yougecn** [comment]
> 请问后面这个问题解决了吗？我们这同样的版本容器部署，每天都会在某个时间点出现同样的问题？大部分时候都能正常提供服务

seata client 2.0.0，seata server 1.8.0，容器化部署，也是同样的情况，后来这个都解决了吗？

**Comment by yougecn** [comment]
> > 请问后面这个问题解决了吗？我们这同样的版本容器部署，每天都会在某个时间点出现同样的问题？大部分时候都能正常提供服务
> 
> seata client 2.0.0，seata server 1.8.0，容器化部署，也是同样的情况，后来这个都解决了吗？

client和server是容器内部通信
