### ISSUE TITLE
Seata 整合 OpenFeign 在 GraalVM 环境远程调用失败

### ISSUE THREAD

**Issue by ruansheng8** [seata/seata#5732]
### Ⅰ. Issue Description

看起来似乎是`GlobalTransactionalInterceptor`在基于Spring AOT 提前编译的问题。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
2023-07-17T20:19:48.962+08:00  INFO 26120 --- [io-18081-exec-1] io.seata.tm.TransactionManagerHolder     : TransactionManager Singleton io.seata.tm.DefaultTransactionManager@5fd1bac
2023-07-17T20:19:48.965+08:00 DEBUG 26120 --- [ctor_TMROLE_1_1] i.s.c.rpc.netty.AbstractNettyRemoting    : io.seata.core.rpc.netty.TmNettyRemotingClient@7a1cefc0 msgId:2, body:GlobalBeginResponse{xid='192.168.2.15:8091:5819065052880822526', extraData='null', resultCode=Success, msg='null'}
2023-07-17T20:19:48.965+08:00 DEBUG 26120 --- [io-18081-exec-1] io.seata.core.context.RootContext        : bind 192.168.2.15:8091:5819065052880822526
2023-07-17T20:19:48.966+08:00  INFO 26120 --- [io-18081-exec-1] i.seata.tm.api.DefaultGlobalTransaction  : Begin new global transaction [192.168.2.15:8091:5819065052880822526]
2023-07-17T20:19:48.966+08:00  INFO 26120 --- [io-18081-exec-1] i.seata.tm.api.DefaultGlobalTransaction  : transaction 192.168.2.15:8091:5819065052880822526 will be rollback
2023-07-17T20:19:48.968+08:00 DEBUG 26120 --- [ctor_TMROLE_1_1] i.s.c.rpc.netty.AbstractNettyRemoting    : io.seata.core.rpc.netty.TmNettyRemotingClient@7a1cefc0 msgId:3, body:GlobalRollbackResponse{globalStatus=Rollbacked, resultCode=Success, msg='null'}
2023-07-17T20:19:48.968+08:00  INFO 26120 --- [io-18081-exec-1] i.seata.tm.api.DefaultGlobalTransaction  : transaction end, xid = 192.168.2.15:8091:5819065052880822526
2023-07-17T20:19:48.968+08:00 DEBUG 26120 --- [io-18081-exec-1] io.seata.core.context.RootContext        : unbind 192.168.2.15:8091:5819065052880822526
2023-07-17T20:19:48.968+08:00  INFO 26120 --- [io-18081-exec-1] i.seata.tm.api.DefaultGlobalTransaction  : [192.168.2.15:8091:5819065052880822526] rollback status: Rollbacked
2023-07-17T20:19:48.969+08:00 ERROR 26120 --- [io-18081-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.IllegalArgumentException: Object of class [org.springframework.context.support.GenericApplicationContext] must be an instance of interface org.springframework.context.annotation.AnnotationConfigRegistry] with root cause

java.lang.IllegalArgumentException: Object of class [org.springframework.context.support.GenericApplicationContext] must be an instance of interface org.springframework.context.annotation.AnnotationConfigRegistry
        at org.springframework.util.Assert.instanceCheckFailed(Assert.java:713) ~[na:na]
        at org.springframework.util.Assert.isInstanceOf(Assert.java:613) ~[na:na]
        at org.springframework.util.Assert.isInstanceOf(Assert.java:644) ~[na:na]
        at org.springframework.cloud.context.named.NamedContextFactory.registerBeans(NamedContextFactory.java:143) ~[business-service.exe:4.0.0]
        at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:137) ~[business-service.exe:4.0.0]
        at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:122) ~[business-service.exe:4.0.0]
        at org.springframework.cloud.context.named.NamedContextFactory.getInstances(NamedContextFactory.java:236) ~[business-service.exe:4.0.0]
        at org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient.execute(FeignBlockingLoadBalancerClient.java:115) ~[business-service.exe:4.0.0]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:102) ~[business-service.exe:na]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:72) ~[business-service.exe:na]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:98) ~[business-service.exe:na]
        at jdk.proxy4/jdk.proxy4.$Proxy45.storage(Unknown Source) ~[na:na]
        at com.alibaba.cloud.examples.HomeController.feign(HomeController.java:109) ~[business-service.exe:na]
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568) ~[business-service.exe:na]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[business-service.exe:6.0.4]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[business-service.exe:6.0.4]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[business-service.exe:6.0.4]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752) ~[business-service.exe:6.0.4]
        at io.seata.spring.annotation.GlobalTransactionalInterceptor$2.execute(GlobalTransactionalInterceptor.java:208) ~[business-service.exe:1.7.0]
        at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:128) ~[business-service.exe:1.7.0]
        at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:205) ~[business-service.exe:1.7.0]
        at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:175) ~[business-service.exe:1.7.0]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[business-service.exe:6.0.4]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752) ~[business-service.exe:6.0.4]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) ~[business-service.exe:6.0.4]
        at com.alibaba.cloud.examples.HomeController$$SpringCGLIB$$0.feign(<generated>) ~[business-service.exe:na]
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568) ~[business-service.exe:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[business-service.exe:6.0.4]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[business-service.exe:6.0.4]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[business-service.exe:6.0.4]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[business-service.exe:6.0.4]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[business-service.exe:6.0.4]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[business-service.exe:6.0.4]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080) ~[business-service.exe:6.0.4]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973) ~[business-service.exe:6.0.4]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[business-service.exe:6.0.4]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[business-service.exe:6.0.4]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705) ~[business-service.exe:6.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[business-service.exe:6.0.4]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[business-service.exe:6.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[business-service.exe:10.1.5]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[business-service.exe:10.1.5]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[business-service.exe:10.1.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[business-service.exe:10.1.5]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[business-service.exe:10.1.5]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[business-service.exe:6.0.4]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[business-service.exe:6.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[business-service.exe:10.1.5]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[business-service.exe:10.1.5]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[business-service.exe:6.0.4]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[business-service.exe:6.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[business-service.exe:10.1.5]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[business-service.exe:10.1.5]
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) ~[business-service.exe:6.0.4]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[business-service.exe:6.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[business-service.exe:10.1.5]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[business-service.exe:10.1.5]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[business-service.exe:6.0.4]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[business-service.exe:6.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[business-service.exe:10.1.5]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[business-service.exe:10.1.5]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[business-service.exe:10.1.5]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[business-service.exe:10.1.5]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[business-service.exe:10.1.5]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119) ~[business-service.exe:10.1.5]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[business-service.exe:10.1.5]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[business-service.exe:10.1.5]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[business-service.exe:10.1.5]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400) ~[business-service.exe:10.1.5]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[business-service.exe:10.1.5]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859) ~[business-service.exe:10.1.5]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734) ~[business-service.exe:10.1.5]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[business-service.exe:10.1.5]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[business-service.exe:10.1.5]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[business-service.exe:10.1.5]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[business-service.exe:10.1.5]
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833) ~[business-service.exe:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[business-service.exe:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178) ~[na:na]
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. See https://github.com/alibaba/spring-cloud-alibaba/tree/2022.x/spring-cloud-alibaba-examples/seata-example/business-service
2. mvn clean spring-boot:run -Pnative
3. mvn clean native:compile -Pnative
4. Run `business-service.exe` and call `http://127.0.0.1:18081/seata/feign`

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK : 17
- Seata client:   1.7.0, 1.7.0-native-rc2
- Database version:
- OS(e.g. `uname -a`): Windows 11
- Others:

**Comment by imgoby** [comment]
how to resolve it?@ruansheng8
