### ISSUE TITLE
If you want to support the oracle database, which classes to rewrite. The company uses oracle.

### ISSUE THREAD

**Issue by 15168326318** [seata/seata#575]
### Cause: java.lang.UnsupportedOperationException: Just support MySQL by now!] with root cause
java.lang.UnsupportedOperationException: Just support MySQL by now!
	at com.alibaba.fescar.rm.datasource.sql.SQLVisitorFactory.get(SQLVisitorFactory.java:65)
	at com.alibaba.fescar.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:72)
	at com.alibaba.fescar.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:46)
	at com.alibaba.fescar.rm.datasource.PreparedStatementProxy.execute(PreparedStatementProxy.java:60)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)

**Comment by slievrly** [comment]
currently support MySQL，oracle will come soon。

**Comment by 15168326318** [comment]
@slievrly 大概什么时候能开放oracle的支持，我们公司要采用你fescar的话必须要支持oracle. 时间太晚我们就来不及了。

**Comment by leizhiyuan** [comment]
see https://github.com/seata/seata/pull/902

**Comment by xingfudeshi** [comment]
Already supported.
