### ISSUE TITLE
seata服务启动注册不到nacos，报错403

### ISSUE THREAD

**Issue by dogcida** [seata/seata#5753]
我的seata版本1.4.2，nacos升级到2.1.2后注册不上去，但是在测试环境一样的版本却可以注册上去
nacos开启了鉴权，然后seata中配置了用户密码认证，但是qidongseata时报错：

SLF4J: A number (17) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
08:45:34.999 INFO --- [ main] io.seata.config.FileConfiguration : The file name of the operation is registry
08:45:35.006 INFO --- [ main] io.seata.config.FileConfiguration : The configuration file used is /data/serviceroot/seata-server1/conf/registry.conf
08:45:35.755 ERROR --- [ main] i.seata.config.nacos.NacosConfiguration : init config properties error
==>
com.alibaba.nacos.api.exception.NacosException:

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 26 08:45:35 CST 2023
There was an unexpected error (type=Forbidden, status=403).

at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:330) ~[nacos-client-1.3.3.jar:na]
at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:149) ~[nacos-client-1.3.3.jar:na]
at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:97) ~[nacos-client-1.3.3.jar:na]
at io.seata.config.nacos.NacosConfiguration.initSeataConfig(NacosConfiguration.java:301) [seata-config-nacos-1.4.2.jar:na]
at io.seata.config.nacos.NacosConfiguration.(NacosConfiguration.java:101) [seata-config-nacos-1.4.2.jar:na]
at io.seata.config.nacos.NacosConfiguration.getInstance(NacosConfiguration.java:87) [seata-config-nacos-1.4.2.jar:na]
at io.seata.config.nacos.NacosConfigurationProvider.provide(NacosConfigurationProvider.java:29) [seata-config-nacos-1.4.2.jar:na]
at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:131) [seata-config-core-1.4.2.jar:na]
at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:94) [seata-config-core-1.4.2.jar:na]
at io.seata.server.ParameterParser.init(ParameterParser.java:84) [seata-server-1.4.2.jar:na]
at io.seata.server.ParameterParser.(ParameterParser.java:60) [seata-server-1.4.2.jar:na]
at io.seata.server.Server.main(Server.java:63) [seata-server-1.4.2.jar:na]
<==
08:45:35.830 ERROR --- [ main] i.seata.config.nacos.NacosConfiguration :

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 26 08:45:35 CST 2023
There was an unexpected error (type=Forbidden, status=403).

application has no explicit mapping for /error, so you are seeing this as a fallback.
Wed Jul 26 08:45:36 CST 2023
There was an unexpected error (type=Forbidden, status=403).

08:45:36.285 INFO --- [ main] i.s.core.rpc.netty.NettyServerBootstrap : Server started, listen port: 8092
08:45:36.651 ERROR --- [ main] io.seata.server.Server : nettyServer init error:ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance after all servers([10.111.107.77:8818, 10.111.107.78:8818, 10.111.108.77:8818]) tried: ErrCode:403, ErrMsg:
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 26 08:45:36 CST 2023
There was an unexpected error (type=Forbidden, status=403).

==>
java.lang.RuntimeException: ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance after all servers([10.111.107.77:8818, 10.111.107.78:8818, 10.111.108.77:8818]) tried: ErrCode:403, ErrMsg:
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 26 08:45:36 CST 2023
There was an unexpected error (type=Forbidden, status=403).
我的seata配置文件registry.conf如下：

![image](https://github.com/seata/seata/assets/140474321/7baebde5-c364-4344-b044-3f34f51f8c85)

账号密码可以保证没问题。

很奇怪，同样的配置，测试环境的同样版本却能够注册上去。

**Comment by dogcida** [comment]
解决了，发现seata1.4.2版本识别nacos密码时，不支持特殊字符，使用了转义符也不行，最总改为不带特殊字符的密码注册成功。

**Comment by a364176773** [comment]
这个是nacos client的问题，升级nacosclient可以修复这个问题

**Comment by dogcida** [comment]
> 
好的十分感谢！！
