### ISSUE TITLE
xa start error retry rollback

### ISSUE THREAD

**Issue by a364176773** [seata/seata#5775]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
start失败的时候，如下面的异常就是druid的依赖冲突导致jdbcconstatns oracle使用时出现NoSuchFieldError，此时tc会重试60s回滚，但是会一直失败，因为没有start成功肯定是没有这个xid的，应该捕获该异常直接进行end，rollback，这个异常不知道为什么没有触发orm框架或者spring的事务管理器进行rollback需要研究下
```
    private synchronized void start() throws XAException, SQLException {
        // 3. XA Start
        if (JdbcConstants.ORACLE.equals(resource.getDbType())) {
            xaResource.start(this.xaBranchXid, SeataXAResource.ORATRANSLOOSE);
        } else {
            xaResource.start(this.xaBranchXid, XAResource.TMNOFLAGS);
        }
```

```
java.lang.NoSuchFieldError: ORACLE
	at io.seata.rm.datasource.xa.ConnectionProxyXA.start(ConnectionProxyXA.java:265) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.datasource.xa.ConnectionProxyXA.setAutoCommit(ConnectionProxyXA.java:180) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:285) ~[spring-jdbc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400) ~[spring-tx-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:572) ~[spring-tx-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:360) ~[spring-tx-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at io.seata.spring.annotation.AdapterInvocationWrapper.proceed(AdapterInvocationWrapper.java:57) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.integration.tx.api.interceptor.handler.GlobalTransactionalInterceptorHandler$2.execute(GlobalTransactionalInterceptorHandler.java:200) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
```
```
2023-08-11 14:59:41.190  INFO 30163 --- [_RMROLE_1_12_16] i.s.c.r.p.c.RmBranchRollbackProcessor    : rm handle branch rollback process:BranchRollbackRequest{xid='10.58.12.165:8091:2306266125201837297', branchId=2306266125201837298, branchType=XA, resourceId='jdbc:mysql://:4366/cjbtest', applicationData='null'}
2023-08-11 14:59:41.191  INFO 30163 --- [_RMROLE_1_12_16] io.seata.rm.AbstractRMHandler            : Branch Rollbacking: 10.58.12.165:8091:2306266125201837297 2306266125201837298 jdbc:mysql://:4366/cjbtest
2023-08-11 14:59:41.218  INFO 30163 --- [_RMROLE_1_12_16] io.seata.rm.AbstractRMHandler            : Branch Rollbacked result: PhaseTwo_RollbackFailed_XAER_NOTA_Retryable
2023-08-11 14:59:41.659  INFO 30163 --- [actionRetry_1_1] i.s.tm.api.DefaultFailureHandlerImpl     : transaction [10.58.12.165:8091:2306266125201837297] current status is [RollbackRetrying]
2023-08-11 14:59:42.188  INFO 30163 --- [_RMROLE_1_13_16] i.s.c.r.p.c.RmBranchRollbackProcessor    : rm handle branch rollback process:BranchRollbackRequest{xid='10.58.12.165:8091:2306266125201837297', branchId=2306266125201837298, branchType=XA, resourceId='jdbc:mysql://:4366/cjbtest', applicationData='null'}
2023-08-11 14:59:42.189  INFO 30163 --- [_RMROLE_1_13_16] io.seata.rm.AbstractRMHandler            : Branch Rollbacking: 10.58.12.165:8091:2306266125201837297 2306266125201837298 jdbc:mysql://:4366/cjbtest
2023-08-11 14:59:42.205  INFO 30163 --- [_RMROLE_1_13_16] io.seata.rm.AbstractRMHandler            : Branch Rollbacked result: PhaseTwo_RollbackFailed_XAER_NOTA_Retryable
```
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by capthua** [comment]
plz assign to me, thanks

**Comment by capthua** [comment]
start是在 TransactionAspectSupport#createTransactionIfNecessary 中执行的，此时还没执行业务方法，所以spring不会rollback
![image](https://github.com/seata/seata/assets/57092586/196ee0fd-8e22-4c29-8f0c-e2ee4f212e15)

**Comment by a364176773** [comment]
> start是在 TransactionAspectSupport#createTransactionIfNecessary 中执行的，此时还没执行业务方法，所以spring不会rollback ![image](https://user-images.githubusercontent.com/57092586/261858722-17b12610-ed8b-4c7d-9df4-f5cbff5c652e.png)

那这种情况是不是应该我们自己catch后向tc report一个一阶段失败的请求，让其直接跳过这个分支事务即可？

**Comment by capthua** [comment]
> > start是在 TransactionAspectSupport#createTransactionIfNecessary 中执行的，此时还没执行业务方法，所以spring不会rollback ![image](https://user-images.githubusercontent.com/57092586/261858722-17b12610-ed8b-4c7d-9df4-f5cbff5c652e.png)
> 
> 那这种情况是不是应该我们自己catch后向tc report一个一阶段失败的请求，让其直接跳过这个分支事务即可？

是的，报告后一阶段失败，sever就直接删除该分支了，不会重试向rm发送回滚的请求，就不会一直报错了。这个方案我觉得ok

**Comment by capthua** [comment]
经测试发现

**Comment by capthua** [comment]
经测试发现
druid版本 <=1.1.24，会出现 java.lang.NoSuchFieldError: ORACLE
![image](https://github.com/seata/seata/assets/57092586/e3928328-d289-4967-96c8-7307ff7dfaab)
druid版本 = 1.2.1, 会出现 java.lang.NoSuchMethodError: com.alibaba.druid.DbType.equals(Ljava/lang/String;)Z 错误
![image](https://github.com/seata/seata/assets/57092586/f0c88c2e-82bf-4a6c-becb-fa2e98e50d0f)
