### ISSUE TITLE
XAER_RMFAIL: The command cannot be executed when global transaction is in the  ACTIVE state

### ISSUE THREAD

**Issue by funky-eyes** [seata/seata#5776]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
当xa事务start，立马遇到了rollback时，会因为没有任何子事务(业务sql还未发出，事务也未end)导致抛出
XAER_RMFAIL: The command cannot be executed when global transaction is in the  ACTIVE state
且由于防悬挂，会再此时rollback的时候，再本地写入一个BranchStatus，再事务end的时候进行了termination，发现事务已经是回滚装了，会进行抛出SQLException异常，但由于此时的异常时在connection.rollback进行的，导致不会再次进行xarollback，导致事务无法被回滚，此时除非等10s后的自动close该物理连接，或者重启应用，否则无法回滚该xa事务

此日志为先进行下发rollback
```
com.mysql.jdbc.jdbc2.optional.MysqlXAException: XAER_RMFAIL: The command cannot be executed when global transaction is in the  ACTIVE state
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:583) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:568) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.rollback(MysqlXAConnection.java:413) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at io.seata.rm.datasource.xa.ConnectionProxyXA.xaRollback(ConnectionProxyXA.java:144) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.datasource.xa.ConnectionProxyXA.xaRollback(ConnectionProxyXA.java:135) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.datasource.xa.ResourceManagerXA.finishBranch(ResourceManagerXA.java:134) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.datasource.xa.ResourceManagerXA.branchRollback(ResourceManagerXA.java:119) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:125) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:67) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:63) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:131) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:63) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:68) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.handleBranchRollback(RmBranchRollbackProcessor.java:63) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.process(RmBranchRollbackProcessor.java:58) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:280) [seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_352]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_352]
Caused by: java.sql.SQLException: XAER_RMFAIL: The command cannot be executed when global transaction is in the  ACTIVE state
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.jdbc2.optional.MysqlXAConnection.dispatchCommand(MysqlXAConnection.java:562) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	... 20 common frames omitted
```
此日志为connection rollback时end失败
```
java.sql.SQLException: failed xa branch 10.58.12.217:8091:2306266123413857512 the global transaction has finish, branch status: 8
	at io.seata.rm.datasource.xa.ConnectionProxyXA.termination(ConnectionProxyXA.java:359) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.datasource.xa.ConnectionProxyXA.termination(ConnectionProxyXA.java:350) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.datasource.xa.ConnectionProxyXA.end(ConnectionProxyXA.java:283) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.rm.datasource.xa.ConnectionProxyXA.commit(ConnectionProxyXA.java:209) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:331) ~[spring-jdbc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743) ~[spring-tx-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711) ~[spring-tx-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:631) ~[spring-tx-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385) ~[spring-tx-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99) ~[spring-tx-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at io.seata.spring.annotation.AdapterInvocationWrapper.proceed(AdapterInvocationWrapper.java:57) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.integration.tx.api.interceptor.handler.GlobalTransactionalInterceptorHandler$2.execute(GlobalTransactionalInterceptorHandler.java:200) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:128) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.integration.tx.api.interceptor.handler.GlobalTransactionalInterceptorHandler.handleGlobalTransaction(GlobalTransactionalInterceptorHandler.java:197) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.integration.tx.api.interceptor.handler.GlobalTransactionalInterceptorHandler.doInvoke(GlobalTransactionalInterceptorHandler.java:166) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.integration.tx.api.interceptor.handler.AbstractProxyInvocationHandler.invoke(AbstractProxyInvocationHandler.java:35) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at io.seata.spring.annotation.AdapterSpringSeataInterceptor.invoke(AdapterSpringSeataInterceptor.java:45) ~[seata-all-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at icu.funkye.service.impl.ProductServiceImpl$$EnhancerBySpringCGLIB$$37136118.reduceStock(<generated>) ~[classes/:na]
	at icu.funkye.controller.ProductController.reduceStock(ProductController.java:30) ~[classes/:na]
```

修改建议，
方案1.end时发现状态已经是回滚状态，直接进行xarollback，而不是将异常抛出去
方案2.end时发现是回滚状态，直接close物理连接

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by capthua** [comment]
plz assign to me

**Comment by capthua** [comment]
我觉得第一种方案比较好，应该让应用维护事务的状态。close连接，让数据库去处理end状态的事务，这种方式有点粗暴。你觉的哪种方式比较好? @a364176773

**Comment by capthua** [comment]
> 但由于此时的异常时在connection.rollback进行的，导致不会再次进行xarollback，导致事务无法被回滚
看日志这里应该是在 ConnectionProxyXA.commit(ConnectionProxyXA.java:209) 的 end 里抛的异常，rollback中不会调用ConnectionProxyXA#end

**Comment by capthua** [comment]
暂无法复现
