### ISSUE TITLE
seata-server  1.7  无法读取nacos的配置信息

### ISSUE THREAD

**Issue by liubang0909** [seata/seata#5797]
seata-server  1.7.0
nacos 2.2.3
jdk 用的 1.8

使用从 nacos 读取配置的方式无法启动
报错信息：
/Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/bin/java  -server -Dloader.path=/Users/liubang/Downloads/seata/lib -Xmx2048m -Xms2048m -Xss512k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/liubang/Downloads/seata/logs/java_heapdump.hprof -XX:+DisableExplicitGC -Xloggc:/Users/liubang/Downloads/seata/logs/seata_gc.log -verbose:gc -XX:+PrintGCDetails  -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=7150 -Dapp.home=/Users/liubang/Downloads/seata -Dbasedir=/Users/liubang/Downloads/seata -Dspring.config.additional-location=/Users/liubang/Downloads/seata/conf/ -Dspring.config.location=/Users/liubang/Downloads/seata/conf/application.yml -Dlogging.config=/Users/liubang/Downloads/seata/conf/logback-spring.xml -jar /Users/liubang/Downloads/seata/target/seata-server.jar 
███████╗███████╗ █████╗ ████████╗ █████╗
██╔════╝██╔════╝██╔══██╗╚══██╔══╝██╔══██╗
███████╗█████╗  ███████║   ██║   ███████║
╚════██║██╔══╝  ██╔══██║   ██║   ██╔══██║
███████║███████╗██║  ██║   ██║   ██║  ██║
╚══════╝╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝

08:58:12.351  INFO --- [                     main] [ta.config.ConfigurationFactory] [                load]  [] : load Configuration from :Spring Configuration
08:58:12.444 ERROR --- [                     main] [amework.boot.SpringApplication] [       reportFailure]  [] : Application run failed
==>
java.lang.ExceptionInInitializerError: null
	at io.seata.server.spring.listener.SeataPropertiesLoader.initialize(SeataPropertiesLoader.java:76) ~[classes!/:1.7.0]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:648) [spring-boot-2.5.13.jar:2.5.13]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:417) [spring-boot-2.5.13.jar:2.5.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.5.13.jar:2.5.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365) [spring-boot-2.5.13.jar:2.5.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) [spring-boot-2.5.13.jar:2.5.13]
	at io.seata.server.ServerApplication.main(ServerApplication.java:31) [classes!/:1.7.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_261]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [seata-server.jar:1.7.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [seata-server.jar:1.7.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [seata-server.jar:1.7.0]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) [seata-server.jar:1.7.0]
Caused by: java.lang.RuntimeException: ErrCode:-400, ErrMsg:endpoint is blank
	at io.seata.config.nacos.NacosConfiguration.<init>(NacosConfiguration.java:100) ~[seata-config-nacos-1.7.0.jar:1.7.0]
	at io.seata.config.nacos.NacosConfiguration.getInstance(NacosConfiguration.java:84) ~[seata-config-nacos-1.7.0.jar:1.7.0]
	at io.seata.config.nacos.NacosConfigurationProvider.provide(NacosConfigurationProvider.java:29) ~[seata-config-nacos-1.7.0.jar:1.7.0]
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:160) ~[seata-config-core-1.7.0.jar:1.7.0]
	at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:112) ~[seata-config-core-1.7.0.jar:1.7.0]
	at io.seata.server.store.StoreConfig.<clinit>(StoreConfig.java:33) ~[classes!/:1.7.0]
	... 15 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: java.lang.reflect.InvocationTargetException
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:46) ~[nacos-api-1.4.2.jar:na]
	at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:44) ~[nacos-api-1.4.2.jar:na]
	at io.seata.config.nacos.NacosConfiguration.<init>(NacosConfiguration.java:97) ~[seata-config-nacos-1.7.0.jar:1.7.0]
	... 20 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_261]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_261]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_261]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_261]
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:43) ~[nacos-api-1.4.2.jar:na]
	... 22 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: endpoint is blank
	at com.alibaba.nacos.client.config.impl.ServerListManager.<init>(ServerListManager.java:183) ~[nacos-client-1.4.2.jar:na]
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.<init>(ServerHttpAgent.java:274) ~[nacos-client-1.4.2.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.<init>(NacosConfigService.java:88) ~[nacos-client-1.4.2.jar:na]
	... 27 common frames omitted
<==

08:58:12.447  WARN --- [                 Thread-1] [mmon.http.HttpClientBeanHolder] [            shutdown]  [] : [HttpClientBeanHolder] Start destroying common HttpClient
08:58:12.447  WARN --- [                 Thread-1] [mmon.http.HttpClientBeanHolder] [            shutdown]  [] : [HttpClientBeanHolder] Destruction of the end

看报错是说初始化失败

seata 的 yml 配置

server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

console:
  user:
    username: seata
    password: seata
seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: nacos
    nacos:
      service-addr: 127.0.0.1:8848
      namespace: bae31d86-e18b-4a86-9a81-4f31aacf2fb3
      group: SEATA_GROUP
      data-id: seataServer.properties
      username: 
      password: 

  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: nacos
    preferred-networks: 30.240.*
    nacos:
      application: seata-server
      server-addr: localhost:8848
      group: SEATA_GROUP
      cluster: default
      namespace: 
      username: 
      password: 
  store:
    # support: file 、 db 、 redis
    mode: db
    db:
      datasource: druid
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seata?rewriteBatchedStatements=true
      user: root
      password: xuhuan123
      min-conn: 10
      max-conn: 100
      global-table: global_table
      branch-table: branch_table
      lock-table: lock_table
      distributed-lock-table: distributed_lock
      query-limit: 1000
      max-wait: 5000
  # server:
  #   vgroup-mapping:
  #     default-tx-group: fsp_tx_group
  #   enable-degrade: false
  #   disable-global-transaction: false
#  server:
#    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login

nacos 中配置文件信息

transport.type=TCP
transport.server=NIO
transport.heartbeat=true
transport.enableTmClientBatchSendRequest=false
transport.enableRmClientBatchSendRequest=true
transport.enableTcServerBatchSendResponse=false
transport.rpcRmRequestTimeout=30000
transport.rpcTmRequestTimeout=30000
transport.rpcTcRequestTimeout=30000
transport.threadFactory.bossThreadPrefix=NettyBoss
transport.threadFactory.workerThreadPrefix=NettyServerNIOWorker
transport.threadFactory.serverExecutorThreadPrefix=NettyServerBizHandler
transport.threadFactory.shareBossWorker=false
transport.threadFactory.clientSelectorThreadPrefix=NettyClientSelector
transport.threadFactory.clientSelectorThreadSize=1
transport.threadFactory.clientWorkerThreadPrefix=NettyClientWorkerThread
transport.threadFactory.bossThreadSize=1
transport.threadFactory.workerThreadSize=default
transport.shutdown.wait=3
transport.serialization=seata
transport.compressor=none
service.vgroupMapping.default_tx_group=default
service.default.grouplist=127.0.0.1:8091
service.enableDegrade=false
service.disableGlobalTransaction=false
client.rm.asyncCommitBufferLimit=10000
client.rm.lock.retryInterval=10
client.rm.lock.retryTimes=30
client.rm.lock.retryPolicyBranchRollbackOnConflict=true
client.rm.reportRetryCount=5
client.rm.tableMetaCheckEnable=true
client.rm.tableMetaCheckerInterval=60000
client.rm.sqlParserType=druid
client.rm.reportSuccessEnable=false
client.rm.sagaBranchRegisterEnable=false
client.rm.sagaJsonParser=fastjson
client.rm.tccActionInterceptorOrder=-2147482648
client.tm.commitRetryCount=5
client.tm.rollbackRetryCount=5
client.tm.defaultGlobalTransactionTimeout=60000
client.tm.degradeCheck=false
client.tm.degradeCheckAllowTimes=10
client.tm.degradeCheckPeriod=2000
client.tm.interceptorOrder=-2147482648
client.undo.dataValidation=true
client.undo.logSerialization=jackson
client.undo.onlyCareUpdateColumns=true
server.undo.logSaveDays=7
server.undo.logDeletePeriod=86400000
client.undo.logTable=undo_log
client.undo.compress.enable=true
client.undo.compress.type=zip
client.undo.compress.threshold=64k
tcc.fence.logTableName=tcc_fence_log
tcc.fence.cleanPeriod=1h
log.exceptionRate=100
store.mode=db
store.lock.mode=db
store.session.mode=db
store.file.dir=file_store/data
store.file.maxBranchSessionSize=16384
store.file.maxGlobalSessionSize=512
store.file.fileWriteBufferCacheSize=16384
store.file.flushDiskMode=async
store.file.sessionReloadReadSize=100
store.db.datasource=druid
store.db.dbType=mysql
store.db.driverClassName=com.mysql.cj.jdbc.Driver
store.db.url=jdbc:mysql://127.0.0.1:3306/seata?useUnicode=true&rewriteBatchedStatements=true
store.db.user=root
store.db.password=xuhuan123
store.db.minConn=5
store.db.maxConn=30
store.db.globalTable=global_table
store.db.branchTable=branch_table
store.db.distributedLockTable=distributed_lock
store.db.queryLimit=100
store.db.lockTable=lock_table
store.db.maxWait=5000
server.recovery.committingRetryPeriod=1000
server.recovery.asynCommittingRetryPeriod=1000
server.recovery.rollbackingRetryPeriod=1000
server.recovery.timeoutRetryPeriod=1000
server.maxCommitRetryTimeout=-1
server.maxRollbackRetryTimeout=-1
server.rollbackRetryTimeoutUnlockEnable=false
server.distributedLockExpireTime=10000
server.xaerNotaRetryTimeout=60000
server.session.branchAsyncQueueSize=5000
server.session.enableBranchAsyncRemove=false
server.enableParallelRequestHandle=false
metrics.enabled=false
metrics.registryType=compact
metrics.exporterList=prometheus
metrics.exporterPrometheusPort=9898

命名空间  group  data-id  都正确  请问是哪里的原因

![Uploading 截屏2023-08-24 09.12.57.png…]()

**Comment by a364176773** [comment]
就是文件挂载有问题，读不到nacos地址异常时nacosclient抛出的

**Comment by liubang0909** [comment]
所以该怎么调试这个问题啊。。  只能file 的方式启动了吗？

**Comment by liubang0909** [comment]
> 

 config改成 file 的方式启动 之后可以注册上 nacos   是不是说明可以访问到   但是读取文件有问题？

**Comment by liubang0909** [comment]
> 就是文件挂载有问题，读不到nacos地址异常时nacosclient抛出的

还有就是seata-server怎么终止？直接kill掉进程？

**Comment by xingfudeshi** [comment]
> > 就是文件挂载有问题，读不到nacos地址异常时nacosclient抛出的
> 
> 还有就是seata-server怎么终止？直接kill掉进程？

You can kill the seata process directly.
