### ISSUE TITLE
数据源无法被代理

### ISSUE THREAD

**Issue by bright-mph** [seata/seata#5834]
### Ⅰ. Issue Description
公司基于jdbc封装的orm框架，配置了多个数据源，数据库使用pgsql，采用nacos配置，项目启动显示 register TM success，使用DataSourceProxy配置数据源后，debug没有进入ExecuteTemplate#execute方法，事务回滚无效，undo_log表始终无记录。

### Ⅱ. Describe what happened

  使用默认的AT模式，自动代理数据源关闭，使用@GlobalTransactional注解，执行数据库插入操作后，手动抛出异常，日志显示Rollbacked，xid传递正常，但是数据库中插入信息，并没有回滚。

这是发起远程调用的服务的日志信息
```
2023-09-08 13:55:46.057  INFO 13808 --- [nio-8004-exec-3] io.seata.tm.TransactionManagerHolder     : TransactionManager Singleton io.seata.tm.DefaultTransactionManager@5fd0bd0a
2023-09-08 13:55:46.065  INFO 13808 --- [nio-8004-exec-3] i.seata.tm.api.DefaultGlobalTransaction  : Begin new global transaction [192.168.1.29:8091:2459398333591875589]
br-emp-disp, xid:------------------> 192.168.1.29:8091:2459398333591875589
2023-09-08 13:55:46.278  INFO 13808 --- [nio-8004-exec-3] i.seata.tm.api.DefaultGlobalTransaction  : Suspending current transaction, xid = 192.168.1.29:8091:2459398333591875589
2023-09-08 13:55:46.278  INFO 13808 --- [nio-8004-exec-3] i.seata.tm.api.DefaultGlobalTransaction  : [192.168.1.29:8091:2459398333591875589] rollback status: Rollbacked
2023-09-08 13:55:46.293 ERROR 13808 --- [nio-8004-exec-3] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/Disp] threw exception [Request processing failed; nested exception is feign.FeignException$InternalServerError: [500] during [POST] to [http://br-emp-others/Others/SeataTest/insert] [FeignOthersService#createSeataTest(Map)]: [{"timestamp":"2023-09-08T05:55:46.259+00:00","status":500,"error":"Internal Server Error","path":"/Others/SeataTest/insert"}]] with root cause
```

这是被调用的服务的日志信息
```
2023-09-08 13:55:46.256  INFO 9592 --- [nio-8006-exec-3] cn.berryinfo.data.trace.DaTracerImpl     : 操作ID: 2, DbAccessorID: 1, 是否事务： 否, 数据源： mp, 线程名称： http-nio-8006-exec-3 
Sql语句: insert into seata_test(id,name,age) values(:id,:name,:age)
参数如下:
		参数名:id，参数类型(JDBCType)：INTEGER，参数值：5，参数方向：INPUT
		参数名:name，参数类型(JDBCType)：VARCHAR，参数值：setatTest，参数方向：INPUT
		参数名:age，参数类型(JDBCType)：INTEGER，参数值：100，参数方向：INPUT

数据行数：1, 开始时间：2023-09-08 13:55:46.229, 结束时间：2023-09-08 13:55:46.256, 时间耗费: 27ms
br-emp-others, xid:------------------> 192.168.1.29:8091:2459398333591875589
2023-09-08 13:55:46.258 ERROR 9592 --- [nio-8006-exec-3] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/Others] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: wuwu] with root cause

java.lang.RuntimeException: wuwu
	at cn.berryinfo.emp.service.SeataTestService.insertMy(SeataTestService.java:56) ~[main/:na]
	at cn.berryinfo.emp.controller.SeataTestController.insert(SeataTestController.java:33) ~[main/:na]
	at cn.berryinfo.emp.controller.SeataTestController$$FastClassBySpringCGLIB$$91219a6b.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.23.jar:5.3.23]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$2.execute(GlobalTransactionalInterceptor.java:204) ~[seata-all-1.6.1.jar:1.6.1]
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:130) ~[seata-all-1.6.1.jar:1.6.1]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:201) ~[seata-all-1.6.1.jar:1.6.1]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:171) ~[seata-all-1.6.1.jar:1.6.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.23.jar:5.3.23]
	at cn.berryinfo.emp.controller.SeataTestController$$EnhancerBySpringCGLIB$$c2366c6d.insert(<generated>) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665) ~[javax.servlet-api-4.0.1.jar:4.0.1]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.68.jar:9.0.68]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at cn.berryinfo.mp.filter.MpJsonWrapperFilter.doFilter(MpJsonWrapperFilter.java:101) ~[br-mp-core-3.1.9.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.23.jar:5.3.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.23.jar:5.3.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.23.jar:5.3.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.68.jar:9.0.68]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

#### nacos相关配置
![image](https://github.com/seata/seata/assets/61874809/551e49e6-89e5-4e90-bd31-28c6dc0192e3)
![image](https://github.com/seata/seata/assets/61874809/5db4674e-c290-4f75-bc79-1bd14cd913f9)
mode使用过file、redis、db，都是日志显示已回滚，未进入方法ExecuteTemplate#execute，数据库插入成功未回滚。

#### 数据源相关配置
![image](https://github.com/seata/seata/assets/61874809/be88631b-14e5-43ad-8861-dcadc6afdb5f)
此处爆红为idea提示前缀重复，对项目无任何影响
![image](https://github.com/seata/seata/assets/61874809/6205e0af-cb9e-49cd-8641-3be37739970c)

#### gradle依赖配置
![image](https://github.com/seata/seata/assets/61874809/73485918-5ffe-4ed4-b823-5c05aa2e4d9f)

### Ⅳ. At last

上述情况使用OpenFeign实现服务间的调用，后面我直接在方法上使用@GlobalTransactional(rollbackFor = Exception.class)，不进行服务间的调用，直接进行数据库插入，再手动抛出异常，出现的问题依旧和上述一样，但是使用Spring的@Transactional(rollbackFor = Exception.class)注解，事务回滚成功

**Comment by xingfudeshi** [comment]
It seems your datasource is not properly proxied. Pls debug it to see if the datasource is DataSourceProxy.

**Comment by xingfudeshi** [comment]
Pls enable this ,see if it works.
<img width="302" alt="image" src="https://github.com/seata/seata/assets/24457941/e9df9b10-0a98-488a-bf32-2b757f271801">

**Comment by bright-mph** [comment]
> Pls enable this ,see if it works. <img alt="image" width="302" src="https://user-images.githubusercontent.com/24457941/266925570-e9df9b10-0a98-488a-bf32-2b757f271801.png">


按照您的说法我试了一下，分布式事务依旧不生效。问一下mybatis或者mybatis plus是实现了分布式事务相关的逻辑了吗？因为用的是公司自己封装的ORM，开会时架构说我们自己的ORM当时并没有考虑分布式事务相关的业务。 @xingfudeshi

**Comment by xingfudeshi** [comment]
Seata only proxies the datasource and has nothing to do with the ORM itself.

**Comment by bright-mph** [comment]
最后数据源配置进去了，但是会报错主键无法找到，然后升级seata版本到1.7.0，问题解决
