### ISSUE TITLE
JdbcUtils.getDbType() NullPointerException

### ISSUE THREAD

**Issue by zwl410** [seata/seata#5848]
![image](https://github.com/seata/seata/assets/35553373/b6b4684f-bf23-4b46-89ef-3a0f1a5036f7)

项目中使用了双数据源mysql和TDengine
方法initDataSourceResource 初始化的时候抛出了异常
断点查看alibaba.druid.util JdbcUtils.getDbType() 没有 jdbc:TAOS: 而引发的空指针异常
![image](https://github.com/seata/seata/assets/35553373/6ba66379-3411-4872-a63b-5f803c160950)

druid.version 1.2.19
seata.version 1.7.1

**Comment by zhangSSSPlus** [comment]
报错日志
2023-09-14 17:40:48 log [main] INFO  o.a.catalina.core.StandardService.log[173] - Stopping service [Tomcat]
2023-09-14 17:40:48 log [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener.logMessage[136] - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-09-14 17:40:48 log [main] ERROR o.s.boot.SpringApplication.reportFailure[843] - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'thirdRequencyInit': Unsatisfied dependency expressed through field 'jdbcTemplate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Unsatisfied dependency expressed through method 'dataSourceScriptDatabaseInitializer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tdengineDataSource' defined in class path resource [com/provider/config/TDengineConfig.class]: Initialization of bean failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1413)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.enneagon.v5.realtime.provider.RealtimeApp.main(RealtimeApp.java:21)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Unsatisfied dependency expressed through method 'dataSourceScriptDatabaseInitializer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tdengineDataSource' defined in class path resource [com/provider/config/TDengineConfig.class]: Initialization of bean failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
	... 20 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tdengineDataSource' defined in class path resource [com/provider/config/TDengineConfig.class]: Initialization of bean failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:610)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 35 common frames omitted
Caused by: java.lang.NullPointerException: null
	at io.seata.rm.datasource.util.JdbcUtils.getDbType(JdbcUtils.java:54)
	at io.seata.rm.datasource.DataSourceProxy.init(DataSourceProxy.java:89)
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:82)
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:67)
	at io.seata.spring.annotation.datasource.SeataAutoDataSourceProxyCreator.buildProxy(SeataAutoDataSourceProxyCreator.java:125)
	at io.seata.spring.annotation.datasource.SeataAutoDataSourceProxyCreator.wrapIfNecessary(SeataAutoDataSourceProxyCreator.java:99)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:291)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:437)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	... 45 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:54884', transport: 'socket'
2023-09-14 17:40:56 log [Thread-1] WARN  c.a.n.c.http.HttpClientBeanHolder.shutdown[108] - [HttpClientBeanHolder] Start destroying common HttpClient

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

**Comment by a364176773** [comment]
这个问题反馈给druid社区看下

**Comment by zwl410** [comment]
项目中只集成alibaba druid启动不会报错，加上seata 启动会报这个异常initDataSourceResource空指针，是否不支持改数据库，就不能使用，有办法避免改问题？

**Comment by wt-better** [comment]
You can exclude `TDengine ` datasource auto proxy if not need it in transaction.

**Comment by leizhiyuan** [comment]
Submitted an issue to the druid, can follow up within https://github.com/apache/druid/issues/15179

**Comment by asdf2014** [comment]
@leizhiyuan 你提错地方了，去这里提 👉 https://github.com/alibaba/druid

**Comment by leizhiyuan** [comment]
> TDengine

https://github.com/alibaba/druid/issues/5389 高版本看上去已经支持了

**Comment by leizhiyuan** [comment]
[        } else if (rawUrl.startsWith("jdbc:TAOS:")) {](https://github.com/alibaba/druid/blob/56300eb61cf085a65ba02d62766c1ac3224e154e/core/src/main/java/com/alibaba/druid/util/JdbcUtils.java#L538)

**Comment by funky-eyes** [comment]
You can upgrade the druid version to solve the problem, if you still have problems please talk to us again.

**Comment by hp88yx** [comment]
druid.version 1.2.22
seata.version 1.8.0

配置了seata.enable-auto-data-source-proxy=true的时候会提示这个错误, 需要关闭自动代理, 然后在需要代理的datasource处手动设置代理数据源
