### ISSUE TITLE
Cannot run DubboBusinessTester successfully.

### ISSUE THREAD

**Issue by morris1990** [seata/seata#641]
I run the demo case on mc os by using zookeeper as registry. I can run the DubboBusinessTester successfully without GlobalTransactional which means the dubbo call is ok in these service. But cannot run successfully with that annotation. please help.
Error:
Exception in thread "main" java.lang.RuntimeException: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [update storage_tbl set count = ? where commodity_code = ?]; SQL state [null]; error code [0]; com.alibaba.fescar.core.exception.TransactionException: RPC Timeout; nested exception is java.sql.SQLException: com.alibaba.fescar.core.exception.TransactionException: RPC Timeout
org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [update storage_tbl set count = ? where commodity_code = ?]; SQL state [null]; error code [0]; com.alibaba.fescar.core.exception.TransactionException: RPC Timeout; nested exception is java.sql.SQLException: com.alibaba.fescar.core.exception.TransactionException: RPC Timeout

**Comment by slievrly** [comment]
please make sure fescar-spring and fescar-server version is 0.4.0  and which registry do you use? please check registry.conf

**Comment by morris1990** [comment]
> please make sure fescar-spring and fescar-server version is 0.4.0 and which registry do you use? please check registry.conf

Where is registry.conf file? I update fescar-spring and fescar-server to 0.4.0, but still failed

**Comment by morris1990** [comment]
Is there any reason can lead branchRegister timout?

Caused by: com.alibaba.fescar.core.exception.TransactionException: RPC Timeout
	at com.alibaba.fescar.rm.datasource.DataSourceManager.branchRegister(DataSourceManager.java:76)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:202)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:175)

**Comment by slievrly** [comment]
@morris1990 please dingtalk ping me.

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
