### ISSUE TITLE
If there are many rollbacks, the error is reported: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(57) + length(42) exceeds writerIndex(96): PooledUnsafeDirectByteBuf(ridx: 57, widx: 96 , cap: 96)

### ISSUE THREAD

**Issue by 15168326318** [seata/seata#646]
2019-03-22 15:29:40 [NettyClientSelector_RMROLE_1] ERROR com.alibaba.fescar.core.rpc.netty.AbstractRpcRemoting -0318
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(57) + length(42) exceeds writerIndex(96): PooledUnsafeDirectByteBuf(ridx: 57, widx: 96, cap: 96)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by slievrly** [comment]
Please use fescar-spring and fescar-server version 0.4. The version upgrade caused the protocol to be incompatible and has been updated in the sample.

**Comment by leizhiyuan** [comment]
It has been fixed ， please retest it based on branch develop. thank 

because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
