### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1 when execution of jdbc query

### ISSUE THREAD

**Issue by asdadmin01** [seata/seata#715]
报错信息:

java.lang.ArrayIndexOutOfBoundsException: 1
	at com.alibaba.fescar.rm.datasource.AbstractPreparedStatementProxy.setParamByIndex(AbstractPreparedStatementProxy.java:106)
	at com.alibaba.fescar.rm.datasource.AbstractPreparedStatementProxy.setObject(AbstractPreparedStatementProxy.java:242)
	at org.springframework.jdbc.core.StatementCreatorUtils.setValue(StatementCreatorUtils.java:464)
	at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValueInternal(StatementCreatorUtils.java:241)
	at org.springframework.jdbc.core.StatementCreatorUtils.setParameterValue(StatementCreatorUtils.java:156)
	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.setValues(PreparedStatementCreatorFactory.java:287)
	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:244)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:690)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:717)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:767)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:192)

代码片段：
String sql = "select * from users where id in (:ids)";
Map parameters = new HashMap();
parameters.put("ids", Arrays.asList(new Long[] {1000L, 2000L}));
namedParameterJdbcTemplate.query(sql, new MapSqlParameterSource(parameter), new BeanPropertyRowMapper<>(User.class));

分析：
AbstractPreparedStatementProxy.java维护了
protected ArrayList<Object>[] parameters;
这个初始化大小为1，sql里的参数是1个，但是类型是List
但是PreparedStatementCreatorFactory.java的setValues()方法是对List里的2个参数进行赋值时，对于List里的第2个参数操作时，出现了数组越界错误。

环境信息：
- JDK version :1,8
- OS :Win10
- Database: Oracle 11g
- Others: druid pool

**Comment by xingfudeshi** [comment]
Thanks for reporting.i will fix it.

**Comment by xingfudeshi** [comment]
we not yet support Oracle.

**Comment by asdadmin01** [comment]
I thinks it's a common issue, not matter Oracle or MySQL. 
The code logic may raise the exception when specify array/list as JdbcTemplate quey parameter.

any suggestions will be appreciated.

**Comment by xingfudeshi** [comment]
ok.fine.

**Comment by xingfudeshi** [comment]
I just tried the problem you described earlier.The result can be returned as expected.
![image](https://user-images.githubusercontent.com/24457941/55533192-1320ea80-56e3-11e9-816f-6173b6e681b5.png)
this is work table in MySQL
![image](https://user-images.githubusercontent.com/24457941/55533246-3d72a800-56e3-11e9-9004-3a57e3065b0b.png)

I guess it's probably because you're using the Orcal database, because Seata doesn't currently support the Oracle database.

**Comment by asdadmin01** [comment]
Using the following code snippet:

String sql = "select * from storage_tbl where id in (:ids)";
		Map parameters = new HashMap();
		parameters.put("ids", Arrays.asList(new Long[] { 17L, 18L }));
		NamedParameterJdbcTemplate namedParameterJdbcTemplate = new NamedParameterJdbcTemplate(jdbcTemplate);
		List<Storage> storages = namedParameterJdbcTemplate.query(sql, new MapSqlParameterSource(parameters), new BeanPropertyRowMapper<>(Storage.class));
		LOGGER.info("storages=>", storages);

and changed to MySQL，the issue cannot be reproduced. Perhaps only Oracle database is affected.

When initParameterHolder() of AbstractPreparedStatementProxy.java executed, 
sql is converted to :
select * from storage_tbl where id in (?, ?)

![1](https://user-images.githubusercontent.com/44864991/55799072-17923c80-5b03-11e9-9dfa-186c80e0edb9.png)

and paramCount is set to 2, on ploblem.

![debug(mysql)](https://user-images.githubusercontent.com/44864991/55798640-098fec00-5b02-11e9-97ce-a8623acfd132.png)
