### ISSUE TITLE
AbstractBranchEndRequest encode NullPointerException

### ISSUE THREAD

**Issue by qqqlllei** [seata/seata#752]
seata version 0.4.1 
FileTransactionStoreManager Store branchSession , branchType  is null

**Comment by zhangthen** [comment]
What is version of  fescar-spring? It shoud be 0.4.1 too.

**Comment by qqqlllei** [comment]
My client configuration

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-fescar</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.fescar</groupId>
                    <artifactId>fescar-spring</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.alibaba.fescar</groupId>
            <artifactId>fescar-spring</artifactId>
            <version>0.4.1</version>
        </dependency>

**Comment by zhangthen** [comment]
> My client configuration
> 
> ```
>     <dependency>
>         <groupId>org.springframework.cloud</groupId>
>         <artifactId>spring-cloud-starter-alibaba-fescar</artifactId>
>         <exclusions>
>             <exclusion>
>                 <groupId>com.alibaba.fescar</groupId>
>                 <artifactId>fescar-spring</artifactId>
>             </exclusion>
>         </exclusions>
>     </dependency>
> 
>     <dependency>
>         <groupId>com.alibaba.fescar</groupId>
>         <artifactId>fescar-spring</artifactId>
>         <version>0.4.1</version>
>     </dependency>
> ```

What is the exception stack  ?

**Comment by qqqlllei** [comment]
> > My client configuration
> > ```
> >     <dependency>
> >         <groupId>org.springframework.cloud</groupId>
> >         <artifactId>spring-cloud-starter-alibaba-fescar</artifactId>
> >         <exclusions>
> >             <exclusion>
> >                 <groupId>com.alibaba.fescar</groupId>
> >                 <artifactId>fescar-spring</artifactId>
> >             </exclusion>
> >         </exclusions>
> >     </dependency>
> > 
> >     <dependency>
> >         <groupId>com.alibaba.fescar</groupId>
> >         <artifactId>fescar-spring</artifactId>
> >         <version>0.4.1</version>
> >     </dependency>
> > ```
> 
> What is the exception stack ?
> What 's version of fescar-server, it shoud be 0.4.1 too .

java.lang.NullPointerException: null
  at com.alibaba.fescar.core.protocol.transaction.AbstractBranchEndRequest.encode(AbstractBranchEndRequest.java:172)
  at com.alibaba.fescar.core.rpc.netty.MessageCodecHandler.encode(MessageCodecHandler.java:85)
  at com.alibaba.fescar.core.rpc.netty.MessageCodecHandler.encode(MessageCodecHandler.java:39)
  at io.netty.handler.codec.ByteToMessageCodec$Encoder.encode(ByteToMessageCodec.java:172)
  at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
  at io.netty.handler.codec.ByteToMessageCodec.write(ByteToMessageCodec.java:108)
  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
  at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
  at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
  at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
  at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128)
  at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:745)


reload branchSession from file 这 branchSession  branchType is null
![image](https://user-images.githubusercontent.com/12453448/55861152-5d551080-5ba8-11e9-87bd-dc38832daebe.png)

**Comment by zhangthen** [comment]
The version of fescar-server shoud be 0.4.1 too .

**Comment by qqqlllei** [comment]
> The version of fescar-server shoud be 0.4.1 too .

  <parent>
        <artifactId>fescar-all</artifactId>
        <groupId>com.alibaba.fescar</groupId>
        <version>0.4.1</version>
    </parent>

The latest code I use 
![image](https://user-images.githubusercontent.com/12453448/55861566-3519e180-5ba9-11e9-961a-fe91b59ab3dd.png)

**Comment by leizhiyuan** [comment]
maybe it has been fixed, please retest it based on develop branch
