### ISSUE TITLE
The fescar server died while it was in the global transaction

### ISSUE THREAD

**Issue by phamtai97** [seata/seata#770]
I have a scenario:
Service A and Service B manage value A, B.
A = 100.
B = 100.

Begin global transaction
- Update value A = A - 100  => A = 0
- Fescar server is died while global transaction does not end. Service A and service B will retry connect with fescar server.

Then, I check value A in DB, result is A = 0. Value A is changed when transaction is not success.

After I restart fescar server, I see log:

```
2019-04-11 17:14:38.401 INFO [RetryRollbacking_1]com.alibaba.fescar.server.coordinator.DefaultCore.doGlobalRollback:282 -Exception rollbacking branch BR:2008699216/2008699215
java.lang.RuntimeException: rm client is not connected. dbkey:jdbc:mysql://127.0.0.1:3306/account_service?useSSL=false&serverTimezone=UTC,clientId:account_service:172.24.22.199:58600
	at com.alibaba.fescar.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:217)
	at com.alibaba.fescar.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:236)
	at com.alibaba.fescar.server.coordinator.DefaultCoordinator.branchRollback(DefaultCoordinator.java:180)
	at com.alibaba.fescar.server.coordinator.DefaultCore.doGlobalRollback(DefaultCore.java:260)
	at com.alibaba.fescar.server.coordinator.DefaultCoordinator.handleRetryRollbacking(DefaultCoordinator.java:224)
	at com.alibaba.fescar.server.coordinator.DefaultCoordinator.access$000(DefaultCoordinator.java:70)
	at com.alibaba.fescar.server.coordinator.DefaultCoordinator$1.run(DefaultCoordinator.java:278)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2019-04-11 17:14:38.402 INFO [RetryRollbacking_1]com.alibaba.fescar.core.rpc.ChannelManager.getChannel:339 -No channel is available for resource[jdbc:mysql://127.0.0.1:3306/account_service?useSSL=false&serverTimezone=UTC]
```
I think value A needs to be rolled back in this case.

`Version fescar server: 0.4.1`

**Comment by slievrly** [comment]
@phamtai97 I will check,If convenient, please dingTalk ping me.

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
