### ISSUE TITLE
com.alibaba.fescar.common.exception.FrameworkException: register error,role:RMROLE,err

### ISSUE THREAD

**Issue by airufei** [seata/seata#85]
ERROR com.alibaba.fescar.core.rpc.netty.RmRpcClient - 0304
com.alibaba.fescar.common.exception.FrameworkException: register error,role:RMROLE,err:cost 75789 ms
	at com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:83)
	at com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:41)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.doConnect(RmRpcClient.java:354)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.connect(RmRpcClient.java:322)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.reconnect(RmRpcClient.java:204)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.access$000(RmRpcClient.java:65)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient$1.run(RmRpcClient.java:153)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

**Comment by slievrly** [comment]
can you paste fescar-server startup cmd and client's application.conf

**Comment by leizhiyuan** [comment]
please use the latest code to test it again, thank you.

because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
