### ISSUE TITLE
rm client is not connected after rm restart

### ISSUE THREAD

**Issue by dreamoftch** [seata/seata#895]
Ⅰ. Issue Description

i have checked and is not the same with [issue680](https://github.com/seata/seata/issues/680)

i am testing exception case based on seata version 0.5.0 and my scenario is like this:
```
void doInGlobalTransaction() {
    serviceA.execute()
    serviceB.execute()
}
```
and code in `serviceB.execute()` looks like this:
```
void execute() {
    jdbcTemplate.update("update user2 set name = 'xxx' where id = 1")
    // mock system crash
    System.exit(1)
}
```
which means all db operations in global transaction has finished, but serviceB crashed.

when i restart serviceB, the seata server(TC) keeps log the error below:
```
java.lang.RuntimeException: rm client is not connected. dbkey:jdbc:mysql://localhost:3307/test2,clientId:my_test_app2:127.0.0.1:53790
  at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:218)
  at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:237)
  at io.seata.server.coordinator.DefaultCoordinator.branchRollback(DefaultCoordinator.java:185)
  at io.seata.server.coordinator.DefaultCore.doGlobalRollback(DefaultCore.java:267)
  at io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking(DefaultCoordinator.java:229)
  at io.seata.server.coordinator.DefaultCoordinator.access$000(DefaultCoordinator.java:73)
  at io.seata.server.coordinator.DefaultCoordinator$1.run(DefaultCoordinator.java:283)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:745)
2019-04-24 17:10:48.037 INFO [RetryRollbacking_1]io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking:231 -Failed to retry rollbacking [2009824946] Unknown java.lang.RuntimeException: rm client is not connected. dbkey:jdbc:mysql://localhost:3307/test2,clientId:my_test_app2:127.0.0.1:53790
2019-04-24 17:10:48.038 INFO 
```

i checked the source code in TC, it seems that TC will take `applicationId + (rm ip) + (rm port)` as the key of rm, but when rm restart, the rm port changed, i am not sure if this is normal? or i should have some configuration to make the rm port fixed?

**Comment by dreamoftch** [comment]
seems same with [issue881](https://github.com/seata/seata/issues/881)

**Comment by slievrly** [comment]
@dreamoftch fix #830 will be release on 0.6.0

**Comment by dreamoftch** [comment]
actually i mean the TC take `applicationId + (rm ip) + (rm port)` as the identity of the rm, but rm port will change after restart

**Comment by wuzunqian** [comment]
I have a problem looks like this issue: I keep send request by jmeter, and restart TC, I get the same log "java.lang.RuntimeException: rm client is not connected.", can not get channel below code: io.seata.core.rpc.netty.RpcServer#sendSyncRequest(java.lang.String, java.lang.String, java.lang.Object, long), i debug and found channel sometimes is null and sometimes is not null with the same resourceid and clientip

**Comment by dreamoftch** [comment]
邮件已收到！谢谢
