### ISSUE TITLE
rpc timeout

### ISSUE THREAD

**Issue by Hccccccccccc** [seata/seata#912]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
rollback rpc timeout

### Ⅱ. Describe what happened
org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is java.sql.SQLException: com.alibaba.fescar.core.exception.TransactionException: RPC Timeout
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:332)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:746)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:533)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:304)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at com.alibaba.fescar.spring.annotation.GlobalTransactionalInterceptor$2.execute(GlobalTransactionalInterceptor.java:106)
	at com.alibaba.fescar.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:66)
	at com.alibaba.fescar.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:103)
	at com.alibaba.fescar.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:75)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.eoyin.rent.web.CollectionController$$EnhancerBySpringCGLIB$$5d294281.test(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: com.alibaba.fescar.core.exception.TransactionException: RPC Timeout
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.recognizeLockKeyConflictException(ConnectionProxy.java:126)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:175)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:152)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:329)
	... 67 more
Caused by: com.alibaba.fescar.core.exception.TransactionException: RPC Timeout
	at com.alibaba.fescar.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:73)
	at com.alibaba.fescar.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:97)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:194)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:173)
	... 69 more
Caused by: java.util.concurrent.TimeoutException: cost 30001 ms
	at com.alibaba.fescar.core.protocol.MessageFuture.get(MessageFuture.java:59)
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemoting.sendAsyncRequest(AbstractRpcRemoting.java:264)
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemoting.sendAsyncRequestWithResponse(AbstractRpcRemoting.java:194)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.sendMsgWithResponse(RmRpcClient.java:199)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.sendMsgWithResponse(RmRpcClient.java:220)
	at com.alibaba.fescar.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:67)
	... 72 more

![image](https://user-images.githubusercontent.com/34225515/56782847-81a52400-681b-11e9-96cb-0f04fd094ca3.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS :  windows 10
- Others:

**Comment by eoyin** [comment]
spring boot

**Comment by xingfudeshi** [comment]
Can you please provide a demo that reproduces this bug.thanks.

**Comment by eoyin** [comment]
> Can you please provide a demo that reproduces this bug.thanks.

![image](https://user-images.githubusercontent.com/34225515/56805126-948b1900-685a-11e9-92f2-be76a3845375.png)
![image](https://user-images.githubusercontent.com/34225515/56805174-c56b4e00-685a-11e9-81db-7ecf9326b7d5.png)
sorry ,my english is no very good 
i can't provide demo ,but i can provide two screenshots,
give fisrt screenshot alias  A service 
give second screenshot alias B service
the A service transfer xid to B service
B servcie can get xid
the transaction rollback success,but rpc time out 
i don't known where the problem is.
A service{
frame: mybatis-plus 3.x
          spring-boot 2.x
   
}
B service{
frame: spring-jpa 2.x
          spring-boot 2.x
}

**Comment by eoyin** [comment]
i found mybatis-plus unable use jdbcTransactionFactory
maybe....

**Comment by eoyin** [comment]
nono   maybe transaction not commit,yes    and   undo_log not have data

**Comment by slievrly** [comment]
branchRegistry error, please upgrade version.

**Comment by eoyin** [comment]
my fescar version is 0.5.0，is the latest




------------------ 原始邮件 ------------------
发件人: "jimin"<notifications@github.com>; 
发送时间: 2019年4月29日(星期一) 晚上9:09
收件人: "seata/seata"<seata@noreply.github.com>; 
抄送: "201565550392 何超"<466589487@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [seata/seata] rpc timeout (#912)




branchRegistry error, please upgrade version.

**Comment by hero-zhanghao** [comment]
Same question, I upgraded seata-server from 0.5.0 to 0.5.1, same error

**Comment by eoyin** [comment]
already updated,at the same time, i found the new question , i have three services,if a service throw exception, the seata-server can't recevid error,can't rollback,seate-server only recevid two message by two service




------------------ 原始邮件 ------------------
发件人: "hero-zhanghao"<notifications@github.com>; 
发送时间: 2019年5月5日(星期天) 下午3:31
收件人: "seata/seata"<seata@noreply.github.com>; 
抄送: "201565550392 何超"<466589487@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [seata/seata] rpc timeout (#912)




Same question, I upgraded seata-server from 0.5.0 to 0.5.1, same error

**Comment by hero-zhanghao** [comment]
I found that the version of my seata-spring was 0.4.2. After I switched the version of seata-server to 0.4.2, the error disappeared

**Comment by eoyin** [comment]
> a

Why don't you use the latest version?

**Comment by eoyin** [comment]
> I found that the version of my seata-spring was 0.4.2. After I switched the version of seata-server to 0.4.2, the error disappeared

Why don't you use the latest version?

**Comment by eoyin** [comment]
> I found that the version of my seata-spring was 0.4.2. After I switched the version of seata-server to 0.4.2, the error disappeared

0.4.2？all?

**Comment by hero-zhanghao** [comment]
Because I am using spring cloud alibaba, the latest version is 0.9.0, while the seata version applied in it is 0.4.2

**Comment by eoyin** [comment]
i just use spring-boot
  




------------------ 原始邮件 ------------------
发件人: "hero-zhanghao"<notifications@github.com>; 
发送时间: 2019年5月9日(星期四) 上午10:59
收件人: "seata/seata"<seata@noreply.github.com>; 
抄送: "201565550392 何超"<466589487@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [seata/seata] rpc timeout (#912)




Because I am using spring cloud alibaba, the latest version is 0.9.0, while the seata version applied in it is 0.4.2

**Comment by leizhiyuan** [comment]
please use the latest version ， The bug has been fixed
