### ISSUE TITLE
performance in rpc client connect mananger

### ISSUE THREAD

**Issue by leizhiyuan** [seata/seata#927]
## Why you need it?

the connect manager will block the requests when concurrent  is very high.  If you run the demo with 2 threads .  maybe you can see some timeout exception

```

        final ExecutorService executorService = Executors.newFixedThreadPool(2);

        for (int i = 0; i < 10; i++) {
            executorService.submit(new Runnable() {
                @Override
                public void run() {
                    try {
                        business.purchase("U100001", "C00321", 2);
                    } catch (Throwable e) {
                        e.printStackTrace();
                    }
                }
            });

            try {
                Thread.sleep(50);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
```

now the 
```
   channelToServer = nettyClientKeyPool.borrowObject(poolKeyMap.get(serverAddress));
```

borrow timeout is 60s. conn number is 2，It is too long, in this scene, you will see some timeout exception, and 
some stack like below, the biz process wait for this lock，
 
```
"rpcDispatch_RMROLE_7_8" #74 daemon prio=5 os_prio=31 tid=0x00007fdf79830800 nid=0xb803 waiting for monitor entry [0x000070000b4b3000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at io.seata.core.rpc.netty.RmRpcClient.connect(RmRpcClient.java:282)
	- waiting to lock <0x00000006c06c2b40> (a java.lang.Object)
	at io.seata.core.rpc.netty.RmRpcClient.sendResponse(RmRpcClient.java:407)
	at io.seata.core.rpc.netty.RmMessageListener.handleBranchRollback(RmMessageListener.java:83)
	at io.seata.core.rpc.netty.RmMessageListener.onMessage(RmMessageListener.java:70)
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.dispatch(AbstractRpcRemotingClient.java:333)
	at io.seata.core.rpc.netty.AbstractRpcRemoting$3.run(AbstractRpcRemoting.java:365)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

"rpcDispatch_RMROLE_6_8" #73 daemon prio=5 os_prio=31 tid=0x00007fdf7e0da800 nid=0x14703 waiting for monitor entry [0x000070000b3b0000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at io.seata.core.rpc.netty.RmRpcClient.connect(RmRpcClient.java:282)
	- waiting to lock <0x00000006c06c2b40> (a java.lang.Object)
	at io.seata.core.rpc.netty.RmRpcClient.sendResponse(RmRpcClient.java:407)
	at io.seata.core.rpc.netty.RmMessageListener.handleBranchCommit(RmMessageListener.java:101)
	at io.seata.core.rpc.netty.RmMessageListener.onMessage(RmMessageListener.java:68)
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.dispatch(AbstractRpcRemotingClient.java:333)
	at io.seata.core.rpc.netty.AbstractRpcRemoting$3.run(AbstractRpcRemoting.java:365)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)


"timeoutChecker_1" #26 daemon prio=5 os_prio=31 tid=0x00007fdf7992e000 nid=0x9a03 in Object.wait() [0x0000700008a35000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1159)
	- locked <0x000000076bb87058> (a org.apache.commons.pool.impl.GenericKeyedObjectPool$Latch)
	at io.seata.core.rpc.netty.RmRpcClient.doConnect(RmRpcClient.java:314)
	at io.seata.core.rpc.netty.RmRpcClient.connect(RmRpcClient.java:282)
	- locked <0x00000006c06c2b40> (a java.lang.Object)
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.reconnect(AbstractRpcRemotingClient.java:350)
	at io.seata.core.rpc.netty.RmRpcClient$1.run(RmRpcClient.java:152)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

you can see  the stack of DubboStorageServiceStarter,there are so many blocks
[lock.log](https://github.com/seata/seata/files/3123639/lock.log)

connection is ok. 

![image](https://user-images.githubusercontent.com/2684384/56846700-c48ef680-6904-11e9-9634-5081fec2b989.png)

## How it could be?

maybe we should implement better connection manager。

**Comment by slievrly** [comment]
Always use a long connection

**Comment by leizhiyuan** [comment]
> Always use a long connection

ok, maybe an exception scene of my local machine, I did not  reproduce it anymore.
