### ISSUE TITLE
eureka register error

### ISSUE THREAD

**Issue by hero-zhanghao** [seata/seata#946]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

I used eureka as the registry, but when the project was started, the project kept reporting errors repeatedly. I could not find the documents and examples related to eureka, and I did not know whether it was my configuration error. The following is my configuration:

**seata-server:**
    **registry.conf：** 

registry {
  type = "eureka"

  nacos {
    serverAddr = "localhost"
    namespace = "public"
    cluster = "default"
  }
  eureka {
    serviceUrl = "http://localhost:8189/eureka"
    application = "seata"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = "0"
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
  }
  file {
    name = "file.conf"
  }
}

config {
  type = "file"

  nacos {
    serverAddr = "localhost"
    namespace = "public"
    cluster = "default"
  }
  apollo {
    app.id = "seata-server"
    apollo.meta = "http://192.168.1.204:8801"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  file {
    name = "file.conf"
  }
}

**serivce-server：**
     **registry.conf：**

      registry {
  type = "eureka"

  eureka {
    serviceUrl = "http://localhost:8189/eureka"
    application = "seata"
    weight = "1"
  }
  file {
    name = "file.conf"
  }
}

        **file.conf：** 
service {
  vgroup_mapping.service-module-user-fescar-service-group = "service-module-user"
  service-module-user.grouplist = "127.0.0.1:8091"
  enableDegrade = false
  disable = false
}

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```

 04-29 21:11:26.544 ERROR [-,,,] 13448 --- [imeoutChecker_1] c.a.f.c.r.n.AbstractRpcRemotingClient    : 0101

com.alibaba.fescar.common.exception.FrameworkException: can not register TM,err:register error,role:TMROLE,err:cost 30003 ms
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient.doConnect(TmRpcClient.java:349)
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient.connect(TmRpcClient.java:281)
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingClient.reconnect(AbstractRpcRemotingClient.java:348)
	at com.alibaba.fescar.core.rpc.netty.TmRpcClient$1.run(TmRpcClient.java:164)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.  Able to resolve exceptions

### Ⅵ. Environment:

- JDK version :8
- OS : winodws
- Others:

**Comment by vikenlove** [comment]
vgroup_mapping.service-module-user-fescar-service-group = "service-module-user" 

 the value is  default

**Comment by xingfudeshi** [comment]
did you start your eureka on port 8189?in addition,please upgrade the version of seata to latest.

**Comment by xingfudeshi** [comment]
Make sure the server and client configurations are consistent.

**Comment by hero-zhanghao** [comment]
I'm sure eureka is on and the port is 8189, and my version of eureka is spring cloud alibaba seata: 0.9.0

**Comment by hero-zhanghao** [comment]
I think this issue is out of date and I have resolved the configuration and launched successfully
