### ISSUE TITLE
RM restart leads to rollback fail

### ISSUE THREAD

**Issue by hongwenyan** [seata/seata#957]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

When I set a debug point before rollback , then restart an RM dubbo service, the glableSession would never be able to rollback, it throw an exception:

### Ⅱ. Describe what happened

```
2019-04-30 18:00:33.218 ERROR[RetryRollbacking_1]io.seata.server.coordinator.DefaultCore.doGlobalRollback:290 -Exception rollbacking branch BR:2010346321/2010346316
io.seata.core.exception.TransactionException: 2010346321/192.168.0.65:8091:2010346316
	at io.seata.server.coordinator.DefaultCoordinator.branchRollback(DefaultCoordinator.java:191)
	at io.seata.server.coordinator.DefaultCore.doGlobalRollback(DefaultCore.java:267)
	at io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking(DefaultCoordinator.java:229)
	at io.seata.server.coordinator.DefaultCoordinator.access$000(DefaultCoordinator.java:73)
	at io.seata.server.coordinator.DefaultCoordinator$1.run(DefaultCoordinator.java:283)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException: cost 30003 ms
	at io.seata.core.protocol.MessageFuture.get(MessageFuture.java:59)
	at io.seata.core.rpc.netty.AbstractRpcRemoting.sendAsyncRequest(AbstractRpcRemoting.java:269)
	at io.seata.core.rpc.netty.AbstractRpcRemoting.sendAsyncRequestWithResponse(AbstractRpcRemoting.java:199)
	at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:222)
	at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:237)
	at io.seata.server.coordinator.DefaultCoordinator.branchRollback(DefaultCoordinator.java:185)
	... 13 common frames omitted
2019-04-30 18:00:33.219 INFO [RetryRollbacking_1]io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking:231 -Failed to retry rollbacking [2010346316] Unknown io.seata.core.exception.TransactionException: 2010346321/192.168.0.65:8091:2010346316
2019-04-30 18:00:33.220 INFO [RetryRollbacking_1]io.seata.core.rpc.ChannelManager.getChannel:379 -Choose [id: 0x8c12e839, L:/127.0.0.1:8091 - R:/127.0.0.1:53828] on the same IP[127.0.0.1]  as alternative of dubbo-demo-account-service:127.0.0.1:40555
```

Then I restart the seata-server, but it keep throwing exception because it could not get the Channel from ChannelManager:

```
java.lang.RuntimeException: rm client is not connected. dbkey:jdbc:mysql://192.168.0.211:3306/......,clientId:......
	at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:218)
	at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:237)
	at io.seata.server.coordinator.DefaultCoordinator.branchRollback(DefaultCoordinator.java:185)
	at io.seata.server.coordinator.DefaultCore.doGlobalRollback(DefaultCore.java:267)
	at io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking(DefaultCoordinator.java:229)
	at io.seata.server.coordinator.DefaultCoordinator.access$000(DefaultCoordinator.java:73)
	at io.seata.server.coordinator.DefaultCoordinator$1.run(DefaultCoordinator.java:283)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

### Ⅲ. Describe what you expected to happen

I want the globalSession to be rollback when I restart the closed dubbo service after registerRMChannel.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. TM: After having all RM invoked, Set a debug point before throw an exception
2. RM: Close an RM dubbo service which should be roleback before execution 
3. Restart the closed service, but it could not rollback

### Ⅵ. Environment:

- JDK version :1.8
- OS :windows10
- Others:

**Comment by CoffeeLatte007** [comment]
it fixed on version 0.5.1
